### ISSUE TITLE
Requests to  `cert/.../raw` fail for no reason

### ISSUE THREAD

**Issue by con-f-use** [hashicorp/vault#22688] opened 2023-08-31 14:46 UTC
The [API documentation](https://developer.hashicorp.com/vault/api-docs/secret/pki#read-certificate) and [its note](https://developer.hashicorp.com/vault/api-docs/secret/pki#vault-cli-with-der-pem-responses) seem to imply that `curl https://<vault_url>/v1/<pki_name>/cert/ca/raw --output -` should work. Yet, I get `{"errors":["unsupported path"]}` in response. The request without `raw` in the end of the URL succeeds.

![image](https://github.com/hashicorp/vault/assets/11145016/2d204ef4-efe1-44d9-8103-69fd3a74141b)

This is on vault version 1.12.2.

**Comment by cipherboy** [comment] 2023-08-31 18:21
@con-f-use This is weird! I've tried 1.15.x, 1.12.10, and now 1.12.2 and haven't been able to reproduce it:

<details>

<summary>Attempted reproduction on 1.12.2</summary>

```
[cipherboy@xps15 vault]$ source devvault && vault secrets enable pki && vault write pki/root/generate/internal key_type=ec common_name="Root R1"
++ mkdir -p /home/cipherboy/devvault
++ truncate -s 0 /home/cipherboy/devvault/vault.log /home/cipherboy/devvault/audit.log
++ echo '
telemetry {
  usage_gauge_period = "5s"
  prometheus_retention_time = "24h"
  disable_hostname = true
}

raw_storage_endpoint = true
'
++ chmod 600 /home/cipherboy/devvault/audit.log /home/cipherboy/devvault/audit-secondary.log /home/cipherboy/devvault/ca.crt /home/cipherboy/devvault/chain.pem /home/cipherboy/devvault/client-key.pem /home/cipherboy/devvault/client.pem /home/cipherboy/devvault/config-1.hcl /home/cipherboy/devvault/config-2.hcl /home/cipherboy/devvault/config-3.hcl /home/cipherboy/devvault/config-4.hcl /home/cipherboy/devvault/config-5.hcl /home/cipherboy/devvault/config-6.hcl /home/cipherboy/devvault/config.hcl /home/cipherboy/devvault/config-secondary.hcl /home/cipherboy/devvault/dhparams.pem /home/cipherboy/devvault/service-key.pem /home/cipherboy/devvault/service.pem /home/cipherboy/devvault/softhsm2 /home/cipherboy/devvault/storage /home/cipherboy/devvault/vault.log /home/cipherboy/devvault/vault-secondary.log /home/cipherboy/devvault/yubihsm2-debug.log /home/cipherboy/devvault/yubihsm.conf
++ chmod 700 /home/cipherboy/devvault
++ ls --color=auto --group-directories-first /home/cipherboy/devvault/softhsm2/ /home/cipherboy/devvault/storage/
++ chmod 700 /home/cipherboy/devvault/softhsm2/ /home/cipherboy/devvault/storage/
+++ pgrep -f 'vault server -dev'
++ past_instances=633113
++ '[' -n 633113 ']'
++ kill 633113
++ sleep 1
==> Vault shutdown triggered
++ for _ in {1..10}
++ nc -w 1 localhost 8200
++ vault server -dev -log-level=trace -config=/home/cipherboy/devvault/config.hcl -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=devroot
++ sleep 1
==> Vault server configuration:

             Api Address: http://0.0.0.0:8200
                     Cgo: disabled
         Cluster Address: https://0.0.0.0:8201
              Go Version: go1.20.7
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: trace
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: inmem
                 Version: Vault v1.12.2, built 2022-11-23T12:53:46Z
             Version Sha: 415e1fe3118eebd5df6cb60d13defdc01aa17b03+CHANGES

==> Vault server started! Log data will stream in below:

WARNING! dev mode is enabled! In this mode, Vault runs entirely in-memory
and starts unsealed with a single unseal key. The root token is already
authenticated to the CLI, so you can immediately begin using Vault.

You may need to set the following environment variables:

    $ export VAULT_ADDR='http://0.0.0.0:8200'

The unseal key and root token are displayed below in case you want to
seal/unseal the Vault or re-authenticate.

Unseal Key: Nrwquty2soi9u4zXJjzmktXnsHJ3A4MlkVskRl/s+s0=
Root Token: devroot

Development mode should NOT be used in production installations!

++ for _ in {1..10}
++ nc -w 1 localhost 8200
++ break
export VAULT_ADDR=http://localhost:8200
export VAULT_TOKEN=devroot
Success! Enabled the file audit device at: file/
Success! Enabled the pki secrets engine at: pki/
WARNING! The following warnings were returned from Vault:

  * This mount hasn't configured any authority information access (AIA)
  fields; this may make it harder for systems to find missing certificates
  in the chain or to validate revocation status of certificates. Consider
  updating /config/urls or the newly generated issuer with this information.

Key              Value
---              -----
certificate      -----BEGIN CERTIFICATE-----
MIIBiDCCAS+gAwIBAgIUfcpKhJit9EAb4VTlyj9EJxZmHv4wCgYIKoZIzj0EAwIw
EjEQMA4GA1UEAxMHUm9vdCBSMTAeFw0yMzA4MzExODEwMDhaFw0yMzEwMDIxODEw
MzhaMBIxEDAOBgNVBAMTB1Jvb3QgUjEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AAQtl/DkSlehgE7eRaZyvPE5wi5m+nTFe4mvfUmLL693aDbxHxd6F86PrsaO7Is7
/XJMtr5JPx5b72Bih6Es8WQ7o2MwYTAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/
BAUwAwEB/zAdBgNVHQ4EFgQUx5PSNW4Xsok5RrBBneA2jl8CyFcwHwYDVR0jBBgw
FoAUx5PSNW4Xsok5RrBBneA2jl8CyFcwCgYIKoZIzj0EAwIDRwAwRAIgZJxZkc60
JOC3PfMN5/Yi32tnQYl3RIpgiY+fHg2jOZ0CIACMZ7VTqoKU/wUd6gLSwkq/zAAP
V4C6IfG5sjZWnNRh
-----END CERTIFICATE-----
expiration       1696270238
issuer_id        a0221767-0cfe-2040-59f6-ed5727c7c706
issuer_name      n/a
issuing_ca       -----BEGIN CERTIFICATE-----
MIIBiDCCAS+gAwIBAgIUfcpKhJit9EAb4VTlyj9EJxZmHv4wCgYIKoZIzj0EAwIw
EjEQMA4GA1UEAxMHUm9vdCBSMTAeFw0yMzA4MzExODEwMDhaFw0yMzEwMDIxODEw
MzhaMBIxEDAOBgNVBAMTB1Jvb3QgUjEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AAQtl/DkSlehgE7eRaZyvPE5wi5m+nTFe4mvfUmLL693aDbxHxd6F86PrsaO7Is7
/XJMtr5JPx5b72Bih6Es8WQ7o2MwYTAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/
BAUwAwEB/zAdBgNVHQ4EFgQUx5PSNW4Xsok5RrBBneA2jl8CyFcwHwYDVR0jBBgw
FoAUx5PSNW4Xsok5RrBBneA2jl8CyFcwCgYIKoZIzj0EAwIDRwAwRAIgZJxZkc60
JOC3PfMN5/Yi32tnQYl3RIpgiY+fHg2jOZ0CIACMZ7VTqoKU/wUd6gLSwkq/zAAP
V4C6IfG5sjZWnNRh
-----END CERTIFICATE-----
key_id           10fbad82-d384-5401-6545-5f7d59b76796
key_name         n/a
serial_number    7d:ca:4a:84:98:ad:f4:40:1b:e1:54:e5:ca:3f:44:27:16:66:1e:fe
[cipherboy@xps15 vault]$ curl http://localhost:8200/v1/pki/cert/ca/raw --output -
0��0�/�}�J����@T��?D'f�0
231002181038Z010URoot R10Y0*�H�*�H�=B-���JW��N�E�r��9�.f�t�{��}I�/�wh6�zΏ�Ǝ�;�rL��I?[�`b��,�d;�c0a0U�0U�0�0UǓ�5n��9F�A��6�_�W0U#0�Ǔ�5n��9F�A��6�_�W0
�9� �g�S�������J��W��!�6V��a[cipherboy@xps15 vault]$ 
```

(Note I rebuilt Vault 1.12.2 fresh for this rather than using the release binary but I imagine it should be the same...)

</details>

This was added back in the v1.10.x cycle...  When I use an invalid path I get two different behaviors:

```
[cipherboy@xps15 changelog]$ curl http://localhost:8200/v1/pki/certs/ca/raw --output -
{"errors":["permission denied"]}
[cipherboy@xps15 changelog]$ curl http://localhost:8200/v1/pki/cert/casdfa/raw --output -
{"errors":["unsupported path"]}
[cipherboy@xps15 changelog]$ curl http://localhost:8200/v1/pki/cert/ca/raws --output -
{"errors":["unsupported path"]}
```

The former error is returned when the path is not registered as matching the unauthenticated prefix (as the request lacks authorization and isn't what you're seeing), the latter when the prefix matches but the path is unknown (not assigned to a handler), but is what you're seeing...

Do you mind sharing [audit log entries](https://developer.hashicorp.com/vault/docs/commands/audit/enable#examples) for this request?

Also, what does `vault path-help qaca` return? The latter might indicate something is weird with the route?

**Comment by hsimon-hashicorp** [comment] 2023-11-04 01:01
Hello @con-f-use. As it has been some time since we've heard from you, I'm going to go ahead and close this issue now. Please feel free to re-open it if you can provide more information. Thanks!

**Closed by hsimon-hashicorp** 2023-11-04 01:01 UTC
Labels: waiting-for-response, secret/pki
