### ISSUE TITLE
Needs to setup monitoring(alert system) around whenever vault gets sealed if restarted unless manually done through api or something like that .

### ISSUE THREAD

**Issue by divvy19** [hashicorp/vault#3734] opened 2017-12-26 13:20 UTC
**Environment:**

* Vault Version:
* Operating System/Architecture:

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**
Whenever the vault gets sealed , it should through an error .

**Actual Behavior:**
No idea about how to setup alert monitoring around that , one solution can be through vault api's but still not sure about how to do it .

**Steps to Reproduce:**

**Important Factoids:**
Trying to enable monitoring of the vault and consul servers whenever they go down . I am curious about how did you do that ?? Using some tool or api calls .
It would be great if you can help me out with this thing .
Any more comments around how to setup alert monitoring system around vault through anything will be helpful.
Thanks in advance.

**References:**
https://github.com/hashicorp/vault/issues/1585

**Comment by jefferai** [comment] 2017-12-26 18:30
Duplicate of https://groups.google.com/d/msg/vault-tool/vga3B1qgu_0/zOHr9suFBAAJ

**Closed by jefferai** 2017-12-26 18:30 UTC
