### ISSUE TITLE
AWS Auth backend for IAM user valid signature is not working

### ISSUE THREAD

**Issue by siddheshwar-more** [hashicorp/vault#3615] opened 2017-11-27 15:54 UTC
**Problem Statement -** 

I'm getting below error while triggering the vault write auth/aws/login role=dev-role-iam command- 

> Error writing data to auth/aws/login: Error making API request.
> 
> URL: PUT http://127.0.0.1:8200/v1/auth/aws/login
> Code: 400. Errors:
> 
> 
> > error making upstream request: received error code 403 from STS: <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
> >   <Error>
> >     <Type>Sender</Type>
> >     <Code>SignatureDoesNotMatch</Code>
> >     <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>
> >   </Error>
> >   <RequestId>c4aee143-d37c-11e7-9fd6-99a4a8d95498</RequestId>
> > </ErrorResponse>

**Command-** 
vault write auth/aws/login role=dev-role-iam \
        iam_http_request_method=POST \
        iam_request_url=aHR0cHM6Ly9zdHMuYW1hem9uYXdzLmNvbS8= \
        iam_request_body=QWN0aW9uPUdldENhbGxlcklkZW50aXR5JlZlcnNpb249MjAxMS0wNi0xNQ== \
        iam_request_headers=eyJBdXRob3JpemF0aW9uIjpbIkFXUzQtSE1BQy1TSEEyNTYgQ3JlZGVudGlhbD1BS0lNUlpTSjJRNFZBSUFBSktaRi8yMDE3MTEyNy91cy1lYXN0LTEvc3RzL2F3czRfcmVxdWVzdCwgU2lnbmVkSGVhZGVycz1jb250ZW50LWxlbmd0aDtjb250ZW50LXR5cGU7aG9zdDt4LWFtei1kYXRlO3gtdmF1bHQtYXdzLWlhbS1zZXJ2ZXItaWQsIFNpZ25hdHVyZT00YmZlMGMxNTMzZDQ2ODdiNTg5YjU5MzdlY2E4YTY1NzAzZGNiNTg2MTZlMmIzMmMyZjA5ZTRlZTI5MDVjYWRmIl0sIkNvbnRlbnQtTGVuZ3RoIjpbIjQzIl0sIkNvbnRlbnQtVHlwZSI6WyJhcHBsaWNhdGlvbi94LXd3dy1mb3JtLXVybGVuY29kZWQ7IGNoYXJzZXQ9dXRmLTgiXSwiVXNlci1BZ2VudCI6WyJhd3Mtc2RrLWdvLzEuMTIuMjMgKGdvMS45LjI7IGxpbnV4OyBhbWQ2NCkiXSwiWC1BbXotRGF0ZSI6WyIyMDE3MTEyN1QxNDA5MDFaIl0sIlgtVmF1bHQtQXdzLUlhbS1TZXJ2ZXItSWQiOlsidmF1bHQuZXhhbXBsZS5jb20iXX0=

{"Authorization":["AWS4-HMAC-SHA256 Credential=AKIMRZSJ2Q4VAIAAJKZF/20171127/us-east-1/sts/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-vault-aws-iam-server-id, Signature=4bfe0c1533d4687b589b5937eca8a65703dcb58616e2b32c2f09e4ee2905cadf"],"Content-Length":["43"],"Content-Type":["application/x-www-form-urlencoded; charset=utf-8"],"User-Agent":["aws-sdk-go/1.12.23 (go1.9.2; linux; amd64)"],"X-Amz-Date":["20171127T140901Z"],"X-Vault-Aws-Iam-Server-Id":["vault.example.com"]}

I'm using the signature generated using  -https://gist.github.com/blelump/9e6880a87fefa6397032#file-aws_signed_request_v4-rb-L74 

**Debugging for access_key/secrete_key** 
When I use the signature generated by vault then above command works fine (with same access_key/secrete_key) .
  to get the signature generated by vault for this command-    ./vault auth -method=aws header_value=vault.example.com role=dev-role-iam
I've putted some logs at https://github.com/hashicorp/vault/blob/master/builtin/credential/aws/cli.go#L71 and build the vault binary locally.

**Comment by joelthompson** [comment] 2017-12-04 07:11
Hi @siddheshwar-more,

It looks like the ruby code you linked to is intended as a sample of how to do request signing rather than a general library for use (e.g., for Vault). Taking a look quickly, I think there are a number of things preventing that ruby code sample from working to generate a valid signature in the Vault context:

* It uses an HTTP request method of `GET` (line 9) while Vault only supports `POST` (and, in fact, you have `iam_http_request_method=POST`). The HTTP request method is included inside the signature, so signing when expecting a GET request while actually sending a POST request will cause a signature validation error.
* It uses a `service` name (line 10) of `iam` instead of `sts` (line 10). Vault uses `sts:GetCallerIdentity` so it should be `sts` instead of `iam`. IIRC, this is also part of the signed request, and the discrepancy would cause a signature validation error.
* It has a `host` (line 11) of `iam.amazonaws.com` instead of `sts.amazonaws.com`. The host header is included in the signed request; further, your `iam_request_headers` variable doesn't include a `Host` header, so it'll default to (IIRC) sts.amazonaws.com, thus causing a signature mismatch.
* The `region` (line 12) is listed as `eu-west-1` -- while STS is a global service, I believe that unless an explicit region is specified, it expects a region of `us-east-1` and that'll also cause a signature mismatch error.
* The `request_parameters` variable (line 14) is off; it should be (I believe) `{ "Action" => "GetCallerIdentity", "Version" => "2011-06-15"}`

I don't know if you've adapted the gist for your own use or not, but these are the issues that immediately jumped out at me from my first glance. If this doesn't help, can you post the exact ruby code you're running as a gist?

Also, since this works using the official Vault CLI, that indicates it's not a bug with Vault itself, these types of discussions are best had on the [Vault mailing list](https://groups.google.com/group/vault-tool) where there are more people monitoring the discussion (e.g., I'm not a ruby expert) and can help you there. If you're still having difficulties, can you post updated details to the mailing list?

**Comment by krish7919** [comment] 2019-02-19 14:08
Try https://gist.github.com/krish7919/44d56dd8a77f3dee94d06b6f1662a8b4

**Comment by catsby** [comment] 2019-11-07 21:09
Hello - I'm going to close this issue for now; it does not seem to be an issue with Vault itself. If you have new information or feel strongly otherwise, please let us know by replying here. Thanks!

**Closed by catsby** 2019-11-07 21:09 UTC
