### ISSUE TITLE
Feature request: Support [command] passthrought to ssh in Vault

### ISSUE THREAD

**Issue by henti** [hashicorp/vault#1718] opened 2016-08-11 09:21 UTC
When using `vault ssh` to connect to vault managed OTP server, there is no way to send commands down the connection like supported by default in ssh. 

Please support this feature. 

I also saw some scp parts in the  vault/builtin/logical/ssh/communicator.go but cannot find any documentation. Is SCP supported ?

**Comment by jefferai** [comment] 2016-08-11 10:54
Duplicate of #1680

**Closed by jefferai** 2016-08-11 10:54 UTC
