### ISSUE TITLE
Some form of UEBA capabilities to differentiate between a manual and an automated API request

### ISSUE THREAD

**Issue by avineshwar** [hashicorp/vault#8476] opened 2020-03-04 21:55 UTC
**Is your feature request related to a problem? Please describe.**
`https://github.com/hashicorp/vault/issues/8461`

**Describe the solution you'd like**
Audit-backed enrichment is in-sufficient in this.

**Describe alternatives you've considered**
Correlation using machine logs.

**Comment by catsby** [comment] 2020-03-05 15:22
Hello @avineshwar - I'm going to close this issue as it's effectively a duplicate of https://github.com/hashicorp/vault/issues/8461. While #8461 is closed it is not locked, and you're welcome to add supporting information to further refine or advocate for your requested change. For example, proposing a solution that would satisfy your use case and be applicable to a number of Vault users could lead to re-opening the issue for consideration. 

Vault is designed with a client-server architecture; all interactions are over the HTTPS API. The audit log records all authenticate API requests/responses, including authentication tokens and lease information (which are hashed with a salt using HMAC-SHA256) as well as the `display_name` and other identifying information for the token used. That information can be used for an operator to know or determine if the interaction was likely from an actual human or not. 

Please reply on #8461 if you'd like to continue discussion on this. Thank you.

**Closed by catsby** 2020-03-05 15:22 UTC
