### ISSUE TITLE
"local node not active but active cluster node not found"

### ISSUE THREAD

**Issue by roy-work** [hashicorp/vault#20336] opened 2023-04-24 21:17 UTC
**Describe the bug**
```
/ $ vault login
Token (will be hidden):
Error authenticating: error looking up token: Error making API request.

URL: GET http://127.0.0.1:8200/v1/auth/token/lookup-self
Code: 500. Errors:

* local node not active but active cluster node not found
```

Vault itself logs nothing during that request.

I have no _idea_ what this error is trying to tell me. I presume "node" here refers to an instance of a Vault; I have no idea what would cause the local node to "not be active".

**To Reproduce**
1. ??? (mess something up; our etcd cluster was down a node at the time, but did have an elected leader.)
2. Run `vault login`
3. See error

**Expected behavior**
Either or both of:
* No error: a single etcd member being down should not affect Vault's availability
* A usable error message.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
   ```
   / $ vault status
   Key                      Value
   ---                      -----
   Recovery Seal Type       shamir
   Initialized              true
   Sealed                   false
   Total Recovery Shares    5
   Threshold                3
   Version                  1.11.3
   Build Date               2022-08-26T10:27:10Z
   Storage Type             etcd
   HA Enabled               true
   HA Cluster               n/a
   HA Mode                  standby
   Active Node Address      <none>
   ```
* Vault CLI Version (retrieve with `vault version`):
   ```
   Vault v1.11.3 (17250b25303c6418c283c95b1d5a9c9f16174fe8), built 2022-08-26T10:27:10Z
   ```
* Server Operating System/Architecture: Linux, GKE

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by maxb** [comment] 2023-04-25 09:24
You are running Vault in HA mode (shown in your `vault status` output) which means you have multiple running instances of the Vault server, communicating amongst themselves, using `etcd` as shared storage (again from the `vault status` output).

Only one running instance of Vault can write to the `etcd` storage at a time, as otherwise different nodes could make conflicting updates.

To enforce that, each Vault server instance tries to acquire a lock - which is represented as something inside the `etcd` storage, and the one that succeeds knows it can become active.

The remaining nodes remain in standby mode, and will forward requests to the active node for processing.

So now, your Vault instance is saying "I haven't managed to acquire the lock to allow me to become active, but neither can I see an advertisement from another node, written within the `etcd` storage, to tell me who is currently active, so I can't forward this request!".

The next step of debugging is to look at the Vault server error logging, for all nodes, possibly elevating logging levels to DEBUG or TRACE if necessary, to look for evidence explaining why none of the nodes are able to acquire the lock and become active.

**Comment by miagilepner** [comment] 2023-04-25 09:27
Hi, this error means that instance of Vault at http://127.0.0.1:8200 isn't the active node, but the cluster can't find another active node in the cluster. 

To confirm, are you using etcd v3?

I wasn't able to replicate this issue when killing just one etcd node in an etcd cluster. If you have reproduction steps that consistently show the problem, please share the steps and we can continue investigating.

**Comment by roy-work** [comment] 2023-04-26 00:44
> You are running Vault in HA mode (shown in your vault status output) which means you have multiple running instances of the Vault server, communicating amongst themselves, using etcd as shared storage (again from the vault status output).
>
> Only one running instance of Vault can write to the etcd storage at a time, as otherwise different nodes could make conflicting updates.

Hmm. I did not know Vault did some form of leader election, on top of etcd. (I would have expected etcd to be the mechanism by which conflicting writes were detected & avoided.)

> To confirm, are you using etcd v3?

Yes.

**Comment by maxb** [comment] 2023-04-26 08:10
> Hmm. I did not know Vault did some form of leader election, on top of etcd.

It's not really an election, it's just every Vault node tries to acquire an etcd lock, and whichever one succeeds becomes active.

> (I would have expected etcd to be the mechanism by which conflicting writes were detected & avoided.)

Vault server makes extensive use of in-memory data structures and processing that should happen at most once, so all of that is coordinated by Vault itself having only one active node at any one time.

**Comment by ipaqmaster** [comment] 2023-06-21 05:27
Had this issue on a single raft vault node this afternoon while provisioning a new raft-backed Vault cluster. This was before I had provisioned the other two. This single node entered a deadlocked state where it refused to leave standby mode. The other two were indefinitely trying to join the cluster which could never come up.

The only consistent thing was `local node not active but active cluster node not found` in the primary cluster member's logs and the message it was giving to the two other vault nodes who were trying to join. The single node did not want to start anymore.

Turns out through my configuration tweaking I accidentally set an invalid node_id through typo. It seems that single solo Vault node with everything on it had latched onto a typo `node_id` from /etc/vault.hcl which wasn't valid. But now that Vault had put it into vault.db, it was unable to start the cluster the next service restart. Vault had effectively killed itself by storing the wrong node_id in its cluster node information, expecting a second node who didn't exist.

This wrong node_id was visible when grepping for it in vault.db's binary data when it shouldn't be there at all.

By luck, the incorrect node_id that Vault's vault.db had latched onto was the same length as the correct node_id for this solo raft-backed vault node.

In a last resort to try and avoid starting all over again I:

1. Stopped the vault service
2. Ran `sed -i 's/wrongHostname/rightHostname/g' vault.db`
3. Started vault back up again 

The single-node cluster came good realising there was no second node to wait for and its own node_id was just missing due to the typo. After unsealing it the other two vault nodes who hadn't been configured yet were able to automatically join the cluster.

This is a common problem I run into with vault clusters where even though the correct settings are in /etc/vault.hcl, it's latched onto some other values and will never read those correct settings until the cluster comes up. This also means you can have a working cluster and introduce either bad or NEW settings which break the cluster from the next restart.

---------

This may not be the place for additional discussion of this issue... but this is a common problem I run into playing around with vault clusters in both staging and production environments. At this point it's a fear of mine it happens that often.

In the case of Vault configuration changes such as:
1. Renaming a vault cluster member's node_id
2. Upgrading a entire vault cluster to HTTPS
3. Renaming all host's in a vault cluster

There's a huge bootstrap paradox problem where Vault tries to start its storage cluster _before_ reading /etc/vault.hcl.

This means you can enter an invalid node_id and your vault node will come up successfully and only then will it will read that after using its old node_id as per vault.db.

It also means if something goes wrong during the bootstrapping of your cluster, say for example a TLS issue which may require you to back out - it's too late. The vault cluster is already configured to use HTTPS and will not read an updated /etc/vault.hcl reversing the change until _after_ the cluster comes up healthily.


In my case with this staging cluster I had accidentally set a bad node_id and my single-node cluster came up and then set the invalid node_id. Then I restarted it with the correct node_id in vault.hcl and the other two to-be vault nodes described as retry_join entries. But because of this vault.db hardcoding problem Vault gets stuck in this invalid startup state trying to cluster with a non-existent node instead of just reading /etc/vault.hcl and coming up.

This overall issue is very apparent when renaming a vault node or whole cluster of nodes. If the cluster can't come up, it will never read /etc/vault.hcl to update its node_id and peer details so just gets stuck.

 Given the nature of this problem it also means you can't stop, rename and bring a whole vault cluster back online because every single node will be trying to establish their storage backend connection using their old node_id's and old peer addresses's, which will never work. Even if you keep the old DNS entries to let that be possible, you'll also have to make sure each of their certs have Subject Alternate Names for both the old **and** new addresses without running into SSL errors. And if that vault cluster happens to be the source of your PKI for their certificates, god help you.

I've seen a handful of unanswered Vault community threads and github issues about this kind of "Sudden vault cluster startup death for no reason" problem due to the hardcoded database/peer data and I think it's a helpful pointer to let people know a Vault cluster won't read a valid vault.hcl until it successfully starts its existing cluster up with old details first.

**Comment by maxb** [comment] 2023-06-21 08:47
Hi @ipaqmaster,

I would agree that the knowledge needed to administer a Raft cluster in failure states is not clearly documented.

I have become an expert in this, mainly through experience and reading the source code.

I am totally not surprised that changing a node ID would cause the behaviour you observed. Changing a node ID is something that should **never** be done.

I have a question for you: why are you specifying the node ID in the first place? If you simply leave it out of the configuration file, Vault will automatically generate a UUID to use as the node ID, and store it as part of the data directory. This completely avoids human error scenarios setting the node ID.

As for your emergency binary surgery... there is a supported recovery mechanism for replacing the Raft peer set information at startup. If a file named `peers.json` exists in the data directory at startup, it will be read for replacement Raft peer information, which will be installed into the configuration, after which the `peers.json` file will be deleted. This is how an administrator is intended to recover from serious Raft outage scenarios which prevent the product coming online at all.

**Comment by maxb** [comment] 2023-06-21 08:50
We are substantially off-topic from @roy-work 's original etcd based issue report at this point.

I suggest that any follow-up discussion about Raft be taken to a separate GitHub issue, GitHub discussion, or https://discuss.hashicorp.com topic.

**Comment by hsimon-hashicorp** [comment] 2023-07-07 19:49
Hi @roy-work - have your questions been answered? If we are unable to reproduce the issue, I'd like to ahead and close it. We can always re-open it later if we need. Please let me know if we can be of further assistance. Thanks!

**Comment by hsimon-hashicorp** [comment] 2023-07-21 19:56
Closing this issue now - please re-open, or open a new issue as needed. Thank you!

**Closed by hsimon-hashicorp** 2023-07-21 19:56 UTC
Labels: waiting-for-response, ha/etcd

**Comment by wardob** [comment] 2023-09-13 08:43
Hello. I'm facing with a similar issue with Vault and etcd when etcd leader node is unexpectedly lost.
Vault version: 1.14.1. Two nodes in HA mode, running in k8s.
Etcd version: 3.5.9. Three nodes cluster, running on VM without any containerization.
Vault storage settings:
```
address: https://fqdn-etcd1:2379,https://fqdn-etcd2:2379,https://fqdn-etcd3:2379
etcd_api: v3
ha_enabled: true
path: some_path
request_timeout: 10s
sync: true
```
Steps to reproduce:
1. Emulate an unexpected loss of etcd leader (forcefully power off virtual machine or remove virtual network cable from virtual machine).
2. Make any request to Vault.
3. See logs.
In the Vault logs only the following messages: "context deadline exceeded".
The client request ends with either "context deadline exceeded" or "local node not active but active cluster node not found" message.
After approx 16 minutes in the both Vault nodes I see the following message in their logs: "error reading from server: read tcp vault_node_ip:33006->failed_etcd_node_ip:2379: read: connection timed out".
Also I see that the standby Vault acquire lock and become the active node.
After that the both Vault nodes return to normal work with remaining two etcd nodes.

**Comment by maxb** [comment] 2023-09-13 20:05
@wardob Rather than appending to an already-closed issue with significant meandering discussion, I think it would be better if you opened a new issue, where the specific abnormally slow recovery that you observed can be discussed without the unrelated conversation distracting from it.

**Comment by wtfloris** [comment] 2023-09-15 14:03
I am going to append this link, because this issue is the first result when you google the "local node not active error":

https://developer.hashicorp.com/vault/tutorials/raft/raft-lost-quorum

@maxb already mentioned the peers.json file recovery mechanism. This link describes how to do it and allowed me to recover a cluster that only had a single node left and became inoperable.

**Comment by Yatekii** [comment] 2024-01-09 11:21
I don't get this. I have 3 nodes to form a HA cluster. The active node is not reachable anymore and now my local node is like "ohwell, let's die too and completely disregard the purpose of HA". What do I misunderstand?
