### ISSUE TITLE
Vault cannot open audit log

### ISSUE THREAD

**Issue by beeradb** [hashicorp/vault#1736] opened 2016-08-15 20:13 UTC
I am trying to restore a failed vault instance with `recovery_mode = 1`, and Vault is reporting that it cannot read the audit log. However, the audit log location (/var/log/vault_audit.log) is (temporarily) set to 777, along with the /var and /var/log directories. After restoring vault, it reports that it cannot open that file for writing and exits immediately.

```
ubuntu@[ip-of-vault-instance]:~$ sudo -u vault /usr/bin/vault server -config /etc/vault/vault.conf
==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: dynamodb (HA available)
 Advertise Address: https:/[ip-of-vault-instance]
        Listener 1: tcp (addr: "0.0.0.0:8200", tls: "enabled")
           Version: Vault v0.5.2

==> Vault server started! Log data will stream in below:

2016/08/15 19:43:46 [INFO] core: vault is unsealed
2016/08/15 19:43:46 [INFO] core: entering standby mode
2016/08/15 19:43:48 [INFO] core: acquired lock, enabling active operation
2016/08/15 19:43:48 [INFO] core: post-unseal setup starting
2016/08/15 19:43:48 [INFO] core: mounted backend of type generic at secret/
2016/08/15 19:43:48 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/08/15 19:43:48 [INFO] core: mounted backend of type system at sys/
2016/08/15 19:43:48 [INFO] rollback: starting rollback manager
2016/08/15 19:45:19 [INFO] expire: restored 3315 leases
2016/08/15 19:45:21 [ERR] core: failed to create audit entry file/: sanity check failed; unable to open /var/log/vault_audit.log for writing
2016/08/15 19:45:21 [INFO] core: pre-seal teardown starting
2016/08/15 19:45:21 [INFO] rollback: stopping rollback manager
2016/08/15 19:45:21 [INFO] core: pre-seal teardown complete
2016/08/15 19:45:21 [ERR] core: post-unseal setup failed: failed to setup audit table
2016/08/15 19:45:24 [INFO] core: acquired lock, enabling active operation
2016/08/15 19:45:24 [INFO] core: post-unseal setup starting
```

Any help in identifying why this would be happening is appreciated. Just for proof the file is writeable by vault:

```
ubuntu@[ip]:/var/log$ sudo -u vault ls -alh /var/log/vault_audit.log
-rwxrwxrwx 1 vault root 0 Aug 15 19:25 /var/log/vault_audit.log
```

And here is our vault.conf:

```
backend "dynamodb" {
  region = "us-west-2"
  table = "[dynamo-table-name]"
  access_key = "xxxxx"
  secret_key = "xxxxxxxxx"
  advertise_addr = "http://[ip-of-vault-instance]"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/etc/certs/server.pem"
  tls_key_file = "/etc/certs/server.key"
}
```

**Comment by jefferai** [comment] 2016-08-15 20:26
Hi @beeradb,

Any chance you can build Vault yourself? I realize looking at the code that the actual error isn't being shown, which makes it rather hard to know what the problem is. I could tell you what to change, or provide you with a build (if you tell me which os/arch, e.g. linux/amd64) that has this error message printed.

**Comment by frodopwns** [comment] 2016-08-15 20:32
@jefferai Ubuntu 14.04 amd64

**Comment by jefferai** [comment] 2016-08-15 20:36
https://www.dropbox.com/s/vcb147rotet7vvl/issue-1736.tar.gz?dl=0

**Comment by frodopwns** [comment] 2016-08-15 20:38
Would appreciate if you could throw that build together. We have been struggling to restore vault all morning and just now took a break to eat something.

**Comment by jefferai** [comment] 2016-08-15 20:41
@frodopwns Already did! ^

**Comment by frodopwns** [comment] 2016-08-15 20:56
Pitfalls of trying to type out responses on phone :-) Thanks!

**Comment by beeradb** [comment] 2016-08-15 21:25
This did provide slightly more info: 

```
2016/08/15 20:59:07 [ERR] core: failed to create audit entry file/: sanity check failed; unable to open /var/log/vault_audit.log for writing: open /var/log/vault_audit.log: too many open files
2016/08/15 20:59:07 [INFO] core: pre-seal teardown starting
2016/08/15 20:59:07 [INFO] rollback: stopping rollback manager
2016/08/15 20:59:07 [INFO] core: pre-seal teardown complete
2016/08/15 20:59:07 [ERR] core: post-unseal setup failed: failed to setup audit table
2016/08/15 20:59:07 http: Accept error: accept tcp [::]:8200: accept4: too many open files; retrying in 10ms
2016/08/15 20:59:07 http: Accept error: accept tcp [::]:8200: accept4: too many open files; retrying in 20ms
2016/08/15 20:59:07 http: Accept error: accept tcp [::]:8200: accept4: too many open files; retrying in 5ms
2016/08/15 20:59:08 http: Accept error: accept tcp [::]:8200: accept4: too many open files; retrying in 10ms
2016/08/15 20:59:08 http: Accept error: accept tcp [::]:8200: accept4: too many open files; retrying in 5ms
2016/08/15 20:59:10 [INFO] core: acquired lock, enabling active operation
2016/08/15 20:59:10 [INFO] core: post-unseal setup starting
2016/08/15 20:59:16 http: Accept error: accept tcp [::]:8200: accept4: too many open files; retrying in 5ms
2016/08/15 20:59:16 http: Accept error: accept tcp [::]:8200: accept4: too many open files; retrying in 10ms
```

Running `lsof` on the vault process it was showing 1000 open files.

Here's what we tried after that: 

- We set `max_open_connections` to 2, as indicated in https://github.com/hashicorp/vault/issues/1257  
- We also  dialed back the dynamodb table read capacity down to 50. We had previously upped it to 1000 because restores were taking quite a while, and we were seeing logs of dynamodb rate limiting after the unseal. There were thousands of these error messages, but all looked fairly similar:

```
2016/08/15 21:20:24 [ERR] expire: failed to revoke 'auth/github/login/[some-token]': failed to revoke token: failed to revoke entry: failed to scan for leases: failed to list leases: ProvisionedThroughputExceededException: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API
```


As you can see in the output, we do have a fairly large number of active tokens (~3100), and when originally using vault we had not set a token duration. We've since set that value, and from what I can tell it looks to be trying to invalidate a large number of tokens directly after restore.

**Comment by jefferai** [comment] 2016-08-15 21:36
Hi @beeradb ,

I don't know much about DynamoDB, but shouldn't you have *upped* the read capacity if you're exceeding your provisioning level?

I think you're having two separate problems here.

One is that your provisioning level isn't high enough for Vault to successfully complete its operations in AWS. The other is that you're hitting your user open files limit, probably because the dynamodb backend doesn't have a way to limit the number of simultaneous ops. You can adjust the max number of open files for that user (temporarily using `ulimit` or permanently) which should help for now.

**Comment by frodopwns** [comment] 2016-08-15 22:35
@jefferai Thanks for your help. We were able to recover.  It seems we were running into issues with ulimit and dynamo rate limiting. After those things subsided we started getting 

```2016/08/15 21:30:51 [ERR] expire: maximum revoke attempts for 'auth/github/login/some_token_string' reached```

which eventually cleared up and we were able to use vault again.

I think in the future we will be abandoning the dynamodb backend in favor of the myssql one.

**Comment by jefferai** [comment] 2016-08-15 22:49
Glad it's all sorted! I do feel the need to point out that you'd be abandoning one community supported backend for another, and one that doesn't support HA or upcoming clustering features if you want that in the future.

**Comment by frodopwns** [comment] 2016-08-15 22:54
@jefferai a lot of our infrastructure relies on Vault to do its work so we want a backend that is somewhat isolated and not likely to die with the rest of our stack in bad times.  I assume you are recommending Consul? Wouldn't we have to maintain a cluster of Consul severs in order to use that correctly? Seems a bit tedious for a bunch of people who don't like servers.

**Comment by jefferai** [comment] 2016-08-15 23:54
Hi @frodopwns ,

I do mean Consul, as you could probably guess.

I totally sympathize about not liking servers. Relying on Vault for the most part comes down to relying on its data store as Vault is in many ways basically a database passthrough. If you have a lot of experience with operationalizing MySQL you may feel comfortable with its needs in terms of backups and so on. However, what you won't get is the ability to have Vault-level failover. This may not matter if you already have MySQL set up in a cluster, of course, but it does mean that Vault upgrades will have longer downtime, and it means that if a single Vault server dies (either the binary or the OS or VM or whatever that it's running on), you have no backup that can take over.

You don't *need* to run a Consul cluster. If you're comfortable with it, you can start with a single node. You can also ignore me, and that's totally fine :-) In the end it comes down to your comfort level. I just wanted to make sure that you understand what you're going from and to, in terms of level of support on our end.

**Comment by frodopwns** [comment] 2016-08-16 15:57
@jefferai All good points. We did happen to notice that the failover when using the dynamodb was dismal. Guess we might have to look into using Consul after all.

**Comment by jefferai** [comment] 2016-08-19 14:28
Closing this for now, let me know if you need more assistance on this issue.

**Closed by jefferai** 2016-08-19 14:28 UTC
