### ISSUE TITLE
Vault Cleanup

### ISSUE THREAD

**Issue by rashmisinghgaurav** [hashicorp/vault#4885] opened 2018-07-10 06:41 UTC
Hi,

We have a vault cluster of 3 nodes with consul as backend (3 node cluster). I am seeing the consul backend is growing at a rate of ~10MB per day.
I am guessing that lots of unused hashivault role tokens(which are not revoked) are the cause of this growth. Is there a way to query tokens for last used time and preform a cleanup?

Thanks!

**Comment by jefferai** [comment] 2018-07-10 16:06
Duplicate of https://groups.google.com/d/msg/vault-tool/dQsFvcAgyHo/yGY4R36WCgAJ

**Closed by jefferai** 2018-07-10 16:06 UTC
