### ISSUE TITLE
Brute Force Attack

### ISSUE THREAD

**Issue by certifiedloud** [hashicorp/vault#336] opened 2015-06-12 17:08 UTC
As far as I can tell, there isn't anything in place to prevent a brute force attack against the auth backend. 

Perhaps there should be a lockout period after so many failed auth attempts. Simple, effective.

**Comment by mitchellh** [comment] 2015-06-12 17:29
Yeah I think our plan is to implement a simple rate limiter on the HTTP endpoint. We can start out with some pretty high defaults and make it configurable. Tagged.

**Comment by jefferai** [comment] 2015-06-18 17:48
Any service, including Vault, is subject to brute force attacks and DoS attacks. There is an argument that this should be handled at a separate/higher level (firewall, for instance). Having some capability in Vault is nice, but only if can be turned off if other, more complex protections are already in place.

**Comment by PushkarJ** [comment] 2017-01-13 23:20
This documentation mentions about returning HTTP status code 429 when rate limit is exceeded: https://www.vaultproject.io/docs/http/

Does this imply that there is a default rate limit set in Vault ? If yes, perhaps the relevant documentation and configuration parameter is missing.

**Comment by jefferai** [comment] 2017-01-14 00:22
Hi Pushkar,

That description is actually incorrect... It looks like a description copied out of the normal 429 meaning rather than what it actually does :-(

I'll get that updated, but no, there is not current a rate limiting mechanism and we recommend firewall capabilities if you need that.

**Comment by jefferai** [comment] 2017-01-14 00:22
Note to Vault team, I assigned this as a milestone ticket to update the docs. No current plans to implement rate limiting within Vault, so let's close after docs are updated.

**Closed** 2017-01-14 04:11 UTC
Labels: core, enhancement

**Comment by PushkarJ** [comment] 2017-01-14 05:55
Thanks for the quick response and update, @mitchellh and @vishalnayak . 

I was wondering if I run vault inside a vagrant box, with rate limiting enabled: https://vagrantcloud.com/help/vagrant/boxes/limits, what would be the expected behavior? 

Does that vagrant box, track ingress requests irrespective of what's running inside? In that case, does it add the HTTP headers mentioned in the above linked documentation before it is sent back to the client?

Apologies, in advance, if I am missing some basic understanding of vagrant/atlas or vault here.
