### ISSUE TITLE
SSH Dynamic key doesn't add public key to authorized_keys unless I use custom install_script

### ISSUE THREAD

**Issue by vascop** [hashicorp/vault#2076] opened 2016-11-08 16:00 UTC
For some reason I need to define a custom install_script for Dynamic Key auth to work. This install_script can have the exact same contents as the one in your repo though. Which is very strange. Here are some steps to reproduce, I can share a Vagrantfile and two ansible scripts to configure both of the machines (vault host and instance to be SSH'ed into). And all of this running Vault v0.6.2

1. Output of `vault read ssh/roles/dynamic_key_role`
```
Key                     Value
---                     -----
admin_user              vaultadmin
allowed_users    
cidr_list        
default_user            vagrant
exclude_cidr_list
install_script          #!/bin/bash
#
# This is a default script which installs or uninstalls an RSA public key to/from
# authoried_keys file in a typical linux machine. 
# 
# If the platform differs or if the binaries used in this script are not available
# in target machine, use the 'install_script' parameter with 'roles/' endpoint to
# register a custom script (applicable for Dynamic type only).
#
# Vault server runs this script on the target machine with the following params:
#
# $1:INSTALL_OPTION: "install" or "uninstall"
#
# $2:PUBLIC_KEY_FILE: File name containing public key to be installed. Vault server
# uses UUID as name to avoid collisions with public keys generated for other requests.
#
# $3:AUTH_KEYS_FILE: Absolute path of the authorized_keys file.
# Currently, vault uses /home/<username>/.ssh/authorized_keys as the path.
#
# [Note: This script will be run by Vault using the registered admin username.
# Notice that some commands below are run as 'sudo'. For graceful execution of
# this script there should not be any password prompts. So, disable password
# prompt for the admin username registered with Vault.

set -e

# Storing arguments into variables, to increase readability of the script.
INSTALL_OPTION=$1
PUBLIC_KEY_FILE=$2
AUTH_KEYS_FILE=$3

# Delete the public key file and the temporary file
function cleanup
{
        rm -f "$PUBLIC_KEY_FILE" temp_$PUBLIC_KEY_FILE
}

# 'cleanup' will be called if the script ends or if any command fails.
trap cleanup EXIT

# Return if the option is anything other than 'install' or 'uninstall'.
if [ "$INSTALL_OPTION" != "install" ] && [ "$INSTALL_OPTION" != "uninstall" ]; then
        exit 1
fi

# Create the .ssh directory and authorized_keys file if it does not exist
SSH_DIR=$(dirname $AUTH_KEYS_FILE)
sudo mkdir -p "$SSH_DIR"                                                            
sudo touch "$AUTH_KEYS_FILE"

# Remove the key from authorized_keys file if it is already present.
# This step is common for both install and uninstall.  Note that grep's
# return code is ignored, thus if grep fails all keys will be removed
# rather than none and it fails secure
sudo grep -vFf "$PUBLIC_KEY_FILE" "$AUTH_KEYS_FILE" > temp_$PUBLIC_KEY_FILE || true
cat temp_$PUBLIC_KEY_FILE | sudo tee "$AUTH_KEYS_FILE"

# Append the new public key to authorized_keys file
if [ "$INSTALL_OPTION" == "install" ]; then
        cat "$PUBLIC_KEY_FILE" | sudo tee --append "$AUTH_KEYS_FILE"
fi
key                     dev_key
key_bits                1024
key_option_specs 
key_type                dynamic
port                    22
```

2. Output of vault read /ssh/config/zeroaddress
```
Key     Value
---     -----
roles   [dynamic_key_role]
```

4. Run `vault write ssh/creds/dynamic_key_role ip=192.168.50.20`, nothing gets added to user's authorized_keys, and the `$PUBLIC_KEY_FILE` gets left in the admin_user's home directory. SSH obviously does not work.
5. Create a file called `install_script.sh` and use as it's contents the output of step 1.
6. `vault write ssh/roles/dynamic_key_role key_type=dynamic key=dev_key admin_user=vaultadmin default_user=vagrant install_script=@install_script.sh`
Success! Data written to: ssh/roles/dynamic_key_role
5. `vault write ssh/creds/dynamic_key_role ip=192.168.50.20`
6. All works fine. Meaning nothing gets left in the default_user's home, public key gets added to the authorized_keys file and I can SSH in.

Everything is working for me now, but you might want to look into why it happens as I had to waste a bit of time making it work.

**Comment by vishalnayak** [comment] 2016-12-01 15:41
@vascop Along with `$PUBLIC_KEY_FILE`, do you also see `$PUBLIC_KEY_FILE.sh` script left in the admin_user's home directory?

**Comment by vishalnayak** [comment] 2016-12-01 15:43
I am not able to reproduce this. Please share the needful so I can reproduce this. Thanks!

**Comment by vishalnayak** [comment] 2017-01-10 15:21
Closing this since it's not reproducible. Please reopen preferably with the information required to reproduce it, if this problem still exists.

**Closed by vishalnayak** 2017-01-10 15:21 UTC
Labels: waiting-reply
