### ISSUE TITLE
Group-membership inconsistencies when using identity/group to remove member entities by group name

### ISSUE THREAD

**Issue by hdeberranger** [hashicorp/vault#10626] opened 2020-12-28 13:29 UTC
Describe the bug

**Related to https://github.com/hashicorp/vault/issues/10223:**
(This bug is still existing on latest version)

Group-membership inconsistencies arise when using identity/group by group name only to remove member entities:

- The group reflects the new membership, with the entity missing.
- The entity shows that it is still a member of the group.

The result is that entities are still granted the policies for the group.

**Comment by mladlow** [comment] 2021-01-28 17:14
Hi @hdeberranger - thanks for bringing this up again. Since the title of this issue is the same as the linked issue, is it a duplicate?

**Comment by mgritter** [comment] 2021-01-29 22:52
Duplicate of #10223, now fixed on main branch.

**Closed by mgritter** 2021-01-29 22:52 UTC
Labels: bug, core/identity, pod/bridge
