### ISSUE TITLE
vault no longer stores token in ~/.vault-token when login MFA duo auth is enabled

### ISSUE THREAD

**Issue by xueshanf** [hashicorp/vault#16928] opened 2022-08-30 02:18 UTC
**Describe the bug**
We enabled Login Multi Factor Authentication with DUO and enforced the MFA on ldap login method.
UI login and command line login work, however, we noticed the vault cli no long stores generated token in ~/.vault-token file.

**To Reproduce**

1. Vault login MFA duo is enabled and enforced
```
vault list identity/mfa/method/duo
Keys
----
a91f44ba-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

```
vault read /identity/mfa/login-enforcement/duo
Key                      Value
---                      -----
auth_method_accessors    [auth_ldap_xxxxxxx]
auth_method_types        []
id                       72c6378a-xxxx-xxxx-xxxx-xxxxxxxxxxxx
identity_entity_ids      []
identity_group_ids       []
mfa_method_ids           [a91f44ba-xxxx-xxxx-xxxx-xxxxxxxxxxxx]
name                     duo
namespace_id             root
```

2. Run `vault login -method=ldap`

```$ vault login -method=ldap 
Password (will be hidden): 
Asking Vault to perform MFA validation with upstream service. You should receive a push notification in your authenticator app shortly
Key                    Value
---                    -----
token                  hvs.CAESIDL59h-QYYNw3X25B8XGcQOXXy5*********
token_accessor         tdax6Znj99ShGLDUv5*****
```
Token is generated.

3. Run `vault print token` returns nothing.
4. Run `ls -l ~/.vault-token` returns */Users/\<username\>/.vault-token: No such file or directory*
5. Also tried `vault login -method=ldap -no-store=false`, same result. Token is not stored in default token helper file.

**Expected behavior**
Generated authentication token should be stored in ~/.vault-token as versions prior 1.11.x

**Environment:**
* Vault Server Version:
```
$ vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    7
Threshold       2
Version         1.11.2
Build Date      2022-07-29T09:48:47Z
Storage Type    gcs
Cluster Name    vault-cluster-9d051ddf
Cluster ID      3d1c227d-df3e-30da-59a6-332dea2002e4
HA Enabled      true
HA Cluster      https://10.4.0.12:8201
HA Mode         active
Active Since    2022-08-30T01:32:31.427655292Z
```

* Vault CLI Version (retrieve with `vault version`):

```
$ vault version
Vault v1.11.2 ('3a8aa12eba357ed2de3192b15c99c717afdeb2b5+CHANGES'), built 2022-07-29T09:48:47Z
```

* Server Operating System/Architecture:

Docker container image v1.11.2.

Vault server configuration file(s):

```hcl
api_addr     = "https://xx.xx.xx.xx.xx:8200"
cluster_addr = "https://10.4.1.3:8201"

ui = true

storage "gcs" {
  bucket     = "data-stage"
  ha_enabled = "true"
}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/etc/vault/tls/tls.crt"
  tls_key_file  = "/etc/vault/tls/tls.key"
  tls_disable_client_certs = true
  tls_min_version="tls12"
  tls_cipher_suites="TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA256"
  tls_prefer_server_cipher_suites="true"
}
```

**Comment by jonnyt** [comment] 2022-08-30 15:50
We just ran into the same situation after upgrading to v1.11.2 last night.  We are using userpass authentication.  

Steps we took to enable Duo:

```shell
USERPASS_ACCESSOR=$(vault auth list | grep userpass | awk '{print $3}')
METHOD_ID=$(vault write -field method_id identity/mfa/method/duo \
        username_format="{{identity.entity.aliases.$USERPASS_ACCESSOR.name}}" \
        api_hostname="$DUO_API_HOSTNAME" \
        integration_key="$DUO_INTEGRATION_KEY" \
        secret_key="$DUO_SECRET_KEY" )

vault write identity/mfa/login-enforcement/duo \
        mfa_method_ids="$METHOD_ID" \
        auth_method_accessors="$USERPASS_ACCESSOR"
```

Steps to reproduce the problem

```shell
$ vault login -method=userpass username=a_user
Password (will be hidden):
Asking Vault to perform MFA validation with upstream service. You should receive a push notification in your authenticator app shortly
Key                    Value
---                    -----
token                  hvs.CAESIK.....
```

Expected result

* Should see the message "Success! You are now authenticated. The token information displayed below
is already stored in the token helper."
* Token should be written to `.vault-token`

**Comment by xueshanf** [comment] 2022-10-05 16:08
Any updates? We are locked on 1.10 release because of this issue. I tried to look source code to see where to fix but it seem the build-in token helper does the right thing. I think the MFA  login changes somehow did not call the token helper.

**Comment by gnugnug** [comment] 2022-10-07 12:47
Still an issue with 1.11.4

**Comment by eliottcassidy2000** [comment] 2022-10-10 17:04
Also asking for updates on this issue. We have some duo MFA vault clusters running 1.10.2 as well as some duo MFA clusters running 1.11.3 and have been seeing the bug with both versions. Not sure if this bug has to do with the version of vault running on the cluster or version of vault that the user runs (ie the version of the binary that runs `vault login`), but with any of the combinations of versions that I've tried I still cant get the dang `.vault-token` file to appear!

 @xueshanf you said that you are locked on the 1.10 release because of this, could you specify exactly which version of vault you are running on your sever and which version you are running the login command with? I would really appreciate it! Would be great to have a way to workaround this bug at least for the moment.

**Comment by xueshanf** [comment] 2022-10-12 00:16
@eliottcassidy2000 looks like the fix is coming :)  

Our vault server version is 1.10.3.  My client version is v1.11.2 but I am sure I had problem with 1.10.x too when upgrading vault server to 1.11. I first thought my client was not updated accordingly, and update my vault client. Same issue.

**Comment by mpalmi** [comment] 2022-10-12 20:58
For a bit of clarity on the matter, there is a [fix](https://github.com/hashicorp/vault/commit/6a98e9955765249b16d4a433036787aabe9c433f) discussed in the [PR above](https://github.com/hashicorp/vault/pull/17494) that we are highly motivated to merge. I just need to wrap up the integration testing on this to make sure it solves the problem without breaking other functionality.

Thank you for your patience. I am hoping to get to this tomorrow.

**Comment by blake-adobe** [comment] 2022-10-12 21:14
Glad to hear this issue is being actively worked! We (Adobe) are in the process of rolling out LoginMFA and upgrading to 1.10.x. If this gets back-ported to 1.10.x soon, we could still roll out LoginMFA this year. Otherwise, we have to wait for another quarter or two. 

We found that versions 1.10.5 through 1.10.7 are affected in our testing.

**Comment by mpalmi** [comment] 2022-10-26 21:04
This still needs to be backported to 1.11/1.12 and merged into ENT.

**Comment by eliottcassidy2000** [comment] 2022-10-31 15:37
Hey @mpalmi I see that your branch was merged and also the backport branches were merged. Thank you so much for working on this! How should I expect to install a version with the bug fixed? Currently I'm installing via yum from https://rpm.releases.hashicorp.com/RHEL/7/x86_64/stable do I need to wait for a new version to be published there (something like 1.11.5)? If so, do you have any idea when that version will be available?

**Comment by pat-s** [comment] 2022-11-02 08:38
I just upgraded to 1.11.5 and it seems #17680 has not made it into the release? I am still not getting `~/.vault-token` stored. Release notes are still missing.

**Comment by mpalmi** [comment] 2022-11-02 11:35
@pat-s could you please share your login method and client version?

**Comment by pat-s** [comment] 2022-11-02 11:46
@mpalmi Ah of course! My fault, I was still on 1.12.0 for the CLI. With 1.12.1 and 1.11.5 on the server, everything works!

**Comment by mpalmi** [comment] 2022-11-02 12:12
Great news! Since this appears to be fixed in the latest minor releases, I'm going to go ahead and close this Issue out. Thanks for all the help getting to the root issue, and for your patience.

Please feel free to open up new issues should any other unexpected behaviors or bugs arise.

**Closed by mpalmi** 2022-11-02 12:12 UTC
Labels: bug, core/token, auth/mfa
