### ISSUE TITLE
Generic webhook secret backend

### ISSUE THREAD

**Issue by Buzer** [hashicorp/vault#2039] opened 2016-10-28 16:33 UTC
Currently the generic backend requires implementing quite a bit of stuff on the system which uses Vault for transmitting the credentials. I believe the current recommended flow is something like:
1. User authenticates to Vault and gets Vault token
2. User sends introspection token to application
3. Application checks the token, creates account for user and writes it to path that's accessiable by user's actual token. This can also be wrapped in Cubbyhole to allow getting the credentials only once
4. Application deletes/disables the account after token expires. Detecting revoked tokens requires periodic checks to the introspection service.

PostgreSQL/MySQL secret backends might be utilized in more generalized cases where application stores everything required in the database thanks to the addition of revocation_sql.

I think it would be helpful to add a generic webhook based secrets backend as well. Essentially Vault would do POST/PUT to the defined URL with it's own schema and DELETE later on to $url/$token to revoke it (or use parameter within the payload).

In this case the application would only need to implement the logic to check the Vault's authorization (JWT? Just a static token?) and create/delete users based on Vault's messages.

Is this something that could get added at this point?

**Comment by jefferai** [comment] 2016-10-28 17:54
This is not dissimilar to previous discussions around a "Generic API Backend" which I am totally failing to find in the issue tracker right now, so I'll keep this open rather than marking as a duplicate.

This is something we're interested in but it needs a lot of planning/vetting. In the past we've thought of it kind of like the templating in the SQL backends where you could define a template containing the calls that needed to be made, and give Vault a credential that can be used to make the calls. 

It's mostly a time issue, as in, nobody on the Vault team has time to get to this anytime soon.

**Comment by ekristen** [comment] 2016-10-29 14:12
@Buzer I like this idea too, what would help would be coming up with an RFC for how you'd think it would be implemented (see https://github.com/hashicorp/vault/issues/1986) and then we could help add/comment and maybe come up with a plan that @jefferai is ok with to do an initial implementation attempt in a pull request.

**Comment by mp911de** [comment] 2017-04-21 19:57
It would make sense to use Vault as the tool for generating/revoking/managing credentials in a generic way. This type of backend could help creating users/tokens/credentials for services that are not integrated with Vault through their own secret backend.

From an ops perspective, Vault would the only component to interact with to create users or revoke leases and reduce the number of involved access/credentials management systems.

**Comment by vishalnayak** [comment] 2021-06-22 18:56
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.

**Closed by vishalnayak** 2021-06-22 18:56 UTC
Labels: ecosystem, feature-request
