### ISSUE TITLE
Vault panics when logging in via CLI

### ISSUE THREAD

**Issue by white-glider** [hashicorp/vault#5646] opened 2018-10-30 16:57 UTC
**Description**
Vault panics when `vault login` is called on the command line.

**Steps To Reproduce The Problem**
Simply install Vault 0.11.4 on a Linux 64-bit machine, initialize it, unseal it and try to login by running `vault login` on the command line. You will receive the following error message:
```
$ vault login
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/hashicorp/vault/command.(*LoginCommand).Run(0xc00008b900, 0xc00000a070, 0x0, 0x0, 0xc0001ce9a0)
        /gopath/src/github.com/hashicorp/vault/command/login.go:255 +0xdee
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc00039c140, 0xc00039c140, 0xc0001cee40, 0xc0001e8960)
        /gopath/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x207
github.com/hashicorp/vault/command.RunCustom(0xc00000a070, 0x1, 0x1, 0xc00008b680, 0x0)
        /gopath/src/github.com/hashicorp/vault/command/main.go:170 +0x74a
github.com/hashicorp/vault/command.Run(0xc00000a070, 0x1, 0x1, 0xc00007c058)
        /gopath/src/github.com/hashicorp/vault/command/main.go:81 +0x48
main.main()
        /gopath/src/github.com/hashicorp/vault/main.go:10 +0x62
```

**Expected behavior**
Vault should ask for the authentication token and not crash with a panic.

**Environment:**
* Vault Version: v0.11.4 ('612120e76de651ef669c9af5e77b27a749b0dba3')
* Server Operating System/Architecture: Ubuntu 18.04.1 Server GNU/Linux 4.15.0 x86_64

Vault server configuration file(s):

```hcl
storage "file" {
  path = "/opt/vault/storage"
}
pid_file = "/opt/vault/vault.pid"
ui = true
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = true
}
```

**Additional context**
Vault v0.11.3 works just fine.

**Comment by vishalnayak** [comment] 2018-10-30 17:05
Duplicate of #5600

**Closed by vishalnayak** 2018-10-30 17:05 UTC
