### ISSUE TITLE
Test failures when running on ppc64le

### ISSUE THREAD

**Issue by vaibhavsood** [hashicorp/vault#2376] opened 2017-02-15 12:29 UTC
Hi,

I'm trying to run vault test cases (as per here: https://github.com/hashicorp/vault#developing-vault) using "make test" on a RHEL 7.2 ppc64le machine

I get errors for these tests:
github.com/hashicorp/vault/builtin/logical/cassandra 
github.com/hashicorp/vault/builtin/logical/consul 
github.com/hashicorp/vault/builtin/logical/mongodb
github.com/hashicorp/vault/builtin/logical/mssql 
github.com/hashicorp/vault/builtin/logical/mysql
github.com/hashicorp/vault/builtin/logical/pki
github.com/hashicorp/vault/builtin/logical/postgresql

The errors are below (some snippets)
2017-02-14 15:05:41.005486 I | Try 59 failed. Retrying.
2017-02-14 15:05:42.006106 I | gocql: unable to dial control conn 127.0.0.1: dial tcp 127.0.0.1:42623: getsockopt: connection refused
2017-02-14 15:05:42.006169 I | Try 60 failed. Retrying.
--- FAIL: TestBackend_basic (67.68s)
        backend_test.go:63: could not connect to database: Could not setup Cassandra container.

Similar for other backends

On investigation, found that these tests are run in containers, for ppc64le these containers are not available on dockerhub except for postgresql. I made following change and github.com/hashicorp/vault/builtin/logical/postgresql passes

[root@pts00433-vm27 vault]# git diff
diff --git a/vendor/gopkg.in/ory-am/dockertest.v2/vars.go b/vendor/gopkg.in/ory-am/dockertest.v2/vars.go
index 619855e..01464a6 100644
--- a/vendor/gopkg.in/ory-am/dockertest.v2/vars.go
+++ b/vendor/gopkg.in/ory-am/dockertest.v2/vars.go
@@ -35,7 +35,7 @@ var (
        MySQLImageName = env.Getenv("DOCKERTEST_MYSQL_IMAGE_NAME", "mysql")

        // PostgresImageName is the PostgreSQL image name on dockerhub.
-       PostgresImageName = env.Getenv("DOCKERTEST_POSTGRES_IMAGE_NAME", "postgres")
+       PostgresImageName = env.Getenv("DOCKERTEST_POSTGRES_IMAGE_NAME", "ppc64le/postgres:9.6")

        // ElasticSearchImageName is the ElasticSearch image name on dockerhub.
        ElasticSearchImageName = env.Getenv("DOCKERTEST_ELASTICSEARCH_IMAGE_NAME", "elasticsearch")

[root@pts00433-vm27 vault]# make test TEST=./builtin/logical/postgresql
go generate
CGO_ENABLED=0 VAULT_TOKEN= VAULT_ACC= go test -tags='vault' ./builtin/logical/postgresql  -timeout=10m -parallel=4
ok      github.com/hashicorp/vault/builtin/logical/postgresql   137.624s

Others still fail due to lack of the right ppc64le containers, wanted to check if vault handles this for ppc64le

Thanks!
Vaibhav

**Comment by jefferai** [comment] 2017-02-15 13:33
I'm not sure what the question is here... Sounds like you can just set an env var and it will work.

**Comment by vaibhavsood** [comment] 2017-03-01 12:04
The issue is with ppc64le docker containers for cassandra, mysql etc. not being available on dockerhub.
The vault tests as per my understanding run in containers and hence fail (docker pull will fail)....

**Comment by vaibhavsood** [comment] 2017-03-01 12:10
Also im trying to build the missing containers locally (write my own dockerfile and create container for ppc64le). Most of the tests pass, however i see an issue with the mysql test

[mysql] 2017/03/01 16:43:16 packets.go:33: unexpected EOF
[mysql] 2017/03/01 16:43:16 packets.go:33: unexpected EOF
[mysql] 2017/03/01 16:43:16 packets.go:33: unexpected EOF
2017/03/01 16:43:16 Try 60 failed. Retrying.
--- FAIL: TestBackend_leaseWriteRead (34.30s)
        backend_test.go:59: could not connect to database: Could not set up MySQL container.
FAIL
FAIL    github.com/hashicorp/vault/builtin/logical/mysql        139.768s

Any idea why i get this error? 

Thanks!

**Comment by jefferai** [comment] 2017-03-01 14:22
Hi @vaibhavsood ,

I also get that error intermittently with the MySQL container. I don't know what the issue is but it seems to be something specific to that container, and it doesn't happen consistently (for me, or in Travis).

**Comment by jefferai** [comment] 2018-03-19 23:35
Closing -- if you have specific code diffs/suggestions please PR them; this can also be used to skip tests depending on platform.

**Closed by jefferai** 2018-03-19 23:35 UTC
