### ISSUE TITLE
AD Secrets engine is rotating the password always irrespective of ttl value

### ISSUE THREAD

**Issue by sivanag1974** [hashicorp/vault#6476] opened 2019-03-26 00:25 UTC
**Description**
AD Secrets engine is rotating password always irrespective of ttl value. As per the documentation of lazy rotation, vault is supposed to rotate the password after the ttl has passed. Even if the ttl has not passed, vault is rotating the password.

**To Reproduce**
Configure the AD secrets engine as per the documentation 

1. vault secrets enable ad
2. vault write ad/config   binddn=ad_account_01     bindpass=account_password url=ldaps://ad_url     userdn="OU=Accounts,DC=xxxx,DC=yyyyy,DC=zzzzz,DC=com" insecure_tls=true ttl=86400 max_ttl=864000 (Note: max_ttl is 10 times more than ttl)
3. vault write ad/roles/account_02 service_account_name="ad_account_02@xxxx.yyyyy.zzzzz.com" ttl=86300 (Note: 100 seconds less than default ttl)
4. Use either root-token or user with appropriate policy to read/write at ad/creds
5. Use the command vault read ad/creds/account_02 or curl command curl --header "X-Vault-Token:s.xxxxxxxxxxxxxxxxxx"  --request GET http://127.0.0.1:8200/v1/ad/creds/account_02 to check the password

**Expected behavior**
Since the ttl has not passed as the configuration, vault is supposed to provide old password. 

**Actual result**
Whenever the command "vault read ad/creds/account_02" is run, vault is displaying different values as
Key                 Value
---                 -----
current_password    ?@154mMQfatgXppPFzuhL8TFO5USgvGl66uoaic6h9AZnn8nPyfLQzzmSw+
username            ad_account_02

Key                 Value
---                 -----
current_password    ?@09AZhSnppTG6YrVTNnB0xkYdzfz9T/oYESdaW9GcA8e1qwgGYdvfRCy6W
username             ad_account_02

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.0
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.0 ('36aa8c8dd1936e10ebd7a4c1d412ae0e6f7900bd')
* Server Operating System/Architecture: Windows 64 bit

Vault server configuration file(s): vault in dev mode

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**
None

**Comment by tyrannosaurus-becks** [comment] 2019-03-26 16:53
Thanks for reporting this, @sivanag1974 ! 

I wrote a test [here](https://github.com/hashicorp/vault-plugin-secrets-ad/compare/vault-issue-6476-ttl) to duplicate it. I was expecting the test to fail [here](https://github.com/hashicorp/vault-plugin-secrets-ad/compare/vault-issue-6476-ttl#diff-9b04936148f911aa5fdb83742443c1d5R30) because it sounds like you're seeing that the password is getting rotated too often. However, the test is passing.

Does my test look correct? Also, what version of Vault are you using, and what version of the AD secrets plugin (if you're running an independent plugin version rather than the one that's built in to Vault).

Thanks!

**Comment by sivanag1974** [comment] 2019-03-26 17:43
I am using Vault 1.1.0 with vault-built-in AD Secrets plugin.
Your test looks good. However I don't last_password when I run the commands
(vault commandline/curl)

Even today I am getting the following response.

vault read ad/creds/svc_vault_test2
Key                 Value
---                 -----
current_password
?@09AZN2k3fgtWBcau0lRlgazlRpi3YG/2YlWbrVUEQBwGQndDz4ZLcrOv3/Wsck
username            svc_vault_test2

vault read ad/creds/svc_vault_test2
Key                 Value
---                 -----
current_password
?@09AZiFKMIaUYm9bDwI63gqXUv/N21j2uK+mj9qkEDoG25H4XaNqgj7UYVWl8VY
username            svc_vault_test2

Output of curl command:

{"request_id":"73e35dc1-399e-3d50-3102-4ea96fa542fb","lease_id":"","renewable":false,"lease_duration":0,"data":{"current_password":"?@09AZFWpw0jVM/4hL9KPxy1RmquTm4OO06M0Gq2EOxepX4L2dAHF5JqkeLsoN9D","username":"svc_vault_test2"},"wrap_info":null,"warnings":null,"auth":null}

The issues I see:
1. In your test, you are comparing current_password and last_password

...
if expectRotated {
if currentPass == lastPass {
t.Fatal("password was not rotated as expected")
}
} else {
if lastPass != nil && (lastPass != currentPass) {
t.Fatal("password was unexpectedly rotated")
}
}
When I run the command, it's not printing the last_password (Please see the
sample runs above) and hence I can't verify it.
Note: I verified these passwords are functional by trying logging to AD
from JXplorer.
2. It changes the value of current_password with every run

Additional information:

Output of "vault status"
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.1.0
Cluster Name    vault-cluster-a60331a8
Cluster ID      906ceeb3-1d45-0ed8-fa1b-4937ce75cddd
HA Enabled      false

output of vault version
Vault v1.1.0 ('36aa8c8dd1936e10ebd7a4c1d412ae0e6f7900bd')

Vault is run in dev mode (vault server -dev) with filesystem as backend in
Windows. Does it matter?

Thanks,
Siva

**Comment by tyrannosaurus-becks** [comment] 2019-03-26 19:21
Hm, I'm still having trouble duplicating this locally. When I simply print out the password I get on both calls in my test, they come back the same. However, I _can_ duplicate this if I always make the `pwdLastSet` field on the Active Directory entry be _after_ Vault last rotated the password.

Would you have the ability to visually look at that field for the entry you're testing on? I'm wondering if perhaps it's in a different timezone than the local Vault instance, and maybe that's the issue; or perhaps an unexpected format isn't parsing correctly.

Could you also post the timezone your Vault instance is in, and the time on that instance when you pull the Active Directory `pwdLastSet` time?

**Comment by sivanag1974** [comment] 2019-03-26 19:51
OK. Does it mean that if the value of pwdLastSet is in future, vault will always rotate?
When I run password rotation, I can see the value for pwsLastSet getting changed to 

131980954065019160
131981028312389468
131981028904206603
(Inspected using JXplorer)

I know the timezone that my vault server is running, which is (UTC-08:00) Pacific Time (US & Canada)
I need to reach out and get timezone info for AD from the one who is maintaining it/supporting it. Will post as soon as I get it.

**Comment by tyrannosaurus-becks** [comment] 2019-03-26 20:59
Interesting! When I plug the last value of "131981028904206603" into the client's time parser, I get "2019-03-26 19:41:30.4206603 +0000 UTC". Subtracting the 8 hour offset from that results in the hour of _11_ rather than _12_ as you've posted. Github says you posted your comment about an hour ago, which would have been around 12:50 Pacific Daylight Savings Time. We may be encountering a case where one server is on Daylight Savings Time and the other isn't, I wonder. If Active Directory thinks the time is different by one hour from Vault's time, it's possible Vault continuously thinks the password in AD has been rotated _since_ it last rotated the password, so it's re-rotating the password so it will "know" it again.

Is there a way to more definitively check the time on both servers? To make sure they exactly match?

**Comment by sivanag1974** [comment] 2019-03-26 21:35
Yes, it is! 
I have reached out to the AD team for getting the timezone information for the AD cluster and its nodes. Waiting for them and send you as soon as I get.

**Comment by sivanag1974** [comment] 2019-03-27 04:51
All our AD server instances are using the timezone as 
(UTC-08:00) Pacific Time (US & Canada)

Our vault server is using (UTC-08:00) Pacific Time (US & Canada)
It looks like all are same.

**Comment by tyrannosaurus-becks** [comment] 2019-03-27 16:25
Hm! Thanks for ruling that out! I'll keep trying to figure out the issue.

**Comment by sivanag1974** [comment] 2019-03-27 17:34
Great

**Comment by tyrannosaurus-becks** [comment] 2019-03-27 18:30
Hi @sivanag1974 ! So, I'm not sure what is causing the issue since I can't duplicate it locally. So, to figure it out, I added some debugging output to the plugin. You can either wait until the next Vault release when the updated version of the Active Directory plugin is included in the plugin catalog, or you can run it with the existing version of Vault.

If you'd prefer to do the latter, here's what you'd do:
- Clone the Active Directory secrets plugin here: https://github.com/hashicorp/vault-plugin-secrets-ad
- Build a binary from the source code using `$ make dev`
- Find the checksum of the binary by running `$ sha256sum bin/vault-plugin-secrets-active-directory` (that's on Ubuntu, the command for your OS may vary)
- Add the plugin to Vault by running something like:
```
vault write sys/plugins/catalog/secret/active-directory \
    sha_256=a5d9268f5a6cf0ab08bc1c3161bbe753f08df0ca77e3513b9fcf7f2c80a13632 \
    command=vault-plugin-secrets-active-directory
```
- Enable the plugin by running `$ vault secrets enable active-directory`
- Configure the Active Directory configuration and role as you have above
- Try to get creds as you have above
- The debug output should show what's happening

Since the output showing what's happening is logged at a debug level, you'll need to ensure that Vault is running with this line in its top-level config as you go through these steps. That config line looks like this:
```
log_level = "Debug"
```
Once you've got the debug output from the Vault logs while you're doing that creds call, it would be awesome if you could post what you see. I'm very curious about what the issue is.

**Comment by sivanag1974** [comment] 2019-03-27 18:59
OK. Thanks for the information. Will first try "later approach" by cloning https://github.com/hashicorp/vault-plugin-secrets-ad and following your steps and send you.

**Comment by sivanag1974** [comment] 2019-04-18 23:00
Alright,
I got time to work on this today.
When I try 
vault write sys/plugins/catalog/secret/active-directory sha_256=f6f527ea0ca50d7b85de4b21bf107f62db9fbed8fa38325c77dc3e154f23d77f command=vault-plugin-secrets-active-directory,

I am getting:
Error writing data to sys/plugins/catalog/secret/active-directory: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/plugins/catalog/secret/active-directory
Code: 500. Errors:

* 1 error occurred:
        * could not set plugin, plugin directory is not configured

**Comment by sivanag1974** [comment] 2019-04-18 23:45
Here is the debug logs:

2019-04-18T19:38:12.262-0400 [DEBUG] secrets.ad.ad_fd06940f: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com TTL:7776000 LastVaultRotation:0001-01-01 00:00:00 +0000 UTC PasswordLastSet:2019-04-17 23:10:58.6128784 +0000 UTC}
2019-04-18T19:38:12.262-0400 [DEBUG] secrets.ad.ad_fd06940f: rotating password for the first time so Vault will know it
2019-04-18T19:38:17.243-0400 [DEBUG] secrets.ad.ad_fd06940f: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com TTL:7776000 LastVaultRotation:2019-04-18 23:38:13.341055573 +0000 UTC PasswordLastSet:2019-04-18 23:38:14.091544 +0000 UTC}
2019-04-18T19:38:17.243-0400 [DEBUG] secrets.ad.ad_fd06940f: starting a regular rotation
2019-04-18T19:38:17.243-0400 [DEBUG] secrets.ad.ad_fd06940f: using stored credential
2019-04-18T19:38:17.243-0400 [DEBUG] secrets.ad.ad_fd06940f: returning previous credential
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=auth/ldap/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=sys/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=identity/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=apps/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=users/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=shared/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=metadata/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=ad/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=cubbyhole/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=auth/token/
2019-04-18T19:38:44.108-0400 [DEBUG] secrets.ad.ad_fd06940f: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com TTL:7776000 LastVaultRotation:2019-04-18 23:38:13.341055573 +0000 UTC PasswordLastSet:2019-04-18 23:38:14.091544 +0000 UTC}
2019-04-18T19:38:44.108-0400 [DEBUG] secrets.ad.ad_fd06940f: starting a regular rotation
2019-04-18T19:38:44.108-0400 [DEBUG] secrets.ad.ad_fd06940f: using stored credential
2019-04-18T19:38:44.108-0400 [DEBUG] secrets.ad.ad_fd06940f: returning previous credential
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=auth/ldap/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=sys/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=identity/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=apps/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=users/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=shared/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=metadata/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=ad/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=cubbyhole/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=auth/token/
2019-04-18T19:39:26.759-0400 [DEBUG] secrets.ad.ad_fd06940f: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com.com TTL:7776000 LastVaultRotation:2019-04-18 23:38:13.341055573 +0000 UTC PasswordLastSet:2019-04-18 23:38:14.091544 +0000 UTC}
2019-04-18T19:39:26.759-0400 [DEBUG] secrets.ad.ad_fd06940f: starting a regular rotation
2019-04-18T19:39:26.759-0400 [DEBUG] secrets.ad.ad_fd06940f: using stored credential
2019-04-18T19:39:26.759-0400 [DEBUG] secrets.ad.ad_fd06940f: returning previous credential
2019-04-18T19:39:28.378-0400 [DEBUG] secrets.ad.ad_fd06940f: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com.com TTL:7776000 LastVaultRotation:2019-04-18 23:38:13.341055573 +0000 UTC PasswordLastSet:2019-04-18 23:38:14.091544 +0000 UTC}
2019-04-18T19:39:28.378-0400 [DEBUG] secrets.ad.ad_fd06940f: starting a regular rotation
2019-04-18T19:39:28.378-0400 [DEBUG] secrets.ad.ad_fd06940f: using stored credential
2019-04-18T19:39:28.379-0400 [DEBUG] secrets.ad.ad_fd06940f: returning previous credential

**Comment by tyrannosaurus-becks** [comment] 2019-04-22 18:19
@sivanag1974 thanks for circling back with that output!

I wrote a test in the Active Directory secrets engine aimed at reproducing the issue. I actually wasn't able to duplicate the fast-rotating behavior you're seeing. However, I do notice a couple of things:

- The debug output is incorrect. Where it says "starting a regular rotation", it's actually just looking up the credentials, rotating them if needed, and returning them.
- The password isn't really being rotated, otherwise we would see this in the logs: https://github.com/hashicorp/vault-plugin-secrets-ad/blob/master/plugin/path_creds.go#L139
- The original config and role you posted have TTL's that differ from the TTL of the role shown (7776000), so I performed my tests with those for the config and role TTL's.

If you're still seeing that the password is indeed being rotated in Active Directory, could you please share the config and role configuration you have for these logs?

Also, FWIW, I have linked a PR fixing the issues I _did_ see with the logging output. If those debug logs had included the fixed output, here's what the would have looked like.
```
2019-04-18T19:38:12.262-0400 [DEBUG] secrets.ad.ad_fd06940f: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com TTL:7776000 LastVaultRotation:0001-01-01 00:00:00 +0000 UTC PasswordLastSet:2019-04-17 23:10:58.6128784 +0000 UTC}
2019-04-18T19:38:12.262-0400 [DEBUG] secrets.ad.ad_fd06940f: rotating password for the first time so Vault will know it
2019-04-18T19:38:17.243-0400 [DEBUG] secrets.ad.ad_fd06940f: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com TTL:7776000 LastVaultRotation:2019-04-18 23:38:13.341055573 +0000 UTC PasswordLastSet:2019-04-18 23:38:14.091544 +0000 UTC}
2019-04-18T19:38:17.243-0400 [DEBUG] secrets.ad.ad_fd06940f: determining whether to rotate credential
2019-04-18T19:38:17.243-0400 [DEBUG] secrets.ad.ad_fd06940f: checking stored credential
2019-04-18T19:38:17.243-0400 [DEBUG] secrets.ad.ad_fd06940f: returning previous credential
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=auth/ldap/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=sys/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=identity/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=apps/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=users/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=shared/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=metadata/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=ad/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=cubbyhole/
2019-04-18T19:38:26.614-0400 [DEBUG] rollback: attempting rollback: path=auth/token/
2019-04-18T19:38:44.108-0400 [DEBUG] secrets.ad.ad_fd06940f: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com TTL:7776000 LastVaultRotation:2019-04-18 23:38:13.341055573 +0000 UTC PasswordLastSet:2019-04-18 23:38:14.091544 +0000 UTC}
2019-04-18T19:38:44.108-0400 [DEBUG] secrets.ad.ad_fd06940f: determining whether to rotate credential
2019-04-18T19:38:44.108-0400 [DEBUG] secrets.ad.ad_fd06940f: checking stored credential
2019-04-18T19:38:44.108-0400 [DEBUG] secrets.ad.ad_fd06940f: returning previous credential
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=auth/ldap/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=sys/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=identity/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=apps/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=users/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=shared/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=metadata/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=ad/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=cubbyhole/
2019-04-18T19:39:26.614-0400 [DEBUG] rollback: attempting rollback: path=auth/token/
2019-04-18T19:39:26.759-0400 [DEBUG] secrets.ad.ad_fd06940f: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com.com TTL:7776000 LastVaultRotation:2019-04-18 23:38:13.341055573 +0000 UTC PasswordLastSet:2019-04-18 23:38:14.091544 +0000 UTC}
2019-04-18T19:39:26.759-0400 [DEBUG] secrets.ad.ad_fd06940f: determining whether to rotate credential
2019-04-18T19:39:26.759-0400 [DEBUG] secrets.ad.ad_fd06940f: checking stored credential
2019-04-18T19:39:26.759-0400 [DEBUG] secrets.ad.ad_fd06940f: returning previous credential
2019-04-18T19:39:28.378-0400 [DEBUG] secrets.ad.ad_fd06940f: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com.com TTL:7776000 LastVaultRotation:2019-04-18 23:38:13.341055573 +0000 UTC PasswordLastSet:2019-04-18 23:38:14.091544 +0000 UTC}
2019-04-18T19:39:28.378-0400 [DEBUG] secrets.ad.ad_fd06940f: determining whether to rotate credential
2019-04-18T19:39:28.378-0400 [DEBUG] secrets.ad.ad_fd06940f: checking stored credential
2019-04-18T19:39:28.379-0400 [DEBUG] secrets.ad.ad_fd06940f: returning previous credential
```

**Comment by sivanag1974** [comment] 2019-04-24 21:23
Here is the information you requested:
I refreshed my local with your latest code changes:

**git pull**
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 12 (delta 3), reused 7 (delta 3), pack-reused 0
Unpacking objects: 100% (12/12), done.
From https://github.com/hashicorp/vault-plugin-secrets-ad
   3d011d0..be17c98  master     -> origin/master
Updating 3d011d0..be17c98
Fast-forward
 plugin/path_creds.go      |  10 ++++++----
 plugin/path_creds_test.go | 118 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 plugin/path_roles.go      |  10 ++++++----
 plugin/util/passwords.go  |   2 +-
 4 files changed, 131 insertions(+), 9 deletions(-)
 create mode 100644 plugin/path_creds_test.go

**Rebuild the plugin:**
 vault write sys/plugins/catalog/secret/active-directory sha_256=97f97745a92b9f40268b3bf756f573e8a6226a19f47aceeaab25cef111f892fd command=vault-plugin-secrets-active-directory
Success! Data written to: sys/plugins/catalog/secret/active-directory

**Enabled again**
vault secrets enable active-directory
Success! Enabled the active-directory secrets engine at: active-directory/

**Configured as**

[root@dev-ops]# vault write active-directory/config   binddn=vault_test1     bindpass=vault_pass url=ldaps://ip_address    userdn="OU=Accounts,DC=aaa,DC=bbb,DC=ccc,DC=com" insecure_tls=true ttl=7776000 max_ttl=7776000
Success! Data written to: active-directory/config

**Reading**
[root@dev-ops]# vault write active-directory/roles/vault_test2 service_account_name="vault_test2@aaa.bbb.ccc.com"
Success! Data written to: active-directory/roles/vault_test2

Read passwords:

[root@dev-ops]# vault read active-directory/creds/vault_test2
Key                 Value
---                 -----
current_password    ?@09AZTDrSSdmEkpEqjuxZ05uLGrWuM0/d/y/8h9toM1T7SMP1zml7wUEEut3ZfW
username            vault_test2
[root@dev-ops]# vault read active-directory/creds/vault_test2
Key                 Value
---                 -----
current_password    ?@09AZCt7Ggnjgqkt6IQQcOvT9ShS9Ln63ESw7+xuR7dAJFfF0NaWChLqS0o/TUQ
username            vault_test2
[root@dev-ops]# vault read active-directory/creds/vault_test2
Key                 Value
---                 -----
current_password    ?@09AZ/9OpvauZsgPEcYnM7Am6ESrlPXZQzZ9EAtkulgz9Kd6QFbhhZ0whSxXzmi
username            vault_test2

Corresponding Logs:

2019-04-24T17:10:16.431-0400 [DEBUG] secrets.active-directory.active-directory_cfa72c5e.active-directory.vault-plugin-secrets-active-directory: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com TTL:7776000 LastVaultRotation:0001-01-01 00:00:00 +0000 UTC PasswordLastSet:2019-04-24 20:46:25.8134313 +0000 UTC}: timestamp=2019-04-24T17:10:16.431-0400
2019-04-24T17:10:16.432-0400 [DEBUG] secrets.active-directory.active-directory_cfa72c5e.active-directory.vault-plugin-secrets-active-directory: rotating password for the first time so Vault will know it: timestamp=2019-04-24T17:10:16.431-0400
2019-04-24T17:10:19.884-0400 [DEBUG] secrets.active-directory.active-directory_cfa72c5e.active-directory.vault-plugin-secrets-active-directory: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com TTL:7776000 LastVaultRotation:2019-04-24 21:10:17.506055129 +0000 UTC PasswordLastSet:2019-04-24 21:10:18.6711926 +0000 UTC}: timestamp=2019-04-24T17:10:19.884-0400
2019-04-24T17:10:19.884-0400 [DEBUG] secrets.active-directory.active-directory_cfa72c5e.active-directory.vault-plugin-secrets-active-directory: Vault rotated the password at 2019-04-24 21:10:17.506055129 +0000 UTC, but it was rotated in AD later at 2019-04-24 21:10:18.6711926 +0000 UTC, so rotating it again so Vault will know it: timestamp=2019-04-24T17:10:19.884-0400
2019-04-24T17:10:25.567-0400 [DEBUG] rollback: attempting rollback: path=auth/ldap/
2019-04-24T17:10:25.568-0400 [DEBUG] rollback: attempting rollback: path=sys/
2019-04-24T17:10:25.568-0400 [DEBUG] rollback: attempting rollback: path=identity/
2019-04-24T17:10:25.568-0400 [DEBUG] rollback: attempting rollback: path=apps/
2019-04-24T17:10:25.568-0400 [DEBUG] rollback: attempting rollback: path=users/
2019-04-24T17:10:25.568-0400 [DEBUG] rollback: attempting rollback: path=shared/
2019-04-24T17:10:25.568-0400 [DEBUG] rollback: attempting rollback: path=metadata/
2019-04-24T17:10:25.568-0400 [DEBUG] rollback: attempting rollback: path=cubbyhole/
2019-04-24T17:10:25.568-0400 [DEBUG] rollback: attempting rollback: path=active-directory/
2019-04-24T17:10:25.568-0400 [DEBUG] rollback: attempting rollback: path=auth/token/
2019-04-24T17:11:02.526-0400 [DEBUG] secrets.active-directory.active-directory_cfa72c5e.active-directory.vault-plugin-secrets-active-directory: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com TTL:7776000 LastVaultRotation:2019-04-24 21:10:20.957142843 +0000 UTC PasswordLastSet:2019-04-24 21:10:22.1221118 +0000 UTC}: timestamp=2019-04-24T17:11:02.525-0400
2019-04-24T17:11:02.526-0400 [DEBUG] secrets.active-directory.active-directory_cfa72c5e.active-directory.vault-plugin-secrets-active-directory: Vault rotated the password at 2019-04-24 21:10:20.957142843 +0000 UTC, but it was rotated in AD later at 2019-04-24 21:10:22.1221118 +0000 UTC, so rotating it again so Vault will know it: timestamp=2019-04-24T17:11:02.525-0400
2019-04-24T17:11:25.568-0400 [DEBUG] rollback: attempting rollback: path=auth/ldap/
2019-04-24T17:11:25.568-0400 [DEBUG] rollback: attempting rollback: path=sys/
2019-04-24T17:11:25.568-0400 [DEBUG] rollback: attempting rollback: path=identity/
2019-04-24T17:11:25.568-0400 [DEBUG] rollback: attempting rollback: path=apps/
2019-04-24T17:11:25.568-0400 [DEBUG] rollback: attempting rollback: path=users/
2019-04-24T17:11:25.568-0400 [DEBUG] rollback: attempting rollback: path=shared/
2019-04-24T17:11:25.568-0400 [DEBUG] rollback: attempting rollback: path=metadata/
2019-04-24T17:11:25.568-0400 [DEBUG] rollback: attempting rollback: path=cubbyhole/
2019-04-24T17:11:25.568-0400 [DEBUG] rollback: attempting rollback: path=active-directory/
2019-04-24T17:11:25.568-0400 [DEBUG] rollback: attempting rollback: path=auth/token/
2019-04-24T17:11:44.267-0400 [DEBUG] secrets.active-directory.active-directory_cfa72c5e.active-directory.vault-plugin-secrets-active-directory: role is: &{ServiceAccountName:vault_test2@aaa.bbb.ccc.com TTL:7776000 LastVaultRotation:2019-04-24 21:11:03.592985061 +0000 UTC PasswordLastSet:2019-04-24 21:11:04.7591743 +0000 UTC}: timestamp=2019-04-24T17:11:44.267-0400
2019-04-24T17:11:44.267-0400 [DEBUG] secrets.active-directory.active-directory_cfa72c5e.active-directory.vault-plugin-secrets-active-directory: Vault rotated the password at 2019-04-24 21:11:03.592985061 +0000 UTC, but it was rotated in AD later at 2019-04-24 21:11:04.7591743 +0000 UTC, so rotating it again so Vault will know it: timestamp=2019-04-24T17:11:44.267-0400

**Comment by sivanag1974** [comment] 2019-04-24 22:41
I have seen the following behavior (sometimes):
First time, if I configure the role correctly, I am getting the password correctly (not rotating until ttl - 10 seconds).
Upon reaching the ttl(10 seconds), vault rotates the password and gives both passwords (current_password and last_password)
From this point on, I am getting different passwords, whenever I read (even before ttl expires)

I am not sure whether is additional information is useful to you

**Comment by tyrannosaurus-becks** [comment] 2019-04-25 23:21
@sivanag1974 thank you for following up.

I see the issue! It's this:
```
2019-04-24T17:11:02.526-0400 [DEBUG] secrets.active-directory.active-directory_cfa72c5e.active-directory.vault-plugin-secrets-active-directory: Vault rotated the password at 2019-04-24 21:10:20.957142843 +0000 UTC, but it was rotated in AD later at 2019-04-24 21:10:22.1221118 +0000 UTC, so rotating it again so Vault will know it: timestamp=2019-04-24T17:11:02.525-0400
```
Active Directory is eventually consistent, so it can take a while for a password rotation to be populated throughout the cluster. So even though Vault _sent_ the password rotation at 2019-04-24 21:10:20.957142843 +0000 UTC, it wasn't really _finished_ in your Active Directory environment until 2019-04-24 21:10:22.1221118 +0000 UTC. That's over a second later. 

There's a buffer of time built into the engine where, if Active Directory shows that the password was rotated over a second later than Vault, then Vault thinks somebody else rotated it out-of-band and then rotates it again to get it back into sync.

That one second buffer is clearly not sufficient in your case. It was a number picked at random. In reality, the length of time needed will vary based on how large people's Active Directory clusters are.

Anyways, I will make this setting configurable. Thank you for sticking with this and bringing it to my attention!

**Comment by tyrannosaurus-becks** [comment] 2019-04-25 23:44
Feel free to follow along with the PR above to track the fix.

**Comment by tyrannosaurus-becks** [comment] 2019-04-26 16:42
Closing this, as the fix has been merged into the plugin. This will become available with Vault out-of-the-box in the next release.

**Closed by tyrannosaurus-becks** 2019-04-26 16:42 UTC

**Comment by sivanag1974** [comment] 2019-05-09 22:28
Thank you.
When is the next release? Any tentative date?

**Comment by sarathmohan4** [comment] 2019-05-22 05:32
Any tentative release date planed for this? @tyrannosaurus-becks
