### ISSUE TITLE
UI - LDAP Auth Method TLS Certificate Input

### ISSUE THREAD

**Issue by jmariondev** [hashicorp/vault#7187] opened 2019-07-24 22:07 UTC
**Describe the bug**
The form to configure an LDAP auth method has a field that takes a PEM-encoded cert, but does not support multi-line input. This causes the error "failed to decode PEM block in the certificate" as it seems to strip newlines from the input.

**To Reproduce**
1. Enable an LDAP auth method
2. Attempt to set a certificate for the method in the UI (eg `/ui/vault/settings/auth/configure/ldap/configuration`)

**Expected behavior**
The form input used to be multi-line (or file selection?), which allowed multi-line input. This allowed the certificate data to save properly.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.3+prem
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.3 ('9bc820f700f83a7c4bcab54c5323735a581b34eb')
* Server Operating System/Architecture: CentOS 7 amd64

**Comment by ankushkumar11** [comment] 2019-07-27 14:40
Even, I got the same error while i was trying to configure LDAP using UI. Then, I tried vault cli. vault write auth/ldap/config and it worked for me.

**Comment by horpek** [comment] 2019-09-04 08:30
I try to configure ldap via API (with ansible) and I hit the same issue too.  Glad to learn if anyone has successfully done it and how.

**Comment by ndobbs** [comment] 2019-11-06 14:45
I just ran into this issue as well, using the CLI worked for me. 

![image](https://user-images.githubusercontent.com/3474164/68307990-19f94c80-007a-11ea-8cfe-239f91b6d153.png)

**Comment by rbigeard** [comment] 2020-01-16 23:11
Hitting this problem with Vault 1.3.x but not Vault 1.2.x. Could there be a regression?

I have tried the CLI, the Json payload method and the UI, same "failed to decode PEM block in the certificate" error.

The CLI method (vault write auth/ldap/config) worked fine with 1.2.x

**Comment by rbigeard** [comment] 2020-01-17 03:09
I managed to make it work and it looks like the order or parameters when passed to the cli matters.

**Comment by PG-TwinsFan** [comment] 2020-01-21 20:05
> I managed to make it work and it looks like the order or parameters when passed to the cli matters.

can you share what order you used via the CLI to get this to work?  Seeing the same thing.

**Comment by rbigeard** [comment] 2020-01-28 04:03
@PG-TwinsFan

(redacted for security reasons)

vault write auth/ldap/config \
    url=xxxx \
    userattr=xxxx \
    userdn=xxxx\
    groupdn=xxxx\
    groupattr="cn" \
    groupfilter=xxxx \
    groupattr="memberOf" \
    binddn=xxxx \
    bindpass=xxxx \
    certificate=@pemfile \
    insecure_tls=true \
    starttls=false

**Comment by Monkeychip** [comment] 2020-03-17 17:46
@jmariondev thank you for the ticket.  This will be fixed in 1.4.  See the [PR for details.](https://github.com/hashicorp/vault/pull/8573).

**Closed** 2020-03-17 17:46 UTC
Labels: bug, ecosystem, ticketed, ui, version/1.1.x
