### ISSUE TITLE
Vault Service stucks in reloading state

### ISSUE THREAD

**Issue by s01u5** [hashicorp/vault#15221] opened 2022-04-29 07:01 UTC
**Environment:**

* Vault Version: `Vault v1.10.0 (7738ec5d0d6f5bf94a809ee0f6ff0142cfa525a6)`
* Operating System/Architecture: `Ubuntu 20.04 LTS`

**Vault Config File:**

```# Storage configuration
storage "raft" {
  path = "/opt/vault/raft/"
  node_id = "node_1"
}

listener "tcp" {
  address = "192.168.56.103:8200"
  tls_disable = "true"
}

api_addr = "http://192.168.56.103:8200"
cluster_addr = "http://192.168.56.103:8201"
disable_mlock = true
ui=true

seal "transit" {
  address = "http://192.168.56.102:8200"
  disable_renewal = "false"
  key_name = "autounseal"
  mount_path = "transit/"
  token = "<token-here>"
  tls_skip_verify = "true"
}

log_level = "Debug"
```

**Startup Log Output:**
Vault logs of restart `sudo systemctl restart vault.service`

![image](https://user-images.githubusercontent.com/28089232/165899571-45226972-184e-4f40-a422-13694b5a35c4.png)

**Expected Behavior:**
Vault should successfully reload.

**Actual Behavior:**
Vault gets stuck in a reloading state.

**Steps to Reproduce:**
1.  Vault logrotate Config 

```
/var/log/vault/audit.log {
  daily
  rotate 7
  notifempty
  missingok
  compress
  delaycompress
  postrotate
  #     /usr/bin/systemctl reload vault 2> /dev/null || true
     /usr/bin/kill -HUP `pidof vault` >> /home/solus/stderr.log 2>&1 || true
  endscript
  create 0600 vault vault
}
```

2. Run the logrotate manually `sudo logrotate -vf /etc/logrotate.d/vault`
3. Check the status of vault `sudo systemctl status vault.service`

![image](https://user-images.githubusercontent.com/28089232/165899332-6a7eb7f7-6cd5-4f08-b413-49282946f419.png)

**Important Factoids:**

**References:**

https://discuss.hashicorp.com/t/vault-stucks-in-reloading-state/38762/7

**Comment by hsimon-hashicorp** [comment] 2022-04-29 17:32
The amazing @maxb thinks the issue may come from here: https://github.com/hashicorp/vault/blob/0be45d012023c8db13a20fdf17ed66115df43b78/command/server.go#L1547

**Comment by maxb** [comment] 2022-04-30 06:53
:slightly_smiling_face: 

Specifically, the above-mentioned code doesn't implement this requirement:

> Note that a service that sends this notification must also send a "READY=1" notification when it completed reloading its configuration.

Documented at https://www.freedesktop.org/software/systemd/man/sd_notify.html

**Comment by jdoss** [comment] 2022-05-03 04:02
This issue is a dupe of https://github.com/hashicorp/vault/issues/7028

There are two PRs that are open that address this issue. The first one seems a bit more complete.

https://github.com/hashicorp/vault/pull/9802
https://github.com/hashicorp/vault/pull/15041

**Comment by jdoss** [comment] 2022-05-03 05:20
Actually, I take that back https://github.com/hashicorp/vault/pull/15041 builds cleanly after a quick rebase on main. https://github.com/hashicorp/vault/pull/9802 is going to need some love to get it up to speed. 

After testing https://github.com/hashicorp/vault/pull/15041 it does let vault reload but it doesn't seem to work when using system to do a `reload-or-restart` such as `ExecStartPost=systemctl reload-or-restart vault.service`

**Comment by ncabatoff** [comment] 2022-05-03 12:35
@jdoss #9802 is actually about systemd for agent, not server.  Thanks for testing #15041.  I'm not sure what we should about the reload-or-restart case, but it seems like support for reload is progress anyway so I'm merging it.

**Closed** 2022-05-03 15:39 UTC
Labels: bug, good-first-issue, core

**Comment by jdoss** [comment] 2022-05-04 03:12
Thanks @ncabatoff !!
