### ISSUE TITLE
CLI binary ignores VAULT_TOKEN environment variable

### ISSUE THREAD

**Issue by wskorodecki** [hashicorp/vault#15151] opened 2022-04-25 08:29 UTC
**Describe the bug**
CLI binary ignores **VAULT_TOKEN** environment variable.

**To Reproduce**
```shell
$ export VAULT_TOKEN=your_token
$ echo $VAULT_TOKEN
your_token

$ vault login
Token (will be hidden): 

$ VAULT_TOKEN=your_token vault login
Token (will be hidden):

$ vault login - < <( echo "${VAULT_TOKEN}" )
Error authenticating: error looking up token: Get "https://127.0.0.1:8200/v1/auth/token/lookup-self": dial tcp 127.0.0.1:8200: connect: connection refused
```

The last command is a bit tricky but currently we are forced to use it in our scripts as a workaround.

**Expected behavior**
It should use the value like described in https://learn.hashicorp.com/tutorials/vault/getting-started-authentication#token-authentication

```
The Vault CLI read the root token from the $VAULT_TOKEN environment variable.
```

**Environment:**
* Vault CLI Version: v1.10.1 ('e452e9b30a9c2c8adfa1611c26eb472090adc767+CHANGES')
* OS: ArchLinux, kernel 5.17.4

**Comment by maxb** [comment] 2022-04-25 22:38
When you run `vault login` with `VAULT_TOKEN` already set, it prints a warning to explain things to you:

```
WARNING! The VAULT_TOKEN environment variable is set! This takes precedence
over the value set by this command. To use the value set by this command,
unset the VAULT_TOKEN environment variable or set it to the token displayed
below.
```

The CLI is functioning as intended.

> The last command is a bit tricky but currently we are forced to use it in our scripts as a workaround.

No, just don't run this command at all - it is not necessary, and other `vault` CLI commands will read and use the `VAULT_TOKEN` environment variable directly anyway.

**Comment by hsimon-hashicorp** [comment] 2022-04-25 23:38
Thanks as always for your assist, @maxb! @wskorodecki can you let us know if that explanation helps?

**Comment by wskorodecki** [comment] 2022-04-26 08:09
So `vault login` command is not necessary in scripts. That explains everything. Thank you @maxb

**Comment by raskchanky** [comment] 2022-04-26 16:48
> The command vault login is necessary always, but it will automatically read the VAULT_TOKEN environment variable, so you don't need to pass it through STDIN.

> If you're already performing export VAULT_TOKEN=your_token in a previous step of your script, you can just run vault login without anything else.

This is actually not true. The main purpose of `vault login` is to authenticate the user and return a Vault token. If you already have a Vault token, you can set it in the `VAULT_TOKEN` env var, and `vault login` is no longer necessary. The Vault API only cares about the token.

**Comment by hsimon-hashicorp** [comment] 2022-04-26 16:59
Since it seems like the question has been answered (and thank you @raskchanky as well!) I will go ahead and close this issue. Please feel free to file a new issue if there's a bug to report, and also check out the [Vault Discuss forum](https://discuss.hashicorp.com/c/vault/30) for more Q&A-style interactions. Thanks!

**Closed by hsimon-hashicorp** 2022-04-26 16:59 UTC
Labels: core/cli, question, core/token

**Comment by maxb** [comment] 2022-04-28 19:09
A final comment to wrap this one up:

The `vault login` implements three separate but related pieces of functionality:
* Calling a Vault HTTP API, to exchange auth-method-dependent credentials for a Vault token
* Calling a Vault HTTP API, to look up additional information about a directly provided token
* Storing a Vault token in `~/.vault-token` or a configured token helper program

The first is activated by the `-method` flag.

The second takes place when the `-method` flag is not used, and a pre-existing token is supplied on the command line or via standard input.

The third happens by default but can be disabled with the `-no-store` flag.

Hopefully that helps explain why it is used in so many ways.
