### ISSUE TITLE
Error deleting/updating orphaned Entity Alias

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/vault#15688] opened 2022-05-31 09:25 UTC
**Describe the bug**

I have an orphaned Entity Alias that is associated with with an Entity that no longer exists, and an auth mount that no longer exist.

Whenever I try to update or delete the alias, I get the error 

```
vault delete identity/entity-alias/id/6efd37dd-51f7-7b6d-97b0-c739773e5ee8 

Error deleting at: identity/entity-alias/id/6efd37dd-51f7-7b6d-97b0-c739773e5ee8.
URL: /v1/identity/entity-alias/id/6efd37dd-51f7-7b6d-97b0-c739773e5ee8
Code: 500
Errors:
  1 error occurred:
	* alias not associated to an entity

```

**To Reproduce**
1. Login with some auth method to cause the creation of an entity and entity alias.
2. Delete the entity.
3. Try to delete the entity alias.

**Expected behavior**

The deletion to succeed.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.10.3
* Vault CLI Version (retrieve with `vault version`): 1.10.3
* Server Operating System/Architecture: HCP Vault Standard Small (AWS)

Vault server configuration file(s):

N/A -- HCP Vault

**Additional context**

N/A

**Comment by hsimon-hashicorp** [comment] 2022-06-20 21:31
Hi there @lawliet89 - we have been unable to repro this using the steps provided. Is the "auth mount that no longer exists" part of the repro? For example, between steps 2 and 3, disable the auth method? Thanks in advance!

**Comment by raskchanky** [comment] 2022-06-21 23:09
Hi @lawliet89 

I'm having trouble reproducing this problem, namely because deleting the entity also deletes any associated aliases (at least when done [through the API](https://www.vaultproject.io/api-docs/secret/identity/entity#delete-entity-by-id)). Is there some other way that the entity is being deleted that results in an orphaned alias?

**Comment by lawliet89** [comment] 2022-06-22 08:30
I used the UI to delete it. Nothing special was done. I tried to disable the auth method to see if it will get rid of the entity alias but it did not. Would opening a HCP support case to diagnose this be useful befure the audit logs are auto-purged?

**Comment by raskchanky** [comment] 2022-06-24 18:28
@lawliet89 Was the entity you deleted the previous target of an entity merge? In other words, if I have 2 entities, A and B, and I merge B into A, and then delete A. If so, that might provide a clue as to what's happening here.

**Comment by lawliet89** [comment] 2022-06-27 02:19
Yes it was. Thanks, I forgot to mention that.

**Comment by VioletHynes** [comment] 2022-08-10 16:52
Closing - this should be fixed by the following PR: https://github.com/hashicorp/vault/pull/16539

This behaviour was caused by a merge leaving one of the aliases in an unfortunate state. We've changed the way merges work to prevent this kind of behaviour in the future.

**Closed by VioletHynes** 2022-08-10 16:52 UTC
Labels: bug, waiting-for-response, core/identity
