### ISSUE TITLE
New auth backend: oauth2

### ISSUE THREAD

**Issue by leeavital** [hashicorp/vault#2716] opened 2017-05-11 17:20 UTC
Hey Vault devs,

This is less of an issue and more of a feature idea.

Our organization uses a custom service for managing authentication that implements the oauth2 spec. We wanted to allow vault to authenticate against this service, but there's no appropriate auth backend.

So: our idea was to add a new auth backend called `oauth2`. You would be able to use it like so:

```
# configure the user and group endpoints, these would authenticate using `Authentication: Bearer  ...` as per the oauth2 spec. The JSON returned must be an object with a configured key that represents the user ID
vault write auth/oauth2/config/urls/user url=https://service.com/api/me field=id

# similar to user, returns a *list* of objects with a configured key to represent each user ID.
vault write auth/oauth2/config/urls/groups url=https://service.com/api/groups field=id

# bind policies to a user
vault write auth/oauth2/users/{userId} policies=...
vault write auth/oauth2/groups/{groupId} policies=... 

# you can login with your API token
vault write auth/oauth2/login token=@token.txt
```

Would this be a reasonable addition? We would be glad to contribute something like this.

**Comment by jefferai** [comment] 2017-05-11 21:14
Duplicate of #2525

**Closed by jefferai** 2017-05-11 21:14 UTC
