### ISSUE TITLE
Some error messages may benefit from further clarification

### ISSUE THREAD

**Issue by fernando-villalba** [hashicorp/vault#10420] opened 2020-11-19 12:49 UTC
Using Vault 1.5.4 Open Source version.

We are using vault with a variety of kubernetes auth roles and occasionally the vault server will spit out some of these error messages.

`Nov 19 08:27:50 ip-172-40-66-110 vault: 2020-11-19T08:27:50.963Z [ERROR] core: failed to lookup token: error="failed to look up namespace from the token: no namespace"`

The above to me translates something like: "somewhere, an error happened, possibly with a malformed token or expired token"

But that's just me guessing

When correlating this with audit logs I can find nothing or relevance that indicates what is causing them.

It would be very useful if more context was given, or if these errors were part of the audit logging, maybe providing some additional information, such as origin ip address, etc.

**Comment by swayne275** [comment] 2020-11-20 23:11
This is a great suggestion. I'll bring it up with my team to think about providing more actionable info in error messages. If you have any other examples of things that don't help you diagnose the issue, please comment below. Thanks!

**Comment by swayne275** [comment] 2020-11-23 21:12
How could we consistently reproduce this error?

**Comment by fernando-villalba** [comment] 2020-11-24 15:41
@swayne275 It's not easy for me to tell what's causing them, hence why I opened this ticket. We are using a third party kubernetes application that has a installer that creates some kubernetes roles and secrets in Vault and that's what's causing these errors to happen, but because Vault is not giving me any more context here and neither is the application we are using, it was hard for me to provide more details. 

Will try and see next time we run this installer, hopefully I can provide further information.

I suppose it would be useful to know under what circumstances Vault spits out the error "failed to lookup namespace". Because we are using Kubernetes it is confusing if it is referring to an actual kubernetes namespace or a Vault namespace (which is not used at all in the open source version of Vault I am using as far as I know)

**Comment by swayne275** [comment] 2020-12-04 00:17
@fernando-villalba it looks like a malformed token may be able to trigger this error. Can you provide an example of an actual token used when this error happens?

**Comment by swayne275** [comment] 2021-01-06 19:21
Closing because this issue has been without update for 30+ days. Please re-open if it hasn't been resolved.

**Closed by swayne275** 2021-01-06 19:21 UTC
Labels: enhancement, error-messages, k8s, version/1.5.x, waiting-for-response
