### ISSUE TITLE
Unable to pass in multiple words to `-description` flag

### ISSUE THREAD

**Issue by tonglil** [hashicorp/vault#9090] opened 2020-05-27 19:37 UTC
**Describe the bug**
Is it a limitation or a bug when trying to pass a `description` of multiple words for `vault secret enable` and `vault secret tune`, the CLI returns an error?

https://github.com/hashicorp/vault/blob/2b8cac726089beed10fe3d9a4cec7e9655c82ccf/command/secrets_tune.go#L82-L87

**To Reproduce**

```
vault secrets tune -description="manage pki for team x" "pki/"
```
results in:
```
Too many arguments (expected 1, got 5)
```

**Expected behavior**
That the secret has a description of multiple words, such as:
````
secret/                                 generic                        generic_2f1c5577                        encrypted key/value storage
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.2.4
* Vault CLI Version (retrieve with `vault version`): 1.3.4
* Server Operating System/Architecture: Darwin

Vault server configuration file(s): n/a

**Additional context**
Add any other context about the problem here.

**Comment by austingebauer** [comment] 2020-05-27 23:35
@tonglil - I'm not able to reproduce the error you're seeing. I'm executing `vault secrets enable pki` followed by `vault secrets tune -description="manage pki for team x" "pki/"` without any error. I also see that the description is successfully updated. I did this using the same Vault version(s) as you. Are you able to provide any additional steps or context to help?

**Comment by raskchanky** [comment] 2020-09-16 16:47
Hi @tonglil 

We haven’t heard back from you on this for a while. I’m going to close this for now, but please feel free to re-open it with additional information!

**Closed by raskchanky** 2020-09-16 16:47 UTC
Labels: bug, core/cli, waiting-for-response
