### ISSUE TITLE
Error authenticating: Error looking up token: redirect would cause protocol downgrade

### ISSUE THREAD

**Issue by pandeybk** [hashicorp/vault#4085] opened 2018-03-06 22:09 UTC
I am trying to setup vault in kubernetes cluster. Using RDS as storage backend and consul as ha_storage backend. Here is my cluster configuration looks like 

```
    listener "tcp" {
        address = "0.0.0.0:8200"
        tls_cert_file = "/vault/config/cert.pem"
        tls_key_file = "/vault/config/cert.key"
        tls_disable = 0
      }

    listener "tcp" {
        address = "0.0.0.0:9000"
        tls_disable = 1
      }

    storage "mysql" {
        address = "somerds.us-west-2.rds.amazonaws.com:3306"
        username = "someuser"
        password = "somepassword"
        database = "somedatabase"
        table = "sometable"
        }

    ha_storage "consul" {
        scheme = "http"
        address = "consul.consul:8500"
        cluster_addr = "https://vault.vault:8200"
        path = "/consul/data/"
        disable_registration = "true"
        tls_cert_file = "/vault/config/cert.pem"
        tls_key_file = "/vault/config/cert.key"
        tls_ca_file = "/vault/config/ca.pem"
    }
```

Without ha_storage backend vault is working perfectly fine. But with ha_storage configuration we are not able to communicate with vault. Seeing following issue,

```
[vault-5fcc69bf45-4c9sl] ==> Vault server configuration: 
[vault-5fcc69bf45-4c9sl]  
[vault-5fcc69bf45-4c9sl] HA Storage: consul 
[vault-5fcc69bf45-4c9sl] Cgo: disabled 
[vault-5fcc69bf45-4c9sl] Cluster Address: https://vault.vault:8201 
[vault-5fcc69bf45-4c9sl] Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled") 
[vault-5fcc69bf45-4c9sl] Listener 2: tcp (addr: "0.0.0.0:9000", cluster address: "0.0.0.0:9001", tls: "disabled") 
[vault-5fcc69bf45-4c9sl] Log Level: err 
[vault-5fcc69bf45-4c9sl] Mlock: supported: true, enabled: true 
[vault-5fcc69bf45-4c9sl] Redirect Address: https://vault.vault:8200 
[vault-5fcc69bf45-4c9sl] Storage: mysql 
[vault-5fcc69bf45-4c9sl] Version: Vault v0.9.4 
[vault-5fcc69bf45-4c9sl] Version Sha: 2e2c89a3d8d2f4876c64dee6ba3d4a5e08691aee 
[vault-5fcc69bf45-4c9sl]  
[vault-5fcc69bf45-4c9sl] ==> Vault server started! Log data will stream in below: 
[vault-5fcc69bf45-4c9sl] 2018/03/06 21:49:41.449910 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure 
[vault-5fcc69bf45-4c9sl] 2018/03/06 21:49:41.450047 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request 
[vault-5fcc69bf45-4c9sl] 2018/03/06 21:49:41.450198 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure 
[vault-5fcc69bf45-4c9sl] 2018/03/06 21:49:41.450223 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request 
[vault-5fcc69bf45-4c9sl] 2018/03/06 21:49:41.450565 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure 
[vault-5fcc69bf45-4c9sl] 2018/03/06 21:49:41.450590 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request 
```

When we try to login to vault using root token seeing following error,
```
vault login $root_token
Error authenticating: Error looking up token: redirect would cause protocol downgrade
```
And from one of the consul server we are seeing following error,

  ```
  2018/03/06 21:30:37 [ERR] http: Request PUT /v1/agent/check/pass/vault:100.122.185.228:9000:vault-sealed-check?note=Vault+Unsealed, error: CheckID "vault:100.122.185.228:9000:vault-sealed-check" does not have associated TTL from=100.122.185.200:51468
    2018/03/06 21:30:37 [DEBUG] http: Request PUT /v1/agent/check/pass/vault:100.122.185.228:9000:vault-sealed-check?note=Vault+Unsealed (53.671µs) from=100.122.185.200:51468
    2018/03/06 21:30:37 [DEBUG] agent: Check 'vault:100.109.168.168:9000:vault-sealed-check' status is now passing
    2018/03/06 21:30:37 [DEBUG] agent: Service 'vault:100.109.168.168:9000' in sync
    2018/03/06 21:30:37 [DEBUG] agent: Check 'vault:100.109.168.168:9000:vault-sealed-check' in sync
    2018/03/06 21:30:37 [DEBUG] agent: Node info in sync
    2018/03/06 21:30:37 [DEBUG] http: Request PUT /v1/agent/check/pass/vault:100.109.168.168:9000:vault-sealed-check?note=Vault+Unsealed (377.07µs) from=100.122.185.203:32806
    2018/03/06 21:30:38 [DEBUG] agent: Check 'vault:100.109.168.168:9000:vault-sealed-check' status is now passing
    2018/03/06 21:30:38 [DEBUG] agent: Service 'vault:100.109.168.168:9000' in sync
    2018/03/06 21:30:38 [DEBUG] agent: Check 'vault:100.109.168.168:9000:vault-sealed-check' in sync
    2018/03/06 21:30:38 [DEBUG] agent: Node info in sync
    2018/03/06 21:30:38 [DEBUG] http: Request PUT /v1/agent/check/pass/vault:100.109.168.168:9000:vault-sealed-check?note=Vault+Unsealed (392.462µs) from=100.118.164.90:53044
    2018/03/06 21:30:38 [ERR] http: Request PUT /v1/agent/check/pass/vault:100.122.185.228:9000:vault-sealed-check?note=Vault+Unsealed, error: CheckID "vault:100.122.185.228:9000:vault-sealed-check" does not have associated TTL from=100.122.185.200:51468
    2018/03/06 21:30:38 [DEBUG] http: Request PUT /v1/agent/check/pass/vault:100.122.185.228:9000:vault-sealed-check?note=Vault+Unsealed (70.09µs) from=100.122.185.200:51468
    2018/03/06 21:30:38 [DEBUG] http: Request GET /v1/kv/consul/data/core/lock (1.733861ms) from=100.122.185.203:32806
    2018/03/06 21:30:39 [DEBUG] http: Request GET /v1/kv/consul/data/core/lock (1.671776ms) from=100.122.185.200:51468
    2018/03/06 21:30:39 [DEBUG] http: Request GET /v1/kv/consul/data/core/lock (1.57219ms) from=100.122.185.203:32806
    2018/03/06 21:30:39 [ERR] http: Request PUT /v1/agent/check/pass/vault:100.122.185.228:9000:vault-sealed-check?note=Vault+Unsealed, error: CheckID "vault:100.122.185.228:9000:vault-sealed-check" does not have associated TTL from=100.122.185.200:51468
    2018/03/06 21:30:39 [DEBUG] http: Request PUT /v1/agent/check/pass/vault:100.122.185.228:9000:vault-sealed-check?note=Vault+Unsealed (53.492µs) from=100.122.185.200:51468
    2018/03/06 21:30:40 [ERR] http: Request PUT /v1/agent/check/pass/vault:100.122.185.228:9000:vault-sealed-check?note=Vault+Unsealed, error: CheckID "vault:100.122.185.228:9000:vault-sealed-check" does not have associated TTL from=100.122.185.200:51468
    2018/03/06 21:30:40 [DEBUG] http: Request PUT /v1/agent/check/pass/vault:100.122.185.228:9000:vault-sealed-check?note=Vault+Unsealed (54.014µs) from=100.122.185.200:51468
    2018/03/06 21:30:41 [DEBUG] http: Request PUT /v1/session/renew/8cc9063d-c50f-5b52-85c8-83f4e620087b (1.696978ms) from=100.122.185.200:51468
    2018/03/06 21:30:41 [DEBUG] http: Request GET /v1/kv/consul/data/core/lock (1.508466ms) from=100.122.185.203:32806
    2018/03/06 21:30:41 [DEBUG] http: Request GET /v1/kv/consul/data/core/lock (1.691428ms) from=100.122.185.200:51468
    2018/03/06 21:30:41 [DEBUG] http: Request GET /v1/kv/consul/data/core/lock (1.577164ms) from=100.122.185.203:32806
    2018/03/06 21:30:41 [ERR] http: Request PUT /v1/agent/check/pass/vault:100.122.185.228:9000:vault-sealed-check?note=Vault+Unsealed, error: CheckID "vault:100.122.185.228:9000:vault-sealed-check" does not have associated TTL from=100.122.185.200:51468
```

**Comment by jefferai** [comment] 2018-03-07 05:15
Do you specifically need cluster_addr defined? It's set to a wrong port number, although oddly in your startup information it doesn't match what you set it to in the configuration.

It'd be useful if you can verify the info there, and if you can use `curl` to make the call with some level of verbosity so we can see where it's trying to redirect you to. Generally redirects aren't necessary at all except since your nodes aren't talking to each other it's falling back.

**Comment by pandeybk** [comment] 2018-03-07 17:53
cluster_addr is not mandatory, I am only playing with configuration. I removed that part still seeing issue. This is my HA configuration looks like now. 

```
   ha_storage "consul" {
        address = "consul.consul:8500"
        path = "/consul/data/"
        scheme = "http"
        disable_registration = "true"
      tls_cert_file = "/vault/config/cert.pem"
      tls_key_file = "/vault/config/cert.key"
      tls_ca_file = "/vault/config/ca.pem"
    }

```
And seeing following log,

 ```
kubectl logs vault-5fcc69bf45-2njpp   -n vault -c vault 
==> Vault server configuration:

              HA Storage: consul
                     Cgo: disabled
         Cluster Address: https://100.118.164.99:9001
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
              Listener 2: tcp (addr: "0.0.0.0:9000", cluster address: "0.0.0.0:9001", tls: "disabled")
               Log Level: err
                   Mlock: supported: true, enabled: true
        Redirect Address: http://100.118.164.99:9000
                 Storage: mysql
                 Version: Vault v0.9.4
             Version Sha: 2e2c89a3d8d2f4876c64dee6ba3d4a5e08691aee

==> Vault server started! Log data will stream in below:

2018/03/07 17:19:47.314081 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 17:19:47.314222 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 17:19:47.382058 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 17:19:47.382122 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 17:19:47.441868 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 17:19:47.441919 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 17:19:47.545593 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 17:19:47.546140 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 17:19:47.719568 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 17:19:47.719614 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 17:19:48.755097 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 17:19:48.755152 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 17:19:50.091911 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 17:19:50.091973 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 17:20:51.971325 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 17:20:51.971380 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 17:21:23.177151 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 17:21:23.177204 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 17:21:23.202186 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 17:21:23.202241 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
```

Curl command for init 

```
curl https://vault.vault:8200/v1/sys/init -k -vvv
* Hostname was NOT found in DNS cache
*   Trying 100.65.150.151...
* Connected to vault.vault (100.65.150.151) port 8200 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Request CERT (13):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: CN=vault-apiserver
* 	 start date: 2018-03-06 21:16:06 GMT
* 	 expire date: 2019-03-06 21:16:06 GMT
* 	 issuer: CN=kube-ca
* 	 SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /v1/sys/init HTTP/1.1
> User-Agent: curl/7.38.0
> Host: vault.vault:8200
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-store
< Content-Type: application/json
< Date: Wed, 07 Mar 2018 17:28:06 GMT
< Content-Length: 21
< 
{"initialized":true}
* Connection #0 to host vault.vault left intact
```
Curl command for login

```
curl -s -k --header "X-Vault-Token: $root_token" --request LIST "https://vault.vault:8200/v1/auth/token/accessors" -vvv
* Hostname was NOT found in DNS cache
*   Trying 100.65.150.151...
* Connected to vault.vault (100.65.150.151) port 8200 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Request CERT (13):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: CN=vault-apiserver
* 	 start date: 2018-03-06 21:16:06 GMT
* 	 expire date: 2019-03-06 21:16:06 GMT
* 	 issuer: CN=kube-ca
* 	 SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> LIST /v1/auth/token/accessors HTTP/1.1
> User-Agent: curl/7.38.0
> Host: vault.vault:8200
> Accept: */*
> X-Vault-Token: 738c0d55-127a-ee8c-f784-7c2299fdf0e8
> 
< HTTP/1.1 307 Temporary Redirect
< Cache-Control: no-store
< Location: http://100.109.168.162:9000/v1/auth/token/accessors
< Date: Wed, 07 Mar 2018 17:49:39 GMT
< Content-Length: 0
< 
* Connection #0 to host vault.vault left intact

```
Init seems working with vault command also.

```
VAULT_ADDR=https://vault.vault:8200 vault operator init
Error initializing: Error making API request.

URL: PUT https://vault.vault:8200/v1/sys/init
Code: 400. Errors:

* Vault is already initialized
```

However seeing problem with login

```
root@vault-5fcc69bf45-wxckj:/# VAULT_ADDR=https://vault.vault:8200 vault login $root_token
Error authenticating: Error looking up token: redirect would cause protocol downgrade
root@vault-5fcc69bf45-wxckj:/# VAULT_ADDR=https://vault.vault:8200 vault login $root_token
Error authenticating: Error looking up token: redirect would cause protocol downgrade
```

**Comment by pandeybk** [comment] 2018-03-07 18:10
Issue looks intermittent,

```
root@vault-5fcc69bf45-m5rm7:/# VAULT_SKIP_VERIFY=true VAULT_ADDR=https://vault.vault:8200 vault login $root_token
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                Value
---                -----
token              738c0d55-127a-ee8c-f784-7c2299fdf0e8
token_accessor     2ef00e89-298a-9313-4834-88d4066263b2
token_duration     ∞
token_renewable    false
token_policies     [root]
root@vault-5fcc69bf45-m5rm7:/# VAULT_SKIP_VERIFY=true VAULT_ADDR=https://vault.vault:8200 vault login $root_token
Error authenticating: Error looking up token: redirect would cause protocol downgrade

```

**Comment by pandeybk** [comment] 2018-03-07 19:05
I saw your comment on advertise_addr. I am moving with this configuration (without tls configuration for now). Seeing some progress, still testing 

```
ha_storage "consul" {
        scheme = "http"
        address = "consul.consul:8500"
        advertise_addr = "https://vault.vault:8200"
        path = "/consul/data/"
        disable_registration = "true"
    }
```

**Comment by pandeybk** [comment] 2018-03-07 21:13
Actually not seeing same error message again,

```
==> Vault server configuration:

              HA Storage: consul
                     Cgo: disabled
         Cluster Address: https://vault.vault:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
              Listener 2: tcp (addr: "0.0.0.0:9000", cluster address: "0.0.0.0:9001", tls: "disabled")
               Log Level: err
                   Mlock: supported: true, enabled: true
        Redirect Address: https://vault.vault:8200
                 Storage: mysql
                 Version: Vault v0.9.4
             Version Sha: 2e2c89a3d8d2f4876c64dee6ba3d4a5e08691aee

==> Vault server started! Log data will stream in below:

2018/03/07 21:07:13.999255 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:07:13.999649 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:07:34.001599 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:07:34.001668 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:07:54.001872 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:07:54.001931 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:07:54.002098 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:07:54.002125 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:08:14.002176 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:08:14.002240 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:08:14.002448 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:08:14.002482 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:08:34.002920 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:08:34.002983 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:08:34.003202 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:08:34.003229 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:08:54.003214 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:08:54.003278 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:09:14.004364 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:09:14.004422 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:09:14.004886 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:09:14.004921 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:09:14.005402 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:09:14.005445 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:09:14.006026 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:09:14.006061 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/07 21:09:14.006472 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/07 21:09:14.006507 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request

```

**Comment by pandeybk** [comment] 2018-03-07 22:35
If you look at my previous log somehow its showing 8201 in cluster address. Which is not the correct port.

```
Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
```

I change my config to following. In previous configuration it was taking time to get response from vault. Now I started getting faster response. But still same intermittent problem `< HTTP/1.1 307 Temporary Redirect`

```
    ha_storage "consul" {
        scheme = "http"
        address = "consul.consul:8500"
        cluster_addr = "https://vault.vault:8200"
        advertise_addr = "https://vault.vault:8200"
        path = "/consul/data/"
        disable_registration = "true"
    }
```

**Comment by jefferai** [comment] 2018-03-08 04:25
8201 is the correct port, not 8200.

You should be setting api_addr and cluster_addr at the top level (https://www.vaultproject.io/docs/configuration/index.html#high-availability-parameters), not under `consul`.

You should be connecting to your localhost consul agent, not to the servers.

There isn't enough logs that you're sending to get any better of an idea of what's going on, but my guess is that your Vault nodes are not actually allowed to connect to each other on the cluster ports.

**Comment by pandeybk** [comment] 2018-03-09 00:08
Thank you @jefferai you are right about 8201 port. I was not exposing this port in service object of kubernetes. Looks like now vault server is running ok. 

I haven't mentioned api_addr and cluster_addr  as mentioned in doc, but here is my working configuration. 

```
ha_storage "consul" {
        scheme = "http"
        address = "consul.consul:8500"
        advertise_addr = "https://vault.vault:8200"
        path = "/consul/data/"
        disable_registration = "true"
    }
```

I am sometimes seeing following error log in some of the vault pods. This is not exactly causing problem. I think I am not running enough test to see the problem. 

Not sure where this is coming from. Trying to figure out the issue

```
2018/03/08 23:04:40.402518 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/08 23:04:40.402569 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
2018/03/08 23:04:51.160352 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/03/08 23:04:51.160399 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
``` 

FYI, all components are running in same k8s cluster. Consul agent we are running as statefulsets and exposing as service object. We don't have any consul running as sidecar. So we can't use localhost for connection. Are you saying this will be a problem and not the recommended settings?

**Comment by jefferai** [comment] 2018-03-09 03:01
You should be setting api_addr and cluster_addr. I don't know what the issue is but it doesn't hurt to set those and may well help.

**Comment by jefferai** [comment] 2018-04-17 20:57
Closing, please poke back if you still need help.

**Closed by jefferai** 2018-04-17 20:57 UTC
