### ISSUE TITLE
Getting errors in the vault auth in EKS

### ISSUE THREAD

**Issue by mchakrabarty** [hashicorp/vault#12509] opened 2021-09-08 11:25 UTC
Hi All,

We are using vault in our projects. But we are facin an issue with the vault. Our applications are using the vault properly but at the pods of vault we are getting this error.
Error: 
2021-09-08T08:45:40.239Z [ERROR] auth.kubernetes.auth_kubernetes_7d5bd6ff: login unauthorized due to: lookup failed: [invalid bearer token, Token has been invalidated, unknown] 2021-09-08T08:46:10.636Z [INFO]  expiration: revoked lease: lease_id=auth/token/create/hd94a7c8d1660531789da04be6e77dbf76a22f6055f07b369d51722f2595ea794

Can anyone please tell me how to resolve this error?

**Comment by hsimon-hashicorp** [comment] 2021-09-10 21:06
Hi @mchakrabarty - could you provide more details about your configuration and more logs? More data would help. Also, repro steps would be helpful as well. Thanks!

**Comment by hsimon-hashicorp** [comment] 2021-10-12 21:48
Hi @mchakrabarty! It's been a while since we've heard from you regarding this issue. I'm going to go ahead and close it now, but please feel free to re-open if you need and you can provide reproduction steps. In the meantime, our [Discuss forum](https://discuss.hashicorp.com/c/vault/30) is a great place to get help from subject matter experts and other community members, and is less of a "bug-reporting" venue. Thanks for your understanding!

**Closed by hsimon-hashicorp** 2021-10-12 21:48 UTC
Labels: waiting-for-response, auth/k8s
