### ISSUE TITLE
Vault transit token is not getting renewed when created with max_ttl

### ISSUE THREAD

**Issue by alok183** [hashicorp/vault#17056] opened 2022-09-08 07:33 UTC
When max_ttl was used to generate the token, vault transit engine is not increasing the expiration date and gives the  warning like “* TTL of "768h" exceeded the effective max_ttl of "767h59m42s"; TTL value is capped accordingly”.

But when token is created with custom ttl then renewable of token is working fine even when n number time requested ro extend the expiry date

![image](https://user-images.githubusercontent.com/24774682/189062135-fda46dde-3cce-42a6-99f0-308c382c63b4.png)
.

**Environment:**

* Vault Version: 1.10.0
* Operating System/Architecture: Linux

```hcl
autounseal.hcl 
            path "transit/encrypt/autounseal" {
            capabilities = [ "update" ]
            }

            path "transit/decrypt/autounseal" {
            capabilities = [ "update" ]
            }
```

**Startup Log Output:**

```text
# Paste your log output here
```

**Expected Behavior:**
Vault transit token  created with max_ttl should get renewed.

**Actual Behavior:**
Vault transit token  created with max_ttl is not  getting renewed.

**Steps to Reproduce:**
1. Generate token with max_ttl
2. Try to renew the token.

**Important Factoids:**

**References:**

**Comment by stevendpclark** [comment] 2022-12-02 18:05
Hello @alok183,

Thanks for submitting the issue, I believe this issue is a duplicate of https://github.com/hashicorp/vault/issues/14833

Within that issue it was concluded that tokens for transit unseal purposes should be created with the `-orphan` and `-period` arguments to not hit a max lifetime and keep renewing itself properly. 

```
vault token create -policy="autounseal" -orphan -period=768h
```

I'll close out this issue, but please re-open/comment on this if I've misunderstood the issue you have filed.

**Closed by stevendpclark** 2022-12-02 18:05 UTC
Labels: bug, secret/transit
