### ISSUE TITLE
Vault treats subject name as a required field

### ISSUE THREAD

**Issue by mr-miles** [hashicorp/vault#14432] opened 2022-03-09 23:21 UTC
I have a pki role configured where the certificate has a blank subject and a SAN.  Logging in to vault using the certificate causes vault to return an error "alias name not set" even though it meets all the constraints.

https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.6 states that certificates with a blank subject must have a SAN marked as critical, and that can be used as the identity for the certificate.  Is it possible to adopt the behaviour from the standard when working out the alias name?  Or is there an alternative route to successfully authenticate with a certificate with blank common name?

#6820

**Comment by maxb** [comment] 2022-03-13 08:40
I was going to add a comment here, but I realised this is, as far as I can see, an exact duplicate of the referenced issue #6820 so I'll respond there instead.

**Comment by sgmiller** [comment] 2022-03-14 15:59
I agree, this is a duplicate, but we'll re-examine the linked issue and take the discussion over there.

**Closed by sgmiller** 2022-03-14 15:59 UTC
Labels: enhancement, auth/cert, question, cryptosec
