### ISSUE TITLE
vault sidecar and vault in different k8s cluster ，can not login

### ISSUE THREAD

**Issue by 13567436138** [hashicorp/vault#20191] opened 2023-04-17 11:03 UTC
**Describe the bug**
vault sidecar and vault in different k8s cluster ，can not login
**To Reproduce**
1. Run `vault write ...`
2. Run `vault login....`
3. See error

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by hghaf099** [comment] 2023-04-17 17:35
Thanks for filing this issue. However, we cannot deduce what the issue is and how we can help considering the provided description of the issue. Please provide us some details for the issue.

**Comment by hsimon-hashicorp** [comment] 2023-04-27 18:56
Are you able to verify the certificate with a tool such as openssl? Please try that and let us know. It looks very much like something's gone wrong in your cert handling. Thanks!

**Comment by hsimon-hashicorp** [comment] 2023-07-07 19:15
Since we have not heard from you regarding this issue in a while, I'm going to go ahead and close it. Please re-open it if you need, or feel free to open a new issue. Thanks!

**Closed by hsimon-hashicorp** 2023-07-07 19:15 UTC
Labels: ecosystem, waiting-for-response
