### ISSUE TITLE
List readable secrets in generic backend

### ISSUE THREAD

**Issue by grantr** [hashicorp/vault#170] opened 2015-05-07 22:59 UTC
Getting a list of readable secrets from the generic secret backend would be useful for a FUSE implementation like keywhiz-fs. I don't see a way to do that currently. Maybe it could recognize wildcards in the secret path?

**Comment by sethvargo** [comment] 2015-05-07 23:12
Closing as a duplicate of https://github.com/hashicorp/vault/issues/111. Let's track that issue please :smile:

**Closed by sethvargo** 2015-05-07 23:12 UTC

**Comment by grantr** [comment] 2015-05-07 23:58
Oops didn't see that one!
