### ISSUE TITLE
Move Revoke Token Button away from Sign Out Button

### ISSUE THREAD

**Issue by jaredblackjcb** [hashicorp/vault#21390] opened 2023-06-21 18:12 UTC
It is very frustrating that the 'Revoke Token' and the 'Sign Out' buttons are right next to each other in the drop down menu. Our team is large and someone is always accidentally clicking 'Revoke Token', which causes us to have to generate a new token and update the vault config for all of our microservices. This is a headache caused by some unbelievably bad UX/UI work.

Please move the 'Revoke Token' button somewhere it can't be clicked by accident, and add a confirmation modal that asks if you really want to revoke the token.
![image](https://github.com/hashicorp/vault/assets/40250874/32babbb7-dd1b-4284-89b2-441f1402c0be)

**Comment by maxb** [comment] 2023-06-23 09:02
[I'm just a community contributor here, and am not associated with HashiCorp.]

I imagine many people would likely consider it a rather significantly bad practice to have humans sharing the same Vault tokens as microservices.

Are there particular constraints in your environment which force this approach on you? Would it not be more convenient all around, if your humans logged in to the Vault UI using personal credentials of some kind, and had separate identities from services?

**Comment by kiannaquach** [comment] 2023-08-02 16:46
We introduced a confirmation modal for "Revoke token" in 1.5, so any revocation has to be acknowledged. We will need to make a change in the modal to make it more clear and easily readable, but that modal is intended to prevent accidental revocations. Is there a scenario where this isn’t working as intended? If so, we’re happy to listen.

**Comment by zofskeez** [comment] 2023-08-16 21:13
Closing since the confirmation dialog is in place for all currently maintained versions. The fix for the confirmation text readability will land in 1.14.2.

**Closed by zofskeez** 2023-08-16 21:13 UTC
Labels: ui, enhancement, waiting-for-response
