### ISSUE TITLE
Creating a secret then backing out (Change of mind) causes the secrets list to not render without a page refresh. Browser console reveals Uncaught TypeError.

### ISSUE THREAD

**Issue by ipaqmaster** [hashicorp/vault#21303] opened 2023-06-16 05:56 UTC
**Describe the bug**

It seems if you go to create a new KV (v2) secret in the /ui/ and click into your secrets engine, go to create a new secret, click back to the previous menu with the on-page blue button to return to your secret engine - it triggers the browser's "Are you sure you wish to leave this page" standard response, but clicking Ok to continue nagivating away reveals an entirely empty secrets engine with a blank list, as if something which handles showing the navigation list has unloaded and hasn't been refreshed.

**To Reproduce**
1. Run `vault server -dev`
2. Run `Visit in your favourite browser`
3. Go into the dev kv engine `secret/`
4. Click to create a new secret
5. Click the blue hyperlink back to the listing of secret/ upper left of the page body.
6. Secret list no longer loads despite healthy network communication (200 response codes)

**Expected behavior**

Secret lists continue to render to the page
**Environment:**
* Vault Server Version (retrieve with `vault status`): 
1. Cluster running `Vault v1.13.3 (cgo)`
2. Cluster running `Vault v1.13.2 (cgo)`
3. Reproducible locally on Windows 10 with `vault server -dev` version `Vault v1.13.2 (b9b773f1628260423e6cc9745531fd903cae853f), built 2023-04-25T13:02:50Z`
* Vault CLI Version (retrieve with `vault version`): This is a /ui/ problem in with a browser
* Server Operating System/Architecture: `Windows 10` client running `Google Chrome Version 113.0.5672.127 (Official Build) (64-bit)`

Vault server configuration file(s):

```hcl
NA
```

**Additional context**

When this happens the following JS error is visible in the browser console:

```
vendor-7da855e798cb22554cdbb9aa84703a8f.js:8386 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'charAt')
    at e.default (vendor-7da855e798cb22554cdbb9aa84703a8f.js:8386:27)
    at e.<anonymous> (vendor-7da855e798cb22554cdbb9aa84703a8f.js:8169:22)
    at vendor-7da855e798cb22554cdbb9aa84703a8f.js:696:67
    at e.untrack (vendor-7da855e798cb22554cdbb9aa84703a8f.js:2968:12)
    at me.get (vendor-7da855e798cb22554cdbb9aa84703a8f.js:696:56)
    at e.r [as firstPartialMatch] (vendor-7da855e798cb22554cdbb9aa84703a8f.js:672:245)
    at je (vendor-7da855e798cb22554cdbb9aa84703a8f.js:715:73)
    at vendor-7da855e798cb22554cdbb9aa84703a8f.js:2314:39
    at vendor-7da855e798cb22554cdbb9aa84703a8f.js:2309:41
    at e.track (vendor-7da855e798cb22554cdbb9aa84703a8f.js:2965:5)
```
With that `null` I assume it's trying to redraw the page before it's made a request for the data to do so.

**Comment by mpalmi** [comment] 2023-06-26 17:32
I'm going to go ahead and close this out, since it appears to be a duplicate of an open issue. Thanks for adding some extra context @ipaqmaster!

**Closed by mpalmi** 2023-06-26 17:32 UTC
