### ISSUE TITLE
Release notes link 404's

### ISSUE THREAD

**Issue by dehnert** [hashicorp/vault#12028] opened 2021-07-09 04:05 UTC
**Describe the bug**

The release notes link on the Downloads page 404's

**To Reproduce**
1. Visit https://www.vaultproject.io/downloads
2. Click "documentation" (in "Release notes are available in our documentation.")
3. See "Page Not Found"

**Expected behavior**
Release notes appear (perhaps https://www.vaultproject.io/docs/release-notes/1.7.0 loads?)

**Environment:**
* Vault Server Version (retrieve with `vault status`): N/A
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: Linux

Vault server configuration file(s): N/A

**Additional context**

It seems like maybe at some point, per-version release notes were a thing, but now it's only the .0 that gets them, and the macro involve in https://github.com/hashicorp/vault/blob/main/website/pages/downloads/index.jsx#L53 does not reflect that?

**Comment by ccapurso** [comment] 2021-10-18 20:48
We have also confirmed that the unexpected behavior seems to be resolved and we are thus closing this issue. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.

**Closed by ccapurso** 2021-10-18 20:48 UTC
Labels: docs, website
