### ISSUE TITLE
S3 backend should work with Minio cloud storage

### ISSUE THREAD

**Issue by ccojocar** [hashicorp/vault#5096] opened 2018-08-14 07:30 UTC
**Describe the bug**

The S3 backend should work with `Minio` cloud storage. There are currently some missing features on Minio side which prevents this. See this related PR #4931.

**To Reproduce**

1. Enable S3 backend with Minio cloud configuration
2. Perform typical vault operations 

**Expected behavior**

The S3 backend should work, and also all the unit tests of S3 backend should pass.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by jefferai** [comment] 2018-08-14 13:36
Duplicate of #4931 -- discussion still ongoing there.

**Closed by jefferai** 2018-08-14 13:36 UTC
