### ISSUE TITLE
Append key-value pairs to a vault file without removing previous pairs

### ISSUE THREAD

**Issue by julianborrey** [hashicorp/vault#639] opened 2015-09-22 19:09 UTC
```
$ vault write secret/test hello=world
```
This puts the key-value pair `hello=world`.

If we then do
```
$ vault write secret/test foo=bar
```
we will lose the `hello=world` key-value pair.
It would be good if it just added `foo=bar` and kept `hello=world`.

So, after those two commands, the final file should be
```
$ vault read secret/test

Key            	Value
lease_id       	secret/test/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
lease_duration 	xxxxxxx
lease_renewable	xxxxx
hello          	world
foo          	bar
```

**Comment by jefferai** [comment] 2015-09-22 19:16
This won't be implemented -- we want Vault to be deterministic, and it follows CRUD semantics. Data lives at a location; if you want to update the data at the location you provide the new data (which includes anything you want to keep).

There are various workarounds, one being to simply read the data before writing it, the other to write the new pieces of data somewhere else and update them there.

**Closed by jefferai** 2015-09-22 19:16 UTC

**Comment by pradeepbhadani** [comment] 2017-11-23 13:57
@jefferai Atleast it would be nice to prompt a warning that "You are going to Overwrite the existing key/value pair".

**Comment by CGreenburg** [comment] 2018-06-08 15:44
Seems like a legit feature. It could be implemented with an -append argument like so `vault write -append foo=bar`

What am I to do if a secret has 10+ key/value pairs? Am I supposed to script out a wrapper around the vault command to preserve old secrets? Seems like a hassle that should be implemented in the main product imo.

**Comment by jefferai** [comment] 2018-06-08 15:50
If you're using KV v2, simply use `vault kv patch`.

**Comment by CGreenburg** [comment] 2018-06-08 15:57
Oh, I wasn't aware the the `vault kv` subset of commands had a patch command. Thanks.

**Comment by djanowski** [comment] 2018-09-21 20:17
In the meantime, one workaround which can easily be turned into a script:

```
vault read -format json -field data secret/foo/bar | \
  jq '.baz = "qux"' | \
  vault write secret/foo/bar -
```

**Comment by sgleske-ias** [comment] 2019-01-31 23:09
`vault kv` does not exist for me in 
```
$ vault --version
Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')
```
Is there no other way?

**Comment by ItsGosho** [comment] 2022-08-05 14:55
Looks like you need to put at least one value in the storage before using patch

**Comment by abdennour** [comment] 2022-12-05 22:50
```sh
 vault kv patch -output-curl-string secret/test TEST=hello
```
that will print
```sh
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"data":{"MSG":"xyz","TEST":"hello"},"options":{"cas":3}}' http://localhost:8200/v1/secret/data/test
```
conclude that put & patch use same HTTP request verb & endpoint & headers.. however , you just need to modify request body to include body.options.cas=3

**Comment by raskchanky** [comment] 2022-12-06 00:32
Note that as of Vault 1.9.0, `vault kv patch` uses PATCH instead of PUT.

**Comment by nemith** [comment] 2023-08-17 23:28
Just wiped one of my keys.  It's  deterministic in the sense that it's gone.

**Comment by mtHuberty** [comment] 2023-09-10 00:30
Just did the same. Thankfully just a nonprod environment but still a headache to get it fixed. Now I'm slapping together something with jq to handle what should be a simple thing. Glad this is at least not an issue with the kv engine. If only we were on that...

**Comment by soakes** [comment] 2023-09-16 22:20
Embarsed to say but, I just did the same thing and obblitered several values.

I can confirm what @raskchanky mentions works perfectly, thank you. 

```
(SO HOME)[soakes@mgmt01 ~]# vault kv put   "assets/ssl/example.com"  "cert=this is a cert"  "fullchain=this is a fullchain"     "privkey=this is a privkey"
======= Secret Path =======
assets/data/ssl/example.com

======= Metadata =======
Key                Value
---                -----
created_time       2023-09-16T22:16:19.813022915Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            3
(SO HOME)[root@mgmt01 ~]# vault kv get  "assets/ssl/example.com"
======= Secret Path =======
assets/data/ssl/example.com

======= Metadata =======
Key                Value
---                -----
created_time       2023-09-16T22:16:19.813022915Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            3

====== Data ======
Key          Value
---          -----
cert         this is a cert
fullchain    this is a fullchain
privkey      this is a privkey
(SO HOME)[soakes@mgmt01 ~]# vault kv patch  "assets/ssl/example.com" "mookey=this is a moo key"
======= Secret Path =======
assets/data/ssl/example.com

======= Metadata =======
Key                Value
---                -----
created_time       2023-09-16T22:16:39.002843108Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            4
(SO HOME)[soakes@mgmt01 ~]# vault kv get   "assets/ssl/example.com"
======= Secret Path =======
assets/data/ssl/example.com

======= Metadata =======
Key                Value
---                -----
created_time       2023-09-16T22:16:39.002843108Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            4

====== Data ======
Key          Value
---          -----
cert         this is a cert
fullchain    this is a fullchain
mookey       this is a moo key
privkey      this is a privkey
```

**Comment by dr0kz** [comment] 2024-07-15 13:04
> Looks like you need to put at least one value in the storage before using patch

Yap and that is annoying. How can I use patch from the first moment ? Because now I have to develop a business logic that will check if something exist on that location and if it does not exist then use PUT otherwise if exist use PATCH.
