### ISSUE TITLE
Multi - Level Certificate

### ISSUE THREAD

**Issue by YangTianning** [hashicorp/vault#487] opened 2015-08-03 16:56 UTC
My init step works just well with the certificate signed by root certificate. However, when trying the one signed by intermediate certificate, there is an error saying "init: x509: certificate signed by unknown authority. I did verify the certificate chain and trusted my root cert and trusted the chain certificate.

**Comment by sethvargo** [comment] 2015-08-07 17:03
Hi there,

This looks like a duplicate of https://github.com/hashicorp/vault/issues/388. Can you please confirm

**Comment by jefferai** [comment] 2015-08-19 02:08
@YangTianning When you say "my init step", can you give more details? Vault init, or init of one of the backends?

**Comment by YangTianning** [comment] 2015-08-19 03:01
Thank you for replying. The problem has been solved when I do it on another platform. Anyway, I meant “vault init” by then.

Tina

**Comment by jefferai** [comment] 2015-08-19 18:30
Solved per user.

**Closed by jefferai** 2015-08-19 18:30 UTC
Labels: bug, secret/pki, waiting-reply
