### ISSUE TITLE
Period value not being used on renewal for AWS IAM authenticated tokens

### ISSUE THREAD

**Issue by EXPEddrewery** [hashicorp/vault#3221] opened 2017-08-22 04:47 UTC
**Environment:**

* Vault Version: 0.8.1 (and master)
* Operating System/Architecture: Amazon Linux

**Expected Behavior:**
1. Instance authenticated using 'auth/aws' where role has Period value set to system default TTL (2764800)
2. Wait 30 seconds
3. Renew token returns a new TTL matching the Period value (2764800)

**Actual Behavior:**
1. Instance authenticated using 'auth/aws' where role has Period value set to system default TTL (2764800)
2. Wait 30 seconds
3. Renew token returns a new TTL not matching the Period value (2764770 or less)

**Steps to Reproduce:**
1. Setup a role using the AWS IAM auth backend with a Period set to system default TTL (2764800)
2. Authenticate an instance using the configured role
3. Wait 30 seconds
4. Attempt to renew the token and check the TTL returned. The value should be 2764770 or less.

**References:**
https://github.com/hashicorp/vault/pull/3220

**Comment by jefferai** [comment] 2017-08-22 13:32
Duplicate of #3220

**Closed by jefferai** 2017-08-22 13:32 UTC
