### ISSUE TITLE
Consul still shows vault status active when vault process is killed

### ISSUE THREAD

**Issue by nailpusher** [hashicorp/vault#5690] opened 2018-11-05 22:04 UTC
Hi all,

I have 2 nodes Vault cluster setup with Consul backend (consul agents are running on each vault node). When I gracefully shut down active vault node, standby node becomes active, shut down node is removed from Consul (/v1/catalog/service/vault). But when I test failure scenario and kill vault process manually, this node is still shown in Consul with "ServiceTags": [ "active"]. Does anyone know why it happens?

**Comment by chrishoffman** [comment] 2018-11-05 22:05
Duplicate of https://groups.google.com/d/msgid/vault-tool/b00dfac3-438a-4eaa-8947-6280fb5eb370%40googlegroups.com

**Closed by chrishoffman** 2018-11-05 22:05 UTC
