### ISSUE TITLE
Wrong base64 unseal key returns 200 when unsealing the vault

### ISSUE THREAD

**Issue by kamikazechaser** [hashicorp/vault#12618] opened 2021-09-23 09:46 UTC
**Describe the bug**
If the vault is in an unsealed state, entering a wrong base64 unseal (change any character in the key to reporoduce) on the UI returns a 200 response and a `progress` key of 1 in the response. A subsequent correct unseal key returns 500 (`"unable to retrieve stored keys: failed to decrypt keys from storage: cipher: message authentication failed"`). The vault never gets unsealed though which is good but the UI bugs out because of the misleading response from the server.

**To Reproduce**
1. Initialize vault
2. Unseal for the 1st time add some random secrets
3. Bring docker container down and remove it (`docker-compose down && docker rm [vault_container_goes_here]`)
4. Bring it back up (`docker-compose up`)
5. Attempt to unseal with a wrong base64 key (change some character)
6. Check request body sent to `POST /unseal`

**Expected behavior**
API response should return 4xx on wrong key and a correct response on the UI.

**Environment:**
* Vault version: 1.8.2
* Environment: Docker (Docker-compose)
* Storage backend: File

Vault server configuration file(s):

```hcl
storage "file" {
    path = "/vault/file"
}

listener "tcp" {
    address     = "0.0.0.0:8200"
    tls_disable = true
}
```

**Additional context**

Docker compose file for convenience:  

```yaml
version: "3"
services:
  vault:
    image: vault:1.8.2
    restart: on-failure
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_UI=true
      - VAULT_ADDR=http://127.0.0.1:8200
    volumes:
      - ./config:/vault/config
      - ./data:/vault/file
      - ./logs:/vault/logs
    entrypoint: vault server -config=/vault/config/vault_config.hcl
```

**Comment by ncabatoff** [comment] 2021-09-23 12:14
Hi @kamikazechaser,

I don't believe it's possible to change the current behaviour.  The individual unseal key fragments are just numbers, and can't be identified by Vault as being valid fragments in isolation.  It's only in combination that we can tell whether they add up to a valid key.  Given a threshold of 3 and two valid keys and one invalid key, all Vault can say is "this is not a valid combination of 3 keys" - it can't identify that two were valid and one was not.

You might say: Vault could provide a better UX by storing the individual fragments, so that it would be possible to identify the bad inputs.  But the problem there is that we don't have a way to store them securely (with encryption at rest), because the whole point of using Shamir is to have a way to protect the master key without having to store any secret data unencrypted.

I'm going to close this issue because what it describes is the intended behaviour.  You're welcome to respond if you have further questions or comments, and I'm happy to re-open if I've missed something and we can do something to make this better.

**Closed by ncabatoff** 2021-09-23 12:14 UTC
