### ISSUE TITLE
Vault crashes with cassandra as backend

### ISSUE THREAD

**Issue by saurabh-zededa** [hashicorp/vault#8465] opened 2020-03-04 05:21 UTC
**Describe the bug**
There is one random vault failure issue while restarting vault container.
vault is not able to connect even though cassandra is up and running.

Error message:
vault_1_6e0fea9cc2e3 | 2020-02-21 06:16:17.397146 I | gocql: unable to dial control conn 127.0.0.1: gocql: no response to connection startup within timeout
vault_1_6e0fea9cc2e3 | Error initializing storage of type cassandra: gocql: unable to create session: control: unable to connect to initial hosts: gocql: no response to connection startup within timeout

Issue description:
vault tries to connect to cassandra and if it fails then vault crashes.

I looked at the vault code and it seems there is no retry mechanism if it's cassandra connectivity fails. In the code it looks like it tries to create cassandra session and if it fails once then it crashes instead of retrying.

**To Reproduce**
transient/random failure
restart vault container
1. Run vault server --config="/vault/config/vault.json"
Error initializing storage of type cassandra: gocql: unable to create session: control: unable to connect to initial hosts: gocql: no response to connection startup within timeout

3. See error
vault_1_6e0fea9cc2e3 | 2020-02-21 06:16:17.397146 I | gocql: unable to dial control conn 127.0.0.1: gocql: no response to connection startup within timeout
vault_1_6e0fea9cc2e3 | Error initializing storage of type cassandra: gocql: unable to create session: control: unable to connect to initial hosts: gocql: no response to connection startup within timeout

**Expected behavior**
Vault server should retry connecting to casandra, instead of exiting if session creates fails.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Version  1.2.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.2.2
* Server Operating System/Architecture: linux/ubuntu, vault running as container.

Vault server configuration file(s):
{
        "backend": {
                "cassandra": {
                        "hosts": "cassandra",
                        "consistency": "LOCAL_QUORUM",
                        "protocol_version": 4,
                        "keyspace": "vault",
                        "table": "secrets",
                        "connection_timeout": 11,
                        "username": "XXXXX",
                        "password": "XXXXX"
                }
        },
        "listener": {
                "tcp": {
                        "address": "0.0.0.0:8200",
                        "tls_cert_file": "/etc/ssl/certs/vault.chained-cert.pem",
                        "tls_key_file": "/etc/ssl/private/vault.privkey.pem"
                }
        },

        "default_lease_ttl": "168h",
        "max_lease_ttl": "720h"
}

**Comment by catsby** [comment] 2020-03-04 18:48
This error seems to be coming from `gocql`:

https://github.com/gocql/gocql/blob/cd4b606dd2fb8920e814a86b2901d062daf388a8/control.go#L248

It looks like when creating the session, the client uses a `SimpleRetry` policy with 3 attempts:

https://github.com/gocql/gocql/blob/cd4b606dd2fb8920e814a86b2901d062daf388a8/control.go#L46-L51

This suggests to me that the Cassandra backend simply isn't up. Could you possibly verify that Cassandra is up and serving requests when this happened? 

At this point, it's not clear what the path forward should be. I'm hesitant to add logic to Vault to retry a connection when the client itself already has retry logic. Also for what it's worth, this behavior is more accurately described as "errors and quits" rather than "crashes".

**Comment by saurabh-zededa** [comment] 2020-03-05 04:49
> This error seems to be coming from `gocql`:
> 
> https://github.com/gocql/gocql/blob/cd4b606dd2fb8920e814a86b2901d062daf388a8/control.go#L248
> 
> It looks like when creating the session, the client uses a `SimpleRetry` policy with 3 attempts:
> 
> https://github.com/gocql/gocql/blob/cd4b606dd2fb8920e814a86b2901d062daf388a8/control.go#L46-L51
> 
> This suggests to me that the Cassandra backend simply isn't up. Could you possibly verify that Cassandra is up and serving requests when this happened?
> 
> At this point, it's not clear what the path forward should be. I'm hesitant to add logic to Vault to retry a connection when the client itself already has retry logic. Also for what it's worth, this behavior is more accurately described as "errors and quits" rather than "crashes".

Yes the error is from gocql.
I am running vault's  container image vault:1.2.2. Vault container crashes if it's not able to create a cassandra session. (Exit code 137)
In my case cassandra is up and running, but vault is not able to create cassanda session.
Why I am sure that cassandra is up?
I am checking two things inside vault container before starting vault server.
1. check if port used by cassandra container is open or not?
2. if the port is open then execute a cqlsh query.
3. If the cassandra query is successful from vault's container then wait for 20 sec and then start vault server. But vault fails to create cassandra session sometime.
This error does not occur every time, I mean vault does not fail to create cassandra session every time, roughly frequency of  failure is once or twice in 10 times.

**Comment by catsby** [comment] 2020-03-05 16:12
What version of Cassandra are you using? Are you able to replicate this outside of Vault, using `gocql` directly? Note that we're using a version of `gocql` from April 2019 (specifically the sha is https://github.com/gocql/gocql/commit/0e1d5de854df). 

If you could reproduce this issue with that version, and then demonstrate that an updated version of the library does not have this issue, then we would have convincing evidence to upgrade our bundled version of `gocql`. 

Without a reproduction using that version of `gocql`, I would be hesitant to update our included version.

**Comment by saurabh-zededa** [comment] 2020-03-05 18:40
> What version of Cassandra are you using? Are you able to replicate this outside of Vault, using `gocql` directly? Note that we're using a version of `gocql` from April 2019 (specifically the sha is [gocql/gocql@0e1d5de](https://github.com/gocql/gocql/commit/0e1d5de854df)).
> 
> If you could reproduce this issue with that version, and then demonstrate that an updated version of the library does not have this issue, then we would have convincing evidence to upgrade our bundled version of `gocql`.
> 
> Without a reproduction using that version of `gocql`, I would be hesitant to update our included version.

Cassandra version detail:
[cqlsh 5.0.1 | Cassandra 3.11.2 | CQL spec 3.4.4 | Native protocol v4] 
Outside of vault we have services that talks to Cassandra. These services has retry mechanism so we have not faced similar issue. We are using gocql version from July 2019.

My only concern is why vault container crashes if it's not able to connect with Cassandra? 

With vault:1.2.2. and Cassandra 3.11.2  I did docker-compose down two times and second time vault crashed.(For my testing I am using docker-compose for orchestration)

vault_1         | 2020-03-05 18:15:04.379492 I | gocql: unable to dial control conn 127.0.0.1: gocql: no response to connection startup within timeout
vault_1         | Error initializing storage of type cassandra: gocql: unable to create session: control: unable to connect to initial hosts: gocql: no response to connection startup within timeout

**Comment by catsby** [comment] 2020-03-10 15:27
Hello - 

If you're using Cassandra as the storage for your Vault container, than it makes sense that the container would exit if it cannot connect to the storage. Vault encrypts and stores it's data in the external storage, and if it cannot access that storage then exiting would be the correct behavior.

> Outside of vault we have services that talks to Cassandra. These services has retry mechanism so we have not faced similar issue. We are using gocql version from July 2019.

Vault utilizes the built-in retry mechanism provided by the Cassandra client in use. If it can be demonstrated that the version we're including is subject to reproduceible connection issues outside of the Vault code base, then we could feel fairly confident that the client version could be at fault, and updating our version would likely be beneficial. 

At this time we're unaware of any other reports of connection issues with the Cassandra storage backend.  As you mentioned previously the connection issues are not consistent and do succeed more times than not, so we'd like to see some other supporting information before taking action here.

**Comment by tyrannosaurus-becks** [comment] 2020-03-26 23:56
Hi! I'm going to go ahead and close this because I do also think it's likely that Cassandra was simply unreachable at the time of testing.

I double-checked that Cassandra works by plugging the Cassandra configuration shown above into [this test](https://github.com/hashicorp/vault/blob/master/physical/cassandra/cassandra_test.go#L30) that spins up a local Cassandra and connects to it. As long as the secrets table exists, it's working in my tests. Hopefully that link can also provide some help with a working example. 

Please do feel free to reopen this issue if you encounter more issues. Thank you!

**Closed by tyrannosaurus-becks** 2020-03-26 23:56 UTC
Labels: storage/cassandra, waiting-for-response
