### ISSUE TITLE
Vault even after configuring prompts for a password.

### ISSUE THREAD

**Issue by kr-143** [hashicorp/vault#16275] opened 2022-07-12 04:57 UTC
**Describe the bug**
I am trying to authenticate target host with vault signed key.. i have followed the official documentation of HashiCorp Vault sshClient signer . Even after that it still prompts for a password.

**Target Host SSH Version shows as : OpenSSH_7.2p2, CiscoSSL 1.0.2n.6.1.368-fips**
is it a problem if we are not using the openssl, as in my target host it is using ciscoSSL. 
What is the setup that we need if we want to use vault sshClient signer.

**Target Host config & OS : Cisco Nexus3500 C3548P-10GX**

What are the algorithms that a target host should have to support vault cert key, how to verify that in target host.
when we are creating roles in vault the payload consists of an **"algorithm_signer": "rsa-sha2-256",**

**Environment:**
* Vault Server Version (retrieve with `vault status`):1.10.1
* Vault CLI Version (retrieve with `vault version`): 1.10.1
* Server Operating System/Architecture:  NX-OS

**Comment by cipherboy** [comment] 2022-07-12 15:24
Hey @kr-143, if you turn on debug logging, you might see the issue is a duplicate of this: https://github.com/hashicorp/vault/issues/15488

**Comment by cipherboy** [comment] 2023-06-01 12:46
Closing this ticket as there has been no response in almost a year.

**Closed by cipherboy** 2023-06-01 12:46 UTC
Labels: secret/ssh
