### ISSUE TITLE
Metadata in policies does not get matched correctly

### ISSUE THREAD

**Issue by hrld** [hashicorp/vault#27586] opened 2024-06-25 05:28 UTC
We tried to use metadata in vault policies to grant permissions based on a common schema as documented in https://developer.hashicorp.com/vault/tutorials/policies/policy-templating#create-templated-acl-policies (using approles).

The expected result was a permission on a path containing a metadata field of each token. The actual result is a permission on a path containing the metadata field of the LAST CREATED token.

Meaning: the permissions of a token get changed by creating additional token via the approle!

Steps to reproduce:

```
### initialize approle, create policy with metadata-template, create approle using the policy:
$ vault auth enable approle

$ vault policy write testpolicy - <<EOL
path "secret/data/path/{{ identity.entity.aliases.auth_approle_88a5c50b.metadata.foo }}/*" {
  capabilities = ["read","list"]
}
EOL
Success! Uploaded policy: testpolicy

$ vault write auth/approle/role/testapprole token_policies="testpolicy"

$ vault read auth/approle/role/testapprole/role-id
Key        Value
---        -----
role_id    90d16fae-8222-e4e0-8d52-91ac5b6dde14

### create secret_id for test1 and test2:
$ vault write auth/approle/role/testapprole/secret-id metadata='{"foo": "test1"}'
Key                   Value
---                   -----
secret_id             25ffbbdf-c308-b0ca-787f-de45e18954a9
secret_id_accessor    dcb7641e-99d7-8c5e-a2b3-50868d5903eb

$ vault write auth/approle/role/testapprole/secret-id metadata='{"foo": "test2"}'
Key                   Value
---                   -----
secret_id             2334caa2-116a-4e11-d732-5e97abefd1f5
secret_id_accessor    d37e3b72-270b-0c42-157f-a93210b19701

### create token for test1:
$ vault write /auth/approle/login role_id=90d16fae-8222-e4e0-8d52-91ac5b6dde14 secret_id=25ffbbdf-c308-b0ca-787f-de45e18954a9
Key                     Value
---                     -----
token                   hvs.CAESIGivhAUge5G8WGpTTDPvVeH9_bO9jmmPEgQjf8dXi8_FGh4KHGh2cy5YR2lGOHJKaFE1VHMwMWlIenh1MUJONm0
token_accessor          Qkj8ZTyWFdrRXH9DUurXC1U0
token_duration          768h
token_renewable         true
token_policies          ["default" "testpolicy"]
identity_policies       []
policies                ["default" "testpolicy"]
token_meta_foo          test1
token_meta_role_name    testapprole

### permissions as expected:
$ vault token capabilities -accessor Qkj8ZTyWFdrRXH9DUurXC1U0 secret/data/path/test1/any
list, read
$ vault token capabilities -accessor Qkj8ZTyWFdrRXH9DUurXC1U0 secret/data/path/test2/any
deny

### create token for test2:
$ vault write /auth/approle/login role_id=90d16fae-8222-e4e0-8d52-91ac5b6dde14 secret_id=2334caa2-116a-4e11-d732-5e97abefd1f5
Key                     Value
---                     -----
token                   hvs.CAESIHkoZ1Fa3MhPWguOH8rzfYYHt02oP-JvJsZUu6VI1mlCGh4KHGh2cy5tR2ZVWG1VdWJKa0dHbExZU0JqNG0yWjA
token_accessor          cmxvf1pTAhy3Vxq2roXxe9Su
token_duration          768h
token_renewable         true
token_policies          ["default" "testpolicy"]
identity_policies       []
policies                ["default" "testpolicy"]
token_meta_foo          test2
token_meta_role_name    testapprole

### permissions as expected:
$ vault token capabilities -accessor cmxvf1pTAhy3Vxq2roXxe9Su secret/data/path/test1/any
deny
$ vault token capabilities -accessor cmxvf1pTAhy3Vxq2roXxe9Su secret/data/path/test2/any
list, read

### permissions for test1-token very much NOT as expected and NOT as they looked like above but are a copy of the last-created token:
$ vault token capabilities -accessor Qkj8ZTyWFdrRXH9DUurXC1U0 secret/data/path/test1/any
deny
$ vault token capabilities -accessor Qkj8ZTyWFdrRXH9DUurXC1U0 secret/data/path/test2/any
list, read

### the metadata on the token is unchanged, so metadata and expected permissions from policy do not match anymore:
$ vault token lookup -accessor Qkj8ZTyWFdrRXH9DUurXC1U0 | grep meta
meta                map[foo:test1 role_name:testapprole]
```

This was tested with 1.16 and 1.17 as single-node docker container, 1.16 as cluster on Debian/12. Behavior is the same with batch and service token.

**Comment by miagilepner** [comment] 2024-06-27 11:01
Hi, thanks for reporting this. After looking into it, I realize that it's not a bug and is in fact expected behavior. 

The approle auth method uses the role_id to determine whether a client already exists (and thus should have it's data updated) or if vault needs to create a new entity for this client. In this case, the role_id is the same so the metadata gets updated. The documentation page describing the [identity system](https://developer.hashicorp.com/vault/docs/concepts/identity#mount-bound-aliases) has more details on what exactly is happening.

I would suggest using a different pattern for authentication. I'm going to close this ticket, as the behavior is expected.

**Closed by miagilepner** 2024-06-27 11:01 UTC
Labels: core/policy
