### ISSUE TITLE
cannot connect to LDAP: could not append CA certificate

### ISSUE THREAD

**Issue by enkaskal** [hashicorp/vault#1549] opened 2016-06-21 21:47 UTC
when trying to rollout the new vault version 0.6.0 as soon as it takes master and anybody tries to `vault auth -method=ldap username=someuser `we receive the error: `cannot connect to LDAP: could not append CA certificate`. However, as soon as we step-down the 0.6.0 instance, thus reverting back to 0.5.3, we are able to once again authenticate successfully. I didn't see anything in the release notes for deprecations/breaking changes so I'm curious if anybody else is having this issue?

**Comment by jefferai** [comment] 2016-06-21 22:47
Hi @enkaskal ,

Definitely not a known breaking change, so if this isn't working anymore it's a regression/bug. Let me dig into it.

**Comment by jefferai** [comment] 2016-06-22 14:06
Hi @enkaskal ,

Any chance I can get your CA certificate (not private key) to use for testing?

**Comment by enkaskal** [comment] 2016-06-22 20:42
sure, I'd be happy to email it to you. if that works, what address should i use?

**Comment by jefferai** [comment] 2016-06-22 20:46
jeff @ <my company>.com will do it. Thanks!

**Comment by jefferai** [comment] 2016-06-30 13:08
Hi @enkaskal 

I found the code giving that error, and I took that code and your CA cert and made a little test program, and no luck reproducing.

Since you seem to be fine testing out custom builds, any chance I can have you try out a custom build that prints out the certificate that it is attempting to add? I wonder if there is some junk (e.g. whitespace junk, maybe) in the string that earlier Go versions were fine with but have since been disallowed.

I could either give you a couple of lines to add or a branch to build off of.

**Comment by enkaskal** [comment] 2016-06-30 17:41
@jefferai i'm happy to build and test a branch.

**Comment by jefferai** [comment] 2016-06-30 17:55
Great -- there's a branch called `cert-appending-problem` -- when you run the code it will spit out some useful info. The CA cert will be a part of that, so if you don't want it here publicly, feel free to email me the output. Thanks!

**Comment by jefferai** [comment] 2016-06-30 21:26
The string there should be the actual PEM string from the certificate file -- not the name of the file.

My *guess* is that during configuration someone meant to do 'certificate=@/usr/share/ca-certificates/ldap_ca_cert.pem' but forgot the '@', so instead of including the file's contents it just set it to the name of the file.

I honestly have no clue right now why your existing servers would continue to work. The code in Vault hasn't changed since July and the code in Go for that function hasn't changed since 2011.

**Comment by enkaskal** [comment] 2016-07-06 04:52
@jefferai my apologies for the delay in response as well as not confirming in a second environment. I will do so tomorrow and have a calendar reminder JIC.

**Comment by enkaskal** [comment] 2016-07-06 23:04
@jefferai your guess proved correct and I'm just as baffled as to why it works fine [0.4.0,0.5.3]. 

unfortunately, when I make that change I receive the following error message when trying to authenticate to vault 0.5.3:

`* LDAP bind failed: LDAP Result Code 200 "": ldap: connection closed`

using 0.6.0 I get a little more information: 

`* cannot connect to LDAP: LDAP Result Code 200 "": TLS handshake failed (x509: certificate is valid for LDAP-INSTANCE-HOSTNAME.example.com, not example.com)``

N.B. the (domain) names have been changed to protect the innocent ;)

however, it works if the vault's auth/ldap/config is hardcoded to a specific host (e.g. ldap://LDAP-INSTANCE-HOSTNAME.example.com) but that means we would lose the ability to failover without having to reconfigure the vault. 

unless I'm missing something?

**Comment by jefferai** [comment] 2016-07-06 23:15
Just looked at code going back to 0.4 and honestly couldn't find an explanation for behavior with the old version. The only real change in this area is that in past versions some errors could be hidden so that it was hard to tell what the real problem was: that's the difference in the error message between 0.5.3 and 0.6.

Unfortunately the only two options are to set the insecure_tls option to disable hostname checking, or to fix your certificates by adding the real hostnames of your various LDAP hosts as SANs on the certificate.

**Comment by enkaskal** [comment] 2016-07-07 05:57
Hmm, I'm not a fan of setting the insecure_tls option, and I must admit that I'm not an expert on Microsoft's AD CS so I'll have to dig in a little more to see what can be done. To date we've just provided the root enterprise cert; which JustWork'd™. If you or anybody else has advice on how to setup such a SAN cert in an AD environment I'd greatly appreciate it :)

**Comment by jefferai** [comment] 2016-07-07 13:07
Honestly I don't know. However, if you'll allow me, might I suggest having your root enterprise cert issue an intermediate CA cert, load that into Vault's PKI backend, and go to town. That backend makes it very easy to issue certs with SANs and other large combinations of options :-)

**Comment by jefferai** [comment] 2016-07-18 17:23
I think at this point it's a matter of getting certs in order more than anything else, so I'm going to close this -- if you think that there's still something on the Vault side, let me know!

**Closed by jefferai** 2016-07-18 17:23 UTC
