### ISSUE TITLE
missing vault_core_unsealed metrics for non-leader nodes

### ISSUE THREAD

**Issue by mike2194** [hashicorp/vault#13450] opened 2021-12-15 20:07 UTC
**Describe the bug**
value missing for metric `vault_core_unsealed` for cluster nodes that are not sealed.

**To Reproduce**
1. enable un-auth metrics
2. collect metrics for all cluster nodes
3. unable to find metric `vault_core_unsealed` for non-leader nodes.

**Expected behavior**
expecting to find metric `vault_core_unsealed` for every node, if it is sealed value should be "0".

**Environment:**
* Vault Enterprise 1.7.2
* Vault client 1.72
* debian linux stable

Vault server configuration file(s):

```hcl
## default.hcl
 25 ui = true
 24
 23 listener "tcp" {
 22   address         = "0.0.0.0:8200"
 21   cluster_address = "0.0.0.0:8201"
 20   tls_cert_file   = "/opt/vault/tls/vault.crt"
 19   tls_key_file    = "/opt/vault/tls/vault.key"
 18
 17   telemetry {
 16     unauthenticated_metrics_access = "true"
 15   }
 14 }
 13
 12 storage "raft" {
 11   path = "/vault/data"
 10   node_id = "${MY_IP}"
  9
  8   retry_join {
  7     auto_join = "provider=aws region=${AWS_DEFAULT_REGION} tag_key=Name tag_value=${REALM_NAME}-mgmt-vault-${AWS_DEFAULT_REGION}"
  6     leader_ca_cert_file = "/opt/vault/tls/ca.crt"
  5     leader_tls_servername = "${AWS_DEFAULT_REGION}.vault.mgmt.${REALM_DOMAIN}"
  4   }
  3 }
  2
  1 disable_mlock = true

## prometheus.hcl
 38 telemetry {
 37   prometheus_retention_time = "24h",
 36   disable_hostname = true
 35 }
```

**Additional context**
tested with prometheus metrics

**Comment by hsimon-hashicorp** [comment] 2021-12-15 20:10
Hello @mike2194 - this looks like a duplicate of #10015 so I am going to close this issue and nudge the linked issue along. Thanks for your patience!

**Closed by hsimon-hashicorp** 2021-12-15 20:10 UTC
Labels: core/metric, core/telemetry

**Comment by mike2194** [comment] 2021-12-15 21:09
Thanks, missed that issue when searching for the metric name exactly

**Comment by hsimon-hashicorp** [comment] 2021-12-15 21:17
> Thanks, missed that issue when searching for the metric name exactly

No worries at all! It'll be something we consider when thinking about how to make existing issue reports easier to find, as we work to continually improve the process and experience for our contributors. :)
