### ISSUE TITLE
Vault CLI always hangs for a few seconds on Windows

### ISSUE THREAD

**Issue by rageshkrishna** [hashicorp/vault#12536] opened 2021-09-11 05:25 UTC
**Describe the bug**
Running any vault command in Windows is delayed almost 10 seconds before anything happens. This is true even if run `vault --version`

**To Reproduce**
1. Run `vault --version`
2. Wait for ~10 seconds
3. See the output

**Expected behavior**
There shouldn't be a 10 second delay.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Irrelevant; just printing the version triggers the delay. No `VAULT_ADDR` or any other `VAULT` envs were set.
* Vault CLI Version (retrieve with `vault version`): Vault v1.8.2 (aca76f63357041a43b49f3e8c11d67358496959f)
* Client Operating System/Architecture: Client is on Windows 11 / x64

Vault server configuration file(s): Irrelevant

**Comment by aphorise** [comment] 2021-09-11 10:27
@rageshkrishna this is likely something specific to your machine - more so if you've not made a comparisons relative to some other systems running the same version. What's more the likelihood of it of it being specific to your system is even more so if you're experiencing the same sort of slowness with all other versions of vault.

For example on my system using PowerShell Prompt (you also didn't mention what you used):

```powershell
PS C:\> (Measure-Command { vault --version | Out-Default }).ToString()
  # Vault v1.8.2 (aca76f63357041a43b49f3e8c11d67358496959f)
  # 00:00:00.6710139
```

You may want to give a few systems as well as versions a try and consider closing.

PS - In the future mention the type of system / version of Vault you're using (32bit / 64) as well as some hardware, specific OS (exact versions) and other details as relevant.

**Comment by rageshkrishna** [comment] 2021-09-12 04:28
Thanks for the pointers, @aphorise. Here's some more information if it helps:

1. Client 1: Windows 11 (Version 21H2 Build 22000.184), running Vault CLI 64-bit 1.8.2 (aca76f) in `cmd` inside Windows Sandbox to rule out any other tooling conflicts
2. Client 2: Windows 10 (Version 21H1 Build 19043.1165), running Vault CLI 64-bit 1.8.1 (4b0264) in Powershell 7.1.4

The delay on both of these machines is roughly the same:

```
(Measure-Command { .\vault --version | Out-Default }).ToString()
Vault v1.8.2 (aca76f63357041a43b49f3e8c11d67358496959f)
00:00:07.8578195
```

Now, the interesting bit is that on the same machines there is no delay when running in WSL:

```
$ time vault --version
Vault v1.8.2 (aca76f63357041a43b49f3e8c11d67358496959f)

real    0m0.499s
user    0m0.115s
sys     0m0.102s

$ uname -a
Linux Adenium 5.10.43.3-microsoft-standard-WSL2 #1 SMP Wed Jun 16 23:47:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

I'm wondering if it could be something about my network. I'm running Tailscale, but disconnecting didn't make any difference. I'm also not sure why `vault --version` would need to go over the network anyway. Any other pointers? Something I can do to debug what in the CLI (if anything) that it's getting stuck on?

**Comment by AndrewSav** [comment] 2021-09-14 07:13
In golang the `init` functions are run before the program run. Each dependency of a project and dependency of dependency and so on can have those init functions. If one runs away we have a slow down. In this particular case it is caused by the [aerospike go client](https://github.com/aerospike/aerospike-client-go/blob/22089645cc0a6764c0b34f50dab91b369e79e0f9/types/rand/xor_shift128.go#L36) combined with a [golang bug in the `time.sleep` function](https://github.com/golang/go/issues/44343). The net result that on certain machines microseconds turn into milliseconds, and the sleep delay in a loop like in aerospike becomes noticeable.

The good new is that aerospike fixed this issue already, and there is a [PR in flight](https://github.com/hashicorp/vault/pull/12165) to update to the latest version of aerospike. The issue will disappear then.

For right now, if you do not mind compiling Vault manually (and you do not use aerospike) just comment out the sleep line in the aerospike source code and re-compile, the delay goes away.

**Comment by rageshkrishna** [comment] 2021-09-14 10:37
Thanks @AndrewSav. I can confirm that this is indeed the issue for me:

```
init github.com/aerospike/aerospike-client-go/logger @407 ms, 0 ms clock, 128 bytes, 2 allocs
init github.com/aerospike/aerospike-client-go/types/rand @407 ms, 7904 ms clock, 16464 bytes, 514 allocs
init github.com/yuin/gopher-lua/parse @8312 ms, 0 ms clock, 944 bytes, 2 allocs
```

I'll keep this issue open until I can verify the fix with the 1.9 release.

**Comment by rageshkrishna** [comment] 2021-10-03 14:45
@AndrewSav Would you happen to have an ETA for the 1.9 release? In the mean time, as a workaround, I suppose I could just downgrade the CLI on my Windows machines to an older release that isn't affected by this issue.

**Comment by AndrewSav** [comment] 2021-10-03 23:13
@rageshkrishna no.

**Comment by DanielBoulerice** [comment] 2021-11-23 19:11
I have the same issue with Vault 1.9 on Windows 10.  It hangs for around 7.2s everytime I send any command.

**Comment by DanielBoulerice** [comment] 2021-11-23 19:56
I had to revert to version 1.7 ([here](https://releases.hashicorp.com/vault/)) to make it work faster.

**Comment by thomaslevesque** [comment] 2021-11-30 16:24
Same issue here

**Comment by nvx** [comment] 2021-12-09 23:43
Just updated to Vault 1.9.1 on Windows which seems to have fixed the issue! (Guessing #12165 did the trick)

**Comment by DanielBoulerice** [comment] 2021-12-10 18:15
I confirm: issue has been zapped in 1.9.1.

**Comment by hsimon-hashicorp** [comment] 2021-12-10 18:29
Huzzah! Thank you so much @nvx and @DanielBoulerice for reporting back!

**Closed by hsimon-hashicorp** 2021-12-10 18:29 UTC
Labels: core, os/windows
