### ISSUE TITLE
Starting from darwin 0.9.2 vault ssh command end with crash

### ISSUE THREAD

**Issue by samm-git** [hashicorp/vault#3972] opened 2018-02-14 12:29 UTC
**Environment:**

* Vault Version: Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')
* Operating System/Architecture: Darwin  16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64

(also same with vault 0.9.2, but works fine on 0.9.1)

**Expected Behavior:**
```
vault ssh  -role core -mode dynamic core@myserver id
Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.
uid=500(core) gid=500(core) groups=500(core),10(wheel),233(docker),248(systemd-journal),250(portage),251(rkt),253(fleet) context=system_u:system_r:kernel_t:s0
```
**Actual Behavior:**

```
vault ssh  -role core -mode dynamic core@myserver id
Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.
uid=500(core) gid=500(core) groups=500(core),10(wheel),233(docker),248(systemd-journal),250(portage),251(rkt),253(fleet) context=system_u:system_r:kernel_t:s0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13b5783]

goroutine 1 [running]:
github.com/hashicorp/vault/api.(*Client).NewRequest(0x0, 0x2cf5e5b, 0x3, 0xc42001afa0, 0x49, 0x0)
	/gopath/src/github.com/hashicorp/vault/api/client.go:472 +0x43
github.com/hashicorp/vault/api.(*Sys).Revoke(0xc4209e7af0, 0xc4209cbdc0, 0x33, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/api/sys_leases.go:24 +0xb0
github.com/hashicorp/vault/command.(*SSHCommand).handleTypeDynamic(0xc42081a320, 0x7fff5fbffa43, 0x4, 0xc4207a22a3, 0xd, 0xc42000e0f0, 0x1, 0x1, 0x0)
	/gopath/src/github.com/hashicorp/vault/command/ssh.go:603 +0x973
github.com/hashicorp/vault/command.(*SSHCommand).Run(0xc42081a320, 0xc42000e0e0, 0x2, 0x2, 0xc4206752c0)
	/gopath/src/github.com/hashicorp/vault/command/ssh.go:317 +0x4df
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4201c7540, 0xc4201c7540, 0xc4206777a0, 0xc4202625a0)
	/gopath/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
github.com/hashicorp/vault/command.Run(0xc42000e090, 0x7, 0x7, 0x2622fb9)
	/gopath/src/github.com/hashicorp/vault/command/main.go:47 +0x411
main.main()
	/gopath/src/github.com/hashicorp/vault/main.go:10 +0x63
```

**Steps to Reproduce:**
Run vault ssh to the server. Works as expected with 0.9.1 but crashes on exit with 0.9.2 and 0.9.3

**Important Factoids:**

**References:**

**Comment by jefferai** [comment] 2018-02-14 12:44
I believe this was fixed in master, any chance you can try?

**Comment by jefferai** [comment] 2018-02-14 14:51
I believe this is a duplicate of https://github.com/hashicorp/vault/pull/3909

**Comment by samm-git** [comment] 2018-02-14 15:58
Just tested with master, can confirm that it is fixed, thank you!

**Comment by jefferai** [comment] 2018-02-14 16:50
Great!

**Closed by jefferai** 2018-02-14 16:50 UTC
