### ISSUE TITLE
Empty `increment` causes token renew to panic

### ISSUE THREAD

**Issue by ianunruh** [hashicorp/vault#408] opened 2015-07-08 17:51 UTC
```
[~]$ export VAULT_ADDR='http://127.0.0.1:8200'
[~]$ export VAULT_TOKEN='d486ef52-d0db-2692-e653-cd84ed1b2652'

[~]$ vault version
Vault v0.2.0-rc (8b6d3809e76927990a538e29f4e6451da7f08c9b)

[~]$ vault token-create
Key            	Value
token          	f45e526f-736e-ed75-7ce4-c5d2b51cd2f0
token_duration 	0
token_renewable	false
token_policies 	[root]

[~]$ curl -i -XPOST -H "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/auth/token/renew/f45e526f-736e-ed75-7ce4-c5d2b51cd2f0 -d '{"increment": null}'
curl: (52) Empty reply from server
```

On the backend:

```
2015/07/08 10:49:13 http: panic serving 127.0.0.1:62803: error reading increment: invalid input '<nil>'
goroutine 22 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/hashicorp/vault/logical/framework.(*FieldData).GetOk(0xc208152930, 0xad87d0, 0x9, 0x0, 0x0, 0xc6642833e900bd01)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/logical/framework/field_data.go:49 +0x2b7
github.com/hashicorp/vault/logical/framework.(*FieldData).Get(0xc208152930, 0xad87d0, 0x9, 0x0, 0x0)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/logical/framework/field_data.go:31 +0x1fd
github.com/hashicorp/vault/vault.(*TokenStore).handleRenew(0xc2080eb3c0, 0xc2080a2400, 0xc208152930, 0x95e380, 0x0, 0x0)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/vault/token_store.go:670 +0x249
github.com/hashicorp/vault/vault.*TokenStore.(github.com/hashicorp/vault/vault.handleRenew)·fm(0xc2080a2400, 0xc208152930, 0xaa84b0, 0x0, 0x0)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/vault/token_store.go:201 +0x4d
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc20808c3f0, 0xc2080a2400, 0x0, 0x0, 0x0)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/logical/framework/backend.go:126 +0x813
github.com/hashicorp/vault/vault.(*Router).Route(0xc2080ea920, 0xc2080a2400, 0x0, 0x0, 0x0)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/vault/router.go:208 +0xac1
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc20808e780, 0xc2080a2400, 0x0, 0x0, 0x0, 0x0)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/vault/core.go:420 +0x811
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc20808e780, 0xc2080a2400, 0x0, 0x0, 0x0)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/vault/core.go:362 +0x452
github.com/hashicorp/vault/http.request(0xc20808e780, 0x1186870, 0xc20814c5a0, 0xc2080f4000, 0xc2080a2400, 0xa7f9f0, 0x4)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/http/handler.go:78 +0x32
github.com/hashicorp/vault/http.func·002(0x1186870, 0xc20814c5a0, 0xc2080f4000)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/http/logical.go:65 +0x53f
net/http.HandlerFunc.ServeHTTP(0xc2080a96d0, 0x1186870, 0xc20814c5a0, 0xc2080f4000)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2080c3e90, 0x1186870, 0xc20814c5a0, 0xc2080f4000)
	/usr/local/go/src/net/http/server.go:1541 +0x17d
github.com/hashicorp/vault/http.func·001(0x1186870, 0xc20814c5a0, 0xc2080f4000)
	/Users/ianunruh/go/src/github.com/hashicorp/vault/http/help.go:18 +0x128
net/http.HandlerFunc.ServeHTTP(0xc2080ebc20, 0x1186870, 0xc20814c5a0, 0xc2080f4000)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2080329c0, 0x1186870, 0xc20814c5a0, 0xc2080f4000)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20814c500)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by sethvargo** [comment] 2015-07-08 21:29
Hi @ianunruh 

I am sorry you are having issues with Vault. I could have sworn we fixed this issue. What version of Vault are you running?

**Comment by ianunruh** [comment] 2015-07-08 21:34
I just pulled from master a few hours ago.

Vault v0.2.0-rc (8b6d3809e76927990a538e29f4e6451da7f08c9b)

**Comment by armon** [comment] 2015-07-08 22:50
@ianunruh I think the issue is that "increment" is being specified but with an invalid value. You should just omit the field entirely instead of specifying the null value.

**Comment by ianunruh** [comment] 2015-07-08 22:51
I agree, but in principle I feel like it shouldn't panic when given invalid inputs.

**Comment by armon** [comment] 2015-07-08 22:56
@ianunruh Agreed, this is fixed in master now, but in general optional arguments should be omitted instead of set to null.

**Closed** 2015-07-08 22:55 UTC
Labels: bug
