### ISSUE TITLE
inability to contact LDAP server leads to runtime error

### ISSUE THREAD

**Issue by richfromm** [hashicorp/vault#2186] opened 2016-12-14 23:00 UTC
I have vault configured with the LDAP auth backend. In general it's working fine.

If I intentionally sever the network connection between vault and the LDAP server, I would expect the authentication to fail:

```
$ vault auth -method=ldap username=rich
Password (will be hidden): 
Error making API request.

URL: PUT https://vault.*****.***:8200/v1/auth/ldap/login/rich
Code: 504. Raw Message:


rich@rich-trusty [14:43:17 Wed Dec 14] ~
```

However, on the server side, I also get the following (actually 3 of them):

```
2016-12-14 22:43:14.062235 I | http: panic serving 172.19.128.177:35688: runtime error: invalid memory address or nil pointer dereference
goroutine 8966 [running]:
```

A full log excerpt showing the three stack traces is attached.
[vault.log.txt](https://github.com/hashicorp/vault/files/653342/vault.log.txt)

**Comment by richfromm** [comment] 2016-12-15 00:05
I forgot to mention in the original report, this is with vault 0.6.1

**Comment by jefferai** [comment] 2016-12-15 00:35
Hi @richfromm ,

Can you please post your LDAP config? Thanks!

**Comment by jefferai** [comment] 2016-12-15 16:27
Hi @richfromm,

The PR above should fix the panic but not necessarily the underlying issue...the issue is basically that an error was coming back from the dial out to your LDAP server, but the contents were being swallowed by this panic. If you can build from source after it's merged you should get the actual error message to help you diagnose the problem.

**Comment by richfromm** [comment] 2016-12-16 01:54
Sorry for the delay in responding, does this mean you no longer need the LDAP config?

The most significant part is probably the URL, which requires a little explaining:
```
url            	ldap://localhost
```
Our vault server lives in AWS EC2, but our LDAP server is hosted internally and not available on the public Internet. For production use, we will need some better answer for vault to talk to LDAP (and we are currently considering our options), but for initial testing I am using ssh port forwarding, via something like:
```
ssh -o ServerAliveInterval=300 -R 389:our.internal.ldap.com:389 root@aws.vault.host.ipaddr
```
which forwards port 389 on the local host to port 389 on our LDAP server, as long as that ssh connection is maintained. Hence the `localhost` URL above.

This means that I can trivially reproduce the issue just by exiting the ssh session.

Even without that hack, I'm guessing you could probably reproduce it pretty easily, just by putting any unreachable URL in the LDAP config. Or maybe hacking the DNS looking by adding a sufficiently bogus entry to `/etc/hosts` so that it fails.

If the purpose of pointing me to the pull request is to help me in the short term, I'm actually okay. If I try to authenticate and the LDAP server is unreachable by vault, I expect it to fail. Yes, the nature of the failure is less than ideal, and something that better reported the nature of the error, and did not cause a stack trace on the server, would be better. But it's not holding up my work in any way.

If the purpose of pointing me to the pull request is that you want my help testing it, that will probably take a little longer. I have no personal experience with Go and don't even have a Go compiler installed. I'm guessing it's not that hard for me to get it working -- it appears from the README.md for vault at github that it's in theory as simple as downloading Go and running make -- but I can't make it my highest priority just right now.

**Comment by jefferai** [comment] 2016-12-16 02:52
Hi @richfromm ,

The PR merely fixes the panic so that the actual underlying error message is shown. If you are aware of what that error is and were simply reporting the panic, then I think this issue is fixed. If that's the case, feel free to close it!

**Comment by jefferai** [comment] 2017-01-24 19:50
Closing due to lack of response.

**Closed by jefferai** 2017-01-24 19:50 UTC

**Comment by richfromm** [comment] 2017-01-24 19:57
Sorry, I hadn't realized that you were awaiting a response from me.

For clarity, I know exactly why vault was unable to contact the LDAP server, and it was not a problem with vault. I was merely reporting that that networking problem led to a vault panic, which seemed like a minor bug to me, and it looks like it has now been fixed. (Based on the commit above, that is; I haven't tried to independently verify.)

**Comment by jefferai** [comment] 2017-01-25 20:30
OK, thanks!
