### ISSUE TITLE
Use Transit to verify signatures based solely on an imported public key

### ISSUE THREAD

**Issue by nicolascrochet7** [hashicorp/vault#20456] opened 2023-05-02 08:32 UTC
As a backend developer I wish I could verify tokens' signatures with Vault, for example a JWT, with only a public key supplied. 

The Transit Engine would import a public key without a private key, and when using the [verify signed data API](https://developer.hashicorp.com/vault/api-docs/secret/transit#verify-signed-data), it would return if the public key supplied can verify the supplied signature.

If I am not mistaken, the Veriy Signed Data is currently a mirrored API of the Sign Data, suggesting that Transit imports or creates a private&public keys set, but is not designed for solely import public keys.

This would help authenticate devices using Trusted Platform Modules, capable of creating their own token based on a embedded private&public keys, where private key is not accessible on purpose.

Of course, this is easily doable with any crypto library and public keys are easily stored ; but since Vault plays a central role in one's backend security design, it would feel more proper to use Vault in such authentication schema.

**Comment by cipherboy** [comment] 2023-05-02 22:25
This is a dupe of #4506, with a proposed patchset in https://github.com/hashicorp/vault/pull/17934 -- feel free to try it out and let us know if it works for your use case :-)

**Closed by cipherboy** 2023-05-02 22:25 UTC
Labels: feature-request, cryptosec
