### ISSUE TITLE
Add option to provide TLS configuration on database backends

### ISSUE THREAD

**Issue by calvn** [hashicorp/vault#3493] opened 2017-10-26 17:54 UTC
**Feature Request:**
Add option to provide TLS-related configuration on database backends. This would users to pass values such as CA cert/path that was used to sign the cert used for SSL connection by the database. Though this can be addressed by importing the CA certs into Vault's host as described in #1996, this provides an overall nicer UX flow.

**Comment by vreon** [comment] 2018-01-02 19:02
Related to / duplicate of #3191?

**Comment by jefferai** [comment] 2018-01-03 16:17
Yep, looks related. Closing as duplicate.

**Closed by jefferai** 2018-01-03 16:17 UTC
