### ISSUE TITLE
Trying to reset the unsealing process from the HTTP API causes validation error.

### ISSUE THREAD

**Issue by megahbite** [hashicorp/vault#920] opened 2016-01-11 12:57 UTC
According to the [current documentation](https://www.vaultproject.io/docs/http/sys-unseal.html), the unseal endpoint supports resetting the process through an optional `reset` parameter. Unfortunately, setting this to true does not produce the expected behaviour. It appears the API is validating the `key` parameter and requiring its presence (despite the documentation)

To reproduce with curl on a sealed vault:

`curl -X PUT -H "Content-Type: application/json" --data-binary '{"reset":true}' http://127.0.0.1:8200/v1/sys/unseal`

Expected to receive the seal status back with `progress` reset to zero.

Received `{"errors":["'key' must specified in request body as JSON"]}` instead.

**Comment by jefferai** [comment] 2016-01-11 15:08
I can't reproduce this using current `master`:

> $ curl -X PUT -H "Content-Type: application/json" --data-binary '{"reset":true}' http://127.0.0.1:8200/v1/sys/unseal
> {"sealed":true,"t":1,"n":1,"progress":0}

What version of Vault are you running?

**Comment by jefferai** [comment] 2016-01-11 15:10
I believe this was behavior that was fixed in 0.4. If you are running 0.4 and still seeing this behavior, please let me know and we can dig in.

Thanks!

**Closed by jefferai** 2016-01-11 15:10 UTC
Labels: waiting-reply

**Comment by megahbite** [comment] 2016-01-12 09:16
Ah, you're right. Sorry, should have double checked there wasn't a new version out.
