### ISSUE TITLE
Concourse + vault lead to very high CPU usage by vault

### ISSUE THREAD

**Issue by EugenMayer** [hashicorp/vault#3651] opened 2017-12-05 09:15 UTC
I am using vault in combination with concourse ci and running into very high load.
 
Vault is running on a VM with 4 sockets of a `Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz` ( qemu ) and 26GB RAM. That VM is shared with concourse ci.

While not a single job is running and only checks are done ( for newer revisions / trigger ) vault is creating a constant load of 6-7 - i guess it is queried for every cred for every check.

Are there any ways to fine-tune that?

I am did increase https://github.com/EugenMayer/docker-image-concourse-configurator/blob/master/bin/vault_init.sh#L51 from 3600 to 3600 to have the token live for a longer time.
Then general setup is https://github.com/EugenMayer/docker-image-concourse-configurator/blob/master/bin/vault_init.sh#L6

And the vault container is running with https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/concourseci/4/docker-compose.yml#L17

Any clues i can make this any better?

**Comment by jefferai** [comment] 2017-12-06 16:44
Unfortunately we don't have much insight into Concourse and the way it uses Vault. You may want to turn on audit logging to get an idea for what calls are being made and if you see some calls being made repeatedly by Concourse that might be the cause of this.

**Comment by EugenMayer** [comment] 2017-12-06 17:57
@jefferai for my general understanding, how "expensive" is one call in on vault?

Fetching one value, lets say < 200byte, what does that mean for vault? I understand, there is encryption involved, but is it as expensive?

What i see in concourse ci, that ever resource is going to trigger vault at last to time per scheduled run, means by default every minute. We have about 150 resources, that makes it up for 300 calls + some have 4, so lets do a 400 calls per minutes. How does this scale with vault in general? Currentlt vault is generating more load then the actual pretty laod-expensive builds

**Comment by jefferai** [comment] 2017-12-06 22:27
Hi @EugenMayer ,

With proper configuration (not being limited on storage I/O, re-using HTTP connections when possible, etc.) in a perfect world Vault can theoretically handle thousands to tens of thousands of requests per second. In practice, customers often see hundreds to a few thousand. The behavior when scaling past a given setup's max point depends on what the limiting factor is. 300-400 calls per minute should be a piece of cake though.

**Comment by EugenMayer** [comment] 2017-12-06 22:33
I got told that the TTL on the cert could be a pointer, so i gave that a little boost to 3600s.

But now i am out of options. The servers I/O is by no means saturated, its rather just a new box with concourse only. I am using file storage, but those drives are non SSD - should i rather pick consul here?

Vault is in the same docker-network here, so network saturation could not be an issue, right. HTTP connection reusage on  concourse side .. that is where i doubt things - how much of an impact would that make?

**Comment by jefferai** [comment] 2017-12-06 22:45
Not enough. You didn't provide the vault version or config file; at this point I'm not sure how to give any more guidance without those bits and a trace level log from Vault (which is dumped to stderr on startup). Any chance you can provide those?

**Comment by EugenMayer** [comment] 2017-12-06 22:57
Actually some of those i did with the links above, but let me sum those up

 - vault 0.9.0 as a [docker container](https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/concourseci/4/docker-compose.yml#L19)
 - [the vault configration](https://github.com/EugenMayer/docker-image-concourse-configurator/blob/master/bin/docker-entrypoint.sh#L31)
 - the [client policy](https://github.com/EugenMayer/docker-image-concourse-configurator/blob/master/bin/docker-entrypoint.sh#L42)
 - client [certificate creation](https://github.com/EugenMayer/docker-image-concourse-configurator/blob/master/bin/vault_client_cert.sh#L6) ( if that gives you any hints )
 - the client [certificate configuration / storage](https://github.com/EugenMayer/docker-image-concourse-configurator/blob/master/bin/vault_init.sh#L46)

The stacktrace:

```
06/12/2017 22:31:13==> Vault server configuration:
06/12/2017 22:31:13
06/12/2017 22:31:13                     Cgo: disabled
06/12/2017 22:31:13              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
06/12/2017 22:31:13               Log Level: info
06/12/2017 22:31:13                   Mlock: supported: true, enabled: true
06/12/2017 22:31:13                 Storage: file
06/12/2017 22:31:13                 Version: Vault v0.9.0
06/12/2017 22:31:13             Version Sha: bdac1854478538052ba5b7ec9a9ec688d35a3335
06/12/2017 22:31:13
06/12/2017 22:31:13==> Vault server started! Log data will stream in below:
06/12/2017 22:31:13
06/12/2017 22:31:132017/12/06 21:31:13 http: TLS handshake error from 10.42.77.53:41139: EOF
06/12/2017 22:31:182017/12/06 21:31:18.702944 [INFO ] core: vault is unsealed
06/12/2017 22:31:182017/12/06 21:31:18.703807 [INFO ] core: post-unseal setup starting
06/12/2017 22:31:182017/12/06 21:31:18.704656 [INFO ] core: loaded wrapping token key
06/12/2017 22:31:182017/12/06 21:31:18.704707 [INFO ] core: successfully setup plugin catalog: plugin-directory=
06/12/2017 22:31:182017/12/06 21:31:18.705588 [INFO ] core: successfully mounted backend: type=kv path=secret/
06/12/2017 22:31:182017/12/06 21:31:18.705802 [INFO ] core: successfully mounted backend: type=system path=sys/
06/12/2017 22:31:182017/12/06 21:31:18.706035 [INFO ] core: successfully mounted backend: type=identity path=identity/
06/12/2017 22:31:182017/12/06 21:31:18.706076 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
06/12/2017 22:31:182017/12/06 21:31:18.770919 [INFO ] expiration: restoring leases
06/12/2017 22:31:182017/12/06 21:31:18.771941 [INFO ] rollback: starting rollback manager
06/12/2017 22:31:182017/12/06 21:31:18.863342 [INFO ] expiration: lease restore complete
06/12/2017 22:31:182017/12/06 21:31:18.863673 [INFO ] identity: entities restored
06/12/2017 22:31:182017/12/06 21:31:18.863704 [INFO ] identity: groups restored
06/12/2017 22:31:182017/12/06 21:31:18.863725 [INFO ] core: post-unseal setup complete
```

Anything else you need?

**Comment by jefferai** [comment] 2017-12-06 23:14
Can you provide a trace level log?

**Comment by EugenMayer** [comment] 2017-12-06 23:16
Not sure how to do that, any advice?

**Comment by EugenMayer** [comment] 2017-12-06 23:19
Found `-log-level=trace` - is there any way doing that using ENV - it rather hard now to reconfigure that in the running container - setting ENV and recreating would be far easier

**Comment by jefferai** [comment] 2017-12-06 23:22
There is not currently a way to do that with env vars.

**Comment by EugenMayer** [comment] 2017-12-06 23:27
Well trying to see how i can start the container with those flags. Looking at https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/concourseci/4/docker-compose.yml#L31 i will create a rancher-condition here to start with our without log level. Which one will you need? `-log-level=trace` ?

IS any confidential data exposed this way?

**Comment by jefferai** [comment] 2017-12-11 17:54
We try not to expose confidential information in logs, even trace logs.

**Comment by EugenMayer** [comment] 2017-12-14 19:46
So, took me a while sorry, added trace and what i mainly see is:

```
14/12/2017 20:32:272017/12/14 19:32:27.919710 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:32:272017/12/14 19:32:27.919714 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:33:272017/12/14 19:33:27.919648 [TRACE] rollback: attempting rollback: path=secret/
14/12/2017 20:33:272017/12/14 19:33:27.919739 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:33:272017/12/14 19:33:27.919824 [TRACE] rollback: attempting rollback: path=identity/
14/12/2017 20:33:272017/12/14 19:33:27.919827 [TRACE] rollback: attempting rollback: path=sys/
14/12/2017 20:33:272017/12/14 19:33:27.919828 [TRACE] rollback: attempting rollback: path=cubbyhole/
14/12/2017 20:33:272017/12/14 19:33:27.919829 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:34:272017/12/14 19:34:27.920210 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:34:272017/12/14 19:34:27.920255 [TRACE] rollback: attempting rollback: path=secret/
14/12/2017 20:34:272017/12/14 19:34:27.920284 [TRACE] rollback: attempting rollback: path=sys/
14/12/2017 20:34:272017/12/14 19:34:27.920304 [TRACE] rollback: attempting rollback: path=identity/
14/12/2017 20:34:272017/12/14 19:34:27.920317 [TRACE] rollback: attempting rollback: path=cubbyhole/
14/12/2017 20:34:272017/12/14 19:34:27.920340 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:35:272017/12/14 19:35:27.923093 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:35:272017/12/14 19:35:27.923127 [TRACE] rollback: attempting rollback: path=secret/
14/12/2017 20:35:272017/12/14 19:35:27.923129 [TRACE] rollback: attempting rollback: path=sys/
14/12/2017 20:35:272017/12/14 19:35:27.923131 [TRACE] rollback: attempting rollback: path=identity/
14/12/2017 20:35:272017/12/14 19:35:27.923132 [TRACE] rollback: attempting rollback: path=cubbyhole/
14/12/2017 20:35:272017/12/14 19:35:27.923134 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:36:272017/12/14 19:36:27.919558 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:36:272017/12/14 19:36:27.919681 [TRACE] rollback: attempting rollback: path=secret/
14/12/2017 20:36:272017/12/14 19:36:27.919684 [TRACE] rollback: attempting rollback: path=cubbyhole/
14/12/2017 20:36:272017/12/14 19:36:27.919685 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:36:272017/12/14 19:36:27.919687 [TRACE] rollback: attempting rollback: path=sys/
14/12/2017 20:36:272017/12/14 19:36:27.919707 [TRACE] rollback: attempting rollback: path=identity/
14/12/2017 20:37:272017/12/14 19:37:27.919504 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:37:272017/12/14 19:37:27.919706 [TRACE] rollback: attempting rollback: path=secret/
14/12/2017 20:37:272017/12/14 19:37:27.919735 [TRACE] rollback: attempting rollback: path=identity/
14/12/2017 20:37:272017/12/14 19:37:27.919770 [TRACE] rollback: attempting rollback: path=sys/
14/12/2017 20:37:272017/12/14 19:37:27.919776 [TRACE] rollback: attempting rollback: path=cubbyhole/
14/12/2017 20:37:272017/12/14 19:37:27.919778 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:38:272017/12/14 19:38:27.919665 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:38:272017/12/14 19:38:27.919736 [TRACE] rollback: attempting rollback: path=secret/
14/12/2017 20:38:272017/12/14 19:38:27.919739 [TRACE] rollback: attempting rollback: path=sys/
14/12/2017 20:38:272017/12/14 19:38:27.919741 [TRACE] rollback: attempting rollback: path=cubbyhole/
14/12/2017 20:38:272017/12/14 19:38:27.919742 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:38:272017/12/14 19:38:27.919749 [TRACE] rollback: attempting rollback: path=identity/
14/12/2017 20:39:272017/12/14 19:39:27.919587 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:39:272017/12/14 19:39:27.919745 [TRACE] rollback: attempting rollback: path=secret/
14/12/2017 20:39:272017/12/14 19:39:27.919747 [TRACE] rollback: attempting rollback: path=cubbyhole/
14/12/2017 20:39:272017/12/14 19:39:27.919749 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:39:272017/12/14 19:39:27.919750 [TRACE] rollback: attempting rollback: path=sys/
14/12/2017 20:39:272017/12/14 19:39:27.919756 [TRACE] rollback: attempting rollback: path=identity/
14/12/2017 20:40:272017/12/14 19:40:27.919782 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:40:272017/12/14 19:40:27.919784 [TRACE] rollback: attempting rollback: path=sys/
14/12/2017 20:40:272017/12/14 19:40:27.919786 [TRACE] rollback: attempting rollback: path=secret/
14/12/2017 20:40:272017/12/14 19:40:27.919789 [TRACE] rollback: attempting rollback: path=cubbyhole/
14/12/2017 20:40:272017/12/14 19:40:27.919790 [TRACE] rollback: attempting rollback: path=identity/
14/12/2017 20:40:272017/12/14 19:40:27.919791 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:41:272017/12/14 19:41:27.919758 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:41:272017/12/14 19:41:27.919802 [TRACE] rollback: attempting rollback: path=cubbyhole/
14/12/2017 20:41:272017/12/14 19:41:27.919805 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:41:272017/12/14 19:41:27.919805 [TRACE] rollback: attempting rollback: path=secret/
14/12/2017 20:41:272017/12/14 19:41:27.919807 [TRACE] rollback: attempting rollback: path=sys/
14/12/2017 20:41:272017/12/14 19:41:27.919812 [TRACE] rollback: attempting rollback: path=identity/
14/12/2017 20:42:272017/12/14 19:42:27.919722 [TRACE] rollback: attempting rollback: path=auth/cert/
14/12/2017 20:42:272017/12/14 19:42:27.919786 [TRACE] rollback: attempting rollback: path=cubbyhole/
14/12/2017 20:42:272017/12/14 19:42:27.919800 [TRACE] rollback: attempting rollback: path=identity/
14/12/2017 20:42:272017/12/14 19:42:27.920167 [TRACE] rollback: attempting rollback: path=auth/token/
14/12/2017 20:42:272017/12/14 19:42:27.920432 [TRACE] rollback: attempting rollback: path=sys/
14/12/2017 20:42:272017/12/14 19:42:27.921658 [TRACE] rollback: attempting rollback: path=secret/
```

to be clear, during the whole time, not a single value has been written, reads only. Anything else i can provide?

**Comment by jefferai** [comment] 2017-12-14 19:56
No, those entries are normal and nothing else seems to be amiss. You're using the `file` storage backend. Any chance your disk I/O is expensive?

**Comment by EugenMayer** [comment] 2017-12-14 20:00
Yes using file, could use consul easily if that is of any use here?

I migrated vault to an SSD drive. My `wa` is rather pretty low, round about max 10 and usually < 0.5

**Comment by vito** [comment] 2017-12-17 23:11
Cross-referencing https://github.com/concourse/atc/pull/236 - a PR to Concourse to cache the credentials.

Per https://github.com/concourse/atc/pull/236#issuecomment-352293407, I'm a little afraid to be implementing this ourselves. Is there any recommendation as to whether the approach is correct/ideal or if there is a plan to bring that kind of implementation into an official Vault client of some sort (so we're not implementing it ourselves, and the next project isn't either)?

**Comment by EugenMayer** [comment] 2017-12-18 08:19
@vito thank you a lot for taken a chance at this!

After optimizing the vault stack i am not sure this is actually something we could have achived throughe vault angle. I think maybe optimize either the amount of queries or optimize the TTL of the client cert ( tried that, did not help ).

I think there might have been 2 issues, either the general amount of queries or the way the HTTP client has been used. I will continue trying / contributing / testing to https://github.com/concourse/atc/pull/236 to see if we can get anything done effictivly and report back here if there might be anything else

**Comment by catsby** [comment] 2019-11-07 21:34
Hello - I'm going to close this issue for now, as it didn't seem to be an issue with Vault itself. Please let me know if you have more information for us to reconsider. Thanks!

**Closed by catsby** 2019-11-07 21:34 UTC
