### ISSUE TITLE
How to Publicly-trusted certificates using Hashicorp PKI  and let's encrypt 

### ISSUE THREAD

**Issue by sithuyeaung** [hashicorp/vault#7576] opened 2019-10-05 04:27 UTC
In my test Env (Hashicorp PKI) . very nice but i don't know how to do config public trusted certificate using let's encrypt certificate . Please help me .......

**Comment by michelvocks** [comment] 2019-11-05 12:26
Duplicate of https://github.com/hashicorp/vault/issues/4950

**Closed by michelvocks** 2019-11-05 12:26 UTC
