### ISSUE TITLE
Add mysql connection details to /mysql/creds/<role> response.

### ISSUE THREAD

**Issue by singram** [hashicorp/vault#1662] opened 2016-07-27 19:58 UTC
The mysql backend must be configured with a mysql connection string but there appears to be no way to surface this back to a user of vault without specifying it as a separate secret.

Is there any reason why the mysql server host details could not be included in the return when creating a set of dynamic credentials given the user must be authenticated & authorized to make the call in the first place?  This would also be useful if the connection string was redirected to another database for some reason.

**Comment by jefferai** [comment] 2016-07-27 20:15
Duplicate of #317

**Closed by jefferai** 2016-07-27 20:15 UTC
