### ISSUE TITLE
vault auth help approle generates INTERNAL ERROR message

### ISSUE THREAD

**Issue by DaleBingham** [hashicorp/vault#4075] opened 2018-03-05 12:23 UTC
**Environment:**
* Vault Version: 0.9.5
* Operating System/Architecture: Docker latest pull from DockerHub running on Mac OSX latest

**Vault Config File:**
{
	"listener": [{
		"tcp": {
			"address": "0.0.0.0:8200",
			"tls_disable" : 1
		}
	}],
	"storage" :{
		"file" : {
			"path" : "/vault/data"
		}
	}
	"max_lease_ttl": "10h",
	"default_lease_ttl": "10h",
}

**Startup Log Output:**
none

**Expected Behavior:**
a printout of help for the approle authentication similar to 'vault auth help aws' and 'vault auth help github'

**Actual Behavior:**
INTERNAL ERROR! Found an auth method enabled at approle/, but its type "approle" is not registered in Vault. This is a bug and should be reported. Please open an issue at github.com/hashicorp/vault.

**Steps to Reproduce:**
Initialize Vault w/in docker w/ the config above. Setup the VAULT_ADDR appropriately. Initialize. Enable the approle auth. Then type the command above to get the error. 

**Important Factoids:**
I am opening port 8200 with -p 8200:8200 w/in my Docker run command

**References:**
none

**Comment by DaleBingham** [comment] 2018-03-05 12:25
what I ran:
`docker run -d -v /Users/dalebingham/Projects/vault:/vault --cap-add=IPC_LOCK -p 8200:8200 --rm --name vault --privileged --hostname vault  vault server`

and then to get a shell into the container:
`docker exec -it vault /bin/sh`

**Comment by jefferai** [comment] 2018-03-07 05:20
Duplicate of #4056

**Closed by jefferai** 2018-03-07 05:20 UTC
