### ISSUE TITLE
days are not accepted as a period time unit

### ISSUE THREAD

**Issue by FalcoSuessgott** [hashicorp/vault#20438] opened 2023-04-29 21:11 UTC
**Describe the bug**
For some reason, any time duration using `d` is not accepted:

```bash
>  vault token create -orphan -policy=policy -period=1d
invalid value "1d" for flag -period: time: unknown unit "ds" in duration "1ds"
```

However, the docs state, that this should be possible: https://developer.hashicorp.com/vault/docs/concepts/duration-format#examples

**To Reproduce**
1. create a periodic token with any day-unit

**Expected behavior**
I expect vault to accept `d` as a valid time unit, since the docs clearly state [this](https://developer.hashicorp.com/vault/docs/concepts/duration-format)

**Environment:**
* Vault Server Version (retrieve with `vault status`): `v1.13.2`
* Vault CLI Version (retrieve with `vault version`): `v1.13.2`
* Server Operating System/Architecture : `Linux x86_64

**Comment by maxb** [comment] 2023-04-30 10:23
This was reported before at #19815 - in brief, Vault is inconsistent about whether it uses its own duration parsing logic (which supports days) or Go's default (which doesn't), so you experience different behaviour in different contexts :-(

**Comment by miagilepner** [comment] 2023-05-01 12:13
Hi, because this is an exact duplicate of #19815 I'm going to close it in favor of that issue.

**Closed by miagilepner** 2023-05-01 12:13 UTC
