### ISSUE TITLE
Vault with Consul backend fails to restore leases and seals itself during runtime

### ISSUE THREAD

**Issue by amruthar** [hashicorp/vault#7018] opened 2019-06-29 19:38 UTC
**Describe the bug**
We use Vault's AppRole auth mechanism to communicate through our application. At midnight there are scheduled sync calls that trigger a large number of requests to Vault. Around this time Vault fails to restore leases and seals itself, rendering vault unserviceable. Attaching Vault and Cosul logs for reference. 
This happens in a both single vault deployments as well as multi-vault deployments.

This error has also occured at other times randomly and rarely.

**We had no token ttl set for approle tokens and realised those might never get expired while the application requests for a new token regularly. We changed the ttl to 15 mins and also revoked all existing leases for our approle via the revoke-prefix API before continuing any other operations. Still this error persists.**

**To Reproduce**
1. Initialize and setup vault (Consul Backend) with approle with no token ttl or token max ttl.
2. Trigger large number of requests to vault.
3. Core shuts down and Vault seals itself.

**Expected behavior**
Vault should not get sealed.

**Environment:**
* 0.10.4
* 0.10.4
* CentOS

Vault server configuration file(s):

```hcl
disable_mlock = true
storage "consul" {
    scheme        = "https"
    address       = "x.x.x.x:5902"
    path          = "/vaultdata"
    service       = "vault"
    tls_ca_file   = "vault-cert.pem"
    tls_cert_file = "vault-cert.crt"
    tls_key_file  = "vault-cert.key"
}
api_addr =  "http://x.x.x.x:5920"
cluster_addr = "http://x.x.x.x:5921"
listener "tcp" {
    address             = "0.0.0.0:5920"
    cluster_address     = "0.0.0.0:5921"
    tls_disable         = 0
    tls_require_and_verify_client_cert = 1
    tls_client_ca_file  = "vault-cert.pem"
    tls_cert_file       = "vault-cert.crt"
    tls_key_file        = "vault-cert.key"
 }
```

**Additional context**
Attaching Consul and Vault logs during auto sealing for reference.

[consul_logs_when_Vault_Seals.log](https://github.com/hashicorp/vault/files/3342249/consul_logs_when_Vault_Seals.log)
[vault_sealed.log](https://github.com/hashicorp/vault/files/3342250/vault_sealed.log)

**Comment by jefferai** [comment] 2019-06-30 20:22
Duplicate of https://groups.google.com/d/msgid/vault-tool/da3f7abc-8258-4964-b8f7-c83014c35403%40googlegroups.com?utm_medium=email&utm_source=footer

**Closed by jefferai** 2019-06-30 20:22 UTC
