### ISSUE TITLE
Write-only policy for a path

### ISSUE THREAD

**Issue by boncheff** [hashicorp/vault#292] opened 2015-06-01 12:53 UTC
Is it (would it be) possible to have write-only policy for a specific path? The current option `write` enables you to `Read, write access to a path`, however I believe sometimes it would be helpful to have write-only permissions

**Comment by sethvargo** [comment] 2015-06-01 15:44
Duplicate of https://github.com/hashicorp/vault/issues/140. Thanks!

**Closed by sethvargo** 2015-06-01 15:44 UTC
