### ISSUE TITLE
Backend silently ignores improperly formatted certificates

### ISSUE THREAD

**Issue by brianshumate** [hashicorp/vault#2984] opened 2017-07-07 13:55 UTC
When configuring a backend (such as LDAP), Vault will ignore a certificate that is part of the configuration when that certificate is not PEM encoded, but the configuration write will appear to succeed without error.

A user can write configuration with a DER formatted certificate for example:

```
vault write auth/ldap/config \
    url="ldaps://der-encoding.example.com" \
    userattr="samAccountName" \
    userdn="OU=_USERS,OU=HAPPY_USERS,DC=DER-ENCODING,DC=example,DC=com" \
    groupdn="OU=_GROUPS,OU=HAPPY_THINGS*,DC=DER-ENCODING,DC=example,DC=com" \
    upndomain="der-encoding.example.com" \
    insecure_tls=false \
    starttls=true \
    certificate=@ldaps.der-encoding.example.com.public.der
```

and Vault will not complain, but the configuration will be invalid as it is missing the certificate value:

```
vault read auth/ldap/config
Key             Value
---             -----
binddn
bindpass
certificate
deny_null_bind  true
discoverdn      false
groupattr       cn
groupdn         OU=_GROUPS,OU=HAPPY_THINGS*,DC=DER-ENCODING,DC=example,DC=com
groupfilter     (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))
insecure_tls    false
starttls        true
tls_max_version tls12
tls_min_version tls12
upndomain       der-encoding.example.com
url             ldaps://der-encoding.example.com
userattr        samaccountname
userdn          OU=_USERS,OU=HAPPY_USERS,DC=DER-ENCODING,DC=example,DC=com
```

It would be nice to validate that the cert is properly PEM encoded and return an error otherwise.

**Comment by jefferai** [comment] 2017-07-17 14:48
Duplicate of #2954

**Closed by jefferai** 2017-07-17 14:48 UTC
