### ISSUE TITLE
Error with install of Hashicorp Vault: "command not found" when I search for vault binary after install. Can someone help?

### ISSUE THREAD

**Issue by jjrocketship** [hashicorp/vault#7514] opened 2019-09-26 00:23 UTC
Please post questions on the mailing list (https://groups.google.com/forum/#!forum/vault-tool) rather than in GitHub issues.
I get:

Jasons-MacBook-Pro:~ jason$ vault
-bash: vault: command not found

**Comment by michelvocks** [comment] 2019-09-26 09:16
Hi @jjrocketship,

it seems like you didn't install the Vault binary locally or you forgot to add the binary to your PATH environment variable. Please have a look at the install learning guide: https://learn.hashicorp.com/vault/getting-started/install

I will close this issue since this is not a bug. Please use for further questions the mailing list (which you have mentioned).

Cheers,
Michel

**Closed by michelvocks** 2019-09-26 09:16 UTC
