### ISSUE TITLE
Vault 0.3.0 amd64 binary distribution is dynamically linked

### ISSUE THREAD

**Issue by jurriaan** [hashicorp/vault#656] opened 2015-09-30 18:58 UTC
As you can see Vault 0.3 (https://dl.bintray.com/mitchellh/vault/vault_0.3.0_linux_amd64.zip) is dynamically linked
```
$ file vault
vault: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, 
  interpreter /lib64/ld-linux-x86-64.so.2, not stripped
```

While Vault 0.2.0 (https://dl.bintray.com/mitchellh/vault/vault_0.2.0_linux_amd64.zip) was statically linked:
```
$ file vault
vault: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, 
  not stripped
```

This makes it harder to run Vault 0.3.0 on a system where ld-linux is not in that particular location (say alpine linux which uses musl instead of glibc).

It does work by doing a `ln -s /lib/ld-musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2` before starting Vault... (but yeah, that's a bit of a hack :wink: )

**Comment by jefferai** [comment] 2015-10-01 01:57
Thanks for the report. I will need to look into this and see what the cause
is... it could be a number of things from a different version of Go to
changed dependencies.

We've seen a lot of strange problems from people running on Alpine, so we
definitely want it to be static so that musl isn't involved.

**Comment by jefferai** [comment] 2015-10-01 21:41
Fixed in master and will be fixed in new releases.

**Closed by jefferai** 2015-10-01 21:41 UTC
