### ISSUE TITLE
Error making API request - * permission denied

### ISSUE THREAD

**Issue by eravindar12** [hashicorp/vault#17246] opened 2022-09-21 00:53 UTC
Hi All,

I'm seeing the below issue and how to fix them, please?

`err: rpc error: code = Unknown desc = error making mount request: couldn't read secret "es-username": Error making API request.

URL: GET http://vault:8200/v1/xxx/data/configuration/xxx_config/xx_config
Code: 403. Errors:

* 1 error occurred:
  * permission denied`

`{"id":"root"},"path":"sear/data/configuration/xxx_config/ex_config","remote_address":"100.66.15.2","remote_port":56268},"error":"1 error occurred:\n\t* permission [denied\n\n"}`

**Comment by alisher-matkurbanov** [comment] 2022-09-21 08:50
Please, check your vault token
Invalid or expired token might be the reason of this error

**Comment by mpalmi** [comment] 2022-09-21 11:41
Thanks for the report! As @alisher-matkurbanov suggested, it is possible that this issue relates to your Vault token. The [api-docs](https://developer.hashicorp.com/vault/api-docs#403) indicate that this is an Authentication issue.

For more information on authentication best practices, you can refer to Authentication section of the API docs:
https://developer.hashicorp.com/vault/api-docs#authentication

It may be helpful to read through the rest of that doc just to rule out expected behaviors. Please let us know if there are any issues outside of what is expected, and we'll be sure to help solve them!

**Comment by refaelb** [comment] 2022-10-25 06:42
Hi still having this problem surprisingly the token is new and still not working T just pointing out I'm on k8s 1.18

**Comment by hsimon-hashicorp** [comment] 2023-01-24 00:17
Unfortunately there isn't a lot of information to go on here. As mentioned, "permission denied" does mean there's an issue with authentication to the Vault server. I'm going to go ahead and close this issue now, but please feel free to open a new one following the issue template if needed. Thanks!

**Closed by hsimon-hashicorp** 2023-01-24 00:17 UTC
Labels: waiting-for-response, core/api
