### ISSUE TITLE
Entity Alias transfer corrupts receiving entity?

### ISSUE THREAD

**Issue by stephanh** [hashicorp/vault#5729] opened 2018-11-08 03:51 UTC
When an entity-alias is updated to alias a different entity. The receiving entity now has two copies of the alias. Here is an example:

```json
[
  {
    "canonical_id": "6f925fa9-5207-e4a8-c880-d5c5ffe2df38",
    "creation_time": "2018-11-08T03:42:19.538526Z",
    "id": "bd7f178e-990c-4750-18b7-3f4db4bb2692",
    "last_update_time": "2018-11-08T03:44:01.420729Z",
    "merged_from_canonical_ids": null,
    "metadata": null,
    "mount_accessor": "auth_token_aa28d9b6",
    "mount_path": "auth/token/",
    "mount_type": "token",
    "name": "alias1"
  },
  {
    "canonical_id": "6f925fa9-5207-e4a8-c880-d5c5ffe2df38",
    "creation_time": "2018-11-08T03:42:19.538526Z",
    "id": "bd7f178e-990c-4750-18b7-3f4db4bb2692",
    "last_update_time": "2018-11-08T03:42:19.538526Z",
    "merged_from_canonical_ids": [
      "83237a90-6fa4-b487-f567-d724ff489e06"
    ],
    "metadata": null,
    "mount_accessor": "auth_token_aa28d9b6",
    "mount_path": "auth/token/",
    "mount_type": "token",
    "name": "alias1"
  }
]
```

 I believe this is also the root cause for #5348. Prior to 0.11.4 it was impossible to delete the transferred alias.

**To Reproduce**

```
# Create an entity-alias without linking it a specific entity
(vault-dev) bash-4.4$ vault write identity/entity-alias name=alias1 mount_accessor=auth_token_aa28d9b6
Key             Value
---             -----
canonical_id    83237a90-6fa4-b487-f567-d724ff489e06
id              bd7f178e-990c-4750-18b7-3f4db4bb2692

# Create an entity
(vault-dev) bash-4.4$ vault write identity/entity name=entity1
Key        Value
---        -----
aliases    <nil>
id         6f925fa9-5207-e4a8-c880-d5c5ffe2df38

# Update alias1 to link it to entity1
(vault-dev) bash-4.4$ vault write identity/entity-alias/id/bd7f178e-990c-4750-18b7-3f4db4bb2692 canonical_id=6f925fa9-5207-e4a8-c880-d5c5ffe2df38 name=alias1 mount_accessor=auth_token_aa28d9b6
WARNING! The following warnings were returned from Vault:

  * alias is being transferred from entity
  "83237a90-6fa4-b487-f567-d724ff489e06" to
  "6f925fa9-5207-e4a8-c880-d5c5ffe2df38"

Key             Value
---             -----
canonical_id    6f925fa9-5207-e4a8-c880-d5c5ffe2df38
id              bd7f178e-990c-4750-18b7-3f4db4bb2692

# Read entity1 and see that alias1 is now mentioned twice.
(vault-dev) bash-4.4$ vault read --format=json identity/entity/id/6f925fa9-5207-e4a8-c880-d5c5ffe2df38 | jq .data.aliases
[
  {
    "canonical_id": "6f925fa9-5207-e4a8-c880-d5c5ffe2df38",
    "creation_time": "2018-11-08T03:42:19.538526Z",
    "id": "bd7f178e-990c-4750-18b7-3f4db4bb2692",
    "last_update_time": "2018-11-08T03:44:01.420729Z",
    "merged_from_canonical_ids": null,
    "metadata": null,
    "mount_accessor": "auth_token_aa28d9b6",
    "mount_path": "auth/token/",
    "mount_type": "token",
    "name": "alias1"
  },
  {
    "canonical_id": "6f925fa9-5207-e4a8-c880-d5c5ffe2df38",
    "creation_time": "2018-11-08T03:42:19.538526Z",
    "id": "bd7f178e-990c-4750-18b7-3f4db4bb2692",
    "last_update_time": "2018-11-08T03:42:19.538526Z",
    "merged_from_canonical_ids": [
      "83237a90-6fa4-b487-f567-d724ff489e06"
    ],
    "metadata": null,
    "mount_accessor": "auth_token_aa28d9b6",
    "mount_path": "auth/token/",
    "mount_type": "token",
    "name": "alias1"
  }
]
```

**Expected behavior**
The receiving entity should only have one reference to the alias.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.4
* Vault CLI Version (retrieve with `vault version`): 0.11.4
* Server Operating System/Architecture: Mac and Linux

**Potential  workaround**

This problem can be avoided by instead first deleting the entity-alias and then recreating with the canonical_id field set instead of updating it. Using this approach means that the first created entity won't be deleted though, while on transfer the first created entity is deleted. I'm not sure what the implications of that are.

**Comment by jefferai** [comment] 2018-11-08 04:48
Consolidated repro case:
```
aliasid=$(vault auth list -format=json | jq -r '.["token/"].accessor' | vault write -field=id identity/entity-alias name=alias1 mount_accessor=-)
entityid=$(vault write -field=id identity/entity name=entity1)
vault write identity/entity-alias/id/${aliasid} canonical_id=${entityid}
vault read --format=json identity/entity/id/${entityid} | jq .data.aliases
```

**Comment by jefferai** [comment] 2018-11-08 05:05
@vishalnayak this workflow is a bit confusing to me. If the alias is already tied to another entity, why do the entities get merged from attempting to update the alias? It seems like that shouldn't happen unless you specifically call `identity/entity/merge`.

I'm basically wondering if the issue is really when we're merging when we shouldn't. So in a normal merge triggered by `identity/entity/merge`, the aliases would be different to begin with so appending them is correct. But in this case instead of assigning an entity to a different entity, it's trying to merge the two together.

**Closed** 2018-11-08 18:04 UTC
