### ISSUE TITLE
UI: No namespace picker rendering

### ISSUE THREAD

**Issue by devlounge** [hashicorp/vault#6922] opened 2019-06-19 12:21 UTC
**Describe the bug**
I use the UI of both Vault Enterprise and Vault open-source from the same computer.
When logged-in on vault enterprise UI, the dropdown allowing to select the namespace doesn't appear.

I'm wondering if this is not because both UIs use the same CSS and therefore the browser serves the open-source CSS from its local cache instead of the one for the enterprise version.

**Environment:**
* Vault Server Version:
- enterprise 1.0.3
- open source: 1.1.3

Chrome: 73.0.3683.75

I'm getting:

```
<ul class="navbar-sections with-ns-picker">
  <li>
    <div class="namespace-picker no-namespaces"></div>
  </li>
  ...
</ul>
```
It works when I log-in with the same user, on another colleague machine.

**Comment by meirish** [comment] 2019-06-20 01:16
Hi @devlounge, thanks for opening an issue!

All of the code for the UI (OSS and Enterprise) is in the OSS repo, however different versions of vault will have different fingerprints for the CSS file, so there shouldn't be anything shared or cached in the browser unless they were the same version. 

With regard to the namespace picker - do you have namespaces created? The picker doesn't show up until you have at least one namespace. Also are there any errors in the network panel of the browser dev tools?

**Comment by bartdzkan** [comment] 2019-07-10 18:42
Honestly the UI it does weird things all the time. I use incognito mode whenever I have to use the UI. 

Go to Access, Namespaces in the UI and see if you can see any there or if you get a permission denied. If you can see them there then you should be able to see them. 
Also check to see if you have a policy attached that lets you LIST for path
--
/sys/namespaces
--

**Comment by grigorescu** [comment] 2021-01-20 18:50
The way permissions are calculated for the Access -> Namespaces view and the Namespaces dropdown is different. As [mentioned above](https://github.com/hashicorp/vault/issues/6922#issuecomment-510181253), you need to be able to list the namespaces in order to view them in the Access -> Namespaces view.

However, that's not sufficient to see the dropdown. To view that, you must have some permissions within a namespace, e.g.:

```
path "education/*" {
   capabilities = ["list"]
}
```

**Comment by aphorise** [comment] 2022-08-31 00:02
Closing as original issue is permissions related and not a bug or anything else different between OSS / ENT versions of Vault.

**Closed by aphorise** 2022-08-31 00:02 UTC
Labels: ui, bug
