### ISSUE TITLE
Metrics: vaul.token.create_root doesn't exist

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault#10844] opened 2021-02-05 13:58 UTC
**Describe the bug**
Counter for the number of [created root](https://github.com/hashicorp/vault/pull/8089) token doesn't exist. 

**To Reproduce**
```
curl -v \
  -H "X-Vault-Request: true" \
  -H "X-Vault-Token: $(vault print token)" \
  https://vault.test.com/v1/sys/metrics | jq . | grep vault.token.create_root
```
**Expected behavior**
Counter exist

**Environment:**
* Vault Server Version: `Version  1.6.1`
* Vault CLI Version: `Vault v1.5.4`

**Additional context**
Regenerated token following [this](https://learn.hashicorp.com/tutorials/vault/generate-root) docs. The counter still not appears.

**Comment by aphorise** [comment] 2022-09-04 16:58
I believe this is actually working as intended. These counters are only reported as and when they occur and for about 20 seconds each time - unless you are using [Prometheus with retention](https://www.vaultproject.io/docs/configuration/telemetry#prometheus) where can be adjusted the period unlike all other telemetry systems.

So for example if you have two terminals open and with one to watch the API below while on the error to create 7 tokens you'll observe:

```shell
# // on Terminal 1 watch:
while true ; do
  curl -s -k -L -H "X-Vault-Token: $VAULT_TOKEN" ${VAULT_ADDR}/v1/sys/metrics | \
  jq -c '.["Gauges", "Counters", "Samples"]|.[]|select(.Name == "vault.token.create_root")|.' ;
  sleep 1 ;
done ;

# // on Terminal 2 using root token in VAULT_TOKEN do:
for iX in {1..7} ; do vault token create ; done ;
# // PRODUCES:
```

```json
{"Name":"vault.token.create_root","Count":7,"Rate":0.7,"Sum":7,"Min":1,"Max":1,"Mean":1,"Stddev":0,"Labels":{}}
```

@iusergii do you agree that there's no issue here and this can be closed?

**Comment by aphorise** [comment] 2022-09-09 22:27
Closing as there's been no follow-up. Please re-open if still relevant.

**Closed by aphorise** 2022-09-09 22:27 UTC
Labels: bug, core/metric
