### ISSUE TITLE
vault.read(kv/my-secret) Error making API request.

### ISSUE THREAD

**Issue by shashankimanage** [hashicorp/vault#6615] opened 2019-04-19 11:31 UTC
**Describe the bug**
unable to read vault secret from kv path.

**To Reproduce**
Written secret to vault kv by - vault kv put kv/my-secret var=pwd
Using consul template tpl i am reading - 
{{ with secret "kv/my-secret" }}
 {{ .Data.var }}{{ end }}
but getting the below error 
 [WARN] (view) vault.read(kv/my-secret): vault.read(kv/my-secret): Error making API request.

URL: GET http://vault:8200/v1/sys/internal/ui/mounts/kv/my-secret
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "kv/my-secret/" (retry attempt 8 after "32s")
2019/04/19 11:22:32.320391 [WARN] (view) vault.read(kv/my-secret): vault.read(kv/my-secret): Error making API request.
why do we need policies for kv path?? 

**Expected behavior**
tpl should read data from vault and push it to json.

**Environment:**
* Vault Server Version (retrieve with `vault status`):1.0.3
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture: docker

# Paste your Vault config here.
backend "consul" {
  address = "consul:8500"
  advertise_addr = "http://127.0.0.1:8200"
  path = "vault"
  scheme = "http"
}
ui = true

listener "tcp" {
  address = "vault:8200"
  tls_disable = 1
}
disable_mlock = true

**Comment by briankassouf** [comment] 2019-04-19 15:23
Hi there,

What policies does Consul Template's token have?

**Comment by shashankimanage** [comment] 2019-04-19 17:32
Root and default I haven't created any policies. 
we don't need any policy for KV it was working before, now it's not working

**Comment by michelvocks** [comment] 2019-04-23 10:38
Hi @shashankimanage,

I just saw that this is a duplicate of https://groups.google.com/forum/#!topic/vault-tool/lKoOke10EVw

I will close this issue for now since I don't think this is a bug. Feel free to reopen the issue if you have any further questions.

Cheers,
Michel

**Closed by michelvocks** 2019-04-23 10:38 UTC
