### ISSUE TITLE
If the path in the created secret has /, the path cannot be deleted.

### ISSUE THREAD

**Issue by lijie-advantech** [hashicorp/vault#8138] opened 2020-01-13 08:52 UTC
**Describe the bug**
If the path in the created secret has /, the path cannot be deleted.

**To Reproduce**
1. Call api / secret / data /: path to create a secret, the path is aa / bb
2. Delete this secret
3. The path aa cannot be deleted

**Expected behavior**
There is no secret under the aa path. I hope to provide a API to delete the aa path.

**Comment by catsby** [comment] 2020-01-13 16:46
Hello - thanks for reporting this. I believe this is effectively a duplicate of https://github.com/hashicorp/vault/issues/1690, so I'm going to close this for now. Please follow #1690 for any updates, or let me know here if you feel that the issues are different. Thanks!

**Closed by catsby** 2020-01-13 16:46 UTC
