### ISSUE TITLE
The signed SSH certificates is not working

### ISSUE THREAD

**Issue by RATIKAdurgade** [hashicorp/vault#3392] opened 2017-09-28 02:33 UTC
**Environment:**
* Vault Version: v0.8.3 
* Operating System/Architecture:CentOS Linux release 7.2.1511 (Core)

**Vault Config File:**
listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 1
}
storage "file" {
  path = "/mnt/vault/data"
}
**Startup Log Output:**
2017/09/27 16:03:40.666663 [INFO ] core: security barrier not initialized
2017/09/27 16:03:40.673424 [INFO ] core: security barrier initialized: shares=5 threshold=3
2017/09/27 16:03:40.677736 [INFO ] core: post-unseal setup starting
2017/09/27 16:03:40.693597 [INFO ] core: loaded wrapping token key
2017/09/27 16:03:40.693615 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2017/09/27 16:03:40.694779 [INFO ] core: successfully mounted backend: type=kv path=secret/
2017/09/27 16:03:40.694825 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/09/27 16:03:40.695034 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/09/27 16:03:40.698608 [INFO ] expiration: restoring leases
2017/09/27 16:03:40.699542 [INFO ] rollback: starting rollback manager
2017/09/27 16:03:40.700242 [INFO ] core: post-unseal setup complete
2017/09/27 16:03:40.702961 [INFO ] expiration: lease restore complete
2017/09/27 16:03:40.703225 [INFO ] core: root token generated
2017/09/27 16:03:40.703235 [INFO ] core: pre-seal teardown starting
2017/09/27 16:03:40.703248 [INFO ] rollback: stopping rollback manager
2017/09/27 16:03:40.703294 [INFO ] core: pre-seal teardown complete
2017/09/27 16:04:44.810428 [INFO ] core: vault is unsealed
2017/09/27 16:04:44.810489 [INFO ] core: post-unseal setup starting
2017/09/27 16:04:44.810592 [INFO ] core: loaded wrapping token key
2017/09/27 16:04:44.810601 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2017/09/27 16:04:44.810836 [INFO ] core: successfully mounted backend: type=kv path=secret/
2017/09/27 16:04:44.810962 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/09/27 16:04:44.810982 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/

**Expected Behavior:**
successful ssh login to host with signed certificates.
**Actual Behavior:**
Server host key: ECDSA XXXX

The authenticity of host '<host IP address>' can't be established.

ECDSA key fingerprint is XXXX

Are you sure you want to continue connecting (yes/no)? yes

Warning: Permanently added '<host IP address>' (ECDSA) to the list of known hosts.
.
.
.
debug1: ssh_ecdsa_verify: signature correct

debug2: kex_derive_keys

debug2: set_newkeys: mode 1

debug1: SSH2_MSG_NEWKEYS sent

debug1: expecting SSH2_MSG_NEWKEYS

debug2: set_newkeys: mode 0

debug1: SSH2_MSG_NEWKEYS received

debug1: SSH2_MSG_SERVICE_REQUEST sent

debug2: service_accept: ssh-userauth

debug1: SSH2_MSG_SERVICE_ACCEPT received

debug2: key: .ssh/signed-cert.pub (0x7f6d87042130), explicit

debug2: key: /root/.ssh/id_rsa (0x7f6d870477a0), explicit

debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic

debug3: start over, passed a different list publickey,gssapi-keyex,gssapi-with-mic

debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password

debug3: authmethod_lookup gssapi-keyex

debug3: remaining preferred: gssapi-with-mic,publickey,keyboard-interactive,password

debug3: authmethod_is_enabled gssapi-keyex

debug1: Next authentication method: gssapi-keyex

debug1: No valid Key exchange context

debug2: we did not send a packet, disable method

debug3: authmethod_lookup gssapi-with-mic

debug3: remaining preferred: publickey,keyboard-interactive,password

debug3: authmethod_is_enabled gssapi-with-mic

debug1: Next authentication method: gssapi-with-mic

debug1: Unspecified GSS failure.  Minor code may provide more information

No Kerberos credentials available

debug1: Unspecified GSS failure.  Minor code may provide more information

No Kerberos credentials available

debug1: Unspecified GSS failure.  Minor code may provide more information

debug1: Unspecified GSS failure.  Minor code may provide more information

No Kerberos credentials available

debug2: we did not send a packet, disable method

debug3: authmethod_lookup publickey

debug3: remaining preferred: keyboard-interactive,password

debug3: authmethod_is_enabled publickey

debug1: Next authentication method: publickey

debug1: Offering RSA-CERT public key: .ssh/signed-cert.pub

debug3: send_pubkey_test

debug2: we sent a publickey packet, wait for reply

debug1: Server accepts key: pkalg ssh-rsa-cert-v01@openssh.com blen 1568

debug1: ssh_rsa_verify: signature correct

debug2: input_userauth_pk_ok: fp XXXX

debug3: sign_and_send_pubkey: RSA-CERT XXXX

debug1: key_parse_private2: missing begin marker

debug1: key_parse_private_pem: PEM_read_PrivateKey failed

debug1: read PEM private key done: type <unknown>

**Enter passphrase for key '.ssh/signed-cert.pub':** 

debug2: no passphrase given, try next key

debug1: Offering RSA public key: /root/.ssh/id_rsa

debug3: send_pubkey_test

debug2: we sent a publickey packet, wait for reply

debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic

debug2: we did not send a packet, disable method

debug1: No more authentication methods to try.

Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

**Steps to Reproduce:**
1. vault mount -path=ssh-client-signer ssh

2.vault write ssh-client-signer/config/ca generate_signing_key=true

  [ On Host:

      a. Copied public key generated above to /etc/ssh/trusted-user-ca-keys.pem

      b. chmod 0600 /etc/ssh/trusted-user-ca-keys.pem

      c. added following at the end of /etc/ssh/sshd_config

         TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem

      d. Service sshd restart

    ]

3. vault write ssh-client-signer/roles/my-role -<<"EOH"

{

  "allow_user_certificates": true,

  "allowed_users": "centos",

  "default_extensions": [

    {

      "permit-pty": ""

    }

  ],

  "key_type": "ca",

  "default_user": "centos",

 "ttl": "30m0s"

}

EOH

4. ssh-keygen -t rsa -C "centos@<host ip address>"

5. vault write -field=signed_key ssh-client-signer/sign/my-role     public_key=@$HOME/.ssh/id_rsa.pub > signed-cert.pub

6. chmod 0600 signed-cert.pub 

7. ssh-keygen -Lf signed-cert.pub

8. ssh -i signed-cert.pub -i ~/.ssh/id_rsa centos@<host ip address>

**Important Factoids:**
1. It is asking for "passphrase for key 'signed-cert.pub" which is generated by vault.
2. Permissions On Vault server
-rw-r----- 1 centos centos 1679 Sep 27 20:31 .ssh/id_rsa
-rw-r----- 1 centos centos 2122 Sep 27 22:27 .ssh/signed-cert.pub
3. Permissions on Host 
-rw------- 1 root root 725 Sep 27 16:09 /etc/ssh/trusted-user-ca-keys.pem

**References:**
I have referred vault documentation from 
[](https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates.html)

**Comment by vishalnayak** [comment] 2017-09-28 11:03
@RATIKAdurgade Passphrase is applicable only for private keys. This could be happening if `ssh` is treating `signed-cert.pub` as a private key. I'd try renaming `signed-cert.pub` into `id_rsa-cert.pub`. The distinction of `-cert.pub` could just be a convention.

OR

Try supplying the certificate using the `-o CertificateFile <file_name>` option.

**Comment by RATIKAdurgade** [comment] 2017-09-28 16:57
Thanks @vishalnayak for your reply.
Here is update.
1. By renaming  `signed-cert.pub` to `id_rsa-cert.pub` , I am able to ssh the client instance.But it is still asking me `Enter passphrase for key '.ssh/id_rsa-cert.pub':`
   client log:
          Sep 28 16:41:15 ipXXXX sshd[2048]:Accepted publickey for centos from <host IP address> port XX ssh2: RSA-CERT ID vault-root-XXXXXX (serial XXXXX) CA RSA XXXX
          Sep 28 16:41:15 ipXXXX sshd[2048]: pam_unix(sshd:session): session opened for user <user> by (uid=X)
2. My new role configuration is 
$vault write ssh-client-signer/roles/my-role -<<"EOH"
 {
   "allow_user_certificates": true,
   "allowed_users": "*",
   "default_extensions": [
     {
       "permit-pty": ""
     }
   ],
   "default_extensions": [
   {
      "permit-port-forwarding": ""
     }
    ],
 "default_extensions": [
     {
 "permit-port-forwarding": ""
     }
 ],
   "key_type": "ca",
   "default_user": "centos",
   "ttl": "30m0s",
   "default_extensions": [
      {
        "permit-X11-forwarding": ""
      }
    ]
 }
 EOH
But I am unable to get any prompt once I am authorized. 

Again Than You for your help. I really appreciate it.

**Comment by RATIKAdurgade** [comment] 2017-09-28 17:58
-I am able to get a prompt after removing default extensions for `permit-port-forwarding` and `permit-X11-forwarding`. 
-We still have `Enter passphrase for key '.ssh/id_rsa-cert.pub'` issue.
-I am unable to supply `-o CertificateFile <file_name>` option
 My ssh client version is `OpenSSH_6.6.1p1`
Error I am getting if I use `-o CertificateFile` is `command-line: line 0: Bad configuration`.

**Comment by johnjelinek** [comment] 2017-12-04 21:54
```
"default_extensions": [{
    "permit-pty": ""
}],
"default_extensions": [{
    "permit-port-forwarding": ""
}]
```
Is that the right format? I thought it was supposed to be:
```
"default_extensions": [{
    "permit-pty": "",
    "permit-port-forwarding": ""
}],
```
or even:
```
"default_extensions": [{
    "permit-pty": "",
}, {
    "permit-port-forwarding": ""
}]
```

**Comment by ayashjorden** [comment] 2018-01-10 21:06
Hi,
I'm getting the same error as @RATIKAdurgade ,
Any solution yet?

**Comment by mikeokner** [comment] 2018-02-01 16:05
What's your SSH config look like?

As @vishalnayak mentioned, passphrases are only applicable for private keys, and getting unexpectedly prompted for one usually means `ssh` was expecting a regular PEM private key and got something else it can't parse in its current format.

For this to work properly, your config should look something like:

```
Host server-name
    HostName 12.34.56.78
    User username
    IdentityFile ~/.ssh/id_rsa
```

And the keys in your `.ssh` directory should look something like:

```
id_rsa
id_rsa.pub
id_rsa-cert.pub
```

where the first is the private key which gets specified as the `IdentityFile` parameter in `.ssh/config`, the second is the public key that you pass to Vault to get signed, and the third is the certificate that Vault returns to you. Permissions on all should be `0600`.

I have confirmed this works and use this setup on a daily basis.

[This docs page](https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates.html) may need to be updated if the instructions on it regarding cert file naming and `IdentityFile` cli args don't work.

**Comment by mikeokner** [comment] 2018-02-01 16:09
@RATIKAdurgade @johnjelinek An example of a working config:

```json
{
  "allow_bare_domains": false,
  "allow_host_certificates": false,
  "allow_subdomains": false,
  "allow_user_certificates": true,
  "allow_user_key_ids": false,
  "allowed_critical_options": "",
  "allowed_domains": "",
  "allowed_extensions": "",
  "allowed_users": "centos",
  "default_critical_options": {},
  "default_extensions": {
    "permit-X11-forwarding": "",
    "permit-agent-forwarding": "",
    "permit-port-forwarding": "",
    "permit-pty": "",
    "permit-user-rc": ""
  },
  "default_user": "centos",
  "key_id_format": "",
  "key_type": "ca",
  "max_ttl": "1h0m0s",
  "ttl": "1h0m0s"
}
```

**Comment by johnjelinek** [comment] 2018-02-01 22:26
Your `default_extensions` isn't an array?

**Comment by mikeokner** [comment] 2018-02-01 23:07
No, that might be another error in the docs. You can see in the [API doc](https://www.vaultproject.io/api/secret/ssh/index.html#default_extensions) it's defined as a map and [in the source](https://github.com/hashicorp/vault/blob/8142b42d951119a73ce46daa3331921b5e21cdee/builtin/logical/ssh/path_roles.go#L41) it's being parsed as a `map[string]string`

**Comment by bljordan** [comment] 2018-02-22 22:51
I found that the ordering of your references to the signed cert and private key matter.  Try referencing the private key and then the signed cert.  Alternatively, you may be able to run an ssh-agent and add your private key to that first.

**Comment by ayashjorden** [comment] 2018-02-23 05:42
For me, the issue was that on Mac, I had to add the private key to ssh-agent, the I got passed the passphrase issue

**Comment by 1NoOne1** [comment] 2018-04-10 04:55
@mikeokner Is that a limit to put the keys only with id_rsa, id_rsa.pub and id_rsa-cert.pub. This is only by default. But I can mention the -i to specify on the command line or to use CentificateFile. Either of them are not working as of now. I won't say this is an issue with Vault but in general ssh. However, could try changing from id_rsa to something else and check whether it works not, please?

**Comment by ggabor82** [comment] 2019-11-05 15:07
I ran to the same issue on Debian 8 using latest Vault (v1.2.3)
Finally I've tried it on Debian 9 and CentOS 7, works out of the box on both using:
```ssh -i signed-cert.pub -i ~/.ssh/id_rsa root@host```

**Comment by michelvocks** [comment] 2019-12-03 14:14
Hi there!

I'm going to close this issue since the original issue owner has been absent for a while.
Please feel free to open a new issue if you experience the same issue mentioned above.

Cheers,
Michel

**Closed by michelvocks** 2019-12-03 14:14 UTC
Labels: bug, secret/ssh, version/0.8.x

**Comment by quickbooks2018** [comment] 2019-12-04 01:52
> I ran to the same issue on Debian 8 using latest Vault (v1.2.3)
> Finally I've tried it on Debian 9 and CentOS 7, works out of the box on both using:
> `ssh -i signed-cert.pub -i ~/.ssh/id_rsa root@host`



 # Fix
Step 1: Adding the private key (PEM file) to the key chain. This allows the user to access the private instances without copying to the bastion host. This adds an additional layer of security.
#you need to run ssh-agent before using it:

eval `ssh-agent -s`

ssh-add -k <PEM_file_name>

ssh-add -L


# ERROR
ssh -i signed-cert.pub -i centos centos@10.20.0.35
Load key "signed-cert.pub": invalid format
centos@10.20.0.35: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive).

# WORKINGS
ssh -i signed-cert.pub -i centos centos@10.20.0.35 -v
OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to 10.20.0.35 [10.20.0.35] port 22.
debug1: Connection established.
debug1: identity file signed-cert.pub type 4
debug1: identity file signed-cert.pub-cert type -1
debug1: identity file centos type -1
debug1: identity file centos-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to 10.20.0.35:22 as 'centos'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:AUVyb/YVpRaTrzqg9VainNr+odYOYQZrydIs0cO7pCA
debug1: Host '10.20.0.35' is known and matches the ECDSA host key.
debug1: Found key in /c/Users/Asim/.ssh/known_hosts:4
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: signed-cert.pub RSA-CERT SHA256:vxx924aHSNb55vCqNrDIPofLZPzsrNpKZBOOLAkpvH0 explicit
debug1: Will attempt key: centos  explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering public key: signed-cert.pub RSA-CERT SHA256:vxx924aHSNb55vCqNrDIPofLZPzsrNpKZBOOLAkpvH0 explicit
debug1: Server accepts key: signed-cert.pub RSA-CERT SHA256:vxx924aHSNb55vCqNrDIPofLZPzsrNpKZBOOLAkpvH0 explicit
debug1: sign_and_send_pubkey: no separate private key for certificate "signed-cert.pub"
Load key "signed-cert.pub": invalid format
debug1: Trying private key: centos
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive
debug1: No more authentication methods to try.
centos@10.20.0.35: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive).

**Comment by johnjelinek** [comment] 2019-12-04 01:54
I found this to be a problem in Windows 10 using Powershell, but it works fine in Powershell Core.

**Comment by con-f-use** [comment] 2020-07-27 20:07
I find it incredibly unclear, how to configure extensions with ssh. 

![image](https://user-images.githubusercontent.com/11145016/88586943-79a6e600-d055-11ea-8219-78ea15a64bd2.png)

What am I supposed to enter here?
