### ISSUE TITLE
Vault UI does not respect the default TTL value and unit when signing SSH keys

### ISSUE THREAD

**Issue by selurvedu** [hashicorp/vault#7962] opened 2019-12-03 13:57 UTC
**Describe the bug**
Vault UI does not respect the default TTL value and unit (seconds, minutes, hours, days) when signing SSH keys.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an SSH role.
2. Set the default TTL and Max TTL to "1 minute" (not "60 seconds", this is important).
3. Open the "Sign SSH key" page in Vault UI. Click "More options".
4. See "TTL: 30 seconds". Don't change the number or the unit.
5. Sign a key. Save it as `keyfile` and run `ssh-keygen -L -f path/to/keyfile` in terminal.
6. See that the key is actually valid for 1 minute, plus 30 seconds before signature generation time (explained in #1036), despite that "30 seconds" was shown on the UI.
7. Open the "Sign SSH key" page again. This time change "30" to "60" but leave "seconds" intact.
8. See "Error: ttl is larger than maximum allowed 60".
9. Change "seconds" to any other option, then change it back to "seconds", or change "60" to "1" and select "minutes".
10. See that the key is signed with a TTL that was specified on the UI.

**Expected behavior**
UI should display the actual default TTL value defined in role configuration.

Changing the value in input field without changing the unit in combo box should use the unit that is specified in the combo box.

There should be a note explaining why the signed key is valid from 30 seconds before the signature was applied on the following pages:
https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates.html
https://www.vaultproject.io/api/secret/ssh/index.html

**Environment:**
* Vault Server Version: 1.3.0
* Vault CLI Version: N/A
* Server Operating System/Architecture: GNU/Linux x86_64

Vault server configuration file(s):
`vault read ssh-client/roles/root -format=json`
```hcl
{
  "request_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "allow_bare_domains": false,
    "allow_host_certificates": false,
    "allow_subdomains": false,
    "allow_user_certificates": true,
    "allow_user_key_ids": false,
    "allowed_critical_options": "",
    "allowed_domains": "",
    "allowed_extensions": "",
    "allowed_user_key_lengths": {},
    "allowed_users": "root",
    "default_critical_options": {},
    "default_extensions": {
      "permit-agent-forwarding": "",
      "permit-port-forwarding": "",
      "permit-pty": ""
    },
    "default_user": "root",
    "key_bits": 0,
    "key_id_format": "{{token_display_name}}",
    "key_type": "ca",
    "max_ttl": 60,
    "ttl": 60
  },
  "warnings": null
}
```

**Comment by crinjes** [comment] 2020-08-05 09:51
I believe this is a display issue just like #9043. The wrap tool shows "seconds" but is actually "minutes" until you change the value from "seconds" to something else and then back.

We can't trust the UI on that one and always make sure to play with units to get the correct one. It's probably showing the wrong unit in more places than signing and wrap.

**Comment by selurvedu** [comment] 2020-08-07 18:10
That's correct.

**Comment by hellobontempo** [comment] 2023-04-12 18:44
Thank you @selurvedu and @crinjes for reporting and the discussion. 

In 1.13 we made some updates to the component that handles `ttl` values in this PR https://github.com/hashicorp/vault/pull/18114. I was unable to reproduce the bug mentioned here, but wanted to check in before closing out the issue.

**Comment by hashishaw** [comment] 2023-04-28 18:35
Closing this out, please reopen or create a new issue if you see this happen again!

**Closed by hashishaw** 2023-04-28 18:35 UTC
Labels: ui, bug, waiting-for-response
