### ISSUE TITLE
cassandra/config/connection not working

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/vault#2292] opened 2017-01-23 09:48 UTC
Via API:
```
[root@thebox ~]# curl -X POST -H "X-Vault-Token:43535-1b4d-dccc-a46f-70a744889f9e" http://127.0.0.1:8200/v1/cassandra/config/connection?hosts=localhost&username=cassandra&password=cassandra

[root@thebox ~]# {"errors":["Hosts cannot be empty"]}
```
Via CLI:
```
[root@thebox ~]#  vault write cassandra/config/connection     hosts=localhost     username=cassandra     password=cassandra
Error writing data to cassandra/config/connection: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/cassandra/config/connection
Code: 400. Errors:

* Error creating session: gocql: unable to create session: control: unable to connect to initial hosts: Invalid or unsupported protocol version (2); the lowest supported version is 3 and the greatest is 4
[root@thebox ~]#  vault write cassandra/config/connection     hosts=localhost     username=cassandra     password=cassandra protocol_version=4
Error writing data to cassandra/config/connection: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/cassandra/config/connection
Code: 400. Errors:

* Error validating connection info: You have to be logged in and not anonymous to perform this request

```

This does not seem as an expected behaviour...

**Comment by ror6ax** [comment] 2017-01-23 12:57
I'm running acceptance tests locally and they show the same:
```
[root@euca-10-254-244-199 vault]# make testacc TEST=./builtin/logical/cassandra
go generate
VAULT_ACC=1 go test -tags='vault' ./builtin/logical/cassandra -v  -timeout 45m
=== RUN   TestBackend_basic
2017/01/23 14:52:17.862109 [TRACE] physical/cache: creating LRU cache: size=32768
2017/01/23 14:52:17.862206 [INFO ] core: security barrier not initialized
2017/01/23 14:52:17.862395 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/01/23 14:52:17.862486 [TRACE] core: cluster name not found/set, generating new
2017/01/23 14:52:17.862500 [DEBUG] core: cluster name set: name=vault-cluster-1d9941a7
2017/01/23 14:52:17.862508 [TRACE] core: cluster ID not found, generating new
2017/01/23 14:52:17.862515 [DEBUG] core: cluster ID set: id=dc82b895-91ec-bf8d-5d7c-c6e0739010b4
2017/01/23 14:52:17.862548 [INFO ] core: post-unseal setup starting
2017/01/23 14:52:17.876211 [INFO ] core: loaded wrapping token key
2017/01/23 14:52:17.878504 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/23 14:52:17.878534 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/23 14:52:17.878615 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/23 14:52:17.879169 [INFO ] core: post-unseal setup complete
2017/01/23 14:52:17.879280 [INFO ] core: root token generated
2017/01/23 14:52:17.879290 [INFO ] core: pre-seal teardown starting
2017/01/23 14:52:17.879311 [INFO ] rollback: starting rollback manager
2017/01/23 14:52:17.879329 [INFO ] rollback: stopping rollback manager
2017/01/23 14:52:17.879357 [INFO ] core: pre-seal teardown complete
2017/01/23 14:52:17.879399 [INFO ] core: vault is unsealed
2017/01/23 14:52:17.879417 [INFO ] core: post-unseal setup starting
2017/01/23 14:52:17.879443 [INFO ] core: loaded wrapping token key
2017/01/23 14:52:17.879538 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/23 14:52:17.879556 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/23 14:52:17.879613 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/23 14:52:17.880123 [INFO ] core: post-unseal setup complete
2017/01/23 14:52:17.880326 [INFO ] rollback: starting rollback manager
2017/01/23 14:52:17.882292 [INFO ] core: successful mount: path=mnt/ type=test
14:52:17.882448 WRN ~ Executing test step step_number: 1 in:
14:52:18.029024 WRN ~ Requesting RollbackOperation in:
--- FAIL: TestBackend_basic (0.17s)
        testing.go:282: Failed step 1: Erroneous response:

                &logical.Response{Secret:<nil>, Auth:<nil>, Data:map[string]interface {}{"error":"Error validating connection info: You have to be logged in and not anonymous to perform this request"}, Redirect:"", warnings:[]string(nil), WrapInfo:(*logical.ResponseWrapInfo)(nil)}
=== RUN   TestBackend_roleCrud
2017/01/23 14:52:18.029356 [TRACE] physical/cache: creating LRU cache: size=32768
2017/01/23 14:52:18.029385 [INFO ] core: security barrier not initialized
2017/01/23 14:52:18.029492 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/01/23 14:52:18.029534 [TRACE] core: cluster name not found/set, generating new
2017/01/23 14:52:18.029545 [DEBUG] core: cluster name set: name=vault-cluster-a614b88d
2017/01/23 14:52:18.029553 [TRACE] core: cluster ID not found, generating new
2017/01/23 14:52:18.029560 [DEBUG] core: cluster ID set: id=3b954309-76c7-0ebb-d00c-31cd370fcd2a
2017/01/23 14:52:18.029578 [INFO ] core: post-unseal setup starting
2017/01/23 14:52:18.045441 [INFO ] core: loaded wrapping token key
2017/01/23 14:52:18.045779 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/23 14:52:18.045803 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/23 14:52:18.045892 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/23 14:52:18.047716 [INFO ] rollback: starting rollback manager
2017/01/23 14:52:18.047942 [INFO ] core: post-unseal setup complete
2017/01/23 14:52:18.047988 [INFO ] core: root token generated
2017/01/23 14:52:18.047995 [INFO ] core: pre-seal teardown starting
2017/01/23 14:52:18.048004 [INFO ] rollback: stopping rollback manager
2017/01/23 14:52:18.048013 [INFO ] core: pre-seal teardown complete
2017/01/23 14:52:18.048055 [INFO ] core: vault is unsealed
2017/01/23 14:52:18.048073 [INFO ] core: post-unseal setup starting
2017/01/23 14:52:18.048099 [INFO ] core: loaded wrapping token key
2017/01/23 14:52:18.048215 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/23 14:52:18.048236 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/23 14:52:18.048315 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/23 14:52:18.048783 [INFO ] core: post-unseal setup complete
2017/01/23 14:52:18.048924 [INFO ] rollback: starting rollback manager
2017/01/23 14:52:18.050440 [INFO ] core: successful mount: path=mnt/ type=test
14:52:18.050576 WRN ~ Executing test step step_number: 1 in:
14:52:18.090288 WRN ~ Requesting RollbackOperation in:
--- FAIL: TestBackend_roleCrud (0.06s)
        testing.go:282: Failed step 1: Erroneous response:

                &logical.Response{Secret:<nil>, Auth:<nil>, Data:map[string]interface {}{"error":"Error validating connection info: You have to be logged in and not anonymous to perform this request"}, Redirect:"", warnings:[]string(nil), WrapInfo:(*logical.ResponseWrapInfo)(nil)}
FAIL
exit status 1
FAIL    _/root/vault_test/vault/builtin/logical/cassandra       0.244s
make: *** [testacc] Error 1
```
Please advice.

**Comment by vishalnayak** [comment] 2017-01-23 14:26
@ror6ax For `Invalid or unsupported protocol version (2);`, the cassandra backend's configuration has a field by name `protocol_version` which defaults to 2. Changing it to 3 or 4 should solve this problem.

As for `You have to be logged in and not anonymous to perform this request`, it looks like it is coming from Cassandra itself. I would verify if the credentials are proper and that the queries are working independently from `cqlsh`.

**Comment by ror6ax** [comment] 2017-01-23 14:32
As I've shown in second snippet, `protocol_version = 4` gives  You have to be logged in and not anonymous error.

I can `cqlsh -u cassandra -p cassndra` just fine.

**Comment by vishalnayak** [comment] 2017-01-23 14:36
@ror6ax Can you do a `LIST USERS;` in the prompt after `cqlsh -u cassandra -p cassandra`?

**Comment by ror6ax** [comment] 2017-01-23 14:47
Eeeh, it's `Unauthorized: Error from server: code=2100 [Unauthorized] message="You have to be logged in and not anonymous to perform this request"` Wat? o_0

**Comment by vishalnayak** [comment] 2017-01-23 14:49
@ror6ax I guess it is something to do with how Cassandra's credentials are supposed to be configured. I am not familiar with Cassandra as much to tell you what that problem could be. Since it is not related to Vault, I am closing this issue.

**Comment by jefferai** [comment] 2017-01-23 14:53
@ror6ax Looks like it may be https://issues.apache.org/jira/browse/CASSANDRA-10800...are you using the allow all authenticator?

**Comment by ror6ax** [comment] 2017-01-23 14:59
Yes, correct.
```
authenticator: AllowAllAuthenticator
authorizer: AllowAllAuthorizer
```

**Comment by jefferai** [comment] 2017-01-23 15:40
@ror6ax From that link it seems like the issue is that some actions still require authentication but the AllowAll* don't do what you expect. They literally allow all people to get past the auth step but not necessarily to take action. I'm not sure what the right answer here is, but maybe it's to switch authenticator so that you're using a "real" user?

**Comment by ror6ax** [comment] 2017-01-23 15:44
Thanks, it seems so. You can close the issue, it's not Vault-related anyway.

**Comment by jefferai** [comment] 2017-01-23 15:45
@ror6ax It may not be, however, we *do* need to fix the tests. I'm hoping that if you find a way to make this work we can update the tests the same way.

**Closed** 2017-01-23 15:44 UTC

**Comment by jefferai** [comment] 2017-01-25 20:39
@ror6ax We've switched our tests to using `dockertest` and we bind mount in a Cassandra yml that doesn't use the AllowAll authn/authz, and our tests are passing.
