### ISSUE TITLE
UI: Issue with API calls for show secrets

### ISSUE THREAD

**Issue by homeles** [hashicorp/vault#4382] opened 2018-04-17 19:37 UTC
**Environment:**

* Vault Version: Vault 0.10.0
* Operating System/Architecture: Official Docker Image -> vault:0.10.0

**Expected Behavior:** Be able to get/show secrets from UI if permissions is granted correctly

**Actual Behavior:** No Authorized message

![2018-04-17_14-27-57](https://user-images.githubusercontent.com/6785228/38892155-16dbaedc-424c-11e8-8677-46720e36c310.png)

I believe is because as part of the url (secret path), a ```data``` prefix is being added and is making the API call to fail.

The correct API call, should be:
```https://url:8200/v1/secret/docker-in-datacenter/dindc-monitor```
instead of this:
```https://url:8200/v1/secret/data/docker-in-datacenter/dindc-monitor```

**Comment by jefferai** [comment] 2018-04-17 20:43
Duplicate of #4335

**Closed by jefferai** 2018-04-17 20:43 UTC
