### ISSUE TITLE
Allow the use of the completed SubjectDN, not just CN when signing a certificate via a CSR

### ISSUE THREAD

**Issue by darkedges** [hashicorp/vault#12912] opened 2021-10-22 20:22 UTC
**Is your feature request related to a problem? Please describe.**
When signing a Certificate using a CSR generated as follows
```
openssl req -new -newkey rsa:2048 -nodes -out star_example_com.txt -keyout star_example_com.key -subj "/C=AU/ST=Victoria/L=Melbourne/O=DarkEdges/OU=IT/CN=*.example.com"
```
[star_example_com.txt](https://github.com/hashicorp/vault/files/7401186/star_example_com.txt)
the certficate generated will only contain `CN=*.example.com`.
[test.txt](https://github.com/hashicorp/vault/files/7401187/test.txt)
```
$ openssl x509 -in test.txt -text -noout
```
[test.out.txt](https://github.com/hashicorp/vault/files/7401192/test.out.txt)

HC Vault is only using `CN` from that field, unless you use `Sign Verbatim`, which is not recommended to use, as it does not use the details defined in the role.

**Describe the solution you'd like**
Respect the `Subject` presented in the CSR.

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
The use case is that we are signing Certifcates for use within a Messaging Service that uses the `SubjectDN` to identify which identity is signing the message.

**Additional context**
Raised an issue when `CN` is greater than 65 characters in lenght - https://github.com/hashicorp/vault/issues/11721

**Comment by mkhpalm** [comment] 2021-11-30 19:40
I agree there needs to be safe middle ground between sign-verbatim and using the subject from a CSR.

This would be useful for service and client certs that use distinguished names (rfc1779) to authenticate. Examples there are elasticsearch/opensearch clusters use DN to authenticate nodes, clients, admins, etc. 

Right now the only way to do es/os with vault is by making roles for every cluster or go full sign-verbatim. To get at the subject to change the distinguished names. Otherwise you have to live with the idea that all elevated users can authenticate to any cluster that was signed by the same vault pki role that has a matching CN.

**Comment by cipherboy** [comment] 2022-05-12 20:55
As a note, this is a duplicate of #4562 and #9774. As we have multiple issues with the same topic (give or take CSR vs role-generated -- which will likely both be solved together), I'm closing this in favor of that one. See some context on why this is a little non-trivial: https://github.com/hashicorp/vault/issues/4562#issuecomment-1125413160

**Closed by cipherboy** 2022-05-12 20:55 UTC
Labels: enhancement, secret/pki, cryptosec
