### ISSUE TITLE
MongoDB Atlas Database Connection ignores Generated TTL for Role

### ISSUE THREAD

**Issue by awoodobvio** [hashicorp/vault#14071] opened 2022-02-15 12:29 UTC
**Describe the bug**
When using the MongoDB Atlas connection type for a database secret, the role appears to ignore the **Generated credentials Time-to-Live (TTL)** when generating dynamic users/leases.  Instead, the system seems to use a default value for the TTL.  Setting the "default lease TTL" at the secret level seems to have corrected the issue at the expense of flexibility.

**To Reproduce**
1. Create a database secret engine
2. Add a connection to MongoDB Atlas
3. Create a new role with a TTL set
4. Generate a credential
5. Note that the TTL/expiration does not correspond to the default TTL set in the role.

**Expected behavior**
The generated user/lease will expire based on the generated ttl setting on the role.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.2
* Vault CLI Version (retrieve with `vault version`): n/a
* Server Operating System/Architecture: K8s (via helm chart) on Linux

**Comment by lavkhanna** [comment] 2022-04-26 06:17
I am facing the similar issue on Postgres Backend.

**Comment by alexkonkin** [comment] 2022-07-23 19:14
I've got the same bug.
Workarounds, thans for the hint from the previous post...
For the ones who would like to fix this on the secret level, please use the documentation below:
https://www.vaultproject.io/docs/commands/secrets/tune
or in case of terraform:
https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/mount

**Comment by Zlaticanin** [comment] 2023-11-03 18:34
Hello @awoodobvio 👋 . Thank you for submitting this! 
I tested this with both MongoDB Atlas and Postgres and I am unable to reproduce the behavior you are seeing. 
I am setting TTL on role creation and I am seeing the expected behavior where the lease expires based on that ttl that was set.

I am closing this issue for that reason. Please re-open if this issue still persists for you with newer vault version.

**Closed by Zlaticanin** 2023-11-03 18:34 UTC
Labels: ecosystem, secret/database/mongodb
