### ISSUE TITLE
oidc role type not working on version 1.10.0

### ISSUE THREAD

**Issue by awolde** [hashicorp/vault#14727] opened 2022-03-27 18:27 UTC
**Describe the bug**
I am able to successfully login with my gmail account using OIDC in vault 1.9.0 but I'm getting `role with oidc role_type is not allowed` when I try to login with v1.10.0.

**To Reproduce**
1. Use this terraform config
```
resource "vault_jwt_auth_backend" "gcp_oidc" {
  description        = "Login with your Gmail Account"
  path               = "google-oidc"
  type               = "oidc"
  oidc_discovery_url = "https://accounts.google.com"
  oidc_client_id     = var.client_id
  oidc_client_secret = var.client_secret
  default_role       = "gmail"
  tune {
    listing_visibility = "unauth"
    default_lease_ttl  = "8h"
    max_lease_ttl      = "8h"
    token_type         = "default-service"
  }
}

resource "vault_jwt_auth_backend_role" "gmail" {
  backend        = vault_jwt_auth_backend.gcp_oidc.path
  role_name      = "gmail"
  token_policies = ["my-policy"]

  bound_audiences = [var.client_id]
  user_claim      = "sub"
  bound_claims = {
    sub = var.gmail_ids #array of gmail ids
  }
  role_type = "oidc"
  allowed_redirect_uris = ["https://localhost:8250/oidc/callback", "https://localhost:8200/ui/vault/auth/goidc/oidc/callback"]
  verbose_oidc_logging  = true
}
```
3. Run `terraform apply` on a vault 1.9.0 cluster, then try on 1.10.0 version.

**Expected behavior**
It should log you in your gmail id.

**Environment:**
* Vault Server Version:
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.9.0
Storage Type    file
Cluster Name    vault-cluster-7b2055fd
Cluster ID      80d1e4de-d1a3-35da-0e49-88a3fb6590ae
HA Enabled      false
```

* Vault CLI Version (retrieve with `Vault v1.9.0`):
* Server Operating System/Architecture:
Running in docker container `"Ubuntu 20.04.3 LTS"`

Vault server configuration file(s):

```hcl
storage "file" {
  path    = "/vault-db"
}

ui = true
listener "tcp" {
  address     = "127.0.0.1:8200"
   tls_disable = 1
}
log_level = "debug"
disable_mlock = true
```

**Comment by austingebauer** [comment] 2022-03-28 02:28
Hi, @awolde. I'm closing this as a duplicate of https://github.com/hashicorp/vault/issues/14671. There is a workaround detailed in the issue and 1.10 [known issues](https://www.vaultproject.io/docs/upgrading/upgrade-to-1.10.x#sign-in-to-ui-using-oidc-auth-method-results-in-an-error) section. Thank you!

**Closed by austingebauer** 2022-03-28 02:28 UTC
Labels: ui, auth/oidc
