### ISSUE TITLE
ELB + DynamoDB issues

### ISSUE THREAD

**Issue by Daerados** [hashicorp/vault#1262] opened 2016-03-27 20:25 UTC
Greetings, I'm sorry if there's similar issues there, but I haven't got my issues solved, hope you can help me.

Basically our wished setup is AWS provided Elastic Load Balancer with two public subnets (ELB has 4 IP's in a such way). As a backend it was decided to use AWS provided DynamoDB. Everything has a single endpoint (TLS enabled DNS which serves as alias of ELB).

Issues:
1) Vault's (we have two) most of the time can't detect that there is another Vault and going stand by - both of them. Unless I delete DynamoDB table and start single one, initialize and then second one. I also tried to put both Vaults in one public subnet, not much of a difference I think.
2) LDAP configuration fails with an error EOF (End of File), there was a similar issue, but I don't think it was resolved. DynamoDB issue? Of course with a Consul it was ok.

Will be appreciated if you could help me. :)
Thank you.

**Comment by jefferai** [comment] 2016-03-28 14:03
Hi @Daerados ,

It's hard to address your issues without more information -- can you provide your Vault configuration for both nodes and their logs?

If it's not something that seems to be an issue in Vault itself, I may have to refer you to the person that coded the DynamoDB backend, as I really don't know much about it. But let's see what I can see first...

Thanks!

**Comment by Daerados** [comment] 2016-03-29 06:15
Greetings, thank you for your response. Vaults has the same configuration:

```
listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}

backend "dynamodb" {
 table = "Vault"
 access_key = "key"
 secret_key = "key2"
 region = "eu-west-1"
 advertise_addr="https://vault.domain.com"
}

listener "tcp" {
 tls_cert_file = "/etc/vault/certs/server.pem"
 tls_key_file = "/etc/vault/certs/server.key"
 address = "0.0.0.0:9000"
}
```

```
2016/03/29 06:12:07 http: TLS handshake error from x.x.x.x:56409: tls: client offered an unsupported, maximum protocol version of 301
2016/03/29 06:12:09 http: TLS handshake error from x.x.x.x:8066: tls: client offered an unsupported, maximum protocol version of 301
2016/03/29 06:12:10 [DEBUG] rollback: attempting rollback on sys/
2016/03/29 06:12:10 [DEBUG] rollback: attempting rollback on secret/
2016/03/29 06:12:10 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/03/29 06:12:25 http: panic serving 127.0.0.1:45088: runtime error: invalid memory address or nil pointer dereference
goroutine 75819 [running]:
net/http.(*conn).serve.func1(0xc82022ea80)
        /goroot/src/net/http/server.go:1389 +0xc1
panic(0x1189fe0, 0xc820012060)
        /goroot/src/runtime/panic.go:426 +0x4e9
github.com/hashicorp/vault/vendor/github.com/go-ldap/ldap.(*Conn).Close(0x0)
        /gopath/src/github.com/hashicorp/vault/vendor/github.com/go-ldap/ldap/conn.go:132 +0x6d
github.com/hashicorp/vault/builtin/credential/ldap.(*backend).pathConfigWrite(0xc820020908, 0xc82022eb80, 0xc8204129b0, 0x6010106, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/builtin/credential/ldap/path_config.go:186 +0x9d2
github.com/hashicorp/vault/builtin/credential/ldap.(*backend).(github.com/hashicorp/vault/builtin/credential/ldap.pathConfigWrite)-fm(0xc82022eb80, 0xc8204129b0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/builtin/credential/ldap/path_config.go:78 +0x42
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc82050d340, 0xc82022eb80, 0xc82022eb80, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:189 +0x833
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc82000dce0, 0xc82022eb80, 0x0, 0x0, 0x3000000, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:265 +0xb9f
github.com/hashicorp/vault/vault.(*Router).Route(0xc82000dce0, 0xc82022eb80, 0xc82022eb80, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3c
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc8201681c0, 0xc82022eb80, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/core.go:534 +0x9c8
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc8201681c0, 0xc82022eb80, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/core.go:455 +0x7dc
github.com/hashicorp/vault/http.request(0xc8201681c0, 0x7f24ef653860, 0xc82047d2b0, 0xc82032c9a0, 0xc82022eb80, 0x30, 0xc8202f8210)
        /gopath/src/github.com/hashicorp/vault/http/handler.go:84 +0x2f
github.com/hashicorp/vault/http.handleLogical.func1(0x7f24ef653860, 0xc82047d2b0, 0xc82032c9a0)
        /gopath/src/github.com/hashicorp/vault/http/logical.go:77 +0x608
net/http.HandlerFunc.ServeHTTP(0xc8203cce20, 0x7f24ef653860, 0xc82047d2b0, 0xc82032c9a0)
        /goroot/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8203a06f0, 0x7f24ef653860, 0xc82047d2b0, 0xc82032c9a0)
        /goroot/src/net/http/server.go:1910 +0x17d
github.com/hashicorp/vault/http.handleHelpHandler.func1(0x7f24ef653860, 0xc82047d2b0, 0xc82032c9a0)
        /gopath/src/github.com/hashicorp/vault/http/help.go:18 +0x11d
net/http.HandlerFunc.ServeHTTP(0xc8203cce60, 0x7f24ef653860, 0xc82047d2b0, 0xc82032c9a0)
        /goroot/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc82019a500, 0x7f24ef653860, 0xc82047d2b0, 0xc82032c9a0)
        /goroot/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82022ea80)
        /goroot/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /goroot/src/net/http/server.go:2137 +0x44e
```

**Comment by jefferai** [comment] 2016-03-29 14:07
@Daerados I found the cause of the panic, although not the underlying reason -- something in `go-ldap` is returning a nil connection when not returning an error. I also don't see why using Consul vs DynamoDB would cause any difference here. If you compile from master that panic should be gone.

The standby/active issues are much more likely to be DynamoDB-related, but you didn't provide much log so I can't really see anything.

**Comment by Daerados** [comment] 2016-03-29 20:14
I will try to compile and will report about results.
Well there's nothing to provide about it, it just goes standby mode as soon as I unseal vaults. When both Vaults in same subnets, everything is ok.

**Comment by jefferai** [comment] 2016-03-30 14:17
@Daerados Vault instances *only* communicate via the shared physical backend -- in your case DynamoDB. So being in the same subnet or a different subnet should have no bearing on Vault behavior, except if it's affecting how DynamoDB behaves.

If changing the subnet didn't make a difference, I would suggest that maybe something is stale in DDB and you need to use recovery mode (https://www.vaultproject.io/docs/config/index.html#recovery_mode). But if moving them to the same subnet causes one to go active, then this shouldn't be the issue.

**Comment by Daerados** [comment] 2016-03-30 15:02
Greetings, I compiled dev build, here what I get now writing LDAP configuration:

```
Error writing data to auth/ldap/config: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/ldap/config
Code: 400. Errors:

* invalid connection returned from LDAP dial
```

I'm pretty sure that with the same configuration and Consul backend it worked. I even authenticated there.

**Comment by jefferai** [comment] 2016-03-30 15:35
I don't know your ldap config string so I couldn't say what might be going wrong with it. That is the expected error, though -- the panic was some condition where `go-ldap` was returning a nil connection but not an associated error. In this case, all we know downstream is that go-ldap returned no connection, and we can't print out any more since no error was given to us.

**Comment by jefferai** [comment] 2016-03-30 23:52
@Daerados Any chance you can compile a fresh pull from master and see if you get a different (and hopefully) more descriptive error? I was digging into the nil connection issue and found something that would be obscuring an error coming back from the library, so you might get a better idea now of what the issue is when you're writing the config.

**Comment by Daerados** [comment] 2016-03-31 14:15
Thank you @jefferai, error shown that ceritificate(s) was the problem, leaded me to alter a bit our setup. However mistyping LDAP's ip still results EOF error :) Will be now testing different availability zones setups for Vault, kinda strange that AWS ELB not making proper requests in such setup.

Btw, could please tell is it possible make expiration for LDAP logins? By default I see json return states that it's expiration and lease duration is 0.

**Comment by jefferai** [comment] 2016-03-31 14:28
Hi @Daerados ,

My guess is that you are giving out the "root" policy on your LDAP logins, as root tokens never expire. You should also never give them out to anyone, ever, as they have unlimited access to all of Vault.

We don't have an audit driver for Kibana, but if someone wanted to write one that would be pretty interesting...

**Comment by Daerados** [comment] 2016-03-31 14:56
My idea was to use Dockers driver (gelf if im not mistaken), like it sends all "docker logs" output to Kibana. But my docker container has only Vault's direct output, since I launch it as core container process.

**Comment by jefferai** [comment] 2016-03-31 15:32
My only suggestion would be to bind-mount in a directory where you configure Vault to write an audit file, then ship that to Kibana.

**Comment by Daerados** [comment] 2016-04-01 11:26
Yes, that was initial though, but it will grow over time etc.

What can you say about this? I configured everything to work as expected, it worked at the start, now it throws something like this when I try to login through LDAP:

```
2016/04/01 11:23:59 http: panic serving x.x.x.x:20844: runtime error: invalid memory address or nil pointer dereference
goroutine 414 [running]:
net/http.(*conn).serve.func1(0xc820616a80)
        /goroot/src/net/http/server.go:1389 +0xc1
panic(0x11f31a0, 0xc820010070)
        /goroot/src/runtime/panic.go:426 +0x4e9
github.com/hashicorp/vault/vendor/github.com/go-ldap/ldap.(*Conn).Bind(0x0, 0xc8201bd8c0, 0x14, 0xc8201bd900, 0x11, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vendor/github.com/go-ldap/ldap/bind.go:94 +0x3c
github.com/hashicorp/vault/builtin/credential/ldap.(*backend).Login(0xc82001e538, 0xc8207edb00, 0xc8206c6be8, 0xa, 0xc8205a51a0, 0xe, 0x0, 0x0, 0x0, 0xc8206acec8, ...)
        /gopath/src/github.com/hashicorp/vault/builtin/credential/ldap/backend.go:103 +0x557
github.com/hashicorp/vault/builtin/credential/ldap.(*backend).pathLogin(0xc82001e538, 0xc8207edb00, 0xc8205a5450, 0xf78700, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/builtin/credential/ldap/path_login.go:40 +0x1a8
github.com/hashicorp/vault/builtin/credential/ldap.(*backend).(github.com/hashicorp/vault/builtin/credential/ldap.pathLogin)-fm(0xc8207edb00, 0xc8205a5450, 0xc8207d8360, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/builtin/credential/ldap/path_login.go:27 +0x42
github.com/hashicorp/vault/helper/mfa.(*backend).wrapLoginHandler.func1(0xc8207edb00, 0xc8205a5450, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/helper/mfa/mfa.go:67 +0x4b
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc82061fc30, 0xc8207edb00, 0xc8207edb00, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:189 +0x833
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc8201e6420, 0xc8207edb00, 0x0, 0x0, 0x2000000, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:265 +0xb9f
github.com/hashicorp/vault/vault.(*Router).Route(0xc8201e6420, 0xc8207edb00, 0xc8207edb00, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3c
github.com/hashicorp/vault/vault.(*Core).handleLoginRequest(0xc8202aec40, 0xc8207edb00, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/core.go:626 +0x39b
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc8202aec40, 0xc8207edb00, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/core.go:459 +0x4d0
github.com/hashicorp/vault/http.request(0xc8202aec40, 0x7f73729458d0, 0xc8206e1930, 0xc8208655e0, 0xc8207edb00, 0x30, 0xc8206c6c90)
        /gopath/src/github.com/hashicorp/vault/http/handler.go:75 +0x2f
github.com/hashicorp/vault/http.handleLogical.func1(0x7f73729458d0, 0xc8206e1930, 0xc8208655e0)
        /gopath/src/github.com/hashicorp/vault/http/logical.go:77 +0x608
net/http.HandlerFunc.ServeHTTP(0xc8201cf680, 0x7f73729458d0, 0xc8206e1930, 0xc8208655e0)
        /goroot/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8201c5da0, 0x7f73729458d0, 0xc8206e1930, 0xc8208655e0)
        /goroot/src/net/http/server.go:1910 +0x17d
github.com/hashicorp/vault/http.handleHelpHandler.func1(0x7f73729458d0, 0xc8206e1930, 0xc8208655e0)
        /gopath/src/github.com/hashicorp/vault/http/help.go:18 +0x11d
net/http.HandlerFunc.ServeHTTP(0xc8201cf6e0, 0x7f73729458d0, 0xc8206e1930, 0xc8208655e0)
        /goroot/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc82059fd80, 0x7f73729458d0, 0xc8206e1930, 0xc8208655e0)
        /goroot/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820616a80)
        /goroot/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /goroot/src/net/http/server.go:2137 +0x44e
```

**Comment by Daerados** [comment] 2016-04-01 14:02
Indeed, splitting Vault to different subnets requires additional NAT/routes, that's the cause. Thank you very much for your help, I guess I should further investigate how to implement it on our end.

**Comment by jefferai** [comment] 2016-04-01 14:26
@Daerados That nil pointer is coming from a condition where we could get an error from the underlying go-ldap library but it was accidentally being masked, leading the bind code to think there was no error when performing the LDAP dial and so not realizing it got a nil pointer back. This was fixed in master a few days ago, so if you build from master you should get a descriptive error message instead.

**Comment by Daerados** [comment] 2016-04-01 15:19
I had compiled both commits, however, returned to released binary after that. But I realized what's the error cause was, it's ok. Again, thank you for your help :)

**Comment by Daerados** [comment] 2016-04-04 10:21
@jefferai I may be mistaken, but connecting to a new instance, it doesn't connect until you enter target instance at least with normal ssh so it can add entry to the trusted instances file. Maybe vault request should also check such thing?

**Comment by jefferai** [comment] 2016-04-04 14:34
@Daerados I honestly don't know what you mean there...can you explain? What's connecting to a new instance, a new instance of what, what's a trusted instances file...?

**Comment by Daerados** [comment] 2016-04-05 07:26
For example, when EC2 instance is created, on first ssh connection, user asked for something like this:

```
The authenticity of host 'xx.x.x.x.x.x' can't be established.
ECDSA key fingerprint is SHA256:ramtamtam123456.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by jefferai** [comment] 2016-04-05 12:31
OK. Everything working/good now?

**Comment by Daerados** [comment] 2016-04-07 10:11
I think so, working with policies now. One thing remained is HA, which is problem from our side :) Thank you for all your help!

**Comment by Daerados** [comment] 2016-04-07 14:48
Also enabling syslogs in container, gives:

vault audit-enable syslog
```
Error enabling audit backend: Error making API request.

URL: PUT ........../v1/sys/audit/syslog
Code: 400. Errors:

* Unix syslog delivery error
```

**Comment by jefferai** [comment] 2016-04-07 15:01
I'm not entirely sure what the cause is, but I can tell you that the syslog code supports connecting to a Unix socket at `/dev/log` or `/var/run/syslog`. If your syslog is running somewhere else, let me know where and I can see about parametizing it.

**Comment by Daerados** [comment] 2016-04-08 06:10
On host and in docker container I'm using CentOS 7, here's what I found

"Red Hat family distributions (including CentOS and Fedora) use /var/log/messages and /var/log/secure where Debian-family distributions use /var/log/syslog and /var/log/auth.log."

**Comment by jefferai** [comment] 2016-04-08 19:33
> "Red Hat family distributions (including CentOS and Fedora) use /var/log/messages and /var/log/secure where Debian-family distributions use /var/log/syslog and /var/log/auth.log."

That's where they log messages _to_, but that's not where the socket of the logging daemon itself lives. That's what Vault is having trouble connecting to.

**Comment by Daerados** [comment] 2016-04-12 11:37
Any workaround for logs?


Also my previous issue actually persists:

```
vault ssh -address https://vault.com -role myrole centos@x.x.x.x
Failed to establish SSH connection:exit status 6
```

Workaround is that I need to trigger:

```
ssh centos@x.x.x.x
The authenticity of host '10.0.1.104 (10.0.1.104)' can't be established.
ECDSA key fingerprint is SHA256:2FU6oIyq2SL993Tlvnk8vL9yDZ3QoHsrjbqv9yBt7Is.
Are you sure you want to continue connecting (yes/no)?
```

And only after that it works with a vault command.

**Comment by jefferai** [comment] 2016-04-12 13:57
@Daerados I have no further information for you about logs as I'm still waiting on information from your side.

@vishalnayak Any chance we can automate, or at least prompt the user for, accepting keys?

**Comment by Daerados** [comment] 2016-04-12 15:59
About logs, I have no idea at the moment where to look. Will investigate later. About the keys, better prompt, it's kinda useful sometimes :) Thank you for your help.

**Comment by vishalnayak** [comment] 2016-04-12 16:40
@Daerados @jefferai I guess I can disable StrictHostKeyChecking while invoking the `ssh` command. I will notify here once I get it done.

**Comment by jefferai** [comment] 2016-04-12 16:50
@vishalnayak I'm not sure doing that unilaterally is the right way to go. I think a totally fine approach is (if possible) to give a better error if that is the reason for a connection failure.

If auto-adding the host key can be done with an opt-in flag that's good too, but I still think a better error message would be useful.

**Comment by vishalnayak** [comment] 2016-04-12 17:25
@jefferai I agree with you and that is the reason I did not fix it right away.
Tracking this in #1322.

**Comment by jefferai** [comment] 2016-07-22 16:19
Closing due to lack of response.

**Closed by jefferai** 2016-07-22 16:19 UTC
