### ISSUE TITLE
Allow clients to set wrapping on a per-request basis

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/vault#4294] opened 2018-04-06 02:46 UTC
**Feature Request:**

**Environment:**
All of them.

* Vault Version: master, all previous (it looks like)
* Operating System/Architecture: All of them

**Vault Config File:**
N/A

**Startup Log Output:**
N/A

**Expected Behavior:**
The Vault API [specifies](https://www.vaultproject.io/docs/concepts/response-wrapping.html#response-wrapping-token-creation) that the wrapping information for a token is set on a per-request basis, and is set using a header. So I would expect the `api` package to allow me to set the wrapping TTL on a per-request basis.

**Actual Behavior:**
The `api` package, only allows us to set that information at [the Client level](https://godoc.org/github.com/hashicorp/vault/api#Client.SetWrappingLookupFunc)

**Steps to Reproduce:**
N/A

**Important Factoids:**
Ideally, we'd have some sort of field on the [`CreateTokenRequest`](https://godoc.org/github.com/hashicorp/vault/api#TokenCreateRequest) struct to set this, or there'd be a way that we could set it when making the API call, not on client creation, and without modifying the client's state or global mutable state.

**References:**
N/A

**Comment by paddycarver** [comment] 2018-04-09 16:35
Sorry for the lack of clarity on this. I'll fully admit that I may have misunderstood something, and if that's the case, I'd super appreciate a correction. From what I understand, though, the issue is as follows:

* Wrapping is a per-request operation. I can e.g., wrap token A, not wrap token B, and wrap token C.
* Right now, the client exposes this as [`SetWrappingLookupFunc`](https://godoc.org/github.com/hashicorp/vault/api#Client.SetWrappingLookupFunc), which lets us set at the client level the endpoints that should be wrapped. It also provides us with a `VAULT_WRAP_TTL` environment variable we can set, that operates at a global level.

The issue is the mismatch of trying to configure a per-request operation using tools that only give us global or per-endpoint granularity. So if I want to wrap token A, not wrap token B, and wrap token C, and I want to create token A, token B, and token C in parallel from the same client, there's no real good way to do that. And if I want to create them serially, I need to either set the environment variable and reset it to its previous value before/after each request, or I need to modify the SetWrappingLookupFunc before and after each request, dealing with the problems that come with editing shared mutable state, because token creation uses the same endpoint for all tokens, from what I can tell.

Ideally, I'd just be able to set a flag in [`TokenCreateRequest`](https://godoc.org/github.com/hashicorp/vault/api#TokenCreateRequest) or in some other struct that gets passed to the function, which is what the API design (specifying it as a header) had me anticipating.

Pointing out any strategies I'm missing, oversights, misunderstandings, or other pointers would be super appreciated, if I'm making this harder than it needs to be. :)

**Comment by jefferai** [comment] 2018-04-09 16:36
@paddycarver I think the problem is just understanding the use-case. For a given path, why would you want tokens A and C wrapped but not B, within the same client?

**Comment by paddycarver** [comment] 2018-04-09 16:48
In my case, it's because I want to be able to offer users the ability to have wrapped and unwrapped token generation in the Terraform provider. That would enable things like provisioning tokens for apps that can do unwrapping, where possible, but for legacy apps/apps that can't, still being able to provision unwrapped tokens. It's entirely possible I'm misunderstanding what a path is, though; for token creation, would it not always be `/auth/token/create`?

**Comment by jefferai** [comment] 2018-04-09 17:07
Generally no, you almost never want to use the bare auth/token/create endpoint. Hit me up on Slack and let's talk about what you're trying to do.

**Comment by paultyng** [comment] 2018-04-09 17:37
The issue here I think is that these tokens are uses in various other downstream integrations with various different wrap needs, so each request has its own potential wrap needs even within the same path.

**Comment by jefferai** [comment] 2018-04-09 18:16
You can just use the WrapTTL value on a given Request object to set it per request, but again, I think we should discuss because auth/token/create is almost never what should be used.

**Comment by richard-mauri** [comment] 2018-11-01 15:53
It would be great to keep the dialog on this open.
Here's my use case:

I have a go tool for initializing vault that uses the initial root token to create another root token with short expiry. I want that token to be response wrapped and ultimately returned to the operator driving the initialization.

I am using this client api:
func (c *TokenAuth) Create(opts *TokenCreateRequest) (*Secret, error)

I want to know how best to have this request return a wrapped token.
The client api func (c *Client) SetWrappingLookupFunc(lookupFunc WrappingLookupFunc) is like the OP mentioned scoped to the client  and requires knowing which operation and path to set to have token create wrap.

The docs and comments in this issue don't make it clear how best to do this.
The comment from @jefferai to "use the WrapTTL value on a given Request object" sounds like a champ, but can we have a code example of how to do this?

**Comment by jefferai** [comment] 2018-11-01 16:30
@richard-mauri It involves creating a custom https://godoc.org/github.com/hashicorp/vault/api#Request and then tripping it through https://godoc.org/github.com/hashicorp/vault/api#Client.RawRequest yourself.

However, there's now an easier way! Use https://godoc.org/github.com/hashicorp/vault/api#Client.Clone and then set the wrapping lookup func on the new client as desired. I just updated the comments on that method (it's not yet on godoc) but only Config object values are copied over currently so things like wrapping function are not (currently) copied over -- we may look into changing this for 1.0.

So you could have one client that creates wrapping tokens, one that doesn't, and just use the appropriate client per request.

I'm actually going to close this as I think the original request is solved by those two methods.

**Closed by jefferai** 2018-11-01 16:30 UTC

**Comment by richard-mauri** [comment] 2018-11-01 18:01
Thanks @jefferai 

For my token creation use case, what would be the wrapping lookup function op and path? You mentioned earlier

> you almost never want to use the bare auth/token/create endpoint.

I will try that before building a RawRequest

**Comment by jefferai** [comment] 2018-11-01 18:45
In your case I think it's fine. In most cases where people are using auth/token/create they're better served by taking advantage of token store roles (https://www.vaultproject.io/api/auth/token/index.html#create-update-token-role)

**Comment by richard-mauri** [comment] 2018-11-01 20:53
No luck wrapping a root token using wrapping lookup function.
Here's a test case: https://github.com/richard-mauri/tokenwrap
I can open a support case if it helps

**Comment by jefferai** [comment] 2018-11-05 21:31
Works for me. Whatever is the issue is in your code:
```
$ vault token create -policy=root -wrap-ttl=5m
Key                              Value
---                              -----
wrapping_token:                  s.44UvwO25tvX4pCH5Jjs2nGTk
wrapping_accessor:               KAwXD4SHd8PVSELIFKNmjTD8
wrapping_token_ttl:              5m
wrapping_token_creation_time:    2018-11-05 16:30:31.9848009 -0500 EST
wrapping_token_creation_path:    auth/token/create
wrapped_accessor:                7IrPNapzjSkLAT1W8dYYhzwz

$ VAULT_TOKEN=s.44UvwO25tvX4pCH5Jjs2nGTk vault unwrap
Key                  Value
---                  -----
token                s.U1mNVKqoRJIHEAxgYD88kIS3
token_accessor       7IrPNapzjSkLAT1W8dYYhzwz
token_duration       ∞
token_renewable      false
token_policies       ["root"]
identity_policies    []
policies             ["root"]
```

**Comment by richard-mauri** [comment] 2018-11-09 23:10
I'm adding a related note as working the client api to be like cli is not trivial.
I am still exploring but thought I'd mention: https://github.com/hashicorp/vault/issues/4688

**Comment by jefferai** [comment] 2018-11-10 00:28
You may want to look at the code that the commands I pasted above triggers.
