### ISSUE TITLE
what policies needed for managing auth backends and secrets engines

### ISSUE THREAD

**Issue by riuvshin** [hashicorp/vault#5256] opened 2018-09-04 14:15 UTC
Hello!
I want to create a special role which will be able to manage some pieces of vault
So my question is how policy for managing auth backends should look like

According to https://www.vaultproject.io/api/system/auth.html 
I've tried this:
```
      #manage auth-backends
      path "/sys/auth/*" {
        policy = "sudo"
        capabilities = ["create", "update", "delete", "read", "list"]
      }
```
but seems this is not enough because it fails with `permission denied`

same question for `secret engines` like KV storage with custom path

Thanks in advance!

**Comment by riuvshin** [comment] 2018-09-04 17:51
I also tried this:
```
path "sys/auth/*" {
  policy = "sudo"
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "auth/*" {
  policy = "sudo"
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "sys/mounts/*" {
  policy = "sudo"
  capabilities = ["create", "read", "update", "delete", "list"]
}
```

still no luck, it works only with this:
```
      path "/sys/*" {
        capabilities = ["create", "read", "update", "delete", "list"]
      }
```
but I want to have more precise policies

**Comment by jefferai** [comment] 2018-09-04 18:16
Duplicate of https://groups.google.com/d/msg/vault-tool/ecolIhkjhpE/petI5rTQBQAJ

**Closed by jefferai** 2018-09-04 18:16 UTC
