### ISSUE TITLE
approle bound_cidr_list constraint rejects a valid IP

### ISSUE THREAD

**Issue by rajpolaris** [hashicorp/vault#2332] opened 2017-02-04 12:14 UTC
I am on vault  0.6.4
I have enabled app role authentication method.

C:\opt\vault>vault write auth/approle/role/testrole1 token_ttl=10m token_max_ttl=100m bind_secret_id=false bound_cidr_list=10.197.192.0/18
Success! Data written to: auth/approle/role/testrole1

C:\opt\vault>vault read auth/approle/role/testrole1/role-id
Key     Value
---     -----
role_id xxxxxxx-ba1d-a762-488b-c2b3dfbf7529

C:\opt\vault>vault read auth/approle/role/testrole1
Key                     Value
---                     -----
bind_secret_id          false
bound_cidr_list         10.197.192.0/18
period                  0
policies                [default]
secret_id_num_uses      0
secret_id_ttl           0
token_max_ttl           6000
token_ttl               600

I am on azure virtual machine with an IP address 10.197.192.6

I am trying to fetch a token using PowerShell rest call.

$body = @{
  role_id = "xxxxxxx-ba1d-a762-488b-c2b3dfbf7529"
}
$json = $body | ConvertTo-Json

$resp = Invoke-RestMethod -Method POST -Body $json -Uri "https://vault.xxxxxx.com:8200/v1/auth/approle/login"

Invoke-RestMethod : {"errors":["failed to validate SecretID: source address unauthorized through CIDR restrictions on the role"]}

ipconfig on the VM where I can try to fetch the token show  this information.

Windows IP Configuration

Ethernet adapter Ethernet 2:

   Connection-specific DNS Suffix  . : d3aio5gjp2lejhzqo025zwnkrb.ex.internal.cl
oudapp.net
   Link-local IPv6 Address . . . . . : fe80::456a:1c8f:def5:97bc%13
   IPv4 Address. . . . . . . . . . . : 10.197.192.6
   Subnet Mask . . . . . . . . . . . : 255.255.192.0
xxxxx
Tunnel adapter isatap.d3aio5gjp2lejhzqo025zwnkrb.ex.internal.cloudapp.net:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : d3aio5gjp2lejhzqo025zwnkrb.ex.internal.cl
oudapp.net

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . :
   IPv6 Address. . . . . . . . . . . : 2001:0:d59:2ec8:347c:1693:f53a:3ff9
   Link-local IPv6 Address . . . . . : fe80::347c:1693:f53a:3ff9%15
   Default Gateway . . . . . . . . . : ::

f I change bound_cidr_list to 10.0.0.0/8 I no longer get this error.

Vault and consul are installed in a shared virtual network in azure

The application servers that going to retrieve the secrets in a different virtual network with non-overlapping IP addresses.
The two virtual networks are peered together.

 Not sure  why 10.197.192.0/18   does not work but  10.0.0.0/8 works

**Comment by vishalnayak** [comment] 2017-02-15 18:45
@rajpolaris It seems like the remote address representing the origin of request was not having the address you mentioned. See #2378; I've added a few tests to ensure that the values you mentioned, pass through the checks in the backend and the remote address will now be added to the error response. Any chance you can build off of that branch (or the master branch if the PR gets merged) and test it again?

**Comment by jefferai** [comment] 2017-02-22 19:01
Please reopen if you still have troubles; our testing code cannot reproduce.

**Closed by jefferai** 2017-02-22 19:01 UTC
