### ISSUE TITLE
Allow vault to reload its config without sealing the vault

### ISSUE THREAD

**Issue by BRMatt** [hashicorp/vault#415] opened 2015-07-12 17:31 UTC
Quite often CF systems are configured to restart/reload services when their configuration changes. In the case of Vault this would seal all servers, resulting in downtime, and would require operator intervention to fix. There are situations where the Vault configuration may change intentionally (e.g. the `statsd` address changes), or unintentionally (someone refactoring chef cookbooks accidentally removes trailing whitespace from the config file). 

Admittedly it could be possible to reconfigure and unseal each Vault server individually, but this requires a lot of manual work and increases the risk of downtime. In an ideal world, Vault would be able to safely reload its configuration from disk, whilst keeping the vault unsealed.

One thing to bear in mind is that this could potentially allow an attacker to reconfigure Vault in a harmful way (e.g. changing the storage backends), but on the other hand, a properly configured server should prevent unauthorised users from editing Vault's configuration. Given that the [security model](https://vaultproject.io/docs/internals/security.html) excludes memory analysis, excluding Vault's configuration from being edited doesn't seem unreasonable, especially as an attacker could always change the config and wait for an operator to restart the service.

Thoughts?

**Comment by hashbrowncipher** [comment] 2015-07-21 20:58
I'd be interested in a fix for this.

I am considering using short-lived certificates for my Vault server.  To achieve this, Vault would have to be restarted and unsealed every time the certificate rotates.

**Comment by armon** [comment] 2015-07-22 20:00
Marked as an enhancement. Doing an online change of the TLS keys will be particularly challenging.

**Comment by theonewolf** [comment] 2015-07-23 17:23
:+1:

**Comment by BSick7** [comment] 2016-02-04 22:00
:+1: We run vault on coreos nodes in high-availability mode.  It feels clunky that a restart after security updates would seal the vault.

**Comment by doublerebel** [comment] 2016-03-10 00:31
+1

**Comment by jefferai** [comment] 2016-03-10 01:28
As an FYI, this is on the radar, but only in a limited fashion. Reloading configuration will require going through the API, and the only item that is planned to be supported, at least initially, is the Vault server certificate/private key. Storage backends could eventually implement some reloading logic of their own for their parameters.

**Comment by roboll** [comment] 2016-04-15 03:45
Per [the docs](https://www.vaultproject.io/docs/config/index.html): 

> Starting with 0.5.2, limited configuration options can be changed on-the-fly by sending a SIGHUP to the server process. These are denoted below.

Assuming those docs are in fact correct?

**Comment by vishalnayak** [comment] 2016-04-15 05:49
@roboll 

Yes. the docs are correct!

The config file that is used to launch Vault can be updated to contain new `tls_cert_file` and `tls_key_file`. A SIGHUP signal to Vault process will then reload the certificate and its private key.

**Comment by theonewolf** [comment] 2016-04-15 12:35
I've also had good mileage using NGINX as a front-end in forwarding connections to Vault.  So then refreshing certs becomes an NGINX issue, and I don't have to worry about Vault becoming unreachable / having issues due to expired certificates.

I bind Vault to localhost and don't forward such connections over a physical network.

Does anyone have any concerns about running such a configuration: HTTPS --> NGINX --> HTTP (localhost) --> Vault.

**Comment by jefferai** [comment] 2016-04-15 13:17
Doing so breaks the trust chain between client and application, and allows for the possibility of traffic advising between the reverse proxy and app. This may not be of concern to you, but if you have to be compatible with certain industry standards, like PCI 3.0, this is not allowed.

**Comment by theonewolf** [comment] 2016-04-15 13:46
Great point @jefferai.  Glad Vault has this functionality now, so I can stop using NGINX in the near future.

**Comment by jefferai** [comment] 2016-08-15 13:28
I'm closing this for the moment as TLS parameter reloading is implemented. For other specific reloading requests, open up new issues and we can address each one on a case-by-case basis depending on feasibility.

**Closed by jefferai** 2016-08-15 13:28 UTC
Labels: enhancement

**Comment by Dmitry1987** [comment] 2018-07-10 19:44
I don't see [this reload operation documented anymore ](https://www.vaultproject.io/docs/config/index.html)- was it deprecated or removed?  Or it's just the docs issue and it still exists?

**Comment by wgebis** [comment] 2021-01-19 15:39
@jefferai 
Hello, looks that Vaut (1.6.1) doesn't reload the TLS certificate by sending the SIGHUP. 
I see in logs:
```
vault[5718]: 2021-01-19T15:34:46.794Z [DEBUG] core: set config: sanitized config=...
```
But the old certificate is used. Only `systemctl restart vault` will make the reloading the TLS cert file. 

Could we reopen this ticket?

**Comment by ncabatoff** [comment] 2021-01-19 16:13
Hi @wgebis,

> Could we reopen this ticket?

Please open a new issue and provide details showing how to reproduce the reload failure.  We do have a unit test that verifies the functionality (TestServer_ReloadListener) but it's not a full end-to-end test using a Vault binary, so it's possible that it's missing something.

**Comment by wgebis** [comment] 2021-01-19 16:22
OK, thanks @ncabatoff, I'll make double-check and will open the new issue.
