### ISSUE TITLE
sys/metrics only accepts X-Vault-Token, not Bearer token

### ISSUE THREAD

**Issue by Artanicus** [hashicorp/vault#19073] opened 2023-02-08 18:18 UTC
**Describe the bug**
According to documentation (https://developer.hashicorp.com/vault/docs/auth/token) token auth can be sent with either of the following headers:
- `X-Vault-Token: <token>`
- `Authorization: Bearer <token>`

The documentation for the `/v1/sys/metrics` (https://developer.hashicorp.com/vault/api-docs/system/metrics#read-telemetry-metrics) endpoint only mentions  `X-Vault-Token: <token>` but the documentation example for Prometheus calls for using a Bearer token: https://developer.hashicorp.com/vault/docs/configuration/telemetry (search for `prometheus.yml`)

Since Prometheus does not support adding a `X-Vault-Token` header and documentation implies Bearer tokens should work, I expected them to work.

**To Reproduce**
1. Enable Prometheus metrics:
```hcl
telemetry {                      
  prometheus_retention_time = "1m"
  disable_hostname = true        
}  
```
2. Create a policy named say `metrics`:
```hcl
path "sys/metrics" {
  capabilities = ["read", "list"]
}
```
3. Generate a token with: `vault token create -policy=metrics`
4. Fetch the metrics with curl in two ways:
```bash
%> curl -L --header "Authorization: Bearer insert_token_here" http://10.0.10.4:8200/v1/sys/metrics?format=prometheus
%> curl -L --header "X-Vault-Token: insert_token_here" http://10.0.10.4:8200/v1/sys/metrics?format=prometheus
```

**Expected behavior**
- Both curls produce metrics output.
- instead, `X-Vault-Token` fetch works, but `Authorization: Bearer` results in:
> {"errors":["permission denied"]}

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.12.3`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.12.3 (209b3dd99fe8ca320340d08c70cff5f620261f9b), built 2023-02-02T09:07:27Z`
* Server Operating System/Architecture: `Ubuntu 20.04.5 LTS`

Vault server configuration file(s):

```hcl
disable_mlock = false                                                                                                                
ui            = true 
api_addr      = "http://10.0.10.4:8200"
cluster_addr  = "http://10.0.10.4:8201"
listener "tcp" {                 
  address     = "0.0.0.0:8200"   
  tls_disable = "true"           
}                                
storage "consul" {               
  address = "127.0.0.1:8500"     
  path    = "vault"              
}                                
                                 
service_registration "consul" {  
  service = "Vault"              
}                                
                                 
telemetry {                      
  prometheus_retention_time = "1m"
  disable_hostname = true        
} 
```

**Comment by akshya96** [comment] 2023-02-28 23:24
Hi @Artanicus, Both the curl commands should produce metrics output. Unfortunately, I cannot reproduce the issue. Would you please confirm if the header in your curl command looks like --header "Authorization: Bearer <token>"?

**Comment by Artanicus** [comment] 2023-03-01 06:49
Weirdly enough after a good while of failures and not changing anything it suddenly started responding correctly both to the same exact curl calls and Prometheus. Would it be plausible that under some conditions it takes a while for that auth method to be available? I haven't restarted any vault instances since then so not sure if I can reproduce it, but could have a go at a standalone repro.

**Comment by Artanicus** [comment] 2023-03-04 14:16
I think I have a clue as to what's going on.
- Calls to a non-leader get `307`d to the leader. (I think this is Bad for metrics since every node should be collected separately.)
- A header of `"X-Vault-Token: $token"` survives the redirect and gets a response.
- A header of `"Authorization: Bearer $token"` does not survive the redirect.
- Both work if issued directly to the leader and only to the leader.

**Comment by VioletHynes** [comment] 2023-03-13 19:17
Hi there!

Thank you for the report! I've been looking into this and I think your theory is correct. It seems that the `"Authorization: Bearer $token"` approach doesn't survive the HA redirect.

I'm still looking into why and working on the fix, but I wanted to give you a bit of an update to corroborate your theory (and let you know we're still looking into it)!

Thanks a bunch,
Violet

**Comment by VioletHynes** [comment] 2023-03-14 19:58
Hi there!

I think I managed to get to the bottom of this!

The 307 behaviour of removing the `Authorization` header on a redirect is CURL behaviour, and is fairly common across clients.

Based on the CURL documentation, I believe you should be able to add `--location-trusted` to keep the Authorization header. In particular, from the CURL docs, without this option: `but since an HTTP redirect might move away to a different host curl limits what it sends away to other hosts than the original within the same transfer`

The documentation I'm referencing is here:
https://everything.curl.dev/http/redirects#redirecting-to-other-host-names

@Artanicus can you confirm if adding the `--location-trusted` option to your CURL command fixes this issue?

Thanks,
Violet

**Comment by Sway23** [comment] 2023-03-25 19:15
Hi @VioletHynes,
I have the same issue as @Artanicus and can confirm that with `--location-trusted` added to CURL with `Authorization` header it works.

**Comment by hghaf099** [comment] 2023-05-02 22:30
It seems that the solution to the issue was confirmed by @Sway23, and I tested it myself as well, and Violet's suggestion works perfectly. I am going to close this issue for now. Please feel free to open a new issue, or let us know to reopen this issue for further discussions. Thanks again for reporting the issue, and we look forward to hearing from you again.

**Closed by hghaf099** 2023-05-02 22:30 UTC
Labels: bug, core/metric, core/telemetry

**Comment by elbars** [comment] 2023-05-10 10:17
> Hi there!
> 
> I think I managed to get to the bottom of this!
> 
> The 307 behaviour of removing the `Authorization` header on a redirect is CURL behaviour, and is fairly common across clients.
> 
> Based on the CURL documentation, I believe you should be able to add `--location-trusted` to keep the Authorization header. In particular, from the CURL docs, without this option: `but since an HTTP redirect might move away to a different host curl limits what it sends away to other hosts than the original within the same transfer`
> 
> The documentation I'm referencing is here: https://everything.curl.dev/http/redirects#redirecting-to-other-host-names
> 
> To put it another way - Vault doesn't do anything different between the two headers, but the client making the request may be removing the `Authorization` header after receiving the redirect.
> 
> @Artanicus can you confirm if adding the `--location-trusted` option to your CURL command fixes this issue?
> 
> Thanks, Violet

Hello, but how pass this option `--location-trusted` into prometheus.yml config?

**Comment by elbars** [comment] 2023-05-10 10:59
> > Hi there!
> > I think I managed to get to the bottom of this!
> > The 307 behaviour of removing the `Authorization` header on a redirect is CURL behaviour, and is fairly common across clients.
> > Based on the CURL documentation, I believe you should be able to add `--location-trusted` to keep the Authorization header. In particular, from the CURL docs, without this option: `but since an HTTP redirect might move away to a different host curl limits what it sends away to other hosts than the original within the same transfer`
> > The documentation I'm referencing is here: https://everything.curl.dev/http/redirects#redirecting-to-other-host-names
> > To put it another way - Vault doesn't do anything different between the two headers, but the client making the request may be removing the `Authorization` header after receiving the redirect.
> > @Artanicus can you confirm if adding the `--location-trusted` option to your CURL command fixes this issue?
> > Thanks, Violet
> 
> Hello, but how pass this option `--location-trusted` into prometheus.yml config?
Having studied the topic, I answer my own question. 
In the target configuration section of **prometheus.yml** , you need to add the option:
`follow_redirects: true`
Maybe this will be useful to someone.
