### ISSUE TITLE
vault cli cannot access prometheus metrics

### ISSUE THREAD

**Issue by jaloren** [hashicorp/vault#7334] opened 2019-08-19 18:26 UTC
**Describe the bug**

According to  the CLI help, i should be able to get the vault prom metrics from prometheus

```
jlorenzini@jlorenzini-mb tests$ vault path-help sys/metrics
Request:        metrics
Matching Route: ^metrics$

Export the metrics aggregated for telemetry purpose.

## PARAMETERS

    format (string)
        Format to export metrics into. Currently accepts only "prometheus".

## DESCRIPTION

<no description>
```

However, the vault cli returns an error.

**To Reproduce**
```
jlorenzini@jlorenzini-mb tests$ vault read -format=json sys/metrics format="prometheus"
Error reading sys/metrics: invalid character '#' looking for beginning of value
```

**Expected behavior**
That prometheus metrics should be returned.

**Environment:**

vault server version
```
Vault v1.1.3 ('9bc820f700f83a7c4bcab54c5323735a581b34eb')
```
* Vault Server Version (retrieve with `vault status`):

```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.1.3
Cluster Name    vault-cluster-1
Cluster ID      e69096a2-2c61-454f-422e-4593a421c2c1
HA Enabled      true
HA Cluster      https://172.26.0.6:8201
HA Mode         active
```

* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.2.2
````
* Server Operating System/Architecture:
Ubuntu

**Comment by spangenberg** [comment] 2020-02-05 16:33
The Error is because the CLI expects JSON to be returned, but the format requested is Prometheus specific.
You could use cURL for example to get the Prometheus metrics:
`curl --header "X-Vault-Token: ..." '.../v1/sys/metrics?format=prometheus'`

I'd like to know more about your use case tho, what do you expect the command you posted should return.
`vault read -format=json sys/metrics format="prometheus"`
JSON encoded Prometheus metrics like this library [[prometheus/prom2json]](https://github.com/prometheus/prom2json) would do?

**Comment by spangenberg** [comment] 2020-02-21 18:47
We haven't heard back regarding this issue in over 16 days. To try and keep our GitHub issues current, we'll be closing this issue in approximately seven days if we do not hear back regarding this issue. Please let us know if you can still reproduce this issue, and if there is any more information you could share, otherwise we'll be closing this issue.

**Comment by spangenberg** [comment] 2020-03-02 16:03
Closing for now. Let us know if you have any more information!

**Closed by spangenberg** 2020-03-02 16:03 UTC
Labels: bug, core/cli, version/1.1.x, waiting-for-response
