### ISSUE TITLE
Docs are rendered with wrong YAML indentation on website

### ISSUE THREAD

**Issue by mbrancato** [hashicorp/vault#11572] opened 2021-05-10 15:07 UTC
**Describe the bug**
The website has not been updated to the latest version of the docs, but starting with this line in the Vault Kubernetes documentation, the fields are outdented and should be nested under `injector` in the current website docs version, and `agentDefaults` in the next release:
https://github.com/hashicorp/vault/blame/e27b43c4829223555484b2fb7f0049b3ec2881fc/website/content/docs/platform/k8s/helm/configuration.mdx#L128

Here is the beginning of the `injector` block:
![image](https://user-images.githubusercontent.com/8493275/117680286-03f0ae80-b17f-11eb-9aa1-748c8c2e0d69.png)

And here is where the `injector.extraLabels` begins:
![image](https://user-images.githubusercontent.com/8493275/117680388-1e2a8c80-b17f-11eb-862a-e42a181b85ff.png)

Note that the `injector.objectSelector` is correctly indented.

I've tested in Chrome and Safari.

**To Reproduce**
1. View docs page: https://www.vaultproject.io/docs/platform/k8s/helm/configuration#objectselector

**Expected behavior**
The indentation should match the documentation.

**Comment by SohamJ** [comment] 2021-05-12 21:00
This also seems to apply to all configs that follow `extraLabels` like  `certs`, `failurePolicy`, `annotations`, etc based on the [injector-deployment](https://github.com/hashicorp/vault-helm/blob/dcb4b102835d1c9911cfc9a47fb9bfc2084ffdbf/templates/injector-deployment.yaml) template

**Comment by jasonodonnell** [comment] 2021-05-19 13:56
Thanks, we'll fix this today!

**Comment by jasonodonnell** [comment] 2021-05-20 15:08
We found the root cause of the issues, this should be fixed now.

**Comment by kitography** [comment] 2022-04-29 21:24
This looks fixed to me (looking at the documentation now), but feel free to reopen if I've missed something.

**Closed by kitography** 2022-04-29 21:24 UTC
Labels: docs
