### ISSUE TITLE
Capability to read from PostgreSQL's replica if the master is down

### ISSUE THREAD

**Issue by mihirk** [hashicorp/vault#8604] opened 2020-03-23 12:07 UTC
**Is your feature request related to a problem? Please describe.**
It would be great if the PostgreSQL storage backend supported reading from the replica if the primary is down. For secrets read-only and geared towards high availability.

**Describe the solution you'd like**
Capability to provide a URL for the PostgreSQL replica, which Vault uses for read operations.

**Describe alternatives you've considered**
Using etcd as secrets storage.

**Explain any additional use-cases**
If Vault is being used in a scenario where it has a write and read heavy workload, then in that scenario reading for the replica would be a good performance gain.

**Additional context**
None

**Comment by vishalnayak** [comment] 2020-03-23 20:10
PostgreSQL storage backend already supports HA mode, wherein both the read and write capabilities will be failed over. With that in place, there is no apparent need for enabling read replicas within each instance of PostgreSQL. If read replicas are enabled, the existing HA model breaks wherein the losing of leadership becomes a non-deterministic operation since a node failure will not handover the responsibility to the standby instance, and instead fails over to the read replica. Since the read replica by design only services reads, it may not be a best of choices as the leader node will not be able to perform its write duties. Also, if multiple nodes failover to read replicas, the cluster will be in a very confused state. Read replica of PostgreSQL solves a specific set of use cases and unfortunately this is not one of them. Also, special casing such functionalities will affect the transparent and consistent error handling of all the storage backends. This won't be supported. Closing.

**Closed by vishalnayak** 2020-03-23 20:10 UTC
Labels: enhancement, storage/postgresql
