### ISSUE TITLE
Vault behind ELB Loop Redirects prevent from logging in

### ISSUE THREAD

**Issue by jaybe78** [hashicorp/vault#6881] opened 2019-06-14 00:54 UTC
Hi,

I have created a dedicated kubernetes cluster for consul and vault in AWS.

My cluster has 3 instances vault and all of them are currently running which means, I've unsealed vault in every single instance

Vault instances are exposed through an AWS NLB.

<img width="325" alt="Screenshot 2019-06-14 at 01 07 03" src="https://user-images.githubusercontent.com/3605098/59476062-e3aafe80-8e46-11e9-82b7-342fcc079934.png">

When logging via web ui or command line I get: 

<img width="1487" alt="Screenshot 2019-06-14 at 01 09 03" src="https://user-images.githubusercontent.com/3605098/59476092-f6253800-8e46-11e9-8274-8deca424432c.png">

**_Note:_** I've found out that if I seal 2 of vault instance and leave one unsealed, I'm able to log in.

So is vault supposed to run only one replica at the same time ?

Will it unseal automatically one the other instance if the current leader fails ?

Please check my vault statefulset's config

```
- name: VAULT_LOCAL_CONFIG
          value:
            api_addr     = "https://$(LOAD_BALANCER_ADDR)"
            cluster_addr = "https://$(POD_IP_ADDR):8201"
            log_level = "warn"
            ui = true
            backend "consul" {
              address = "127.0.0.1:8500"
              redirect_addr = "https://$(LOAD_BALANCER_ADDR):8200"
              cluster_addr = "https://$(VAULT_1_SERVICE_HOST):$(VAULT_1_SERVICE_PORT_BACKENDPORT)"
              token = "$(VAULT_CONSUL_KEY)"
              disable_registration = "false"
            }

            listener "tcp" {
              address     = "127.0.0.1:8200"
              tls_disable = "true"
            }
            listener "tcp" {
              address       = "$(POD_IP_ADDR):8200"
              tls_cert_file = "/etc/vault/tls/tls.crt"
              tls_key_file  = "/etc/vault/tls/tls.key"
              tls_disable_client_certs = true
            }
        args:
        - "server"
        ports:
        - name: vault-port
          containerPort: 8200
          protocol: TCP
        - name: cluster-port
          containerPort: 8201
          protocol: TCP
        readinessProbe:
          httpGet:
            path: "/v1/sys/health?standbyok=true"
            port: 8200
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
```

vault service

```
kind: Service
apiVersion: v1
metadata:
  name: vault-lb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: vault
  ports:
  - name: vault-port
    port: 443
    targetPort: 8200
    protocol: TCP
```

**Comment by michelvocks** [comment] 2019-11-07 12:14
Hi @jaybe78!

The problem is that your `api_addr` points to your load balancer whereas it should actually point to the current node its own instance address. This is required for the high availability mode to allow standby nodes to route incoming traffic to the current active node. Please have a look at our documentation for more information: https://www.vaultproject.io/docs/concepts/ha.html#behind-load-balancers

I also recommend having a look at our Kubernetes Vault Helm chart: https://www.vaultproject.io/docs/platform/k8s/index.html

Closing this now since this doesn't seem to be a bug but feel free to open a new issue if you run into other issues!

Cheers,
Michel

**Comment by michelvocks** [comment] 2019-11-07 13:05
Reopening this because apparently the configuration is correct due to the fact that clients should not have access to Vault instances directly if they are behind an ELB.

By default, Vault should not return redirect responses except when the `X-Vault-No-Request-Forwarding` header is set to a non-empty value. Is it possible that something else (e.g. Kubernetes ingress, ELB ...) returns these redirects or maybe you are setting the mentioned header above explicitly?

I also noticed that your Kubernetes service expects an NLB instead of an ELB. Is that correct?

```
annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

Cheers,
Michel

**Comment by jaybe78** [comment] 2019-11-07 14:09
Thanks for your time @michelvocks.
It's been a while I haven't look at that issue. So far I've made it work by leaving 2 of my vault instances sealed and only one unsealed.(as explained in my first comment)
Looking at the documentation I could not see what is wrong in my configuration.
Yes I'm using a network LB instead of classic one. Do you think that matters ?

**Comment by jefferai** [comment] 2019-11-07 18:08
It would be good if you can confirm that your clients are getting 307s. If so it suggests that something is not behaving correctly with the request forwarding mechanism -- information on that should then appear in the logs.

**Comment by jefferai** [comment] 2019-11-07 18:08
(Removing the core/replication label as HA/request forwarding is not a part of replication)

**Comment by michelvocks** [comment] 2020-01-03 09:56
Closing this due to inactivity. Feel free to open a new issue if you are still experiencing this issue.

**Closed by michelvocks** 2020-01-03 09:56 UTC
Labels: bug, version/1.3.x, waiting-for-response
