### ISSUE TITLE
Max lease period for Token

### ISSUE THREAD

**Issue by narayan8291** [hashicorp/vault#689] opened 2015-10-09 20:42 UTC
I have tuned the auth/token backend with a default time period of 1 min and a max time period of 10 mins. When I create a token, the duration is set to the default period of 1 min. I was wondering if I can choose the duration period of that token to 10 mins which is the max ttl set for auth/token

**Comment by jefferai** [comment] 2015-10-09 20:43
Duplicate of #688.

**Closed by jefferai** 2015-10-09 20:43 UTC
