### ISSUE TITLE
Failed to lock memory: cannot allocate memory

### ISSUE THREAD

**Issue by xtrasmal** [hashicorp/vault#97] opened 2015-04-29 12:28 UTC
Hello everybody,

Can somebody explain this to me:

```
[12:12 PM]-[vagrant@cockmagic]-[/var/www]
$ vault server -dev
Error initializing core: failed to lock memory: cannot allocate memory
```
htop screenshot:
![htop](https://cloud.githubusercontent.com/assets/1174877/7390829/ee0b8332-ee7b-11e4-8561-9f1d74f92f12.png)

**Comment by bbirkinbine** [comment] 2015-04-29 13:56
Check your 'max locked memory' ulimit -l settings for non-root user

http://stackoverflow.com/questions/974636/what-does-ulimit-l-mean

**Comment by xtrasmal** [comment] 2015-04-29 13:59
When I run ``` ulimit -l ``` it says 64

**Comment by sethvargo** [comment] 2015-04-29 14:23
Hi @xtrasmal @bbirkinbine @xtrasmal 

Thank you for opening an issue. This is actually a duplicate of https://github.com/hashicorp/vault/issues/59 and has already been fixed on master. You can read more in the linked issue. Please let me know if you have any questions.

**Closed by sethvargo** 2015-04-29 14:23 UTC
