### ISSUE TITLE
Vault doesn't use new revisions of Google KMS key. Stuck.

### ISSUE THREAD

**Issue by ingvarch** [hashicorp/vault#18389] opened 2022-12-14 22:43 UTC
**Describe the bug**
Vault doesn't use new revisions of Google KMS key. It stuck. Old revisions were destroyed. As a result Vault can't be unseal. 

**To Reproduce**
1. Create key-ring and key in Google KMS 
2. Create Google Bucket 
3. Run `vault server -config $PATH/to/config`
4. Create new revisions of key in Google KMS
5. Wait day/week/....
6. Remove old revision of key
7. wait day/week/... ?
8. Restart vault
9. See error

**Expected behavior**
I expect that Vault checks new revisions of key in Google KMS - maybe once per day or so, and does its magic to change revision for unseal. But it stuck!

**Environment:**
* Vault Server Version (retrieve with `vault status`):

```
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   true
Total Recovery Shares    5
Threshold                3
Unseal Progress          0/3
Unseal Nonce             n/a
Version                  1.10.3
Storage Type             gcs
HA Enabled               true
```

* Vault CLI Version (retrieve with `vault version`):

```
Vault v1.10.3 (af866591ee60485f05d6e32dd63dde93df686dfb)
```

* Server Operating System/Architecture:

```
uname -a # inside the POD
Linux vault-0 5.10.0-0.bpo.15-amd64 #1 SMP Debian 5.10.120-1~bpo10+1 (2022-06-13) x86_64 Linux
```

```
Helm Chart: vault-0.20.1
Kubernetes Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:26:59Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

Vault server configuration file(s):

```hcl
disable_mlock = true
ui = true

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"

  telemetry {
    unauthenticated_metrics_access = true
  }
}

storage "gcs" {
  bucket        = "HIDDEN"
  ha_enabled    = "true"
}

seal "gcpckms" {
  project     = "HIDDEN"
  region      = "europe-west1"
  key_ring    = "vault-helm-unseal-kr-prod"
  crypto_key  = "vault-helm-unseal-key-prod"
}

telemetry {
  prometheus_retention_time = "30s",
  disable_hostname = true
}
```

**Additional context**

**Secret Engines:**
- K/V version 2
- Transit

**Auth methods:**
- Kubernetes
- JWT
- Github

**Startup logs**
```
==> Vault server configuration:

             Api Address: http://localhost:8200
                     Cgo: disabled
         Cluster Address: https://localhost:8201
              Go Version: go1.17.9
              Listener 1: tcp (addr: "[::]:8200", cluster address: "[::]:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: gcs (HA available)
                 Version: Vault v1.10.3
             Version Sha: af866591ee60485f05d6e32dd63dde93df686dfb

==> Vault server started! Log data will stream in below:

2022-12-14T21:44:34.383Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
2022-12-14T21:44:36.158Z [INFO]  core: Initializing versionTimestamps for core
2022-12-14T21:44:36.160Z [INFO]  core: stored unseal keys supported, attempting fetch
2022-12-14T21:44:36.449Z [WARN]  failed to unseal core: error="fetching stored unseal keys failed: failed to decrypt keys from storage: failed to decrypt envelope: rpc error: code = FailedPrecondition desc = projects/HIDDEN/locations/europe-west1/keyRings/vault-helm-unseal-kr-prod/cryptoKeys/vault-helm-unseal-key-prod/cryptoKeyVersions/769 is not enabled, current state is: DESTROYED."
2022-12-14T21:44:41.451Z [INFO]  core: stored unseal keys supported, attempting fetch
2022-12-14T21:44:41.712Z [WARN]  failed to unseal core: error="fetching stored unseal keys failed: failed to decrypt keys from storage: failed to decrypt envelope: rpc error: code = FailedPrecondition desc = projects/HIDDEN/locations/europe-west1/keyRings/vault-helm-unseal-kr-prod/cryptoKeys/vault-helm-unseal-key-prod/cryptoKeyVersions/769 is not enabled, current state is: DESTROYED."
2022-12-14T21:44:46.719Z [INFO]  core: stored unseal keys supported, attempting fetch
2022-12-14T21:44:47.007Z [WARN]  failed to unseal core: error="fetching stored unseal keys failed: failed to decrypt keys from storage: failed to decrypt envelope: rpc error: code = FailedPrecondition desc = projects/HIDDEN/locations/europe-west1/keyRings/vault-helm-unseal-kr-prod/cryptoKeys/vault-helm-unseal-key-prod/cryptoKeyVersions/769 is not enabled, current state is: DESTROYED."
2022-12-14T21:44:52.011Z [INFO]  core: stored unseal keys supported, attempting fetch
2022-12-14T21:44:52.327Z [WARN]  failed to unseal core: error="fetching stored unseal keys failed: failed to decrypt keys from storage: failed to decrypt envelope: rpc error: code = FailedPrecondition desc = projects/HIDDEN/locations/europe-west1/keyRings/vault-helm-unseal-kr-prod/cryptoKeys/vault-helm-unseal-key-prod/cryptoKeyVersions/769 is not enabled, current state is: DESTROYED."
^C==> Vault shutdown triggered
```

As you can see in the screenshot - `Version 772` was created before `Version 769` was destroyed.
Also `Versions 770 and 771` were created after 769. 

I'm surprised - Why Vault didn't change the version?

![Screenshot 2022-12-14 at 21 58 30](https://user-images.githubusercontent.com/1292445/207724201-19fe3202-8eb0-4c3d-8e11-e7998d7f2c41.png)

I faced this issue 9th of December. In logs - Nothing before restart!

**Attaching the logs:** `--from="2022-12-01T00:00:00Z" --to="2022-12-08T23:59:59Z"` 

```
2022-12-08T15:26:40Z {} 2022-12-08T15:26:40.609541738Z stderr F 2022-12-08T15:26:40.609Z [INFO]  expiration: revoked lease: lease_id=auth/kubernetes/login/hd0a8062610cbd615460acc2f0dc595645d323da6407654a85f12d4ca64211cb5
2022-12-08T15:26:30Z {} 2022-12-08T15:26:30.286171626Z stderr F 2022-12-08T15:26:30.285Z [INFO]  expiration: revoked lease: lease_id=auth/kubernetes/login/hbcbf473a73eb75feca89ba873319fa306aa1e07025a60d8a0b96f8c9137b1689
2022-12-08T15:20:41Z {} 2022-12-08T15:20:41.719488934Z stderr F 2022-12-08T15:20:41.719Z [INFO]  expiration: revoked lease: lease_id=auth/kubernetes/login/hc60af89525c6055b9d4ad4fa5460b8b6fafcbc9db945a79e5bbd6dc54031df2e
2022-12-06T15:23:24Z {} 2022-12-06T15:23:24.868486745Z stderr F 2022-12-06T15:23:24.868Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/ha79187fe056d7428fdd7e92200810920904b85fa83df3fcddcddcd68a0f4bca3
2022-12-05T09:13:22Z {} 2022-12-05T09:13:22.539001671Z stderr F 2022-12-05T09:13:22.538Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h6a141e6d2e53b1b142f0d9891763f2bfc73dab759e14fa9a062e999ec06106f1
2022-12-03T10:31:01Z {} 2022-12-03T10:31:00.879006913Z stderr F 2022-12-03T10:31:00.878Z [INFO]  expiration: revoked lease: lease_id=auth/kubernetes/login/ha807994db10e8c8eab243f7f92eac13c63b25e234aaa0272c450526b37daa31e
2022-12-02T14:10:14Z {} 2022-12-02T14:10:14.165375563Z stderr F 2022-12-02T14:10:14.165Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h0b179eba2b70744b8efd317e78b3dbe72f23293d1dc117277954c710824118a1
2022-12-02T12:48:45Z {} 2022-12-02T12:48:45.724289637Z stderr F 2022-12-02T12:48:45.724Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h39f1cc5a37aea32a566b871bd63baf2aaa89e5b1a85727ba4d77958332bce4ec
2022-12-02T11:26:43Z {} 2022-12-02T11:26:43.643490705Z stderr F 2022-12-02T11:26:43.643Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/hbf67c5c8fdc7f01d2274e13245c87a59f94c6a88bf3d90dd82c77eff67b856ed
2022-12-02T09:48:13Z {} 2022-12-02T09:48:13.337339497Z stderr F 2022-12-02T09:48:13.337Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h335fc37b76dc2bc189e4ba0f22804601c613bbf17a92d7064da4c37ac2c803f2
2022-12-01T22:17:22Z {} 2022-12-01T22:17:22.104443576Z stderr F 2022-12-01T22:17:22.104Z [INFO]  expiration: revoked lease: lease_id=auth/kubernetes/login/h77600d1e53145c24c8ac958bedb8a3cb6454993d2b6d3615950bb788d8c6e990
2022-12-01T13:27:35Z {} 2022-12-01T13:27:35.437963517Z stderr F 2022-12-01T13:27:35.437Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h982c4c597816ebaf3dd1fbbcc5d52379092a8cd6dc7c15bc811442aa7fe2c270
2022-12-01T13:14:09Z {} 2022-12-01T13:14:09.104543672Z stderr F 2022-12-01T13:14:09.104Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/hbf3d7b9a46624dc2e732a0f2ceefdf26dd7a9c18682753604a2101a7ce828d58
2022-12-01T13:14:05Z {} 2022-12-01T13:14:05.170209185Z stderr F 2022-12-01T13:14:05.169Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h16bb52cfa1a19dabe471832d5a7793267bc48b35eb3f1af1a463d438fe1bea15
2022-12-01T12:59:12Z {} 2022-12-01T12:59:12.778762478Z stderr F 2022-12-01T12:59:12.778Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h25220a77b3e5348967214c3011dc999caa568c1f8e0c5cd6f71d28d62f84cc25
```

**Attaching the logs:** `--from="2022-10-20T00:00:00Z" --to="2022-10-20T23:59:59Z"` 

Day when version 769 was destroyed. 

```
2022-10-20T13:43:04Z {} 2022-10-20T13:43:04.831722866Z stderr F 2022-10-20T13:43:04.831Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h105fb7241f91a7b137329393fe71504c29693cf077235d9acac962c3f1a35a33
2022-10-20T13:15:19Z {} 2022-10-20T13:15:19.647448678Z stderr F 2022-10-20T13:15:19.647Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h9fd039c90db48c73014a7c95ecb6fe2038bd9b7e8c3eec0ffa0ea191f57f7607
2022-10-20T13:04:06Z {} 2022-10-20T13:04:06.235830826Z stderr F 2022-10-20T13:04:06.235Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h914740834f8e88093b3d69e3ef5c824769b09e9d26054895f57fe812021e4454
2022-10-20T13:04:04Z {} 2022-10-20T13:04:04.335609188Z stderr F 2022-10-20T13:04:04.335Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h67911b4b0ffdbc6bf109bd4f9c6a15d1fa109d8ed7c3f332f1386864348c9d92
2022-10-20T12:01:05Z {} 2022-10-20T12:01:05.419397422Z stderr F 2022-10-20T12:01:05.419Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/hc983bb44105f68ef974a50239dbde61468ceeb6b32002f34f0bf647358ae59ef
2022-10-20T11:46:00Z {} 2022-10-20T11:46:00.117697553Z stderr F 2022-10-20T11:46:00.117Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h7258d3c6c5826f62c3f74b60ce2ee58853b51a597e69476aeb51f65c06abe0e5
2022-10-20T11:45:59Z {} 2022-10-20T11:45:59.251911662Z stderr F 2022-10-20T11:45:59.251Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h1e536a489e5ded763c02fff044af1eee908dc55b9afa095db4adee66d92d3fc1
2022-10-20T11:45:59Z {} 2022-10-20T11:45:59.222939809Z stderr F 2022-10-20T11:45:59.222Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h57b2397a182b9a7ed055dd1c96bd5f6137b5d215d41eb5086bffa0322b5cf93c
2022-10-20T11:26:30Z {} 2022-10-20T11:26:30.507633374Z stderr F 2022-10-20T11:26:30.507Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h0af370b4f87ab0bde1ce9d584366aaddd72a451f7d60bc510dbc06a0579aac26
2022-10-20T11:21:18Z {} 2022-10-20T11:21:18.300887829Z stderr F 2022-10-20T11:21:18.300Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h2c001b295f229283b852cb30b1701c2a1d1d93042200534a541e9a763c3092cc
2022-10-20T10:48:52Z {} 2022-10-20T10:48:52.823864192Z stderr F 2022-10-20T10:48:52.823Z [INFO]  expiration: revoked lease: lease_id=auth/kubernetes/login/h62181a84b0d1d85f27d4aae1c867d809e0a8850c9861ffe9b8b37840d8443658
2022-10-20T10:48:26Z {} 2022-10-20T10:48:26.099192538Z stderr F 2022-10-20T10:48:26.099Z [INFO]  expiration: revoked lease: lease_id=auth/kubernetes/login/he93a363915c4a638a58c921caa04fc19024965dd0c756632af7cf1008a2c2606
2022-10-20T07:34:30Z {} 2022-10-20T07:34:30.532349967Z stderr F 2022-10-20T07:34:30.532Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h72b25a63bd8b7e7ee75d96c506643720c2080433d0990365edeb8b08930e3a81
2022-10-20T07:30:17Z {} 2022-10-20T07:30:16.870354222Z stderr F 2022-10-20T07:30:16.869Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/hff6c0abfb83c8721f71ca08e008cc8596fddf5664af578e8e3ac182f0751993d
2022-10-20T07:18:02Z {} 2022-10-20T07:18:02.7517465Z stderr F 2022-10-20T07:18:02.751Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h42ca850825d65a938a813a70121d7511425c8722ba6612feedb10f84e2889906
2022-10-20T06:33:47Z {} 2022-10-20T06:33:47.321199501Z stderr F 2022-10-20T06:33:47.320Z [INFO]  expiration: revoked lease: lease_id=auth/jwt/login/h9a5a72d2abfab3d474a3100a46b74d6a4a46aae43c0809a7cf01be56486d03d6
```

**Attaching the logs:** `--from="2022-10-06T00:00:00Z" --to="2022-10-06T23:59:59Z"` 

Day when version 769 was created. I did some manual restarts to make sure that previous destroyed version doesn't affect the Vault. 

[vault-log-2022-10-06.log](https://github.com/hashicorp/vault/files/10232188/vault-log-2022-10-06.log)

Unfortunately I don't have DEBUG logs in production environment. 

**Summary:** 

Google can't restore destroyed version of key. 
**My Vault sealed.** I can't work. 
This is a huge bug!

I suggest adding the ability to **force** the version number to the config.

**Comment by hsimon-hashicorp** [comment] 2022-12-14 23:36
Hello! As a general rule, if a change of any value that Vault is using occurs outside of Vault's "knowledge", you will experience unexpected behavior. It may work, it may not. If you want to rotate the unseal key, you should use the command `vault operator rekey`, and not change it inside Google's KMS. If you have the recovery keys, you can try to re-key for your unseal keys. Please see the following for more on the seal/unseal mechanisms and expected / supported behavior: https://developer.hashicorp.com/vault/docs/concepts/seal
As a final note, Vault is expected to seal itself in the case of it detecting changes outside of its control. This is part of its security mechanisms, and is by design.
Please let me know if you have any more questions. Thanks!

**Comment by ingvarch** [comment] 2022-12-15 09:02
@hsimon-hashicorp 

> This operation is zero downtime, but it requires the Vault is unsealed and a quorum of existing unseal keys are provided.

My Vault is sealed. 

Please, help me, what I can do?

**Comment by maxb** [comment] 2022-12-15 09:25
I responded to this question 4 days ago over at https://discuss.hashicorp.com/t/problems-with-auto-unseal-via-google-kms/47850 but there was no further response in that venue.

@ingvarch 's situation is very unfortunate - they appear to have suffered data loss.

An important question here, is why is this GCP KMS key set to automatically rotate versions and destroy old versions.

If that was done manually, it is an unfortunate case of user error - https://developer.hashicorp.com/vault/docs/configuration/seal/gcpckms states that:

> Old keys version must not be disabled or deleted and are used to decrypt older data.

If that was the default configuration out of the box, then we have a situation where product defaults set users up to lose their data!

I am not familiar with GCP so I'm not sure which of the above is the case.

**Comment by ingvarch** [comment] 2022-12-15 09:45
@hsimon-hashicorp 

Can I bump version of key in Vault ? 


I see in `core/recovery-key` this 


```

0
 E�X��
�*iG��pi
        '�Z�hǽda9T��=z�"��o|W

                            %R�^�z�a*�projects/HIDDEN/locations/europe-west1/keyRings/vault-helm-unseal-kr-prod/cryptoKeys/vault-helm-unseal-key-prod/cryptoKeyVersions/769*s
&�u"�
�;(S]N�WI���ݬ���88���3����a���ɺ'���݉k
                                    ��t�M9-��d�bȳ4�?�Кjy� j,���5�0L%
```

**Comment by hsimon-hashicorp** [comment] 2022-12-15 18:50
If you have access to your recovery keys, you can use this guide to rekey Vault. However, if you do not have access to your recovery keys, unfortunately Max is correct and your data is lost.
https://support.hashicorp.com/hc/en-us/articles/4404364271763-How-to-rekey-vault-recovery-keys-when-using-auto-unseal

**Comment by maxb** [comment] 2022-12-15 22:00
I have #15490 asking for recovery keys to be changed so they do address this use-case.

**Comment by maxb** [comment] 2022-12-15 22:06
> [redacted for your safety]

I don't think this value is actually a risk... but if it was, be aware that GitHub still allows users to view old versions of comments, by clicking on "edited" in the comment title, so the redaction would be ineffective.

**Comment by hsimon-hashicorp** [comment] 2022-12-15 22:07
> > [redacted for your safety]
> 
> I don't think this value is actually a risk... but if it was, be aware that GitHub still allows users to view old versions of comments, by clicking on "edited" in the comment title, so the redaction would be ineffective.

Thank you as always! I am grateful to have you as a partner in our community. :)

**Comment by maxb** [comment] 2022-12-16 16:52
> An important question here, is why is this GCP KMS key set to automatically rotate versions and destroy old versions.

I have learnt some more about Google Cloud KMS since I wrote the above.

It appears, as far as I can tell from the docs, that destroying old key versions is never automatic, occurring only via explicit human action, or explicit API calls.

That means that this data loss incident was an unfortunate case of an operator performing what they believed was safe cleanup, but was in fact critically destructive.

Although https://developer.hashicorp.com/vault/docs/configuration/seal/gcpckms does technically say this:

> Old keys version must not be disabled or deleted and are used to decrypt older data.

this warning could be made a lot stronger.

In addition, since GCP Cloud KMS key versions are a billable resource, and Vault provides no way to ever safely reduce key versions, explicit advice on how to manage this seal method efficiently over time, would be a plus.

As for what I said earlier about recovery keys:

> I have https://github.com/hashicorp/vault/issues/15490 open, asking for recovery keys to be changed so they do address this use-case.

I have realised that even if recovery keys were changed to permit unsealing Vault itself, this would still leave data protected by sealwrap unrecoverable. Only a concern for Enterprise users, but a complication, none the less.

**Comment by hsimon-hashicorp** [comment] 2022-12-16 19:42
> > An important question here, is why is this GCP KMS key set to automatically rotate versions and destroy old versions.
> 
> I have learnt some more about Google Cloud KMS since I wrote the above.
> 
> It appears, as far as I can tell from the docs, that destroying old key versions is never automatic, occurring only via explicit human action, or explicit API calls.
> 
> That means that this data loss incident was an unfortunate case of an operator performing what they believed was safe cleanup, but was in fact critically destructive.
> 
> Although https://developer.hashicorp.com/vault/docs/configuration/seal/gcpckms does technically say this:
> 
> > Old keys version must not be disabled or deleted and are used to decrypt older data.
> 
> this warning could be made a lot stronger.
> 
> In addition, since GCP Cloud KMS key versions are a billable resource, and Vault provides no way to ever safely reduce key versions, explicit advice on how to manage this seal method efficiently over time, would be a plus.
> 
> As for what I said earlier about recovery keys:
> 
> > I have #15490 open, asking for recovery keys to be changed so they do address this use-case.
> 
> I have realised that even if recovery keys were changed to permit unsealing Vault itself, this would still leave data protected by sealwrap unrecoverable. Only a concern for Enterprise users, but a complication, none the less.

Thanks as always Max! I'll ask our engineers to take a look at making the warning stronger in the documentation. I appreciate all of your efforts.

I'll close this issue now, but we'll definitely keep looking for ways to assist users in best practices.

**Closed by hsimon-hashicorp** 2022-12-16 19:42 UTC
