### ISSUE TITLE
Vault bug: Failed to run existence check ... file name too long

### ISSUE THREAD

**Issue by karysto** [hashicorp/vault#6210] opened 2019-02-11 20:53 UTC
**Describe the bug**
I'm using the Go APIs in the Vault 0.11.5 Docker image on Ubuntu 16.04 with the file backend, and I'm noticing this error come up. Everything is setup, the backend is mounted, the secrets engine (V2) is enabled, entities are created, the Go client is logged in with the token (user pass authentication) and able to make requests. For some reason, when saving a secret, I get this error: "Failed to run existence check ... file name too long". I've attached the trace below for additional context (some logs are my application).

```
2019/02/11 19:14:15 successfully created entity with id=
"4e125ef9-51dd-bcb2-d7b8-fbcfd597ae64"
2019/02/11 19:14:15 creating entities...
2019/02/11 19:14:15 successfully created entity with id=
"4e564d34-6894-7633-23d4-984bfc2abfee"
2019/02/11 19:14:15 successfully created entity with id=
"ef7b0cdb-40f0-1e46-5a2d-ed02cce54492"
2019/02/11 19:14:15 enable kv secrets engine at user-kv
2019-02-11T19:14:15.321Z [INFO]  core: successful mount: namespace= path=
user-kv/ type=kv
2019/02/11 19:14:15 successfully enabled new kv secrets engine at user-kv
2019/02/11 19:14:15 setup complete, ready for application connections...
2019-02-11T19:14:15.331Z [INFO]  secrets.kv.kv_b283d0f3: collecting keys to 
upgrade
2019-02-11T19:14:15.331Z [INFO]  secrets.kv.kv_b283d0f3: done collecting 
keys: num_keys=1
2019-02-11T19:14:15.331Z [INFO]  secrets.kv.kv_b283d0f3: upgrading keys 
finished

--after I make the secret write API call in Go--

2019-02-11T19:16:13.740Z [ERROR] core: failed to run existence check: error="open 
vault_data/logical/06664d18-8ec2-3d86-5b92-5803a0e573a3/9f131beb-f334-9679-3bb7-2e2715a8bf73/metadata/1TfFUMtlW918N8L7cCFkQmkbSUpyh6s03pVzhR9uqr6aRp3yMXPv45B1b4mkoUCxBnoxkULEF/8RGGW6fZnqAPxakIPjLoZ7luSQ5BbTCQGEwWB0zhJl01XKRzDRAEoTEdrsGeWbhZ6aZQPznuqmaTmH/_30OcGnws0Lvdj9kRdEkovCsUMr11zgC1Zf6WK0UepVnGZO7JxCGtuRfFUmQSpxO1xFgij5GWqjSNpPFYgtJSw7JEmTXEhELTmTQOSZfdH2RYSP9BUiXXetrEOkfDSrP0siqDcR0tOvwu6twqK051i7zuzmyUq1apXi80Zu1EuUSRCPj: 
file name too long"

```
**To Reproduce**
Use the code below on an Ubuntu 16.04 machine with the Docker image `vault:0.11.5`.

```go
// writeToVault writes the given content to the secretPath using the client
func writeToVault(client *api.Client, secretPath, content string) error {
    if client == nil {
        return fmt.Errorf(`writeToVault error: cannot write because 
received vault client is nil`)
    }

    secretData := map[string]interface{}{
        `data`: map[string]interface{}{
            `content`: content,
        },
    }

    writeResponse, writeError := client.Logical().Write(secretPath, 
secretData)
    if writeError != nil {
        return fmt.Errorf(`error while writing to vault: %s`, writeError)
    }

    for _, warning := range writeResponse.Warnings {
        log.Printf(`warning while writing to vault: '%s'`, warning)
    }

    return nil
}
```

**Expected behavior**
The secret to be successfully created

**Environment:**
-Docker image: `vault:0.11.5`

Vault server configuration file(s):

```hcl
ui = false
disable_cache = false
disable_mlock = true

listener "tcp" {
  address       = "REDACTED:8200"
  tls_enable    = 1
  tls_cert_file = "/tls/selfsigned.crt"
  tls_key_file  = "/tls/selfsigned.key"
}

storage "file" {
  path = "./vault_data"
}

```

**Additional context**
What's odd about this error is that despite being run on Docker, my colleague's laptop (MacOS Sierra 
10.12.6) works seamlessly without this error using the same code.

I've narrowed the error output to this file in Vault, but can't determine why it's happening on Ubuntu anot Mac
despite being run in Docker on both machines.

https://github.com/hashicorp/vault/blob/47d339fce18017bf21b6765ea7452c9175dff06f/vault/request_handling.go#L285

**Comment by jefferai** [comment] 2019-02-11 21:07
Duplicate of https://groups.google.com/d/msgid/vault-tool/f0fee33b-d54f-48ce-b555-0cc50a576d03%40googlegroups.com?utm_medium=email&utm_source=footer

**Closed by jefferai** 2019-02-11 21:07 UTC
