### ISSUE TITLE
vault  login panic

### ISSUE THREAD

**Issue by xueshanf** [hashicorp/vault#5602] opened 2018-10-24 18:00 UTC
**Describe the bug**

Vault version: 0.11.4
`vault login` without any argument, or with -method=<ldap|userpass>, without username, panics with error:

panic: assignment to entry in nil map

**To Reproduce**
1. Run `vault login`
```$ vault login
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/hashicorp/vault/command.(*LoginCommand).Run(0xc00059da40, 0xc00000a070, 0x0, 0x0, 0xc00058d6e0)
	/private/tmp/vault-20181024-94467-1i61kxt/src/github.com/hashicorp/vault/command/login.go:255 +0xdee
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc0000ffe00, 0xc0000ffe00, 0xc00058daa0, 0xc00025c5a0)
	/private/tmp/vault-20181024-94467-1i61kxt/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x207
github.com/hashicorp/vault/command.RunCustom(0xc00000a070, 0x1, 0x1, 0xc00059d8b0, 0x0)
	/private/tmp/vault-20181024-94467-1i61kxt/src/github.com/hashicorp/vault/command/main.go:170 +0x74a
github.com/hashicorp/vault/command.Run(0xc00000a070, 0x1, 0x1, 0xc000098058)
	/private/tmp/vault-20181024-94467-1i61kxt/src/github.com/hashicorp/vault/command/main.go:81 +0x48
main.main()
	/private/tmp/vault-20181024-94467-1i61kxt/src/github.com/hashicorp/vault/main.go:10 +0x62
```

Same for `vault login -method=ldap`, `vault login -method=userpass`.  It works IF username is provided.

**Expected behavior**

In 0.10.x, vault login assumes default login (token), and if -method is used, without username, it tries to use LOGNAME, USER environment variable. 

I think if vault login no longer takes default, it  should exit with error information instead of panic.

**Environment:**

* Vault Server Version
```
$ vault status
Key                    Value
---                    -----
Seal Type              shamir
Initialized            false
Sealed                 false
Total Shares           7
Threshold              2
Version                0.11.1
Cluster Name           vault-cluster-9d051ddf
Cluster ID             3d1c227d-df3e-30da-59a6-332dea2002e4
HA Enabled             true
HA Cluster             https://10.88.1.38:8201
HA Mode                standby
Active Node Address    https://:8200 (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:
```

**Comment by kalafut** [comment] 2018-10-24 18:33
Duplicate of #5600

**Closed by kalafut** 2018-10-24 18:33 UTC

**Comment by Tibevilaqua** [comment] 2018-10-30 02:34
Same for me, I'm getting the same problem when I try to follow the intro guide `https://learn.hashicorp.com/vault/getting-started/authentication`
More specifically, when I run: `vault login -method=github`

I'm using a docker container `FROM vault:latest`

`vault status`
