### ISSUE TITLE
AWS Login with PKCS7 fails in 0.9.4

### ISSUE THREAD

**Issue by gargath** [hashicorp/vault#4042] opened 2018-02-27 12:00 UTC
Since upgrading our 3-node HA-with-DynamoDB Vault cluster from 0.7.2 to 0.9.4, EC2 instances can no longer log in using their PKCS7 identity document signature.
Vault fails to validate the signature, even though manual validation (as per https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html) succeeds.
Nothing has changed about the auth flow except for the vault version.
No errors are present in vault logs.
I would appreciate some pointers on how to debug this further.

**Environment:**

* Vault Version: Vault v0.9.4 ('2e2c89a3d8d2f4876c64dee6ba3d4a5e08691aee')
* Operating System/Architecture: CoreOS / Docker

**Vault Config File:**
```
storage "dynamodb" {
  ha_enabled = "true"
  region = "us-east-1"
  table = "<redacted>"
  read_capaticy = 3
  write-capacity = 3
}
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/vault/tls/certificate.crt"
  tls_key_file = "/vault/tls/certificate.key"
}
cluster_name = "<redacted>"
```

**Startup Log Output:**
```
Feb 26 14:01:50 ip-172-16-0-222.ec2.internal docker[1082]:                      Cgo: disabled
Feb 26 14:01:50 ip-172-16-0-222.ec2.internal docker[1082]:          Cluster Address: https://172.16.0.222:8201
Feb 26 14:01:50 ip-172-16-0-222.ec2.internal docker[1082]:               Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
Feb 26 14:01:50 ip-172-16-0-222.ec2.internal docker[1082]:                Log Level: info
Feb 26 14:01:50 ip-172-16-0-222.ec2.internal docker[1082]:                    Mlock: supported: true, enabled: true
Feb 26 14:01:50 ip-172-16-0-222.ec2.internal docker[1082]:         Redirect Address: https://<redacted>:8200
Feb 26 14:01:50 ip-172-16-0-222.ec2.internal docker[1082]:                  Storage: dynamodb (HA available)
Feb 26 14:01:50 ip-172-16-0-222.ec2.internal docker[1082]:                  Version: Vault v0.9.4
Feb 26 14:01:50 ip-172-16-0-222.ec2.internal docker[1082]:              Version Sha: 2e2c89a3d8d2f4876c64dee6ba3d4a5e08691aee
```

**Expected Behavior:**
Previously, using vault 0.7.2, we had EC2 instances logging into vault via:
```
PKCS7=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 | tr -d '\n')
VAULT_TOKEN=$(curl -s -L -X POST "https://vault.pusherplatform.io:8200/v1/auth/aws/login" -d '{"role": "node", "pkcs7":"'"$PKCS7"'"}' | jq .auth.client_token | tr -d \" )
```

**Actual Behavior:**
Since upgrading to 0.9.4, this exact same method fails with
```
{"errors":["failed to verify the signature"]}
```

**Steps to Reproduce:**
I'm not sure how reproducible this is going to be. It happens to 100% of nodes in our environment.
```
$ curl -s -L --header "X-Vault-Token: $(cat ~/.vault-token)" -X LIST "https://vault.pusherplatform.io:8200/v1/auth/aws/roles"

{"request_id":"90575d93-956a-2670-7d64-2cf7a9731eda",
  "lease_id":"",
  "renewable":false,
  "lease_duration":0,
  "data": {
    "keys":["node"]
  },
  "wrap_info":null,
  "warnings":null,
  "auth":null
}

$ curl -s -L --header "X-Vault-Token: $(cat ~/.vault-token)" -X GET "https://vault.pusherplatform.io:8200/v1/auth/aws/config/client"

{
  "request_id": "f2495d19-8ffd-3161-abd9-44cca7bcdc1c",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "MaxRetries": -1,
    "access_key": "",
    "endpoint": "",
    "iam_endpoint": "",
    "iam_server_id_header_value": "",
    "secret_key": "",
    "sts_endpoint": ""
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}


$ curl -s -L --header "X-Vault-Token: $(cat ~/.vault-token)" -X GET "https://vault.pusherplatform.io:8200/v1/auth/aws/role/node"

{
  "request_id": "5ec7d4b9-6e0f-c93e-a25a-9b51ba1c6ff7",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "allow_instance_migration": false,
    "auth_type": "ec2",
    "bound_account_id": "<redacted>",
    "bound_ami_id": "",
    "bound_iam_instance_profile_arn": "",
    "bound_iam_principal_arn": "",
    "bound_iam_principal_id": "",
    "bound_iam_role_arn": "",
    "bound_region": "",
    "bound_subnet_id": "",
    "bound_vpc_id": "",
    "disallow_reauthentication": false,
    "inferred_aws_region": "",
    "inferred_entity_type": "",
    "max_ttl": 36000,
    "period": 0,
    "policies": [
      "default",
      "node"
    ],
    "resolve_aws_unique_ids": false,
    "role_tag": "",
    "ttl": 0
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

**Important Factoids:**
Vault nodes use their EC2 instance role to access AWS APIs and so normally do not need a key or secret, but I have also tried configuring an explicit access_key and secret_key. The result was the same.

**Comment by jippi** [comment] 2018-02-27 12:28
Duplicate of #4014 and was fixed in 0.9.5

**Comment by gargath** [comment] 2018-02-27 13:07
Thanks, sorry for not finding #4014 on my own. Will upgrade to `0.9.5` and re-test.

**Comment by gargath** [comment] 2018-02-27 14:01
@jippi https://hub.docker.com/r/library/vault/tags/ does not seem to have a `0.9.5` image. Will have to wait until one is available.

**Comment by jefferai** [comment] 2018-02-27 14:11
It's in Docker's hands at the moment.

You can build on your own, or use the separate instance doc/signature parameters instead, which did not have this problem.

**Closed by jefferai** 2018-02-27 14:11 UTC

**Comment by chrishoffman** [comment] 2018-02-27 18:23
@gargath @jippi Docker images are now published.
