### ISSUE TITLE
Request forwarding may choke on non-url-safe values

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#3049] opened 2017-07-24 15:41 UTC
It seems like request forwarding may cause certain values like `//` which are url-encoded coming into Vault to not be properly escaped after forwarding, leading to 301s.

**Comment by chrishoffman** [comment] 2017-08-01 12:57
It looks like this issue is not related to request forwarding but has to do with how `net/http` handles `//`.  If there is a double slash encountered in the URL, it replaces it with a single slash and redirects with a 301.  We could probably work around this but I'm not sure it makes much sense to.  

https://github.com/golang/go/blob/master/src/net/http/server.go#L2213-L2219
https://github.com/golang/go/blob/master/src/path/path.go#L55-L140

**Comment by jefferai** [comment] 2017-08-01 13:49
The 301 is how I knew what the problem was in the first place, since Vault doesn't issue 301s itself :-) But, the user only saw the 301s when hitting standby nodes; no 301s were issued when directly accessing the active node.

What this suggests is that the client is properly urlencoding the slashes in its path in the original request, but that when we then package up that path and send it to the active node, somewhere along the way we are failing to re-urlencode the path, leading the active node to issue 301s to the standby's request.

**Comment by chrishoffman** [comment] 2017-08-01 13:53
I tried using unencoded and encoded slashes on the active node and got 301s on all of them for any url with a double slash.  

These are from just a straight `vault server -dev` with no standby or forwarding.  Are you not seeing the same behavior?

```% curl -v http://127.0.0.1:8200/v1/ldskj///
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8200 (#0)
> GET /v1/ldskj/// HTTP/1.1
> Host: 127.0.0.1:8200
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Cache-Control: no-store
< Location: /v1/ldskj/
< Date: Tue, 01 Aug 2017 13:52:15 GMT
< Content-Length: 45
< Content-Type: text/html; charset=utf-8
<
<a href="/v1/ldskj/">Moved Permanently</a>.

* Connection #0 to host 127.0.0.1 left intact
% curl -v http://127.0.0.1:8200/v1/ldskj/%2F%2F
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8200 (#0)
> GET /v1/ldskj/%2F%2F HTTP/1.1
> Host: 127.0.0.1:8200
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Cache-Control: no-store
< Location: /v1/ldskj/
< Date: Tue, 01 Aug 2017 13:52:27 GMT
< Content-Length: 45
< Content-Type: text/html; charset=utf-8
<
<a href="/v1/ldskj/">Moved Permanently</a>.

* Connection #0 to host 127.0.0.1 left intact
```

**Comment by chrishoffman** [comment] 2017-08-01 15:44
Closing this issue since we cannot reproduce the behavior only happening on the standby nodes using request forwarding.

**Comment by jefferai** [comment] 2017-08-01 15:44
I've also tried, both POST and GETs, to both active and standby nodes. Cannot reproduce any kind of invalid behavior -- 301s are expected but do not then result in any kind of loop as the user seemed to see.

This appears to be an issue in the user test suite.

**Closed by chrishoffman** 2017-08-01 15:44 UTC
