### ISSUE TITLE
Vault Agent is revoking periodic tokens at system/mountpoint max_ttl

### ISSUE THREAD

**Issue by danlsgiga** [hashicorp/vault#6659] opened 2019-04-30 19:03 UTC
Vault agent works nicely on managing renewal of tokens and leases. But it does not manage to create a new token once the one it has expires due to the default vault max_ttl of 32 days. I'm using the AWS Auth secret engine and even setting the roles with `max_ttl=0` and `periodic=4hr`, the token still expires when the 32 default max_ttl is reached. Right now we have a workaround to restart the vault agent service but it would be nice to have it handling that scenario.

**Describe the solution you'd like**
Once the token is about to expire due to its max_ttl, create a new one and manage its renewal lifecycle without requiring a service restart. 

Also, it would be nice to have a hook to execute a command whenever that happens so we can automate requesting new Consul ACLs via Vault and updating them accordingly via Consul API. It would basically be the same behaviour that consul-template would have when a value changes on consul where you have an optional command to run after the new template is rendered.

**Describe alternatives you've considered**
Alternatives are basically out-of-band processes like restarting the daemon to force a new token creation

**Additional context**
We can potentially extend the `max_ttl` setting of Vault globally or the mountpoint. But this sounds dirty and goes totally against the value of having Vault.

**Comment by calvn** [comment] 2019-04-30 19:48
Agent should be able to handle periodic token renewals continuously as long as the token is renewed within the period's value (agent should take care of this). Can you provide your role configuration setup with any sensitive information scrubbed? The config parameter for the period should be `period` and not `periodic`.

**Comment by danlsgiga** [comment] 2019-04-30 19:56
Sure, here it goes... 

```
Key                               Value
---                               -----
allow_instance_migration          false
auth_type                         iam
bound_account_id                  []
bound_ami_id                      []
bound_ec2_instance_id             <nil>
bound_iam_instance_profile_arn    [arn:aws:iam::xxx:instance-profile/yyy]
bound_iam_principal_arn           []
bound_iam_principal_id            []
bound_iam_role_arn                []
bound_region                      []
bound_subnet_id                   []
bound_vpc_id                      []
disallow_reauthentication         false
inferred_aws_region               us-east-1
inferred_entity_type              ec2_instance
max_ttl                           0s
period                            4h
policies                          [baseline-ro secrets-baseline]
resolve_aws_unique_ids            true
role_id                           arandomuuid
role_tag                          n/a
ttl                               4h
```

**Comment by calvn** [comment] 2019-05-01 17:28
I was partially able to reproduce the issue where a periodic token was not being handled as one during the renewal process. However, even in the case of a non-periodic token, agent should be able to re-fetch a new token via the auto-auth mechanism whenever the old one expires once it reaches the system's max TTL. Can you provide the agent config and logs around the time when the token expired, if that's available?

**Comment by danlsgiga** [comment] 2019-05-01 19:39
Sorry I can't find any relevant logs...

Here's my config:

```
exit_after_auth = false

vault {
  address = "https://vault.service.consul:8200"
}

auto_auth {
  method "aws" {
    mount_path = "auth/aws"
    config = {
      type = "iam"
      role = "my-role"
    }
  }

  sink "file" {
    config = {
      path = "/dev/shm/.vault-token"
    }
  }
}

cache {
  use_auto_auth_token = true
}

listener "tcp" {
  address = "127.0.0.1:8100"
  tls_disable = true
}
```

I believe I understand now what happened in our env. We use consul to discover the vault nodes but we also introduce the Consul ACL via a systemd timer that is triggered whenever consul or the vault agent are started/restarted.

`
/opt/consul/client/bin/consul acl set-agent-token default $(/opt/vault/client/bin/vault read -address=http://127.0.0.1:8100 -field=token consul/creds/my-consul-acl-role)
`

The problem is, since the auth token was revoked, so did the Consul ACL and in that case Consul can't do DNS resolving anymore which then makes the vault agent dead since it can't find vault.service.consul anymore and we ended up in a "deadlock".

So, being able to trigger that systemd service to update the Consul ACL whenever a new auth token is created would be nice.

**Comment by calvn** [comment] 2019-05-01 20:10
I see, so in this case it was a DNS resolution issue that caused agent to be unable to reach Vault in order to fetch a new token, which in turn was caused by the token hitting the system max TTL. I'm working on addressing the periodic renewal issue, so once that's fixed the token shouldn't be bounded by the system's max TTL.

> So, being able to trigger that systemd service to update the Consul ACL whenever a new auth token is created would be nice.
I am not exactly sure what's the best approach to this, but maybe having a different token that issues the ACL token externally (one that's not created by an agent-managed token) and injects it into the instance would prevent this chicken-and-egg problem.

**Comment by danlsgiga** [comment] 2019-05-01 20:38
Hmm... if you are able to fix the issue of the periodic token expiring and revoking everything under it at the system or mountpoint max_ttl time then I should be good. That way the token will be valid "indefinitely" and I won't need to have any trigger to create new Consul ACLs.

**Comment by calvn** [comment] 2019-05-02 01:17
After further investigation, weren't able to reproduce the apparent periodic token renewal issue (it was the testing procedure that was done incorrectly).

Would you be able to reproduce (perhaps by setting up an AWS mount with a low TTL value (e.g. 5mins), and attach trace-level logs from the server and agent?

Another question we have is around the bootstrapping process for consul and agent. Since it seems that consul service DNS resolution works only with a valid ACL token, how is that token fetched the first time around? Vault agent is not yet able to resolve the Vault address, and consul agent doesn't yet have an ACL token fetched via `$(/opt/vault/client/bin/vault read -address=http://127.0.0.1:8100 -field=token consul/creds/my-consul-acl-role)`.

**Comment by calvn** [comment] 2019-05-02 01:21
Can you also include the Vault server and agent versions that you're running?

**Comment by danlsgiga** [comment] 2019-05-02 15:22
Ok, I can try setting up a new mountpoint with short max_ttl and use that to troubleshoot but the problem here is the token being revoked at the system max_ttl... periodic token and Consul ACLs generated are renewed fine in the 4h TTL timerange of the role... until the max_ttl reaches.

Vault agent and server are running on v1.1.0

Regarding the bootstrap process, we are giving the anonymous policy the following rules:

```hcl
node_prefix "" { policy = "write" }
agent_prefix "" { policy = "write" }
service_prefix "" { policy = "read" }
```

This overcome that bootstrap limitation for the agent to be able to discover other services until its ACL token is injected by that script. I have another issue open in the Consul repo [here](https://github.com/hashicorp/consul/issues/5535) asking for a better way for us to make that process less painful.

**Comment by danlsgiga** [comment] 2019-05-02 15:55
Ok, I've setup a new mountpoint for aws auth, configured it and configured a secondary vault agent... I can't reproduce the auth token being revoked at max_ttl at all. So putting that aside I'm wondering if the Consul ACLs are the ones being revoked via the Consul Secret backend at the system max_ttl since there are no notion of Consul ACL Periodic Token. I have specified max_ttl for the consul mountpoint to 0, so it makes sense it would expire at the max_ttl.

Is there a solution for that?

**Comment by calvn** [comment] 2019-05-02 16:21
If you're setting the [max_lease_ttl](https://www.vaultproject.io/api/system/mounts.html#max_lease_ttl) on a mount, and that is shorter that the systems's max TTL, that value should take precedence. By setting the mount's max lease TTL we are trying to trigger that expiration behavior without waiting for 32 days. However, this value doesn't seem to be the root cause for token expiry in this case.

The issue might be as you've pointed out - the Consul token that is generated doesn't support periodic renewal, so once it hits the [max_ttl](https://www.vaultproject.io/api/secret/consul/index.html#max_ttl), it will get expired and agent will lose connectivity with the Vault server, which in turn will fail to renew its auto-auth token (using the aws auth method).

Would it be possible to decouple the dependency between agent and its ability to discover the Vault server in your setup?

**Comment by danlsgiga** [comment] 2019-05-02 16:28
Ok, I just confirmed the problem is indeed the Consul ACL being revoked at the max_ttl. The AWS Auth token is being renewed indefinitely as expected.

I believe the problem now relies on Vault's Consul Secret backend revoking the ACL Token after the system max_ttl is reached, even though I set the mountpoint max_ttl to 0. Is there any alternative to workaround that?

**Comment by danlsgiga** [comment] 2019-05-02 16:54
@calvn If I have my Consul Secret mountpoint set with default TTL set to 15m at what time will Vault try to renew it?

I'm wondering what periodicity should I set for my `$(/opt/vault/client/bin/vault read -address=http://127.0.0.1:8100 -field=token consul/creds/my-consul-acl-role)` script to run to be able to get a new Consul ACL token when it is close to reach the max_ttl (system or mount point).

I believe my only solution for now is to have that script to run often enough to get a new Consul ACL token and inject it to the Consul agent before it gets revoked.

**Comment by calvn** [comment] 2019-05-02 17:10
It works in the same way as the [role's TTL](https://www.vaultproject.io/api/secret/consul/index.html#ttl). If the role TTL is not provided then the mount's default_lease_ttl will be used, but otherwise the role TTL is used.

Your proposed solution makes sense, just make sure that the frequency is lower than the Consul token's max_ttl value (the lowest of the role's max TTL, mount's max TTL, and system max TTL) to ensure a valid token for the consul agent at all times. In this case, you can leave the consul secret engine mount's default TTL untouched.

**Comment by danlsgiga** [comment] 2019-05-02 17:22
Based on my calculation here, I'd have to run that script every 2 minutes to be able to get a new Consul ACL token with a default TTL of 15m to avoid the current one being revoked before I get a new one. 🤔 A bit overkill but 🤷‍♂

**Comment by calvn** [comment] 2019-05-02 17:27
You should base it off the max TTL, not the default TTL value. Can you share the `my-consul-acl-role` role? If you didn't set a `max_ttl` value in there, and you didn't se a `max_lease_ttl` in the mount, any time before the system's max TTL (by default its 32 days) should work.

**Comment by danlsgiga** [comment] 2019-05-02 17:44
Not really... I'm using the Vault agent cache mechanism, so if I run `$(/opt/vault/client/bin/vault read -address=http://127.0.0.1:8100 -field=token consul/creds/my-consul-acl-role)` repeatedly I'll always get the same results since it is getting the values from the cache. So I need to be able to run that command after the Vault agent failed to renew the lease which will force the creation of a new one.

My max_ttl is effectively set to 32 days (using the defaults), if I run that command every 30 days the lease is still valid and cached and in the next 2 days the max_ttl will be reached and the agent won't be able to renew it anymore.

Based on that we should use the default_ttl - the amount of time Vault will take to try to renew and fail.

I've done some tests here and it seems to me that Vault agent tries to renew the lease at ~ 30% of the defined default TTL...

Default TTL set to 3m - Vault will renew at ~ 54 seconds remaining to the lease to expire
Default TTL set to 15m - Vault will renew at ~ 270 seconds remaining to the lease to expire

So, in my case, the default TTL is 15m and Vault will only fail to renew the lease ~ 4.5 minutes before it is revoked by the max_ttl.

Makes sense at all?

**Comment by calvn** [comment] 2019-05-02 17:56
Ah, right re-fetching like so won't do it since it's being cached. There's an API endpoint that let's you clear the cache for that entry: https://www.vaultproject.io/docs/agent/caching/index.html#cache-clear (perhaps using type: `request_path`, value: `consul/creds/my-consul-acl-role`). You'll have to do that before running the `$(/opt/vault/client/bin/vault read -address=http://127.0.0.1:8100 -field=token consul/creds/my-consul-acl-role)` command.

I still think that the calculation should be based off the max TTL value. The default TTL doesn't really matter in this case since renewal will simply extend the lease. What we want do to is to get a new token before it expires, regardless of whether renewal has occurred or not, which is determined by the max TTL.

**Comment by calvn** [comment] 2019-05-02 18:04
Actually that might not work, since clearing the cache would probably revoke the lease. I'll have to verify that.

**Comment by danlsgiga** [comment] 2019-05-02 18:08
Ok, that may be a better path to take... thanks for poiting the clear cache endpoint.

So, from my understanding, clearing the cache will cause the agent to not renew the leases attached to that request_path anymore... but... it *won't* revoke the lease, right?

**Comment by danlsgiga** [comment] 2019-05-02 18:21
According to my tests, it does *not* revoke the lease! 🎉 

I was able to clear the cache using the request_path = /v1/consul/creds/my-consul-acl-role

Right after I requested a new one via `$(/opt/vault/client/bin/vault read -address=http://127.0.0.1:8100 -field=token consul/creds/my-consul-acl-role)` and the subsequent requests were cached!

**Comment by calvn** [comment] 2019-05-02 19:02
Awesome! I'll close this for now, but if the problem re-surfaces feel free to re-open!

**Closed by calvn** 2019-05-02 19:02 UTC

**Comment by Kevino135** [comment] 2021-12-22 04:51
.
