### ISSUE TITLE
Critical Issue - Vault

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/vault#2480] opened 2017-03-14 06:49 UTC
We are facing a difficult situation in which all vault commands are returning internal error
* Vault version `0.6.1`

```
vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Version: Vault v0.6.1
Cluster Name: vault-cluster-6a7ff43d
Cluster ID: ce8c41ff-f289-60c1-a22f-dae514310cc2

High-Availability Enabled: true
	Mode: active
	Leader: https://ourserver:8200
```

```
vault auth
Token (will be hidden):
Error validating token: Error making API request.

URL: GET https://ourserver:8200/v1/auth/token/lookup-self
Code: 500. Errors:

* internal error
```

* All applications are currently working since appid based authentication and reading of secrets is going through fine
* We are unable to create any new tokens/appids as any operation to do with root token throws this internal error
* There are absolutely no logs when this error happens

* Is there anything that we can do to come out of this situation? 
* Changing the cluster leader might be an option to try by using the `step-down` api but that looks scary and we don't want to lose the entire cluster functionality by doing it.

**Comment by vishalnayak** [comment] 2017-03-14 09:38
@vrenjith I am not able to think of a reason why this is happening offhand. But happy to work with you to find out the cause.

- Which storage backend are you using? Have you taken the backup of your storage backend? If not, can you do it?
- How many Vault nodes are in your cluster?
- How does your Vault config look like?
- What is your VAULT_ADDR set to?
- Are there any logs that are coming from other nodes? (active and standbys)
- Are all the nodes using the same version of Vault binary?

**Comment by vrenjith** [comment] 2017-03-14 10:49
- Which storage backend are you using? Have you taken the backup of your
storage backend? If not, can you do it? - Consul. No backups.
- How many Vault nodes are in your cluster? - 5
- How does your Vault config look like?
```

backend "consul" {
    address = "@@HOSTIP@@:8500"
    path = "vault"
    scheme="http"
    advertise_addr="https://@@HOSTNAME@@:8200"
}

listener "tcp" {
    address = "@@HOSTIP@@:8200"
    tls_cert_file = "/var/vault/ssl/certs/vault.service.@@MU_DOMAIN@@.crt"
    tls_key_file = "/var/vault/ssl/private/vault.service.@@MU_DOMAIN@@.key"
}

```

- What is your VAULT_ADDR set to? http://ourserver:8200
- Are there any logs that are coming from other nodes? (active and
standbys) - Absolutely nothing
- Are all the nodes using the same version of Vault binary? - All on same
version `0.6.1`

**Comment by vrenjith** [comment] 2017-03-14 10:50
* Which storage backend are you using? Have you taken the backup of your
storage backend? If not, can you do it? - Consul. No backups.
* How many Vault nodes are in your cluster? - 5
* How does your Vault config look like?
```
backend "consul" {
    address = "@@HOSTIP@@:8500"
    path = "vault"
    scheme="http"
    advertise_addr="https://@@HOSTNAME@@:8200"
}

listener "tcp" {
    address = "@@HOSTIP@@:8200"
    tls_cert_file = "/var/vault/ssl/certs/vault.service.@@MU_DOMAIN@@.crt"
    tls_key_file = "/var/vault/ssl/private/vault.service.@@MU_DOMAIN@@.key"
}
```
* What is your VAULT_ADDR set to? http://ourserver:8200
* Are there any logs that are coming from other nodes? (active and
standbys) - Absolutely nothing
* Are all the nodes using the same version of Vault binary? - All on same
version `0.6.1`

**Comment by vishalnayak** [comment] 2017-03-14 11:19
@vrenjith 

Since the problem is showing up in a specific code paths, and since Vault is still operational, just checking if the problem is only around the lookup-self call or if it can be noticed elsewhere as well. Could you please give more examples for failures, as you mentioned that all operations involving root tokens are failing?

To isolate the problem, is it a possibility that you take a backup of the storage and bring up an independent Vault server on the backup replica to see if the problem exists there? Following that, trying out with an upgraded binary is also one way to go about.

Are you seeing any Consul logs?

**Comment by jefferai** [comment] 2017-03-14 11:45
@vrenjith Vault always outputs logs, to stdout. If you are not capturing those you may not have any logs, but they are being output. Without those it's hard to guess what the problem may be.

**Comment by jefferai** [comment] 2017-03-14 14:38
(Closing in favor of the ZenDesk ticket)

**Closed by jefferai** 2017-03-14 14:38 UTC
