### ISSUE TITLE
Templated policy with metadata does not work

### ISSUE THREAD

**Issue by ichilton** [hashicorp/vault#11925] opened 2021-06-23 11:57 UTC
**Describe the bug**

I am trying to use a policy with the template functionality to use metadata.

Am using Vault with SaltStack and am trying to create a single policy to replace a policy per host.

When SaltStack creates a token for a minion (host), it automatically includes metadata. In particular, saltstack-minion is set to the hostname.

**To Reproduce**

Salt makes a request to:

```
POST /v1/auth/token/create HTTP/1.0
```

The request contains:

```
{"policies": ["salt/minions", "salt/minion/myhost.domain.net"], "num_uses": 50, "meta": {"saltstack-jid": "20210622154012124421", "saltstack-minion": "myhost.domain.net", "saltstack-user": "root"}, "explicit_max_ttl": "300"}
```

The response contains:

```
"policies":["default","salt/minion/myhost.domain.net","salt/minions"],"token_policies":["default","salt/minion/myhost.domain.net","salt/minions"],"metadata":{"saltstack-jid":"20210622154012124421","saltstack-minion":"myhost.domain.net","saltstack-user":"root"},
```

A request for auth/token/lookup-self contains:

```
    meta:
        ----------
        saltstack-jid:
            20210622154012124421
        saltstack-minion:
            myhost.domain.net
        saltstack-user:
            root
    num_uses:
```

I then create a policy containing:

```
path "salt/minion/{{identity.entity.metadata.saltstack-minion}}/*" {
  capabilities = ["read"]
}
```

I then do a request for:

```
GET /v1/salt/minion/myhost.domain.net/db HTTP/1.0
```

and it returns 403!

```
$ vault token capabilities s.mytoken salt/minion/myhost.domain.net/db
deny
```

```
$ vault token lookup s.mytoken
Key                 Value
---                 -----
...
policies            [default salt/minion/myhost.domain.net salt/minions]

$ vault policy read salt/minions
path "salt/global/*" {
  capabilities = ["read"]
}

path "salt/minion/{{identity.entity.metadata.saltstack-minion}}/*" {
  capabilities = ["read"]
}
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.0
* Vault CLI Version (retrieve with `vault version`): 1.7.0
* Server Operating System/Architecture: Debian buster (10), x86_64.

Vault server configuration file(s):

```hcl
listener "tcp" {
  address       = "127.0.0.1:8200"
  tls_disable	= 1
}

storage "file" {
  path = "/opt/vault/data"
}

ui = true
```

**Additional context**

Forum thread - https://discuss.hashicorp.com/t/templated-policy/25851/4

**Comment by vishalnayak** [comment] 2021-06-23 15:58
@ichilton I think authentication using token backends does not populate entity information. https://www.vaultproject.io/docs/secrets/identity

When you do token lookup, do you see identity related information there?

**Comment by ichilton** [comment] 2021-06-23 16:01
It has:
```
entity_id:
```

..but it does have the metadata:

```
    meta:
        ----------
        saltstack-jid:
            20210623160002940813
        saltstack-minion:
            myhost.domain.com
        saltstack-user:
            root
```

Thanks,

Ian

**Comment by vishalnayak** [comment] 2021-06-24 15:34
@ichilton The metadata that you are templating are for the metadata on the entity. It seems like you are referring to the metadata on the token itself.

Please refer to this learn guide and let us know if it helps. https://learn.hashicorp.com/tutorials/vault/policy-templating

**Comment by ncabatoff** [comment] 2021-07-08 21:16
Hi @ichilton ,

I think for this to work as you'd like, you'd need to define an entity and entity alias, then make saltstack use https://www.vaultproject.io/api/auth/token#entity_alias to tie it to the tokens being created.

Alternatively, it looks like saltstack can use Approle auth instead of creating tokens directly, and indeed they recommend approle as the preferred method.  That should be the easiest way to get the metadata you want into your templates, since logging in via approle should automatically create an entity and entity alias.

I'm going to close this as it doesn't look like a bug to me, Vault is working as intended.

**Closed by ncabatoff** 2021-07-08 21:16 UTC
Labels: waiting-for-response
