### ISSUE TITLE
Create a policy to list & read (on the UI) specific secrets

### ISSUE THREAD

**Issue by royt-via** [hashicorp/vault#8695] opened 2020-04-07 21:21 UTC
Using Vault v2.
Trying to create ACL policy to allow read-only to specific secrets.
By doing this - 
```
path "kv/data/specific_secret" {
  capabilities=["read", "list"]
}
```
I was able to curl it but not see it on the UI.
By doing this -
```
path "kv/metadata" {
  capabilities=["list"]
}
path "kv/data/specific_secret" {
  capabilities=["read", "list"]
}
```
I was able to see ALL secrets on the UI but read only the specific_secret one.
I was wondering if there's a way to specify the secret I want to show.
I tried doing
```
path "kv/metadata/specific_secret" {
  capabilities=["list"]
}
path "kv/data/specific_secret" {
  capabilities=["read", "list"]
}
```
but that didn't work..
Thanks!

**Comment by tyrannosaurus-becks** [comment] 2020-04-08 21:49
Hi! I'm thinking this is essentially a dupe of https://github.com/hashicorp/vault/issues/5362. I'm going to go ahead and close this in favor of that one, but please do head over there and upvote it if you get the chance. Thank you!

**Closed by tyrannosaurus-becks** 2020-04-08 21:49 UTC
Labels: question

**Comment by royt-via** [comment] 2020-04-08 22:44
@tyrannosaurus-becks you right, same issue.
I see it was posted over 18 months ago. Any idea to when (if at all) it'll be resolved?

**Comment by tyrannosaurus-becks** [comment] 2020-04-09 22:12
Ah, good question. We receive a flood of enhancement requests, far outpacing the number of engineers we have. Because of that, for each release we go through a planning period where we look at the most requested changes and decide which to move into scope for that release, and which to keep in the backlog. To my knowledge, that work has not been added to any future release yet and assigned an engineer. However, upvoting it can help it be selected. Also, community contributions are welcome for the ones you're passionate about but our team has been unable to get to.
