### ISSUE TITLE
Segfault when TMPDIR environment variable is set before invoking vault

### ISSUE THREAD

**Issue by sriedel** [hashicorp/vault#8455] opened 2020-03-03 09:22 UTC
**Describe the bug**
Running vault commands with an adjusted TMPDIR results in a segfault

**To Reproduce**
1. Run `mkdir $HOME/mytmp`
2. Run `chmod 700 $HOME/mytmp`
3. Run `TMPDIR=$HOME/mytmp /usr/bin/vault -h`
4. See Segfault
5. Run `TMPDIR=/tmp /usr/bin/vault -h`
6. See Segfault
7. Run `/usr/bin/vault -h`
8. See no Segfault

**Expected behavior**
Vault does not segfault and returns the expected response, regardless of the TMPDIR value.

**Environment:**
* Vault CLI Version (retrieve with `vault version`): Vault v1.3.2 ('d433f38172a75f69ab0f40158936f9ac7c24f0ee+CHANGES')
* Client Operating System: archlinux x86_64
* Shell: bash 5.0.16
* umask: 0022

**Additional context**
I've tried running the vault command with strace to narrow down where the error occurs, however vault displays the expected behavior.

This has worked before, both with 1.1.x and 1.2.x versions of the vault cli. I suspect some change with 1.3 introduced this, however I can't be 100% certain. I've observed this issue for a few weeks but only got to digging into the issue now.

**Comment by catsby** [comment] 2020-03-04 18:24
Hello @sriedel - 

Unfortunately I'm not able to reproduce this, would it be possible to share more information from the segfault (without exposing any secret information)?

Here's my attempt using Vagrant to create a VM with Archlinux:

```
[vagrant@archlinux ~]$ mkdir $HOME/mytmp
[vagrant@archlinux ~]$ chmod 700 $HOME/mytmp
[vagrant@archlinux ~]$ TMPDIR=$HOME/mytmp /usr/bin/vault -h
Usage: vault <command> [args]

Common commands:
    read        Read data and retrieves secrets
    write       Write data, configuration, and secrets
    delete      Delete secrets and configuration
    list        List data or secrets
    login       Authenticate locally
    agent       Start a Vault agent
    server      Start a Vault server
    status      Print seal and HA status
    unwrap      Unwrap a wrapped secret

Other commands:
    audit          Interact with audit devices
    auth           Interact with auth methods
    debug          Runs the debug command
    kv             Interact with Vault's Key-Value storage
    lease          Interact with leases
    namespace      Interact with namespaces
    operator       Perform operator-specific tasks
    path-help      Retrieve API help for paths
    plugin         Interact with Vault plugins and catalog
    policy         Interact with policies
    print          Prints runtime configurations
    secrets        Interact with secrets engines
    ssh            Initiate an SSH session
    token          Interact with tokens
[vagrant@archlinux ~]$ TMPDIR=$HOME/mytmp /usr/bin/vault -v
Vault v1.3.2
[vagrant@archlinux ~]$
```

**Comment by sriedel** [comment] 2020-03-10 10:29
Hi,
sorry for the late response. I'd love to give more information in order to be able to reproduce or pin down the issue, however I'm a bit at a loss as to what can help you.

I've reverified the behavior described in the ticket description. Unfortunately running vault in gdb will also produce the (non-segfaulting) expected behavior, and for some reason I can't get a corefile to generate.

The only thing I can think of that explains why your VM is not seeing this behavior is that I'm running on a self-compiled 5.5.0 kernel, which however would be odd if that produced the shown behavior.

Installed glibc is 2.31-1.

    $ ldd $(which vault)
	linux-vdso.so.1 (0x00007ffdfa2e5000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f5a5b84b000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f5a62c05000)

If you can think of any other information that would help you, I'll try to supply it.

**Comment by raskchanky** [comment] 2020-09-16 16:56
Hi @sriedel 

We haven’t heard back from you on this for a while. I’m going to close this for now, but please feel free to re-open it with additional information!

**Closed by raskchanky** 2020-09-16 16:56 UTC
Labels: bug, core/cli, waiting-for-response
