### ISSUE TITLE
Upgrade from 0.10.4 -> 0.11.0 fails

### ISSUE THREAD

**Issue by smeach** [hashicorp/vault#5249] opened 2018-09-03 09:47 UTC
**Describe the bug**
We followed the standard upgrade path for our non-HA environment described here: https://www.vaultproject.io/guides/upgrading/index.html

**To Reproduce**
1. Stop Vault `systemctl stop vault` #we have a service script, so basically sending sigterm
2. Upgrade Vault by downloading the new binary and copying to the appropriate location
3. Start Vault `systemctl start vault` #the service script executes: `/usr/local/bin/vault server -config=/etc/vault/vault.cfg`
4. Unseal Vault
5. Check the logs for errors *after* a request for secrets via the client `cat /var/log/messages | grep ".*vault.*ERROR.*"`

> Sep  3 09:32:35 <host>: 2018-09-03T09:32:35.576+0100 [ERROR] core: failed to construct ACL: error="failed to get policy: failed to parse policy: failed to validate policy templating: unbalanced templating characters"
> Sep  3 09:32:36 <host>: 2018-09-03T09:32:36.875+0100 [ERROR] core: failed to construct ACL: error="failed to get policy: failed to parse policy: failed to validate policy templating: unbalanced templating characters"
> Sep  3 09:32:39 <host>: 2018-09-03T09:32:39.474+0100 [ERROR] core: failed to construct ACL: error="failed to get policy: failed to parse policy: failed to validate policy templating: unbalanced templating characters"
> 

**Expected behavior**
No errors

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.0
* Vault CLI Version (retrieve with `vault version`): 0.10.3
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
storage "file" {
  path = "/mnt/vault/data"
}

listener "tcp" {
 address = "<public-ip>:8200"
 tls_cert_file = "/etc/pki/tls/certs/<host>.crt"
 tls_key_file = "/etc/pki/tls/private/<host>.key"
}

```

**Additional context**

**Comment by Garath620** [comment] 2018-09-03 12:05
Look #5219

**Comment by chrishoffman** [comment] 2018-09-03 12:06
Thanks for reporting. This is a duplicate of #5219.

**Closed by chrishoffman** 2018-09-03 12:06 UTC
