### ISSUE TITLE
Issue with PKI Secret Lease Revocations causing Reoccuring Vault Leader Failures

### ISSUE THREAD

**Issue by hescmi** [hashicorp/vault#8994] opened 2020-05-13 22:29 UTC
**Describe the bug**
We have run into an issue similar to what is described in https://github.com/hashicorp/vault/issues/673 where Vault is DOSing Consul and itself, due to an excess of leases which are not getting cleaned up. 

While updating vault from 1.0.3 to the current latest version appears to be a route forward (that seems to be the resolution advocated in some other issues), we're looking for insight into this situation.  Details on what we hit are below.

We are on Vault v1.0.3 and for us the majority of leases are in relation to certificates generated via the PKI Secrets Engine (we have a much smaller population of KV secrets).

Following vault being stopped on a host during a maintenance we hit the following situation :

When a vault leader was elected we saw some normal lease expiration occur, and Vault was responsive
```
2020-05-13T00:02:24.846Z [INFO]  core: post-unseal setup complete
2020-05-13T00:02:24.846Z [INFO]  core: starting listener: listener_address=10...:8201
2020-05-13T00:02:24.846Z [INFO]  core: serving cluster requests: cluster_listen_address=10...:8201
2020-05-13T00:02:24.939Z [INFO]  expiration: revoked lease: lease_id=auth/token/create/nomad-cluster/cwnbvtwczaxffntlgz9x5clafsw2jkxh57nl0nzewuxgy2iwd3mv4besviagiv1hjw
. . .
2020-05-13T00:02:58.536Z [INFO]  expiration: revoked lease: lease_id=auth/token/create/nomad-cluster/hux46zrhu2god0pdu3qimm35lop3yvm5w0l5dc2cie0xjhudv5q4uvq6xlbxlvsa6m
2020-05-13T00:03:17.246Z [INFO]  expiration: lease restore complete
```

This was rather immediately followed by hundreds of the following type of message occurring within the same second and Vault becoming unresponsive:
```
2020-05-13T00:03:55.415Z [ERROR] expiration: failed to revoke lease: lease_id=pki_platform/issue/cert/02CMUQ1kRXixWnKZltBp91J9 error="failed to revoke entry: resp: (*logical.Response)(nil) err: error encountered during CRL building: error fetching list of revoked certs: context deadline exceeded"
```
Each host running Vault showed the following symptoms and weren't ultimately able to stay leader.  No host was able to handle the `failed to revoke lease` situation, and so the Vault cluster went through cyclical leader elections where for the 1st minute Vault behaved normally and then became unresponsive following the swarm of revocation attempts.

Consul remained accessible though, so we attempted what is mentioned in https://github.com/hashicorp/vault/issues/3154#issuecomment-396912466 (but with Consul as the backend).  We cleaned up entries in sys/expire that corresponded to the error messages we were seeing in the Vault logs.

After this we brought back up Vault on only one host to keep the leader on the same host. 

Vault after 1000s of additional of errors (see below) was able to eventually after several hours become stable and remain up. 
```
2020-05-13T18:41:05.227Z [ERROR] expiration: maximum revoke attempts reached: lease_id=pki/issue/cert/JsZK9B8O4CkGQUimrOAmn4zA
2020-05-13T18:41:05.227Z [ERROR] expiration: maximum revoke attempts reached: lease_id=pki/issue/cert/fPOcVgLSUWnEQ8YpFA96g8K5
2020-05-13T18:41:05.228Z [ERROR] expiration: maximum revoke attempts reached: lease_id=pki/issue/cert/y9rnF0CIOAZL9URgU24UaiVe
```

**To Reproduce**
(Not clear on the commands to induce the situation)
1. Generate 50000+ pki certs which result in bloated sys/expire/../pki/..
- This for us occurred over weeks of normal operation 

2. Stop current vault leader, triggering leader election
3. Observe new leader attempting to deal with contents of sys/expire
4. See vault become unresponsive

**Expected behavior**
Either:
The ability to control Vault requests to Consul (via `max_parallel`)
or
ideally the new leader executing lazy lease loading (though it looks like the lease type is one that still must force an immediate load)

**Environment:**
* Vault Server Version: `1.0.3`
* Vault CLI Version: `Vault v1.0.3`
* Server Operating System/Architecture: CentOS 7.8 / x86_64

Vault server configuration file(s):

```
storage "consul" {
    address = "10...:8501"
    path = "vault"
    scheme = "https"
    tls_skip_verify = "false"
    tls_ca_file = "/etc/certs/pki/vault/consul/ca.cert"
    tls_key_file = "/etc/certs/pki/vault/consul/vault.key"
    tls_cert_file = "/etc/certs/pki/vault/consul/vault.cert"
    max_parallel = "2"
}

listener "tcp" {
    address = "10..:8200"
    cluster_address = "10...:8201"
    tls_disable = 0
    tls_client_ca_file = "/etc/certs/pki/vault/vault/ca.cert"
    tls_key_file = "/etc/certs/pki/vault/vault/vault.key"
    tls_cert_file = "/etc/certs/pki/vault/vault/vault.cert"
}

api_addr = "https://10...:8200"
cluster_addr = "https://10..:8201"
```

**Additional context**
We´ve tried various value for the max_parallel parameter to no observable effect, Vault still appears to generate the same number of revoke requests to Consul. (The parameter in the config was added when troubleshooting the problem and has been left in, but we originally did not have it defined)

Also its unclear on why we leases which could not be revoked were occurring.

**Comment by ncabatoff** [comment] 2020-05-18 13:20
Hi @hescmi,

I'm sorry, this is obviously a frustrating situation to be in.  It's unfortunately not that uncommon: Vault will happily accept a bigger expiration burden than it can handle.  In other words, you can create more leases that will expire at time T than Vault (or more likely, its underlying storage) will be able to expire in a reasonable amount of time.  And sometimes, as happens here, Vault's desperate attempt to expire everything at once after being down for a while leads to further problems.  Typically this is the "fault" of the storage layer, but Vault doesn't do as good a job as it should of handling the problem.  We're working on it.

I'm surprised `max_parallel` isn't working for you.  I've used it to good effect in the past.  But it's a heavy hammer: you're throttling not just the expiration work, but also the storage layer when used to service all incoming requests.  Really the better solution is to make sure that you're not generating an unsustainable expiration load.  That said, if you want me to follow up, some more complete logs would be helpful.

Re:
> Also its unclear on why we leases which could not be revoked were occurring.
This is because you're getting timeouts ("context deadline exceeded") from Consul when trying to revoke.

You say you're seeing 50k certs in sys/expire after a few weeks.  That seems high, do you have 50k certs in use, or are many of these duplicates?  Are you keeping your cert lifetimes short as per https://www.vaultproject.io/docs/secrets/pki#keep-certificate-lifetimes-short-for-crl-s-sake?  If your cert ceases to become valid before revocation, it won't get added to the CRL.

The fact that you saw this:

> 2020-05-13T00:03:55.415Z [ERROR] expiration: failed to revoke lease: lease_id=pki_platform/issue/cert/02CMUQ1kRXixWnKZltBp91J9 error="failed to revoke entry: resp: (*logical.Response)(nil) err: error encountered during CRL building: error fetching list of revoked certs: context deadline exceeded"

makes me wonder if you have a large CRL, since all that's doing is a LIST to Consul on the pki mount's `revoked/` prefix.  Can you query it ([Read CRL](https://www.vaultproject.io/api-docs/secret/pki#read-crl)) and see if indeed it is large?  If so, do you know why?  Are you explicitly revoking a lot of certs, or have you done so in the past?

Are you actually making use of the CRL?  There are going to be gaps in yours due to the failed revocation attempts.   Either way it may make sense to start fresh, by doing a tidy with [tidy_revoked_certs](https://www.vaultproject.io/api-docs/secret/pki#tidy_revoked_certs).

**Comment by ncabatoff** [comment] 2020-05-21 13:43
I'm going to close this issue.  I won't say it's "not a bug", because although Vault is working as designed, it includes some notorious footguns in this area.  We will continue to work to improve the situation re handling excessive leases, but this is a longstanding issue that will require major changes, and the work won't be tracked by a single github issue.  

I think the right place to continue this discussion (if desired) is the [forum](https://discuss.hashicorp.com/c/vault).  Since this is an issue that affects many Vault clusters at some point, I'd rather more people see it and benefit from it, or even participate in the discussion. 

One last thought: the one item you brought up that really looks like a potential bug (as opposed to an architectural decision with unfortunate ramifications) is the consul max_parallel setting not working.  If you're able to reproduce that and can provide debug logs (consul & vault) to show it, please open a new bug and provide the logs.

**Closed by ncabatoff** 2020-05-21 13:43 UTC
