### ISSUE TITLE
POLICY UPDATE RELATED TO USER AT RUNNING TIME

### ISSUE THREAD

**Issue by lagging** [hashicorp/vault#902] opened 2016-01-04 12:18 UTC
i)can user created using tls_authentication and having policy say "oms" can be renewed .

**Comment by jefferai** [comment] 2016-01-04 17:13
I'm sorry, but I'm not clear on the question...can you explain a bit further what it is you are asking?

**Comment by lagging** [comment] 2016-01-05 04:51
If we created user say "xyz"(using tls authentication) and assigned policy "dev" . Now if we want to modify our policy "dev" which is assigned to user "xyz" so what should be our approach.

**Comment by jefferai** [comment] 2016-01-05 14:44
You can modify policies at any time by simply writing the new values to the same policy name. This will have immediate effect on users that have those policies assigned tot hem.

**Comment by lagging** [comment] 2016-01-05 17:07
Okay!!!   i) can we also list the users made ii) and can we view the json or hcl of policies if made using http

**Comment by jefferai** [comment] 2016-01-05 17:18
Hi @lagging 

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Closed by jefferai** 2016-01-05 17:18 UTC
