### ISSUE TITLE
Secret backend based around AWS STS (AssumeRole)

### ISSUE THREAD

**Issue by hashbrowncipher** [hashicorp/vault#800] opened 2015-11-24 19:36 UTC
The existing AWS backend creates a new IAM user and attaches a policy for every credential issued.  Amazon limits the number of IAM users allowed in a given account, and the credentials it issues are permanent.  Vault must later revoke the credentials.

By contrast, AWS STS is designed to enable the issuance of temporary security credentials, with bounded lifetimes that do not need additional maintenance from Vault.  They also interface easily with other forms of configuration management and versioning for AWS IAM policies, because Vault need only know role names, not whole policies.  Lastly, there is a limit on the number of IAM users allowed in an account, but no limit (that I know of) on STS credentials issued.

**Comment by jefferai** [comment] 2015-11-25 16:00
I think this is a duplicate of #295; if not, please let me know and I can re-open.

**Closed by jefferai** 2015-11-25 16:00 UTC

**Comment by hashbrowncipher** [comment] 2015-11-25 17:33
It is, thanks! And sorry for missing #295.
