### ISSUE TITLE
Inmem token generation with custom policies does not work

### ISSUE THREAD

**Issue by roycrowder** [hashicorp/vault#305] opened 2015-06-02 20:30 UTC
```text
╭─ rocrowde  ~
╰─$ ./vault auth 523e5660-85e1-f715-a4ea-3172ec072ac8                                         1 ↵
Successfully authenticated! The policies that are associated
with this token are listed below:

root
╭─ rocrowde  ~
╰─$ vi test.hcl
╭─ rocrowde  ~
╰─$ ./vault policy-write test test.hcl
Policy 'test' written.
╭─ rocrowde  ~
╰─$ ./vault token-create -policy="test"
94bd9d1a-d6b9-1038-b2cf-838bef151162
╭─ rocrowde  ~
╰─$ vault auth 94bd9d1a-d6b9-1038-b2cf-838bef151162
zsh: command not found: vault
╭─ rocrowde  ~
╰─$ ./vault auth 94bd9d1a-d6b9-1038-b2cf-838bef151162                                       127 ↵
Successfully authenticated! The policies that are associated
with this token are listed below:

root
```

HCL file used was copied directly from Getting Started page on vaultproject.io

**Comment by armon** [comment] 2015-06-02 20:50
I think this is actually a bug with Vault CLI. It's using the old token instead of the new one most likely. Please confirm with:

```
$ vault read auth/token/lookup-self
```

**Comment by armon** [comment] 2015-06-02 20:50
I think this is actually a bug with Vault CLI. It's using the old token instead of the new one most likely. Please confirm with:

```
$ vault read auth/token/lookup-self
```

**Comment by roycrowder** [comment] 2015-06-03 03:05
This has to do with using the VAULT_TOKEN environment variable. If you export what the dev server tells you to then even if you auth with a different token it will still tell you you have root privileges. Example below:

╭─ rocrowde  ~
╰─$ export VAULT_ADDR='http://127.0.0.1:8200'
╭─ rocrowde  ~
╰─$ ./vault auth 2c0fe65d-a484-5a70-1004-bb76c8bb62ab
Successfully authenticated! The policies that are associated
with this token are listed below:

root
╭─ rocrowde  ~
╰─$ ./vault policy-write test test.hcl
Policy 'test' written.
╭─ rocrowde  ~
╰─$ ./vault token-create -policy="test"
0d3fe0e7-b3c9-d39a-f04a-94b7fb2d9d5f
╭─ rocrowde  ~
╰─$ ./vault auth 0d3fe0e7-b3c9-d39a-f04a-94b7fb2d9d5f
Successfully authenticated! The policies that are associated
with this token are listed below:

test
╭─ rocrowde  ~
╰─$ export VAULT_TOKEN='2c0fe65d-a484-5a70-1004-bb76c8bb62ab'
╭─ rocrowde  ~
╰─$ ./vault auth 2c0fe65d-a484-5a70-1004-bb76c8bb62ab
Successfully authenticated! The policies that are associated
with this token are listed below:

root
╭─ rocrowde  ~
╰─$ ./vault auth 0d3fe0e7-b3c9-d39a-f04a-94b7fb2d9d5f
Successfully authenticated! The policies that are associated
with this token are listed below:

root
╭─ rocrowde  ~
╰─$ ./vault read auth/token/lookup-self
Key         	Value
display_name	root
id          	2c0fe65d-a484-5a70-1004-bb76c8bb62ab
meta        	<nil>
num_uses    	0
path        	auth/token/root
policies    	[root]

**Comment by armon** [comment] 2015-06-03 08:45
I'm going to close as a duplicate of #195. I think `vault auth` just needs to warn that VAULT_TOKEN is going to take precendence.

**Closed by armon** 2015-06-03 08:45 UTC
Labels: bug, waiting-reply

**Comment by jonbrandenburg** [comment] 2015-06-03 11:31
Can you at least make sure that the tutorials get updated since it is a point of confusion and serves as a mismatch when walking through the documented tutorial.  My co-workers and I each ran into this issue independently while working our way through the tutorials.
