### ISSUE TITLE
Configurable Hashing Method for Audit backends

### ISSUE THREAD

**Issue by MadsRC** [hashicorp/vault#156] opened 2015-05-07 13:08 UTC
The secrets in the logs seems to be hashed with SHA1 (As the documentation mention) - For this very reason, I'd be very paranoid about my logs, as unsalted SHA1 is pretty easy to bruteforce. Would it be possible to change to either SHA512 or maybe PBDKF2 (iterations configurable in the configuration file)

**Comment by mitchellh** [comment] 2015-05-07 15:41
They support a salt which we'll one day make configurable, but your point is still valid. If you look in the `audit/` folder, you'll see we actually laid some groundwork there to make the hashing configurable so we do intend to support other types.

**Comment by armon** [comment] 2015-05-07 18:51
I'm changing the title to better reflect the enhancement

**Comment by jefferai** [comment] 2015-06-08 16:28
Found this while looking to add my own bug.

Please don't use SHA1 as the default. Ideally hashes would be configurable, but in the meantime *please* switch to SHA256 as the default hash. As @MadsRC said, SHA1 is just too easy to brute-force at this point. Having that as the default in something as important as auditing is a bad idea.

**Comment by mitchellh** [comment] 2015-06-08 16:30
We'll make it configurable, but @jefferai "brute forcing" the SHA1 isn't really an issue here because it is still difficult to find the _original_ value. Finding a colliding value is relatively useless, since the original value is likely the secret you need (PG password, AWS key, etc.). A colliding value doesn't tell you much in the context of an audit log.

The purpose of the SHA is to just give you a non-reversible (to the exact value) way to check that a secret you might know is what is in the audit log

**Comment by jefferai** [comment] 2015-06-08 16:44
@mitchellh The problem with SHA1 (and in fact any SHA derivative) is how fast you can compute values. It is far easier to brute-force -- not find collisions, but actually brute-force -- values hashed with SHA than many other functions, especially since you can build FPGAs to do it. This is why, for instance, you should use bcrypt when storing user passwords in a database -- it's slow to compute and memory-intensive, so very costly to build into customized hardware.

My previous post was a bit wrongheaded because I wasn't really thinking about this as an audit log -- as you said, collisions don't really matter (I've been steeped in X509 recently...). However, this actually means getting off SHA is even more important, because these are actual secrets being hashed that are being stored in a log that is expected to persist for a long time -- possibly years.

The default should be changed, but not to a SHA function. The question of course is what to change it to, since many secure hash functions are slow by design.

**Comment by mitchellh** [comment] 2015-06-08 16:46
Yep, this part is very true.

**Comment by jefferai** [comment] 2016-03-14 18:54
These are now HMAC-SHA256 instead of SHA1, so I'm going to close this.

**Closed by jefferai** 2016-03-14 18:54 UTC
Labels: enhancement
