### ISSUE TITLE
Cannot renew token created by an orphan token.

### ISSUE THREAD

**Issue by nemothekid** [hashicorp/vault#1401] opened 2016-05-12 06:40 UTC
Continuing off https://groups.google.com/forum/#!msg/vault-tool/VT-0yUcOfsM/p7fpu1ccAQAJ - the issue I'm having is that I cannot renew a token that was created by another orphaned token.

The full steps to reproduce are:

```bash
$ export VAULT_ADDR="https://vault.channelmeter.com:8200"
$ export VAULT_TOKEN=ROOT_TOKEN
$ curl -s https://raw.githubusercontent.com/ChannelMeter/vault-gatekeeper-mesos/master/gatekeeper-policy.hcl > /tmp/policy.hcl
$ vault policy-write tmp-test-gk /tmp/policy.hcl
$ ./vault token-create -orphan -policy tmp-test-gk
Key            	Value
token          	35d3276f-fa60-dcc2-e5bd-72b0dbb0d2e6
token_accessor 	ed0c560a-e890-c905-bffa-4a5ac4d43f86
token_duration 	2592000
token_renewable	true
token_policies 	[default tmp-test-gk]
$ curl -X POST -H "X-Vault-Token: 35d3276f-fa60-dcc2-e5bd-72b0dbb0d2e6" -d '{"ttl":"1h", "policies":["default"], "num_uses":0}' "${VAULT_ADDR}/v1/auth/token/create-orphan"
{
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": null,
  "warnings": null,
  "auth": {
    "client_token": "e1d21ba8-05a1-1787-1f86-0f14d08e8851",
    "accessor": "81b5412e-31e6-75da-fccb-a41becdd556c",
    "policies": [
      "default"
    ],
    "metadata": null,
    "lease_duration": 3600,
    "renewable": true
  }
}
$ VAULT_TOKEN=e1d21ba8-05a1-1787-1f86-0f14d08e8851 ./vault token-lookup
Key          	Value
accessor     	81b5412e-31e6-75da-fccb-a41becdd556c
creation_time	1.463034909e+09
creation_ttl 	3600
display_name 	token
id           	e1d21ba8-05a1-1787-1f86-0f14d08e8851
meta         	<nil>
num_uses     	0
orphan       	true
path         	auth/token/create
policies     	[default]
role         	
ttl          	0
$ VAULT_TOKEN=e1d21ba8-05a1-1787-1f86-0f14d08e8851 ./vault token-renew
Error renewing token: Error making API request.

URL: PUT https://vault.channelmeter.com:8200/v1/auth/token/renew-self
Code: 500. Errors:

* lease not found or lease is not renewable
```

Note that the token that is unable to be renewed is the orphan token's orphan. The `ROOT_TOKEN`'s orphan can renew just fine.

**Comment by jefferai** [comment] 2016-05-12 16:26
Can you post the contents of policy `tmp-test-gk`?

**Comment by nemothekid** [comment] 2016-05-12 16:29
Sure, it's the same as the file that's downloaded in the curl command.
```
/*
	Add the ability to create orphan tokens with any policy.
*/
path "auth/token/create" {
	capabilities = ["create", "read", "sudo", "update"]
}

path "auth/token/create/*" {
	capabilities = ["create", "read", "sudo", "update"]
}

path "auth/token/create-orphan" {
	capabilities = ["create", "read", "sudo", "update"]
}

// Policy Reading
path "secret/gatekeeper" {
	capabilities = ["read"]
}
```

**Comment by jefferai** [comment] 2016-05-12 17:52
I can't reproduce:

```
$ curl -s https://raw.githubusercontent.com/ChannelMeter/vault-gatekeeper-mesos/master/gatekeeper-policy.hcl > /tmp/policy.hcl
$ vault policy-write tmp-test-gk /tmp/policy.hcl
$ vault token-create -orphan -policy tmp-test-gk
Key             Value
token           49734237-5586-ada8-21e0-115a87001e33
token_accessor  26353d52-c376-ed35-aba6-b28d91a46b71
token_duration  2592000
token_renewable true
token_policies  [default tmp-test-gk]

$ curl -X POST -H "X-Vault-Token: 49734237-5586-ada8-21e0-115a87001e33" -d '{"ttl":"1h", "policies":["default"], "num_uses":0}' "${VAULT_ADDR}/v1/auth/token/create-orphan"
{"lease_id":"","renewable":false,"lease_duration":0,"data":null,"warnings":null,"auth":{"client_token":"5ff5b11d-62d0-e95b-c083-0fcab164454d","accessor":"a52fbee8-0219-245c-4f6a-108d6a576cc6","policies":["default"],"metadata":null,"lease_duration":3600,"renewable":true}}

$ VAULT_TOKEN=5ff5b11d-62d0-e95b-c083-0fcab164454d vault token-lookup
Key                     Value
accessor                a52fbee8-0219-245c-4f6a-108d6a576cc6
creation_time           1463075280
creation_ttl            3600
display_name            token
explicit_max_ttl        0
id                      5ff5b11d-62d0-e95b-c083-0fcab164454d
meta                    <nil>
num_uses                0
orphan                  true
path                    auth/token/create-orphan
policies                [default]
role            
ttl                     3563

$ VAULT_TOKEN=5ff5b11d-62d0-e95b-c083-0fcab164454d vault token-renew
Key             Value
token           5ff5b11d-62d0-e95b-c083-0fcab164454d
token_accessor  a52fbee8-0219-245c-4f6a-108d6a576cc6
token_duration  2591961
token_renewable true
token_policies  [default]
```

Any chance it has to do with you using `./vault` in some commands and `vault` in others? Usually `.` isn't in `PATH`. Is it possible one is newer and the other is old?

**Comment by nemothekid** [comment] 2016-05-12 17:57
Odd, are you using a version other than (or newer than) 0.5.2? I noticed that your ttl value on the orphan token with `vault token-lookup` returns a valid ttl (3563), rather than 0 (which is a bug you fixed here #1306) so maybe this issue has already been fixed on master?

**Comment by jefferai** [comment] 2016-05-12 18:04
I think this is a duplicate of https://github.com/hashicorp/vault/issues/1256

**Comment by nemothekid** [comment] 2016-05-12 22:32
So would you consider this issue fixed? #1256 is closed. It seems that way if the vault version you are testing against doesn't reproduce the same behavior.

**Comment by jefferai** [comment] 2016-05-12 23:06
Hi @nemothekid 

I think so. In my testing I definitely hit this issue in 0.5.2 but did not in `master` and that issue looks like the reason.

**Comment by jefferai** [comment] 2016-05-12 23:07
(Actually, to be clear, I'm not sure it's literally the same issue, but I think that the fix for that issue is what is fixing this too)

**Comment by jefferai** [comment] 2016-05-12 23:07
I'll close it, feel free to ping back if you think it needs to be reopened.

**Closed by jefferai** 2016-05-12 23:07 UTC
