### ISSUE TITLE
App-ID source address restriction broken behind a load balancer

### ISSUE THREAD

**Issue by bkeroackdsc** [hashicorp/vault#834] opened 2015-12-10 21:16 UTC
We have a Vault installation consisting of three Vault servers in HA configuration behind an Elastic Load Balancer in AWS. The healthcheck is configured such that only the active/master Vault server is forwarded traffic from the ELB at any given time.

Since Vault only looks at the source address (not X-Forwarded-For), CIDR block restrictions on App-ID authentication does not work. Vault sees all traffic coming as coming from the ELB subnet (for example, 10.10.34.0/24) and not the actual app server subnets (eg, 10.10.100.0/24).

**Comment by jsok** [comment] 2015-12-10 21:19
This looks like a duplicate of #799 and #291

**Comment by jefferai** [comment] 2015-12-10 21:35
@jsok beat me to it, but yes, closing as a duplicate of the other two issues.

**Closed by jefferai** 2015-12-10 21:35 UTC
