### ISSUE TITLE
Dynamic SSH key expiration causing panic

### ISSUE THREAD

**Issue by eliah-hecht-zocdoc** [hashicorp/vault#1810] opened 2016-08-30 16:01 UTC
I am using Vault 0.6.1 and it is currently panicking as soon as it is unsealed, with this error:

```
panic: interface conversion: interface is json.Number, not float64

goroutine 692 [running]:
panic(0x129d340, 0xc420264300)
        /goroot/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/vault/builtin/logical/ssh.(*backend).secretDynamicKeyRevoke(0xc4202325c0, 0xc4201b7540, 0xc4206e8d80, 0x12f2a80, 0x68f901, 0xc4206e8d80)
        /gopath/src/github.com/hashicorp/vault/builtin/logical/ssh/secret_dynamic_key.go:95 +0x50b
github.com/hashicorp/vault/builtin/logical/ssh.(*backend).(github.com/hashicorp/vault/builtin/logical/ssh.secretDynamicKeyRevoke)-fm(0xc4201b7540, 0xc4206e8d80, 0x0, 0x2, 0xc420466ed0)
        /gopath/src/github.com/hashicorp/vault/builtin/logical/ssh/secret_dynamic_key.go:27 +0x3e
github.com/hashicorp/vault/logical/framework.(*Secret).HandleRevoke(0xc420466ed0, 0xc4201b7540, 0x1460c4e, 0x6, 0xc4206c3b01)
        /gopath/src/github.com/hashicorp/vault/logical/framework/secret.go:86 +0x8b
github.com/hashicorp/vault/logical/framework.(*Backend).handleRevokeRenew(0xc420160540, 0xc4201b7540, 0x1460c4e, 0x6, 0x1)
        /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:407 +0x23d
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc420160540, 0xc4201b7540, 0xc4201b7540, 0xc4206e12a0, 0x1a)
        /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:152 +0x7dd
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc420239230, 0xc4201b7540, 0x40ef00, 0x0, 0x1410000, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:269 +0x748
github.com/hashicorp/vault/vault.(*Router).Route(0xc420239230, 0xc4201b7540, 0x10e6, 0x1280e40, 0xc4206da750)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3a
github.com/hashicorp/vault/vault.(*ExpirationManager).revokeEntry(0xc42023ee40, 0xc4206da750, 0x3f, 0xc4206da750)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:598 +0x22c
github.com/hashicorp/vault/vault.(*ExpirationManager).revokeCommon(0xc42023ee40, 0xc4201d0b00, 0x3f, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:201 +0x351
github.com/hashicorp/vault/vault.(*ExpirationManager).Revoke(0xc42023ee40, 0xc4201d0b00, 0x3f, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:181 +0x10f
github.com/hashicorp/vault/vault.(*ExpirationManager).expireID(0xc42023ee40, 0xc4201d0b00, 0x3f)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:571 +0xe3
github.com/hashicorp/vault/vault.(*ExpirationManager).Restore.func1()
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:153 +0x3f
created by time.goFunc
        /goroot/src/time/sleep.go:154 +0x44
```

Any thoughts on what I can do to help diagnose this? I tried rolling back to 0.6.0 to see if it was a new issue in 0.6.1 but that seemed to cause issues with acquiring the master lock (I'm using a HA configuration with the Consul storage backend).

**Comment by eliah-hecht-zocdoc** [comment] 2016-08-30 17:43
Update: this appears to be a new issue with 0.6.1. I set up a server running 0.6.0 as a test (just using the file storage backend) and it successfully revoked the credential.

**Comment by jefferai** [comment] 2016-08-30 18:25
Duplicate of #1779

**Closed by jefferai** 2016-08-30 18:25 UTC
