### ISSUE TITLE
Don't say "Success!" when a specific field is requested.

### ISSUE THREAD

**Issue by maokt** [hashicorp/vault#21545] opened 2023-07-02 15:54 UTC
**Describe the bug**
vault write outputs a message when asked to output a specific field.

**To Reproduce**
1. Run `vault write -field somefield secret/squirrel foo=hoge`
2. See "Success! Data written to: %s"

**Expected behavior**
Given that the response is empty and I requested a specific field, I am expecting no output.

**Additional context**
It's not particularly serious when writing to a secret because we expect the entire response to be empty so would probably never ask for a field.  But the same behaviour happens when "writing" to one of the endpoints that performs a lookup, such as auth/approle/role/:role_name/secret-id/lookup, where we may or may not get an empty response, and we need to easily distinguish those cases.

**Comment by VioletHynes** [comment] 2023-08-16 19:22
Hi there! I'd like to better understand this problem, as I don't quite understand what the issue is after looking over the issue and PR. `-field` is something that makes sense when reading, but when writing it doesn't, today, seem to output anything but 'success' in any use case I can see. 

e.g.
```
violet@violet-TX54KFJWXM vault % vault secrets enable kv
Success! Enabled the kv secrets engine at: kv/
violet@violet-TX54KFJWXM vault % vault write kv/my-secret foo=bar bar=baz
Success! Data written to: kv/my-secret
violet@violet-TX54KFJWXM vault% vault write -field foo kv/my-secre
t bar=baz2
Success! Data written to: kv/my-secret
```

Are you saying that you'd like the output to be nothing at all? That seems counter to what I'd expect `-field` to do, but admittedly it seems `-field` doesn't seem to affect the response in any situation for KV writes.

If you're simply looking for a silent write option, `-format json` should work:
```
violet@violet-TX54KFJWXM vault % vault write -format json kv/my-secret bar=baz2
violet@violet-TX54KFJWXM vault %
```

However, I fear I'm not actually understanding your core problem.

**Comment by maxb** [comment] 2023-08-17 05:16
An illustration of the example described in OP's initial post would be:
```
$ vault write -field=secret_id_accessor auth/approle/role/foo/secret-id/lookup secret_id=60c4d489-c60e-be58-a94f-7a291d568fe3 
9133f2dc-1945-412b-0b10-172f29c5faa0
$ vault write -field=secret_id_accessor auth/approle/role/foo/secret-id/lookup secret_id=invalid
Success! Data written to: auth/approle/role/foo/secret-id/lookup
```

When the user has indicated by using `-field` they are expecting one value alone suitable for capturing and using in other automation, the CLI should not render an HTTP 204 No Content response into a friendly message intended for human consumption.

**Comment by VioletHynes** [comment] 2023-08-17 14:18
Oh, that's a great demonstration, thanks! I think this makes sense to me. I'm going to re-review the PR and hopefully get it merged.

**Closed** 2023-08-17 15:49 UTC
