### ISSUE TITLE
Identify the vault role creating tokens

### ISSUE THREAD

**Issue by infa-svijayak** [hashicorp/vault#14415] opened 2022-03-09 13:28 UTC
Hello All,
I would like to ask for a feature request with vault. Currently we have close to 2 million active tokens in our vault and the backend of the vault is stored in consul. Due to this the memory consumption of consul is going off the roofs. Currently we are experiencing a memory usage of 35 Gb for each of the consul k8 pods serving as backend for the vault. 

Currently we are able to figure out the reason for increase in memory of consul is because the number of tokens which are created by vault, but there is no way to figure out which vault roles are creating these many tokens via CLI or through the access log. It will be helpful if we can devise a way which will help us in identifying the count of current active tokens based on which role it created either in CLI or log

This is the current scenario of our vault engine
211 vault/logical/d69f0c5f-2b93-8de2-6013-bd7901288cba/packer
1288 vault/logical/e175f97a-a9ef-5dc3-4a90-0a7487a36d4f/certs
19008 vault/logical/b3dd2ec7-a08f-806b-5f64-ec9bc285b21c/certs
707079 vault/logical/df3863b8-d898-35e8-3b2c-6695397bebe8/e84e1f55-1a3e-c4d5-82e4-fb6eb06eb88c
1700541 vault/sys/expire/id
2063914 vault/sys/token/id
2063966 vault/sys/token/accessor

Any help on this will be much appreciated as due to this there are frequent outages in vault and we have to keep on increasing our VM sizes just so that consul can load the kv backend containing vault which is now close to 35 GB

**Comment by swayne275** [comment] 2022-03-09 17:17
Hi!

Are any of the metrics [here](https://www.vaultproject.io/docs/internals/telemetry#token-identity-and-lease-metrics) a useful proxy, specifically `vault.expire.job_manager.queue_length` (or some other `summary` that would have a breakdown)

**Comment by asenyaev** [comment] 2022-03-10 09:15
Hi!

I have almost the same situation.

If I use `system:auth-delegator` for all service accounts and set `enableSecretRotation: true` in helm chart of [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/charts/secrets-store-csi-driver/values.yaml#L200), then I have a lot of tokens inside of Vault (`/vault/data/sys/token`) at some moment. So, 10Gb (default space for PV) can be reached after a week and all services will be down, because they cannot sync secrets and Vault logs show `No left space on device` error.

My situation shows that several secret engines with ~15 secrets can fill disk space in a few days. I also tried to remove `expire` and `token` folders in `/vault/data/sys/token` path, files just creating anyway and no one service is down.

Is there any configuration for removing these tokens after some time (minutes/days)?

**Comment by maxb** [comment] 2022-03-12 19:00
This issue is interesting to me as I've been dealing with a similar issue - though at significantly smaller scale (my normal operational state is ~45000 tokens and the issue is how to understand what's causing spikes of more than +20% above that).

My technique has been to use the Vault API, and I'll explain in case it is useful to you, although with nearly 2 million tokens, I'm not sure if the API will cope:
* LIST `auth/token/accessors/` to get all token accessors. Unfortunately the Vault API does not support pagination, so for you this is going to be a gigantic JSON response if it succeeds, and might fail outright.
* POST `auth/token/lookup-accessor` for every token, to get info about what it is - you want the `display_name` and `meta` from this response

Assuming you're able to gather this data, you'll be able to tell why you have so many tokens.

If the API isn't a solution, another option would be to enable audit logging, if you don't have it already, and look for requests to paths you know will create new tokens. `auth/something/login` and `auth/token/create` and similar are the main ones.

Something else to look into: what lifetime (TTL) are your tokens of various types being assigned? In most cases, tokens should be relatively short lived, so either your tokens are set to last a long time before expiring, or you have a ferociously large volume of requests creating new tokens all the time.

**Comment by maxb** [comment] 2022-03-12 21:02
The `vault.token.count.by_*` metrics from https://www.vaultproject.io/docs/internals/telemetry also look useful.

**Comment by hsimon-hashicorp** [comment] 2023-07-21 20:27
As it has been some time since we've heard more about the problem in this issue, I'm going to go ahead and close it. Please feel free to re-open if the problem persists or open a new issue as needed. Thanks!

**Closed by hsimon-hashicorp** 2023-07-21 20:27 UTC
Labels: enhancement, waiting-for-response, core/token, storage/consul, performance
