### ISSUE TITLE
Vault requires go 1.22.5 to build; found 1.22.2.

### ISSUE THREAD

**Issue by borjaOrtizLlamas** [hashicorp/vault#27894] opened 2024-07-29 15:36 UTC
**Describe the bug**
I am building vault with some patches and i am having this error:  

```
==> Checking that build is using go version >= 1.22.5...
go: downloading go1.22.2 (linux/amd64)
Vault requires go 1.22.5 to build; found 1.22.2.
```

logs: 

```make[1]: Entering directory '/builds/ISE/mirrors/vault/build/vault-1.17.2'
make[2]: Entering directory '/builds/ISE/mirrors/vault/build/vault-1.17.2'
==> Checking that build is using go version >= 1.22.5...
go: downloading go1.22.2 (linux/amd64)
Vault requires go 1.22.5 to build; found 1.22.2.
make[2]: *** [Makefile:266: check-go-version] Error 1
make[2]: Leaving directory '/builds/ISE/mirrors/vault/build/vault-1.17.2'
make[1]: *** [debian/rules:15: override_dh_auto_build] Error 2
make[1]: Leaving directory '/builds/ISE/mirrors/vault/build/vault-1.17.2'
make: *** [debian/rules:8: build] Error 2
```

**To Reproduce**
Build with make 
`
prep: check-go-version clean
`

**Expected behavior**
Finish  the build

**Comment by borjaOrtizLlamas** [comment] 2024-07-30 07:35
i already have it, the problem i found its here 

https://github.com/hashicorp/vault/blob/main/api/auth/aws/go.mod#L5

If i change it to 1.25, it works. Do you think is also my system?

**Comment by hsimon-hashicorp** [comment] 2024-07-30 21:06
> i already have it, the problem i found its here 
> 
> 
> 
> https://github.com/hashicorp/vault/blob/main/api/auth/aws/go.mod#L5
> 
> 
> 
> If i change it to 1.25, it works. Do you think is also my system? 
> 
> 
> 
> 

No, that's pretty clear - thanks for the report! I'll take it back to the team. :)

**Comment by borjaOrtizLlamas** [comment] 2024-07-31 08:01
Tell me if this change pass all tests, unless with the unitary works. Dont know with the conformance.

**Comment by banks** [comment] 2024-07-31 10:56
Hi @borjaOrtizLlamas, I'm trying to understand the issue here - I don't think Go should prevent you building because there is an _older_ toolchain in a submodule. If they all have to be perfectly in sync then ours and many projects release processes are all broken so that would be a bigger issue!

Also, I can build this on the same version of Go as you without issues and so can our CI!

That said, I'm not super familiar with this new `toolchain` stuff so I'm just trying to figure it out from https://go.dev/doc/toolchain

There is says:

> In the standard configuration, the go command uses its own bundled toolchain when that toolchain is at least as new as the go or toolchain lines in the main module or workspace.

Which I think means this should be fine since you have have a version of Go toolchain that is newer it should just use that and be happy.

It seems like Go is downloading the older version to satisfy this `toolchain` command, but it should presumably only use that older version for building that module 🤔 .

It could be that our go version check in Makefile is interacting with this new toolchain behaviour badly and needs a fix, but I'm curious why I and others are not seeing the same thing you are in that case.

Can you confirm whether you have `GOTOOLCHAIN` set in env?

When you said `Build with make` which make target are you using? I can run `prep` and `dev` fine on the same Go version.

You also mentioned patches, can you build `main` without your patches or do you get the same result (just to rule out changes to dependencies etc. caused by your changes)?

**Comment by banks** [comment] 2024-07-31 11:10
Oh I see the logs include `https_proxy=http://itproxy.1and1.org:3128/ make` so presumably that is the command you are seeing cause an issue. Can you confirm whether you are doing that from the root of the repo or just trying to build a specific go module under SDK? It works for me from the root at least.

**Comment by stevendpclark** [comment] 2024-09-09 13:33
Hello @borjaOrtizLlamas, since there hasn't been any follow up on the issue for over a month, I'm going to assume we can close this out without the proposed fixes. 

If I'm incorrect and you are still encountering the issue, please re-open this issue with a follow up to the questions/comments above.

**Closed by stevendpclark** 2024-09-09 13:33 UTC
Labels: waiting-for-response, dependencies
