### ISSUE TITLE
issue when i tried to connect the oci object storage to hashicorp vault helmchart 0.6.0

### ISSUE THREAD

**Issue by joaqquin89** [hashicorp/vault#13122] opened 2021-11-11 16:49 UTC
Hi everyone

i'm writing this post because i have problems when i tried to connect my oci object storage with the hashicorp vault 0.6.0(helmchart).

all started when i noticed that my vault was sealed without reason ... debugging the logs i founded the next message 
![image](https://user-images.githubusercontent.com/16735054/141336193-c51db992-c6a4-4ea3-8ab6-b19ae6c72aee.png)

my subnet has attached the service gateways in the route table (that service gateway should fix the connection problems).

i have the next config in my values

![image](https://user-images.githubusercontent.com/16735054/141336593-bd142797-276b-422b-911b-ebd1f1e27e12.png)

maybe the versions has problems with the object storage ?

regards

**Comment by joaqquin89** [comment] 2021-11-11 16:50
this way of message is very common in my anothers pod

![image](https://user-images.githubusercontent.com/16735054/141336765-5a5096e9-3124-438a-aac4-39d43b7c3db8.png).

i deployed this helmchart as ha cluster

**Comment by hsimon-hashicorp** [comment] 2021-11-12 16:24
Hi @joaqquin89! Unfortunately this isn't much information to go on to allow us to reproduce the issue. Can you check with the bug report issue template and make sure it's all filled out? Reproduction steps, your full Vault configuration (with sensitive information redacted), versions, etc. We'd love to help you out. Thanks! :)

**Comment by hsimon-hashicorp** [comment] 2021-12-10 22:36
Hi @joaqquin89 - wanted to check back in with you on if you were able to provide more information on this. Please let me know - thanks! :)

**Comment by hsimon-hashicorp** [comment] 2021-12-20 21:53
Hi @joaqquin89 - some research I've done on this suggests that this might be an issue with a timeout being hit - for OCI, judging from a related issue I saw, this can be 60s. Here's a support article with more potential information: https://support.hashicorp.com/hc/en-us/articles/4404634420755-Why-am-I-seeing-context-deadline-exceeded-errors
Since it's been a little while since we heard from you regarding this, I'm going to go ahead and close this issue now, but please do feel free to re-open it as needed. :) Thanks!

**Closed by hsimon-hashicorp** 2021-12-20 21:53 UTC
Labels: waiting-for-response, storage/oci, helmchart
