### ISSUE TITLE
vault server -dev Freezes Terminal Window

### ISSUE THREAD

**Issue by jcderose** [hashicorp/vault#710] opened 2015-10-22 00:00 UTC
I'm following the documentation [here](https://vaultproject.io/intro/getting-started/dev-server.html) to initiate a Vault dev server. The `vault server -dev` command freezes my terminal screen with log data:

```
➜  ~  vault server -dev
==> WARNING: Dev mode is enabled!

In this mode, Vault is completely in-memory and unsealed.
Vault is configured to only have a single unseal key. The root
token has already been authenticated with the CLI, so you can
immediately begin using the Vault CLI.

The only step you need to take is to set the following
environment variables:

    export VAULT_ADDR='http://127.0.0.1:8200'

The unseal key and root token are reproduced below in case you
want to seal/unseal the Vault or play with authentication.

Unseal Key: [removed]
Root Token: [removed]

==> Vault server configuration:

         Log Level: info
             Mlock: supported: false, enabled: false
           Backend: inmem
        Listener 1: tcp (addr: "127.0.0.1:8200", tls: "disabled")

==> Vault server started! Log data will stream in below:

2015/10/21 16:43:02 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/10/21 16:43:02 [INFO] core: post-unseal setup starting
2015/10/21 16:43:02 [INFO] core: mounted backend of type generic at logical/75f7963c-0a9e-3cb8-fbe5-c8f98a3a66a8/
2015/10/21 16:43:02 [INFO] core: mounted backend of type cubbyhole at logical/ceebb274-c860-5798-e8db-c625415829ae/
2015/10/21 16:43:02 [INFO] core: mounted backend of type system at sys/
2015/10/21 16:43:02 [INFO] rollback: starting rollback manager
2015/10/21 16:43:02 [INFO] core: post-unseal setup complete
2015/10/21 16:43:02 [INFO] core: root token generated
2015/10/21 16:43:02 [INFO] core: pre-seal teardown starting
2015/10/21 16:43:02 [INFO] rollback: stopping rollback manager
2015/10/21 16:43:02 [INFO] core: pre-seal teardown complete
2015/10/21 16:43:02 [INFO] core: vault is unsealed
2015/10/21 16:43:02 [INFO] core: post-unseal setup starting
2015/10/21 16:43:02 [INFO] core: mounted backend of type generic at logical/75f7963c-0a9e-3cb8-fbe5-c8f98a3a66a8/
2015/10/21 16:43:02 [INFO] core: mounted backend of type cubbyhole at logical/ceebb274-c860-5798-e8db-c625415829ae/
2015/10/21 16:43:02 [INFO] core: mounted backend of type system at sys/
2015/10/21 16:43:02 [INFO] core: post-unseal setup complete
2015/10/21 16:43:02 [INFO] rollback: starting rollback manager
```

If I quit the command or close the terminal window, I cannot connect to Vault. However, if I open a new terminal window, export the VAULT_ADDR value, and run "vault status", I get a successful connection message:
```
➜  ~  vault status
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: false
```

**Comment by jefferai** [comment] 2015-10-22 00:05
Closing as a duplicate of #692, please re-open if you do not think you are seeing the same behavior.

Thanks!

**Comment by jcderose** [comment] 2015-10-22 15:30
Thanks @jefferai ! Any chance we can get that information added to the documentation, to prevent other Vault users from experiencing this headache?

**Comment by jefferai** [comment] 2015-10-22 16:35
Sure. I'll mark this as a documentation fix.

**Comment by jcderose** [comment] 2015-10-22 17:03
Thank you!

**Closed** 2015-10-30 16:48 UTC
Labels: documentation
