### ISSUE TITLE
UI api-explorer display exception

### ISSUE THREAD

**Issue by 2775468731** [hashicorp/vault#24244] opened 2023-11-23 08:47 UTC
**Describe the bug**
UI api-explorer display exception，

**To Reproduce**
1. Accessing vault console
2. Run `api`
3. See error

**Expected behavior**
ui display exception

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.13.2
* Vault CLI Version (retrieve with `vault version`): 1.13.2
* Server Operating System/Architecture: centos 7

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
ui = true
disable_mlock = true

storage "raft" {
   path    = "/opt/vault/raft/"
   node_id = ""
}

listener "tcp" {
  address       = "[::]:8200"
  cluster_address = "[::]:8201"
  tls_disable = "true"
}

api_addr = "http://127.0.0.1:8200"
cluster_addr = "http://127.0.0.1:8201"

```

**Additional context**

error screenshot:
![image](https://github.com/hashicorp/vault/assets/38467223/664b529b-9925-4d5f-8e45-254d46adde2c)

**Comment by 2775468731** [comment] 2023-11-23 08:54
This project uses the vault custom engine and source code deployment. How can I fix it

**Comment by miagilepner** [comment] 2023-11-27 12:57
Hi @2775468731, I am not able to reproduce this UI error on 1.13.2 or any later versions. What browser and version of the browser are you using?

**Comment by Monkeychip** [comment] 2023-11-30 17:05
A related note: the swagger/OpenAPI styling was updated due to a package upgrade. That [change](https://github.com/hashicorp/vault/pull/24035) was backported to 1.14.7.  However, similar to @miagilepner I am unable to reproduce your error.

**Comment by 2775468731** [comment] 2023-12-06 10:08
> Hi @2775468731, I am not able to reproduce this UI error on 1.13.2 or any later versions. What browser and version of the browser are you using?
I have used Google and Edge browsers, and the phenomenon is the same.
I suspect its appearance is related to my use of source code deployment and the use of cloud resource components.

**Comment by hellobontempo** [comment] 2024-05-07 17:05
@2775468731 - is this still an issue on a `1.14.x` version of the Vault UI?

**Comment by hsimon-hashicorp** [comment] 2024-05-13 19:53
Due to the issue age and quiescence, I'm going to go ahead and close it now. Please feel free to re-open as needed, or visit our [Discuss forums](https://discuss.hashicorp.com/c/vault/30) for community support.

**Closed by hsimon-hashicorp** 2024-05-13 19:53 UTC
Labels: ui, waiting-for-response
