### ISSUE TITLE
`vault seal` should work on standbys

### ISSUE THREAD

**Issue by mitchellh** [hashicorp/vault#196] opened 2015-05-13 20:05 UTC
It is currently doing leader redirection, which does exactly not what you expect. :)

**Comment by karel1980** [comment] 2015-06-02 08:59
I took a stab at this by slapping this on the end of http/logical_test.go:TestLogical_StandbyRedirect:
```go
	//// SEAL on standby
	resp = testHttpPut(t, addr2+"/sys/seal", nil)
	testResponseStatus(t, resp, 200) //GH-196, should not be a 307 redirect
```

Unfortunately core2 has a nil tokenStore, so the /sys/seal call fails. Not sure if that's by design because it's Standby or just because of the way the test is created. Any hints?

```
2015/06/02 10:53:23 http: panic serving 127.0.0.1:35240: runtime error: invalid memory address or nil pointer dereference
goroutine 78 [running]:
net/http.func·011()
	/home/karel/.gvm/gos/go1.4/src/net/http/server.go:1130 +0xbb
github.com/hashicorp/vault/vault.(*TokenStore).SaltID(0x0, 0xc2080f64b6, 0x24, 0x0, 0x0)
	/home/karel/.gvm/pkgsets/go1.4/global/src/github.com/hashicorp/vault/vault/token_store.go:249 +0x140
github.com/hashicorp/vault/vault.(*TokenStore).Lookup(0x0, 0xc2080f64b6, 0x24, 0x0, 0x0, 0x0)
	/home/karel/.gvm/pkgsets/go1.4/global/src/github.com/hashicorp/vault/vault/token_store.go:357 +0x1a6
github.com/hashicorp/vault/vault.(*Core).checkToken(0xc20805c780, 0x94d660, 0x5, 0x971cd0, 0x8, 0xc2080f64b6, 0x24, 0x0, 0x0, 0x0)
	/home/karel/.gvm/pkgsets/go1.4/global/src/github.com/hashicorp/vault/vault/core.go:545 +0x1c8
github.com/hashicorp/vault/vault.(*Core).Seal(0xc20805c780, 0xc2080f64b6, 0x24, 0x0, 0x0)
	/home/karel/.gvm/pkgsets/go1.4/global/src/github.com/hashicorp/vault/vault/core.go:927 +0x1ea
github.com/hashicorp/vault/http.func·022(0x7f2bb17e3ba8, 0xc208145cc0, 0xc208146750)
	/home/karel/.gvm/pkgsets/go1.4/global/src/github.com/hashicorp/vault/http/sys_seal.go:25 +0xf5
net/http.HandlerFunc.ServeHTTP(0xc208170460, 0x7f2bb17e3ba8, 0xc208145cc0, 0xc208146750)
	/home/karel/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208134c00, 0x7f2bb17e3ba8, 0xc208145cc0, 0xc208146750)
	/home/karel/.gvm/gos/go1.4/src/net/http/server.go:1541 +0x17d
github.com/hashicorp/vault/http.func·001(0x7f2bb17e3ba8, 0xc208145cc0, 0xc208146750)
	/home/karel/.gvm/pkgsets/go1.4/global/src/github.com/hashicorp/vault/http/help.go:18 +0x128
net/http.HandlerFunc.ServeHTTP(0xc20813c880, 0x7f2bb17e3ba8, 0xc208145cc0, 0xc208146750)
	/home/karel/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208134ba0, 0x7f2bb17e3ba8, 0xc208145cc0, 0xc208146750)
	/home/karel/.gvm/gos/go1.4/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20812e900, 0x7f2bb17e3ba8, 0xc208145cc0, 0xc208146750)
	/home/karel/.gvm/gos/go1.4/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208144780)
	/home/karel/.gvm/gos/go1.4/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/home/karel/.gvm/gos/go1.4/src/net/http/server.go:1751 +0x35e
--- FAIL: TestLogical_StandbyRedirect (0.01s)
	http_test.go:40: err: Put http://127.0.0.1:33231/v1/sys/seal: EOF
```

**Comment by armon** [comment] 2015-06-02 13:43
@karel1980 After thinking about this, it's actually worse than I suspected. The `Seal` operation is privileged and requires a token since it can cause availability issues. The Standby instances cannot easily verify a token, since they have not mounted any of the internals (by design). 

My current thinking is that the standby instances should put the Seal request into a "pendingSeal" queue, and when they become active, they check if any of the those requests were valid (e.g. verify the token) and then automatically seal and step down.

**Comment by iostat** [comment] 2015-11-29 04:54
This just caused me to scratch my head for a good hour or two! Perhaps a note in the HTTP reference would be useful or an appropriate code (501, maybe?) + error message ("Sealing HA Standbys is not supported") for the time being. The current error 500 somewhat conflicts with the 500 that get sent for a missing client token when sealing.

**Comment by jefferai** [comment] 2018-03-14 21:12
This has been fixed for a long time, so closing.

**Closed by jefferai** 2018-03-14 21:12 UTC
Labels: bug, core
