### ISSUE TITLE
Plugin setup problem

### ISSUE THREAD

**Issue by niclarcipretti** [hashicorp/vault#8009] opened 2019-12-11 21:25 UTC
**Describe the bug**
Can't use vault plugins. When I try to execute them, an error occurs.

**To Reproduce**
Steps to reproduce the behavior: (I'll use the oracle plugin as an example)

1. Run vault as a docker container
Dockerfile:

```
FROM vault:1.2.3

COPY instantclient-basic-linux.x64-19.5.0.0.0dbru.zip /vault/oracle/instantclient.zip

COPY vault-plugin-database-oracle /vault/plugins/vault-plugin-database-oracle

COPY config.json /vault/config/config.json

RUN chown -R vault.vault /vault && chmod -R 777 /vault/plugins

ENV OCI_LIB64 /vault/oracle/instantclient_19_5

ENV PATH $PATH:/vault/oracle/instantclient_19_5

ENV VAULT_ADDR http://127.0.0.1:8200

RUN cd /vault/oracle && unzip instantclient.zip && mkdir /etc/ld.so.conf.d && echo /vault/oracle/instantclient_19_5 > /etc/ld.so.conf.d/oracle-instantclient.conf

CMD ["vault", "server", "-config", "/vault/config/config.json"] 
```

with the following config.json:

```
{
   "listener":{
      "tcp":{
         "address":"[::]:8200",                  
         "tls_disable":true
      }
   },
   "storage":{
      "file":{
         "path":"/vault/data"         
      }
   },
   "ui":"true",
   "plugin_directory":"/vault/plugins",
   "disable_mlock": true
}
```
Docker run cmd:

`docker run -d -e SKIP_CHOWN=true --cap-add IPC_LOCK -p 8200:8200 vault:my_tag`

2. Run `vault login`

3. Run `vault write sys/plugins/catalog/database/vault-plugin-database-oracle sha_256=9b1ba434aa0cce9522d8e49171a118148267131bceb694c144208d84f363b8cb command="vault-plugin-database-oracle"`

4. Run `vault write database/config/sigtint plugin_name="vault-plugin-database-oracle" connection_url="<some oracle conn string>" allowed_roles="my-role"`

5. See error 
```
Error writing data to database/config/sigtint: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/sigtint
Code: 400. Errors:

* error creating database object: fork/exec /vault/plugins/vault-plugin-database-oracle: no such file or directory
```
**Expected behavior**
The plugin should be executed correctly.

**Environment:**
Vault version: 1.2.3 (Docker - vault:1.2.3)
Oracle plugin version:0.1.6 (https://github.com/hashicorp/vault-plugin-database-oracle) (downloaded from: https://releases.hashicorp.com/vault-plugin-database-oracle/0.1.6/)

Vault server configuration file(s):

```
{
   "listener":{
      "tcp":{
         "address":"[::]:8200",                  
         "tls_disable":true
      }
   },
   "storage":{
      "file":{
         "path":"/vault/data"         
      }
   },
   "ui":"true",
   "plugin_directory":"/vault/plugins",
   "disable_mlock": true
}
```
I've tested with a custom plugin (made it myself) and the error is the same.

Can anyone help me with that? Am I doing something wrong?

Thanks in advance

NIkao

**Comment by briankassouf** [comment] 2019-12-11 22:11
Hi @niclarcipretti,

This error makes me think that the plugin binary isn't being copied to the plugin directory correctly:

`fork/exec /vault/plugins/vault-plugin-database-oracle: no such file or directory`
 
Can you exec into the docker container and check if the plugin exists on the filesystem?

**Comment by catsby** [comment] 2019-12-11 22:17
Hey @niclarcipretti - I would be interested too if you could reproduce this with the plugin you've built but outside of using Docker, e.g. run vault in dev mode locally and try adding the plugin. Please let us know what you find! Thanks

**Comment by niclarcipretti** [comment] 2019-12-11 22:18
Hi @briankassouf,

Yes, the file exists in the container. And it's permissions are ok too. You can see in my Dockerfile the commands that I used to achieve that.
Any other thoughts? 

Thanks

**Comment by niclarcipretti** [comment] 2019-12-11 22:30
Hi @catsby,

I've tried locally (windows and Linux) already. Same result. I'm guessing this error is not related to the plugin itself. It seems to fail when vault calls the OS to execute the plugin's file. 

Have you used custom plugins successfully lately? Am I missing some step? 

Thanks

**Comment by briankassouf** [comment] 2019-12-11 22:30
Does the plugin have exec permissions? You may need to `chmod +x` it.

**Comment by niclarcipretti** [comment] 2019-12-11 22:34
Sorry @briankassouf, I'm already doing that too, just realized that my Dockerfile up there was not updated. Just did it. Check it out on the description. (in fact, that was my first worry too)

**Comment by briankassouf** [comment] 2019-12-11 22:46
Looks like there may be a few typos on that new line: `vault.vault` -> `vault:vault`, `& &` -> `&&`, and `chmod - R` -> `chmod -R`

**Comment by niclarcipretti** [comment] 2019-12-11 22:49
@briankassouf sorry again. I'm using my phone to reply. The spell checker messed it up.

Cheers

**Comment by briankassouf** [comment] 2019-12-12 00:13
I see, I wasn't sure if the type was in the docker file that you built. I'm able to get the plugin to execute locally, so i suspect it's something with your docker file/setup. I'd recommend exec'ing into the container and poking around to see if there is anything misconfigured.

**Comment by niclarcipretti** [comment] 2019-12-12 01:06
@briankassouf could you please provide me the steps you took to make it work locally so I can try it again here?

Thanks in advance!

**Comment by michelvocks** [comment] 2019-12-12 09:10
Hi @niclarcipretti!

I remember having the same issue in the past. 
The real problem is that the Vault Docker image is based on Alpine Linux which is missing a library (I think it was musl) which is required. You should be able to see the issue by running the `ldd <path-to-plugin>` command inside your Docker image.

I never solved that issue but maybe this thread here might help you: https://stackoverflow.com/questions/53263972/oracle-on-alpine-linux

Cheers,
Michel

**Comment by niclarcipretti** [comment] 2019-12-12 14:11
Hi @michelvocks,

I was suspicious that Alpine could be the culprit too. So, I've invested some time to build my own vault base image, based on oracle's client image.

After some back and forths, I managed to get it running, and now, the error seems to be more comprehensive: 

```
Error writing data to database/config/sigtint: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/sigtint
Code: 400. Errors:

* error creating database object: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

I'll try to recompile the plugin as suggested.

Some further thoughts:
If some 3rd party plugins can't work properly with Alpine, should vault's base image be Alpine exclusive?

Cheers

**Comment by niclarcipretti** [comment] 2019-12-12 17:52
Well, just recompiled the plugin and the result didn't change. I asked the folks from the plugin repo if they tested it against vault's latest version, no answer yet.

I'm running out of ideas here, any help would be appreciated :(

**Comment by briankassouf** [comment] 2019-12-12 18:09
@niclarcipretti Make sure your vault server has trace logging enabled, it should output errors when starting the plugin. I suspect it can't find the dynamic libs

**Comment by briankassouf** [comment] 2019-12-12 18:11
And if that is the issue, try setting `export $LD_LIBRARY_PATH=/vault/oracle/instantclient_19_5`

**Comment by niclarcipretti** [comment] 2019-12-12 18:21
@briankassouf how can I enable the trace logging? A richer log would be very helpful indeed!

Just to update you: I've created my own vault docker base image based on oracle's client image, here it is:

```
FROM store/oracle/database-instantclient:12.2.0.1
# This is the release of Vault to pull in.
ARG VAULT_VERSION=1.3.0

ENV VAULT_ADDR http://127.0.0.1:8200

COPY vault-plugin-database-oracle /vault/plugins/vault-plugin-database-oracle

COPY config.json /vault/config/config.json

# Create a vault user and group first so the IDs get set the same way,
# even as the rest of this may change over time.
RUN groupadd vault && \
    useradd -r -g vault vault

RUN chown -R vault.vault /vault && chmod -R 777 /vault/plugins

# Set up certificates, our base tools, and Vault.
RUN set -eux
RUN     yum -y install ca-certificates gnupg openssl libcap su-exec dumb-init tzdata wget unzip which   
RUN     VAULT_GPGKEY=91A6E7F85D05C65630BEF18951852D87348FFC4C;
RUN mkdir -p /tmp/build
RUN cd /tmp/build
RUN wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip && \
    wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS && \
    wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS.sig
RUN grep vault_${VAULT_VERSION}_linux_amd64.zip vault_${VAULT_VERSION}_SHA256SUMS | sha256sum -c
RUN unzip -d /bin vault_${VAULT_VERSION}_linux_amd64.zip
RUN cd /tmp
RUN rm -rf /tmp/build
RUN rm -rf /root/.gnupg

# /vault/logs is made available to use as a location to store audit logs, if
# desired; /vault/file is made available to use as a location with the file
# storage backend, if desired; the server will be started with /vault/config as
# the configuration directory so you can add additional config files in that
# location.
RUN mkdir -p /vault/logs && \
    mkdir -p /vault/file && \
    mkdir -p /vault/config && \
    chown -R vault:vault /vault

# Expose the logs directory as a volume since there's potentially long-running
# state in there
VOLUME /vault/logs

# Expose the file directory as a volume since there's potentially long-running
# state in there
VOLUME /vault/file

# 8200/tcp is the primary interface that applications use to interact with
# Vault.
EXPOSE 8200

# The entry point script uses dumb-init as the top-level process to reap any
# zombie processes created by Vault sub-processes.
#
# For production derivatives of this container, you shoud add the IPC_LOCK
# capability so that Vault can mlock memory.
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]

# By default you'll get a single-node development server that stores everything
# in RAM and bootstraps itself. Don't use this configuration for production.
CMD ["vault", "server", "-config", "/vault/config/config.json"] 

```
So, I'm guessing all configuration of oracle's client should be ok. Even ldded the plugin to make sure:


```
bash-4.2# ldd vault-plugin-database-oracle
        linux-vdso.so.1 =>  (0x00007fffb0959000)
        libclntsh.so.12.1 => /usr/lib/oracle/12.2/client64/lib/libclntsh.so.12.1 (0x00007f2279461000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2279245000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2278e77000)
        libmql1.so => /usr/lib/oracle/12.2/client64/lib/libmql1.so (0x00007f2278c00000)
        libipc1.so => /usr/lib/oracle/12.2/client64/lib/libipc1.so (0x00007f22787cd000)
        libnnz12.so => /usr/lib/oracle/12.2/client64/lib/libnnz12.so (0x00007f2278084000)
        libons.so => /usr/lib/oracle/12.2/client64/lib/libons.so (0x00007f2277e36000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f2277c32000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f2277930000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f2277716000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f227750e000)
        libaio.so.1 => /lib64/libaio.so.1 (0x00007f227730c000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f22770f3000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f227cf06000)
        libclntshcore.so.12.1 => /usr/lib/oracle/12.2/client64/lib/libclntshcore.so.12.1 (0x00007f2276b25000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f227690f000)
```
I've used this image to recompile the plugin too (installed go, pkg-config, bla, bla, bla).

My main concern now is if vault-oracle-plugin was tested with the latest versions of vault. Cause the error message seems to be RPC related.

Cheers

**Comment by briankassouf** [comment] 2019-12-12 18:25
You can add log level to your vault config: https://www.vaultproject.io/docs/configuration/index.html#log_level

And yes, I was able to get it to run yesterday with the latest version of vault

Let's see what the trace logs output

**Comment by niclarcipretti** [comment] 2019-12-12 19:22
@briankassouf did it, here's what I found out with trace loggin enabled when I ran the already built plugin (downloaded from vault-oracle-plugin repo):

```
error while loading shared libraries: libclntsh.so.19.1: cannot open shared object file: No such file or directory
2019-12-12T19:07:53.222Z [DEBUG] secrets.database.database_c47b61e8.vault-plugin-database-oracle: plugin process exited: path=/vault/plugins/vault-plugin-database-oracle pid=90 error="exit status 127"
```
Figures! I'm using oracle client 12 in this new image. 

So, I've tried with my custom built plugin (built with the right oracle cli/sdk version) , and trace log showed nothing this time.

Sorry to bother you again with this, but, could you please provide me the steps you took to make the plugin work for you?

Thanks

**Comment by briankassouf** [comment] 2019-12-12 19:38
Yeah the API addr needs to be set so plugins know how to call back to vault to get the TLS config https://www.vaultproject.io/docs/configuration/index.html#api_addr

**Comment by briankassouf** [comment] 2019-12-12 19:39
But if you've gotten that far it seems the binary was able to find the correct shared libraries, and was executed successfully!

**Comment by niclarcipretti** [comment] 2019-12-13 13:28
Yes @briankassouf! Your're right! I successfuly executed the plugin. I've created an issue in the plugin's repo and asked if they could improve their docs. I'll reference this issue here for historic purpose only: https://github.com/hashicorp/vault-plugin-database-oracle/issues/24

I guess we could improve Vault's docs too, informing that it's docker image is Alpine based and may not work with some plugins. Other thing that could be improved is the plugin execution error messages, just reflecting the OS message is not enough. The error I was getting was "file not found" but the real error was "glibc libraries not found/oci version is wrong" lol. I'll go a little further. Vault could execute "ldd" when you try to register a plugin just to check if it is a valid executable. That would prevent a lot of inconvinience for vault's users. Does this makes any sense to you?

Let me know if you need an extra hand to address this.

Cheers.

**Comment by michelvocks** [comment] 2020-01-03 10:39
Hi @niclarcipretti!

I'm going to close this issue since I saw you've opened a separate PR at https://github.com/hashicorp/vault-plugin-database-oracle/pull/25.

Cheers,
Michel

**Closed by michelvocks** 2020-01-03 10:39 UTC
Labels: core/plugin, waiting-for-response
