### ISSUE TITLE
Cert auth method path UI/API vs CLI

### ISSUE THREAD

**Issue by datadude816** [hashicorp/vault#11540] opened 2021-05-05 17:12 UTC
**Describe the bug**
There is a discrepancy on what paths can be used with the Cert auth method.

The UI will allow you to set a custom path and the API will allow you to use that path.

That path is unable to be used via the API

**To Reproduce**
1. Log into the UI
2. Select `Access
3. Select "Enable new method"
4. Select "TLS Certificates" and next
5. type in your desired path and select options
6. enable the method
7. back out to auth methods and select your new method
8. Create your certificate
9. Use certificate via API

**Expected behavior**
I expect good documentation. I expect consistent behavior across all three access methods UI,API and CLI.

I expect to be able to set paths especially for cert auth so that there can be some organization of the certificates in the system. This would also allow RBAC on what certs get what ACL applied.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.6.2
* Vault CLI Version (retrieve with `vault version`): 1.6.2
* Server Operating System/Architecture: Cent 8

Vault server configuration file(s): N/A

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**
![vault_cert_path](https://user-images.githubusercontent.com/57238962/117181353-fbb4ff80-ad89-11eb-875d-28052a2d43cc.png)
![method enabled](https://user-images.githubusercontent.com/57238962/117181392-0a031b80-ad8a-11eb-96d1-95fc93d44cbd.png)

`$ vault write auth/cert/certs/test0/file1 displayname=file1 policy=test certificate=@machine.pem
Error writing data to auth/cert/certs/test0/file1: Error making API request.

URL: PUT https://active.vault.service.consul.domain.us:8200/v1/auth/cert/certs/test0/file1
Code: 404. Errors:

* 1 error occurred:
	* unsupported path

`

**Comment by datadude816** [comment] 2021-05-05 18:07
The below works the path is a little strange to work with but...some more documentation or changes should be made.

vault write **auth/cert/certs/test0/certs/file1** policies=test certificate=@machine.pem

**Comment by divyapola5** [comment] 2022-02-17 21:27
Hey @datadude816  

I tried to reproduce the issue and after going through the documentation for cert auth method, 
this is my observation:
 
**CLI:**
The command used to create a certificate via CLI is 

vault write **mount-path**/certs/**display-name** display_name=web policies=web,prod certificate=@web-cert.pem ttl=3600

For example, I enabled a new cert auth method at path 'auth/foo/'
<img width="1004" alt="Screen Shot 2022-02-17 at 2 35 28 PM" src="https://user-images.githubusercontent.com/87338962/154566396-f0174ab2-cc59-484e-8d6e-851e2207d074.png">


and I created a new certificate using the command:
%vault write **auth/foo**/certs/file1 policies=test certificate=@web-cert.pem displayname=file1
Success! Data written to: auth/foo/certs/file1

In this case the mount-path is 'auth/foo' ( which is the custom path that I set above) and display-name is 'file1'

**API:**
I was able to use the same path via API as well using the command:
POST	**/auth/foo**/certs/:name

'auth/foo' in above POST command is the mount path.



In your case it is mounted at 'auth/cert/certs/test0', and so the command used in your Success attempt (**auth/cert/certs/test0**/certs/file1) is the right way to use it and so it worked.

Please note that the TLS Certificate Auth Method (API) documentation states that 
"This documentation assumes the TLS Certificate method is mounted at the /auth/cert path in Vault.", and all the
examples used in the documentation reflect the same path.

As the documentation clearly states about the mount path and the same custom path could be used consistently across UI, CLI and API,  I think we can close this issue. Please let us know if you have any other thoughts. Thanks.

**Comment by sgmiller** [comment] 2022-03-07 15:45
Going to mark this one closed for now, as it seems to be as designed.  Feel free to reopen though if you're still having trouble!

**Closed by sgmiller** 2022-03-07 15:45 UTC
Labels: ui, waiting-for-response, cryptosec
