### ISSUE TITLE
Vault leaks credentials when erroring on "verifying connection"

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/vault#4084] opened 2018-03-06 20:34 UTC
**Environment:**
```
Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

**Vault Config File:**

```
backend "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 1
}

telemetry {
  statsd_address   = "127.0.0.1:8126"
  disable_hostname = true
}
```

**Expected Behavior:**

Do not output credentials on error creating a mount.

**Actual Behavior:**

```
[production] time="2018-03-06T17:54:47Z" level=fatal msg="Error making API request.
[production] 
[production] URL: PUT http://active.vault.service.consul:8200/v1/db-mysql/config/default
[production] Code: 400. Errors:
[production] 
[production] * error creating database object: error verifying connection: parse postgresql://user:password@some-host:5432/database?timezone=utc: net/url: invalid userinfo" 
```

> Note: the credentials actually have valid info.

**Steps to Reproduce:**

Setup a connection that will cause a `verifying connection` error, and the parsed output will have the credentials.

**Important Factoids:**

I _think_ the invalid userinfo is because I have a `]` in the password. Thats the only thing I can think of that would break, as this worked just fine in our previous version.

We started seeing this after an upgrade from 0.8.4 to 0.9.3. This doesn't appear to affect any of our other mounts.

We're seeing this error when we apply mounts via `hashi-helper`.

**Comment by jefferai** [comment] 2018-03-07 05:08
Duplicate of #3976 (we received reports via security@ and are addressing there).

**Closed by jefferai** 2018-03-07 05:08 UTC
