### ISSUE TITLE
Dynamic ssh key revoke errors

### ISSUE THREAD

**Issue by nyxcharon** [hashicorp/vault#1870] opened 2016-09-09 15:09 UTC
When using Vault 0.6.1 I get an error message when exiting a machine using the ssh dynamic key type:
```
Error revoking the key: Put http://<ip>:8200/v1/sys/revoke/ssh/creds/dynamic_key_role/2bcb2262-5ac9-0c89-fe8f-262438e688e9: EOF
```

On the server side, i get this dump:
```
  2016-09-09 14:48:44.871997 I | http: panic serving <ip>:54060: interface conversion: interface is json.Number, not float64
 goroutine 11627 [running]:
 net/http.(*conn).serve.func1(0xc42014e180)
         /goroot/src/net/http/server.go:1491 +0x12a
 panic(0x129d340, 0xc4205ab140)
         /goroot/src/runtime/panic.go:458 +0x243
 github.com/hashicorp/vault/builtin/logical/ssh.(*backend).secretDynamicKeyRevoke(0xc42025f250, 0xc420468fa0, 0xc42067d180, 0x12f2a80, 0x68f901, 0xc42067d180)
         /gopath/src/github.com/hashicorp/vault/builtin/logical/ssh/secret_dynamic_key.go:95 +0x50b
 github.com/hashicorp/vault/builtin/logical/ssh.(*backend).(github.com/hashicorp/vault/builtin/logical/ssh.secretDynamicKeyRevoke)-fm(0xc420468fa0, 0xc42067d180, 0x0, 0x2, 0xc4204eef00)
         /gopath/src/github.com/hashicorp/vault/builtin/logical/ssh/secret_dynamic_key.go:27 +0x3e
 github.com/hashicorp/vault/logical/framework.(*Secret).HandleRevoke(0xc4204eef00, 0xc420468fa0, 0x1460c4e, 0x6, 0xc4205dfa01)
         /gopath/src/github.com/hashicorp/vault/logical/framework/secret.go:86 +0x8b
 github.com/hashicorp/vault/logical/framework.(*Backend).handleRevokeRenew(0xc42008c780, 0xc420468fa0, 0x1460c4e, 0x6, 0x1)
         /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:407 +0x23d
 github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc42008c780, 0xc420468fa0, 0xc420468fa0, 0xc4206aadc0, 0x1a)
         /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:152 +0x7dd
 github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc42023d320, 0xc420468fa0, 0x40ef00, 0x0, 0x1410000, 0x0, 0x0)
         /gopath/src/github.com/hashicorp/vault/vault/router.go:269 +0x748
 github.com/hashicorp/vault/vault.(*Router).Route(0xc42023d320, 0xc420468fa0, 0x10e5, 0x1280e40, 0xc420069c20)
         /gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3a
 github.com/hashicorp/vault/vault.(*ExpirationManager).revokeEntry(0xc42022d140, 0xc420069c20, 0x3f, 0xc420069c20)
         /gopath/src/github.com/hashicorp/vault/vault/expiration.go:598 +0x22c
 github.com/hashicorp/vault/vault.(*ExpirationManager).revokeCommon(0xc42022d140, 0xc4208cecd3, 0x3f, 0x0, 0x0, 0x0)
         /gopath/src/github.com/hashicorp/vault/vault/expiration.go:201 +0x351
 github.com/hashicorp/vault/vault.(*ExpirationManager).Revoke(0xc42022d140, 0xc4208cecd3, 0x3f, 0x0, 0x0)
         /gopath/src/github.com/hashicorp/vault/vault/expiration.go:181 +0x10f
 github.com/hashicorp/vault/vault.(*SystemBackend).handleRevoke(0xc420237df0, 0xc420468dc0, 0xc42067cd80, 0x6000103, 0x0, 0xffffffffffffffff)
         /gopath/src/github.com/hashicorp/vault/vault/logical_system.go:1015 +0xdd
 github.com/hashicorp/vault/vault.(*SystemBackend).(github.com/hashicorp/vault/vault.handleRevoke)-fm(0xc420468dc0, 0xc42067cd80, 0x0, 0x6, 0xc4201b1678)
         /gopath/src/github.com/hashicorp/vault/vault/logical_system.go:304 +0x3e
 github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc42008c480, 0xc420468dc0, 0xc420468dc0, 0xc4208cecc8, 0x4a)
         /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:206 +0x42e
 github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc42023d320, 0xc420468dc0, 0x0, 0x0, 0x6000000, 0x0, 0x0)
         /gopath/src/github.com/hashicorp/vault/vault/router.go:269 +0x748
 github.com/hashicorp/vault/vault.(*Router).Route(0xc42023d320, 0xc420468dc0, 0xc420468dc0, 0x0, 0x0)
         /gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3a
 github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc42004d180, 0xc420468dc0, 0x0, 0x0, 0x0, 0x0)
         /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:160 +0xb90
 github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc42004d180, 0xc420468dc0, 0x0, 0x0, 0x0)
         /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:42 +0x687
 github.com/hashicorp/vault/http.request(0xc42004d180, 0x1ced5c0, 0xc4204665b0, 0xc420503ef0, 0xc420468dc0, 0x0, 0x0)
         /gopath/src/github.com/hashicorp/vault/http/handler.go:161 +0x39
 github.com/hashicorp/vault/http.handleLogical.func1(0x1ced5c0, 0xc4204665b0, 0xc420503ef0)
         /gopath/src/github.com/hashicorp/vault/http/logical.go:110 +0x10e
 net/http.HandlerFunc.ServeHTTP(0xc420248b40, 0x1ced5c0, 0xc4204665b0, 0xc420503ef0)
         /goroot/src/net/http/server.go:1726 +0x44
 github.com/hashicorp/vault/http.handleRequestForwarding.func1(0x1ced5c0, 0xc4204665b0, 0xc420503ef0)
         /gopath/src/github.com/hashicorp/vault/http/handler.go:128 +0x696
 net/http.HandlerFunc.ServeHTTP(0xc420248b60, 0x1ced5c0, 0xc4204665b0, 0xc420503ef0)
         /goroot/src/net/http/server.go:1726 +0x44
 net/http.(*ServeMux).ServeHTTP(0xc42023cd50, 0x1ced5c0, 0xc4204665b0, 0xc420503ef0)
         /goroot/src/net/http/server.go:2022 +0x7f
 github.com/hashicorp/vault/http.handleHelpHandler.func1(0x1ced5c0, 0xc4204665b0, 0xc420503ef0)
         /gopath/src/github.com/hashicorp/vault/http/help.go:18 +0xd8
 net/http.HandlerFunc.ServeHTTP(0xc420248c00, 0x1ced5c0, 0xc4204665b0, 0xc420503ef0)
         /goroot/src/net/http/server.go:1726 +0x44
 net/http.serverHandler.ServeHTTP(0xc420240300, 0x1ced5c0, 0xc4204665b0, 0xc420503ef0)
         /goroot/src/net/http/server.go:2202 +0x7d
 net/http.(*conn).serve(0xc42014e180, 0x1cee6c0, 0xc4205aa940)
         /goroot/src/net/http/server.go:1579 +0x4b7
 created by net/http.(*Server).Serve
         /goroot/src/net/http/server.go:2293 +0x44d
```

This is a fresh install, consul is the backend. 
I have been using vault in production with the exact same setup (roles, etc) for a while. I do not have this issue with 0.6.0 in production, though production has been through multiple upgrades and not a fresh install. 

Let me know if you need any more information.

**Comment by vishalnayak** [comment] 2016-09-09 20:15
Duplicate of #1779

**Closed by vishalnayak** 2016-09-09 20:15 UTC
