### ISSUE TITLE
High Vault server CPU usage caused by client agent.template.server error

### ISSUE THREAD

**Issue by BruXy** [hashicorp/vault#22789] opened 2023-09-06 14:32 UTC
**Describe the bug**

Vault server will have high CPU usage because it is being hammered by requests from clients. When checking vault-agent on clients nodes, I am getting this error:

```
Aug 31 13:28:33 int-es7-master-0bdd2c3acfd60c618 vault[5865]: 2023-08-31T13:28:33.833Z [ERROR] agent.template.server: template server error: error="error rendering \"/opt/vault/client/templates/es7_cert.tmpl\" => \"/etc/elasticsearch/certs/cert.crt\": failed reading file: open /etc/elasticsearch/certs/cert.crt: permission denied"
```
Restarting of vault-agent will help. From the observation, I found that certificates that are going to expire
in a few days (around 5), will not be renewed and this error will occur.  I was checking permissions, but both
files are 644 for vault-agent user/group (640 for template) and I can read them when trying to sudo to the user (no additional ACLs and SELinux flags are `system_u:object_r:etc_t:s0`).

Also, we did update a while ago from the older version v1.6.3 is okay, but the newer v1.13.2 is the one with the problem.

**To Reproduce**

1. Having PKI issue certificates with 30 days expiration.
2.  Wait until they will be sooner to expire.

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):

```
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    5
Threshold                3
Version                  1.13.2
Build Date               2023-04-25T13:02:50Z
Storage Type             dynamodb
Cluster Name             us-east-1
Cluster ID               f87e0b83-17c7-ac4c-9892-05fcf0a5a407
HA Enabled               true
HA Cluster               https://172.18.0.161:8201
HA Mode                  active
Active Since             2023-06-07T19:52:00.235059959Z
```

* Vault CLI Version (retrieve with `vault version`): `Vault v1.13.2 (b9b773f1628260423e6cc9745531fd903cae853f), built 2023-04-25T13:02:50Z`

* Server Operating System/Architecture:  `Linux 5.10.184-175.749.amzn2.x86_64 #1 SMP Wed Jul 12 18:40:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Vault server configuration file(s):

```hcl
exit_after_auth = false

vault {
  address = "https://active.vault.service.consul:8200"
}

auto_auth {
  method "aws" {
    mount_path = "auth/aws"
    config = {
      type = "iam"
      role = "storage"
    }
  }
}

cache {
  use_auto_auth_token = true
}

listener "tcp" {
  address = "127.0.0.1:8100"
  tls_disable = true
}
template {
  source          = "/opt/vault/client/templates/filebeat_cert.tmpl"
  destination     = "/etc/filebeat/certs/cert.crt"
  left_delimiter  = "[["
  right_delimiter = "]]"
}
template {
  source          = "/opt/vault/client/templates/filebeat_certkey.tmpl"
  destination     = "/etc/filebeat/certs/cert.key"
  command         = "/bin/bash -c 'sudo /bin/systemctl restart filebeat || true'"
  left_delimiter  = "[["
  right_delimiter = "]]"
}
template {
  source          = "/opt/vault/client/templates/es7_cert.tmpl"
  destination     = "/etc/elasticsearch/certs/cert.crt"
  left_delimiter  = "[["
  right_delimiter = "]]"
}
template {
  source          = "/opt/vault/client/templates/es7_certkey.tmpl"
  destination     = "/etc/elasticsearch/certs/cert.key"
  left_delimiter  = "[["
  right_delimiter = "]]"
}
```

**Comment by VioletHynes** [comment] 2024-02-13 19:44
I believe this is a duplicate of https://github.com/hashicorp/vault/issues/12566, as this seems to be the same issue. The good news is that this bug fix is planned for our next sprint of work! I'll try and make sure we report back when this is fixed.

**Closed** 2024-02-20 19:43 UTC
Labels: agent
