### ISSUE TITLE
login - panic: assignment to entry in nil map (0.11.4)

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/vault#5640] opened 2018-10-29 20:33 UTC
With `0.11.4` on Linux AMD64, running:

```
vault login
```

Crashes with:

```
root@dae9a269aed0:/tmp# vault login
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/hashicorp/vault/command.(*LoginCommand).Run(0xc00009e230, 0xc000096010, 0x0, 0x0, 0xc00000b820)
	/gopath/src/github.com/hashicorp/vault/command/login.go:255 +0xdee
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc0004ef7c0, 0xc0004ef7c0, 0xc00000bbe0, 0xc0006341e0)
	/gopath/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x207
github.com/hashicorp/vault/command.RunCustom(0xc000096010, 0x1, 0x1, 0xc000143b30, 0x0)
	/gopath/src/github.com/hashicorp/vault/command/main.go:170 +0x74a
github.com/hashicorp/vault/command.Run(0xc000096010, 0x1, 0x1, 0xc000080058)
	/gopath/src/github.com/hashicorp/vault/command/main.go:81 +0x48
main.main()
	/gopath/src/github.com/hashicorp/vault/main.go:10 +0x62
```

Reverting to version `0.11.3` `vault login` works as expected.

Configuring is simply:

```hcl
storage "file" {
  path = "/tmp/vault-data"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = true
}
```

**Comment by chrishoffman** [comment] 2018-10-29 20:41
Duplicate of #5602

**Closed by chrishoffman** 2018-10-29 20:41 UTC

**Comment by mesaugat** [comment] 2018-10-30 02:05
The issue was fixed 5 days ago but no sign of a release yet. Isn't this critical functionality?

**Comment by jefferai** [comment] 2018-10-30 02:14
You can simply use 0.11.3 instead; this is a client side only issue.

**Comment by mesaugat** [comment] 2018-10-30 02:54
I've been using 0.11.3, thanks! Even though this is a client only issue I was hoping for a release.
