### ISSUE TITLE
Regenerate master key?

### ISSUE THREAD

**Issue by sebastiang** [hashicorp/vault#180] opened 2015-05-09 20:16 UTC
Is it possible to rotate the master key, i.e. to distribute a new set of partial keys to operators? It seems good practice to rotate this key just as any other key.

**Comment by armon** [comment] 2015-05-11 17:55
@sebastiang This is not yet possible, but its in the 0.2 roadmap!

**Comment by armon** [comment] 2015-05-11 18:00
Closing as duplicate of #129

**Closed by armon** 2015-05-11 18:00 UTC
Labels: question
