### ISSUE TITLE
Encrypt tokens in cookie and in headers.

### ISSUE THREAD

**Issue by naunga** [hashicorp/vault#231] opened 2015-05-19 22:06 UTC
If the host where the vault server is running were to be compromised then it could be that the TLS cert and key that vault is using would be compromised as well.

In which case an OpenSSL server could be setup to intercept traffic to the vault server, reap tokens & keys, and even forward requests on to the real vault server and route the responses back to the requestor or send fake responses back to the server. 

For example a request to seal was made or revoke a token could be intercepted and kept from vault, but the requestor could be sent a legitimate looking response and believe that the request went through.

Seems sensible to either require the tokens be encrypted or some kind of handshaking take place between the clients and the vault server to ensure that client is talking to the vault server, and not an imposter.

**Comment by armon** [comment] 2015-05-19 22:49
@naunga To really implement this, effectively we would be running TLS within TLS. If we want confidentiality of traffic and authenticity of the peer, those are the promises that we get via TLS. 

The problem is that that nested TLS has the same issue as the outer TLS, which is if the host running Vault is compromised, you will probably leak that nested layer as well.

I'm not sure I see a clear answer to this problem, and nested TLS seems to create more problems than it solves. Open to feedback however!

**Comment by naunga** [comment] 2015-05-20 01:31
Yep that makes perfect sense, and I don't have (at present) a great solution (otherwise I'd have sent a pull request). 

I can think of schemes until the cows come home...

- Each token could actually be an encrypted string that is salted with one of the unseal keys.

- The server could examine things like iptables' rules for ports being forwarded away from its listening port. 

- SSH-style host fingerprinting. So that a client has a unique fingerprint, and that fingerprint is checked before the response is sent. 

Ideas are easy. Good solutions are another. 

Thanks for the response.

**Comment by armon** [comment] 2015-06-18 22:47
I'm closing this as the current answer is that TLS should be used.

**Closed by armon** 2015-06-18 22:47 UTC
Labels: core, thinking
