### ISSUE TITLE
Is there any Rest API in Vault which can give me directly value of the field in HashiCorp Vault?

### ISSUE THREAD

**Issue by ksupriyasingh** [hashicorp/vault#5450] opened 2018-10-03 05:33 UTC
I have stored some data using this API http://localhost:8200/v1/secret/email in vault, now when i do GET i get the below json as a response {
    "request_id": "69d74243-682c-9999-af34-ff84b2aadb43",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 2764800,
    "data": {
        "smtp.Password": "20111995",
        "smtp.Port": "587",
        "smtp.Server": "smtp.gmail.com",
        "smtp.Username": "ksuingh"
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}

Now my requirement is to get the data separately For example if i query with 'smtp.Password' i should get only its value '20111995' not the other data. So i want to know is there any Rest API available in Vault which i can use for my requirement.

**Comment by jefferai** [comment] 2018-10-03 13:12
Duplicate of #2421.

**Closed by jefferai** 2018-10-03 13:12 UTC
