### ISSUE TITLE
Feature Proposal: Simple Delegation w/ required_parameters

### ISSUE THREAD

**Issue by tallpauley** [hashicorp/vault#3065] opened 2017-07-26 19:25 UTC
I want the ability to give access to a group of users to create their own policies and auth backends like **approle** but restrict the which paths these policies can address. I have a simple idea that I think solves this use case (albeit not optimally) with a little addition to Vault policy policy definitions.

If there was a fine-grained path parameter **required_params**, we could force a new, say **approle** to have certain policies which would restrict access. These mandatory policies (using the fact that **deny** trumps *allow*) would enable higher-level admins to delegate policy creation and assignment, but "sandbox" delegates to subtractive policies that the higher-level admins define.

The policy for the delegate would contain the following path rule, where `dev_team` would be a restrictive policy that has **deny** statements for all paths that the group shouldn't be able to access (defined by the higher-level admins).
```
path "auth/approle/*" {
  capabilities = ["create"]
  required_parameters = {
    "roles" = ["dev_team"]
  }
}
```

I'm ignoring the fact that roles is defined in CSV string, so maybe the field would be something like *required_parameters_csv*?

The issue I see with this approach is that the **deny** ACLs defined by the higher-level admin must be comprehensive, since the users can make any role with any ACL they want. It would be better if you could "mask" or "restrict" the ACLs that the delegate defines with another policy that only allows certain paths for that group. Also, is the Vault team working on delegation, or if not where is it on the roadmap?

**Comment by tallpauley** [comment] 2017-07-26 19:48
The problem is exactly as stated in this comment:
https://groups.google.com/d/msg/vault-tool/lqLgiBV5dd0/YzJzvN_CDQAJ

I see the lack of policy management delegation as a big deal for these reasons:
1) ability to create policies and auth backends and associate the two is basically root access. No admin alone should have this kind of power. Even the top-most admins should not be able to see certain secrets without generating a root token as a group.
2) it's bottleneck that requires there to be "elite" admins who create policies whenever a lower-level admin just wants to say allow a CI/CD job to access a subset of the secrets he/she can already access.

**Comment by jefferai** [comment] 2017-07-27 15:01
Duplicate of #1043

**Closed by jefferai** 2017-07-27 15:01 UTC
