### ISSUE TITLE
Listing issued PKI certs

### ISSUE THREAD

**Issue by hexedpackets** [hashicorp/vault#1472] opened 2016-05-29 15:46 UTC
Currently it's only possible to retrieve a cert in the PKI backend if you know the serial. It would be useful to have the ability to list certs - for my use case in particular, I'd like to list non-expired certs issued by a given CA in Vault.

**Comment by vishalnayak** [comment] 2016-05-29 16:18
Duplicate of #1466

**Closed by vishalnayak** 2016-05-29 16:18 UTC
