### ISSUE TITLE
Add parameter for Object Identifier (OID) SANs to `/pki/issue/:role` API

### ISSUE THREAD

**Issue by mattupstate** [hashicorp/vault#2587] opened 2017-04-11 20:52 UTC
Probably a very specific use case here, but I happen to use an open source plugin for ElasticSearch that enables SSL over HTTP and transport protocols called [Search Guard](https://floragunn.com/searchguard/). One of the requirements for the plugin is that it requires certificates to include an "Object Identifier" (OID) SANs entry. More info [here](https://github.com/floragunncom/search-guard-docs/blob/master/architecture.md#client--and-server-certificates). I would be indebted if Vault had a parameter to issue certs with this type of SANs.

**Comment by jefferai** [comment] 2017-04-13 17:20
Duplicate of #2289

**Closed by jefferai** 2017-04-13 17:20 UTC
