### ISSUE TITLE
Vault arm http runtime error

### ISSUE THREAD

**Issue by chmod750** [hashicorp/vault#11246] opened 2021-03-31 09:09 UTC
**Describe the bug**
Vault version 1.7.0, 1.7.0.rc1 and 1.7.0.rc2 for ARM generate an http runtime error at vault initialization.

**To Reproduce**
1. Deploy vault binary on RaspberryPi.
2. Run `vault operator init` or through the web user interface
3. See error
```
Mar 31 10:57:34 domus vault[7958]: ==> Vault server started! Log data will stream in below:
Mar 31 10:57:34 domus vault[7958]: 2021-03-31T10:57:34.645+0200 [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
Mar 31 10:57:34 domus vault[7958]: 2021-03-31T10:57:34.646+0200 [WARN]  storage.consul: appending trailing forward slash to path
Mar 31 10:57:34 domus vault[7958]: 2021-03-31T10:57:34.648+0200 [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
Mar 31 10:57:34 domus consul[7848]:     2021-03-31T10:57:34.910+0200 [INFO]  agent: Synced service: service=vault:192.168.86.10:8200
Mar 31 10:57:34 domus consul[7848]:     2021-03-31T10:57:34.926+0200 [INFO]  agent: Synced check: check=vault:192.168.86.10:8200:vault-sealed-check
Mar 31 10:57:39 domus vault[7958]: 2021-03-31T10:57:39.350+0200 [INFO]  core: security barrier not initialized
Mar 31 10:57:39 domus vault[7958]: 2021-03-31T10:57:39.698+0200 [INFO]  core: security barrier not initialized
Mar 31 10:57:39 domus vault[7958]: 2021-03-31T10:57:39.700+0200 [INFO]  core: security barrier not initialized
Mar 31 10:57:39 domus vault[7958]: 2021-03-31T10:57:39.702+0200 [INFO]  core: seal configuration missing, not initialized
Mar 31 10:57:39 domus vault[7958]: 2021-03-31T10:57:39.746+0200 [INFO]  core: security barrier not initialized
Mar 31 10:57:39 domus vault[7958]: 2021-03-31T10:57:39.747+0200 [INFO]  core: security barrier not initialized
Mar 31 10:57:39 domus vault[7958]: 2021-03-31T10:57:39.748+0200 [INFO]  core: seal configuration missing, not initialized
Mar 31 10:57:44 domus vault[7958]: 2021-03-31T10:57:44.223+0200 [INFO]  core: security barrier not initialized
Mar 31 10:57:44 domus vault[7958]: 2021-03-31T10:57:44.245+0200 [INFO]  http: panic serving 192.168.86.2:44286: runtime error: invalid memory address or nil pointer dereference
Mar 31 10:57:44 domus vault[7958]: goroutine 66 [running]:
Mar 31 10:57:44 domus vault[7958]: net/http.(*conn).serve.func1(0x8da5800)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:1801 +0xf0
Mar 31 10:57:44 domus vault[7958]: panic(0x3804748, 0x6d63700)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/runtime/panic.go:975 +0x47c
Mar 31 10:57:44 domus vault[7958]: runtime/internal/atomic.goXadd64(0x8cb53fc, 0x1, 0x0, 0x1, 0x4748f30)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/vendor/go.uber.org/atomic.(*Int64).Add(...)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/vendor/go.uber.org/atomic/atomic.go:94
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/vault.(*AESGCMBarrier).encryptTracked(0x8cb53b0, 0x3f1a02a, 0xb, 0x1, 0x4748f30, 0x8cd27e0, 0x8dbe800, 0x72, 0x80, 0x8f12dc0, ...)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:1126 +0xc8
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/vault.(*AESGCMBarrier).persistKeyring(0x8cb53b0, 0x4748ed0, 0x8d8a000, 0x90121e0, 0x0, 0x0)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:254 +0x338
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/vault.(*AESGCMBarrier).Initialize(0x8cb53b0, 0x4748ed0, 0x8d8a000, 0x90ec7a0, 0x20, 0x20, 0x90ec7c0, 0x20, 0x20, 0x470f838, ...)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:182 +0x1e0
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/vault.(*Core).Initialize(0x8cb6c00, 0x4748ed0, 0x8d8a000, 0x92f7a8c, 0x0, 0x0, 0x0)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/vault/init.go:284 +0x58c
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/http.handleSysInitPut(0x8cb6c00, 0x4746ab0, 0x94fe1e0, 0x8cc6b80)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/http/sys_init.go:67 +0x17c
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/http.handleSysInit.func1(0x4746ab0, 0x94fe1e0, 0x8cc6b80)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/http/sys_init.go:18 +0x88
Mar 31 10:57:44 domus vault[7958]: net/http.HandlerFunc.ServeHTTP(0x8c0ed98, 0x4746ab0, 0x94fe1e0, 0x8cc6b80)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:2042 +0x34
Mar 31 10:57:44 domus vault[7958]: net/http.(*ServeMux).ServeHTTP(0x9173b30, 0x4746ab0, 0x94fe1e0, 0x8cc6b80)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:2417 +0x16c
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/http.wrapHelpHandler.func1(0x4746ab0, 0x94fe1e0, 0x8cc6b80)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/http/help.go:24 +0x144
Mar 31 10:57:44 domus vault[7958]: net/http.HandlerFunc.ServeHTTP(0x9177ef0, 0x4746ab0, 0x94fe1e0, 0x8cc6b80)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:2042 +0x34
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/http.wrapCORSHandler.func1(0x4746ab0, 0x94fe1e0, 0x8cc6b80)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/http/cors.go:29 +0x738
Mar 31 10:57:44 domus vault[7958]: net/http.HandlerFunc.ServeHTTP(0x9177f00, 0x4746ab0, 0x94fe1e0, 0x8cc6b80)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:2042 +0x34
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/http.rateLimitQuotaWrapping.func1(0x4746ab0, 0x94fe1e0, 0x8cc6b80)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/http/util.go:98 +0x7e0
Mar 31 10:57:44 domus vault[7958]: net/http.HandlerFunc.ServeHTTP(0x9177f10, 0x4746ab0, 0x94fe1e0, 0x8cc6b80)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:2042 +0x34
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x4746ab0, 0x94fe1e0, 0x8cc6a80)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/http/handler.go:323 +0x3dc
Mar 31 10:57:44 domus vault[7958]: net/http.HandlerFunc.ServeHTTP(0x90f9600, 0x4746ab0, 0x94fe1e0, 0x8cc6a80)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:2042 +0x34
Mar 31 10:57:44 domus vault[7958]: github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp.PrintablePathCheckHandler.func1(0x4746ab0, 0x94fe1e0, 0x8cc6a80)
Mar 31 10:57:44 domus vault[7958]:         /gopath/src/github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp/handlers.go:42 +0xa4
Mar 31 10:57:44 domus vault[7958]: net/http.HandlerFunc.ServeHTTP(0x9177f20, 0x4746ab0, 0x94fe1e0, 0x8cc6a80)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:2042 +0x34
Mar 31 10:57:44 domus vault[7958]: net/http.serverHandler.ServeHTTP(0x954bb90, 0x4746ab0, 0x94fe1e0, 0x8cc6a80)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:2843 +0x88
Mar 31 10:57:44 domus vault[7958]: net/http.(*conn).serve(0x8da5800, 0x4748eb0, 0x8f30380)
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:1925 +0x7d0
Mar 31 10:57:44 domus vault[7958]: created by net/http.(*Server).Serve
Mar 31 10:57:44 domus vault[7958]:         /goroot/src/net/http/server.go:2969 +0x2d0
```

**Expected behavior**
A proper vault initialization.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.0, 1.7.0.rc1, 1.7.0.rc2
* Vault CLI Version (retrieve with `vault version`): 1.7.0, 1.7.0.rc1, 1.7.0.rc2
* Server Operating System/Architecture: ARM

**Comment by ncabatoff** [comment] 2021-03-31 16:26
Hi @chmod750,

Thanks for reporting this!  As it's a duplicate of #11197 I'm going to close it.  There'll be a fix in the next point release.

**Closed by ncabatoff** 2021-03-31 16:26 UTC
