### ISSUE TITLE
Vault not recognising it's been uninitialised

### ISSUE THREAD

**Issue by richard-hulm** [hashicorp/vault#598] opened 2015-09-08 14:01 UTC
Hi Guys,

We're running Vault in HA mode with consul as a backend.

As part of one of our testing environments, we've been completely resetting vault by sealing it, wiping consul and then re-initializing it.

However, occasionally one of the instances will fail to recognise that consul has been wiped - still saying it's been initialised until we restart the service, which is not ideal.

Is there a better way of completely clearing vault that we missed? Ideally without a restart. 

Otherwise, is this something that can be included in a future release? Just something like checking the back-end before it says it's initalised would improve our workflow

Cheers,

**Comment by jefferai** [comment] 2015-09-08 14:41
Generally speaking it's not nice to wipe a stateful server's backing store while it's running  :-)

That said, you say it usually works. Have you noticed a pattern for when it doesn't work... specifically whether that node is or isn't the leader before sealing? Without looking at the code I can imagine a scenario where that might happen if the node was the leader.

**Comment by richard-hulm** [comment] 2015-09-08 14:48
Quite right - and we don't do this in production, it's just a convenient way of clearing the data between testing runs. As I said, we seal the vault before we wipe it, so it's never going to be making any more writes or (I would of imagined) accessing the backend at all while it's sealed (except for any unseal requests)

I think you might be right in that everytime it's happened, the node was the leader at the time. It's only happened a couple of times recently, so can't give much more info but will keep an eye on it and let you know if anything more identifiable comes up.

**Comment by armon** [comment] 2015-09-08 16:05
This is likely caused by the read cache we use. We flush the cache when going into standby or becoming a leader, but during active operation it would make sense that the leader gets borked.

**Comment by jefferai** [comment] 2018-03-14 21:53
Closing as it's from wiping storage under Vault.

**Closed by jefferai** 2018-03-14 21:53 UTC
