### ISSUE TITLE
vault API return !(NOVERB)

### ISSUE THREAD

**Issue by shsjshentao** [hashicorp/vault#4204] opened 2018-03-27 07:42 UTC
[root@**** bin]# vault read -tls-skip-verify -field=value ******
TEST%
[root@**** bin]# echo `vault read -tls-skip-verify -field=value ******`
TEST%!(NOVERB)
[root@**** bin]# vault read -tls-skip-verify -format=json ******  | jq -r .data.value
TEST%
[root@**** bin]# echo `vault read -tls-skip-verify -format=json ******   | jq -r .data.value`
TEST%

only use "-field" and then use shell will cause this problem

**Comment by jefferai** [comment] 2018-03-27 13:01
Please provide more context here. I don't understand what you're trying to show. Understanding the data that was stored and being read would help.

**Comment by joelthompson** [comment] 2018-03-27 13:33
What version of Vault are you using? This looks to be a duplicate of #4005 which was fixed in, I believe, 0.9.4.

**Comment by shsjshentao** [comment] 2018-03-28 05:18
v0.9.3

**Closed** 2018-03-28 05:33 UTC
