### ISSUE TITLE
changelog is missing 1.14.x 

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/vault#22032] opened 2023-07-24 14:45 UTC
The 1.14.0 [download/release page](https://developer.hashicorp.com/vault/downloads)[1] links to the [CHANGELOG.md](https://github.com/hashicorp/vault/blob/v1.14.0/CHANGELOG.md)[2] file in this repo, but that file only contains changes through 1.13.2, with the last update in April. More specifically, mid-June's 1.14.x release is entirely absent from the changelog.

Don't believe this is an issue with an incorrect link, just that the CHANGELOG updates were overlooked.

I thought I read some of the 1.14 highlights so I believe at the very least a 1.14 summary exists somewhere, maybe in an HCP email, but can't find them now.

[1] https://developer.hashicorp.com/vault/downloads 
[2] https://github.com/hashicorp/vault/blob/v1.14.0/CHANGELOG.md

**Comment by cwchristerw** [comment] 2023-07-24 23:05
You can find latest CHANGELOG.md always from main branch.
https://raw.githubusercontent.com/hashicorp/vault/main/CHANGELOG.md

**Comment by rjhornsby** [comment] 2023-07-25 02:21
> You can find latest CHANGELOG.md always from main branch.

Ah, thanks. That's the doc I was looking for. Maybe the changelog file got updated after the 1.14 tag was created, and so the changes never made it to where they were expected to land at the commit pointed to by `v1.14.0`

**Comment by cwchristerw** [comment] 2023-07-25 18:04
I can confirm that only includes past releases when looking CHANGELOG.md in specific release tag like v1.14.0 it will not include v1.14.0 in CHANGELOG.md.

**Comment by peteski22** [comment] 2023-07-28 09:49
Thanks for reporting this @rjhornsby, I'm going to take a look into it as it does seem slightly confusing to be given a link to a changelog that doesn't have changes for that particular release in it. 

You can find the changelog notes here too: https://github.com/hashicorp/vault/releases/tag/v1.14.1, or for any specific tag, which hopefully will help. 

I'll drop an update once I figure this out, it might just be that this was a one-off and will be fixed going forward. 😄

**Comment by peteski22** [comment] 2023-07-28 14:19
I believe this is related to our process for generating changelogs. 

It seems (to me) that we pull all the relevant changes from our release branches to generate the changelog, but it's stored in `main` now and not 'regenerated' in each release branch. 

So the solution seems to be that we should update the changelog URL on https://developer.hashicorp.com/vault/downloads to send folks to the right place. I'll look into that.

**Comment by VioletHynes** [comment] 2023-08-08 18:04
Hey! Thanks for raising this. We flagged the right channels internally and got this fixed. Our pages now direct you to `/releases/tag/v${version}`, e.g. https://github.com/hashicorp/vault/releases/tag/v1.14.1.

Closing this, but feel free to open a new issue if you find something new. Thanks a bunch for bringing this to our attention.

**Closed by VioletHynes** 2023-08-08 18:04 UTC
Labels: docs, bug, reproduced
