### ISSUE TITLE
KV: auto delete secrets after date x

### ISSUE THREAD

**Issue by bor-tso** [hashicorp/vault#6256] opened 2019-02-19 06:31 UTC
**Is your feature request related to a problem? Please describe.**
Due to the GDPR it is required to delete personal data after a certain time.

**Describe the solution you'd like**
I would like to have a auto delete function where all KV secret versions (not the whole secret!), older than a specified time range (older than a year for example), are automatically deleted. I guess this could be something to set as metadata?

**Describe alternatives you've considered**
None

**Explain any additional use-cases**
Cleanup 

**Additional context**

**Comment by briankassouf** [comment] 2019-02-19 16:47
Duplicate of #6061

**Closed by briankassouf** 2019-02-19 16:47 UTC

**Comment by briankassouf** [comment] 2019-02-19 16:49
And #6184
