### ISSUE TITLE
Panic from S3 Backend

### ISSUE THREAD

**Issue by deverton** [hashicorp/vault#2779] opened 2017-05-29 22:51 UTC
Not sure exactly what triggered this but the leader in our 0.7.2 Vault cluster just crashed.  Please see https://gist.github.com/deverton/adb37b4bb5491bd5b03bed4f7000713a for full stack trace.

Our setup is three nodes in a cluster with Consul for the HA backend and S3 for the storage. It looks like the node that had the panic was the leader at the time. Another node took over as leader within 30 seconds so that worked.

**Comment by jefferai** [comment] 2017-05-29 23:18
It looks like the S3 library from the official AWS SDK is either giving us a page that doesn't exist or giving us a key that doesn't exist. It's unclear whether the issue is with our code or the lib, but we should be able to avoid panicking here.

**Comment by jefferai** [comment] 2017-06-05 15:02
Should be fixed by 2785

**Closed by jefferai** 2017-06-05 15:02 UTC
