### ISSUE TITLE
Vault PKI no longer can issue certificates as root CA

### ISSUE THREAD

**Issue by sprutner** [hashicorp/vault#2685] opened 2017-05-06 00:12 UTC
**previously erroneously reported as intermediate CA
Vault Version 0.7.0 and also still persists when upgraded to 0.7.1

I now run into an issue when trying to issue certificates using:

```
vault write pki/issue/my-web-site common_name=test.mywebsite.com
```

I just get this error 

```
Code: 500. Errors:

* 1 error occurred:

* Error fetching CA certificate: stored CA information not able to be parsed
```

I'm not sure what's going on here. After some sleuthing it seems some people suggest the root CA might have been overridden? Unfortunately I can't even find docs on how to verify that myself by trying to read the root certs.

I've issued several certs already before, and hope to keep using vault as a PKI. I have two roles that I have been using to issue certs for two domains, all descendant from the root vault CA I set up.

Here's full syslog for vault. some noise there that I don't think is related but I left it in. I don't see any log activity when I try to run the command

```
May  6 00:05:47 ip-10-104-21-203 systemd[1]: vault.service: Dependency After=vault.service dropped
May  6 00:05:47 ip-10-104-21-203 systemd[1]: Starting vault server...
May  6 00:05:47 ip-10-104-21-203 systemd[1]: Started vault server.
May  6 00:05:54 ip-10-104-21-203 vault[1433]: ==> Vault server configuration:
May  6 00:05:54 ip-10-104-21-203 vault[1433]:               HA Storage: consul
May  6 00:05:54 ip-10-104-21-203 vault[1433]:                      Cgo: disabled
May  6 00:05:54 ip-10-104-21-203 vault[1433]:          Cluster Address: https://xx.xx.xx.xx:8201
May  6 00:05:54 ip-10-104-21-203 vault[1433]:               Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "enabled")
May  6 00:05:54 ip-10-104-21-203 vault[1433]:               Listener 2: tcp (addr: "10.104.21.203:8200", cluster address: "10.104.21.203:8201", tls: "enabled")
May  6 00:05:54 ip-10-104-21-203 vault[1433]:               Listener 3: tcp (addr: "10.104.21.203:1867", cluster address: "10.104.21.203:1868", tls: "enabled")
May  6 00:05:54 ip-10-104-21-203 vault[1433]:                Log Level: info
May  6 00:05:54 ip-10-104-21-203 vault[1433]:                    Mlock: supported: true, enabled: true
May  6 00:05:54 ip-10-104-21-203 vault[1433]:         Redirect Address: http://xx.xx.xx.xx:8200
May  6 00:05:54 ip-10-104-21-203 vault[1433]:                  Storage: consul
May  6 00:05:54 ip-10-104-21-203 vault[1433]:                  Version: Vault v0.7.1
May  6 00:05:54 ip-10-104-21-203 vault[1433]:              Version Sha: 1767ced3a336aee9dxsbce7f4f0ad652ff44e8ddab
May  6 00:05:54 ip-10-104-21-203 vault[1433]: ==> Vault server started! Log data will stream in below:
May  6 00:05:54 ip-10-104-21-203 vault[1433]: 2017/05/06 00:05:53.384874 [WARN ] physical/consul: appending trailing forward slash to path
May  6 00:05:54 ip-10-104-21-203 vault[1433]: 2017/05/06 00:05:53.385546 [WARN ] physical/consul: appending trailing forward slash to path
May  6 00:05:54 ip-10-104-21-203 consul[1376]:     2017/05/06 00:05:54 [INFO] agent: Synced service 'vault:10.104.21.203:8200'
May  6 00:05:54 ip-10-104-21-203 consul[1376]:     2017/05/06 00:05:54 [INFO] agent: Synced check 'vault:10.104.21.203:8200:vault-sealed-check'
May  6 00:06:01 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:01 http: TLS handshake error from 10.104.20.66:64741: EOF
May  6 00:06:02 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:02 http: TLS handshake error from 10.104.21.37:27658: EOF
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.452506 [INFO ] core: vault is unsealed
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.453022 [INFO ] core: entering standby mode
May  6 00:06:07 ip-10-104-21-203 consul[1376]:     2017/05/06 00:06:07 [INFO] agent: Synced check 'vault:10.104.21.203:8200:vault-sealed-check'
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.486236 [INFO ] core: acquired lock, enabling active operation
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.543484 [INFO ] core: post-unseal setup starting
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.546747 [INFO ] core: loaded wrapping token key
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.555154 [INFO ] core: successfully mounted backend: type=generic path=secret/
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.555607 [INFO ] core: successfully mounted backend: type=system path=sys/
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.555859 [INFO ] core: successfully mounted backend: type=consul path=consul/
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.556380 [INFO ] core: successfully mounted backend: type=pki path=pki/
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.556665 [INFO ] core: successfully mounted backend: type=aws path=aws/
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.556893 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.558762 [INFO ] rollback: starting rollback manager
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.575226 [INFO ] expiration: restoring leases
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.614820 [INFO ] expire: leases restored: restored_lease_count=16
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.622888 [INFO ] core: post-unseal setup complete
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.623196 [INFO ] core/startClusterListener: starting listener: listener_address=127.0.0.1:8201
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.623439 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=127.0.0.1:8201
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.623642 [INFO ] core/startClusterListener: starting listener: listener_address=10.104.21.203:8201
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.623846 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=10.104.21.203:8201
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.624035 [INFO ] core/startClusterListener: starting listener: listener_address=10.104.21.203:1868
May  6 00:06:07 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:07.624238 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=10.104.21.203:1868
May  6 00:06:07 ip-10-104-21-203 consul[1376]:     2017/05/06 00:06:07 [INFO] agent: Synced service 'vault:10.104.21.203:8200'
May  6 00:06:07 ip-10-104-21-203 consul[1376]:     2017/05/06 00:06:07 [INFO] agent: Synced check 'vault:10.104.21.203:8200:vault-sealed-check'
May  6 00:06:12 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:12.616719 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/08ef2f77-b6f7-752b-bdd5-00a8dc9ad138 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:06:12 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:12.617027 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/85ab62a8-49fc-17ab-852a-820ae2a3c78a error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:06:12 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:12.622263 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d2f4f096-d5a6-b399-768d-842959f67e9f error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:06:12 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:12.622585 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d964c2ed-b3b9-34ba-8dde-187b0d657101 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:06:12 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:12.622800 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/ebe225f6-e3d4-5df1-1dc6-a94f021a2c84 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:06:16 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:16 http: TLS handshake error from 10.104.20.66:64749: EOF
May  6 00:06:17 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:17 http: TLS handshake error from 10.104.21.37:27680: EOF
May  6 00:06:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:22.620492 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/85ab62a8-49fc-17ab-852a-820ae2a3c78a error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: ACL not found)
May  6 00:06:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:22.621237 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/08ef2f77-b6f7-752b-bdd5-00a8dc9ad138 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: ACL not found)
May  6 00:06:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:22.626374 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d2f4f096-d5a6-b399-768d-842959f67e9f error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:06:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:22.627164 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d964c2ed-b3b9-34ba-8dde-187b0d657101 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:06:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:22.627843 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/ebe225f6-e3d4-5df1-1dc6-a94f021a2c84 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:06:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:42.624747 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/85ab62a8-49fc-17ab-852a-820ae2a3c78a error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:06:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:42.625500 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/08ef2f77-b6f7-752b-bdd5-00a8dc9ad138 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:06:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:42.629103 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d2f4f096-d5a6-b399-768d-842959f67e9f error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: ACL not found)
May  6 00:06:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:42.629838 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d964c2ed-b3b9-34ba-8dde-187b0d657101 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: ACL not found)
May  6 00:06:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:06:42.630554 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/ebe225f6-e3d4-5df1-1dc6-a94f021a2c84 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: ACL not found)
May  6 00:07:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:07:22.629155 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/85ab62a8-49fc-17ab-852a-820ae2a3c78a error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:07:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:07:22.630703 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/08ef2f77-b6f7-752b-bdd5-00a8dc9ad138 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:07:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:07:22.633282 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d2f4f096-d5a6-b399-768d-842959f67e9f error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:07:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:07:22.634809 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/ebe225f6-e3d4-5df1-1dc6-a94f021a2c84 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:07:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:07:22.635521 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d964c2ed-b3b9-34ba-8dde-187b0d657101 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:08:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:08:42.633924 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/85ab62a8-49fc-17ab-852a-820ae2a3c78a error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:08:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:08:42.634898 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/08ef2f77-b6f7-752b-bdd5-00a8dc9ad138 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:08:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:08:42.637171 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d2f4f096-d5a6-b399-768d-842959f67e9f error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:08:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:08:42.638112 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/ebe225f6-e3d4-5df1-1dc6-a94f021a2c84 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:08:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:08:42.639034 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d964c2ed-b3b9-34ba-8dde-187b0d657101 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:11:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:11:22.637404 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/85ab62a8-49fc-17ab-852a-820ae2a3c78a error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: ACL not found)
May  6 00:11:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:11:22.638520 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/08ef2f77-b6f7-752b-bdd5-00a8dc9ad138 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: ACL not found)
May  6 00:11:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:11:22.642755 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d2f4f096-d5a6-b399-768d-842959f67e9f error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:11:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:11:22.643422 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/ebe225f6-e3d4-5df1-1dc6-a94f021a2c84 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:11:22 ip-10-104-21-203 vault[1433]: 2017/05/06 00:11:22.644150 [ERROR] expire: failed to revoke lease: lease_id=consul/creds/readonly/d964c2ed-b3b9-34ba-8dde-187b0d657101 error=failed to revoke entry: resp:(*logical.Response)(nil) err:Unexpected response code: 403 (rpc error: rpc error: ACL not found)
May  6 00:16:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:16:42.637624 [ERROR] expire: maximum revoke attempts reached: lease_id=consul/creds/readonly/85ab62a8-49fc-17ab-852a-820ae2a3c78a
May  6 00:16:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:16:42.638713 [ERROR] expire: maximum revoke attempts reached: lease_id=consul/creds/readonly/08ef2f77-b6f7-752b-bdd5-00a8dc9ad138
May  6 00:16:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:16:42.642925 [ERROR] expire: maximum revoke attempts reached: lease_id=consul/creds/readonly/d2f4f096-d5a6-b399-768d-842959f67e9f
May  6 00:16:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:16:42.643564 [ERROR] expire: maximum revoke attempts reached: lease_id=consul/creds/readonly/ebe225f6-e3d4-5df1-1dc6-a94f021a2c84
May  6 00:16:42 ip-10-104-21-203 vault[1433]: 2017/05/06 00:16:42.644287 [ERROR] expire: maximum revoke attempts reached: lease_id=consul/creds/readonly/d964c2ed-b3b9-34ba-8dde-187b0d657101
```

**Comment by jefferai** [comment] 2017-05-06 12:54
Hi there,

The first thing to do is figure out your ACL errors -- those are coming from the storage layer and until we know your storage is behaving there isn't much point in looking at other Vault errors as all sorts of things can go wrong.

It seems like your ACL token for Consul is invalid. If you just upgraded Consul you may want to look at the ACL guide as I think 0.8 also changed some things there.

Regarding the CA issue, first thing is to see if it persists after your storage is fixed. With working storage, the only cause we've ever seen for that error so far are people who generated a new intermediate key but did not yet install a signed cert from the generated CSR.

**Comment by sprutner** [comment] 2017-05-08 17:40
Hey Jeff,

That issue is resolved, but the same error still persists. Logs below.

```
May  8 08:22:27 ip-10-104-21-131 systemd[1]: Started vault server.
May  8 08:22:27 ip-10-104-21-131 vault[6457]: ==> Vault server configuration:
May  8 08:22:27 ip-10-104-21-131 vault[6457]:               HA Storage: consul
May  8 08:22:27 ip-10-104-21-131 vault[6457]:                      Cgo: disabled
May  8 08:22:27 ip-10-104-21-131 vault[6457]:          Cluster Address: https://10.104.21.131:8201
May  8 08:22:27 ip-10-104-21-131 vault[6457]:               Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "enabled")
May  8 08:22:27 ip-10-104-21-131 vault[6457]:               Listener 2: tcp (addr: "10.104.21.131:8200", cluster address: "10.104.21.131:8201", tls: "enabled")
May  8 08:22:27 ip-10-104-21-131 vault[6457]:               Listener 3: tcp (addr: "10.104.21.131:1867", cluster address: "10.104.21.131:1868", tls: "enabled")
May  8 08:22:27 ip-10-104-21-131 vault[6457]:                Log Level: info
May  8 08:22:27 ip-10-104-21-131 vault[6457]:                    Mlock: supported: true, enabled: true
May  8 08:22:27 ip-10-104-21-131 vault[6457]:         Redirect Address: http://10.104.21.131:8200
May  8 08:22:27 ip-10-104-21-131 vault[6457]:                  Storage: consul
May  8 08:22:27 ip-10-104-21-131 vault[6457]:                  Version: Vault v0.7.1
May  8 08:22:27 ip-10-104-21-131 vault[6457]:              Version Sha: 1767ced3a336aee9dbce7f4f0ad652ff44e8ddab
May  8 08:22:27 ip-10-104-21-131 vault[6457]: ==> Vault server started! Log data will stream in below:
May  8 08:22:27 ip-10-104-21-131 vault[6457]: 2017/05/08 08:22:27.501158 [WARN ] physical/consul: appending trailing forward slash to path
May  8 08:22:27 ip-10-104-21-131 vault[6457]: 2017/05/08 08:22:27.501194 [WARN ] physical/consul: appending trailing forward slash to path
May  8 08:22:27 ip-10-104-21-131 consul[1417]:     2017/05/08 08:22:27 [INFO] agent: Synced service 'vault:10.104.21.131:8200'
May  8 08:22:27 ip-10-104-21-131 consul[1417]:     2017/05/08 08:22:27 [INFO] agent: Synced check 'vault:10.104.21.131:8200:vault-sealed-check'
May  8 08:22:33 ip-10-104-21-131 vault[6457]: 2017/05/08 08:22:33.202049 [INFO ] core: vault is unsealed
May  8 08:22:33 ip-10-104-21-131 vault[6457]: 2017/05/08 08:22:33.202569 [INFO ] core: entering standby mode
May  8 08:22:33 ip-10-104-21-131 consul[1417]:     2017/05/08 08:22:33 [INFO] agent: Synced check 'vault:10.104.21.131:8200:vault-sealed-check'
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.181973 [INFO ] core: acquired lock, enabling active operation
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.225114 [INFO ] core: post-unseal setup starting
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.227299 [INFO ] core: loaded wrapping token key
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.231102 [INFO ] core: successfully mounted backend: type=generic path=secret/
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.231397 [INFO ] core: successfully mounted backend: type=system path=sys/
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.231605 [INFO ] core: successfully mounted backend: type=consul path=consul/
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.231835 [INFO ] core: successfully mounted backend: type=pki path=pki/
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.232031 [INFO ] core: successfully mounted backend: type=aws path=aws/
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.232213 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.232534 [INFO ] rollback: starting rollback manager
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.243249 [INFO ] expiration: restoring leases
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.267364 [INFO ] expire: leases restored: restored_lease_count=10
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.272551 [INFO ] core: post-unseal setup complete
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.272924 [INFO ] core/startClusterListener: starting listener: listener_address=127.0.0.1:8201
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.273139 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=127.0.0.1:8201
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.273319 [INFO ] core/startClusterListener: starting listener: listener_address=10.104.21.131:8201
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.273522 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=10.104.21.131:8201
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.273717 [INFO ] core/startClusterListener: starting listener: listener_address=10.104.21.131:1868
May  8 08:24:23 ip-10-104-21-131 vault[6457]: 2017/05/08 08:24:23.273927 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=10.104.21.131:1868
May  8 08:24:23 ip-10-104-21-131 consul[1417]:     2017/05/08 08:24:23 [INFO] agent: Synced service 'vault:10.104.21.131:8200'
May  8 08:24:23 ip-10-104-21-131 consul[1417]:     2017/05/08 08:24:23 [INFO] agent: Synced check 'vault:10.104.21.131:8200:vault-sealed-check'
```

```
Code: 500. Errors:

* 1 error occurred:

* Error fetching CA certificate: stored CA information not able to be parsed
```

**Comment by jefferai** [comment] 2017-05-08 17:45
Hi @sprutner ,

As I said earlier, the only cause we've ever seen for that error so far are people who generated a new intermediate key but did not yet install a signed cert from the generated CSR. Are you sure that nothing called the intermediate generate function?

**Comment by sprutner** [comment] 2017-05-08 20:44
@jefferai This isn't the case for me, I was issuing certs from the intermediate CA without issue recently, and there's nothing else with access at the moment. I have plaintext of the intermediate keys and certs used as well.

**Comment by jefferai** [comment] 2017-05-08 20:49
The only time we use this error message is for that case, where the intermediate certificate is not set (https://github.com/hashicorp/vault/blob/207983f5265c6a02d9cdc24f5f76f0951cd2339f/builtin/logical/pki/cert_util.go#L164). The question is why it isn't set for you. If you have the intermediate certificate, you could try using the set-signed endpoint; if the key is there it should then work.

Based on the fact that you were having storage issues, I wonder if the intermediate was never properly saved, but somehow was able to be used in the running Vault; then when you upgraded, since the intermediate wasn't in memory or in a cache, and not actually written to the filesystem, it started behaving like this. (We did fix a bug with the underlying cache in 0.7 so it's not impossible that this behavior could be related, if that's actually what happened.)

**Comment by sprutner** [comment] 2017-05-08 21:28
Actually, you're right about the intermediate certificate. I was just issuing certificates in this test environment as root per https://www.vaultproject.io/docs/secrets/pki/ which was working fine. Is this no longer supported? I just re-used the commands from the docs verbatim.

**Comment by jefferai** [comment] 2017-05-08 21:37
Sorry, I don't understand the question. Is what no longer supported?

**Comment by sprutner** [comment] 2017-05-08 21:44
If you run through https://www.vaultproject.io/docs/secrets/pki/ to set up PKI, then you end being able to issue certificates directly from root without an intermediate CA like below:

```
vault write pki/issue/example-dot-com \
    common_name=blah.example.com
```

This is how I was doing things, but it no longer works. It does not appear like any pki/intermediate endpoint is hit here in the guide. The issue here for me is that this was working and then suddenly stopped working--before any upgrade to 0.7.1.

I tried to set up an intermediate CA just now on a separate mount, using the root to sign a CSR from the intermediate, but I just got the same 500 error as above when trying to sign the CSR at the endpoint /pki/root/sign-intermediate

**Comment by jefferai** [comment] 2017-05-10 14:28
Can you provide the exact steps you are running? Our backend tests exercise these endpoints so the exact steps would be useful to help reproduce.

**Comment by sprutner** [comment] 2017-05-10 23:22
I would just run one of these:

```

vault write credodev/issue/website_dot_com \
    common_name=blah.website.dev \
    alternate_name=127.0.0.1
```

and I would get the error. Common name could be anything.

I gave up and just started over with new root CA certs, this time choosing to export the private key so that I could keep it in a safe place so that if it got corrupted/overwritten/who knows what happened I can just re-upload. Now the above command works again.

**Comment by jefferai** [comment] 2017-08-11 14:28
Closing, cannot reproduce.

**Closed by jefferai** 2017-08-11 14:28 UTC
