### ISSUE TITLE
Vault audit log remote_address should inflect X-Forwarded-For

### ISSUE THREAD

**Issue by ctennis** [hashicorp/vault#2895] opened 2017-06-20 13:00 UTC
If using a load balancer in front of Vault, and passing in an X-Forwarded-For header, the remote_address (or perhaps another field) should reflect that as to note where the actual request originated.  As is, all we see in the logs is the IP of the load balancer itself.

**Comment by jefferai** [comment] 2017-06-20 13:22
This is a duplicate of multiple other open issues, so closing (on phone so not looking up ATM but a simple search will find them if you're interested).

**Closed by jefferai** 2017-06-20 13:22 UTC
