### ISSUE TITLE
forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by jamesongithub** [hashicorp/vault#3847] opened 2018-01-25 20:04 UTC
**Environment:**

* Vault Version: Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')
* Operating System/Architecture: DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

**Vault Config File:**

```
storage "consul" {
  address = "127.0.0.1:8500"
  scheme = "https"
  tls_ca_file = "/mnt/consul/consul.ca"
  tls_cert_file = "/mnt/consul/consul.crt"
  tls_key_file = "/mnt/consul/consul.key"
  tls_min_version = "tls12"
  tls_skip_verify = "false"
  redirect_addr = "https://ADDRESS:8200"
  cluster_addr = "https://ADDRESS:8201"
  token = "thetoken"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_key_file = "/opt/vault/vault.key"
  tls_cert_file = "/opt/vault/vault.crt"
}
```

**Startup Log Output:**

```
                     Cgo: disabled
         Cluster Address: https:/ADDRESS:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
               Log Level: debug
                   Mlock: supported: true, enabled: true
        Redirect Address: https://ADDRESS:8200
                 Storage: consul (HA available)
                 Version: Vault v0.8.3
```

**Expected Behavior:**

Vault nodes should redirect correctly.

**Actual Behavior:**

After running for a while the standby node doesn't redirect to the active one.

**Steps to Reproduce:**

**Important Factoids:**

We're running two vault nodes behind an load balancer. Both vault nodes have access to each other 8200 and 8201 ports. Clients have direct access to all vault nodes. The load balancer uses the standbyok query param for all vault nodes. 

It seems to work after restarting, but after a few weeks it gets into this state again.

```
2018/01/25 19:54:01.378248 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:54:31.378164 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:55:01.378197 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:55:31.378194 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:56:01.378170 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:56:31.378208 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:57:01.378189 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:57:31.378233 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:58:01.378252 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:58:31.378190 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:59:01.378216 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/01/25 19:59:31.378194 [D
```

**References:**

https://www.vaultproject.io/docs/concepts/ha.html
https://www.vaultproject.io/docs/configuration/index.html#cluster_addr

**Comment by jefferai** [comment] 2018-01-26 01:18
What do you see in logs from the active node? This indicates that the connection has been interrupted; if the active node is spitting an error it may be useful to try to figure things out.

**Comment by jamesongithub** [comment] 2018-01-26 01:44
on the active side

```
2018/01/25 19:23:49.428486 [INFO ] expiration: revoked lease: lease_id=auth/aws/login/REDACT
2018/01/25 19:33:49.442786 [INFO ] expiration: revoked lease: lease_id=auth/aws/login/REDACT
2018/01/25 19:43:49.495349 [INFO ] expiration: revoked lease: lease_id=auth/aws/login/REDACT
2018/01/25 19:49:50 http: TLS handshake error from 10.10.1.66:44890: tls: oversized record received with length 64774
2018/01/25 19:49:52.024915 [DEBUG] core: error handshaking cluster connection: error=tls: oversized record received with length 64774
2018/01/25 19:53:49.490115 [INFO ] expiration: revoked lease: lease_id=auth/aws/login/REDACT
2018/01/25 19:58:17.358507 [DEBUG] core: error handshaking cluster connection: error=tls: oversized record received with length 64774
2018/01/25 20:03:49.910430 [INFO ] expiration: revoked lease: lease_id=auth/aws/login/REDACT
2018/01/25 20:13:50.667801 [INFO ] expiration: revoked lease: lease_id=auth/aws/login/REDACT
```

tls?

**Comment by michelvocks** [comment] 2019-12-03 14:23
Hi @jamesongithub!

Is this still an issue for you? Would you mind to reproduce this issue with the latest Vault version (1.3.0)?

Cheers,
Michel

**Comment by jamesongithub** [comment] 2019-12-05 05:01
Hi,

It's been a while. I actually don't have access to this cluster anymore. So wouldn't be able to repro.

**Comment by michelvocks** [comment] 2019-12-05 07:18
Hi @jamesongithub!

Thanks for letting me know. I will close this issue for now since we are unable to reproduce this.
Feel free to open a new issue if you hit the same problem again. 

Cheers,
Michel

**Closed by michelvocks** 2019-12-05 07:18 UTC
Labels: bug, core, version/0.8.x, waiting-for-response

**Comment by esethuraman** [comment] 2020-06-24 22:02
@jamesongithub  Can you recollect how did the issue go away in your case?

**Comment by jamesongithub** [comment] 2020-06-24 22:10
I never had a resolution. Only can bounce the servers periodically.
