### ISSUE TITLE
APP-ID + Service Discovery Deleting userid Issue

### ISSUE THREAD

**Issue by ashishrathore1** [hashicorp/vault#1448] opened 2016-05-25 13:08 UTC
We are using app-id  and service discovery approach to register different services in vault.Our approach is as follow:

1. Our service discovery write its content  in zookeeper whenever new service comes up in its znode.
e.g /services/service_name/component/hosts
2. We have written watcher which monitors root znode i.e. /services  and whenever new service comes up lets say /services/service1/comp1/host1 with content {hostname:host1} which is always unique.
3. Now we take  service1+comp1 and generate app-id with this. and using host1 contents i.e  {hostname:host1} generate userid and after mapping these we create user  in vault.
4. Now when service gets down its znode gets deleted but as znode gets deleted from vault we cannot get its content i.e {hostname:host1} so cannot get user-id . But we want to remove userid  when host gets removed or app-id when service gets removed.
5. The problem with vault is that we cannot list app-id or user id so is there any way to remove userid  as we cannot get .

**Comment by jefferai** [comment] 2016-05-26 13:53
Duplicate of #1320

**Closed by jefferai** 2016-05-26 13:53 UTC
