### ISSUE TITLE
Vault auto-unseal for gcp kms failing [context deadline exceeded]

### ISSUE THREAD

**Issue by rohitranjan1991** [hashicorp/vault#16257] opened 2022-07-08 14:20 UTC
**Describe the bug**
"vault operator init" thows error "Error initializing: context deadline exceeded" when trying to connect with GCP KMS. Even though the vault is still initialized despite of the error thrown. I am trying to setup vault in GKE in asia region and KMS is also in asia region.

Since the above command is not printing the root token and unseal keys, the vault setup even though as per logs in ready to be used cannot be accessible.

**To Reproduce**
1. vault operator init
2. See error "Error initializing: context deadline exceeded"

**Expected behavior**
It should print the root token and unseal keys

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.10.3
* Vault CLI Version (retrieve with `vault version`):  1.10.3
* Server Operating System/Architecture: GKE 

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
seal "gcpckms" {
         project     = "<project-name>"
         region      = "asia"
         key_ring    = "vault"
         crypto_key  = "vault-key"
      }
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by sgmiller** [comment] 2022-07-08 16:04
Just a guess, but typically that error is due to hanging on a network request.  It's possible that your server cannot connect to GCP to complete the initialization process.  Can you provide the logs, and possibly run with TRACE level debugging?

**Comment by maxb** [comment] 2022-07-10 07:29
Same question also asked at https://discuss.hashicorp.com/t/vault-auto-unseal-for-gcp-kms-failing-on-init-context-deadline-exceeded/41764 though more info has been given here.

**Comment by rohitranjan1991** [comment] 2022-07-11 05:54
Thanks @sgmiller for quick reply. I think the GKE pod is able to coinnect to the KMS URL because if I provide the wrong key ring or crypto key, Its says "not found". So the connectivity is there however it may be a bit slow (even though both are on the same region in GCP). Is there a way to provide a way to extend the context deadline ??

Also how do I do a TRACE level debugging in vault command ??

@maxb yeah, I was not sure where would I get the answer so I posted it both the places :-)

**Comment by rohitranjan1991** [comment] 2022-07-11 06:22
As for the logs from vault-0 

```
2022-07-11T06:18:42.417Z [INFO]  core: security barrier not initialized
2022-07-11T06:18:42.515Z [INFO]  core.autoseal: seal configuration missing, but cannot check old path as core is sealed: seal_type=recovery
2022-07-11T06:18:46.455Z [INFO]  core: stored unseal keys supported, attempting fetch
2022-07-11T06:18:46.539Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
2022-07-11T06:18:47.424Z [INFO]  core: security barrier not initialized
2022-07-11T06:18:47.499Z [INFO]  core.autoseal: seal configuration missing, but cannot check old path as core is sealed: seal_type=recovery
2022-07-11T06:18:51.540Z [INFO]  core: stored unseal keys supported, attempting fetch
2022-07-11T06:18:51.623Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
2022-07-11T06:18:52.724Z [INFO]  core: security barrier not initialized
2022-07-11T06:18:53.104Z [INFO]  core.autoseal: seal configuration missing, but cannot check old path as core is sealed: seal_type=recovery
2022-07-11T06:18:56.624Z [INFO]  core: stored unseal keys supported, attempting fetch
2022-07-11T06:18:56.709Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
2022-07-11T06:18:57.646Z [INFO]  core: security barrier not initialized
2022-07-11T06:18:57.752Z [INFO]  core.autoseal: seal configuration missing, but cannot check old path as core is sealed: seal_type=recovery
2022-07-11T06:19:01.709Z [INFO]  core: stored unseal keys supported, attempting fetch
2022-07-11T06:19:01.790Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
2022-07-11T06:19:02.648Z [INFO]  core: security barrier not initialized
2022-07-11T06:19:02.729Z [INFO]  core.autoseal: seal configuration missing, but cannot check old path as core is sealed: seal_type=recovery
2022-07-11T06:19:03.604Z [WARN]  core: stored keys supported on init, forcing shares/threshold to 1
2022-07-11T06:19:03.987Z [INFO]  core: security barrier not initialized
2022-07-11T06:19:04.995Z [INFO]  core: security barrier initialized: stored=1 shares=1 threshold=1
2022-07-11T06:19:06.343Z [INFO]  core: post-unseal setup starting
2022-07-11T06:19:07.537Z [INFO]  core: loaded wrapping token key
2022-07-11T06:19:07.921Z [INFO]  core.autoseal: seal configuration missing, but cannot check old path as core is sealed: seal_type=recovery
2022-07-11T06:19:08.247Z [INFO]  core: Recorded vault version: vault version=1.10.3 upgrade time="2022-07-11 06:19:07.53800754 +0000 UTC"
2022-07-11T06:19:08.324Z [INFO]  core: successfully setup plugin catalog: plugin-directory=""
2022-07-11T06:19:08.709Z [INFO]  core: no mounts; adding default mount table
2022-07-11T06:19:09.334Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2022-07-11T06:19:09.335Z [INFO]  core: successfully mounted backend: type=system path=sys/
2022-07-11T06:19:09.335Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2022-07-11T06:19:12.257Z [INFO]  core.autoseal: seal configuration missing, but cannot check old path as core is sealed: seal_type=recovery
2022-07-11T06:19:12.609Z [INFO]  core: successfully enabled credential backend: type=token path=token/ namespace="ID: root. Path: "
2022-07-11T06:19:13.258Z [INFO]  rollback: starting rollback manager
2022-07-11T06:19:13.258Z [INFO]  core: restoring leases
2022-07-11T06:19:13.347Z [INFO]  expiration: lease restore complete
2022-07-11T06:19:14.112Z [INFO]  identity: entities restored
2022-07-11T06:19:14.194Z [INFO]  identity: groups restored
2022-07-11T06:19:15.720Z [WARN]  core: post-unseal upgrade seal keys failed: error="no recovery key found"
2022-07-11T06:19:15.720Z [INFO]  core: usage gauge collection is disabled
2022-07-11T06:19:17.258Z [INFO]  core.autoseal: seal configuration missing, but cannot check old path as core is sealed: seal_type=recovery
2022-07-11T06:19:18.681Z [INFO]  core: post-unseal setup complete
2022-07-11T06:19:20.641Z [INFO]  core: root token generated
2022-07-11T06:19:20.641Z [INFO]  core: pre-seal teardown starting
2022-07-11T06:19:20.641Z [INFO]  rollback: stopping rollback manager
2022-07-11T06:19:20.641Z [INFO]  core: pre-seal teardown complete
2022-07-11T06:19:50.669Z [INFO]  core: stored unseal keys supported, attempting fetch
2022-07-11T06:19:51.081Z [INFO]  core.cluster-listener.tcp: starting listener: listener_address=[::]:8201
2022-07-11T06:19:51.082Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
2022-07-11T06:19:51.082Z [INFO]  core: vault is unsealed
2022-07-11T06:19:51.082Z [INFO]  core: entering standby mode
2022-07-11T06:20:51.128Z [INFO]  core: unsealed with stored key
2022-07-11T06:20:51.129Z [WARN]  core: attempted unseal with stored keys, but vault is already unsealed
```

where as the logs from the shell 

```

/ $ vault operator init
Error initializing: context deadline exceeded
/ $ 

```

**Comment by rohitranjan1991** [comment] 2022-07-11 15:04
@sgmiller

**Comment by KosShutenko** [comment] 2022-09-01 09:35
@rohitranjan1991 did you fixed this issue? I have the same one.

**Comment by densnoigaskogen** [comment] 2022-09-05 11:48
hi @rohitranjan1991 @rohitranjan1991 , I experienced exactly the same issue when using gcpkms auto-sealing. Any updates on the cause&solutions?

**Comment by shoootyou** [comment] 2022-10-09 20:33
Hello @KosShutenko @densnoigaskogen @rohitranjan1991 increase VAULT_CLIENT_TIMEOUT to 300s using the environment variables

My environment (GKE) works with that. Here the documentation: [Hashicorp Support](https://support.hashicorp.com/hc/en-us/articles/8552873602451-Vault-on-Kubernetes-and-context-deadline-exceeded-errors)

**Comment by IngCr3at1on** [comment] 2023-01-19 20:08
> Hello @KosShutenko @densnoigaskogen @rohitranjan1991 increase VAULT_CLIENT_TIMEOUT to 300s using the environment variables
> 
> My environment (GKE) works with that. Here the documentation: [Hashicorp Support](https://support.hashicorp.com/hc/en-us/articles/8552873602451-Vault-on-Kubernetes-and-context-deadline-exceeded-errors)

Just for general knowledge I just used this to resolve this exact same issue on a GKE cluster with gcpckms auto unseal.
The issue looks kind of stale so sorry to necro-bump but being open I figured it was worth a confirmation.

**Comment by densnoigaskogen** [comment] 2023-01-20 19:30
hi @IngCr3at1on  @rohitranjan1991 @shoootyou , yes, I can also confirm that the solution suggested by @shoootyou solved the problem, and our Vault on GCP with auto-sealing works fine.

**Comment by hsimon-hashicorp** [comment] 2023-02-03 15:06
Since there's a solution in the comments, I'm going to go ahead and close this issue now. Thanks for the community support! <3

**Closed by hsimon-hashicorp** 2023-02-03 15:06 UTC
Labels: core/seal

**Comment by maradwan** [comment] 2023-02-28 13:09
export VAULT_CLIENT_TIMEOUT=300s
