### ISSUE TITLE
Disable Warning Messages about VAULT_TOKEN if token store is deactivated

### ISSUE THREAD

**Issue by DirkWi** [hashicorp/vault#17360] opened 2022-09-29 13:24 UTC
I'm having issues with parallel jobs in powershell trying to login to vault store:

System.Management.Automation.InvocationInfo
--
: Error storing token: replace C:\Users\[Username]\.vault-token.tmp C:\Users\[User]\.vault-token: Acces denied
--
Due to parallel access on the same file (which seems to get renamed to ".vault-token.tmp" in between), the access denied error does occur. Thus I disabled the store functionality by using the option "-no-store" in combination with the login method "userpass", but I do get an additional warning:
"The token was not stored in token helper. Set the VAULT_TOKEN environment
variable or pass the token below with each request to Vault."

This warning gets interpreted as an error in a connected system which receives and processes the response. I need to suppress the warning, is there any chance to implement this feature?
I continued with a kv get command without problems, but the warning does break the system.

Any help is kindly appreciated. If there is any other chance, like using random file names for the token store, that would be fine, too.

**Comment by hsimon-hashicorp** [comment] 2022-12-14 19:31
Hello! This is intended behavior at this time. You may wish to investigate using a token helper, such as: https://developer.hashicorp.com/vault/docs/commands/token-helper
I'm going to go ahead and close this issue now, but please feel free to re-open it if you need. Thanks!

**Closed by hsimon-hashicorp** 2022-12-14 19:31 UTC
Labels: core/token
