### ISSUE TITLE
Lost mount configuration after catastrophic shutdown

### ISSUE THREAD

**Issue by glindstedt** [hashicorp/vault#8594] opened 2020-03-20 17:28 UTC
**Describe the bug**

We have a vault cluster configured with GCS as a backend (with versioning) and auto-unseal using KMS. Due to user error the Google Cloud project hosting those resources was accidentally deleted and vault lost contact to the backend.

Once the project had been restored and we restarted the vault cluster it seemed to start fine and unsealed. However, our KV secret mounts (one V1 under `secret/` and one V2 under `kv/`) were missing.

Manually inspecting the GCS bucket we could see that the data for those mounts were still present under the `/logical/` folder, however somehow the configuration for them in vault had been lost. Other configuration, such as LDAP integration and policies were left untouched.

**We were able to resolve the issue by shutting down the cluster again and reverting the `/core/mounts` file to a version prior to the event, and then starting the cluster back up again.**

I'm guessing that the `/core/mounts` file somehow ended up in a corrupt state, and that vault then silently replaced it with a fresh one.

Here are the logs from the shutdown process (from 3 instances):

```
2020-03-20T14:30:51.865Z [ERROR] core: writing request counters to barrier: err="failed to save request counters: 1 error occurred:
	* error closing connection: googleapi: Error 404: The requested project was not found., notFound
"
2020-03-20T14:30:57.664Z [ERROR] core: failed to acquire lock: error="lock: attempt lock: googleapi: Error 404: The requested project was not found., notFound"
2020-03-20T14:31:02.302Z [INFO]  core: acquired lock, enabling active operation
2020-03-20T14:31:02.716Z [ERROR] core: leader advertisement setup failed: error="1 error occurred:
	* error closing connection: googleapi: Error 404: The requested project was not found., notFound
"
2020-03-20T14:31:05.178Z [WARN]  core.cluster-listener: no TLS config found for ALPN: ALPN=[req_fw_sb-act_v1]
2020-03-20T14:31:05.387Z [WARN]  core.cluster-listener: no TLS config found for ALPN: ALPN=[req_fw_sb-act_v1]
2020-03-20T14:31:05.710Z [ERROR] core: failed to acquire lock: error="lock: attempt lock: googleapi: Error 404: The requested project was not found., notFound"
2020-03-20T14:31:07.798Z [INFO]  core: acquired lock, enabling active operation
2020-03-20T14:31:08.153Z [INFO]  core: post-unseal setup starting
2020-03-20T14:31:08.248Z [WARN]  core.cluster-listener: no TLS config found for ALPN: ALPN=[req_fw_sb-act_v1]
2020-03-20T14:31:08.255Z [INFO]  core: loaded wrapping token key
2020-03-20T14:31:08.255Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
2020-03-20T14:31:08.434Z [INFO]  core: successfully mounted backend: type=system path=sys/
2020-03-20T14:31:08.434Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2020-03-20T14:31:08.434Z [INFO]  core: successfully mounted backend: type=kv path=secret/
2020-03-20T14:31:08.569Z [INFO]  core: successfully mounted backend: type=kv path=kv/
2020-03-20T14:31:08.569Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2020-03-20T14:31:09.150Z [INFO]  core: successfully enabled credential backend: type=token path=token/
2020-03-20T14:31:09.151Z [INFO]  core: successfully enabled credential backend: type=ldap path=ldap/
2020-03-20T14:31:09.151Z [INFO]  core: restoring leases
2020-03-20T14:31:09.151Z [INFO]  rollback: starting rollback manager
2020-03-20T14:31:09.165Z [ERROR] expiration: error restoring leases: error="failed to scan for leases: list failed at path "": failed to read object: storage: bucket doesn't exist"
2020-03-20T14:31:09.165Z [ERROR] core: shutting down
2020-03-20T14:31:09.165Z [INFO]  core: marked as sealed
2020-03-20T14:31:09.249Z [WARN]  core.cluster-listener: no TLS config found for ALPN: ALPN=[req_fw_sb-act_v1]
2020-03-20T14:31:09.513Z [INFO]  identity: entities restored
2020-03-20T14:31:09.529Z [INFO]  core: pre-seal teardown starting
2020-03-20T14:31:09.529Z [INFO]  rollback: stopping rollback manager
2020-03-20T14:31:09.529Z [INFO]  core: pre-seal teardown complete
2020-03-20T14:31:09.529Z [ERROR] core: post-unseal setup failed: error="failed to scan for groups: failed to read object: storage: bucket doesn't exist"
2020-03-20T14:31:09.565Z [WARN]  core.cluster-listener: no TLS config found for ALPN: ALPN=[req_fw_sb-act_v1]
2020-03-20T14:31:09.595Z [INFO]  core: stopping cluster listeners
2020-03-20T14:31:09.595Z [INFO]  core.cluster-listener: forwarding rpc listeners stopped
2020-03-20T14:31:10.065Z [INFO]  core.cluster-listener: rpc listeners successfully shut down
2020-03-20T14:31:10.065Z [INFO]  core: cluster listeners successfully shut down
2020-03-20T14:31:10.065Z [INFO]  core: vault is sealed
```

Here are the logs from the subsequent startup sequence. Note that neither of the `secret/` or `kv/` mounts are mounted:

```
==> Vault shutdown triggered
==> Vault shutdown triggered
==> Vault shutdown triggered
==> Vault server configuration:
      <REDACTED>
==> Vault server started! Log data will stream in below:
2020-03-20T15:16:26.611Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2020-03-20T15:16:27.263Z [INFO]  core: stored unseal keys supported, attempting fetch
2020-03-20T15:16:27.544Z [INFO]  core.cluster-listener: starting listener: listener_address=0.0.0.0:8201
2020-03-20T15:16:27.545Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
2020-03-20T15:16:27.545Z [INFO]  core: entering standby mode
2020-03-20T15:16:27.570Z [INFO]  core: vault is unsealed
2020-03-20T15:16:27.570Z [INFO]  core: unsealed with stored keys: stored_keys_used=1
2020-03-20T15:16:32.786Z [INFO]  core: acquired lock, enabling active operation
2020-03-20T15:16:33.197Z [INFO]  core: post-unseal setup starting
2020-03-20T15:16:33.282Z [INFO]  core: loaded wrapping token key
2020-03-20T15:16:33.282Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
2020-03-20T15:16:33.360Z [INFO]  core: successfully mounted backend: type=system path=sys/
2020-03-20T15:16:33.360Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2020-03-20T15:16:33.360Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2020-03-20T15:16:33.941Z [INFO]  core: successfully enabled credential backend: type=token path=token/
2020-03-20T15:16:33.941Z [INFO]  core: successfully enabled credential backend: type=ldap path=ldap/
2020-03-20T15:16:33.941Z [INFO]  core: restoring leases
2020-03-20T15:16:33.941Z [INFO]  rollback: starting rollback manager
2020-03-20T15:16:34.128Z [INFO]  identity: entities restored
2020-03-20T15:16:34.150Z [INFO]  identity: groups restored
2020-03-20T15:16:34.214Z [INFO]  expiration: lease restore complete
2020-03-20T15:16:34.361Z [INFO]  core: post-unseal setup complete
```

**To Reproduce**

I'm not sure if this is easily reproducible, but potentially could be reproduced by severing the backend connection while the cluster is up.

**Expected behavior**

The mount configuration would remain untouched during catastrophic shutdown when loosing connection to the backend.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.2
* Vault CLI Version (retrieve with `vault version`): 1.3.3
* Server Operating System/Architecture: Google Kubernetes Engine

Vault server configuration file(s):

```hcl
cluster_name = <REDACTED>
api_addr     = "https://$(POD_IP_ADDR):8200"
cluster_addr = "https://$(POD_IP_ADDR):8201"
ui           = true
log_format   = "standard"

default_lease_ttl = "24h"

seal "gcpckms" {
  project    = <REDACTED>
  region     = <REDACTED>
  key_ring   = <REDACTED>
  crypto_key = <REDACTED>
}
storage "gcs" {
  bucket     = <REDACTED>
  ha_enabled = "true"
}
listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/etc/vault/tls/tls.crt"
  tls_key_file  = "/etc/vault/tls/tls.key"
  tls_disable_client_certs = true
}
telemetry {
  ...
}
```

**Comment by aphorise** [comment] 2022-09-03 11:49
Closing this request as there's insufficient details nor any reproduction.

Issue was most likely due to GCS related factors specific to the user and or differences in the authoring of mount options within 1.3.2 that are different in more recent 1.11.x versions.

@glindstedt - hey thank you for initially reporting this and if you have any repeat of the issue with more recent versions then please do re-open this and that would be most appreciated. Any further confirmation you may have on how you progressed and if this is applicable in the most recent versions would be helpful too (for clarity and community).

**Closed by aphorise** 2022-09-03 11:49 UTC
Labels: bug, storage/gcs
