### ISSUE TITLE
ACL required for renewing secret leases?

### ISSUE THREAD

**Issue by nbrownus** [hashicorp/vault#535] opened 2015-08-14 00:49 UTC
Noticing that once a lease expires `consul-template` attempts to renew.

The policy these tokens have only allow reading a particular mount:

```hcl
name = "example-dev"

path "example-dev/*" {
    policy = "read"
}
```

It seems that I must also give to make it work properly:

```hcl
path "sys/renew/*" {
    policy = "write"
}
```

It would seem that any lease could be renewed by a token in this policy, similar problem as #455 

The error I am seeing:

```json
{"type":"request","auth":{"display_name":"","policies":null,"metadata":null},"request":{"operation":"write","path":"sys/renew/...","data":{"increment":1},"remote_address":"..."},"error":"permission denied"}
```

**Comment by sethvargo** [comment] 2015-08-14 19:54
Hi @nbrownus 

This is correct. I think this is a duplicate of #455, but the only way to currently renew a token is to get write to the renew endpoint.

Let's track #455 to reduce confusion though please :smile:

**Closed by sethvargo** 2015-08-14 19:54 UTC

**Comment by nbrownus** [comment] 2015-08-14 20:47
Sounds good as long as #455 increases in scope to include secret lease renewal as well as auth token renewal.

**Comment by agperson** [comment] 2016-02-01 18:40
It does not appear that #455 was expanded in scope to include secret lease renewal.  Is this being tracked elsewhere?

**Comment by damomurf** [comment] 2016-03-01 04:07
@sethvargo Can we reopen this, seeing as it appears that #455 was never increased in scope to include secret lease renewals? Correct me if I'm wrong, but I don't see this actually being tracked anywhere.

**Comment by sethvargo** [comment] 2016-03-01 04:22
@damomurf `/auth/token/renew-self`: https://www.vaultproject.io/docs/auth/token.html

**Comment by sethvargo** [comment] 2016-03-01 04:23
lease-id's are prefixed with their auth method/policy and path, so it's possible to use glob matching to only allow sub-path secret lease renewal. There is no notion of "self" for a secret.
