### ISSUE TITLE
[Feature Request] Support partial updates to database secret backend

### ISSUE THREAD

**Issue by Xopherus** [hashicorp/vault#3544] opened 2017-11-07 00:58 UTC
**Feature Request:**

For some context, I have a repo which codifies *most* of the mount configuration in my system - basically roles and secret backend configuration (minus the secrets themselves). That means when someone needs a new secret backend, we'll have to manually mount + configure it. After that if we have to add additional roles or make configuration changes (e.g., change a default_lease_ttl) we can do so via mount tuning or via the secret backend's API.

Per the docs, if I want to set up a database connection via the [database secret backend](https://www.vaultproject.io/api/secret/databases/index.html), I must issue a write like so:

`vault write database/config/connection plugin_name="mysql-database-plugin" connection_url="user:pass@tcp(host:port)/db"`

So for example, if I want to add `max_connection_lifetime=10m` to the connection, I have to issue this:

`vault write database/config/connection plugin_name="mysql-database-plugin" connection_url="user:pass@tcp(host:port)/db" max_connection_lifetime=10m`

It would be nice to allow partial updates like this:
`vault write database/config/connection max_connection_lifetime=10m`

**Comment by james-lawrence** [comment] 2017-11-14 01:08
duplicate of #1468

**Comment by rwiggins** [comment] 2018-06-14 20:05
Ran into this today. For instance, adding to `allowed_roles`  requires issuing a write with [a bunch of details](https://github.com/hashicorp/vault/blob/master/builtin/logical/database/path_config_connection.go#L227-L237) in it. Pretty sure it requires more than just the connection_url and plugin_name to prevent clobbering.

Really frustrating.

**Closed** 2018-06-19 15:24 UTC
