### ISSUE TITLE
Vault Down in Production using mysql backend

### ISSUE THREAD

**Issue by ruchi15** [hashicorp/vault#1088] opened 2016-02-17 10:27 UTC
Our Config file is like this
----------------------------------------------------------------------------------------------------------------------------------------
backend "mysql" {
 username= "vaultprod"
 password= "@vaUltProd"
 address = "52.74.149.36:3307"

}
listener "tcp" {
 address = "vault.klikpay.int:8200"
 tls_cert_file = "/home/centos/star.klikpay.int.bundle/star.klikpay.int.crt"
 tls_key_file= "/home/centos/star.klikpay.int.bundle/star.klikpay.int.key"
 tls_min_version="tls10"
}

disable_mlock=true

---------------------------------------------------------------------------------------------------------------------------------------

Previously it was working fine but now it gets down every time we unseal it . Unable to figure out issue
pls help...

==> Vault server configuration:

        Log Level: info
            Mlock: supported: true, enabled: false
          Backend: mysql
       Listener 1: tcp (addr: "vault.klikpay.int:8200", tls: "enabled")
          Version: Vault v0.4.1

==> Vault server started! Log data will stream in below:

2016/02/09 17:10:13 http: TLS handshake error from 10.245.6.91:52685: EOF
2016/02/09 17:10:28 http: TLS handshake error from 10.245.26.171:59237: EOF
2016/02/09 17:10:43 http: TLS handshake error from 10.245.6.91:52702: EOF
2016/02/09 17:11:00 http: TLS handshake error from 10.245.26.171:59249: EOF
2016/02/09 17:11:13 http: TLS handshake error from 10.245.6.91:52722: EOF
2016/02/09 17:11:28 http: TLS handshake error from 10.245.26.171:59267: EOF
2016/02/09 17:11:46 http: TLS handshake error from 10.245.6.91:52736: EOF
2016/02/09 17:11:58 http: TLS handshake error from 10.245.26.171:59279: EOF
2016/02/09 17:12:14 http: TLS handshake error from 10.245.6.91:52752: EOF
2016/02/09 17:12:18 [INFO] core: vault is unsealed
2016/02/09 17:12:18 [INFO] core: post-unseal setup starting
2016/02/09 17:12:19 [INFO] core: mounted backend of type generic at logical/a93db1ce-6365-1cfe-754f-e4be5c2b0f5b/
2016/02/09 17:12:19 [INFO] core: mounted backend of type cubbyhole at logical/ed57fc8e-8952-47cf-00f8-66ada2baeadc/
2016/02/09 17:12:19 [INFO] core: mounted backend of type system at sys/
2016/02/09 17:12:19 [INFO] rollback: starting rollback manager
2016/02/09 17:12:23 [INFO] expire: restored 156 leases
2016/02/09 17:12:23 [INFO] core: post-unseal setup complete
2016/02/09 17:12:24 http: panic serving 10.242.96.11:42376: runtime error: invalid memory address or nil pointer dereference
goroutine 30340 [running]:
net/http.(*conn).serve.func1(0xc820c2ba20, 0x7fd3f208f710, 0xc820fe5600)
/goroot/src/net/http/server.go:1287 +0xb5
database/sql.(*Rows).Next(0x0, 0xc822bc4b28)
/usr/local/go/src/database/sql/sql.go:1633 +0x22
github.com/hashicorp/vault/physical.(*MySQLBackend).List(0xc8201da080, 0xc820922de0, 0x2f, 0x0, 0x0, 0x0, 0x0, 0x0)

**Comment by ruchi15** [comment] 2016-02-17 10:29
[vault_log.txt](https://github.com/hashicorp/vault/files/134050/vault_log.txt)


Attached is overall log.

**Comment by jefferai** [comment] 2016-02-17 16:46
Duplicate of #1084.

**Closed by jefferai** 2016-02-17 16:46 UTC
