### ISSUE TITLE
Confusion about token lifecycle

### ISSUE THREAD

**Issue by icodeforlove** [hashicorp/vault#1938] opened 2016-09-28 16:53 UTC
```
vault token-renew $TOKEN 2500000
```

Renews the token for another ~700 hours. How many times can I do this on the following token:

```
Key              	Value
---              	-----
creation_time    	1475071011
creation_ttl     	2592000
display_name     	token
explicit_max_ttl 	0
last_renewal_time	1475079285
meta             	<nil>
num_uses         	0
orphan           	false
path             	auth/token/create
renewable        	true
ttl              	2579846
```

I have read a few things that say that eventually I will be forced to swap tokens, can someone please clear this up for me. I'm hoping theres a way I can issue a system a token, and have it renew itself when it accesses vault.

**Comment by vishalnayak** [comment] 2016-09-28 16:54
Duplicate of #1733

**Closed by vishalnayak** 2016-09-28 16:54 UTC

**Comment by jefferai** [comment] 2016-09-28 18:01
I don't think this is related to #1733 at all. But I do encourage @icodeforlove to read https://www.vaultproject.io/docs/concepts/tokens.html as it goes into extensive detail about token lifecycle.

**Comment by icodeforlove** [comment] 2016-09-29 00:45
@jefferai  Is it ok if you were to do something like this?

```
vault mount-tune -max-lease-ttl=315360000 -default-lease-ttl=315360000 auth/token
```

now tokens live for 10 years until revoked?

**Comment by jefferai** [comment] 2016-09-29 02:03
You could...probably you want to look into periodic tokens though!
