### ISSUE TITLE
auth/app-id allow list of map/app-id and map/auth-id

### ISSUE THREAD

**Issue by tomalok** [hashicorp/vault#1313] opened 2016-04-10 05:50 UTC
would be helpful to be able to periodically clean up any cruft that accumulates over time.  similar to #1312 - the issue it was based on (#911) also originally mentioned app-id.

would also be helpful to be able to somehow view metadata on the creation timestamp and the last successful authentication timestamp.

**Comment by jefferai** [comment] 2016-04-10 11:21
Duplicate of #1261

**Closed** 2016-04-19 23:31 UTC
