### ISSUE TITLE
HashicorpLearn - Docs - minor misleading

### ISSUE THREAD

**Issue by unfor19** [hashicorp/vault#8508] opened 2020-03-09 13:59 UTC
**Describe the bug**
After reading about [Built-in Help](https://learn.hashicorp.com/vault/getting-started/help), there's the [Policies](https://learn.hashicorp.com/vault/getting-started/policies) section, which states:

> "...Policies in Vault control what a user can access. In the last section, we learned about **authentication**. This section is about authorization."

The [authentication](https://learn.hashicorp.com/vault/getting-started/authentication) section comes **after** the Policies section, so it's a bit misleading what should be read first

If there's another place to comment about the docs, feel free to share where

**Comment by catsby** [comment] 2020-03-09 14:51
Hello! I believe this is a duplicate of https://github.com/hashicorp/vault/issues/8436 , @yhyakuna can you take a look at this and 8436?

**Comment by unfor19** [comment] 2020-03-09 15:49
Correct, closing, thanks!

**Closed** 2020-03-09 15:49 UTC
