### ISSUE TITLE
Getting started guide ordering conflicts with content

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/vault#8459] opened 2020-03-03 19:57 UTC
**Is your feature request related to a problem? Please describe.**
The content of the [authentication guide](https://github.com/hashicorp/vault/blob/master/website/pages/intro/getting-started/authentication.mdx) refers to Policies as the next section and Dynamic Secrets as the previous section (sometimes implicitly, such as referring to the next section being about authorization). However, the guides are ordered such that Policies is the previous section.

**Describe the solution you'd like**
Re-ordering or content change; either is fine.

**Describe alternatives you've considered**
Both above.

**Explain any additional use-cases**
n/a

**Additional context**
This is probably not super important, except to remove confusion when people new to Vault read through this section in the guides.

**Comment by cainejette** [comment] 2020-03-03 21:25
Duplicate of https://github.com/hashicorp/vault/issues/8436

**Comment by catsby** [comment] 2020-03-03 21:47
Hey @mschuchard  - I agree with @cainejette that this is mostly a duplicate of #8436, so I'm going to close this one for now. Please track #8436 for updates, and thank you for opening the issue.

**Closed by catsby** 2020-03-03 21:47 UTC
