### ISSUE TITLE
Going in a secret directory where subdirectories can't be listed prevent anything to be listed on the WebUI (until we refresh)

### ISSUE THREAD

**Issue by Banh-Canh** [hashicorp/vault#14123] opened 2022-02-17 13:54 UTC
**Describe the bug**
In an attempt to hide path to secrets users aren't supposed to access, we managed to make it works but what is displayed on the webui is inconsistent.
We used the following policy:
```
path "secrets/metadata/+"
{
  capabilities = ["list"]
}
path "secrets/metadata/+/+"
{
  capabilities = ["list"]
}
path "secrets/metadata/+/subdir2-visible/*"
{
  capabilities = ["list"]
}
path "secrets/data/+/subdir2-visible/*"
{
  capabilities = ["read"]
}
```
User should be able to see sub-directories in: "secrets", "secrets/subdir1" and "secrets/subdir1/subdir2-visible/*"
but not anything in "secrets/subdir1/subdir2-invisible" which is at the same level as "subdir2-visible".

The policy is working as intended and on the web UI, if an user go to "secrets/subdir1/subdir2-invisible", it show nothing inside it which is normal. But if the user then goes back to the parent folder (subdir1), it doesn't list anything anymore until I refresh the page (it shows neither subdir2-visible or subdir2-invisible). 
Actually, nothing is listed anymore (if we go back further to the parent directory or if we chose to go to another path) until we refresh the page.

**To Reproduce**
1) Set the mentionned policy.
2) Connect to the vault web ui using an user with the policy set.
3) Try to see the secret hidden behind the path that is supposed to work (it should works) then go back to a path which isn't supposed to work (you should not see any subdirectory) then go back to a directory where subdirectory are supposed to be shown, for example go up one time to the parent directory, and you should not be able to see any subdirectory (until you refresh the page) that you previously could.

**Expected behavior**
Path/directories/subdirectories that can and are listed should still be listed even if an authorized user go once to a directory where the content can't be listed.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.3

**Comment by zofskeez** [comment] 2023-10-23 21:03
Thanks for reporting this @Banh-Canh. I tested in the latest version (1.15.1) and was unable to reproduce. There was a rebuild of KV secrets for 1.15 and it's possible that it was fixed as part of that effort or in an version newer than 1.9. I'm going to go ahead and close this but feel free to reopen if necessary.



https://github.com/hashicorp/vault/assets/24611656/1c905cab-f474-4d5c-be63-45e7a5f6610d

**Closed by zofskeez** 2023-10-23 21:03 UTC
Labels: ui, enhancement, core/policy
