### ISSUE TITLE
CLI: breaks when writing values with embedded spaces.

### ISSUE THREAD

**Issue by kenrestivo-stem** [hashicorp/vault#3222] opened 2017-08-22 17:10 UTC
**Environment:**

* Vault Version:
Vault v0.8.0 ('af63d879130d2ee292f09257571d371100a513eb')

* Operating System/Architecture:
Linux prod-vault-1 4.4.0-1018-aws #27-Ubuntu SMP Fri May 19 17:20:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Vault Config File:**
```javascript
{
    "backend": {"file": {"path": "/vault/file"}},
    "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": 1}},
    "default_lease_ttl": "168h",
    "cluster_name": "prod",
    "disable_mlock": 1,
    "max_lease_ttl": "720h"
}
```

**Startup Log Output:**

**Expected Behavior:**
Vault LDAP plugin should have sent to the LDAP server as its DN:
```
cn=System Authorizer,ou=people,ou=hq,dc=stem,dc=com
```
**Actual Behavior:**
Vault instead sent this to the LDAP server:
```
cn=System
```
which is obviously wrong.
```
4	0.000118	97	172.33.10.101	49598	10.35.8.74	389	0.000329000		229	bindRequest(1) "cn=System" simple
```

**Steps to Reproduce:**
Have a space in the CN for the binddn, which is perfectly legal and typical for LDAP!

```sh
vault write auth/ldap/config \
      url='ldap://identity.stem.com' \
      binddn='cn=System Authorizer,ou=people,ou=hq,dc=stem,dc=com' \
      bindpass='REDACTED!' \
      userattr='uid' \
      groupdn='ou=hq,dc=stem,dc=com' \
      groupfilter='(&(objectClass=posixGroup)(memberUid=%s))' \
      groupattr='memberOf' 
```

**Important Factoids:**
Spaces are legal in LDAP CN's. The Vault LDAP plugin chokes on this space and terminates the binddn string at it.

Note also that the configuration is *not* getting saved correctly in vault's database; 
```
vault read auth/ldap/config
Key            	Value
---            	-----
binddn         	cn=System
bindpass       	REDACTED!
certificate    	
deny_null_bind 	true
discoverdn     	false
groupattr      	memberOf
groupdn        	ou=hq,dc=stem,dc=com
groupfilter    	(&(objectClass=posixGroup)(memberUid=%s))
insecure_tls   	false
starttls       	false
tls_max_version	tls12
tls_min_version	tls12
upndomain      	
url            	ldap://REDACTED.stem.com
userattr       	uid
userdn         	
```

So the bug appears to be in the saving.

**References:**
Here is a screenshot of the packet capture from vault ldap plugin talking to the LDAP server:
https://brownbag-static.s3.amazonaws.com/2017.08.22.10.11.23-0.jpg

Suspect this is a bug in the string parsing in the ldap plugin.

**Comment by kenrestivo-stem** [comment] 2017-08-22 17:43
The bug appears to be in the string parsing in the command-line client.

I was able to successfully save the binddn with spaces, correctly using the REST API as JSON.

**Comment by jefferai** [comment] 2017-08-22 17:44
How are you invoking the CLI?

**Comment by kenrestivo-stem** [comment] 2017-08-22 21:09
```sh
vault write auth/ldap/config \
      url='ldap://identity.stem.com' \
      binddn='cn=System Authorizer,ou=people,ou=hq,dc=stem,dc=com' \
      bindpass='REDACTED!' \
      userattr='uid' \
      groupdn='ou=hq,dc=stem,dc=com' \
      groupfilter='(&(objectClass=posixGroup)(memberUid=%s))' \
      groupattr='memberOf' 
```

**Comment by jefferai** [comment] 2017-08-22 21:34
This is a bit strange because it works normally:

```
$ vault write secret/foo bar='foo bar'
Success! Data written to: secret/foo

$ vault read secret/foo
Key             	Value
---             	-----
refresh_interval	768h0m0s
bar             	foo bar
```

**Comment by jefferai** [comment] 2017-08-30 19:27
I'm having trouble reproducing:
```
$ vault auth-enable ldap
Successfully enabled 'ldap' at 'ldap'!

$ vault write auth/ldap/config \
>       url='ldap://identity.stem.com' \
>       binddn='cn=System Authorizer,ou=people,ou=hq,dc=stem,dc=com' \
>       bindpass='REDACTED!' \
>       userattr='uid' \
>       groupdn='ou=hq,dc=stem,dc=com' \
>       groupfilter='(&(objectClass=posixGroup)(memberUid=%s))' \
>       groupattr='memberOf'
Success! Data written to: auth/ldap/config

$ vault read auth/ldap/config
Key             Value
---             -----
binddn          cn=System Authorizer,ou=people,ou=hq,dc=stem,dc=com
bindpass        REDACTED!
certificate
deny_null_bind  true
discoverdn      false
groupattr       memberOf
groupdn         ou=hq,dc=stem,dc=com
groupfilter     (&(objectClass=posixGroup)(memberUid=%s))
insecure_tls    false
starttls        false
tls_max_version tls12
tls_min_version tls12
upndomain
url             ldap://identity.stem.com
userattr        uid
userdn

The following warnings were returned from the Vault server:
* Read access to this endpoint should be controlled via ACLs as it will return the configuration information as-is, including any passwords.
```
Obviously I can't log in with this info, but you can see that the binddn is saved correctly.

Any chance this works for you on 0.8.1 or if you try a dev server?

**Comment by jefferai** [comment] 2017-08-31 20:59
Closing for now as not reproducible, please comment if you have a reproducible test case.

**Closed by jefferai** 2017-08-31 20:59 UTC
