### ISSUE TITLE
CLI: vault secrets list - add option to filter by engine type

### ISSUE THREAD

**Issue by varshavaradarajan** [hashicorp/vault#6019] opened 2019-01-09 17:20 UTC
**Is your feature request related to a problem? Please describe.**
Given that there can be many secrets engines enabled, its useful to have an option to filter by the engine type while using `vault secrets list`.

**Describe the solution you'd like**
Provide a `type` flag for the `vault secrets list` command. This will list secrets belonging to the specified engine type only. If the type passed is invalid, shows an error. 

**Additional context**
Related issue: https://github.com/hashicorp/vault/issues/5347

**Comment by lucymhdavies** [comment] 2019-02-28 14:50
As someone who manages a Vault instance with almost 150 secret engines mounted, this would be a very useful feature.

**Comment by aphorise** [comment] 2020-08-09 22:21
What about leveraging **`jq`**? - eg: 

```bash
E1='kv'; E2='system'; vault secrets list -format=json | jq -r ".[] | select(.type==\"${E1}\" or .type==\"${E2}\")" ;
```

```json
 {
   "uuid": "0935371e-2c96-87fc-d0b0-7d24d9ca5171",
   "type": "kv",
   "description": "",
   "accessor": "kv_31eeab06",
   "config": {
     "default_lease_ttl": 0,
     "max_lease_ttl": 0,
     "force_no_cache": false
   },
   "options": {
     "version": "2"
   },
   "local": false,
   "seal_wrap": false,
   "external_entropy_access": false
 }
 {
   "uuid": "d46cc605-1fc5-50b0-385b-c0131357b043",
   "type": "system",
   "description": "system endpoints used for control, policy and debugging",
   "accessor": "system_9d3b34b7",
   "config": {
     "default_lease_ttl": 0,
     "max_lease_ttl": 0,
     "force_no_cache": false,
     "passthrough_request_headers": [
       "Accept"
     ]
   },
   "options": null,
   "local": false,
   "seal_wrap": false,
   "external_entropy_access": false
 }
```

**Comment by vishalnayak** [comment] 2021-06-24 21:08
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.

**Comment by aphorise** [comment] 2022-08-31 18:39
Hey @varshavaradarajan @lucymhdavies - I'm curious of your thoughts to my suggestions with `jq` and if there's any reasons why doesn't already suffice?

**Comment by lucymhdavies** [comment] 2022-08-31 19:39
Oh agreed, jq is a pretty good way of handling this.

If you're in a position where you're interacting with the secrets list programmatically, it's probably relatively safe to assume you have some familiarity with JSON processing.

Adding filters to this one specific API endpoint is not something to do in isolation; it'd be something we'd likely want to add in more places too. Not entirely sure what a generic version would look like.

**Comment by varshavaradarajan** [comment] 2022-09-02 14:46
Agreed, jq should be enough if it is worth it to get all the secrets from the server and then filter ourselves on the client side.

**Comment by aphorise** [comment] 2022-09-02 17:55
Thank you for the inputs. I'll closed this and it's good there's an agreed / confirmed approach in case anyone else stumbles upon this.

**Closed by aphorise** 2022-09-02 17:55 UTC
Labels: enhancement, core/cli
