### ISSUE TITLE
Encrypt as a Service - Encryption key export

### ISSUE THREAD

**Issue by housseinabdo** [hashicorp/vault#5332] opened 2018-09-13 16:20 UTC
I am trying to use vault to create data encyption keys (AES 256 keys) and use them to encrypt/decrypt data. I succeded to generate keys, encrypt and decrypt using Vault by following the steps on this link https://www.vaultproject.io/guides/encryption/transit.html. 

The question is, how can export the keys to use them somewehre else (encrypt not using Vault) and the decrypt with the same keys using Vault?

Thanks in advance

**Comment by jefferai** [comment] 2018-09-14 13:29
Duplicate of https://groups.google.com/d/msgid/vault-tool/5e1024ba-804a-40c1-9fab-0e20705330ee%40googlegroups.com

**Closed by jefferai** 2018-09-14 13:29 UTC

**Comment by housseinabdo** [comment] 2018-09-14 13:43
@jefferai sorry, I saw that it would be better to ask questions on groups.google. So I duplicated it
