### ISSUE TITLE
UI not displaying changes even in Incognito for Role that were applied

### ISSUE THREAD

**Issue by kennyatzeroeyes** [hashicorp/vault#11613] opened 2021-05-15 18:10 UTC
**Describe the bug**
Have stopped, upgraded and opened in incognito, but changes to pki secret engine like default/max ttl are not displaying as they are set on the backend. It's still displaying previous value.

**To Reproduce**
1. Open UI
2. Edit role
3. Expand options and set Default / Max TTL to some other value
4. Open Incognito, login and browse to said role details

**Expected behavior**
Value change is displayed as expected in UI

**Environment:**
1.7.1
* Server Operating System/Architecture:
Ubuntu Linux 18.04

Vault server configuration file(s):

```hcl
log_level = "Trace"

api_addr = "http://ip.address.hidden:8200"
cluster_addr = "http://ip.address.hidden:8201"
ui = true

disable_mlock = true

storage "gcs" {
  bucket = "hidden"
}

HTTP listener
listener "tcp" {
  address = "[::]:8200"
  tls_disable = 0
}


# HTTPS listener
listener "tcp" {
  address       = "[::]:8200"
  tls_cert_file = "/path/to/self/signed/file.crt"
  tls_key_file  = "/path/to/self/signed/file.key"
}
```

**Additional context**
Using self signed cert, but is trusted and endpoints if matters are entered and accessible.

**Comment by ReCodee** [comment] 2022-10-01 12:25
@vishalnayak, is this issue still relevant?
I'd like to work on this issue

**Comment by hellobontempo** [comment] 2023-04-12 18:38
Closing this issue as I was unable to reproduce as of 1.13. Please reopen you're still experiencing the issue and, if possible, could you report the network request data for the `POST` request when updating a role 🙂

**Closed by hellobontempo** 2023-04-12 18:38 UTC
Labels: ui, bug, good-first-issue
