### ISSUE TITLE
Step down causing vault to hang

### ISSUE THREAD

**Issue by ElliotG** [hashicorp/vault#3276] opened 2017-09-01 07:14 UTC
**Environment:**

* Vault Version: 0.7.3
* Operating System/Architecture: Ubuntu 16.04.3 LTS

**Vault Config File:**

backend "consul" {
    address = "127.0.0.1:8500"
    redirect_addr = "https://0.vault.domain:443"
    cluster_addr = "https://10.1.1.1:8200/"
    path = "vault/"
    token = "..."
}

cluster_name = "hashistack"

listener "tcp" {
    address = "0.0.0.0:8200"
    tls_cert_file = "/etc/ssl/certs/foo.crt"
    tls_key_file = "/etc/ssl/certs/foo.key"
}

**Startup Log Output:**

**Expected Behavior:**
Hitting https://${addr}/v1/sys/step-down should cause the leader to step down. The replica's should make a mad scramble for leader, and after 10 seconds the former leader will enter the fray. Either way, within 30 seconds, Vault should have a new leader.

**Actual Behavior:**
Vault 0: Leader
Vault 1: Replica

Vault 0 started the step down procedure:
Vault 0 --> [WARN ] core: stepping down from active operation to standby
<preseal, cluster listeneners, rpc listeners...>
Vault 0 --> [INFO ] rollback: stopping rollback manager

After that, nothing. Vault 1 claimed that Vault 0 was still the leader. SSH'd into Vault 0, and ran "vault status". This command hung. Moments after that, Nomad went through and killed all of it's jobs.

**Steps to Reproduce:**
1. SSH'd to Vault 0, ran vault status, everything looks normal
2. SSH'd to Vault 1, ran vault status, everything looks normal
3. Ran curl https://${addr}/v1/sys/step-down on Vault 0 and waited 30 seconds
4. Ran curl https://${addr}/v1/sys/leader on Vault 0 and command hangs
5. On Vault 0, we run “vault status” and it hangs
6. On Vault 1, we run “vault status” and it says “mode standby, leader <vault 0 address>”
7. Nomad attempts to refresh all the tokens for all (most) the jobs, and fails with a 503 from Vault
8. Nomad stops all the docker containers

If we delete both nodes, then they come back just fine.

**Important Factoids:**
-We are running 8-10 separate vault clusters, and this only fails on 1 of them, the one with the most consul data. We also noticed that during a cycling of Consul, the vault servers kept promoting each other back and forth.

Here is our theory: could vault be failing to release it's lock (core/lock) in consul, and that this event isn't being logged? Something in Vault must be deadlocking, and this seems like a convenient answer.

We aren't sure where to debug from here, and was hoping for some help:

1 - Is this a symptom of another known bug/misconfiguration?
2 - Is there a way for us to generate a stack trace from Vault when it's frozen like this?

**Comment by jefferai** [comment] 2017-09-01 13:29
If Consul is in an unhappy state this will certainly affect Vault operations. Your theory could be true, except it could be that it's not failing to log it, but rather that what's actually hanging are calls to Consul that occur as part of the step-down process.

It'd be good to understand the state of your Consul cluster when this is happening. Are you near your RAM or CPU limits on the Consul boxes? Is leadership flapping?

You can generate a stacktrace from vault by sending it a SIGABRT or SIGQUIT (but this will also kill the process).

**Comment by ElliotG** [comment] 2017-09-01 23:30
Hey Jeff, thanks for the response.

*re: Consul performance*
-CPU is consistently <1%, load <1
-Box is hovering at 3GB of mem out of 7

*re: Consul flapping*
-Is there a log line I should look for when consul election changes? Not sure where to go for that.

*re: vault stacktrace*
-Will do, in the next 3-4 days run this and see what I get. (Each test requires a prod outage, so will have to iterate slowly. We've failed to get this to reproduce in any of the other envs).

**Comment by jefferai** [comment] 2017-09-01 23:40
I'm not sure what you'd look for in terms of Consul log lines, but I imagine if leadership is flapping there will be something.

You could also try upgrading to 0.8.1, although 0.8.2 will be out probably early Tuesday so could wait for that (it is much faster in failover scenarios in many conditions). We changed some logic around in related paths. Additionally, we changed some locking on the enterprise side but haven't ported it yet, I'll see if that can happen for 0.8.2.

**Comment by nrvale0** [comment] 2017-09-01 23:41
Elliot,

Both Vault and Consul support a '-log-level=' option. Default is 'info' and the next step up in verbosity is 'debug'. (This is contrary to our previous conversation btw...I was mistaken about there being something between info and debug.) 

* https://www.consul.io/docs/agent/options.html#_log_level

It's also in Vault though harder to find mentioned in the docs.

**Comment by jefferai** [comment] 2017-09-01 23:43
Vault doesn't have nearly as many command line flags so It's not on its own page. It's in the output of vault server -h :-/

**Comment by jefferai** [comment] 2017-09-02 01:34
A couple of other things:

1) In your OP you said "replica". I assume you are just using normal HA? Vault OSS doesn't have any knowledge of replication.

2) Do you have server logs from both the active and standby? Debug/trace would be better but I'll take what I can get.

3) I checked the diff between 0.7.3 and 0.8.0 and as I thought I remembered, we did make changes to how step-down and sealing behave to work around possible lock contention issues. It's entirely possible this problem is already solved in the 0.8.x series.

**Comment by ElliotG** [comment] 2017-09-03 21:18
1 - Yeah, normal HA of Standby + Leader. Used the wrong term above

2 - Yes, have the server logs of both, but not at the debug level, will get that enabled.

3 - Will aim for the upgrades first

**Comment by holtwilkins** [comment] 2017-09-05 07:52
Ok, we've reproduced this with Vault 0.8.1.  I was able to issue a few step-downs successfully waffling back and forth between the two nodes until it eventually repro'd.

I've attached the stacktrace along with the couple of statements immediately before vault was hung and I issued it a SIGABRT.

I issued the step-down at 7:12:55 UTC as you can see in the log.  `vault status` was then hanging querying this local machine, and the ELB removed it from being inservice, etc, until I issued the SIGABRT at 7:15:52 it looks like.

[vault.txt](https://github.com/hashicorp/vault/files/1276502/vault.txt)

**Comment by jefferai** [comment] 2017-09-05 13:11
I @holtwilkins ,

Thanks, the stack trace was super useful. At this point I see *where* it's hanging, still trying to sort out why though.

**Comment by jefferai** [comment] 2017-09-05 13:56
Here are my thoughts so far:

* It's hanging when the rollback manager is waiting for outstanding rollback requests to finish. This means either the logic for the requests (using a wait group) or the requests themselves are to blame.
* I can't see anything obviously wrong in the rollback manager logic. A few things that maybe could be cleaned up, but nothing that I can definitively say would cause an issue. So -- doesn't mean it isn't there, just that if so it's not immediately apparent.
* Another possibility is that the rollback requests are, in fact, taking a very long time to finish. What would help here are a couple of things:
** Can you give us a list of the types of mounts you're using? (Both secret and auth.)
** Any chance you can provide more logs? Specifically, it would be good to know if the paths shown when the rollback manager puts out "rollback: attempting rollback" (on trace level logging) changes over time. This would indicate that some prior rollback operation didn't complete yet.

**Comment by ElliotG** [comment] 2017-09-06 05:16
*Mounts:*
- AWS
- Consul
- Cubbyhole
- Postgresql
- PKI
- Generic
- SSH
- System

**Comment by calvn** [comment] 2017-09-08 17:05
@ElliotG Would you be able to provide us with more verbose logs, possibly at the trace level? As Jeff mentioned, it would help immensely if we were able to look at which path(s) the rollback manger got stuck in when attempting to perform a rollback on stop.

**Comment by holtwilkins** [comment] 2017-09-11 06:35
[vault.txt](https://github.com/hashicorp/vault/files/1291576/vault.txt)
Hey @calvn , I've repro'd with trace logging enabled, but it seems to have added only one line of logging output.  Attached log shows the node receiving the step-down, but the other node never picked it up.  I then issued it a sigabrt again to get another stacktrace.

**Comment by jefferai** [comment] 2017-09-11 16:07
Hi @holtwilkins ,

Any chance you can provide more logs? Specifically, it would be good to know if the paths shown when the rollback manager puts out "rollback: attempting rollback" (on trace level logging) changes over time. This would indicate that some prior rollback operation didn't complete yet.

**Comment by holtwilkins** [comment] 2017-09-11 22:41
Hey @jefferai , I'd be happy to, but they provide a bit too much information about our setup to post on github I think.  I'll send you both full Vault servers journald logs privately.

**Comment by jefferai** [comment] 2017-09-19 13:05
This is being followed up privately, closing.

**Closed by jefferai** 2017-09-19 13:05 UTC
