### ISSUE TITLE
Failing to get public keys from keybase when init of a vault

### ISSUE THREAD

**Issue by arthurlogilab** [hashicorp/vault#2846] opened 2017-06-12 15:14 UTC
Following https://www.vaultproject.io/docs/concepts/pgp-gpg-keybase.html#initializing-with-keybase

I get : 

```
# vault init -key-shares=3 -key-threshold=2     -pgp-keys="keybase:arthurlogilab,keybase:user2,keybase:user3"
invalid value "keybase:arthurlogilab,keybase:user2,keybase:user3" for flag -pgp-keys: openpgp: invalid argument: no armored data found
invalid argument: no armored data found
Usage: vault init [options]
[snip]
# vault --version
Vault v0.7.3 ('0b20ae0b9b7a748d607082b1add3663a28e31b68')
```
Am I missing something ? Does keybase cli need to be installed ? Installed and configured ?

**Comment by jefferai** [comment] 2017-06-14 16:31
*Probably* a duplicate of #2372

**Comment by vishalnayak** [comment] 2021-06-22 19:22
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.

**Closed by vishalnayak** 2021-06-22 19:22 UTC
Labels: bug, core, version/0.7.x
