### ISSUE TITLE
how can we read the policies mapped to the teams is there any command for that. I didn't see in documentation

### ISSUE THREAD

**Issue by SivaKrishna05** [hashicorp/vault#5027] opened 2018-08-01 19:12 UTC
I am looking for the command to read the policies associated with teams already mapped for org.
Please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues.

With over 1700 subscribers, the mailing list gets a _lot_ more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the list.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by jefferai** [comment] 2018-08-01 20:50
duplicate of https://groups.google.com/d/msg/vault-tool/QSqjIpZroB0/_Up2rw2rBwAJ

**Closed by jefferai** 2018-08-01 20:50 UTC
