### ISSUE TITLE
Sporadic net/http: Invalid Header field value on vault auth aws

### ISSUE THREAD

**Issue by jamesongithub** [hashicorp/vault#4135] opened 2018-03-15 23:12 UTC
**Environment:**
ec2
running vault-cli via jenkins

* Vault Version: Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')
* Operating System/Architecture:

**Vault Config File:**

HA vault behind elb

**Startup Log Output:**

**Expected Behavior:**

Should authenticate correctly.

**Actual Behavior:**

Sporadically hits this error.

**Steps to Reproduce:**

Setup HA vault behind elb
1) auth with ec2 iam role
2) vault auth -method=aws -token-only role=myRole
3) 
```
Put ${HOSTNAME}:8200/v1/auth/aws/login: net/http: invalid header field value "\x1f\xffa\x95\xa1\x06!FC\xb6\x90s\xf7\xef\x1dy\xc4t\x99l\x147\t\x8bV\xe6ԧ\x83\xc6~vGn\x92wg\x1b\xb4\\\xdd\xd2i^y\xcf\xe7 \x9f\x930BV\x80J \"VL\x90\xa5\xb8\xc7%\f+:\xcb~\xd7X\x80\xfd\xbf\xbabu\x92\x94s\xfcF(1\x01%j\x9d\xb0~\xb2\xcd\xda\x19\xbd6\xd2۱\xe0\xd8M\xb1\x8eW\xc8T\xb5&\x1d\x91H\xebb\xd5\x1e!\x90\xdd}i\xbc\xb9Sz\xea\xad\xf5\x97w\v\xc8\xff\xef:;\xa9\n\xe8\\'~&\xe0N\x96Խ\xec\x17\xd3h\x9a\t\x01\x17t\x83-\xe7\x
...
qK\"\r%\n\x14\x04HXNR\xee4\xa3W\xbc\xb5\xb9ia\v\x01\xe4\x97\x05\x18\v\v\xa6\x93a\xf2{\x11\xa8\xcf\x13\xe0\x95\xe8W\x99y0\xacq\vXhSn\x99\xdf^\x01\xf0Q\x99 \xa6n\xef\xf8\x95Ԩ\x13\x89uw<\xa2\x8c\x90\xe1\x96\xc3<\xf0\xcdټ\x82;\xc5\x14N\xa1\xf99\xe3h\xac{\xd7\xea\x10\x15\x91\x90ڱ\xd4G\xf0\xb1-\xa2" for key X-Vault-Token
```

**Important Factoids:**

**References:**

**Comment by vishalnayak** [comment] 2018-03-16 16:46
@jamesongithub We have not encountered this error in our testing. It would be helpful if there is a way for us to be able to reproduce this. Can you see if you can reproduce it in a deterministic manner, and with the latest version of Vault if possible?

@joelthompson Do you see anything suspicious?

**Comment by jamesongithub** [comment] 2018-03-16 20:37
@vishalnayak Does your testing include HA with elb? I'm wondering if it happens when the standby receives the first request. I don't have a means to upgrade vault at the moment.

I also noticed in your docs for `vault login` this `header_value` is required.

https://www.vaultproject.io/docs/auth/aws.html#perform-the-login-operation

vault login -method=aws header_value=vault.example.com role=dev-role-iam

0.8.3 only has `vault auth` so probably not related?

**Comment by jamesongithub** [comment] 2018-03-16 20:54
I'm seeing these on the active node.

```
2018/03/16 20:35:06.902363 [INFO ] expiration: revoked lease: lease_id=auth/aws/login/ba8b261c190dda{REDCATED}ff8e40bb36e43
2018/03/16 20:45:05.941659 [INFO ] expiration: revoked lease: lease_id=auth/aws/login/73d250a46a6f39f4{REDCATED}e8564a31946c187
2018/03/16 20:45:06.929222 [INFO ] expiration: revoked lease: lease_id=auth/aws/login/59df15a5db36368{REDCATED}d1d8cbdaa5
```

**Comment by joelthompson** [comment] 2018-03-17 00:45
@vishalnayak -- not really seeing anything that pops out to me. Biggest question is that I'm not sure what is throwing the error message -- is it the vault CLI sending the request to the Vault server, or a standby Vault server forwarding to active, or the active Vault server sending the STS request?

@jamesongithub -- can you try using the latest Vault CLI? It should be backwards compatible with Vault server 0.8.3 (and it will allow you to use both the `vault auth -method=aws` and `vault login -method=aws` commands, both _should_ be identical), so you don't have to upgrade your Vault servers. Also, can you try actively directing the request to an inactive Vault server behind an ELB to see if that reproduces the issue? Also, it looks like the end of the error message got cut off in GitHub. Could you paste the very end (I'd expect it to say something like "for key ..."). That would be very helpful.

FYI, the header_value is only required if your Vault admin has configured your AWS auth backend to require it, and it shouldn't make a difference here, but it does.

**Comment by vishalnayak** [comment] 2018-03-18 17:43
@jamesongithub 

> Does your testing include HA with elb?
No.

> 0.8.3 only has `vault auth` so probably not related?
As Joel said, `vault login` and `vault auth` should behave identically. So, this seems unrelated as well.

> I'm seeing these on the active node.

```
2018/03/16 20:35:06.902363 [INFO ] expiration: revoked lease: lease_id=auth/aws/login/ba8b261c190dda{REDCATED}ff8e40bb36e43
```

These look like expirations of the tokens from the previous successful logins and hence are unrelated too.


Given the intermittent nature of the failure, I do suspect one possibility. Are all the clients using the CLI to login or are some using the API (https://www.vaultproject.io/api/auth/aws/index.html#login) directly? An accidental addition of undesired characters in the header values might cause this issue. The CLI is unlikely the culprit, because if it was, the issue would have been consistent.

**Comment by jamesongithub** [comment] 2018-03-20 23:39
@vishalnayak We use both the CLI and the api to login, but only have seen this when using the cli.

@joelthompson I've configured the cli to go directly to the standby and/or the active node and still have seen the issue. Standby seem to be redirecting correctly. I don't see anywhere in the vault conf where `header_value` is configured. I've updated the OP w/ the key: it's the `X-Vault-Token`. Upgrading the cli to 0.9.5 we now get this:

`Error authenticating: Configured Vault token contains non-printable characters and cannot be used.`

https://github.com/hashicorp/vault/pull/3841

So at least it's preventing us to call the api with an invalid token. So an encoding issue? I'm not familiar with how vault encodes the token. We're running the vault-cli on jenkins and our default encoding is `en_US.UTF` set via the `LANG` env var if that helps.

**Comment by jefferai** [comment] 2018-03-21 00:15
Probably you have leading or trailing non printable characters coming from somewhere when passing around the token.

**Comment by joelthompson** [comment] 2018-03-21 00:38
@jamesongithub -- if you retry immediately, do you get the same behavior?

Also, when this happens, can you check the contents of the VAULT_TOKEN environment variable and the ~/.vault-token file and see if there's anything weird in those places?

**Comment by joelthompson** [comment] 2018-03-21 00:41
Also, the header_value is described [here](https://www.vaultproject.io/docs/auth/aws.html#iam-auth-method):

> In addition, Vault allows you to require an additional header, X-Vault-AWS-IAM-Server-ID, to be present to mitigate against different types of replay attacks (such as a signed GetCallerIdentity request stolen from a dev Vault instance and used to authenticate to a prod Vault instance). Vault further requires that this header be one of the headers included in the AWS signature and relies upon AWS to authenticate that signature.

It is controlled with the `iam_server_id_header_value` parameter to the [auth/aws/config/client](https://www.vaultproject.io/api/auth/aws/index.html#iam_server_id_header_value) API endpoint.

**Comment by jamesongithub** [comment] 2018-03-21 01:01
@joelthompson Thanks for the link. Yeah, it looks like our of our build servers had binary content in ~/.vault-token some how. That's why it was sporadic. We pretty much only use the vault-cli or the api to auth. To my knowledge, nothing writes directly there. If the response token is invalid, will the token be saved anyway?

**Comment by jefferai** [comment] 2018-03-21 01:19
It shouldn't take precedence, no. (And in my long experience using Vault, it doesn't.) My guess is that something in that command isn't working right so it's not being set to what you think it's being set to.

**Comment by jamesongithub** [comment] 2018-03-21 01:26
Oh I mean, once the token file is corrupt, subsequent auth's will fail, without trying to overwrite it.

**Comment by joelthompson** [comment] 2018-03-21 01:26
@jefferai -- just thinking -- does it make sense for `vault auth`/`vault login` commands to send an authentication token for any method other than `token`? Regardless of what ~/.vault-token gets set to, the vault auth command shouldn't really need it.

**Comment by jefferai** [comment] 2018-03-21 01:41
I'm unaware of why `vault auth/vault login` need `~/.vault-token` _ever_ except to write to it. My guess is that reading it is just common/shared behavior, and a bug in this case.

**Comment by jefferai** [comment] 2018-04-11 19:06
Closing as the root cause was identified and there isn't really any work to schedule on this right now.

**Closed by jefferai** 2018-04-11 19:06 UTC
