### ISSUE TITLE
SSH engine certificate store and revocation list

### ISSUE THREAD

**Issue by lhw** [hashicorp/vault#11420] opened 2021-04-20 15:12 UTC
**Is your feature request related to a problem? Please describe.**
A great feature for the SSH engine would be to allow it to retain a list of signed SSH certificates, similar to how the SSL PKI engine works. This could allow the administrators to have an overview of currently active SSH certificates and in case of lost certificates a revocation list could be generated from this data source which in turn could be synced to the nodes.

**Describe the solution you'd like**

- Implementation of a certificates list for the ssh engine similar to the SSL PKi engine.
- SSH Key revocation-/blacklist similiar to a SSL CRL/OCSP list 

**Describe alternatives you've considered**
Parsing the audit log for all interactions with the ssh engine and creating an external data source to the same effect.

**Comment by cipherboy** [comment] 2023-01-12 14:23
Closing as duplicate of #3377.

**Closed by cipherboy** 2023-01-12 14:23 UTC
Labels: ecosystem, enhancement, feature-request
