### ISSUE TITLE
Can't apply Signed SSH Certificates to ansible

### ISSUE THREAD

**Issue by thachnv92** [hashicorp/vault#14777] opened 2022-03-30 04:57 UTC
Hello,

I follow this guide about [Signed SSH Certificates](https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates).
I can use SSH CA key signed with private key to SSH server. But I’m stucking when apply this to ansible.

ssh -o StrictHostKeyChecking=no -i cicd-signed-key.pub -i privatekey username@servername “hostname” => It’s Ok.
but how to I config in ansible to get both the SSH CA key signed and private key?
I can’t do it or find anything documents/guides.

Please help me.
Thank you.

**Comment by gemone** [comment] 2022-03-30 10:25
You can try `man ssh_config`. Specify the certificate by configuring SSH config.

```
     CertificateFile
             Specifies a file from which the user's certificate is read.  A corresponding private key must be provided separately in order to use this certificate either
             from an IdentityFile directive or -i flag to ssh(1), via ssh-agent(1), or via a PKCS11Provider or SecurityKeyProvider.

             Arguments to CertificateFile may use the tilde syntax to refer to a user's home directory, the tokens described in the TOKENS section and environment vari‐
             ables as described in the ENVIRONMENT VARIABLES section.

             It is possible to have multiple certificate files specified in configuration files; these certificates will be tried in sequence.  Multiple CertificateFile
             directives will add to the list of certificates used for authentication.
```

I can't also find the documents of ansible about ssh certificate login.

**Comment by stevendpclark** [comment] 2022-03-31 12:09
Hi @thachnv92! 

As this looks like a question and not a bug report, we ask that these sorts of posts be made in our [Discuss forum](https://discuss.hashicorp.com/c/vault/30). I'm going to go ahead and close this issue now, but if you have a bug report or enhancement request, please do feel free to file that here.

**Closed by stevendpclark** 2022-03-31 12:09 UTC
Labels: question
