### ISSUE TITLE
`vault path-help` against a non leader fails

### ISSUE THREAD

**Issue by martinssipenko** [hashicorp/vault#2709] opened 2017-05-11 07:00 UTC
```sh
/ # vault path-help secret
Error reading help: Error making API request.

URL: GET https://127.0.0.1:8200/v1/secret?help=1
Code: 500. Errors:

* Vault is in standby mode
```

**Comment by jefferai** [comment] 2017-05-11 11:46
You didn't specify your Vault version, but this should be fixed in 0.7.2.

**Comment by martinssipenko** [comment] 2017-05-11 11:47
Thanks

**Closed by jefferai** 2017-05-11 11:46 UTC

**Comment by tomwilkie** [comment] 2018-01-02 17:31
I've seeing this with Vault 0.9.1:

```
$ curl -v --CAcert terraform/uswest-cluster/vault-ca.pem https://vault.uswest-cluster.redacted:8200/v1/ssh/ca/config?help=1
*   Trying 34.215.123.211...
* TCP_NODELAY set
* Connected to vault.uswest-cluster.redacted (xxx.xxx.xxx.xxx) port 8200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: terraform/uswest-cluster/vault-ca.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: O=redacted; CN=vault.uswest-cluster.redacted
*  start date: Jan  2 12:50:48 2018 GMT
*  expire date: Jan  1 12:50:48 2021 GMT
*  subjectAltName: host "vault.uswest-cluster.redacted" matched cert's "vault.uswest-cluster.redacted"
*  issuer: O=redacted; CN=Root Vault CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fafef804600)
> GET /v1/ssh/ca/config?help=1 HTTP/2
> Host: vault.uswest-cluster.aws.redacted:8200
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 500 
< cache-control: no-store
< content-type: application/json
< content-length: 40
< date: Tue, 02 Jan 2018 17:29:21 GMT
< 
{"errors":["Vault is in standby mode"]}
* Connection #0 to host vault.uswest-cluster.redacted left intact
```

I'll note on other paths, I get a `location` response header for the redirect.

**Comment by jefferai** [comment] 2018-01-04 02:26
I'm not able to reproduce this, although I *do* see an error with curl saying that I'm missing a client token, if I don't provide one (I'm not sure at the moment if this is expected or not). Are you sure that you are running Vault 0.9.1 on the server, as opposed to just the client?

**Comment by jefferai** [comment] 2018-01-04 02:27
On further looking I believe that we do require a client token -- but the reason I see that is because the standby check happens before the token check and the standby check is passing due to it being help, which indicates it working as expected.
