### ISSUE TITLE
Feature Requst: acme client support

### ISSUE THREAD

**Issue by jdelic** [hashicorp/vault#4362] opened 2018-04-15 12:21 UTC
Feature Request: acme client/challenge support
=================================

A server implementation of the acme protocol was previously discussed in 2015 in #668. This is not that. :)

The problem space
---------------------------

We deploy Vault for secret management. Many of our non-customer-facing systems use certificates issued through LetsEncrypt, which delivers a convenient certificate that can still be validated by common public CAs. What annoys me is that `certbot` and other available acme implementations require us to tunnel `http` challenges or set up credentials for production systems to access DNS APIs to process `dns` challenges. Even acme implementations that run inside of server software (like lua-based plugins for haproxy), result in the suboptimal situation that the retained certificate must be distributed through the cluster or every endpoint needs to request its own certificate.

An idea
-----------

While discussing a solution based around the consul kv store and consul-template, I realized that it would be so much nicer to do the following:

* Have Vault generate the certificate private key and CSR
* Create the challenge and communicate with an acme endpoint when triggered through an API
* Have the CA (LetsEncrypt) talk to a public endpoint that is tunneled through a vault instance (i.e. Vault directly handles the `.well-known/acme-challenge/` request and response)
* Have Vault receive, validate and store the certificate from the CA
* Vault would also schedule and handle certificate renewal
* Clients inside the network can use `consul-template` and `nomad` and the Vault API to receive the certificate, private key and certificate chain as needed

Vault ACLs, tokens and response wrapping could then be used to their full effect. It would be a beautiful solution in my opinion.

**Comment by remilapeyre** [comment] 2019-09-23 15:00
Hi @jdelic this is a duplicate of https://github.com/hashicorp/vault/issues/4950 where some discussion has happened, I suggest we close this issue in favor of #4950

**Comment by mholt** [comment] 2019-10-16 21:16
@remilapeyre This issue was created first, and I think this one has more actionable material.

**Comment by vishalnayak** [comment] 2021-06-24 20:12
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.

**Closed by vishalnayak** 2021-06-24 20:12 UTC
Labels: ecosystem, feature-request

**Comment by kalafut** [comment] 2021-06-25 21:02
Please see https://github.com/hashicorp/vault/issues/4950 for continued discussion.
