### ISSUE TITLE
vault ui: edit in json mode, after press keyboard enter button , it doesnt enter in new line

### ISSUE THREAD

**Issue by zoezhangmattr** [hashicorp/vault#26237] opened 2024-04-02 02:41 UTC
**Describe the bug**

vault version 1.15.2 (after upgraded from 1.11.0)
chrome version Version 123.0.6312.87 (Official Build) (arm64)

in the vault ui, when trying to update an existent kv value in json mode
press the enter button , it goes back to the start point of the json content

working fine in version 1.11.0

**To Reproduce**
1. Run `vault write ...`
2. Run `vault login....`
3. See error

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by timonych** [comment] 2024-04-24 18:38
Try to update last 1.15 version, but not to 1.16.1 - the problem is exist.

**Comment by marcboudreau** [comment] 2024-05-06 20:27
@zoezhangmattr Though your description of the issue is more on point, the underlying problem has already been reported in #26634 

I'm going to close this Issue as a duplicate. Thank you for taking the time to report.

**Closed by marcboudreau** 2024-05-06 20:27 UTC
Labels: ui, ticketed, reproduced
