### ISSUE TITLE
vault should tolerate line endings in $HOME/.vault-token

### ISSUE THREAD

**Issue by dch** [hashicorp/vault#1902] opened 2016-09-19 09:24 UTC
If `$HOME/.vault-token` has a \n appended, as many text editors like to do silently, `vault status` and related commands will fail:

```
$ vault status
Error checking seal status: Get https://vault.blah.com:8200/v1/sys/seal-status: net/http: invalid header field value "blah-blah\n" for key X-Vault-Token
```

I've looked a bit at the source in `builtin/token/disk/command.go` and don't see where this is retrieved. Did I miss something?

**Comment by jefferai** [comment] 2016-09-19 13:40
Duplicate of #1774

**Closed by jefferai** 2016-09-19 13:40 UTC
