### ISSUE TITLE
Improve proxy_protocol error logging

### ISSUE THREAD

**Issue by sidewinder12s** [hashicorp/vault#4066] opened 2018-03-02 23:43 UTC
**Feature Request:**
Improve error logging of proxy_protocol failures. If a load balancer starts sending a proxy protocol header to a Vault instance (or any client I suppose sends it), it just fails to respond with the message below. It should either ignore the header or state why its failing.

**Environment:**

* Vault Version: v0.9.3
* Operating System/Architecture: docker/ubuntu/amd64

**Vault Config File:**
No proxy_protocol configuration.

**Client Log**
```
vault login -method=ldap -username=username
Password (will be hidden):
Error authenticating: Put https://127.0.0.1:8200/v1/auth/ldap/login/username: remote error: tls: record overflow
```
**Expected Behavior:**
Vault should continue to work.

**Actual Behavior:**
The client can no longer talk to Vault through the LB.

**Steps to Reproduce:**
Add a proxy protocol headers to a load balancer configuration that is forwarding traffic to vault, without updating Vault's configuration with any proxy_protocol settings.

**Comment by michelvocks** [comment] 2020-01-21 09:25
Hi @sidewinder12s!

Thank you for opening this issue and sorry for the super late reply!
I've tried to reproduce this with the latest Vault version (1.3.2) but was unable to do so.
Would you mind to give it another try with the latest Vault version?

Cheers,
Michel

**Comment by sidewinder12s** [comment] 2020-01-23 03:26
@michelvocks I no longer have access to the infrastructure in question.

**Comment by michelvocks** [comment] 2020-01-23 12:29
@sidewinder12s Thanks for the quick reply. I will close this issue for now since it is not reproducible. Feel free to open a new issue if you tackle the same issue again in the future.

**Closed by michelvocks** 2020-01-23 12:29 UTC
Labels: bug, core, version/0.9.x, waiting-for-response
