### ISSUE TITLE
AWS SDK version is too old to support pod-level permissions in AWS EKS

### ISSUE THREAD

**Issue by danielmittelman** [hashicorp/vault#7986] opened 2019-12-08 17:04 UTC
**Is your feature request related to a problem? Please describe.**
AWS has released pod-level permissions a few months ago, allowing Vault to be run in EKS without having to give all the neighboring pods the same permissions to the AWS APIs being used. 

This feature is support for SDK versions > 1.23.13 ([as described here](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html))

The version currently used in Vault is 1.19, and so this cannot be used.

**Describe the solution you'd like**
Update the AWS SDK to the latest v1 version, or at least version 1.24

**Describe alternatives you've considered**
There are two alternatives to this, both are not ideal:
1) Providing an access key and a secret key, either via the values.yml (bad practice) or via a mounted `Secret`
2) Assigning a role to all the worker nodes, giving all the pods in the cluster access to the resources used by Vault for storage and encryption

**Comment by jefferai** [comment] 2019-12-08 17:24
Duplicate of #7458

**Closed by jefferai** 2019-12-08 17:24 UTC
