### ISSUE TITLE
Vault gets hung after an ACL specific operation fails.

### ISSUE THREAD

**Issue by bharath-b23** [hashicorp/vault#7379] opened 2019-08-28 09:39 UTC
**Describe the bug**
We have a setup with two instances of vault and three instances of consul running on two nodes to achieve HA. When these nodes came up from reboot, active vault instance hits an error scenario while collecting ACL policy keys and gets hung, none of the requests are responded to, and are timing out. But the standby instance of vault on another node, seems to be performing basic operations such as read, write & list without any issues.

Below logs were observed during this erroneous scenario.
**Vault server logs** 
```
^[[0;0m==> Vault server configuration:
^[[0m
^[[0;0m                     Cgo: disabled^[[0m
^[[0;0m         Cluster Address: https://[x.x.x.x]:5820^[[0m
^[[0;0m              Listener 1: tcp (addr: "[x.x.x.x]:5819", cluster address: "[x.x.x.x]:5820", tls: "enabled")^[[0m
^[[0;0m               Log Level: debug^[[0m
^[[0;0m                   Mlock: supported: true, enabled: true^[[0m
^[[0;0m        Redirect Address: https://[x.x.x.x]:5819^[[0m
^[[0;0m                 Storage: consul (HA available)^[[0m
^[[0;0m                 Version: Vault v0.9.3^[[0m
^[[0;0m             Version Sha: ed3e7ea4c9c66e78996e1572a8b87a28adc690af+CHANGES^[[0m
^[[0;0m^[[0m
^[[0;0m==> Vault server started! Log data will stream in below:
^[[0m
2019/08/27 18:17:26.605145 [DEBUG] physical/consul: config path set: path=testdata/
2019/08/27 18:17:26.605198 [DEBUG] physical/consul: config disable_registration set: disable_registration=false
2019/08/27 18:17:26.605220 [DEBUG] physical/consul: config service set: service=vault
2019/08/27 18:17:26.605229 [DEBUG] physical/consul: config service_tags set: service_tags=
2019/08/27 18:17:26.605236 [DEBUG] physical/consul: config address set: address=[x.x.x.x]:5821
2019/08/27 18:17:26.605238 [DEBUG] physical/consul: config scheme set: scheme=https
2019/08/27 18:17:26.608114 [DEBUG] physical/consul: configured TLS
2019/08/27 18:17:31.404780 [INFO ] core: vault is unsealed
2019/08/27 18:17:31.442087 [INFO ] core: entering standby mode
2019/08/27 18:48:31.596851 [DEBUG] forwarding: error sending echo request to active node: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2019/08/27 18:48:31.986237 [INFO ] core: acquired lock, enabling active operation
2019/08/27 18:48:32.897262 [INFO ] core: post-unseal setup starting
2019/08/27 18:48:33.218174 [INFO ] core: loaded wrapping token key
2019/08/27 18:48:33.238311 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2019/08/27 18:48:33.357060 [INFO ] core: successfully mounted backend: type=kv path=secret/
2019/08/27 18:48:33.392044 [INFO ] core: successfully mounted backend: type=system path=sys/
2019/08/27 18:48:33.677578 [INFO ] core: successfully mounted backend: type=identity path=identity/
2019/08/27 18:48:33.713791 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
**_2019/08/27 18:48:48.522973 [ERROR] policy: error collecting acl policy keys: error=list failed at path '': Unexpected response code: 500_**
2019/08/28 12:03:49.227025^[[0;0m==> Vault shutdown triggered^[[0m [INFO ]
physical/consul: Shutting down consul backend
```

**Vault client logs**
`Get https://[x.x.x.x]:5819/v1/sys/leader: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**To Reproduce**
1. Post-reboot, during process startup, said error was observed.

**Expected behavior**
Vault on hitting an error, should have recovered and continued to provide other services.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key             Value
---             -----
Seal Type       shamir
Sealed          false
Total Shares    1
Threshold       1
Version         0.9.3
Cluster Name    vault-cluster-f0848381
Cluster ID      cd29a2a7-7b0d-a3b3-43be-aafe1ecbc2ff
HA Enabled      true
HA Mode         active
HA Cluster      https://[x.x.x.x]:5820
```

* Vault CLI Version (retrieve with `vault version`):
`Vault v0.9.3 ('ed3e7ea4c9c66e78996e1572a8b87a28adc690af+CHANGES')`

* Server Operating System/Architecture: 
```
  - Linux vi_node 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
  - CentOS Linux release 7.6.1810 (Core)
  - Extract of lshw output(4 CPU cores)
    description: Computer
    product: OpenStack Compute
    vendor: RDO
    version: 17.0.6-0.20180704141006.3163c93.el7
    serial: [REMOVED]
    width: 64 bits
    capabilities: smbios-2.8 dmi-2.8 smp vsyscall32
    configuration: boot=normal family=Virtual Machine uuid=[REMOVED]
  *-core
       description: Motherboard
       physical id: 0
     *-firmware
          description: BIOS
          vendor: SeaBIOS
          physical id: 0
          version: 1.11.0-2.el7
          date: 04/01/2014
          size: 96KiB
```

Vault server configuration file(s):

```
backend "consul" {
        address = "[x.x.x.x]:5821"
        redirect_addr = "https://[x.x.x.x]:5819"
        cluster_addr = "https://[x.x.x.x]:5820"
        path = "testdata/"
        scheme = "https"
        service = "vault"
        tls_ca_file = "/opt/cacert.crt"
        tls_cert_file = "/opt/vaultserver.crt"
        tls_key_file = "/opt/vaultserverprivkey.pem"
        consistency_mode = "strong"
        tls_min_version = "tls12"
        tls_skip_verify = "false"
}

listener "tcp" {
        address = "[x.x.x.x]:5819"
        cluster_address = "[x.x.x.x]:5820"
        tls_disable = "false"
        tls_cert_file = "/opt/vaultserverpubnca.crt"
        tls_key_file = "/opt/vaultserverprivkey.pem"
        tls_min_version = "tls12"
        tls_cipher_suites = "TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        tls_prefer_server_cipher_suites = "false"
        tls_require_and_verify_client_cert = "true"
        tls_client_ca_file = "/opt/vaultClientCAs.crt"
}

disable_mlock = false
default_lease_ttl = 0
max_lease_ttl = 0
```

**Additional context**
We are observing this issue, on a VI setup.
Recovered from the issue, on restarting the active vault instance, and the standby took over.

**Comment by BharathB23** [comment] 2019-08-29 05:55
Since both nodes were rebooted, and vault & consul services were coming up, for a brief time, consul was trying to stabilise and elect a leader. We have these as systemd services, and also dependency is created to start vault after consul services are started.

Problem being faced is, when active instance of vault hits the error mentioned, standby node is not taking up the active role, and the cluster service(in my case service port 5820) is in listen at the node where active vault instance is running, which is not responding to any queries.

Even if there were some errors while contacting consul, shouldn't vault be responsive state, why a restart is required to come out of it.

**Comment by ncabatoff** [comment] 2019-08-29 12:46
You only provided the logs for one of your nodes, so I'm doing some guessing in my analysis.  The node whose logs you provided saw an error from consul, so it never finished coming up, nor did it become the active node.  I'd originally said it stepped down, but looking closer at the logs and the code I see I was mistaken.  In 0.9.3 that error should result in a panic, though since we don't see that in your logs I'm not sure what's going on.  

Because it never became the active node and didn't acquire the corresponding lock, one of your other nodes became the active node instead of a standby.  It wasn't forwarding requests, it was processing them locally.

I think this is a problem:

> the cluster service(in my case service port 5820) is in listen at the node where active vault instance is running

It sounds like you're assuming that one of your nodes is always going to be healthy enough to either handle or forward requests, which isn't a good HA assumption.  I'm not sure what you mean by "the cluster service", but you should either use a load balancer that's able to direct traffic only to healthy nodes, or use service discovery to send traffic to the active node registered in Consul.

> Even if there were some errors while contacting consul, shouldn't vault be responsive state, why a restart is required to come out of it.

That's a bug in 0.9.3.  Upgrading won't prevent the issue I spoke of above, wherein a failure during startup means that a different node than you might expect becomes the active node, but it will fix this problem of needing a restart when an error occurs in this part of the startup sequence ("error collecting acl policy keys").

**Comment by BharathB23** [comment] 2019-08-30 06:45
Thank you a lot for the timely response and clarification.

> It sounds like you're assuming that one of your nodes is always going to be healthy enough to either handle or forward requests, which isn't a good HA assumption. I'm not sure what you mean by "the cluster service", but you should either use a load balancer that's able to direct traffic only to healthy nodes, or use service discovery to send traffic to the active node registered in Consul.

By cluster service, I meant to say, the active service started by vault, i.e. vault port+1(5819 is my vault port, 5820 was the cluster service started by vault), and according to my understanding this service is started by active vault instance and indicates that he is leader, please correct me, if the understanding is wrong.

> That's a bug in 0.9.3. Upgrading won't prevent the issue I spoke of above, wherein a failure during startup means that a different node than you might expect becomes the active node, but it will fix this problem of needing a restart when an error occurs in this part of the startup sequence ("error collecting acl policy keys").

I would request you to redirect to the pull request, if possible, to enhance my understanding on the behaviour, which corrected the issue of requiring a restart on hitting the issue.

**Comment by aphorise** [comment] 2020-08-23 23:42
I think issue is no longer applicable. @BharathB23 can you confirm if you've been able to reproduce in any of the most recent versions (1.4.x or higher)?

**Comment by aphorise** [comment] 2022-08-30 21:42
I'm closing this request as I believe it's no longer relevant and no further follow-up have been provided now in over 3 years.

**Closed by aphorise** 2022-08-30 21:42 UTC
Labels: bug, core/replication
