### ISSUE TITLE
Add VAULT_ADVERTISE_ADDR environment variable

### ISSUE THREAD

**Issue by Moeser** [hashicorp/vault#842] opened 2015-12-11 23:39 UTC
For HA, vault tries to automatically determine its own advertise address unless configured in the hcl file.  Unfortunately, that auto detection process isn't always reliable.  That leaves us with configuring the advertise address in the hcl file, but a lot of people run vault from docker containers.  In our org, we run four vault servers, and building four different docker containers with a specialized config for each host seems kind of backward.
Is there any way we can get a VAULT_ADVERTISE_ADDR environment variable?  That way, we can pass the IP address to the container at execution time, instead of editing it into 4 separate config files.

**Comment by jefferai** [comment] 2015-12-14 12:52
This is easy to do but would currently conflict with another PR coming in; once that's merged I"ll add this.

**Comment by jefferai** [comment] 2015-12-14 16:16
Closing as a duplicate of #581

**Closed by jefferai** 2015-12-14 16:16 UTC
