### ISSUE TITLE
vaultproject.io getting started layout issues

### ISSUE THREAD

**Issue by stephengfriend** [hashicorp/vault#838] opened 2015-12-11 13:44 UTC
While browsing through the docs on vaultproject.io getting started section, the following alignment issue with the layout was happening:

![Image of vault.io styling issues](http://dpr.stephengfriend.com/1fpXX.png)

Additionally, any links that fall under the paragraph text are not clickable. 

This is happening in Chrome Version 47.0.2526.73 (64-bit) and Firefox Version 42.0

**Comment by jefferai** [comment] 2015-12-11 15:04
I wasn't seeing this on Chrome 47.0.2526.73 (64-bit), but I can
reproduce on Chrome 47.0.2526.80. I cannot reproduce on Firefox 42.0.

**Comment by stephengfriend** [comment] 2015-12-11 15:13
Since I thought it might be an extension issue, I also just checked Safari Version 9.0.2 (10601.3.9) and seeing it there as well.

**Comment by Dashed** [comment] 2015-12-11 16:57
Can confirm using `Chrome Version 48.0.2564.23 beta (64-bit)` on OSX.

**Comment by jefferai** [comment] 2015-12-14 16:47
This should be fixed by the above PR.

**Closed by jefferai** 2015-12-14 16:47 UTC
