### ISSUE TITLE
KV Version 2: Unable to list keys

### ISSUE THREAD

**Issue by timothyclarke** [hashicorp/vault#11545] opened 2021-05-06 12:43 UTC
**Describe the bug**
Unable to create a policy to list the keys within a kv2 secret 
Note this maybe a terminology issue using "key" instead of "secret" within docs, however I doubt it as the [List Secrets documentation](https://www.vaultproject.io/api-docs/secret/kv/kv-v2#list-secrets) surrounding secrets. The documentation includes phrases which imply that the keys should be assessable 
> do not encode sensitive information in key names. The values themselves are not accessible via this command.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable kv2 secrets at `/secret` with `vault secrets enable --path=secret kv-v2`
2. Create secrets
```
vault kv put secret/environment/app/database username=user password=pass host=127.0.0.1 port=3306 dbname=mydb
```
3. Create and apply policy to list secrets and to read metadata
```
$ cat <<EOF  >>policy.hcl
path "secret/*"
{
  capabilities = [ "list" ]
}
path "secret/metadata/*"
{
  capabilities = [ "list", "read" ]
}
EOF

vault policy write mypolicy policy.hcl
```
Note it is assumed that the policy is applied to a user, and the user is then executing the following.

4. Display list of keys within a secret `vault list secret/data/environment/app/database` or `vault kv list secret/environment/app/database`  Ideally this is also available via the web UI.

**Expected behavior**
Secrets are key value pairs. I should be able to list the keys without revealing the values and without giving the ability to also list the values. 

eg 
```
Key         Value
---         -----
host        *****
password    *****
port        *****
username    *****
```
,
``` 
{
  "host": "*******",
  "password": "*******",
  "port": "*******",
  "username": "*******"

}
```
or similar

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.7.0`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.7.0 (4e222b85c40a810b74400ee3c54449479e32bb9f)`
* Server Operating System/Architecture: linux / docker / kubernetes. Helm chart version `vault-0.10.0`

**Additional context**
Ultimately I'm wanting to create policies where development teams can edit secrets in development environments and see the structure of secrets in other environments. eg the secret `terraform_credentials` has keys `access_key_id` and `secret_access_key`, but not be able to see the values associated with the keys.
This should not require the constraint of having to define the secret with `allowed_parameters = {}` 

This bug looks similar to 
* https://github.com/hashicorp/vault/issues/9874  - I think this one is viewing the secret name
* https://github.com/hashicorp/vault/issues/10714 - I think this one is different but in a similar area
* https://github.com/hashicorp/vault/issues/10704  - It maybe a duplicate of this one, but per above I consider this a bug with either the implementation or the documentation as I'd consider this an obvious requirement and the documentation seems to imply it should be possible.

**Comment by g-psantos** [comment] 2021-05-07 00:44
Try modifying the policy to the following:

```hcl
path "secret/metadata"
{
  capabilities = [ "list" ]
}

path "secret/metadata/*"
{
  capabilities = [ "list", "read" ]
}
```

I think I ran into this issue at some point and fixed it by having the `list` permission associated with the `metadata` path alone (no `/*`).

**Comment by timothyclarke** [comment] 2021-05-07 08:10
@g-psantos Thank you for the idea, but I'm suspecting the you ran into has either been fixed or doesn't apply for me. 
I've tried applying your policy and it does not help. 
I can list the secrets eg  `vault kv list secret/environment/app` will tell me `database` exists from the example above, I list a chunk of metadata about it eg `vault read secrets/metadata/testing/devopsTest` will give me
```
Key                     Value
---                     -----
cas_required            false
created_time            2021-04-21T12:07:07.561870432Z
current_version         1
delete_version_after    0s
max_versions            0
oldest_version          0
updated_time            2021-04-21T12:07:07.561870432Z
versions                map[1:map[created_time:2021-04-21T12:07:07.561870432Z deletion_time: destroyed:false]]
```
Without granting the ability to fully read the secret I cannot list the keys within the secret

**Comment by g-psantos** [comment] 2021-05-07 11:34
My apologies, I misunderstood the question.

AFAIK, the "key" the documentation refers to is really the "path" to the entire object. If your object has multiple properties, those are all "secret" data.

Currently, I think your only option would be to separate out `host`, `username`, etc. into their own paths – but of course that would mean they would be versioned independently, which I'm sure is not ideal.

**Comment by vishalnayak** [comment] 2021-06-03 19:07
@timothyclarke Note that the list operation on KV stores works under the analogy of directories and files. For example, if the secret path is `secret/environment/app/database`, then "secret", "environment" and "app" are analogous to directories and "database" is analogous to a file that holds the secrets.

What you are asking for is to look into the file that contains the secret material and list the keys from there. This cannot be allowed with the current ACLing rules. The reason is that being able to reveal what is in the `database` (in your example), sort of breaches the `read` capability contract. Meaning the lister will also now be able to read partially the secret, and this can't be allowed, even if it means that we are only showing the "keys" and not the "values". Even the keys can be secret/sensitive for many users.

Having said all that, we have been thinking internally about ways we can improve observability in the KV-V2 engine, but nothing is concrete yet, and there isn't even a timeline tied to it. If anything changes, we'll try and provide an update.

In the meanwhile, closing this! Sorry.

**Closed by vishalnayak** 2021-06-03 19:07 UTC
Labels: feature-request

**Comment by timothyclarke** [comment] 2021-06-08 17:04
@vishalnayak While I appreciate that this is not currently possible, This is still a bug. 
You'll need to decide if this is a bug in your documentation 
* [list keys within secrets](https://www.vaultproject.io/api-docs/secret/kv/kv-v2#list-secrets), possibly a nomenclature _This endpoint returns a list of key names at the specified location._ certainly sounds like what I'm after and this IS a `key`:`value` store so calling the entire secret a `key` is a nomenclature issue.

Or a bug in your approach / implementation
* _This cannot be allowed with the current ACLing rules._  If you say something is possible within the documentation (see prior point) then the current ACL rules mush have an issue.  
The following ACL rule would strikes me as what I would need to view the keys. If I swap `list` to `read` below I'd expect to then be able to see the values as well.
```
path "secret/data/environment/app/database"
{
  capabilities = [ "list" ]
}
``` 


Additionally tagging this as a feature request, saying what amounts to _we're thinking about it_ and then closing it sends a really bad message.

**Comment by vishalnayak** [comment] 2021-06-16 15:21
@timothyclarke I understand how it is confusing from the perspective you are reading from. But I'd like to clarify a few things in this regard.

The documentation does use the term `key`. This term is generally used for storage keys throughout Vault's documentation. In this backend specifically, the term is getting overloaded with the `keys` within secrets as well. It certainly does not mean that the list endpoint will list keys within the secrets. As I had mentioned earlier, doing so would be a breach of the `read` capability contract and we can't allow it. To disambiguate that, the documentation uses `key names` as the term. You _may_ call this a documentation bug at best. If you do, feel free to PR the changes and I'll be happy to review that!

Removed the `feature-request` tag. This issue showed up as an issue and it isn't one.

Regarding the mention of we thinking about this and closing the issue, please note that the intention here is to keep the issue count low and thus be able to provide faster responses and better engagement with the community. We don't have a solution worked out and we don't have a timeline as well, hence closing it. Note that it is a "soft close", and we encourage users to reopen if they feel that the issue isn't resolved yet.

Hope this helps!

**Comment by gioppoluca** [comment] 2024-04-02 16:44
On 1.12 this issue still present, even with root access

**Comment by fansari** [comment] 2025-05-12 13:55
I use v1.13 and came accross the same issue.

Getting a single secret via API is working. 

With the vault binary "vault kv list -mount=mysecrets ..," works.

But when I try to get a list with API I get this error message:

"Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv list' for this operation."
