### ISSUE TITLE
vault database backend Parameters

### ISSUE THREAD

**Issue by viveksaiaws** [hashicorp/vault#5891] opened 2018-12-03 21:53 UTC
can you explain by example to how to use `revocation_statements ` and `rollback_statements` in database backend ( Cassandra )

i am unable to find example and how to use those 

[link](https://www.vaultproject.io/api/secret/databases/cassandra.html#revocation_statements)

**Comment by kalafut** [comment] 2018-12-04 17:59
If you want to provide a specific CQL statement to revoke or rollback (in event of error) users you can configure these, otherwise Vault will default to just dropping the users.

**Comment by viveksaiaws** [comment] 2018-12-04 18:15
thank @kalafut, sorry but i dont understand from your answer
can you elaborate, if can you provide example 

Thanks!

**Comment by ncabatoff** [comment] 2018-12-04 18:33
You normally don't need to use them unless you want to do something special.  Here are the defaults that are used when you don't provide a value:

```
creation: CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER;
revocation: DROP USER '{{username}}';
rollback: DROP USER '{{username}}';
```

**Comment by briankassouf** [comment] 2018-12-04 19:14
Nick is correct, if you have a more complicated creation statement then you might need to update the revoke and rollback statements. Rollback is used when there is an error during user creation. 

Also going to close this ticket since it's not a bug or issue that we want to track. A better place to ask questions is over at our mailing list https://groups.google.com/forum/#!forum/vault-tool

**Closed by briankassouf** 2018-12-04 19:14 UTC
