### ISSUE TITLE
design/opinion: Secret backends with complex config

### ISSUE THREAD

**Issue by ianunruh** [hashicorp/vault#260] opened 2015-05-25 20:58 UTC
I'm wanting to implement a number of secret backends aimed at preparing Vault for use in deploying OpenStack for IaaS.
- RabbitMQ
- Keystone
- MongoDB

These all will work similarly to the PostgreSQL/MySQL backends, where accounts are created and then assigned permissions towards databases (MongoDB), tenants (Keystone), or virtual hosts (RabbitMQ). The SQL backends use a simple mapping of a "role" to an SQL query that gets interpolated with variables from the backend and then ran against the SQL server. However, the databases/services I want to manage don't take SQL queries, and so the configuration options for a "role" will have to be pushed up to the logical API that operators of Vault will use.

The point of this issue is to get feedback on how the API and logical framework should be utilized for some of these (probably common) use cases. The built-in secret backends are great, but they're not complex enough to make it obvious how we should be using the API and logical framework as developers.
## RabbitMQ

RabbitMQ's permissions model has an idea of tags which define how a user can interact with the management API.

```
vault write rabbitmq/roles/admin tags=administrator
```

Regular users don't need any tags, but we can't write empty keys to the logical API through the CLI.

```
vault write rabbitmq/roles/web
```

RabbitMQ assigns permissions to each user for each virtual host they want to access. Out of the box, RabbitMQ has a default vhost `/`, which makes our paths look a bit odd.

```
vault write rabbitmq/roles/web// configure=^$ read=.* write=.*
vault write rabbitmq/roles/web/othervhost configure=.* read=.* write=.*
```
## Keystone

In Keystone, users are created and then assigned roles on tenants.

Again, we can't write empty keys with the CLI

```
vault write keystone/roles/web
```

Then we would write comma-separated role names to add to the user for each tenant.

```
vault write keystone/roles/web/TENANT_XXX value=_member_,admin
vault write keystone/roles/web/TENANT_YYY value=_member_
```
## MongoDB

In MongoDB, users also have roles that are applied to each database that the user should have access to.

Can't write empty keys with the CLI

```
vault write mongodb/roles/web
```

But we can write roles to add to the user for each database:

```
vault write mongodb/roles/web/DB_XXX value=readOnly
vault write mongodb/roles/web/DB_YYY value=readWrite
```
### JSON documents

The API could accept JSON documents describing roles instead:

```
vault write keystone/roles/web value=@web.json
```

``` json
{
    "tenants": {
        "TENANT_XXX": "_member_,admin",
        "TENANT_YYY": "_member_"
    }
}
```

But then there's JSON within JSON (on the Vault client's request), which is a bit odd. The end-user also has to deal with the JSON documents, but that's not a huge deal.

When it comes to storing/interacting with the JSON documents, I'm guessing that when receiving the JSON, we would write it into the logical storage and then unmarshal it when creating the credentials. Then the fields would be accessed like any other struct.

The AWS backend accepts a JSON document, but that's only because it's an opaque string that just gets passed to IAM. Other backends use an SQL query, which is also opaque to the backend (besides the interpolation)

So far this seems like the easiest to implement on the backend, but it forces the end-user to write a JSON document (not a huge deal though).
### Map types

I also noticed that there is `TypeMap` in `logical/framework`, but it's not used anywhere yet that I can find, so I'm unsure of the syntax that would be used on the CLI client (if it's even been implemented in there yet).
### Race conditions

General question, is it possible to lock/unlock entries for reading/writing in logical storage? Assuming that there's an entry in logical storage that looks like:

```
type RoleEntry struct {
    Roles map[string]string `json:"roles"`
}
```

And you performed the following, where each write loaded the role from logical storage, updated the `Roles` map, and wrote it back to logical storage.

```
vault write keystone/roles/web/XXX roles=_member_,admin
vault write keystone/roles/web/YYY roles=_member_,admin
```

Then there's the possibility that the last write would clobber the first if performed in parallel, and only one of the operations would have succeeded. This is not a problem for any of the current backends, as each operation involves the entire entry stored in logical storage, rather than a subset of the entry.

**Comment by armon** [comment] 2015-05-27 17:40
@ianunruh So there are a few good points here. I think the one about `vault write` disallowing an empty value write will be getting fixed by just adding a `-f` flag that allows an empty body. We've run into this a few times and it is a bit annoying.

We've also run into the need for more complex settings with the PKI backend:
https://github.com/hashicorp/vault/issues/125

The path we've gone there is to have a lot of configurable values on the role configuration, and just set sane defaults for most of them. I think this is probably preferable to having nested configuration or JSON based configuration. 

The race condition issue is a problem, but since its a last-write-wins semantics it's not too bad. If the issue is something like parent keys needing to be updated or cross-key updates with clobber potential, you can do locking within the secret backend to avoid it.

Hope that helps! Let me know if I can help at all as you are tackling these! I think the RabbitMQ one would be great personally, as we could use it internally. The others are great to have as well.

**Comment by camspilly** [comment] 2015-06-17 21:03
@ianunruh What's the status on the potential for MongoDB integrations?

**Comment by jefferai** [comment] 2018-03-14 21:15
Closing as we already have Rabbit and Mongo, and generally have a usable framework.

**Closed by jefferai** 2018-03-14 21:15 UTC
Labels: core, enhancement, thinking
