### ISSUE TITLE
Please implement update operation for /sys/auth/:path

### ISSUE THREAD

**Issue by CVTJNII** [hashicorp/vault#3149] opened 2017-08-11 23:14 UTC
Please create a update operation for /sys/auth/:path.  Currently to update the settings of an auth backend a library must delete and recreate the backend.  Implementing an update method on the same path will allow client libraries which implement the CRUD model against different backends to be consistent between the different backends.  Thanks.

**Comment by jefferai** [comment] 2017-08-12 01:04
What settings?

**Comment by CVTJNII** [comment] 2017-08-14 19:06
The description is really the only practical thing, as changing type on the fly isn't really a logical thing to do.  There is also local, but as a open source user I'm not sure what the semantics are of that.

The spirit of this request was to allow a common update method to work across all backends, so that a vault configuration management tool doesn't need to know which endpoints can be updated with an update, or which need a delete and recreation.  However that hope has been dashed with #3151 being closed.  As I think about it not supporting update isn't that big a deal as it won't be too hard to detect a 405 and fall back to delete/create.  After thinking about this over the weekend I'm much more interested in the reads (#3148, #3150) than updates with a goal of making a configuration management tool that isn't tightly coupled to the nuances of the API.

**Comment by jefferai** [comment] 2017-08-14 19:09
Local can't be changed after create, and updating the description would be a duplicate of https://github.com/hashicorp/vault/issues/2645 so accordingly I'm closing this.

**Closed by jefferai** 2017-08-14 19:09 UTC

**Comment by CVTJNII** [comment] 2017-08-14 20:59
Makes sense, thanks!
