### ISSUE TITLE
Support list operation

### ISSUE THREAD

**Issue by issacg** [hashicorp/vault#906] opened 2016-01-06 10:18 UTC
One of the peeves I've had for a while with Vault is that other than mounts, it's hard to see what's stored inside my vault server.  Given that the key names are all plaintext in the backend storage engines, I'm assuming that browsing shouldn't be a security hazard (ACL-permitting, of course).

I wanted to get some eye-balls on [this](https://github.com/ironSource/vault/commit/42c47b15dc66600b9ecfbce73707ea5188dc63f4) and [that](https://github.com/ironSource/vault/commit/0421cafbc058eb53924c497427ce4cb20a99ee27) as a starting point for supporting a `list` command.

This has only really been tested with the `secret` backend; for other backends we'd probably want to list something else (roles, for most of them).  Is there interest in pushing this effort further as a pull-request?

**Comment by jefferai** [comment] 2016-01-06 14:11
Closing as a duplicate of #111. List support is coming eventually, but there are some changes that need to happen in Vault's core first.

**Closed by jefferai** 2016-01-06 14:11 UTC
