### ISSUE TITLE
Full cluster restart with raft and auto unseal requires recovery keys.

### ISSUE THREAD

**Issue by zelch** [hashicorp/vault#9692] opened 2020-08-08 00:49 UTC
**Is your feature request related to a problem? Please describe.**
A solid use case for Vault with Raft and AWS auto unseal is to be able to restart the cluster and have the cluster as a whole come up successfully, without operator intervention.

However if the entire cluster is shut down at once, you have the problem that each cluster node remembers who the raft leader was when it was shut down, however that node is no longer running.

On restart, every node is waiting for some part of the cluster to be running, and instead no consensus can be formed.

As far as I can tell, the only way to recover is to put at least one node into recovery mode, manually unseal using the recovery keys, and then shut down that node and restart it.  When the node is unsealed in recovery mode it removes all of the raft peers, and then the other nodes can connect to it and form a new consensus.

This is clearly suboptimal.

**Describe the solution you'd like**
Ideally, vault would detect that it can't reach any raft peers and enter into a state where it can't accept standard requests, but can attempt to form a new consensus if enough nodes start talking to it again.  In this case, recovery would be completely automatic with no operator intervention.

Barring this, being able to trigger the removal of the raft peers manually _without_ using the recovery keys for auto unseal configurations would at least remove the need for multiple administrators to be involved.

**Comment by ivan046** [comment] 2020-11-25 21:58
No progress here? Same issue with Google Cloud KMS auto unseal :(

**Comment by Slm0n87** [comment] 2021-02-19 20:54
Hi @zelch - I found your issue while reporting a different one.  
What you describe was a testcase that I did. But it is on-prem, not in AWS. In my case I only had to ensure that the configured transit address is reachable. Then I had to start the necessary number of nodes (in my case 2 becaus I have a cluster out of 3 nodes). Then the two nodes successfully connects and a after a view seconds one of the two nodes enter HA Mode "active."  
May you have to check with `vault operator raft list-peers`  if the peer list is still valid?  
Not sure of one of them changes in the AWS cloud somehow (but usually not by power off & on...)?  

But reading your report you are most probably able to solve my issue in #10950 , because it sounds like you were able to start vault with a single node in auto seal mode? :smiley:

**Comment by ncabatoff** [comment] 2022-05-09 16:34
@zelch, I'm not sure if things have changed since 2020, but certainly today this is not the case.  If the entire cluster is shut down at once, even if the former leader doesn't come back up, the remaining nodes know each other's addresses.   They can initiate elections, become candidates, get elected, and form consensus. If the addresses have changed, you can use the [manual recovery process](https://www.vaultproject.io/docs/concepts/integrated-storage#manual-recovery-using-peers-json).

I'm going to close this issue, feel free to re-open or open a new one if you can still reproduce this.

**Closed by ncabatoff** 2022-05-09 16:34 UTC
Labels: core/seal, storage/raft
