### ISSUE TITLE
I am unable to fetch element of secret with valid path

### ISSUE THREAD

**Issue by Vox1984** [hashicorp/vault#10358] opened 2020-11-09 16:30 UTC
**Describe the bug**
I am unable to fetch element of secret with valid path.

The structure as seen in VAULT UI is engine/userpasslist/db_admin_pass and I am trying to get password **db_admin_pass** only. 

**To Reproduce**
1. Create nested structure in vault: engine/userpasslist/db_admin_pass
2. Try getting db_admin_pass with curl:
```
curl     --header "X-Vault-Token: s.s2XXXXXXX"     https://vault.domain.com/v1/engine/userpasslist/db_admin_pass
{"errors":[]}
```
**Expected behavior**
db_admin_pass is being returned

**Actual behavior**
empty result

**Environment:**
* Vault Server Version Vault 1.5.5 
* Vault CLI Version Vault v1.1.1 ('a3dcd63451cf6da1d04928b601bbe9748d53842e')
* Server Operating System/Architecture: Centos 7

Vault server configuration file(s):

```
path "engine/userpasslist/*" {
  capabilities = ["read","list"]
}
```
P.S
I can fetch the shorter ```engine/userpasslist``` no problem. Is Vault limited to one level nested secrets or something?

**Comment by aphorise** [comment] 2020-11-16 16:13
An empty listing / string is by design I believe in a lot of places for security reasons - rather than divulging what is or is not where. 

Vault UI is a consumer of the API's and you may wish to just open Inspect view under network to get path correlations as you're after. Can you try that?

**Comment by swayne275** [comment] 2020-12-18 16:24
Closing this issue as it's been 30+ days. Please reopen if aphorise's comment didn't resolve it!

**Closed by swayne275** 2020-12-18 16:24 UTC
Labels: waiting-for-response
