### ISSUE TITLE
Wrong values get configured while configuring the kv secret via web gui

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/vault#9333] opened 2020-06-28 18:09 UTC
**Describe the bug**

Wrong values get configured while configuring the kv secret via web gui

**To Reproduce**

Enable a new engine > kv > Next

now keep pressing TAB till you reach the "version" drop down menu
notice it is set to "2"
notice that you have to press DOWN twice to make it "1"  (I think this is a bug)

Also, press UP a few times, say 5 times.
Now notice that you have to press DOWN twice to make the version to "1"

More buggy behavior ...

Expand the "Method Options"
scroll down to "Default Lease TTL"
notice the default value is set to "30" and "seconds"

ONLY click the edit box "Default Lease TTL" and make the value 300 (i.e. just type a 0 sfter the default 30)

do the same 30 -> 300 with the "Max Lease TTL" edit box (LEAVE the seconds drop down box untouched)

Click the button "Enable Engine"

Now go to the secret engine configuration you just created,

notice the value of "Default Lease TTL" and "Max Lease TTL" is 18000 (i.e. 300 minutes)

*** The seconds/minutes/hours/days dropdown defaults to "minutes", even it was showing "Seconds" in the web GUI

**If I click the "seconds/minutes/.." drop down using the mouse and click seconds, then the seconds value gets chosen correctly.**

**Expected behavior**
The expected behavior is that what is seen on the web gui should be chosen correctly.

**Environment:**
* Vault Server Version (retrieve with `vault status`):

```
Key                     Value
---                     -----
Seal Type               shamir
Initialized             true
Sealed                  false
Total Shares            5
Threshold               3
Version                 1.4.2
Cluster Name            vault-dc1
Cluster ID              9ec8cee9-5336-94b5-f8c6-dfa8113bd5c1
HA Enabled              true
HA Cluster              https://my_private_ip:8201
HA Mode                 active
Raft Committed Index    12091
Raft Applied Index      12091
```

* Vault CLI Version (retrieve with `vault version`):

Vault v1.4.2

* Server Operating System/Architecture:
CentOS 8.2 (+latest updates)

Browser: Firefox 77.0.1 (if that matters 🙄 )

Vault server configuration file(s):

n/a

**Comment by shantanugadgil** [comment] 2020-06-30 17:12
<bump> any eyes on this?

**Comment by shantanugadgil** [comment] 2020-11-23 09:28
:bump:

**Comment by chelshaw** [comment] 2021-03-04 16:33
Hey there, this issue was fixed in #8743 (1.5.0 release). Please let us know if you still see the behavior.

**Closed by chelshaw** 2021-03-04 16:33 UTC
Labels: bug, ui

**Comment by shantanugadgil** [comment] 2021-03-04 17:16
Tested just now with version 1.6.3 in dev mode (`vault server -dev`)

1.  This bug seems solved
> notice the value of "Default Lease TTL" and "Max Lease TTL" is 18000 (i.e. 300 minutes)



---


2. This bug still seems to be present
> now keep pressing TAB till you reach the "version" drop down menu
> notice it is set to "2"
> notice that you have to press DOWN twice to make it "1" (I think this is a bug)

**Comment by chelshaw** [comment] 2021-03-04 18:19
Hi @shantanugadgil, thanks for the confirmation about the TTL picker.
As far as the dropdown, 2 is the newer version and we encourage people to use that version, which is why it's listed first. As such this is a design decision, and not a bug.

**Comment by shantanugadgil** [comment] 2021-03-04 18:23
Huh? No....the problem is not that version 2 is first, the problem is that I have to press the DOWN key *twice* to make it version 1.
I should have to press the DOWN key only once.

**Comment by ivana-mcconnell** [comment] 2021-03-04 18:52
Hi @shantanugadgil. In your original report, you mentioned "notice it is set to "2"— we wanted to be thorough and make sure that was addressed for you. Thanks again for submitting it. 

If the problem is specifically that you have to press the down key twice to reach the number 1, this is not something we will be changing at this time. It is a default behaviour that you will find works the same on other <select> elements elsewhere. If you would like to only press the down button once, you can open the <select> with the space bar once it is focused, then press down to select Version 1.

If you believe this is still a serious issue, we welcome you to submit a pull request (please make sure that your tests pass) with your desired behaviour. We will not be commenting further on the issue here.

**Comment by shantanugadgil** [comment] 2021-03-04 18:54
Hi, thanks for responding. 🙂
It is not a serious issue at all.
