### ISSUE TITLE
OAuth2 access token refreshing

### ISSUE THREAD

**Issue by zakjan** [hashicorp/vault#669] opened 2015-10-05 17:43 UTC
OAuth2 access tokens can be valid for a limited period of time, and when invalidated, they must be refreshed by so called refresh tokens. 

It would be cool if Vault would support automatic refreshing of OAuth2 access tokens when the token is requested and its validity time expired or on demand.

**Comment by jefferai** [comment] 2015-10-05 17:47
Duplicate of #96 .

**Closed by jefferai** 2015-10-05 17:47 UTC
