### ISSUE TITLE
vault read -field is somehow interpreting the value

### ISSUE THREAD

**Issue by saikatguha** [hashicorp/vault#2597] opened 2017-04-15 22:36 UTC
## Steps to reproduce
1. `$ vault write secret/foo bar='%2b'`
2. `$ vault read secret/foo`
    ```
    Key                     Value
    ---                     -----
    bar                     %2b
    ```
3. `$ vault read -field=bar secret/foo`
    ```
    %!b(MISSING)
    ```

## Actual results
`%!b(MISSING)`

## Expected results
`%2b`

##

**Comment by vishalnayak** [comment] 2017-04-17 00:39
@saikatguha I am not able to reproduce this on master. Which version of Vault are you using?

**Comment by jefferai** [comment] 2017-04-17 15:58
Duplicate of #2109, fixed in 0.6.3.

**Closed by jefferai** 2017-04-17 15:58 UTC
