### ISSUE TITLE
Getting issue while running go .mod 

### ISSUE THREAD

**Issue by AmanChh** [hashicorp/vault#18072] opened 2022-11-22 09:29 UTC
**Describe the bug**
go: github.com/hashicorp/vault@v1.8.5 requires
        github.com/docker/docker@v17.12.0-ce-rc1.0.20200309214505-aa6a9891b09c+incompatible: reading https://proxy.golang.org/github.com/docker/docker/@v/v17.12.0-ce-rc1.0.20200309214505-aa6a9891b09c+incompatible.mod: 401 Unauthorized

**To Reproduce**
1. Run `go mod tidy`

**Expected behavior**
Go mod should not give unauthorised issue 

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by hghaf099** [comment] 2022-11-22 17:19
Thanks for filing this ticket. Unfortunately, I cannot reproduce the issue. Would you please confirm if the bug is about Vault 1.8.5? Would you please also confirm which Go version are you using?

**Comment by maxb** [comment] 2022-11-27 10:16
The error shows proxy.golang.org returning a 401 Unauthorized error.

Since the public proxy.golang.org service doesn't require or use authentication, my guess is it's something like:
* a corporate intercepting proxy performing man-in-the-middle inspection on internet traffic
* a problem on Google's side (they run proxy.golang.org)
* a throttling/rejection of the requesting source IP for some kind of perceived bad behaviour

In any case, it wouldn't be something within the remit of the Vault project.

**Comment by raskchanky** [comment] 2022-11-29 22:35
Based on the info @maxb provided, and given @hghaf099 was unable to reproduce this, it doesn't sound like this is a bug with Vault, per se. As such, I'm going to close this issue. Please feel free to respond with more information if you feel this was an error. Thanks!

**Closed by raskchanky** 2022-11-29 22:35 UTC
Labels: core, waiting-for-response
