### ISSUE TITLE
Issue migrating from consul to raft

### ISSUE THREAD

**Issue by dferramosi** [hashicorp/vault#10769] opened 2021-01-26 02:32 UTC
**Describe the bug**
I started a migration, pointing at the old consul datastore(vault 1.3.1, consul 1.4.4), and at the local dir for the new raft endpoint (vault 1.6.1), which started fine, but fails to resume

**To Reproduce**
1. create migrate.hcl like: (IP's changed but otherwise the actual config i used)
```storage_source "consul" {
  address = "192.168.1.100:8500"
  path    = "vault"
}

storage_destination "raft" {
  path = "/vault/data"
  node_id = "vault-0"
}
cluster_addr = "http://127.0.0.1:8201"```
2. Run `vault operator migrate -config=./migrate.hcl` on the new container with 1.6.1
3. After some time ctrl-c or otherwise kill the migration
4. Run `vault operator migrate -config=./migrate.hcl -start=sys/expire/id/auth/token` (or any other key you'd like to resume from)
5. get error `Error migrating: error mounting 'storage_destination': could not bootstrap clustered storage: error bootstrapping cluster: cluster already has state` 

**Expected behavior**
Expected migration to resume at the key I provided in the start flag

**Environment:**
* Vault Server Version (retrieve with `vault status`): old is 1.3.1, new is 1.6.1
* Vault CLI Version (retrieve with `vault version`): 1.6.1
* Server Operating System/Architecture: old: linux/x86_64, new: official k8s container via helm chart x86_64

Vault server configuration file(s):

```hcl
disable_mlock = true
ui = true

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

//storage "raft" {
//  path = "/vault/data"
//}
storage "consul" {
  path = "vault"
  address = "192.168.1.100:8500"
}
```
I left the raft config in as a comment to make it easier to switch over once the migration is complete.
**Additional context**
I didn't think I was doing anything special, this is currently being run in a k8s provided by docker-machine as a test to validate the process with a dev instance of Vault, nothing really special about either env.

**Comment by ncabatoff** [comment] 2021-07-21 12:40
Hi @dferramosi ,

There are a variety of reasons that make it impractical for us to resume migrations.  The biggest problem is that we can't assume that have been no changes in the source storage, so we can't really define an ordering of the data to be copied, so we can't easily see what's left to be copied.  There is a `-reset` option to the migrate command that allows you to instead start over from zero.

Hopefully your migration is ancient history and this information is irrelevant to you.  Since Vault is working as intended, I'm going to close this issue.

**Closed by ncabatoff** 2021-07-21 12:40 UTC
Labels: core/migration, pod/distsys, storage/raft
