### ISSUE TITLE
ssh cert signing: allowed_users w/ list of templates yields "alias not found"

### ISSUE THREAD

**Issue by jdef** [hashicorp/vault#13440] opened 2021-12-15 15:38 UTC
**Describe the bug**
SSH public key signing (read: SSH cert) fails when the SSH signing policy references multiple templates in the `allowed_users` field. For example:
```
"allowed_users": "{{identity.entity.aliases.auth_ldap_xyz.name}},{{identity.entity.aliases.auth_oidc_abc.name}}"
```

Error message (when logged in via OIDC):
```
{"errors":["template '{{identity.entity.aliases.auth_ldap_xyz.name}}' could not be rendered -\u003e alias not found"]}
```

**To Reproduce**
1. vault login using ldap
2. request SSH cert signing
3. observe that vault complains about "alias not found" for the oidc template/alias

1. vault login using oidc
2. request SSH cert signing
3. observe that vault complains about "alias not found" for the ldap template/alias

**Expected behavior**
I expect to be able to "vault login" using a variety of approved mechanisms, and write a SSH cert signing policy that allows any of them via templates in `allowed_users`.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture: Linux

**Additional context**
https://github.com/hashicorp/vault/blob/19ef44e121e0d3723adc5a9a130955e61f13ff6a/builtin/logical/ssh/path_sign.go#L227
^ template is parsed here; all errors (including "alias not found") result in the failure of the signing request

https://github.com/hashicorp/vault/blob/19ef44e121e0d3723adc5a9a130955e61f13ff6a/sdk/helper/identitytpl/templating.go#L230
^ i'm guessing this is the origin of the error text that I see

My cluster is air-gapped, apologies for any typos (since all error messages were hand-typed, vs copy/pasted).

**Comment by jdef** [comment] 2022-01-22 21:06
Has there been any movement on this at all, at least internally?

**Comment by cipherboy** [comment] 2022-02-07 20:49
@jdef I think this would be a duplicate of #12220, let me know if you disagree though and I won't close it. :-) That said, there's been no movement either internally or externally as far as I'm aware.

**Comment by jdef** [comment] 2022-02-07 22:21
Yes, looks like a duplicate issue.

**Closed** 2022-02-07 22:22 UTC
Labels: secret/ssh, cryptosec
