### ISSUE TITLE
Vault Status Error

### ISSUE THREAD

**Issue by Gauravjaitly** [hashicorp/vault#11743] opened 2021-06-02 01:52 UTC
I need to update my SSL certificates in the vault but it has been throwing some errors.

vault status
Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: x509: certificate has expired or is not yet valid

Not sure what to do

**Comment by vishalnayak** [comment] 2021-06-02 15:22
@Gauravjaitly It seems like the certificate is already expired. Vault will not respond to any request when that is the case. Have you tried replacing the certificate with non-expired ones and restarting Vault?

**Comment by Gauravjaitly** [comment] 2021-06-02 17:23
Hey Vishal,
Yes i have replaced the certificates with the new ones but when i restart
the vault its status gives me the following error:

root@VAULT-global-1:/usr/lib/vault/certs# systemctl status vault

vault.service - "HashiCorp Vault - A tool for managing secrets"

   Loaded: loaded (/etc/systemd/system/vault.service; disabled)

   Active: *active (running)* since Wed 2021-06-02 12:58:02 EDT; 2min 14s
ago

     Docs: https://www.vaultproject.io/docs/

 Main PID: 7559 (vault)

   CGroup: name=dsystemd:/system/vault.service

           └─7559 /usr/local/bin/vault server -config=/etc/vault.d/vault.hcl


Jun 02 12:58:02 VAULT-global-1 vault[7559]: Log Level: info

Jun 02 12:58:02 VAULT-global-1 vault[7559]: Mlock: supported: true,
enabled: true

Jun 02 12:58:02 VAULT-global-1 vault[7559]: Recovery Mode: false

Jun 02 12:58:02 VAULT-global-1 vault[7559]: Storage: s3

Jun 02 12:58:02 VAULT-global-1 vault[7559]: Version: Vault v1.5.0

Jun 02 12:58:02 VAULT-global-1 vault[7559]: ==> Vault server started! Log
data will stream in below:

Jun 02 12:58:02 VAULT-global-1 vault[7559]: 2021-06-02T12:58:02.629-0400
[INFO]  proxy environment: http_proxy= https_proxy= no_proxy=

Jun 02 12:58:14 VAULT-global-1 vault[7559]: 2021-06-02T12:58:14.709-0400
[INFO]  http: TLS handshake error from 127.0.0.1:55648: remote error: tls:
bad certificate

Jun 02 12:59:54 VAULT-global-1 vault[7559]: 2021-06-02T12:59:54.971-0400
[INFO]  http: TLS handshake error from 172.16.32.253:52504: remote error:
tls: unknown certificate authority

Jun 02 12:59:54 VAULT-global-1 vault[7559]: 2021-06-02T12:59:54.985-0400
[INFO]  http: TLS handshake error from 172.16.32.253:52506: remote error:
tls: unknown certificate authority

*root@VAULT-global-1:/usr/lib/vault/certs# vault status*

*Error checking seal status: Get "https://0.0.0.0:8200/v1/sys/seal-status
<https://0.0.0.0:8200/v1/sys/seal-status>": x509: cannot validate
certificate for 0.0.0.0 because it doesn't contain any IP SANs*

Not sure how to dix this as i am new with the vault. Please let me know if
someone can jump on our call and help us to fix this. this is really urgent
as our clients are effected by this.

Thanks,
Gaurav Jaitly

**Comment by vishalnayak** [comment] 2021-06-07 13:44
@Gauravjaitly It seems like the certificate which is replaced on the server side doesn't have a trusted CA.
Sorry I couldn't get back to you earlier on this. Is this issue resolved?

**Comment by marcboudreau** [comment] 2021-06-21 02:16
@Gauravjaitly, actually, the fact that the error message is reporting the host in the endpoint as `https://0.0.0.0:8200`, means that the **vault** binary is trying to connect to the address `0.0.0.0:8200`, using HTTPS.  Since the **-address** argument wasn't used with the `vault status` command, I would check to see if you have the **VAULT_ADDR** environment variable set in the current shell.  In order for the TLS handshake to succeed, the hostname used by the client (in **VAULT_ADDR** or with **-address**) must match one of the hostnames listed in your certificate.

**Comment by hsimon-hashicorp** [comment] 2021-09-02 16:33
Since it's been a few months since there was last activity on this issue, I'll go ahead and close it now. If you have further bug reports, or more activity on this issue, please feel free to re-open it. Don't forget you can get help on our discuss forum, as well! https://discuss.hashicorp.com/c/vault/30

**Closed by hsimon-hashicorp** 2021-09-02 16:33 UTC
Labels: waiting-for-response

**Comment by chance2021** [comment] 2022-06-16 12:39
In my case, I just updated the vault.crt and the issue is fixed
```
# prepare env
SERVICE=vault
NAMESPACE=vault
SECRET_NAME=vault-server-tls
TMPDIR=/tmp

# Create a key for Kubernetes to sign
openssl genrsa -out ${TMPDIR}/vault.key 2048

# Create a Certificate Signing Request (CSR)
$ cat <<EOF >${TMPDIR}/csr.conf
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = ${SERVICE}
DNS.2 = ${SERVICE}.${NAMESPACE}
DNS.3 = ${SERVICE}.${NAMESPACE}.svc
DNS.4 = ${SERVICE}.${NAMESPACE}.svc.cluster.local
IP.1 = 127.0.0.1
EOF

# Create a CSR
<<<<<<< v1.18.0
openssl req -new -key ${TMPDIR}/vault.key -subj "/CN=${SERVICE}.${NAMESPACE}.svc" -out ${TMPDIR}/server.csr -config ${TMPDIR}/csr.conf
=======
openssl req -new -key ${TMPDIR}/vault.key -subj "/CN=system:node:${SERVICE}.${NAMESPACE}.svc;/O=system:nodes" -out ${TMPDIR}/server.csr -config ${TMPDIR}/csr.conf
>>>>>>> v1.23.4
-----------------------------------
# Create the certificate
$ export CSR_NAME=vault-csr
------------------------------------
<<<<<<< v1.18.0
$ cat <<EOF >${TMPDIR}/csr.yaml
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: ${CSR_NAME}
spec:
  groups:
  - system:authenticated
  request: $(cat ${TMPDIR}/server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
=======
$ cat <<EOF >${TMPDIR}/csr.yaml
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ${CSR_NAME}
spec:
  groups:
  - system:nodes
  request: $(cat ${TMPDIR}/server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
  signerName: kubernetes.io/kubelet-serving
EOF
>>>>>>> v1.23.4
------------------------------------
# Send the CSR to Kubernetes
kubectl create -f ${TMPDIR}/csr.yaml

# Approve the CSR in Kubernetes
kubectl certificate approve ${CSR_NAME}

2. Store key, cert, and Kubernetes CA into Kubernetes secrets store and 

create secret
# Retrieve the certificate
serverCert=$(kubectl get csr ${CSR_NAME} -o jsonpath='{.status.certificate}')

# Write the certificate out to a file
echo "${serverCert}" | openssl base64 -d -A -out ${TMPDIR}/vault.crt

# Retrieve Kubernetes CA.
kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}' | base64 -d > ${TMPDIR}/vault.ca

# Delete existing cm 
kubectl -n ${NAMESPACE} delete secret ${SECRET_NAME}
kubectl -n minio delete cm vault.crt

# Store the key, cert, and Kubernetes CA into Kubernetes secrets
kubectl create secret generic ${SECRET_NAME} \
        --namespace ${NAMESPACE} \
        --from-file=vault.key=${TMPDIR}/vault.key \
        --from-file=vault.crt=${TMPDIR}/vault.crt \
        --from-file=vault.ca=${TMPDIR}/vault.ca   

kubectl -n minio create cm vault.crt --from-file vault.crt 
```
