### ISSUE TITLE
TTL config of SSH engine is not working in UI

### ISSUE THREAD

**Issue by Jamesits** [hashicorp/vault#6901] opened 2019-06-18 09:38 UTC
**Describe the bug**
In Vault UI, TTL config in SSH engine is not working.

**To Reproduce**
1. Open Vault UI
2. Log in
3. Enable a SSH engine
4. Create an SSH role, click on more options, change TTL or Max TTL with some other vaule than the default 30mins
5. Click "create role"
6. Try to sign a key with it
7. Run `ssh-keygen.exe -Lf example.pub` to check the actual cert TTL

**Expected behavior**
Signed cert TTL should be what you set previously.

**Actual behavior**
Signed cert TTL is 30mins.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.3
* Server Operating System/Architecture: Linux/x64

**Additional context**
A simple HTTP request analysis shows that `ttl` and `max_ttl` fields in the post data is always `null` no matter what you fill in. This might be the root cause of this problem.

**Comment by tmanninger** [comment] 2019-07-02 06:02
Same problem with the pki configuration.
ttl and max_ttl are not saved.

**Comment by JakobP** [comment] 2019-07-09 12:44
I reproduced this with a SSH host certificate.

**Environment:**
Vault Server Version (retrieve with vault status): 1.1.3
Server Operating System/Architecture: CentOS 7

**Comment by michelvocks** [comment] 2019-11-07 12:03
Closing this since #7094 has been merged. 
@trolleksii Please open a new issue if you still encounter the same issue. Thanks!

**Closed by michelvocks** 2019-11-07 12:03 UTC
Labels: bug, ticketed, ui
