### ISSUE TITLE
AWS Lease length doesn't seem to work

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#387] opened 2015-07-02 20:53 UTC
Unless I'm misunderstanding something, I was expecting that I can increase the default lease time given to a set of IAM credentials generated with the AWS secret backend.  I was expecting I could do `vault write aws-itsa/config/lease lease=24h lease_max=24h`, and when I do that, I get `Success! Data written to: aws-itsa/config/lease`.  

However, when I do `vault read aws-itsa/creds/admin`, I get a lease of 3600.  

If relevant, yes, I have mounted the AWS back end at a non-default path, as we have multiple AWS accounts and will eventually want to set them all up.

**Comment by armon** [comment] 2015-07-22 23:03
@bkrodgers Marked as a bug, sorry about that! We are probably not parsing it correctly or returning the wrong lease duration internally.

**Comment by spawnius** [comment] 2015-08-13 12:23
It seems you are not passing it in https://github.com/hashicorp/vault/blob/master/builtin/logical/aws/secret_access_keys.go

**Comment by ctennis** [comment] 2015-08-13 21:44
This should be fixed in https://github.com/hashicorp/vault/pull/534

**Comment by frodopwns** [comment] 2015-12-31 21:05
Are we still unable to change lease duration of aws creds?

**Comment by jefferai** [comment] 2015-12-31 21:48
@frodopwns This has not been fixed yet, sorry!

**Comment by frodopwns** [comment] 2015-12-31 22:58
OK, thanks for the response!

**Comment by emk** [comment] 2016-02-29 10:50
This is blocking our migration to the S3 backend. We'd be happy to work on a patch. Would it be possible to sketch out the rough shape of a fix to help us get started? Thank you!

**Comment by jefferai** [comment] 2016-02-29 12:48
@emk This was fixed in 0.5!

**Closed by jefferai** 2016-02-29 12:48 UTC
Labels: bug

**Comment by emk** [comment] 2016-03-05 18:50
Great! Thank you.

**Comment by horalstvo** [comment] 2018-04-18 14:52
I still see the issue:
```
$ vault write aws/config/lease lease=720h lease_max=7200h                                                                      Success! Data written to: aws/config/lease

$ vault read aws/sts/myrole                                                                                          
 Key                Value
---                -----
lease_id           aws/sts/myrole/id
lease_duration     59m59s
```

**Comment by joelthompson** [comment] 2018-04-18 14:58
AWS limits the duration of STS credentials, and so if you request a duration greater than is supported by AWS, the lease will be truncated to the maximum value allowed by AWS. See the AWS documentation for the `DurationSeconds` parameter in [AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) or [GetFederationToken](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html) depending on whether you're fetching assumed-role credentials or federation token credentials, for more information about the limits AWS places on the credential length duration. The default cap for assume-role credentials is 1 hour (AWS recently allowed you to up that to 12 hours), so it looks like that's what you're running in to.

**Comment by horalstvo** [comment] 2018-04-18 15:01
Thank you. That was one lightning fast reply :)

**Comment by Xopherus** [comment] 2018-07-18 17:15
@joelthompson I think I'm seeing the same issue though I've configured `lease` and `lease_max` to be below the 36h threshold for [GetFederationToken](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html). It seems as though sts always defaults to 1h even if you change the mount's lease to be something else. 

Here's the configuration steps I took against Vault 0.10.2:

```
$ vault mount aws

# I would expect the sts lease to be valid for 6h
$ vault write aws/config/lease lease=6h lease_max=36h
$ vault write aws/sts/custom-role

# add key, secret from IAM user with "sts:GetFederationToken" permissions
$ vault write aws/config/root access_key=${ACCESS_KEY} secret_key=${SECRET_KEY} region=us-west-2

# get sts credentials
$ vault write aws/sts/custom-role
Key                Value
---                -----
lease_id                aws/sts/custom-role/92a17e4a-ed5f-eccd-439f-073782ed8c76
lease_duration     59m59s
lease_renewable  false
access_key          blahblah
secret_key           blahblah
security_token     blahblah

$ vault write sys/leases/lookup lease_id=aws/sts/custom-role/92a17e4a-ed5f-eccd-439f-073782ed8c76
Key             Value
---             -----
expire_time    2018-07-18T14:06:05.000034662-04:00
id                     aws/sts/custom-role/92a17e4a-ed5f-eccd-439f-073782ed8c76
issue_time      2018-07-18T13:06:05.338942744-04:00
last_renewal    <nil>
renewable       false
ttl                     3117
```

Have I configured things correctly? If you have time to reproduce that would be greatly appreciated!

**Comment by jefferai** [comment] 2018-07-19 13:19
You specify it at fetch time: https://www.vaultproject.io/api/secret/aws/index.html#ttl

**Comment by Xopherus** [comment] 2018-07-19 20:47
@jefferai I think [this might be](https://github.com/hashicorp/vault/blob/master/builtin/logical/aws/path_sts.go#L30) where the default TTL for STS federation tokens is set. Can you confirm?

It would be great if we could tune this default on the mount. I'm not sure if it the current `lease` and `lease_max` parameters should apply both for IAM and STS though, given that IAM has much longer TTLs allowed by Amazon. What do you think?

**Comment by jefferai** [comment] 2018-07-20 04:14
I think I'd like to wait for https://github.com/hashicorp/vault/pull/4360 to land before discussing further changes  :-)

**Comment by Xopherus** [comment] 2018-07-20 15:49
Sounds good! I'll keep an eye on it
