### ISSUE TITLE
New release required for upgraded Pester library

### ISSUE THREAD

**Issue by pritamsarkar007** [hashicorp/vault#4464] opened 2018-04-26 16:21 UTC
**Expected Behavior:**

The API calls should have a retry behavior for HTTP code 429
**Actual Behavior:**

The retry behavior was not implemented in pester library previously. I have made a contribution to the upstream [library](https://github.kdc.capitalone.com/pritam-sarkar/pester/pull/1). Please cut a new release with the fix.
**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by jefferai** [comment] 2018-04-26 20:12
This is problematic. We may have to remove pester entirely. The problem is that to comply with Consul health checks the default status for a standby node being queried for sys/health is 429 so we'd now have to special cases a call to sys/health but also take into account any custom codes that the user might have specified, which can technically be anything the user wants, including using 429 for an entirely different purpose.

Additionally, it's not clear that 429 is unilaterally the best way to deal with a Too Many Requests scenario. I've opened https://github.com/sethgrid/pester/issues/34 to suggest removing this behavior, so that we can keep it out of the Vault API client.

**Comment by jhnlsn** [comment] 2018-04-26 20:48
Jeff, according to https://tools.ietf.org/html/rfc6585#section-4 http status code 429 is by definition the status code to use when to many requests have been sent by the client to the server and could optionally set a Retry-After header to let the client know when it can retry.

Could you elaborate on your thoughts as to why 429 should not be used for "Too Many Requests"?

**Comment by jefferai** [comment] 2018-04-26 21:16
I do think it's wrong, and I do think it should be changed -- https://github.com/hashicorp/consul/issues/2294#issuecomment-384789580 -- but many Vault users are backed by Consul, and adding this change to Pester in means that any health check (or, simply, any call to sys/health) that uses the Vault Golang SDK will retry multiple times and eventually report failure. This change has a big blast radius. If Consul starts allowing different status codes to indicate standby as per the ticket then we can change the default behavior here while still allowing for backwards compatibility via having users set `standbycode`.

**Comment by jefferai** [comment] 2018-05-10 20:50
Closing as we no longer use Pester.

**Closed by jefferai** 2018-05-10 20:50 UTC
