### ISSUE TITLE
vault token-renew <token> <increment> doesn't increase the time remaining on a token TTL.

### ISSUE THREAD

**Issue by wwalker** [hashicorp/vault#1079] opened 2016-02-15 18:01 UTC
There seems to be no way to renew a token. 

If the increment is greater than the time remaining, it is "successful" but the time remaining doesn't increase. If the increment is less than the current time remaining, it decreases the time remaining, rather than incrementing the time remaining.

{noformat}
[wwalker@tst-mcontrol1 ~]$ vault token-renew $VAULT_TOKEN 1200000
Key             Value
token           REDACTED
token_duration  1136002
token_renewable true
token_policies  [pg_devops_secret_ro]
[wwalker@tst-mcontrol1 ~]$ vault token-renew $VAULT_TOKEN 1200000
Key             Value
token           REDACTED
token_duration  1136001
token_renewable true
token_policies  [pg_devops_secret_ro]
[wwalker@tst-mcontrol1 ~]$ vault token-renew $VAULT_TOKEN 1000000
Key             Value
token           REDACTED
token_duration  1000000
token_renewable true
token_policies  [pg_devops_secret_ro]
[wwalker@tst-mcontrol1 ~]$ 
[wwalker@tst-mcontrol1 ~]$ vault version
Vault v0.5.0
{noformat}

This token operates under this policy:
{noformat}

[wwalker@tst-mcontrol1 ~]$ vault policies pg_devops_secret_ro
path "sys/*" {
  policy = "deny"
}

path "secret/ops/configs/properties/product_groups/*" {
  policy = "read"
}

path "auth/token/lookup-self" {
  policy = "read"
}

path "auth/token/renew-self" {
  policy = "write"
}
{noformat}

**Comment by jefferai** [comment] 2016-02-17 17:03
This is probably because the token's lifetime is already the maximum allowed TTL. You can't renew a token past the maximum.

Renewing a token for a TTL that is less than the current TTL will indeed decrease the time of the current TTL. This in on purpose, to allow token holders to reduce the length of their token validity if they do not need the full term.

**Comment by wwalker** [comment] 2016-02-24 18:01
Clearly I am missing something.  26 days ago I created this token, it says it has roughly 4 days TTL, 
I try to renew it, it is "successful, but the TTL keeps going down.

How can I keep this token from expiring?

    [wwalker@tst-mcontrol1 ~]$ vault token-lookup $VT
    Key                     Value
    creation_time           1.454102549e+09
    creation_ttl            2.592e+06
    display_name            token-DevOps-Product-Group-ReadOnly
    id                      REDACTED
    last_renewal_time       1.456336237e+09
    meta                    <nil>
    num_uses                0
    orphan                  false
    path                    auth/token/create
    policies                [pg_devops_secret_ro]
    ttl                     358044
    [wwalker@tst-mcontrol1 ~]$ vault token-renew $VT
    Key             Value
    token           REDACTED
    token_duration  358008
    token_renewable true
    token_policies  [pg_devops_secret_ro]
    [wwalker@tst-mcontrol1 ~]$ vault token-lookup $VT
    Key                     Value
    creation_time           1.454102549e+09
    creation_ttl            2.592e+06
    display_name            token-DevOps-Product-Group-ReadOnly
    id                      REDACTED
    last_renewal_time       1.45633654e+09
    meta                    <nil>
    num_uses                0
    orphan                  false
    path                    auth/token/create
    policies                [pg_devops_secret_ro]
    ttl                     357996
    [wwalker@tst-mcontrol1 ~]$

**Comment by jefferai** [comment] 2016-02-25 02:52
By default, unless changed via mount tuning or in Vault's config file, issued tokens are valid for 30 days, or 2592000 seconds (which you can see in `creation_ttl` above). This is both the default *and* the maximum TTL.

When you are attempting to renew the token, the logic first looks at what the renew period should be (the default, or a value you specify in the renew command), and then caps that value to the maximum lifetime. In your case, since (unless you have changed it, but it doesn't seem so) the default and the maximum are the same, you *cannot* renew the token any longer; the renew command succeeds, but it is capped at the maximum lifetime. As you noted earlier, you could specify a shorter lifetime, which would be honored, but you simply cannot go past the maximum.

**Comment by wwalker** [comment] 2016-02-26 22:46
Based on this, it seems that we need both a ttl and a maximum_ttl in the token-lookup response.

Do the other backend tokens have maximum_ttl also?

**Comment by jefferai** [comment] 2016-02-26 23:35
All backends have maximum and default TTLs. You can see them via the 'vault mounts' command and they can be adjusted with the 'vault mount-tune' command.

**Comment by jefferai** [comment] 2016-02-26 23:37
To be clear, renewals look at the current value of the mount max and compare that to the issue time of the token.

**Comment by wwalker** [comment] 2016-03-02 20:22
Is there any way to extend the max ttl of auth backend tokens?

**Comment by wwalker** [comment] 2016-03-02 20:31
OK for those who find this ticket later, THIS is the magic you have been looking for (default token ttl to 6 months, maximum token life to 5 years):

{{vault mount-tune -default-lease-ttl=4380h -max-lease-ttl=43800h auth/token}}

**Comment by jefferai** [comment] 2016-03-02 20:34
That seems pretty excessive -- a much better idea would be to use periodic tokens coming in 0.5.2.

**Comment by BRMatt** [comment] 2016-04-19 21:17
We've also been running into a similar issue. We have a script that increments a token's TTL by 20 days worth of seconds, but we're now in a situation where every call `/auth/token/renew-self` is succeeding with a 200 response and a new `last_renewal_time`, but the TTL is not being extended. The tokens themselves currently have a TTL of ~13.5 days.

![](http://cl.ly/1X132z1J3T3b/Image%202016-04-19%20at%209.07.55%20pm.png)

The saw tooth pattern is caused by the daily cron job that renews the tokens. The large drop at the beginning is when we changed the increment from 29 days to 20 hours and the TTL of all tokens dropped (as @wwalker describes in his opening post).

Between the 12th and the 18th the cron fails to run because of unrelated problems. The final bump is (I believe) when we manually renewed the tokens and their TTL was bumped to 355 hours (14.79 days). Since then, the ttls do not change no matter how many times we manually run the renewal script/call renew-self with the 20 days worth of seconds. Given that calling `renew-self` can decrease the remaining TTL for a token I don't really want to experiment with attempting lower TTLs.

> When you are attempting to renew the token, the logic first looks at what the renew period should be (the default, or a value you specify in the renew command), and then caps that value to the maximum lifetime. In your case, since (unless you have changed it, but it doesn't seem so) the default and the maximum are the same, you cannot renew the token any longer; the renew command succeeds, but it is capped at the maximum lifetime. As you noted earlier, you could specify a shorter lifetime, which would be honored, but you simply cannot go past the maximum.

So, to clarify my understanding, if you have a token that can be renewed an infinite amount of times, and the mount/backend/system is configured with some max lease TTL that is > 0, then renewing an auth token _should always_ result in the token's lifetime being extended by some positive number of seconds?

It seems like the renew logic might taking the max of the wrong things. Here's an example interaction from our setup:

```console
$ vault read auth/token/lookup-self
Key              	Value
creation_time    	1.459673445e+09
creation_ttl     	2.592e+06
display_name     	token-bliss
id               	$TOKEN
last_renewal_time	1.461097182e+09
meta             	<nil>
num_uses         	0
orphan           	false
path             	auth/token/create
policies         	[default service-account-credentials-full-access]
ttl              	1.168224e+06
$ vault token-renew $TOKEN 2592000
Key            	Value
token          	$TOKEN
token_duration 	1168218
token_renewable	true
token_policies 	[default service-account-credentials-full-access]
$ vault read auth/token/lookup-self
Key              	Value
creation_time    	1.459673445e+09
creation_ttl     	2.592e+06
display_name     	token-bliss
id               	$TOKEN
last_renewal_time	1.461097227e+09
meta             	<nil>
num_uses         	0
orphan           	false
path             	auth/token/create
policies         	[default service-account-credentials-full-access]
ttl              	1.168215e+06
```

As an aside, we spotted this because we had an outage a few weeks ago where all our tokens expired and were revoked (likely due to this bug). Afterwards we added the above metrics and got alerted when the TTLs were not being extended.

If anybody else is using statically assigned, long-lived tokens I'd strongly recommend adding metrics for the TTLs of your tokens. We're using long-lived tokens because it's the easiest way to work vault into our existing applications. Hopefully we can migrate to another auth backend further down the line.

**Comment by jefferai** [comment] 2016-04-19 22:13
@BRMatt I don't think this is a bug; I think it's a misunderstanding of the longevity of tokens:

>  if you have a token that can be renewed an infinite amount of times

Since 0.5, as detailed in the upgrade notes (https://www.vaultproject.io/docs/install/upgrade-to-0.5.html), tokens cannot be renewed forever. You can set a very, very, very, very long maximum TTL for either the system default max TTL or the `auth/token` mount specifically -- 900 years, if you want to -- but tokens have a maximum lifetime.

The *only* exception to this rule is the periodic tokens introduced along with token roles in 0.5.2. This provides a way to issue tokens that are allowed to live forever, but with administratively set controls and easier ways to revoke them if they are lost. This is in contrast to pre-0.5 behavior where any auth token issued directly from the token backend (and in some cases, from other auth backends) could be renewed indefinitely, which had a lot of negative security implications.

What likely happened in your situation is that you upgraded to 0.5 but didn't account for the fact that tokens would now honor the maximum TTL set within the system or the mount, and did not extend that TTL accordingly.

Using metrics to check the TTL of tokens is good practice regardless, in case something happens -- Vault is unavailable to a service so a renewal cannot happen, or authentication credentials are incorrect or have expired so a new token cannot be fetched, or so on. But I don't think what you saw was a bug.

**Comment by BRMatt** [comment] 2016-04-20 11:07
> Since 0.5, as detailed in the upgrade notes (https://www.vaultproject.io/docs/install/upgrade-to-0.5.html), tokens cannot be renewed forever. You can set a very, very, very, very long maximum TTL for either the system default max TTL or the auth/token mount specifically -- 900 years, if you want to -- but tokens have a maximum lifetime.

Thanks, that makes more sense. I think my confusion is coming from the fact that the CLI presents TTL  as "seconds remaining" to the end user, and this can be changed by renewing the token. When I read "max TTL" in the code/documentation I assumed it was a cap on the seconds you're incrementing by, rather than a hard limit on the token's _age_.

i.e. `newTTL = min(currentTTL + newIncrement, maxTTL); expirationDate = now + newTTL`, whereas the actual behaviour is `expirationDate = min(now + newIncrement, creationDate + maxTTL)`.

Do you think using "max age" to describe this cap would make more sense? I notice the changelog has a bit of trouble with the terminology and uses TTL to refer to "seconds from now" and "seconds from creation" in the same paragraph:

> (As a refresher: the default TTL is the amount of time that the initial lease/token is valid for before it must be renewed; the maximum TTL is the amount of time a lease or token is valid for before it can no longer be renewed and must be reissued. A mount can be more restrictive with its maximum TTL, but cannot be less restrictive than the mount's maximum TTL.)

 
> What likely happened in your situation is that you upgraded to 0.5 but didn't account for the fact that tokens would now honor the maximum TTL set within the system or the mount, and did not extend that TTL accordingly.

Yep, that sounds likely. I think this was overlooked because we'd been running 0.5.0 dev since mid December (only handling a small percentage of production traffic). The weird thing is that there was over a month between us rolling out 0.5.0 stable and the outage, and the cron job was attempting to "increment" the TTL to 30 days every morning. The tokens were created a long time(> 30 days) before we upgraded to 0.5.0 stable, so in theory they should've expired almost immediately?

The main thing I'm still not sure about is why **_incrementing_** a token's TTL with a positive value less than the current TTL will reduce the TTL. I'm guessing the use case behind it is to keep tokens short-lived, so that a co-process can renew a token with say `3600` seconds every few minutes, and the token's TTL won't run all the way up to 30 days?  If so, is it worth renaming the API/cli parameters from `increment` to something like `set_ttl`, `new_ttl`, `expire_in`, or even just `ttl`? I can see this causing a heck of a lot of confusion for folks who're just getting started with vault.

**Comment by jefferai** [comment] 2016-04-20 14:19
@BRMatt I can understand your confusion -- I'm more than happy to fix up places in the docs that you found confusing, so feel free to point them my way.

As for "max age" I'm not sure -- technically both are indeed times to live. Changing terminology is hard because it tends to get disjoint, and a while back TTL was proposed as the preferred way from max lease because of the specific connotation TTL has in the community. At the moment I think rather than change the name I'd prefer to change documentation where needed.

> The weird thing is that there was over a month between us rolling out 0.5.0 stable and the outage, and the cron job was attempting to "increment" the TTL to 30 days every morning. The tokens were created a long time(> 30 days) before we upgraded to 0.5.0 stable, so in theory they should've expired almost immediately?

No -- this was actually compatibility behavior we put in to avoid the 0.5 upgrade immediately killing everyone's tokens. If the creation time hadn't been recorded for a token (which was the case pre-0.5), on the next renewal, we treated it as being created "now", updated the token's creation time, and started subjecting it to the maximum TTL.

`increment` is an old term at this point that hasn't changed for compatibility. It's also not technically wrong, although I understand how it can be confusing, especially given that the documentation describes it as a time period for extending the lease, when what it really is doing is specifying an extension of the lease from the current moment -- which may be net negative. That parameter does seem ripe for some more explanatory documentation, if not deprecation/replacement.

AFAICT the real problem is that the people that originally wrote the code are very into math  :-)  A mathematics definition of _increment_ is "a small positive or negative change in a variable quantity or function". Viewing it through that lens, it is indeed specifying a change, but colloquially you may expect that change to always be additive. This is conjecture on my part, but I wouldn't be surprised if it's the truth.

Anyways, the increment value can reduce the lifetime of a token/lease because the consumer of a token or lease that doesn't need it for the amount of time for which it has issued may decide to limit its lifetime to prevent accidental disclosure. For tokens there's some overlap with `revoke-self` (which didn't exist at the time, nor did the `default` policy), but for leases there may well not be privileges to the generic revocation endpoint for all callers, and besides, there are definite use cases where a client wants to limit the active lifetime of its token or lease if it fails to keep it renewed (say, an unintended shutdown), but still be able to use the token while it's alive.

**Comment by BRMatt** [comment] 2016-05-03 08:26
Sorry for the delayed reply, I was off work for a bit.

> Changing terminology is hard because it tends to get disjoint

Agreed, naming things is hard. :/ I've tried to add some documentation [to a branch in our repo](https://github.com/hashicorp/vault/compare/master...geckoboard:improve-token-docs), so I'll be sending a PR shortly.

While writing the docs I was trying (and failing) to think of a nice way clients could check if Vault changed the TTL according to the increment, or whether it had been capped at the max. Do you know of such a way? The only approach I could think of was comparing the new TTL to the requested increment, but that seems like it could be error prone. 

> AFAICT the real problem is that the people that originally wrote the code are very into math :-)

Ah, that could explain it!

**Comment by jefferai** [comment] 2016-05-03 13:37
> The only approach I could think of was comparing the new TTL to the requested increment, but that seems like it could be error prone.

Why do you think that would be error prone?

**Comment by BRMatt** [comment] 2016-05-03 15:02
Well, I guess if there were some delay between the TTL being set and the response being generated (e.g. a slow storage backend) the TTL returned wouldn't match the increment, even though the requested increment wouldn't have taken it over the cap. So if you're comparing the two, you have to start adding in a fudge factor to work out if the TTL is significantly lower than what you were expecting.

On the other hand, we could make this a bit more explicit in the response. e.g. if the TTL has been capped then the response could include a message to that effect. Another alternative could be to include the token's maximum TTL in the response. Then you could check `token_ttl == token_max_ttl` to see if it's even feasible to carry on using the token. At the very least, it would've made things a heck of a lot clearer for us when debugging this issue.

```console
$ vault renew-token ...
Key            	    Value
token          	    242409fa-60f5-d545-b1c7-f4ebe3e251a8
token_ttl      	    3600
token_max_ttl      	3600
token_renewable    	true
token_policies     	[default]
```

(This example also changes `token_duration` to `token_ttl`. Is `token_duration` the accepted terminology or should I make an issue/PR to change it to ttl?)

**Comment by jefferai** [comment] 2016-05-03 15:26
We can't include a token's maximum TTL in the response since right now there is no way to set a per-token explicit maximum. It's up to the backend to decide based on configuration what that value should be, and if nothing is set it delegates to the mount default and system default in that order, and at renewal time the backend can opt to use an updated value if it's been updated since. A way to set an explicit max may show up at some point, but quite possibly only for tokens issued either directly from the token auth backend's create functions or as a part of the token auth backend's new role support.

The "key" you see there is actually not coming from the response in this case, just how it's displayed. Feel free to submit a PR changing it.

**Comment by BRMatt** [comment] 2016-05-04 09:34
Ok. Is there a recommended tactic for checking if a new token should be created?

**Comment by jefferai** [comment] 2016-05-04 14:10
Most tools renew at TTL half time, then if they see that the new TTL isn't far enough off they reauthenticate.

**Comment by F21** [comment] 2016-06-09 00:50
I just came across this issue because I am seeing the same problem and am still quite confused about how I should be renewing my tokens.

For some background, I am running my microservices in docker containers and injecting the tokens in to each container using the cubbyhole approach. I plan to have a service that generates the token and puts it into a cubbyhole using a temp token. The temp token is injected into the service and the service uses the temp token to retrieve the actual token.

I do not want to set the actual token to have a long TTL. Preferably, the ttl should be something like 72 hours, so that if a service is destroyed or replaced, the token would only be valid for 72 hours. However, I would like to renew it indefinitely because I would need to needlessly destroy and recreate the service to get a new token via the cubbyhole (and this creates more orchestration responsibilities).

What should I be doing here? Should the service be creating a new token every time the TTL is about to expire?

**Comment by jefferai** [comment] 2016-06-09 01:04
@F21 please use the mailing list for questions. This issue is coalescing around some documentation enhancements and not renewal strategies.

**Comment by harishanchu** [comment] 2016-09-23 10:13
I think these concepts are not very clear from current documentation.

**Comment by bitsofinfo** [comment] 2016-11-28 19:23
Yes this is very confusing, I see this too: https://github.com/hashicorp/vault/issues/2134

**Comment by jefferai** [comment] 2016-11-28 19:45
@bitsofinfo Your issue is not the same.

I'm closing this; if someone has specific verbiage suggestions, please PR.

**Closed by jefferai** 2016-11-28 19:45 UTC
