### ISSUE TITLE
Issue with unseal using raft storage

### ISSUE THREAD

**Issue by igor-nikiforov** [hashicorp/vault#9071] opened 2020-05-23 21:23 UTC
**Describe the bug**
Cannot unseal Vault 1.4.2 with raft storage using only one node.

**To Reproduce**
Start Vault with Raft storage, create cluster with 1 node and try to unseal.

**CLI:**
```
# export VAULT_ADDR=http://0.0.0.0:8200
# vault operator unseal
Unseal Key (will be hidden):
Error unsealing: Error making API request.

URL: PUT http://0.0.0.0:8200/v1/sys/unseal
Code: 500. Errors:

* cannot use unspecified IP with raft storage: 0.0.0.0:8201
```
**UI:**
Each attempt of unseal from UI cause this line in log - `[WARN]  core: cluster listener is already started`

**Expected behavior**
This worked with Vault 1.4.0 and 1.4.1 versions.

**Environment:**
Vault 1.4.2

Vault server configuration file(s):

```hcl
storage "raft" {
  path    = "/vault/data"
  node_id = "node-1"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_disable = true
}

disable_mlock = true
api_addr = "http://0.0.0.0:8200"
cluster_addr = "http://0.0.0.0:8201"
ui = true
```

**Additional context**
It is probably regression from PR [9008](https://github.com/hashicorp/vault/pull/9008).

**Comment by ingtarius** [comment] 2020-10-12 13:51
Confirm, same issue

**Comment by raskchanky** [comment] 2020-10-12 16:29
From reading the changes in https://github.com/hashicorp/vault/pull/9008, it doesn't look like a regression. That PR specifically forbids the use of `0.0.0.0` as a cluster address. I'm going to close this, because I don't think there's anything for us to do here.

**Closed by raskchanky** 2020-10-12 16:29 UTC
Labels: storage/raft

**Comment by ingtarius** [comment] 2020-10-12 19:30
https://discuss.hashicorp.com/t/cant-unseal-new-vault/15416/2
If it is one node install, then you should use 127.0.0.1 for cluster_addr
I cant check it right now
