### ISSUE TITLE
executing vault cli commands inside the JVM wraps text in a unintended fashion

### ISSUE THREAD

**Issue by casz** [hashicorp/vault#7295] opened 2019-08-11 09:45 UTC
**Describe the bug**
When executing a command against vault CLI inside the JVM (which is inside a docker container) we experience odd line-wrapping when trying to consume the string output of stdout.

```
java.lang.AssertionError: 
Expected: a string containing "password123"
     but: was "====== Me
tadata ======

Key      
        
Value
--
-           
   ----
-
created_
time   
  2019-05-28
T06:07:00.92
1354802
Z
deletio
n_time   
 n/a
destro
yed      
  false

version 
        
 1

=====
== Data 
=======

Key    
       V
alue
---    
       --
---
top
_secret 
   passw
ord123
"
```

We had a chat about it here: https://gitter.im/jenkinsci/configuration-as-code-plugin?at=5c7c052b8a7def075208edd9
testcontainers also experienced it here: https://github.com/testcontainers/testcontainers-java/pull/1410#issuecomment-496666569

can also be experienced in this PR https://github.com/jenkinsci/configuration-as-code-plugin/pull/764 on this commit: 
https://github.com/fishi0x01/configuration-as-code-plugin/commit/01eb2553f9d90890ed783580313dc05451cc6ce5#diff-1f76c3e79f43f462a54019703a6a40e5R76

**To Reproduce**
1. Clone https://github.com/robfrank/testcontainers-java/tree/fix_vault
2. Run tests
3. See error

**Expected behavior**
Lines of text should not wrap unexpectedly

**Environment:**
Experienced using vault:1.0.3 and above

**Comment by ncabatoff** [comment] 2019-08-12 13:13
Hi @casz,

Have you tried using the `format` option, e.g. json?

**Comment by casz** [comment] 2019-08-20 18:03
@ncabatoff 
This happens for JSON and YAML format as well

```
{
  "unseal_keys_b64": [
    "4Ym0LUJ5O9Bd
rfQiuuQsCB1IR
eDetMJMhpE5wc
/Sy7M="
  ],
 
 "unseal_keys_h
ex": [
    "e189b42d4279
3bd
0
5dadf4
22bae42c08
1d4845e0de
b4c24c869139c1cf
d2cbb3"
  ],
  "u
nseal_shares": 1,

  "un
sea
l_thres
hold":
 1,
  "
recove
ry_
keys_b
64"
: []
,
  "
recove
ry_key
s_hex": []
,
 
 "recov
ery
_ke
ys_shar
es"
: 5
,
  "re
cov
ery_key
s_t
hreshold":
 3,
  "root_toke
n": "s.DKFT6u3Onj
SKgMJxQWUekWfk
"
}
```

```
recovery_keys_b64: []
recovery_ke
ys_hex: []

recover
y_keys
_sha
re
s
: 
5
re
covery_key
s_th
reshol
d: 
3

root_token: 
s.MUF3
zfkk3aHD
zMEo
BJ
KT
gckr
un
seal_key
s_b64:
- A
v2m
yja3+
lOyt4/A
U3rejE+q
BZyOR
QR+gJl
PrzjQlsc=
unse
al_keys_he
x:
- 02
f
da6
ca36
b7f
a53b2b78fc0537ade8c4faa
059c8e45047e80994faf
38d096c7
unse
a
l_s
hare
s:
 1
unseal_thre
shold:
 1
```

**Comment by michelvocks** [comment] 2019-12-18 14:36
Hi @casz!

Sorry for the late reply!
I tried to reproduce your issue but I'm unable to do so. I used the following test java program:
```
import java.io.IOException;
import java.io.BufferedReader;
import java.io.InputStreamReader;

class Test 
{ 
    public static void main(String args[]) 
    { 
        try {
            String command = "/tmp/vault kv get secret/test";
            Runtime run = Runtime.getRuntime();
            String[] envp = new String[2];
            envp[0] = "VAULT_ADDR=http://docker.for.mac.host.internal:8200";
            envp[1] = "VAULT_TOKEN=12345";
            Process proc = run.exec(command, envp);

            BufferedReader stdInput = new BufferedReader(new InputStreamReader(proc.getInputStream()));
            BufferedReader stdError = new BufferedReader(new InputStreamReader(proc.getErrorStream()));

            // Read the output from the command
            System.out.println("Here is the standard output of the command:\n");
            String s = null;
            while ((s = stdInput.readLine()) != null) {
                System.out.println(s);
            }

            // Read any errors from the attempted command
            System.out.println("Here is the standard error of the command (if any):\n");
            while ((s = stdError.readLine()) != null) {
                System.out.println(s);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    } 
}
```

Even if I run the program in a Docker container I'm not able to reproduce it.
Could you provide any additional information on how to reproduce this? I'm not able to get your tests working.

Cheers,
Michel

**Comment by casz** [comment] 2019-12-18 15:41
@michelvocks you should be able to use the testcontainers-java project to create a vault container that you can execute commands against and reproduce the bug that way.

**Comment by casz** [comment] 2019-12-18 15:43
if you'd like I can see if I can create a repro 😓

**Comment by michelvocks** [comment] 2019-12-19 08:47
> @michelvocks you should be able to use the testcontainers-java project to create a vault container that you can execute commands against and reproduce the bug that way.

Would you mind to share how I do that?

**Comment by casz** [comment] 2019-12-19 09:02
I'll try and fit a repro in this evening 😅

**Comment by casz** [comment] 2019-12-19 20:33
https://github.com/casz/vault-cli-docker-repro here you go, even with ci and log output, so you don't even have to run it locally 😆

The issue definitely exist: https://github.com/casz/vault-cli-docker-repro/commit/370f607bfdb0d5f60d38e7e9aac665662524668b/checks?check_suite_id=367394523#step:4:708

I seen it worse locally:

```
output:
====== Metadata ======

Key  
            Value
---              -----
created_time 
 
 
  
2
01
9
-1
2-
1
9
T20
:2
8
:
0
1
.
6
86
6081
67
Z

d
elet
i
on_time    n/a
destroyed        false
version          1


=
===
=
==
 Da
t
a
 
=======
Key           V
a
lue


-
--  
   
 
    
 
-
----
top_s
e
c
r
e
t
 
 
 
 
p
a
s
s
w
o
r
d
1
2
3

```

```
output:
====== Metadata ======

Key              Value
---              -----
creat
ed_time     2019-12-19T20:27:59.219757354Z
deletion_time  
  n/a
destroyed        false
version          1

======== Data ========

Key             Value

---             
-----
secret_four 
    password4
secret_one      password1
secret_three    [password3 password3]
secret_two      password2

output:
{
  "request_id": "c161cd2d-d2d4-58a4-1b2a-08ada7835d6d",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "data": {
      "secret_four": "password4",
      "secret_one": "password1",
      "secret_three": [
        "password3",
        "password3"
      ],
      "secret_two": "password2"
    },
    "metadata": {
      "created_time": "2019-12-19T20:27:59.219757354Z",
      "deletion_time": "",
      "destroyed": false,
      "version": 1
    }
  },
  "warnin
gs": null
}

output:
data:
  data:
    secret_four: password4
    secret_one: password1
    secret_three:
    - password3
    -
 password3
    secret_two: password2
  metadata:
    created_time: "2019-12-19T20:27:59.219757354Z"
    deletion_time: ""
    destro
yed: false
    version: 1
lease_duration: 0
lease_id: ""
renewable: false
reques
t_id: 21
f9480b-b936-1cc5-9108-1c37897eaead
warnings: null



```

**Comment by michelvocks** [comment] 2019-12-20 10:34
Hi @casz!

Thank you for providing the example. I was able to reproduce it locally.
I don't think this is a problem related to Vault. You can see from my test that the execution & output inside a Docker container works without any issues. I also noticed that you use docker-java to run the command and retrieve the output which I think is the cause of the issue.

I recommend opening an issue at docker-java which potentially malformed the output of the Vault client.

Cheers,
Michel

**Comment by michelvocks** [comment] 2020-02-07 10:30
Hi @casz!

I'm going to close this issue because I think this is not related to Vault itself but more a problem related to docker-java. Feel free to open a new issue/comment on this one if you've received additional information regarding this topic. 

Cheers,
Michel

**Closed by michelvocks** 2020-02-07 10:30 UTC
Labels: bug, core/cli, version/1.0.x, waiting-for-response
