### ISSUE TITLE
SHA1 Padding on KeyType_RSA (Transit Key)

### ISSUE THREAD

**Issue by higonetr** [hashicorp/vault#8045] opened 2019-12-17 20:12 UTC
Hi! 

We import a key that we alredy have in production to the vault. Tweaking a little the backup file from a key, We succeded import our key.

But that key is being used for some payments devices that encrypt the data with a SHA1 padding. So we can't not be able to use decrypt function from the vault in our application. 
So we need to change the source code from the vault, in \sdk\helper\keysutil\policy.go File on lines 904 and 1038. Because SHA256 was hardcode in one of the parameters on the function. So we just replace that with SHA1 and everything works. 

But making optional the type of padding in transit keys would be a great feature.

Thanks!

**Comment by catsby** [comment] 2019-12-18 20:43
Hello - could you provide a bit more detail on how you're importing your key, and the workflow you're using to encrypt and decrypt things? An example of the steps to reproduce this would be helpful, especially if you can share parts of the error messages if you are getting any. 

Thanks!

**Comment by catsby** [comment] 2019-12-18 20:49
Just to be clear, you're requesting we use `sha1.New()` in place of `sha256.New()` as the first parameter of the function call on this line:

https://github.com/hashicorp/vault/blob/c5ae51e59762102d7a07701d785d3f84475855db/sdk/helper/keysutil/policy.go#L904

If I understand correctly then it's very unlikely that change would be a good idea, as [crypto/sha1][sha1] is documented to be "cryptographically broken and should not be used for secure applications." 

[sha1]: https://golang.org/pkg/crypto/sha1/

**Comment by raimsten** [comment] 2019-12-19 15:02
We are not getting any error when we import the key. We did it correctly.

We've some devices that not supported another RSA-OAEP padding than SHA1. So for be enable to use all functionality of Transit Vault Keys we tuned the source code.
But how the SHA padding is the first parameter of EncryptOAEP DecryptOAEP functions, it's not dificult to add that option to transit key settings. 
It's easier change that functions than to change all devices from production.

Thanks for response!

**Comment by catsby** [comment] 2020-01-23 20:48
Hello - adding an option to choose the hash function given is likely easy enough, sure, however I'm not convinced enabling a "cryptographically broken" configuration setting for users is a good idea.

**Comment by catsby** [comment] 2020-02-07 12:04
I'm going to close this issue for now, as I still don't believe it's something we should do. If anyone has more supporting information or reasoning for doing so please follow-up here. Thanks!

**Closed by catsby** 2020-02-07 12:04 UTC
Labels: feature-request, secret/transit, waiting-for-response

**Comment by DorianGreen** [comment] 2020-09-19 13:39
SHA1 for OAEP padding has no real disadvantage compared to SHA2.

Granted, SHA2 is more secure, but that is arguably a non issue when padding RSA encrypted data.

If the key is to be  compatible with Microsoft key storages like CAPI or even Azure Key Vault, then an option to set the padding hash algorithm to SHA1 is required.

**Comment by larnoux** [comment] 2021-07-24 17:48
Same situation here: we imported an existing rsa key used by another system that we cannot change but we cannot use vault to decrypt anything was externally encrypted because the padding used is different (pkcs1).
It would be nice to be able to provide that at least in the import format if not as an option for keys creation.

Any system using "openssl rsautl" instead of "openssl pkeyutl" will not be able to generate a padding compatible with Vault transit.

**Comment by rcaillon-Iliad** [comment] 2023-07-24 15:16
Now that it is possible to import an externally generated key into transit engine, I think that this issue should be reconsidered. We should either be able to specify the padding scheme to be used when importing a key or when decrypting a cypher. Indeed, some legacy cryptographic devices only support OAEP with SHA1, so the support of such padding scheme is required for migrating to Hashicorp Vault easily. Furthermore, OAEP-SHA1 is supported with Azure Key Vault (see https://learn.microsoft.com/en-us/azure/key-vault/keys/about-keys-details)
