### ISSUE TITLE
Using this command:-vault operator init \ -tls-skip-verify -key-shares=1 -key-threshold=1 usage: 

### ISSUE THREAD

**Issue by prashansahans** [hashicorp/vault#8643] opened 2020-03-31 08:59 UTC
_Using this Command_
**vault operator init \ -tls-skip-verify -key-shares=1 -key-threshold=1**
_Actual Output_
usage: vault [-version] [-help] <command> [args]

Common commands:
    delete           Delete operation on secrets in Vault
    path-help        Look up the help for a path
    read             Read data or secrets from Vault
    renew            Renew the lease of a secret
    revoke           Revoke a secret.
    server           Start a Vault server
    status           Outputs status of whether Vault is sealed and if HA mode is enabled
    unwrap           Unwrap a wrapped secret
    write            Write secrets or configuration into Vault

All other commands:
    audit-disable    Disable an audit backend
    audit-enable     Enable an audit backend
    audit-list       Lists enabled audit backends in Vault
    auth             Prints information about how to authenticate with Va

Thanks!
Please suggest where the error should be

**Comment by tyrannosaurus-becks** [comment] 2020-03-31 16:10
Hi! Thank you for posting this question. 

It looks like the issue is from the syntax of the command you're using itself. Having the backslash on the same line as the rest of the statement causes it not to parse correctly. Either of these should work for you:
```
vault operator init \
    -tls-skip-verify -key-shares=1 -key-threshold=1
```
```
vault operator init -tls-skip-verify -key-shares=1 -key-threshold=1
```
Closing this for now but if you have more questions, check out [our forum](https://discuss.hashicorp.com/c/vault/30) as it's more for questions. If for some reason you're not able to use the forum though, feel free to continue here.

Thanks again! :-)

**Closed by tyrannosaurus-becks** 2020-03-31 16:10 UTC
Labels: question

**Comment by prashansahans** [comment] 2020-04-01 09:01
But there is not a syntax error.. does vault operator depend uponvault
version or as such because when i check vault status it doent show operator.


Thanks and regards
Prashansa

**Comment by tyrannosaurus-becks** [comment] 2020-04-02 18:27
@prashansahans we can double-check if the version of Vault is the issue. What version of Vault are you using? And the exact command?
