### ISSUE TITLE
Getting permission denied:forbidden while trying to read or write secrets

### ISSUE THREAD

**Issue by prgoel96** [hashicorp/vault#6403] opened 2019-03-13 05:36 UTC
Please post questions on the mailing list (https://groups.google.com/forum/#!forum/vault-tool) rather than in GitHub issues.

With over 1700 subscribers, the mailing list gets a _lot_ more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the list.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by prgoel96** [comment] 2019-03-13 05:39
I am trying to access hashicorp vault through aws lambda by assuming vault role using sts. I am able to assume role but while fetching vault credentials, i am getting permission denied: forbidden
permission denied: Forbidden
Traceback (most recent call last):
File "/var/task/function.py", line 34, in lambda_handler
client.write('secret/foo', baz='bar', lease='1h')
File "/var/task/hvac/v1/__init__.py", line 227, in write
response = self._adapter.post('/v1/{0}'.format(path), json=kwargs, wrap_ttl=wrap_ttl)
File "/var/task/hvac/adapters.py", line 106, in post
return self.request('post', url, **kwargs)
File "/var/task/hvac/adapters.py", line 276, in request
utils.raise_for_error(response.status_code, text, errors=errors)
File "/var/task/hvac/utils.py", line 33, in raise_for_error
raise exceptions.Forbidden(message, errors=errors)
hvac.exceptions.Forbidden: permission denied

Here is the error.

**Comment by jefferai** [comment] 2019-03-13 13:53
Duplicate of https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/vault-tool/JcyqNcIoohE/MgwXHrufCAAJ

**Closed by jefferai** 2019-03-13 13:53 UTC

**Comment by manisha-tanwar** [comment] 2020-08-25 22:19
Hi @prgoel96 Were you able to fix the issue?
