### ISSUE TITLE
github auth fails with x509 error after upgrade to vault 0.7.2 (ent) and consul 0.8.1 (ent)

### ISSUE THREAD

**Issue by LuckyMik** [hashicorp/vault#2793] opened 2017-06-02 19:22 UTC
Github auth was previously configured and working on vault 0.6.5 (open source) running with consul 0.7.5 (open source).  We disabled the feature for some weeks prior to the upgrade.  Upon upgrading to vault 0.7.2 (ent) and consul 0.8.1 (ent), we re-enabled the github authentication as a new use case arose.  Upon re-enabling the feature, we were no longer able to authenticate using GitHub teams.  The error received is as follows:

 vault auth -method=github token=<personal access token>
Error making API request.

URL: PUT https://<vault server>/v1/auth/github/login
Code: 500. Errors:

* Get https://<enterprise github address>/api/v3/user: x509: certificate signed by unknown authority

I can run the same github api calls using the personal access token from the same system without issue.  Due to the upgrades between the testing, I rolled vault back to 0.7.2 (open source) and then 0.6.5 (open source) but the issue remained, seemingly indicating that consul is somehow contributing.  I am concerned that issue #700 may have resurfaced, but need some guidance on how to test further.

**Comment by jefferai** [comment] 2017-06-03 11:51
What commands did you use to enable/configure the mount?

**Comment by LuckyMik** [comment] 2017-06-03 14:29
vault auth-enable github
vault write auth/github/config base_url="https://<enterprise github>/api/v3/" organization="<our-org>" ttl="5m" max_ttl="5m"
vault mount-tune -default-lease-ttl="5m" -max-lease-ttl="5m" auth/github
vault write auth/github/map/teams/<our-team> value=<our-policy>

**Comment by LuckyMik** [comment] 2017-06-03 14:34
FYI, I have been placing team specific information inside left/right angle brackets and forgot that they get stripped.  Please see repost of relevant info again below:

vault auth -method=github token=[personal access token]
Error making API request.

URL: PUT https://[vault]/v1/auth/github/login
Code: 500. Errors:

Get https://[enterprise github]/api/v3/user: x509: certificate signed by unknown authority

vault auth-enable github
vault write auth/github/config base_url="https://[enterprise github]/api/v3/" organization="" ttl="5m" max_ttl="5m"
vault mount-tune -default-lease-ttl="5m" -max-lease-ttl="5m" auth/github
vault write auth/github/map/teams/[our-team] value=[our-policy]

**Comment by jefferai** [comment] 2017-06-03 14:39
Vault will use your system certificates. Looks like your CA cert isn't trusted by the server Vault is running on.

**Comment by pantocrator27** [comment] 2017-06-05 13:30
hey @jefferai, in following https://github.com/hashicorp/vault/issues/700, `curl` from the box appears to work and so what I would ask is what cert bundle is `vault` using out of the box if it is different than the default cert bundle?

**Comment by jefferai** [comment] 2017-06-05 13:46
@pantocrator27 why are you following #700?

**Comment by pantocrator27** [comment] 2017-06-05 13:53
As @LuckyMik pointed out above, the error message seemed similar to #700 with regard to the GitHub error message and was following https://github.com/hashicorp/vault/issues/700#issuecomment-148432639.

**Comment by jefferai** [comment] 2017-06-05 15:21
@pantocrator27 But you are not @LuckyMik and this is not your ticket...

**Comment by LuckyMik** [comment] 2017-06-05 15:44
@jefferai we work together, @MarsuperMammal was not available for our customer call and Josh asked us to open the ticket instead

**Comment by jefferai** [comment] 2017-06-05 16:01
Josh?

**Comment by LuckyMik** [comment] 2017-06-05 16:07
sorry, Josh Epstein <jepstein@hashicorp.com>, he did not seem to be a github member that I could find

**Comment by jefferai** [comment] 2017-06-05 16:09
Thank you. If you are a customer they should not have been pointing you to GitHub to file issues.

As for your issue, it may be related to #700, it may not. There didn't used to be a way to pass in your own client so in the past you couldn't work around what was fixed in #700 with GitHub. If that's actually the problem, it can be fixed.

**Comment by LuckyMik** [comment] 2017-06-05 16:21
Understood on the communication path and sorry for the trouble.  Regarding the issue, do you have any recommendations on next steps to help determine the root cause of our issue?  We can take this into another forum if necessary.  I could email @MarsuperMammal directly.

**Comment by jefferai** [comment] 2017-06-05 16:24
@LuckyMik No problem on the communication path, the issue is that we don't know anything about any SLAs if it's just a random GitHub issue.

We will be having a new release out soon and I am attempting to use the new bits in the oauth2 library to specify a clean transport. So the first step would be to see if that makes a difference.

**Closed** 2017-06-05 16:27 UTC

**Comment by LuckyMik** [comment] 2017-06-05 16:29
Thanks @jefferai
