### ISSUE TITLE
SSH certificate KRL signing

### ISSUE THREAD

**Issue by Celant** [hashicorp/vault#18679] opened 2023-01-12 11:00 UTC
**Is your feature request related to a problem? Please describe.**
We use Vault for SSH certificates but manage/distribute our own KRL. It is hard for us to verify the integrity of the distributed KRL file.

**Describe the solution you'd like**
We'd love to see a method added to the Vault SSH engine that would allow us to sign an arbitrary KRL file with the SSH CA key held in Vault. This would allow us to verify the integrity of the KRL with the SSH CA public key, without the overheads of Vault having to generate and manage the KRL internally.

**Describe alternatives you've considered**
We've considered also signing the KRL with our own arbitrary key, but this would require us to store, track, and distribute another key along-side the SSH CA key.

**Explain any additional use-cases**
This would greatly help in securing SSH certificate auth with Vault, as servers can then verify that the KRL was signed by one of the SSH CA keys it has knowledge of.

**Comment by cipherboy** [comment] 2023-01-12 14:23
Closing as duplicate of #3377, I'll add another response there.

**Closed by cipherboy** 2023-01-12 14:23 UTC
