### ISSUE TITLE
Rollback: error rolling back: unsupported path

### ISSUE THREAD

**Issue by carlpett** [hashicorp/vault#505] opened 2015-08-07 16:25 UTC
I'm experimenting with the PKI backend, and mounted it at `test-pki`. At one point, I accidentally threw the order around, and did `vault write pki-test [...]`. I got an error, fixed it and moved on. Ever since then, however, I'm getting this line logged every minute:

    vault[27125]: 2015/08/07 18:17:51 [ERR] rollback: error rolling back pki-test/: unsupported path

I'm guessing something is queued up, but keeps failing. How can I get rid of it? I'm running a three-node installation in HA-mode, with a Consul backend.

**Comment by sethvargo** [comment] 2015-08-07 16:30
Hey @jefferai have you seen this before?

**Comment by jefferai** [comment] 2015-08-15 12:30
@sethvargo I doubt this is related to the PKI backend. He has it mounted at `test-pki`, but the path that's throwing the error is from `pki-test` -- where the PKI backend *isn't*. So this is probably something coming from the bowels of Vault.

**Comment by carlpett** [comment] 2015-09-21 10:52
As a (temporary?) fix, I mounted a store on pki-test, waited a minute so whatever rollback was being tried could go through, and then unmounted it. Problem resolved at least insofar that it no longer spews logs.

**Comment by jefferai** [comment] 2015-09-21 11:09
When you say that during that write you "...got an error, fixed it...", what error did you get? Was it an unsupported path error that you fixed by correcting the path, or something else?

**Comment by carlpett** [comment] 2015-09-21 11:28
It was quite some while ago, so unfortunately I don't remember. I didn't notice the problem with logging failed rollback immediately, so I didn't think about writing down the error when it happened. Only a few days later when I checked the system journal did I see the logs. Sorry.

**Comment by jefferai** [comment] 2015-09-21 12:27
OK. If it happens again please let us know. I've tried replicating it but all I can think of trying is a write against a non-existent path, and this isn't triggering bad behavior for me. (It's also possible that it's simply behavior that's been fixed since 0.2.)

Sorry!

**Closed by jefferai** 2015-09-21 12:27 UTC
Labels: bug, core

**Comment by shomron** [comment] 2016-05-27 18:53
@jefferai I seem to be having a similar issue?

```
2016/05/26 04:14:13 [ERR] rollback: error rolling back auth/token/: unsupported path
2016/05/26 04:15:13 [ERR] rollback: error rolling back auth/token/: unsupported path
2016/05/26 04:16:13 [ERR] rollback: error rolling back auth/token/: unsupported path
```

Authentication gives me:

```
$ vault auth
Token (will be hidden):
Error validating token: Error making API request.

URL: GET https://<snip>:8200/v1/auth/token/lookup-self
Code: 404. Errors:

* no handler for route 'auth/token/lookup-self/'
```

**Comment by jefferai** [comment] 2016-05-27 18:57
@shomron That's a separate bug that affected `master` for some time and in certain situations. It has since been fixed, but you may or may not be able to recover from it by building from recent `master`. We tried to work around it but it's not always possible.

**Comment by shomron** [comment] 2016-05-27 18:59
Uh oh. Do you have a link to the issue number for that?

I'll rebase our fork (I'm running my ldap enhancements) and hope for good.

**Comment by jefferai** [comment] 2016-05-27 19:05
There is no issue number; we discovered it internally and patched it (2eb70f39824f36ca5f324f96aedbb3598cf72bdc). If you need to recover, and if you have backups, I can tell you what value to pull in from your backup. Since you're handy with code, you could also try dumping your `auth` table's JSON when it's being loaded in `vault/auth.go` in `loadCredentials`, manually fixing it up (based on looking at your storage to see which UUIDs actually have entries behind them -- this probably simply means removing all entries with `auth/` in the path), setting it as a constant, and having that constant value be written into storage right before loading.

**Comment by jefferai** [comment] 2016-05-27 19:06
To be clear, the code we put in that commit *may* work to fix it. It really depends on your exact situation; it did in some reproduction scenarios, but not in others that we couldn't reliably reproduce.

**Comment by shomron** [comment] 2016-05-27 19:13
Roger that, wish me luck!

**Comment by jefferai** [comment] 2016-05-27 19:17
Good luck! Sorry you're hitting this, it takes a combination of a few steps to trigger so it didn't trip unit tests and we didn't catch it ourselves until recently. The perils of using `master` -- but at the same time, finding these things and reporting them to us is super valuable, so we love our `master` users...  :heart:

**Comment by shomron** [comment] 2016-05-28 13:55
No worries! Rebasing https://github.com/hashicorp/vault/pull/1388 to incorporate your fix cleared up the exceptional state without additional surgery. Thanks again!

And so....https://www.youtube.com/watch?v=e3mLoFndR6M
