### ISSUE TITLE
Consul to Raft Migration fails to unseal post-migration

### ISSUE THREAD

**Issue by Mercwri** [hashicorp/vault#10716] opened 2021-01-18 16:16 UTC
**Describe the bug**
Migration from Consul to Vault Raft succeeds but Vault cannot unseal after the migration, cli outputs `Error unsealing: context deadline exceeded`.

**To Reproduce**
1. Run `vault operator migrate -config=migrate.hcl`
2. Start Vault with new hcl
3. Attempt to unseal Vault, on entering the last unseal key unsealing process hangs

**Expected behavior**
Vault should unseal and operate in raft storage mode.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.6.1
Vault server configuration file(s):

```vault.hcl
# Storage configuration
storage "raft" {
  path = "/vault/raft/"
  node_id = "node_1"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  cluster_address = "127.0.0.1:8201"
  tls_cert_file = "/ssl/cert.pem"
  tls_key_file = "/ssl/key.pem"
}

api_addr = "https://127.0.0.1:8200"
cluster_addr = "https://127.0.0.1:8201"
disable_mlock = true
ui=true
```

```vault log (with trace)
==> Vault server configuration:

             Api Address: https://127.0.0.1:8200
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Go Version: go1.15.4
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled")
               Log Level: trace
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: raft (HA available)
                 Version: Vault v1.6.1
             Version Sha: 6d2db3f033e02e70202bef9ec896360062b88b03

==> Vault server started! Log data will stream in below:

2021-01-18T16:00:00.667Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2021-01-18T16:00:00.685Z [DEBUG] core: set config: sanitized config={"api_addr":"https://127.0.0.1:8200","cache_size":0,"cluster_addr":"https://127.0.0.1:8201","cluster_cipher_suites":"","cluster_name":"","default_lease_ttl":0,"default_max_request_duration":0,"disable_cache":false,"disable_clustering":false,"disable_indexing":false,"disable_mlock":true,"disable_performance_standby":false,"disable_printable_check":false,"disable_sealwrap":false,"disable_sentinel_trace":false,"enable_ui":true,"listeners":[{"config":{"address":"127.0.0.1:8200","cluster_address":"127.0.0.1:8201","tls_cert_file":"/ssl/cert.pem","tls_key_file":"/ssl/key.pem"},"type":"tcp"}],"log_format":"unspecified","log_level":"","max_lease_ttl":0,"pid_file":"","plugin_directory":"","raw_storage_endpoint":false,"seals":[{"disabled":false,"type":"shamir"}],"storage":{"cluster_addr":"https://127.0.0.1:8201","disable_clustering":false,"redirect_addr":"https://127.0.0.1:8200","type":"raft"}}
2021-01-18T16:00:00.685Z [DEBUG] storage.cache: creating LRU cache: size=0
2021-01-18T16:00:00.689Z [DEBUG] cluster listener addresses synthesized: cluster_addresses=[127.0.0.1:8201]
2021-01-18T16:00:34.106Z [INFO]  http: TLS handshake error from 127.0.0.1:46364: remote error: tls: bad certificate
2021-01-18T16:01:36.653Z [DEBUG] core: unseal key supplied: migrate=false
2021-01-18T16:01:36.653Z [DEBUG] core: cannot unseal, not enough keys: keys=1 threshold=3 nonce=d64d3198-7ab2-61b9-dea9-fc232e4638cf
2021-01-18T16:01:44.091Z [DEBUG] core: unseal key supplied: migrate=false
2021-01-18T16:01:44.091Z [DEBUG] core: cannot unseal, not enough keys: keys=2 threshold=3 nonce=d64d3198-7ab2-61b9-dea9-fc232e4638cf
2021-01-18T16:01:50.410Z [DEBUG] core: unseal key supplied: migrate=false
2021-01-18T16:01:50.410Z [DEBUG] core: starting cluster listeners
2021-01-18T16:01:50.410Z [INFO]  core.cluster-listener.tcp: starting listener: listener_address=127.0.0.1:8201
2021-01-18T16:01:50.410Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=127.0.0.1:8201
2021-01-18T16:01:50.426Z [TRACE] storage.raft: setting up raft cluster
2021-01-18T16:01:50.432Z [INFO]  storage.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:3e24a88d-8036-e0fd-6699-dbcad55cf033 Address:127.0.0.1:8201}]"
2021-01-18T16:01:50.433Z [INFO]  storage.raft: entering follower state: follower="Node at 127.0.0.1:8201 [Follower]" leader=
2021-01-18T16:01:57.362Z [WARN]  storage.raft: not part of stable configuration, aborting election
```

```cli output
Key                Value
---                -----
Seal Type          shamir
Initialized        true
Sealed             true
Total Shares       5
Threshold          3
Unseal Progress    0/3
Unseal Nonce       n/a
Version            1.6.1
Storage Type       raft
HA Enabled         true
/ # vault operator unseal
Unseal Key (will be hidden):
Key                Value
---                -----
Seal Type          shamir
Initialized        true
Sealed             true
Total Shares       5
Threshold          3
Unseal Progress    1/3
Unseal Nonce       xxxx
Version            1.6.1
Storage Type       raft
HA Enabled         true
/ # vault operator unseal
Unseal Key (will be hidden):
Key                Value
---                -----
Seal Type          shamir
Initialized        true
Sealed             true
Total Shares       5
Threshold          3
Unseal Progress    2/3
Unseal Nonce       xxx
Version            1.6.1
Storage Type       raft
HA Enabled         true
/ # vault operator unseal
Unseal Key (will be hidden):
Error unsealing: context deadline exceeded
```

**Comment by jcheng-paxos** [comment] 2021-03-01 15:55
bumping this, i'm seeing the exact same error. I however am doing a migration from DynamoDB backend to Raft

**Comment by jcheng-paxos** [comment] 2021-03-01 17:27
@Mercwri did you finding a solution?

**Comment by Plasmar** [comment] 2021-04-28 04:14
bump. having exact same error.  Driving myself crazy trying to solve for 3 days now.

**Comment by Mercwri** [comment] 2021-04-28 15:16
I ended up doing the following, I was also moving from individual VMs to a k8s deployment:

1. snapshot consul raft storage
2. stand up a vault container to run migrate.hcl on
3. snapshot the vault storage after running the migrate
4. deploy vault, init, and unseal
5. import the vault raft snapshot

**Comment by czeigler** [comment] 2021-06-16 01:27
I had this exact problem.  I was able to solve it in my case.  I noticed that I put the wrong node_id in the storage_destination part of the migrate.hcl file.  That node id had a typo didn't match the correct node id in the main hcl file.  I saw this by closely looking at the output of the migrate command and I noticed from that output that it was incorrect.  In my case I had done a snapshot of the VM and successfully done a dry run migration with the exact same vault so I knew that when it didn't work it must have been my error.

**Comment by Mercwri** [comment] 2021-10-04 18:13
@prajwalsrinivasa 
The Snapshot is taken from your current running Vault ENV , you then stand up a one-off single node container and within that perform the migrate from the consul snapshot to raft, then take a Vault Raft snapshot, and import that into your k8s deployment.

Vaul/Consul -> consul-snapshot -> standalone docker vault env -> vault-snapshot -> kubernetes deployment

**Comment by prajwalsrinivasa** [comment] 2021-10-05 06:26
@Mercwri thanks for your reply. Yup I performed the same and one thing what I have noticed is the seal type should be same on both the environments like VM and K8s and then only things will be easy or else again we will see the leader election issues.

**Comment by prajwalsrinivasa** [comment] 2021-10-05 14:56
@Mercwri once you're restoring the snapshot on K8s vault, Are you able to see the HA mode active on the same. Because in my case it is going to standby node.And do you have any solution for the same.

**Comment by hsimon-hashicorp** [comment] 2021-10-05 16:03
Hi folks! I'm glad to see the community discussion around this. However, we prefer to keep GitHub to bug reports and pull requests, and we encourage people to troubleshoot and assist the community on our [Discuss Vault forum](https://discuss.hashicorp.com/c/vault/30). I'm going to close this issue, but please feel free to keep chatting on the forum, or open a new issue if there's a bug that needs looking at. Thanks! :)

**Closed by hsimon-hashicorp** 2021-10-05 16:03 UTC
Labels: core/seal, storage/raft

**Comment by Plasmar** [comment] 2022-01-18 19:42
I still think there is a bug in this.

A summary of what we have tried:
 
Ultimately, the goal which we were trying to achieve can be captured almost perfectly by the following brief blog post.  **Note: the author of the blog post uses 1.6.0 while we are using 1.8.1**.  https://www.itinsights.org/HashiCorp-Vault-Raft-Storage-Snapshot-Recovery/
 
**Important Note**: We initially had tried using the open source vault snapshot agent (basically the same thing as the Enterprise Vault automated snapshot feature/offering), which takes snapshots on a given interval based on a policy, and stores them somewhere (S3 in our case), and you can then restore from those snapshots at your leisure.  This is the step-by-step guide we followed for this (only difference is we used our own S3 storage location instead of the MinIO Docker container as described in the post). https://medium.com/hashicorp-engineering/how-to-backup-a-hashicorp-vault-integrated-storage-cluster-with-minio-33b88399bf63
 
The production cluster source where snapshots were being taken from is a transit-auto-unsealed, 3-node cluster with Raft storage. **Important Note: this cluster was the product of not only a standard data migration from a CONSUL backed legacy Vault cluster that was sunset recently, but _also_ a SEAL migration from Shamir to auto-unsealing via a single transit node servicing the 3 node production RAFT cluster.** 
 
^ This is a point that we suspect could be the root cause of the snapshot restoration issues and odd error messages.  We were unable to find any information regarding the migration’s potential effects on the underlying Raft database and its ability to have snapshots saved (without corruption or other unexpected behavior), as well as then restored to a new “DR” or backup cluster in a separate region, which did not have the same storied past of migrations and seal migrations that “prod cluster A” experienced.
 
- In taking the snapshots, as well as restoring (or attempting to), we followed the instructions in the documentation meticulously, including the little gotcha’s like including the `-force` flag on the restore command which effectively uses an entirely separate HTTP API endpoint during the restoration process.
 

- We have tried manually taking snapshots in a few different ways, including locally from the leader node using the CLI, remotely from a local terminal with the VAULT_ADDR pointed to the leader node IP, and remotely from a local terminal with the VAULT_ADDR pointed to the load balancer, and from the UI viewing the Raft cluster and using the snapshot dropdown button.
 

- We can't restore this snapshot onto a DR cluster with the same exact raft backend configuration, node configuration, etc, because there appears to be some sort of data corruption within the current prod cluster when it tries to write the snapshot
 
- Command to save snapshot: `vault operator raft snapshot save FILENAME.snap`
 

- we copy the snapshot over to the new cluster in a variety of different ways including directly over SCP, indirectly via S3 as an intermediary, and indirectly via downloading the snapshot to our local machines and then uploading to new host
 

- Command to restore snapshot: `vault operator raft snapshot restore -force FILENAME.snap`
 
- Initial efforts produced an error message indicating there is an unexpected EOF encountered upon trying to restore on the new cluster.  Less than helpful error message for diagnostics.
 
- If we try to retrieve the snapshot from production using the Raft Storage UI -> Download Snapshot functionality as root, we cannot expand the snapshot from it's .gz format (neither via double clicking it in Finder nor using the tar utility to extract it either).  We get a variety of different error messages depending on said methods of attempting extraction.  From the terminal with tar, we get the following screenshot:
 
cid:image001.png@01D7DC67.780F2680


- Expanding that .gz archive does not show the SHA256SUM files; only the state.bin and meta.json. the meta.json file looks incomplete
 

- From the GUI, we get another new and exotic error which we cannot seem to get much information on when researching further online (screenshot below):

cid:image002.png@01D7DC67.780F2680
 
 
We are incredibly thankful for anyone offering to try and help us out, and I'm happy to demonstrate some of this in a live demo if that would help.  This is actually not even an exhaustive list of all of the different permutations and combinations of ways to get this snapshot/restore process to work that we have tried, there are actually even more, but it pretty much covers it.
 
Sincerely,
Cameron,

**Comment by Plasmar** [comment] 2022-01-18 19:44
Screenshots didn't render, apologies!  The two screenshots mentioned above (in the same order):

<img width="524" alt="image001" src="https://user-images.githubusercontent.com/10328255/150007382-b9d900d7-b80b-4e3a-82b3-600072de5c5d.png">

<img width="1421" alt="image002" src="https://user-images.githubusercontent.com/10328255/150007488-53e7331c-1565-4b30-840d-d224869dee04.png">

**Comment by lucasscheepers** [comment] 2022-12-01 15:25
[I'm experiencing the same issue... ](https://github.com/hashicorp/vault/issues/18188)
