### ISSUE TITLE
Verify_connection=false not working with static roles

### ISSUE THREAD

**Issue by rakesh-kanchalwar** [hashicorp/vault#9620] opened 2020-07-29 11:06 UTC
While setting up Vault for Static credentials (rotating password only), I am making use of terraform to setup the vault in local testing(docker) and production instance. This also involves running some test cases. For this reason I want that connection should not be checked while setting up vault or testing as the target database might not be available at this time. I have used _verify_connection=false_ but some how it is not working. The setup is failing as it is not able to establish the connection.

Initially I thought that this might be terraform issue, but same issue is appearing with manual setup of vault as well.

**To Reproduce**
1. Follow instructions on this page https://learn.hashicorp.com/vault/secrets-management/db-creds-rotation, except https://learn.hashicorp.com/vault/secrets-management/db-creds-rotation#step-1-run-postgresql-in-docker-container .i.e do not setup any database.

2. Here for connection command
`vault write database/config/postgresql plugin_name=postgresql-database-plugin allowed_roles="*" connection_url="postgresql://{{username}}:{{password}}@localhost:5432/postgres?sslmode=disable" username="root" password="rootpassword"`
Below error is being thrown,

> Error writing to: database/config/postgresql.
URL: /v1/database/config/postgresql
Code: 400
Errors:
  error creating database object: error verifying connection: dial tcp [::1]:5432: connect: connection refused

3. If I use verify_connection=false with this command
`vault write database/config/postgresql plugin_name=postgresql-database-plugin allowed_roles="*"        connection_url=postgresql://{{username}}:{{password}}@localhost:5432/postgres?sslmode=disable username="root"       password="rootpassword" verify_connection=false`

Success message is disclayed as 

> Success! Data written to: database/config/postgresql

4 But for next command,
`vault write database/static-roles/education db_name=postgresql rotation_statements=@rotation.sql username="vault-edu" rotation_period=86400`
it is failing as 

> Error writing to: database/static-roles/education.
URL: /v1/database/static-roles/education
Code: 500
Errors:
  1 error occurred:
	* error setting credentials: dial tcp [::1]:5432: connect: connection refused

**Expected behavior**
verify_connection=false is working in case of Dynamic Secrets, similar behavior is expected from static credentials as well.

**Environment:**
* Vault Server Version 1.4.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.4.2
* Server Operating System/Architecture: Oracle Linux

**Comment by pcman312** [comment] 2021-02-24 21:12
Hi @rakesh-kanchalwar ! This is actually intended behavior. The `verify_connection` argument only applies to the configuration setup, not subsequent calls to create static roles. When the static role is created, Vault immediately takes ownership of the user in the database, rotates the password of that user, and starts a timer for the next time it will rotate that user's password (based on the `rotation_period`). It needs to rotate the password immediately for two reasons:
1) The previous password is unknown to Vault and therefore if `/static-creds` is called, Vault cannot give an answer
2) If the configuration is invalid (or the database otherwise inaccessible), Vault should error early so it's known that there was a problem having Vault take ownership of the user. Otherwise setting up the static role won't fail and subsequent failures during rotation will fail in the log rather than known when the role is set up.

I hope this was helpful!

**Comment by sgmiller** [comment] 2021-04-20 20:07
Closing this issue.  Please reopen if you have additional trouble.

**Closed by sgmiller** 2021-04-20 20:07 UTC
Labels: secret/database, waiting-for-response, wontfix
