### ISSUE TITLE
custom database plugin with db2

### ISSUE THREAD

**Issue by andrewKev12** [hashicorp/vault#9906] opened 2020-09-07 14:16 UTC
Trying to develop a custom database plugin for db2 database. I am using the postgresql code base and making changes on it.

importing github.com/ibmdb/go_ibm_db in the db.go file

sqltypename used is go_ibm_db.

when trying to configure the plugin using 
vault write database/config/db2-database plugin_name=db2-database-plugin connection_url="jdbc:db2://<username>:<password>@localhost:5342/" username="" password="" allowed_roles="my-role"

Obtained error as "Error creating database object:rpc error : code = unknown desc = error verifying connection : SQLDriverConnect {08001}[IBM][CLI Driver] SQL1024N Database connection does not exist. SQLSTATE = 08003

Help me know with the driver name and the db configuration for the plugin using db2.

Guide me with the steps to be carried out.

**Comment by pmorch** [comment] 2020-09-27 21:07
Did you notice that there was an existing issue about this? #6283 

I can see that this is the very first issue you've created on github. Typically, github issues is not place to get help. It is a place for reporting issues. If you have an improvement suggestion, share it. But in this case it would be a duplicate of #6283. If you have a bug which is when something doesn't work as advertised be specific about what doesn't work. https://discuss.hashicorp.com where you posted the [exact same question](https://discuss.hashicorp.com/t/driver-name-for-creating-custom-database-plugin-with-db2/13863) or https://stackoverflow.com are better places to get help.

Also, perhaps English is not your first language, but at least the last two sentences are written in [imperative](https://www.grammarly.com/blog/imperative-verbs/) form, so they read as orders. For native english speakers, it sounds like you are trying to order the rest of us around. Which is not what you want when asking somebody for help.

**Comment by raskchanky** [comment] 2020-09-28 21:19
Thank you @pmorch for pointing out that the forums are the best place to ask for help. Since there is already a forum post for this question, I'm going to close this issue.

**Closed by raskchanky** 2020-09-28 21:19 UTC
Labels: ecosystem/plugin, question
