### ISSUE TITLE
vault login doesn't work with  aws sts credentials

### ISSUE THREAD

**Issue by abdusahin** [hashicorp/vault#17923] opened 2022-11-13 23:53 UTC
**Describe the bug**
When AWS credentials are set as variables, vault login fails, it seems `AWS_SESSION_TOKEN` is ignored 
for example setting AWS credentials as below then calling vault login fails.
```
ROLE_JSON=$(aws sts assume-role --role-arn XXX --role-session-name vault-login-session)
AWS_ACCESS_KEY_ID=$(echo "${ROLE_JSON}" | jq --raw-output ".Credentials.AccessKeyId")
AWS_SECRET_ACCESS_KEY=$(echo "${ROLE_JSON}" | jq --raw-output ".Credentials.SecretAccessKey")
AWS_SESSION_TOKEN=$(echo "${ROLE_JSON}" | jq --raw-output ".Credentials.SessionToken")
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_SESSION_TOKEN

export VAULT_ADDR=AAA
export VAULT_SKIP_VERIFY=true
vault status
vault login -method=aws role=vault-role region=${region} 
```
whereas when `AWS_SESSION_TOKEN` value is passed to   `aws_security_token` option then vault login works.

Working configuration.
```
vault login -method=aws role=vault-role region=${region} \
        aws_access_key_id=${AWS_ACCESS_KEY_ID} \
        aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} \
        aws_security_token=${AWS_SESSION_TOKEN}
```

First behaviour is against AWS Login method described on  https://developer.hashicorp.com/vault/docs/auth/aws as:

`
This assumes you have AWS credentials configured in the standard locations AWS SDKs search for credentials (environment variables, ~/.aws/credentials, IAM instance profile, or ECS task role, in that order). If you do not have IAM credentials available at any of these locations, you can explicitly pass them in on the command line (though this is not recommended), omitting aws_security_token if not applicable.
`

**To Reproduce**
- export AWS credentials variables as describes in step1 above.
- try vault login command with aws auth.

**Expected behavior**
- vault login should work with AWS STS credentials without the need for explicit `aws_security_token` configuration.

**Environment:**
```
Version                  1.11.2+ent.hsm
```

**Comment by austingebauer** [comment] 2023-08-09 17:47
Thanks @abdusahin. I'm going to try to reproduce this.

**Comment by austingebauer** [comment] 2023-08-11 18:15
Hi @abdusahin. I haven't been able to reproduce this. Can you provide the error you were seeing when performing the login command using environment variables?

I successfully used the following similar to your description:
```
get_vault_aws() {
    ROLE_JSON=$(aws sts assume-role --role-arn <todo_role_arn> --role-session-name <todo_session_name>)     
    AWS_ACCESS_KEY_ID=$(echo "${ROLE_JSON}" | jq --raw-output ".Credentials.AccessKeyId")
    AWS_SECRET_ACCESS_KEY=$(echo "${ROLE_JSON}" | jq --raw-output ".Credentials.SecretAccessKey")
    AWS_SESSION_TOKEN=$(echo "${ROLE_JSON}" | jq --raw-output ".Credentials.SessionToken")
    
    export AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY
    export AWS_SESSION_TOKEN
}

# Fetch and export assume role credentials
get_vault_aws

# Login with Vault
vault login -method=aws role=dev-role-iam region=us-east-1
```

**Comment by hsimon-hashicorp** [comment] 2023-11-04 00:58
As it has been some time since we've heard from you, @abdusahin, I'll go ahead and close this issue now. Please feel free to re-open it if you can provide the information requested by Austin. Thanks!

**Closed by hsimon-hashicorp** 2023-11-04 00:58 UTC
Labels: ecosystem, waiting-for-response, auth/aws
