### ISSUE TITLE
Add periodic secrets feature

### ISSUE THREAD

**Issue by jhaohai** [hashicorp/vault#6280] opened 2019-02-22 02:25 UTC
**Is your feature request related to a problem? Please describe.**
Periodic token with max ttl unset will never expire. But the secrets engine doesn't support this feature. By setting max ttl to 0, the secrets will expire in 32 day. Our walk around is setting the max ttl to 10 year. But that was dirty.

**Describe the solution you'd like**
Add period options for secret backend.

**Comment by dekimsey** [comment] 2022-07-05 20:00
Is this an engine-specific limitation or one affecting all engines? I did a quick check and couldn't identify any secrets engines that support the setting in the docs. My search wasn't exhaustive though.

Use-case: I am interested in generating Consul tokens with a periodic TTL to address an inability in rotating the secret with Envoy. Database engine secrets would also be highly desirable.

**Comment by sgmiller** [comment] 2022-07-07 17:49
All secrets mounts can use `secrets tune` to set default and max lease TTLs. May I ask which secrets engine this is?

**Comment by aphorise** [comment] 2022-09-02 22:22
Hey folks - just adding my 2 cents. You can set the following parameters to as high as needed:

> [max_lease_ttl](https://www.vaultproject.io/docs/configuration#max_lease_ttl) (string: "768h")

Once Vault is started with this set then [you can `secret tune`](https://www.vaultproject.io/docs/commands/secrets/tune) as mentioned earlier.

There's also KV1/KV2 in which these wouldn't be applicable but I understand the issue is in the context of other secret engines where TTLs are applicable.

@jhaohai @dekimsey - do you guys agree that this issue can be closed?

**Comment by aphorise** [comment] 2022-09-09 21:36
Closing due to no follow up. Please re-open if still relevant.

**Closed by aphorise** 2022-09-09 21:36 UTC
Labels: enhancement, core/secret

**Comment by dekimsey** [comment] 2022-10-03 17:45
Hrmm. I missed this issue being closed. I don't think it's resolved myself.

What I'd like to do is be able to issue a consul ACL token that remains live for as long as the vault-agent keeps it alive (periodic tokens).

In my case we are using the consul secrets backend to generate consul tokens for our Connect/envoy apps. The issue here is that we cannot effectively replace the CONSUL_HTTP_TOKEN without an envoy outage. (Envoy itself has no ability to update/replace the secret token in use). If the backend had support for periodic tokens, we could maintain the token's ttl for the duration of vault-agent's session.

Right now vault-agent is writing a CONSUL_HTTP_TOKEN out for our `consul connect envoy` start-up. Once started though I have no ability to update this secret other than a process restart. I'm trying to reduce the number of restarts because our apps are not handling that gracefully right now.
