### ISSUE TITLE
Vault is getting sealed upon issues with object storage

### ISSUE THREAD

**Issue by andrejbiro** [hashicorp/vault#8698] opened 2020-04-08 11:47 UTC
Hi,
we have issues with our vault cluster - vault was sealed on APR-02-2020 around 5pm UTC. We have 3 nodes vault cluster. In attempt to unseal vault cluster I've restarted vault instances "systemctl restart vault" but it got sealed again.

Vault binaries version - vault-1.3.2.linux-amd64
For storage we use Oracle OCI object storage and they confirmed there was object storage outage in our region around time of our issues with vault.

Attached logs for APR-02-2020 for all three vault nodes in cluster.

There is "Vault shutdown triggered" in logs because I was doing "systemctl restart vault" in attempt to unseal our vaults. Please have a look at this snippet as I think it is showing the moment when vault got sealed -

```
Apr 02 17:06:53 vault01 vault[28151]: <head><title>502 Bad Gateway</title></head>
Apr 02 17:06:53 vault01 vault[28151]: <body bgcolor="white">
Apr 02 17:06:53 vault01 vault[28151]: <center><h1>502 Bad Gateway</h1></center>
Apr 02 17:06:53 vault01 vault[28151]: <hr><center></center>
Apr 02 17:06:53 vault01 vault[28151]: </body>
Apr 02 17:06:53 vault01 vault[28151]: </html>
Apr 02 17:06:53 vault01 vault[28151]: .. http status code: 502. Opc request id: "
Apr 02 17:06:53 vault01 vault[28151]: 2020-04-02T17:06:53.615Z [ERROR] core: shutting down
Apr 02 17:06:53 vault01 vault[28151]: 2020-04-02T17:06:53.615Z [INFO]  core: marked as sealed

```

Could you please check what went wrong that vault get sealed and help to improve vault stability? It is impacting our production customers.

Let me know if you need more info.

Thanks & Regards,
Andrej

[vault_cluster.zip](https://github.com/hashicorp/vault/files/4450226/vault_cluster.zip)

**Comment by tyrannosaurus-becks** [comment] 2020-04-08 20:00
This appears to be a dupe of #8677

**Comment by tyrannosaurus-becks** [comment] 2020-04-08 22:23
Closing as a dupe, will reopen the linked question and continue discussion there.

**Closed by tyrannosaurus-becks** 2020-04-08 22:23 UTC
Labels: question
