### ISSUE TITLE
Support renewing tokens by token accessor

### ISSUE THREAD

**Issue by charlesknipe** [hashicorp/vault#7748] opened 2019-10-28 17:24 UTC
**Is your feature request related to a problem? Please describe.**
I am building an application that manages the lifecycle of vault tokens (acquire, renew, revoke) on behalf of applications that consume vault secrets but are not, themselves, vault aware.  I'd like my service to be able to renew the tokens as long as the consuming application needs access to the secrets, and revoke them on exit.  Ideally I'd like to do this without having the renewal/revocation portion of my service have direct access to the tokens under management.  It looks like Token accessors solve the revocation use case, but renewal can currently only be done using the actual token.

**Describe the solution you'd like**
Ideally it would be great if the token accessor could be used to request renewal of a token.

**Describe alternatives you've considered**
Our alternative would be to give the renewer portion of our service access to the actual tokens, and come up with a way to safely communicate and store them.

**Explain any additional use-cases**
N/A

**Additional context**
Our service is meant to be deployed in a Kubernetes environment.  It consists of an init container for token and secrets acquisition, and a renewer/revoker service that manages the tokens based on whether the pods that acquired them are still running.  Keeping the tokens valid is specifically important to us because we are using dynamic secrets in an environment with applications that are not vault aware.  We've opted to configure dynamic secrets with very long TTL, acquired using tokens that have short renewal periods, so we can do the lifecycle management entirely at the token level rather than having to manage the lifecycle of the tokens and secrets separately.

**Comment by michelvocks** [comment] 2019-11-05 12:55
Duplicate of https://github.com/hashicorp/vault/issues/7507

**Closed by michelvocks** 2019-11-05 12:55 UTC
Labels: core/token, enhancement
