### ISSUE TITLE
arm64 compatible docker images

### ISSUE THREAD

**Issue by paymog** [hashicorp/vault#11037] opened 2021-03-03 18:05 UTC
**Is your feature request related to a problem? Please describe.**
I would like to use vault on arm64 machines - it would be great if there were arm64 compatible docker images.

**Describe the solution you'd like**
I would like to be able to pull arm64 docker images from dockerhub.

**Describe alternatives you've considered**
I'm currently working to build arm64 images for vault myself.

**Explain any additional use-cases**
With the new M1 chips and expanding use case of ARM everywhere, it would be great if vault provided out-of-the-box support.

**Additional context**
N/A

**Comment by HridoyRoy** [comment] 2021-03-08 17:14
Hi,
I'm going to close this issue as a duplicate of https://github.com/hashicorp/vault/issues/10645 . Please leave a thumbs up on that issue and add a comment if you'd like.
Thanks!

**Closed by HridoyRoy** 2021-03-08 17:14 UTC
