### ISSUE TITLE
HCL adversely auto lower case docker tag to impact expression of Host rule

### ISSUE THREAD

**Issue by vvitayau** [hashicorp/vault#8091] opened 2020-01-03 20:08 UTC
**Describe the bug**

I am unable to explicit set the docker tag in `/etc/vault.d/vault.hcl` to configure the router Host rule per https://docs.traefik.io/routing/routers/  because the docker tag gets lowered case. As a result it unable to properly evaluate the `Host` rule expression.

**To Reproduce**

1. Edit `vault.hcl` and restart
```
...
storage "consul" {
  address      = "localhost:8500"
  path         = "vault"
  service      = "vault"
  service_tags = <<EOF
traefik.http.routers.vault-http.entrypoints=http,
traefik.http.routers.vault-http.middlewares=https-redirect@file,
traefik.http.routers.vault-http.rule=Host(`vault.foo.bar`)||Host(`vault.foo.baz`),
traefik.http.routers.vault-https.entrypoints=https,
traefik.http.routers.vault-https.rule=Host(`vault.foo.bar`)||Host(`vault.foo.baz`),
traefik.http.routers.vault-https.tls=true,
traefik.http.routers.vault-https.tls.certresolver=le,
traefik.http.routers.vault-https.tls.domains[0].main=vault.foo.bar,
traefik.http.routers.vault-https.tls.domains[0].sans=vault.foo.baz,
traefik.enable=true
EOF
}
...
```

2. See error

**Expected behavior**

Neither https://vault.foo.bar nor https://vault.foo.baz works because consul tag shows `Host` in lower case
```
traefik.http.routers.vault-http.rule=host(`vault.foo.bar`)||host(`vault.foo.baz`),
traefik.http.routers.vault-https.rule=host(`vault.foo.bar`)||host(`vault.foo.baz`),
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.0
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
providers:
  consulCatalog:
    cache: false
    defaultRule: "Host(`{{ .Name }}.foo.bar.`)"
```

**Additional context**

1. At least https://vault.foo.bar will work if re-edit docker tag to remove the following rule lines below
```
traefik.http.routers.vault-http.rule=Host(`vault.foo.bar`)||Host(`vault.foo.baz`),
traefik.http.routers.vault-https.rule=Host(`vault.foo.bar`)||Host(`vault.foo.baz`),
```

**Comment by catsby** [comment] 2020-01-07 22:03
Hello - this appears to be a duplicate of https://github.com/hashicorp/vault/issues/6427, so I'm going to close this. Please follow #6427 for any updates.

**Closed by catsby** 2020-01-07 22:03 UTC
Labels: bug, core/storage
