### ISSUE TITLE
versions above 0.9.1 try to create periodic tokens even when not requested

### ISSUE THREAD

**Issue by dansteen** [hashicorp/vault#4701] opened 2018-06-05 15:44 UTC
When creating tokens from the CLI using any version above 0.9.1 (I tested them all), vault tries to create periodic tokens even when a regular token is requested.  As an example, when running the following command:

```vault token-create -ttl=1m -explicit-max-ttl=2m -renewable=true -display-name=test -use-limit=2```

Under version 0.9.1 and below I get:

```
Key             Value
---             -----
token           a9804202-329e-4585-6c5d-19080cf8d615
token_accessor  7dbe12be-249e-4496-7dd8-bc4d3be4bdd4
token_duration  1m0s
token_renewable true
token_policies  [default sysadmin]
```

While under 0.9.2 and above I get:

```
Error creating token: Error making API request.

URL: POST https://active.vault.service.consul:8200/v1/auth/token/create
Code: 400. Errors:

* root or sudo privileges required to create periodic token
```

**Environment:**
Vault Server Version: 0.9.0
Vault CLI Version: 0.9.0 - 0.10.1
Server System: Debian linux 8.6
Client System: Archlinux

Thanks!

**Comment by jefferai** [comment] 2018-06-05 16:54
Cannot reproduce:

```
$ vault token create -policy=default
Key                Value
---                -----
token              6907c671-ad61-2849-1b6f-cfe8aa786067
token_accessor     b37b2d14-0c76-834b-919c-782a352f784b
token_duration     768h
token_renewable    true
token_policies     [default]

$ vault token lookup 6907c671-ad61-2849-1b6f-cfe8aa786067
Key                 Value
---                 -----
accessor            b37b2d14-0c76-834b-919c-782a352f784b
creation_time       1528217541
creation_ttl        2764800
display_name        token
entity_id           n/a
expire_time         2018-07-07T12:52:21.80091639-04:00
explicit_max_ttl    0
id                  6907c671-ad61-2849-1b6f-cfe8aa786067
issue_time          2018-06-05T12:52:21.800916253-04:00
meta                <nil>
num_uses            0
orphan              false
path                auth/token/create
policies            [default]
renewable           true
ttl                 2764751

$ VAULT_TOKEN=6907c671-ad61-2849-1b6f-cfe8aa786067 vault token create -policy=default -ttl=1m -explicit-max-ttl=2m -renewable=true -display-name=test -use-limit=2
Key                Value
---                -----
token              9c766319-8bfa-27f7-7131-3f2b9515aba8
token_accessor     3c7d5ab5-99a4-0cdb-49bc-2a41de181777
token_duration     1m
token_renewable    true
token_policies     [default]

$ vault token lookup 9c766319-8bfa-27f7-7131-3f2b9515aba8
Key                 Value
---                 -----
accessor            3c7d5ab5-99a4-0cdb-49bc-2a41de181777
creation_time       1528217669
creation_ttl        60
display_name        token-test
entity_id           n/a
expire_time         2018-06-05T12:55:29.818491809-04:00
explicit_max_ttl    120
id                  9c766319-8bfa-27f7-7131-3f2b9515aba8
issue_time          2018-06-05T12:54:29.818491641-04:00
meta                <nil>
num_uses            2
orphan              false
path                auth/token/create
policies            [default]
renewable           true
ttl                 38
```

**Comment by jefferai** [comment] 2018-06-05 17:07
Note that you're likely seeing a fixed bug in 0.9.0 which is the server version, which is why changing the client version doesn't help.

**Comment by jefferai** [comment] 2018-06-05 17:10
Yep, I can reproduce with 0.9.0 with a newer client but not with 0.9.0 CLI and not with a newer server. Closing as this is an already-fixed bug.

**Closed by jefferai** 2018-06-05 17:10 UTC

**Comment by dansteen** [comment] 2018-06-05 17:32
I would contend that this is not a fixed bug under the assumption that newer versions of the client should be backwards compatible with older versions of the server.

**Comment by jefferai** [comment] 2018-06-05 17:33
We don't make that promise and never have.

**Comment by dansteen** [comment] 2018-06-05 17:39
Au contraire :-)

Per:  `https://www.vaultproject.io/guides/upgrading/upgrade-to-0.9.2.html`

```Backwards Compatible CLI Changes

This upgrade guide is typically reserved for breaking changes, however it is worth calling out that the
CLI interface to Vault has been completely revamped while maintaining backwards compatibility. This
could lead to potential confusion while browsing the latest version of the Vault documentation on
vaultproject.io.

All previous CLI commands should continue to work and are backwards compatible in almost all cases.

Documentation for previous versions of Vault can be accessed using the GitHub interface by browsing tags (eg 0.9.1 website tree) or by building the Vault website locally.```

I do realize that it says "almost" but it would be nice if this were included in the docs or the changelog as a backwards incompatibility.

**Comment by jefferai** [comment] 2018-06-05 17:47
The backwards compatibility being stated there was for the user UX, not the API interaction between the Vault client and server.

**Comment by dansteen** [comment] 2018-06-05 17:53
ah.  well then I suppose things are good.   Not super clear though.  Thanks for the replies!

**Comment by jefferai** [comment] 2018-06-05 18:08
No problem!
