### ISSUE TITLE
A deleted userpass user is still returned by LIST

### ISSUE THREAD

**Issue by dsuch** [hashicorp/vault#10394] opened 2020-11-13 02:16 UTC
Hello,

my Vault version is as below:

```bash
$ vault --version
Vault v1.1.0 ('36aa8c8dd1936e10ebd7a4c1d412ae0e6f7900bd')
$
```

I have an application that inadvertently created two userpass users differing only in lower-case vs. upper-case names.

* my_user_name
* My_User_Name

The application should not allow it and it is being changed to prevent it in the future. Meanwhile, I am trying to delete the users using the Vault's REST API but I am not able to delete one of them.

In particular, I deleted my_user_name but My_User_Name is still returned by the LIST command, please check below.

```bash
$ curl \
>     --header "X-Vault-Token: <root-token>" \
>     --request LIST \
>     https://127.0.0.1:8200/v1/auth/<mount-point>/userpass/users
{"request_id":"<request-id>","lease_id":"","renewable":false,"lease_duration":0,
"data":{"keys":["My_User_Name", "user2", "user3"]},"wrap_info":null,"warnings":null,"auth":null}
$ 
```

Now, when I attempt to delete the user:

```bash
$ curl -v \
>     --header "X-Vault-Token: <root-token>" \
>     --request DELETE \
>     https://127.0.0.1:8200/v1/auth/<mount-point>/userpass/users/My_User_Name

[...]

> Host: 127.0.0.1:8200
> User-Agent: curl/7.47.0
> Accept: */*
> X-Vault-Token: <root-token>
> 
< HTTP/1.1 204 No Content
< Cache-Control: no-store
< Content-Type: application/json
< Date: Fri, 13 Nov 2020 01:58:17 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
$ 
```

Please note that the DELETE call does not return anything even if the username is genuinely invalid, e.g. providing **this_user_does_not_exist** instead of **My_User_Name** does not return any error either.

Next, when I try to change My_User_Name's password, I get the message below:

```bash
$ curl \
>     --header "X-Vault-Token: <root-token>" \
>     --request POST \
>     --data @payload.json \
>     https://127.0.0.1:8200/v1/auth/<mount-point>/userpass/users/My_User_Name/password
{"errors":["1 error occurred:\n\t* username does not exist\n\n"]}
$ 
```

Thus, it appears that Vault recognised here that there is no such user even if the LIST command returns My_User_Name on output.

This is a production environment consisting of three Vault servers in a cluster. I have root tokens but I cannot restart the environment.

Can you please tell me how I can investigate it further and how I can ensure that My_User_Name is truly deleted?

Thank you.

**Comment by aphorise** [comment] 2020-11-18 15:38
Did you confirm that the Upper-Case user was actually created? - if so I'm wonder if it could be a OS specific thing as I was not able to re-produce it using version 1.1.0 - where in my case it only created a single user in lower cases. 

```bash
vault auth enable userpass ;

curl -X POST -H "X-Vault-Token: ${VAULT_TOKEN}" -d '{"password": "test1", "policies": "default"}' ${VAULT_ADDR}/v1/auth/userpass/users/My_User_Name ;

curl -s -X LIST -H "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/auth/userpass/users | jq -r . ;
  # {
  #   "request_id": "39a64e0b-3816-de36-d0bf-7c5d201a7502",
  #   "lease_id": "",
  #   "renewable": false,
  #   "lease_duration": 0,
  #   "data": {
  #     "keys": [
  #       "my_user_name"
  #     ]
  #   },
  #   "wrap_info": null,
  #   "warnings": null,
  #   "auth": null
  # }
```

In any case - are you actually [after: `auth/userpass/users/`](https://www.vaultproject.io/api-docs/auth/userpass#delete-user) without any mount specifics? - like the following which seems to work:

```bash
sUSER='my_user_name' ;

curl -X DELETE -H "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/auth/userpass/users/${sUSER} ;

curl -s -X LIST -H "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/auth/userpass/users | jq -r . ;
  # {
  #   "errors": []
  # }
```

**Comment by dsuch** [comment] 2020-11-18 16:15
Thanks @aphorise - yes, I am sure the user used to be there, I confirmed it with the initial LIST. I then went ahead and tried to delete both; one was deleted but the other could not be which is what led me to opening of this ticket.

The mount point is in the format /v1/auth/<some-data>/userpass rather than /v1/auth/userpass, this is correct.

That version of Vault works well so there is not much incentive to change it. This particular situation is not a big concern, I was just trying to clean up things.

Say, there is no command to dump the full contents of the database on some very low level, is there?

**Comment by dsuch** [comment] 2020-11-18 18:39
Also, @aphorise - please note that regardless of whether both users truly existed (they did), today My_User_Name is for sure returned via LIST.

Yet, a POST to change the user's password fails so at the very least this is some inconsistency in that LIST returns a user but the password cannot be changed.

**Comment by aphorise** [comment] 2020-11-18 22:06
@dsuch hey - out of interest:
1. What's your OS & disk types? (`uname -pisorv && df -lhaT`)
2. Using Consul? - if so which version?
3. Have you [enabled: `raw_storage_endpoint`](https://www.vaultproject.io/docs/configuration#raw_storage_endpoint)?
  I'm thinking if `vault list ...` & `vault delete ...` could be an option for low-level clean-up.

Curious if there's a quick way using Vagrant or otherwise I can recreate your scenario :computer: :floppy_disk:

**Comment by dsuch** [comment] 2020-11-23 14:33
Hi @aphorise,

I thank you again for your assistance, and I will leave all the details for future reference, but I will not be really able to spend more time on this ticket.

If you are an employee of Hashicorp then I kindly suggest to keep the ticket in mind because there clearly was some kind of a confusion in this setup but, because this is not a big concern in our case, I just cannot work on it more.

Here are the specifics of the system:

```bash
$ consul --version
Consul v1.3.1
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
$ 
```

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
$ 
```

```bash
$ uname -pisorv
Linux 4.4.0-1084-aws #94-Ubuntu SMP Fri May 17 13:10:20 UTC 2019 x86_64 x86_64 GNU/Linux
$ 
```

Unfortunately, I cannot run "df -lhaT" because it would reveal too much information - but please just let me know if there is a part of it that you are particularly interested in?

As to the raw_storage endpoint - it is not enabled.

Thanks again.

**Comment by aphorise** [comment] 2020-11-24 01:37
@dsuch What's the filesystem type that you're using? (that's what the `df -T` was intended for).

**Comment by dsuch** [comment] 2020-11-24 12:43
I cannot list the mount points in a public ticket but I can confirm that both Consul and Vault use ext4. Thanks.

**Comment by aphorise** [comment] 2020-11-25 15:50
I was still unable to reproduce this @dsuch (see below). I think your best option is to try using `consul kv` to manually remove the entry - eg:

```
uname -pisorv && df -lhT && consul --version && vault --version ;
  # Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) unknown unknown GNU/Linux
  # Filesystem     Type      Size  Used Avail Use% Mounted on
  # /dev/sda1      ext4       19G  1.9G   16G  11% /
  # Consul v1.3.1
  # Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
  # Vault v1.1.0 ('36aa8c8dd1936e10ebd7a4c1d412ae0e6f7900bd')

vault auth enable userpass ;
curl -X POST -H "X-Vault-Token: ${VAULT_TOKEN}" -d '{"password": "test1", "policies": "default"}' ${VAULT_ADDR}/v1/auth/userpass/users/My_User_Name ;
curl -s -X LIST -H "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/auth/userpass/users | jq -r . ;
  # {
  #   "request_id": "4f325e69-8330-3cef-a19b-fe171f260b1b",
  #   "lease_id": "",
  #   "renewable": false,
  #   "lease_duration": 0,
  #   "data": {
  #     "keys": [
  #       "my_user_name"
  #     ]
  #   },
  #   "wrap_info": null,
  #   "warnings": null,
  #   "auth": null
  # }

# // DELETE above via `consul kv`
consul kv get -recurse -separator="" -keys vault/ ;
  # vault/auth/ccc480a0-7884-1d4a-8d79-b2aaf2678654/user/my_user_name
  # ....
consul kv delete vault/auth/ccc480a0-7884-1d4a-8d79-b2aaf2678654/user/my_user_name ;
curl -s -X LIST -H "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/auth/userpass/users | jq -r . ;
  # {
  #   "errors": []
  # }
```

**Comment by swayne275** [comment] 2021-01-06 19:21
Closing because this issue has been without update for 30+ days. Please re-open if it hasn't been resolved.

**Closed by swayne275** 2021-01-06 19:21 UTC
Labels: version/1.1.x, waiting-for-response
