### ISSUE TITLE
Vault 0.11.4 client cannot auth (aws) against Vault 0.11.3 Server

### ISSUE THREAD

**Issue by myoung34** [hashicorp/vault#5649] opened 2018-10-30 19:21 UTC
**Describe the bug**

Client 0.11.4 with Server 0.11.3 with aws auth causes a crash

**To Reproduce**
1. Run `vault login -method=aws`

**Expected behavior**
Should auth succesfully or fail gracefully

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.3
* Vault CLI Version (retrieve with `vault version`): 0.11.4
* Server Operating System/Architecture: Linux amd64

Vault server configuration file(s):

n/a

**Additional context**

```

$ vault status
Key             Value
---             -----
Seal Type       shamir
Sealed          false
Total Shares    5
Threshold       3
Version         0.11.3
Cluster Name    vault-cluster-d963f07e
Cluster ID      redact
HA Enabled      false


$ docker run -it -e VAULT_ADDR=$VAULT_ADDR vault:0.11.3 vault login -method=aws
Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --privileged or --cap-add IPC_LOCK
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

WARNING! The following warnings were returned from Vault:

  * TTL of "1h0m0s" exceeded the effective max_ttl of "5m0s"; TTL value is
  capped accordingly

Key                                Value
---                                -----
token                              redact
token_accessor                     redact
token_duration                     5m
token_renewable                    true
token_policies                     ["default" "ops"]
identity_policies                  []
policies                           ["default" "ops"]
token_meta_client_user_id          redact
token_meta_inferred_aws_region     n/a
token_meta_inferred_entity_id      n/a
token_meta_inferred_entity_type    n/a
token_meta_account_id              redact
token_meta_auth_type               iam
token_meta_canonical_arn           redact
oken_meta_client_arn              redact


$ docker run -it -e VAULT_ADDR=$VAULT_ADDR vault:0.11.4 vault login -method=aws
Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --privileged or --cap-add IPC_LOCK
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/hashicorp/vault/command.(*LoginCommand).Run(0xc00050e230, 0xc0000380b0, 0x0, 0x0, 0xc0001fd700)
        /gopath/src/github.com/hashicorp/vault/command/login.go:255 +0xdee
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc000527a40, 0xc000527a40, 0xc0001fdae0, 0xc00026e5a0)
        /gopath/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x207
github.com/hashicorp/vault/command.RunCustom(0xc0000380a0, 0x2, 0x2, 0xc0005127d0, 0x0)
        /gopath/src/github.com/hashicorp/vault/command/main.go:170 +0x74a
github.com/hashicorp/vault/command.Run(0xc0000380a0, 0x2, 0x2, 0xc0000a6058)
        /gopath/src/github.com/hashicorp/vault/command/main.go:81 +0x48
main.main()
        /gopath/src/github.com/hashicorp/vault/main.go:10 +0x62

```

**Comment by vishalnayak** [comment] 2018-10-30 19:40
Duplicate of #5600

**Closed by vishalnayak** 2018-10-30 19:40 UTC
