### ISSUE TITLE
1.7.0rc1 Azure AD - OIDC nil pointer exception

### ISSUE THREAD

**Issue by alexanderccc** [hashicorp/vault#11125] opened 2021-03-17 13:40 UTC
**Describe the bug**
When setting up OIDC with vault 1.7.0rc1 and azure ad when the process sort of finishes we get a runtime error: invalid memory address or nil pointer dereference. We had issues with OIDC setup of vault with azure ad, with latest stable, 1.6.3 where the token_id was not "found" by vault. With upgrading to 1.7.0rc1 we can see the proper token in the request but it seems that it's causing issues with vault.

**To Reproduce**
Set OIDC with vault and azure ad and test it out.

**Expected behavior**
Login should be performed.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.0rc1
* Vault CLI Version (retrieve with `vault version`): 1.7.0rc1
* Server Operating System/Architecture: AWS linux v2

Vault server configuration file(s):

```hcl
ui = true
listener "tcp" {
   address = "0.0.0.0:8200"
   tls_disable = 1
}
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
  tls_skip_verify = true
  service = "vault"
  service_tags = "vault"
  service_address = ""
}
api_addr = "http://0.0.0.0:8200"
max_lease_ttl = "10h"
default_lease_ttl = "10h"
cluster_name = "vault"
cluster_addr = ""
log_level = "trace"
```

**Additional context**
Log when executing the OIDC login from either UI or CLI

```
Mar 16 20:06:00 keystore-02 vault[12323]: 2021-03-16T20:06:00.967Z [DEBUG] auth.oidc.auth_oidc_2a9b7196: OIDC provider response: id_token=*******************************.xxxxxxxxxxx
Mar 16 20:06:00 keystore-02 vault[12323]: 2021-03-16T20:06:00.968Z [INFO]  http: panic serving 10.40.3.12:46814: runtime error: invalid memory address or nil pointer dereference
Mar 16 20:06:00 keystore-02 vault[12323]: goroutine 850 [running]:
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.(*conn).serve.func1(0xc000c9a1e0)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:1801 +0x147
Mar 16 20:06:00 keystore-02 vault[12323]: panic(0x4966500, 0x892d830)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/runtime/panic.go:975 +0x47a
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vendor/github.com/hashicorp/cap/oidc.(*Tk).StaticTokenSource(...)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vendor/github.com/hashicorp/cap/oidc/token.go:113
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vendor/github.com/hashicorp/vault-plugin-auth-jwt.(*jwtAuthBackend).pathCallback(0xc000cf71a0, 0x5cfa240, 0xc000dd0780, 0xc000cd6000, 0xc0000404e0, 0x4000106, 0x0, 0xffffffffffffffff)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_oidc.go:262 +0x691
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vendor/github.com/hashicorp/vault/sdk/framework.(*Backend).HandleRequest(0xc000cf52b0, 0x5cfa240, 0xc000dd0780, 0xc000cd6000, 0x0, 0x0, 0x0)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vendor/github.com/hashicorp/vault/sdk/framework/backend.go:272 +0x4cc
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/builtin/plugin.(*PluginBackend).HandleRequest.func1(0x30, 0x477245e909546464)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/builtin/plugin/backend.go:200 +0x5a
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/builtin/plugin.(*PluginBackend).lazyLoadBackend(0xc0011ffcc0, 0x5cfa240, 0xc000dd0780, 0x5cfad80, 0xc000903680, 0xc0010b67a0, 0x0, 0x0)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/builtin/plugin/backend.go:162 +0x9d
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/builtin/plugin.(*PluginBackend).HandleRequest(0xc0011ffcc0, 0x5cfa240, 0xc000dd0780, 0xc000cd6000, 0x0, 0xc000f36100, 0x28)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/builtin/plugin/backend.go:198 +0xbb
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc000b13400, 0x5cfa240, 0xc000dd0780, 0xc000cd6000, 0x62cdfd4700, 0x0, 0xc001050000, 0x0, 0x0)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vault/router.go:684 +0x959
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vault.(*Router).Route(...)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vault/router.go:484
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vault.(*Core).doRouting(0xc00053e600, 0x5cfa240, 0xc000dd0780, 0xc000cd6000, 0xc000904870, 0x0, 0x0)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:598 +0x59
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vault.(*Core).handleLoginRequest(0xc00053e600, 0x5cfa240, 0xc000dd0780, 0xc000cd6000, 0x0, 0x0, 0x0, 0x0)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:1077 +0xb45
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vault.(*Core).handleCancelableRequest(0xc00053e600, 0x5cfa240, 0xc000dd0750, 0x8937a60, 0xc000cd6000, 0x0, 0x0, 0x0)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:464 +0x2fe
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vault.(*Core).switchedLockHandleRequest(0xc00053e600, 0x5cfa240, 0xc000dd0570, 0xc000cd6000, 0xc0010b7201, 0x0, 0x0, 0x0)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:426 +0x385
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vault.(*Core).HandleRequest(...)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:391
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/http.request(0xc00053e600, 0x5ccdb80, 0xc0004ce540, 0xc000efa900, 0xc000cd6000, 0x0, 0x0)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/http/handler.go:822 +0x7e
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/http.handleLogicalInternal.func1(0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/http/logical.go:444 +0x39e
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.HandlerFunc.ServeHTTP(0xc000710060, 0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:2042 +0x44
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/http.handleRequestForwarding.func1(0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/http/handler.go:756 +0x2c2
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.HandlerFunc.ServeHTTP(0xc000710080, 0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:2042 +0x44
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.(*ServeMux).ServeHTTP(0xc0005616c0, 0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:2417 +0x1ad
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/http.wrapHelpHandler.func1(0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/http/help.go:24 +0x14a
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.HandlerFunc.ServeHTTP(0xc000710140, 0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:2042 +0x44
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/http.wrapCORSHandler.func1(0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/http/cors.go:29 +0x91e
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.HandlerFunc.ServeHTTP(0xc000710160, 0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:2042 +0x44
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/http.rateLimitQuotaWrapping.func1(0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/http/util.go:98 +0xa95
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.HandlerFunc.ServeHTTP(0xc000710180, 0x5ccdb80, 0xc0004ce540, 0xc000efa900)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:2042 +0x44
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x5ccdb80, 0xc0004ce540, 0xc000efa000)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/http/handler.go:323 +0x4a4
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.HandlerFunc.ServeHTTP(0xc000838c30, 0x5ccdb80, 0xc0004ce540, 0xc000efa000)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:2042 +0x44
Mar 16 20:06:00 keystore-02 vault[12323]: github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp.PrintablePathCheckHandler.func1(0x5ccdb80, 0xc0004ce540, 0xc000efa000)
Mar 16 20:06:00 keystore-02 vault[12323]: /gopath/src/github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp/handlers.go:42 +0xba
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.HandlerFunc.ServeHTTP(0xc0007101a0, 0x5ccdb80, 0xc0004ce540, 0xc000efa000)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:2042 +0x44
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.serverHandler.ServeHTTP(0xc000b76620, 0x5ccdb80, 0xc0004ce540, 0xc000efa000)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:2843 +0xa3
Mar 16 20:06:00 keystore-02 vault[12323]: net/http.(*conn).serve(0xc000c9a1e0, 0x5cfa180, 0xc000c6e180)
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:1925 +0x8ad
Mar 16 20:06:00 keystore-02 vault[12323]: created by net/http.(*Server).Serve
Mar 16 20:06:00 keystore-02 vault[12323]: /goroot/src/net/http/server.go:2969 +0x36c
```

**Comment by HridoyRoy** [comment] 2021-03-18 02:29
Hello,
I'm not able to reproduce this. A runbook with the general steps to do this would be super helpful. 
Thanks1

**Comment by kalafut** [comment] 2021-03-18 03:18
@alexanderccc Thanks for testing the RC and for the panic logs!

cc @austingebauer @jimlambrt

**Comment by austingebauer** [comment] 2021-03-18 04:05
@alexanderccc - Are you able to provide more details around your configuration of OIDC auth? The panic in the stack trace suggests to me that you're using an implicit flow by setting [oidc_response_types](https://www.vaultproject.io/api-docs/auth/jwt#oidc_response_types) to `id_token`. I'd like to verify my assumption so that we can get a fix in place. Thanks!

**Comment by alexanderccc** [comment] 2021-03-18 20:55
@austingebauer Sorry for my delayed response. You are correct the response_type is set to id_token, bellow is my OIDC configuration:

```
bound_issuer                                                                                      
default_role           test                                                                     
jwks_ca_pem                                                                                       
jwks_url                                                                                          
jwt_supported_algs     []                                                                         
jwt_validation_pubkeys []                                                                         
oidc_client_id         *********                                      
oidc_discovery_ca_pem                                                                             
oidc_discovery_url     https://login.microsoftonline.com/**********/v2.0
oidc_response_mode     form_post                                                                  
oidc_response_types    ["id_token"]                                                               
provider_config        {"provider":"azure"}     
```

The issue that we faced with OIDC was unrelated to vault and something wrong with azure, so I guess that when this bug is fixed this ticket can be closed

**Comment by austingebauer** [comment] 2021-03-18 21:04
@alexanderccc - Thanks for providing the configuration. That confirms my understanding of what's happening. I was able to reproduce the issue and am currently working on a fix. 

Thanks again for testing out the RC 👍

**Comment by alexanderccc** [comment] 2021-03-18 21:05
awesome! Let me know if more information is required.

**Comment by briankassouf** [comment] 2021-03-19 21:13
fixed in https://github.com/hashicorp/vault-plugin-auth-jwt/pull/163 & https://github.com/hashicorp/vault/pull/11157. Going to close, but please let us know if you have any further issues!

**Closed by briankassouf** 2021-03-19 21:13 UTC
Labels: bug
