### ISSUE TITLE
Allow users to set custom global banners in the UI

### ISSUE THREAD

**Issue by wwsean08** [hashicorp/vault#6584] opened 2019-04-12 22:14 UTC
**Is your feature request related to a problem? Please describe.**
As an administrator in the middle of beta testing vault internally I would like to be able to setup a banner on the UI for all people that use it to tell them explicitly this is a beta setup and may go away or change.  Below is a screenshot of an example of what I was thinking:

![Screen Shot 2019-04-12 at 3 03 58 PM](https://user-images.githubusercontent.com/839261/56068618-5a872680-5d34-11e9-8d41-9c9dd5d1df27.png)

**Describe the solution you'd like**
When users add an entry to sys/config/ui/banner with the value text="Text I want to display" then that text will be displayed.  Also potentially adding the ability to see it before logging in with a tune parameter like the auth policies of listing_visibility=unauth.

**Describe alternatives you've considered**
Can't really think of an alternative

**Explain any additional use-cases**
This could also be useful to display warnings about any planned maintenance coming up or any known issues that are currently being tracked.

**Additional context**

**Comment by meirish** [comment] 2019-04-16 14:38
We don't have anything like this currently, but if you wanted to build Vault to use in these deployments, you can set `UI_AUTH_WELCOME` at build time - https://github.com/hashicorp/vault/blob/master/ui/config/environment.js#L77. This gets picked up by the UI and showed when the user is authenticating - it was added for use on our demo site https://demo.vaultproject.io - the blue message in the lower left is driven by this.

**Comment by wwsean08** [comment] 2019-04-16 18:01
I saw that while trying to get this working @meirish, i have the backend working for this enhancement request (based on what I specified) though i'm having trouble figuring out how to get the value to display via the UI as I'm normally a back end developer and don't really know javascript or ember.js.  I do have a spot for it in the template and the styling done (theoretically) just trying to figure out how to get the value to actually display.

**Comment by tlin20151** [comment] 2020-07-08 13:56
I have a requirement to add/customize a banner (in addition to a footer)similar to @wwsean08 's UI.  Do we have any progress on this ticket?

Additionally, is there a way to add and customize a disclaimer or message on the login screen?

**Comment by bastelfreak** [comment] 2021-02-04 08:39
Hi people. I also would like to display data collection notice before/after the login in the web ui. Is that somehow possible without repackaging vault?

**Comment by xunto** [comment] 2021-12-02 09:49
I want to add another use case. 

We want to have a separate vault for our staging. The problem is we are afraid somebody may mistake production vault for staging one, so we would want to make them somehow visually different.

So having a banner that says "This is staging vault." would work, good alternative would be changing styles but there is no such option either.

**Comment by tcjolie** [comment] 2022-06-21 20:49
Hello - in addition to the use case mentioned by xunto above (clearly calling out stg vs. prod) - we'd like to display a banner as mentioned by others.  In our case, it would be really great to prompt our users regarding a shift in login process.  We're sending emails and slack notifications, but we all know people often do not read these and having the information as a banner would allow us to avoid confusion for sure.

**Comment by mikenomitch** [comment] 2023-02-02 22:43
Adding a reference to Nomad's PR that implements this in case it helps anybody (internal or external) when implementing this in Vault - https://github.com/hashicorp/nomad/issues/10813

**Comment by xunto** [comment] 2023-03-04 13:04
> Sorry for the ignorance folks - but is it not possible to [clone the repo](https://github.com/hashicorp/vault) - and specifically [hacking your own UI logo / build](https://github.com/hashicorp/vault/tree/main/ui) as per [build steps](https://github.com/hashicorp/vault#developing-vault) already available?

It is possible but we don't want to have to maintain a new fork, update it, etc Especially for such a minor thing.

**Comment by finnstech** [comment] 2023-10-13 20:58
We are working on this for an upcoming release of Vault. Stay tuned!

**Comment by hellobontempo** [comment] 2024-03-19 19:18
This feature has been released as of `1.16.0-rc1` https://github.com/hashicorp/vault/pull/23945

**Closed by hellobontempo** 2024-03-19 19:18 UTC
Labels: ui, enhancement, ticketed

**Comment by AleksArabadzhy** [comment] 2024-12-02 09:45
> We are working on this for an upcoming release of Vault. Stay tuned!

Hi @finnstech 
Any updates?

**Comment by hellobontempo** [comment] 2024-12-02 15:57
Hey there @AleksArabadzhy. This was released as an enterprise feature to version 1.16. I realize my above comment wasn't clear about the version, so I've amended it. The Vault docs can be viewed here [Vault Custom Messages](https://developer.hashicorp.com/vault/docs/ui/custom-messages)
