### ISSUE TITLE
etcd v3 as storage failing with connection error

### ISSUE THREAD

**Issue by raoofm** [hashicorp/vault#2518] opened 2017-03-21 22:33 UTC
[rm@vm-01 ~]$ vault server -config=vault_config.hcl -log-level=debug
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://node01.example.com:8200
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: debug
                   Mlock: supported: true, enabled: false
        Redirect Address: http://node01.example.com:8200
                 Storage: etcd (HA available)
                 Version: Vault v0.7.0
             Version Sha: 614deacfca3f3b7162bbf30a36d6fc7362cd47f0

==> Vault server started! Log data will stream in below:

2017/03/21 22:26:39.101239 [WARN ] Failed to dial node05.dev.etcd.com:2379: connection error: desc = "transport: context canceled"; please retry.
2017/03/21 22:26:39.101400 [WARN ] Failed to dial node01.dev.etcd.com:2379: connection error: desc = "transport: context canceled"; please retry.
2017/03/21 22:26:39.101437 [WARN ] Failed to dial node03.dev.etcd.com:2379: connection error: desc = "transport: context canceled"; please retry.
2017/03/21 22:26:39.101471 [WARN ] Failed to dial node04.dev.etcd.com:2379: connection error: desc = "transport: context canceled"; please retry.

^C==> Vault shutdown triggered
[rm@vm-01 ~]$ more vault_config.hcl
storage "etcd" {
  address = "https://node01.dev.etcd.com:2379,https://node02.dev.etcd.com:2379,https://node03.dev.etcd.com:2379,https://node04.dev.etcd.com:2379,https://node05.dev.etcd.com:2379"
  path    = "vault/dev/"
  etcd_api = "v3"
  ha_enabled = "true"
  redirect_addr = "http://node01.example.com:8200"
  cluster_addr = "http://node01.example.com:8200"
  sync = "true"
  tls_ca_file = "/var/home/rm/etcdCerts/etcd.trustedca.crt"
  tls_cert_file = "/var/home/rm/etcdCerts/etcd.crt"
  tls_key_file = "/var/home/rm/etcdCerts/etcd.key"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = "true"
}

telemetry {
  disable_hostname = true
}

disable_mlock = true

**Comment by raoofm** [comment] 2017-03-21 22:35
adding @xiang90 @heyitsanthony

**Comment by raoofm** [comment] 2017-03-21 22:35
running etcd version 3.1.3 and vault version 0.7.0

**Comment by xiang90** [comment] 2017-03-21 22:51
@raoofm Have you tried etcd3 without TLS?

**Comment by raoofm** [comment] 2017-03-22 16:18
@xiang90 tried didn't work.
@jefferai 
[rm@vm-01 ~]$ vault server -config=vault_config.hcl -log-level=debug
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://nodoe01.example.com:8200
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: debug
                   Mlock: supported: true, enabled: false
        Redirect Address: http://node01.example.com:8200
                 Storage: etcd (HA available)
                 Version: Vault v0.7.0
             Version Sha: 614deacfca3f3b7162bbf30a36d6fc7362cd47f0

==> Vault server started! Log data will stream in below:

2017/03/22 16:08:46.947428 [WARN ] Failed to dial node03.example.com:2379: grpc: the connection is closing; please retry.
2017/03/22 16:08:46.947572 [WARN ] Failed to dial node02.example.com:2379: grpc: the connection is closing; please retry.


[rm@node01 ~]$ vi vault_config.hcl
storage "etcd" {
  address = "http://node01.example.com2379,http://node02.example.com2379,http://node03.example.com2379"
  path    = "vault/dev/"
  etcd_api = "v3"
  ha_enabled = "true"
  redirect_addr = "http://node01.example.com8200"
  cluster_addr = "http://node01.example.com8200"
  sync = "true"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 1
}

disable_mlock = true

------------------------------
[rm@node01 ~]$ ps -ef | grep etcd
etcd     11360     1  0 15:03 ?        00:00:22 /var/lib/etcd/etcd -initial-cluster node01=https://node01.example.com:2380,node02=https://node02.example.com:2380,node03=https://node03.example.com:2380 -advertise-client-urls http://node01.example.com:2379 -initial-cluster-state new -name node01 -data-dir /var/lib/etcd/cluster/datadir -listen-peer-urls https://node01.example.com:2380 -initial-advertise-peer-urls https://node01.example.com:2380 -listen-client-urls http://node01.example.com:2379 -peer-trusted-ca-file /var/home/rm/cfssl/ca.pem -peer-cert-file /var/home/rm/cfssl/member1.pem -peer-key-file /var/home/rm/cfssl/member1-key.pem -heartbeat-interval 200 -election-timeout 2000 -initial-cluster-token etcd-cluster-dev

[rm@node02 ~]$ ps -ef | grep etcd
etcd     11707     1  0 15:03 ?        00:00:19 /var/lib/etcd/etcd -initial-cluster node02=https://node02.example.com:2380,node01=https://node01.example.com:2380,node03=https://node03.example.com:2380 -advertise-client-urls http://node02.example.com:2379 -initial-cluster-state new -name node02 -data-dir /var/lib/etcd/cluster/datadir -listen-peer-urls https://node02.example.com:2380 -initial-advertise-peer-urls https://node02.example.com:2380 -listen-client-urls http://node02.example.com:2379 -peer-trusted-ca-file /var/home/rm/cfssl/ca.pem -peer-cert-file /var/home/rm/cfssl/member2.pem -peer-key-file /var/home/rm/cfssl/member2-key.pem -heartbeat-interval 200 -election-timeout 2000 -initial-cluster-token etcd-cluster-dev

[rmohammed@apigateway-vm-03 ~]$ ps -ef | grep etcd
etcd     18702     1  0 15:02 ?        00:00:25 /var/lib/etcd/etcd -initial-cluster node03=https://node03.example.com:2380,node02=https://node02.example.com:2380,node01=https://node01.example.com:2380 -advertise-client-urls http://node03.example.com:2379 -initial-cluster-state new -name node03 -data-dir /var/lib/etcd/cluster/datadir -listen-peer-urls https://node03.example.com:2380 -initial-advertise-peer-urls https://node03.example.com:2380 -listen-client-urls http://node03.example.com:2379 -peer-trusted-ca-file /var/home/rm/cfssl/ca.pem -peer-cert-file /var/home/rm/cfssl/member3.pem -peer-key-file /var/home/rm/cfssl/member3-key.pem -heartbeat-interval 200 -election-timeout 2000 -initial-cluster-token etcd-cluster-dev

**Comment by xiang90** [comment] 2017-03-22 17:50
OK. I will give it a try late this week.

**Comment by raoofm** [comment] 2017-03-22 19:48
@xiang90 thanks. can this be sooner as this is a blocker. We chose etcd backend over others due to its reliability and perf and as we already had its setup in prod, went through the upgrade cycle and are very excited to use this feature in prod along with kubernetes. Please :smile:

**Comment by raoofm** [comment] 2017-03-22 21:34
@xiang90 it seems like a false alarm... though it complains connection errors in logs, but I'm able to run the commands against vault. so not urgent, take your time

I will update if I have any findings.

**Comment by xiang90** [comment] 2017-03-22 22:27
@raoofm OK. Just let me know.

**Comment by raoofm** [comment] 2017-03-28 15:54
@xiang90 though it seems to work. I still don't know the cause of the warning messages. Is that a false alarm, then can that be removed?

**Comment by raoofm** [comment] 2017-05-10 15:21
@jefferai any ideas

==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://node-03.example.com:8201
              Listener 1: tcp (addr: "node-03.example.com:8200", cluster address: "node-03.example.com:8201", tls: "enabled")
               Log Level: trace
                   Mlock: supported: true, enabled: true
        Redirect Address: https://node-03.example.com:8200
                 Storage: etcd (HA available)
                 Version: Vault v0.7.0
             Version Sha: 614deacfca3f3b7162bbf30a36d6fc7362cd47f0

==> Vault server started! Log data will stream in below:

2017/05/10 15:16:40.616878 [WARN ] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.1.1.6:2379: getsockopt: connection refused"; Reconnecting to {etcd-node-03.example.com:2379 <nil>}
2017/05/10 15:16:40.630391 [WARN ] Failed to dial etcd-node-01.example.com:2379: connection error: desc = "transport: context canceled"; please retry.
2017/05/10 15:16:40.630524 [WARN ] Failed to dial etcd-node-03.example.com:2379: context canceled; please retry.

**Comment by jefferai** [comment] 2017-05-22 17:15
Nope, @xiang90 might have more ideas.

**Comment by yg-xue** [comment] 2017-09-05 13:27
Hi,

I have the same problem ([WARN ] Failed to dial %s: %v; please retry. etcd:2379 grpc: the connection is closing). Does anyone have any update about this issue? Thanks in advance.

**Comment by jefferai** [comment] 2017-09-05 14:04
None, but from the previous user's errors it appears that their etcd node is down.

**Comment by xiang90** [comment] 2017-09-05 14:19
@yg-xue can you provide your setup and the steps to reproduce the problem?

**Comment by yg-xue** [comment] 2017-09-05 16:28
@xiang90  My vault and etcd are running in docker containers. I checked my etcd pods, they are working well.  My vault's config.hcl:

disable_cache = true                                                                                                                                                                                                                                                                                  
storage "etcd" {                                                                                                                                                                                                                                                                      
  address  = "http://etcd:2379"                                                                                                                                                                                                                                                       
  etcd_api = "v3"                                                                                                                                                                                                                                                                     
  path = "vault/"                                                                                                                                                                                                                                                                     
}                                                                                                                                                                                                                                                                                       
listener "tcp" {                                                                                                                                                                                                                                                                      
  address = "127.0.0.1:8200"                                                                                                                                                                                                                                                          
  tls_disable = 1                                                                                                                                                                                                                                                                     
}

**Comment by yg-xue** [comment] 2017-09-12 17:51
My error logs gone after I set etcd_api to "v2". Thanks!

**Comment by brunomcustodio** [comment] 2017-09-14 17:05
> My error logs gone after I set etcd_api to "v2". Thanks!

I believe this is not an acceptable workaround for most users.

In my scenario (Kubernetes deployment of Vault with `etcd` managed by `etcd-operator`) these messages go away after setting

```hcl
storage "etcd" {
    // (...)
    sync = "false"
    // (...)
}
```

in the configuration. However, I am still not satisfied with this solution. Any other ideas @jefferai @xiang90 ?

**Comment by xiang90** [comment] 2017-09-14 18:57
@brunomcustodio 

Thanks for the info. I think I know what is going wrong. I will get it fixed in the next few days.

**Comment by xiang90** [comment] 2017-09-14 23:45
@brunomcustodio which version of vault are you running?

**Comment by brunomcustodio** [comment] 2017-09-15 05:04
@xiang90 I've seen this with both `v0.8.2` and `HEAD`.

**Comment by dmyerscough** [comment] 2017-09-26 05:28
I am getting the same errors

```
./vault server -config=miru.hcl                                                                                                                   
==> Vault server configuration:                                                                                                                                              
                                                                                                                                                                             
                     Cgo: disabled                                                                                                                                           
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "disabled")                                                                       
               Log Level: info                                                                                                                                               
                   Mlock: supported: true, enabled: true                                                                                                                     
                 Storage: etcd (HA disabled)                                                                                                                                 
                 Version: Vault v0.8.3                                                                                                                                       
             Version Sha: 6b29fb2b7f70ed538ee2b3c057335d706b6d4e36                                                                                                           
                                                                                                                                                                             
==> Vault server started! Log data will stream in below:                                                                                                                     
                                                                                                                                                                             
2017/09/26 00:57:27.917078 [WARN ] balancerWrapper: is pickfirst: false                                                                                                      
                                                                                                                                                                             
2017/09/26 00:57:27.917149 [WARN ] balancerWrapper: got update addr from Notify: [{ops-etcd1-1-sfo:2379 <nil>} {ops-etcd1-2-sfo:2379http: <nil>}]                            


2017/09/26 00:57:27.917149 [WARN ] balancerWrapper: got update addr from Notify: [{ops-etcd1-1-sfo:2379 <nil>} {ops-etcd1-2-sfo:2379http: <nil>}]                            

2017/09/26 00:57:27.917159 [WARN ] ccBalancerWrapper: new subconn: [{ops-etcd1-1-sfo:2379 0  <nil>}]                                                                         
2017/09/26 00:57:27.917168 [WARN ] ccBalancerWrapper: new subconn: [{ops-etcd1-2-sfo:2379http: 0  <nil>}]                                                                    
2017/09/26 00:57:27.917184 [WARN ] balancerWrapper: handle subconn state change: 0xc420219b90, CONNECTING                                                                    
2017/09/26 00:57:27.917188 [WARN ] balancerWrapper: handle subconn state change: 0xc420219b90, CONNECTING                                                                    
2017/09/26 00:57:27.917223 [WARN ] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp: address ops-etcd1-2-sfo:2379http:: too many colons in address"; Reconnecting to {ops-etcd1-2-sfo:2379http: 0  <nil>}
2017/09/26 00:57:27.917225 [WARN ] balancerWrapper: handle subconn state change: 0xc420219b90, TRANSIENT_FAILURE                                                             
2017/09/26 00:57:27.917232 [WARN ] balancerWrapper: handle subconn state change: 0xc420219b40, CONNECTING                                                                    
2017/09/26 00:57:27.917235 [WARN ] balancerWrapper: handle subconn state change: 0xc420219b40, CONNECTING                                                                    
2017/09/26 00:57:27.917587 [WARN ] balancerWrapper: handle subconn state change: 0xc420219b40, READY                                                                         
2017/09/26 00:57:27.917783 [WARN ] balancerWrapper: got update addr from Notify: [{ops-etcd1-1-sfo:2379 <nil>}]                                                              

2017/09/26 00:57:27.917789 [WARN ] ccBalancerWrapper: removing subconn                
2017/09/26 00:57:27.917793 [WARN ] balancerWrapper: handle subconn state change: 0xc420219b90, SHUTDOWN                                                                      
2017/09/26 00:57:27.917797 [WARN ] Failed to dial ops-etcd1-2-sfo:2379http:: context canceled; please retry.                                                                 
2017/09/26 00:57:27.922855 [WARN ] balancerWrapper: got update addr from Notify: [{192.168.1.187:2379 <nil>} {192.168.1.110:2379 <nil>} {192.168.1.167:2379 <nil>}]          

2017/09/26 00:57:27.922870 [WARN ] ccBalancerWrapper: new subconn: [{192.168.1.187:2379 0  <nil>}]                                                                           
2017/09/26 00:57:27.922880 [WARN ] ccBalancerWrapper: new subconn: [{192.168.1.110:2379 0  <nil>}]                                                                           
2017/09/26 00:57:27.922887 [WARN ] ccBalancerWrapper: new subconn: [{192.168.1.167:2379 0  <nil>}]                                                                           
2017/09/26 00:57:27.922893 [WARN ] ccBalancerWrapper: removing subconn                
2017/09/26 00:57:27.922904 [WARN ] balancerWrapper: handle subconn state change: 0xc420219b40, SHUTDOWN                                                                      
2017/09/26 00:57:27.922910 [WARN ] balancerWrapper: got update addr from Notify: [{ops-etcd1-1-sfo:2379 <nil>}]                                                              

2017/09/26 00:57:27.922917 [WARN ] ccBalancerWrapper: new subconn: [{ops-etcd1-1-sfo:2379 0  <nil>}]                                                                         
2017/09/26 00:57:27.922923 [WARN ] ccBalancerWrapper: removing subconn                
2017/09/26 00:57:27.922928 [WARN ] balancerWrapper: handle subconn state change: 0xc42035a2a0, SHUTDOWN                                                                      
2017/09/26 00:57:27.922933 [WARN ] ccBalancerWrapper: removing subconn                
2017/09/26 00:57:27.922937 [WARN ] balancerWrapper: handle subconn state change: 0xc42035a2f0, SHUTDOWN                                                                      
2017/09/26 00:57:27.922942 [WARN ] ccBalancerWrapper: removing subconn                
2017/09/26 00:57:27.922947 [WARN ] balancerWrapper: handle subconn state change: 0xc42035a340, SHUTDOWN                                                                      
2017/09/26 00:57:27.922960 [WARN ] balancerWrapper: handle subconn state change: 0xc42035a3c0, CONNECTING                                                                    
2017/09/26 00:57:27.922966 [WARN ] balancerWrapper: handle subconn state change: 0xc42035a3c0, CONNECTING                                                                    
2017/09/26 00:57:27.923122 [WARN ] Failed to dial 192.168.1.187:2379: grpc: the connection is closing; please retry.                                                         
2017/09/26 00:57:27.923140 [WARN ] Failed to dial 192.168.1.110:2379: grpc: the connection is closing; please retry.                                                         
2017/09/26 00:57:27.923149 [WARN ] Failed to dial 192.168.1.167:2379: grpc: the connection is closing; please retry.                                                         
2017/09/26 00:57:27.923302 [WARN ] balancerWrapper: handle subconn state change: 0xc42035a3c0, READY                                                                         
2017/09/26 01:06:39.459028 [INFO ] core: seal configuration missing, not initialized  
```

```
curl http://192.168.1.187:2379/version 
{
    "etcdserver":"3.2.5",
    "etcdcluster":"3.2.0"
}
```

I can see Vault responds to HTTP requests

```
$ curl http://127.0.0.1:8200/v1/sys/seal-status
{"errors":["server is not yet initialized"]}

./vault init
Unseal Key 1: XXX
Unseal Key 2: XXX
Unseal Key 3: XXX
Unseal Key 4: XXX
Unseal Key 5: XXX
Initial Root Token: e290b3af-2eef-764e-e3fd-ca3fadf9688c

Vault initialized with 5 keys and a key threshold of 3. Please
securely distribute the above keys. When the vault is re-sealed,
restarted, or stopped, you must provide at least 3 of these keys
to unseal it again.

Vault does not store the master key. Without at least 3 keys,
your vault will remain permanently sealed.

```


Vault Config

```
storage "etcd" {
  address       = "http://ops-etcd1-1-sfo:2379,http://ops-etcd1-2-sfo:2379http://ops-etcd1-3-sfo:2379"
  etcd_api      = "v3"
  path          = "vault/"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 1
}
```

**Comment by swizzlr** [comment] 2017-09-26 13:54
Has anyone found a suitable workaround to this?

**Comment by brunomcustodio** [comment] 2017-09-26 13:58
@dmyerscough I believe your errors to have a different cause — check #3362. I have those as well starting from Vault 0.8.3.

**Comment by brunomcustodio** [comment] 2017-09-26 13:59
@swizzlr setting `sync = "false"` in my configuration solved this particular problem for me (using etcd v3 and Vault v0.8.2/v0.8.3).

**Comment by raoofm** [comment] 2017-12-06 16:48
@xiang90 is this fixed in any newer versions of etcd?

**Comment by michelvocks** [comment] 2020-02-07 11:00
Hi @raoofm!

With https://github.com/hashicorp/vault/pull/8037 we upgraded the etcd API library which will be available with Vault 1.4. Would it be possible for you to manually build Vault from source and see if you experience the same issue again with the latest changes?

Cheers,
Michel

**Comment by raoofm** [comment] 2020-02-07 21:25
@michelvocks sorry, 2+ yrs is a long time, we moved on and are using s3/dynamodb/awskms and are soon going to migrate to raft. Probably if you guys need then I can help out in testing raft backend.

**Comment by raoofm** [comment] 2020-02-07 21:28
sorry, we were doing it on VMs around that time and now on k8s, I dont remember, neither do I have a set up, there is no quick way for me to replicate this

**Comment by michelvocks** [comment] 2020-02-10 09:22
Hi @raoofm!

Thanks for the quick reply. I absolutely understand that 2+ years is a long time and you might be not able to reproduce this issue now.
I will close this issue now since we are also unable to reproduce this. Feel free to open a new issue if you ever hit this issue again.

Thanks again and Cheers,
Michel

**Closed by michelvocks** 2020-02-10 09:22 UTC
Labels: bug, core/storage, version/0.7.x, waiting-for-response
