### ISSUE TITLE
Setting server log_level to debug does not show debug

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#763] opened 2015-11-07 19:02 UTC
Steps to reproduce:

1. Run:

        vault server -log-level=debug -dev

2. See `[INFO]` for startup
3. Make requests - never see any debug or trace info

**Comment by jefferai** [comment] 2015-11-09 15:08
Duplicate of #667 (there's no DEBUG output either).

**Closed by jefferai** 2015-11-09 15:08 UTC

**Comment by ashmckenzie** [comment] 2015-12-10 06:18
It does now https://github.com/ashmckenzie/vault/blob/master/command/server.go#L101 :)

**Comment by SydOps** [comment] 2016-10-08 13:46
Thanks, @ashmckenzie 
The file is at:

https://github.com/hashicorp/vault/blob/master/command/server.go#L101

Related loglevel is at: 

https://github.com/hashicorp/vault/blob/master/command/server.go#L82-L98

So  it works and get extra logs.

```
export VAULT_LOG_FORMAT=debug
vault server -dev
```

**Comment by jefferai** [comment] 2016-10-08 13:55
I think you mean LEVEL, not FORMAT.

**Comment by SydOps** [comment] 2016-10-08 13:58
@jefferai 

It is `VAULT_LOG_FORMAT` or `LOGXI_FORMAT`, not `LEVEL`

Related codes are here: 

https://github.com/hashicorp/vault/blob/master/command/server.go#L100-L103

**Comment by SydOps** [comment] 2016-10-08 14:05
Seems this is the trouble: 

https://github.com/hashicorp/vault/blob/master/command/server.go#L69

**Comment by SydOps** [comment] 2016-10-08 14:12
Ok, it works with `-log-level=trace` already.  In below output, `Log Level: trace`, I can see some 
 `TRC` or `DBG` logs.

```
$ vault server -log-level=trace -dev
==> Vault server configuration:

                 Backend: inmem
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "", tls: "disabled")
               Log Level: trace
                   Mlock: supported: true, enabled: false
                 Version: Vault v0.6.2
...

01:09:14.582894 TRC vault cluster listener addresses synthesized
   cluster_addresses: [map[IP:127.0.0.1 Port:8201 Zone:]] in:
01:09:14.590158 INF vault core: security barrier not initialized
01:09:14.590365 INF vault core: security barrier initialized shares: 1
   threshold: 1
01:09:14.590455 TRC vault core: cluster name not found/set, generating new in:
01:09:14.590603 DBG vault core: cluster name set name: vault-cluster-c90d3582
01:09:14.590620 TRC vault core: cluster ID not found, generating new in:
01:09:14.590763 DBG vault core: cluster ID set
   id: 62bc738a-93c0-8e22-39ac-7277a9335141
01:09:14.590811 INF vault core: post-unseal setup starting
01:09:14.591668 INF vault core: successfully mounted backend type: generic
   path: secret/
01:09:14.591738 INF vault core: successfully mounted backend type: cubbyhole
   path: cubbyhole/
01:09:14.592284 INF vault core: successfully mounted backend type: system
   path: sys/
```

**Comment by jefferai** [comment] 2016-10-08 14:14
@SydOps one does not set the logging level via FORMAT...

**Comment by SydOps** [comment] 2016-10-08 14:16
@jefferai Yes, you are right. The port mention in @ashmckenzie 's link is for FORMAT, not log LEVEL
