### ISSUE TITLE
Cant get vault started on Rasperry Pi4 using Arm Binary

### ISSUE THREAD

**Issue by Riprock** [hashicorp/vault#11257] opened 2021-04-01 02:50 UTC
**Describe the Bug**
Unable to start server as shown in the docs
**To Reproduce** 
Run `vault server -dev`
Just recently discovered vault and going to set it up in my lab env. When I downloaded the arm binary and extracted it to run I am encountering go panic: runtime errors. I through the issue was the binary was requiring root permission to run but the same error occurred. 

```
2021-03-31T22:46:35.097-0400 [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2021-03-31T22:46:35.097-0400 [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
2021-03-31T22:46:35.099-0400 [INFO]  core: security barrier not initialized
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11b20]

goroutine 1 [running]:
runtime/internal/atomic.goXadd64(0x74ce2ec, 0x1, 0x0, 0x1, 0x475b178)
        /goroot/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
github.com/hashicorp/vault/vendor/go.uber.org/atomic.(*Int64).Add(...)
        /gopath/src/github.com/hashicorp/vault/vendor/go.uber.org/atomic/atomic.go:94
github.com/hashicorp/vault/vault.(*AESGCMBarrier).encryptTracked(0x74ce2a0, 0x3f2b67a, 0xb, 0x1, 0x475b178, 0x7731440, 0x7a4a600, 0x72, 0x80, 0x7ce4140, ...)
        /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:1126 +0xc8
github.com/hashicorp/vault/vault.(*AESGCMBarrier).persistKeyring(0x74ce2a0, 0x475b158, 0x751b560, 0x74a4690, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:254 +0x338
github.com/hashicorp/vault/vault.(*AESGCMBarrier).Initialize(0x74ce2a0, 0x475b158, 0x751b560, 0x7ce98a0, 0x20, 0x20, 0x7ce98c0, 0x20, 0x20, 0x47219d0, ...)
        /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:182 +0x1e0
github.com/hashicorp/vault/vault.(*Core).Initialize(0x769b800, 0x475b158, 0x751b560, 0x7c5581c, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/init.go:284 +0x58c
github.com/hashicorp/vault/command.(*ServerCommand).enableDev(0x7729440, 0x769b800, 0x7876e00, 0x7729440, 0x2, 0x79ac0a0)
        /gopath/src/github.com/hashicorp/vault/command/server.go:1995 +0x118
github.com/hashicorp/vault/command.(*ServerCommand).Run(0x7729440, 0x740a0b0, 0x1, 0x2, 0x0)
        /gopath/src/github.com/hashicorp/vault/command/server.go:1671 +0x453c
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0x7cc8580, 0x7cc8580, 0x78a6b40, 0x78a6ab0)
        /gopath/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:261 +0x188
github.com/hashicorp/vault/command.RunCustom(0x740a0a8, 0x2, 0x3, 0x7706210, 0x74000e0)
        /gopath/src/github.com/hashicorp/vault/command/main.go:180 +0x674
github.com/hashicorp/vault/command.Run(...)
        /gopath/src/github.com/hashicorp/vault/command/main.go:88
main.main()
        /gopath/src/github.com/hashicorp/vault/main.go:10 +0x60
```

**Expected Behavior** 
Starting vault server

**Environment**
Vault server version - 1.7.0
Server Platform - Raspberry Pi 4
Server OS - Raspbian 10(Buster) Kernel 5.10.17

**Comment by HridoyRoy** [comment] 2021-04-01 15:50
Hi @Riprock ,

I'm going to close this as a duplicate of https://github.com/hashicorp/vault/issues/11197 

The fix has been implemented and will be available in the next point release. Thanks!

**Closed by HridoyRoy** 2021-04-01 15:50 UTC

**Comment by Riprock** [comment] 2021-04-02 03:07
No problem, Didnt realize that this was already a submitted issue
