### ISSUE TITLE
Github personal token Login don't expire 

### ISSUE THREAD

**Issue by dharavahini** [hashicorp/vault#8605] opened 2020-03-23 18:46 UTC
I am logging using Github auth method , with Cloud storage backend, and i want Github personal tokens to expire in 20 mins once login in vault and need to generate a new personal token every use after certain expiration . I have tuned the default lease to 2mins for the auth method enabled at "github/ (path) to check if its working , still no luck .

Can you please help me how do i implement this ? Thank you

Version
Vault:1.2.2

**Comment by tyrannosaurus-becks** [comment] 2020-03-23 23:05
Hi @dharavahini , thanks for posting this question.

Am I right in thinking that you're using the Github auth method to log in, and when you get a Vault token, you want it to expire in 20 minutes? If that's correct, you can configure the Vault token `token_ttl` and `token_max_ttl` [here](https://www.vaultproject.io/api/auth/github/index.html#configure-method). 

If I'm not correct about your question, can you please post steps to reproduce what you're doing? 

Thanks!

**Comment by tyrannosaurus-becks** [comment] 2020-03-30 18:22
Hi! I'm closing this for now because it doesn't seem like there's more to do here on our end. If you have further questions, please do feel free to post them in [our forum](https://discuss.hashicorp.com/c/vault/30). If for some reason you can't, though, feel free to reopen this and continue here.

Thank you! :-)

**Closed by tyrannosaurus-becks** 2020-03-30 18:22 UTC
Labels: auth/github, question
