### ISSUE TITLE
Panic when trying to use raft storage for the first time

### ISSUE THREAD

**Issue by mterron** [hashicorp/vault#7919] opened 2019-11-21 02:37 UTC
**Describe the bug**
When trying to start `vault` with the raft storage backend for the first time it panics with:
```
vault server -config config.json
panic: invalid page type: 0: 4

goroutine 1 [running]:
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Cursor).search(0xc0005d7108, 0x5ee70e8, 0x4, 0x4, 0x4)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/cursor.go:250 +0x354
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Cursor).seek(0xc0005d7108, 0x5ee70e8, 0x4, 0x4, 0x10, 0x2faeb80, 0x7f8c326d0001, 0xc000718830, 0xc0005d7128, 0x444812, ...)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/cursor.go:159 +0x7e
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Bucket).Bucket(0xc0007422b8, 0x5ee70e8, 0x4, 0x4, 0x1)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/bucket.go:105 +0xd5
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Tx).Bucket(...)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/tx.go:101
github.com/hashicorp/vault/physical/raft.(*FSM).Get.func1(0xc0007422a0, 0x3581b70, 0xc0007422a0)
        /go/src/github.com/hashicorp/vault/physical/raft/fsm.go:290 +0x95
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*DB).View(0xc000726600, 0xc0005d72a0, 0x0, 0x0)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/db.go:719 +0x90
github.com/hashicorp/vault/physical/raft.(*FSM).Get(0xc000238700, 0x3acc060, 0xc00004e0c0, 0x344e02e, 0xe, 0x0, 0x0, 0x0)
        /go/src/github.com/hashicorp/vault/physical/raft/fsm.go:288 +0x1c1
github.com/hashicorp/vault/physical/raft.(*RaftBackend).Get(0xc000734d00, 0x3acc060, 0xc00004e0c0, 0x344e02e, 0xe, 0x0, 0x0, 0x0)
        /go/src/github.com/hashicorp/vault/physical/raft/raft.go:791 +0x176
github.com/hashicorp/vault/command.CheckStorageMigration(0x3acc9a0, 0xc000734d00, 0xc000238700, 0xc000707b90, 0xc00075a000)
        /go/src/github.com/hashicorp/vault/command/server.go:2504 +0x63
github.com/hashicorp/vault/command.(*ServerCommand).storageMigrationActive(0xc000724140, 0x3acc9a0, 0xc000734d00, 0x3acc9a0)
        /go/src/github.com/hashicorp/vault/command/server.go:2471 +0x5a
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc000724140, 0xc00004c0a0, 0x2, 0x2, 0x0)
        /go/src/github.com/hashicorp/vault/command/server.go:934 +0xe5c
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc000118780, 0xc000118780, 0xc000408a20, 0xc000408920)
        /go/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x1f1
github.com/hashicorp/vault/command.RunCustom(0xc00004c090, 0x3, 0x3, 0xc0003e8230, 0xc0000ae058)
        /go/src/github.com/hashicorp/vault/command/main.go:180 +0x862
github.com/hashicorp/vault/command.Run(...)
        /go/src/github.com/hashicorp/vault/command/main.go:88
main.main()
        /go/src/github.com/hashicorp/vault/main.go:10 +0x6c
```
**To Reproduce**
```sh
# ls -l
total 0
-rwxrwxrwx    1 user   user         114 Nov 22 08:15 config.json
 # cat config.json
{
  "cluster_addr": "http://127.0.0.1:8201",
  "storage": {
    "raft": {
      "path": "/tmp/vault/",
      "node_id": "test",
    }
  }
}
# ls -lR /tmp/vault/
/tmp/vault/:
total 0
# env | grep -i vault
# vault server -config config.json
panic: invalid page type: 0: 4

goroutine 1 [running]:
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Cursor).search(0xc000659108, 0x5ee70e8, 0x4, 0x4, 0x4)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/cursor.go:250 +0x354
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Cursor).seek(0xc000659108, 0x5ee70e8, 0x4, 0x4, 0x10, 0x2faeb80, 0x7f3e6c9b0001, 0xc0006f7de0, 0xc000659128, 0x444812, ...)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/cursor.go:159 +0x7e
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Bucket).Bucket(0xc000682478, 0x5ee70e8, 0x4, 0x4, 0x1)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/bucket.go:105 +0xd5
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Tx).Bucket(...)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/tx.go:101
github.com/hashicorp/vault/physical/raft.(*FSM).Get.func1(0xc000682460, 0x3581b70, 0xc000682460)
        /go/src/github.com/hashicorp/vault/physical/raft/fsm.go:290 +0x95
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*DB).View(0xc0002ae800, 0xc0006592a0, 0x0, 0x0)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/db.go:719 +0x90
github.com/hashicorp/vault/physical/raft.(*FSM).Get(0xc000238700, 0x3acc060, 0xc0000bc010, 0x344e02e, 0xe, 0x0, 0x0, 0x0)
        /go/src/github.com/hashicorp/vault/physical/raft/fsm.go:288 +0x1c1
github.com/hashicorp/vault/physical/raft.(*RaftBackend).Get(0xc0007a41a0, 0x3acc060, 0xc0000bc010, 0x344e02e, 0xe, 0x0, 0x0, 0x0)
        /go/src/github.com/hashicorp/vault/physical/raft/raft.go:791 +0x176
github.com/hashicorp/vault/command.CheckStorageMigration(0x3acc9a0, 0xc0007a41a0, 0xc000238700, 0xc0006f7b70, 0xc00078b100)
        /go/src/github.com/hashicorp/vault/command/server.go:2504 +0x63
github.com/hashicorp/vault/command.(*ServerCommand).storageMigrationActive(0xc00072b7c0, 0x3acc9a0, 0xc0007a41a0, 0x3acc9a0)
        /go/src/github.com/hashicorp/vault/command/server.go:2471 +0x5a
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc00072b7c0, 0xc0000cc020, 0x2, 0x2, 0x0)
        /go/src/github.com/hashicorp/vault/command/server.go:934 +0xe5c
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc000110500, 0xc000110500, 0xc0000d4740, 0xc0000d4640)
        /go/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x1f1
github.com/hashicorp/vault/command.RunCustom(0xc0000cc010, 0x3, 0x3, 0xc000412230, 0xc0000ae058)
        /go/src/github.com/hashicorp/vault/command/main.go:180 +0x862
github.com/hashicorp/vault/command.Run(...)
        /go/src/github.com/hashicorp/vault/command/main.go:88
main.main()
        /go/src/github.com/hashicorp/vault/main.go:10 +0x6c
# ls -lR /tmp/vault/
/tmp/vault/:
total 32
-rw-------    1 user   user          36 Nov 22 08:16 node-id
drwxr-xr-x    1 user   user        4096 Nov 22 08:16 raft
-rw-r--r--    1 user   user       32768 Nov 22 08:16 vault.db

/tmp/vault/raft:
total 32
-rw-------    1 user   user       32768 Nov 22 08:16 raft.db
drwxr-xr-x    1 user   user        4096 Nov 22 08:16 snapshots

/tmp/vault/raft/snapshots:
total 0
#
```

**Expected behavior**
Vault starts up

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.0
* Vault CLI Version (retrieve with `vault version`): 1.3.0
* Server Operating System/Architecture: linux amd64

Vault server configuration file(s):
```json
{
  "cluster_addr": "http://127.0.0.1:8201",
  "storage": {
    "raft": {
      "path": "/tmp/vault/",
      "node_id": "test",
    }
  }
}
```

**Additional context**

**Comment by mterron** [comment] 2019-11-21 03:09
It'd be even better if you did something similar to what Consul does and generate a `node_id` if one is not provided. See https://github.com/hashicorp/consul/issues/2877

**Comment by briankassouf** [comment] 2019-11-21 17:04
Hi @mterron, 

We do indeed generate a `node_id` value if one is not configured: 
https://github.com/hashicorp/vault/blob/0b103335d5feb1d776d28bac7ca91c53c124609a/physical/raft/raft.go#L200-L213

If you look in `/tmp/data/storage/` you should see a file named `node-id`.

This panic seems like a corruption of your boltdb file. Could you provide a little more history about this node? Did it panic the first time you ran the server or has this node been around for some time? Did you ever get a chance to initialize vault? (`vault operator init ...`). Did anything outside of vault mutate the files in the `/tmp/data/storage/` directory?

Also is this the exact server config you are using? Any Vault environment variables? I ask because when i run your config vault fails with:

```
Error initializing core: missing API address, please set in configuration or via environment
```

**Comment by mterron** [comment] 2019-11-21 19:34
@briankassouf My description was misleading, I know found that even when providing `node_id` it fails the same way.  It seems that it fails to start the first time, I'll update the description.

Here are the steps to reproduce:

```sh
# ls -l
total 0
-rwxrwxrwx    1 user   user         114 Nov 22 08:15 config.json
 # cat config.json
{
  "cluster_addr": "http://127.0.0.1:8201",
  "storage": {
    "raft": {
      "path": "/tmp/vault/",
      "node_id": "test",
    }
  }
}
# ls -lR /tmp/vault/
/tmp/vault/:
total 0
# env | grep -i vault
# vault server -config config.json
panic: invalid page type: 0: 4

goroutine 1 [running]:
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Cursor).search(0xc000659108, 0x5ee70e8, 0x4, 0x4, 0x4)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/cursor.go:250 +0x354
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Cursor).seek(0xc000659108, 0x5ee70e8, 0x4, 0x4, 0x10, 0x2faeb80, 0x7f3e6c9b0001, 0xc0006f7de0, 0xc000659128, 0x444812, ...)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/cursor.go:159 +0x7e
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Bucket).Bucket(0xc000682478, 0x5ee70e8, 0x4, 0x4, 0x1)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/bucket.go:105 +0xd5
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*Tx).Bucket(...)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/tx.go:101
github.com/hashicorp/vault/physical/raft.(*FSM).Get.func1(0xc000682460, 0x3581b70, 0xc000682460)
        /go/src/github.com/hashicorp/vault/physical/raft/fsm.go:290 +0x95
github.com/hashicorp/vault/vendor/go.etcd.io/bbolt.(*DB).View(0xc0002ae800, 0xc0006592a0, 0x0, 0x0)
        /go/src/github.com/hashicorp/vault/vendor/go.etcd.io/bbolt/db.go:719 +0x90
github.com/hashicorp/vault/physical/raft.(*FSM).Get(0xc000238700, 0x3acc060, 0xc0000bc010, 0x344e02e, 0xe, 0x0, 0x0, 0x0)
        /go/src/github.com/hashicorp/vault/physical/raft/fsm.go:288 +0x1c1
github.com/hashicorp/vault/physical/raft.(*RaftBackend).Get(0xc0007a41a0, 0x3acc060, 0xc0000bc010, 0x344e02e, 0xe, 0x0, 0x0, 0x0)
        /go/src/github.com/hashicorp/vault/physical/raft/raft.go:791 +0x176
github.com/hashicorp/vault/command.CheckStorageMigration(0x3acc9a0, 0xc0007a41a0, 0xc000238700, 0xc0006f7b70, 0xc00078b100)
        /go/src/github.com/hashicorp/vault/command/server.go:2504 +0x63
github.com/hashicorp/vault/command.(*ServerCommand).storageMigrationActive(0xc00072b7c0, 0x3acc9a0, 0xc0007a41a0, 0x3acc9a0)
        /go/src/github.com/hashicorp/vault/command/server.go:2471 +0x5a
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc00072b7c0, 0xc0000cc020, 0x2, 0x2, 0x0)
        /go/src/github.com/hashicorp/vault/command/server.go:934 +0xe5c
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc000110500, 0xc000110500, 0xc0000d4740, 0xc0000d4640)
        /go/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x1f1
github.com/hashicorp/vault/command.RunCustom(0xc0000cc010, 0x3, 0x3, 0xc000412230, 0xc0000ae058)
        /go/src/github.com/hashicorp/vault/command/main.go:180 +0x862
github.com/hashicorp/vault/command.Run(...)
        /go/src/github.com/hashicorp/vault/command/main.go:88
main.main()
        /go/src/github.com/hashicorp/vault/main.go:10 +0x6c
# ls -lR /tmp/vault/
/tmp/vault/:
total 32
-rw-------    1 user   user          36 Nov 22 08:16 node-id
drwxr-xr-x    1 user   user        4096 Nov 22 08:16 raft
-rw-r--r--    1 user   user       32768 Nov 22 08:16 vault.db

/tmp/vault/raft:
total 32
-rw-------    1 user   user       32768 Nov 22 08:16 raft.db
drwxr-xr-x    1 user   user        4096 Nov 22 08:16 snapshots

/tmp/vault/raft/snapshots:
total 0
#
```

Now the next time you run it, it does fail gracefully with
```sh
# vault server -config config.json
Error initializing core: missing API address, please set in configuration or via environment
```

**Comment by briankassouf** [comment] 2019-12-06 19:33
@mterron Thanks for the specific steps! Unfortunately I've still been unable to reproduce this panic:

```
brian@ubuntu:~$ mkdir /tmp/vault/
brian@ubuntu:~$ cat config.hcl 
{
  "cluster_addr": "http://127.0.0.1:8201",
  "storage": {
    "raft": {
      "path": "/tmp/vault/",
      "node_id": "test",
    }
  }
}
brian@ubuntu:~$ ./vault server -config config.hcl
Error initializing core: missing API address, please set in configuration or via environment
brian@ubuntu:~$ ls -lah /tmp/vault/
total 36K
drwxr-xr-x  3 brian brian 4.0K Dec  6 11:31 .
drwxrwxrwt 20 root  root  4.0K Dec  6 11:31 ..
drwxr-xr-x  3 brian brian 4.0K Dec  6 11:31 raft
-rw-r--r--  1 brian brian  32K Dec  6 11:31 vault.db
```

 Is there any more information you're able to share that may help to track it down? What OS are you running, what filesystem, are you using SSDs/spinning disks/EBS volumes/etc?

Thanks for helping to track this down!

**Comment by mterron** [comment] 2019-12-08 20:37
I'm running on Docker for Windows, SSD. Nothing too fancy, can try to reproduce on bare metal linux if that helps.

**Comment by briankassouf** [comment] 2019-12-09 23:13
Ah okay, may be a WSL issue. What version of WSL are you running? According to this comment it may be fixed in 18912.

https://github.com/etcd-io/bbolt/issues/144#issuecomment-500552510

**Comment by briankassouf** [comment] 2020-01-16 18:40
Going to close this for now, but please let us know if a WSL update doesn't fix this issue.

**Closed by briankassouf** 2020-01-16 18:40 UTC
Labels: storage/raft, waiting-for-response
