### ISSUE TITLE
Vault Cassandra Config error

### ISSUE THREAD

**Issue by heyitsaakash** [hashicorp/vault#3374] opened 2017-09-25 17:34 UTC
for cassandra 3.11 getting error
Hi,
When trying to mount and connect cassandra for secrets i am getting error below - 

vault write database/config/cassandra plugin_name=cassandra-database-plugin  allowed_roles="readonly" hosts=localhost username=cassandra password=cassandra 
Error writing data to database/config/cassandra: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/cassandra
Code: 400. Errors:

* error creating database object: error verifying connection: error creating session: gocql: unable to create session: control: unable to connect to initial hosts: dial tcp [::1]:9042: getsockopt: connection refused

**Comment by jefferai** [comment] 2017-09-25 17:46
Duplicate of #3370

**Closed by jefferai** 2017-09-25 17:46 UTC

**Comment by ror6ax** [comment] 2017-09-26 10:36
@heyitsaakash - how did you run into this?

**Comment by heyitsaakash** [comment] 2017-09-26 15:54
I ran the following commands
1 . vault mount database
2. vault write database/config/cassandra plugin_name=cassandra-database-plugin  allowed_roles="readonly" hosts=localhost username=cassandra password=cassandra

at backend cassandra is runnning. I am running vault in dev mode. I have not made any other configuration changes so far such as setting storage backed etc.

**Comment by RohanKurane** [comment] 2018-03-03 07:14
@heyitsaakash were you able to resolve this ?
