### ISSUE TITLE
Vault login from CLI is working but through UI failing due to token expiry

### ISSUE THREAD

**Issue by infa-svijayak** [hashicorp/vault#6486] opened 2019-03-27 17:38 UTC
Hi Team,
I have a peculiar issue. I was trying to login to vault UI using one of my tokens and I get the following error
Error
Your auth token expired at 2019-03-26 22:12:59.
But when I try to login using cli I am able to login successfully. The token was expired so we renewed the token and set the ttl to 1 year. Any help on this please.

**Comment by infa-msethi** [comment] 2019-03-27 17:43
+1

**Comment by jefferai** [comment] 2019-03-27 17:45
How are you logging in using CLI?

**Comment by infa-msethi** [comment] 2019-03-27 17:47
I'm using "vault login <token>" to log in and perform a different operation.

**Comment by infa-svijayak** [comment] 2019-03-27 17:47
export VAULT_ADDR=<vault url>
INM1VHATKHTD6:~ svijayak$ vault login
Token (will be hidden):<vault token>
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

**Comment by infa-svijayak** [comment] 2019-03-27 18:13
Further to add, the creation TTL of the token when created was 768h and later we increased the TTL to 8760 h.

**Comment by infa-samperay** [comment] 2019-03-28 04:45
+1

**Comment by ncabatoff** [comment] 2019-03-29 14:54
Can you run `vault token lookup` and confirm that the `id` field matches what you're logging in to the UI with?

**Comment by infa-svijayak** [comment] 2019-04-01 06:31
Yes both are same.

**Comment by aphorise** [comment] 2022-09-01 19:35
Closing as issue is very likely related to clashes with environment variables `VAULT_TOKEN` vs file `~/vault_token` post login (as per the warning message after `vault login` is performed). There's also been no reproduction or follow up since it was raised.

**Closed by aphorise** 2022-09-01 19:35 UTC
Labels: ui, bug, core/token

**Comment by mcfriend99** [comment] 2024-03-07 14:00
I'm having the same issue
