### ISSUE TITLE
Sending multiple HUP signals to Vault agent causes it to crash

### ISSUE THREAD

**Issue by denniswloo** [hashicorp/vault#17873] opened 2022-11-09 23:17 UTC
**Environment:**

* Vault Version:*
*  1.11.3
* Operating System/Architecture:
Linux amd64

**Vault Config File:**

```hcl
storage "raft" {
  path = "/vault/data"
  node_id = "node1"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 0
  tls_cert_file = "/vault/config/tls/tls.crt"
  tls_key_file = "/vault/config/tls/tls.key"
}

api_addr = "https://127.0.0.1:8200"
cluster_addr = "https://127.0.0.1:8201"

disable_mlock = true
#ui = true
max_lease_ttl = "120h"
default_lease_ttl = "120h"

**Vault Agent config **
auto_auth {
  method "approle"{
    mount_path = "auth/agent"

    config = {
      role_id_file_path = "/vault/vault-agent/config/vault-agent-role-id"
      secret_id_file_path = "/tmp/vault-agent-secret-id"
      remove_secret_id_file_after_reading = false
    }
  }

  sink "file" {
    config = { path = "/start/token"
      mode = 0644
    }
  }
}

cache {
  use_auto_auth_token = true
}

listener "tcp" {
  address = "127.0.0.1:8400"
  tls_disable = 0
  tls_cert_file = "/vault/config/tls/tls.crt"
  tls_key_file = "/vault/config/tls/tls.key"
}
** Vault agent config: **
auto_auth {
  method "approle"{
    mount_path = "auth/agent"

    config = {
      role_id_file_path = "/vault/vault-agent/config/vault-agent-role-id"
      secret_id_file_path = "/tmp/vault-agent-secret-id"
      remove_secret_id_file_after_reading = false
    }
  }

  sink "file" {
    config = { path = "/start/token"
      mode = 0644
    }
  }
}

cache {
  use_auto_auth_token = true
}
listener "tcp" {
  address = "127.0.0.1:8400"
  tls_disable = 0
  tls_cert_file = "/vault/config/tls/tls.crt"
  tls_key_file = "/vault/config/tls/tls.key"
}

vault {
  address = "https://127.0.0.1:8200"
}


**Startup Log Output:**
n/a

```text
# Paste your log output here
```

**Expected Behavior:**
Vault agent restarts

**Actual Behavior:**
Vault agent crashes

**Steps to Reproduce:**

1.  Start up the vault server using https
2. Start up the vault agent using https
3. Let the vault agent finish basic processing like rendering secrets
4. Send HUP signal using "pkill -SIGHUP vault"
5. The vault server is ok but running step 4 more than once cause the vault agent to crash
**Important Factoids:**

Every thing is local vault agent and vault server are on one container.
**References:**

**Comment by ccapurso** [comment] 2022-11-11 18:33
Hi @denniswloo, thank you for your feedback! What you are likely running into is the default action for [SIGHUP](https://en.wikipedia.org/wiki/SIGHUP) on POSIX-compliant systems:

> SIGHUP can be [handled](https://en.wikipedia.org/wiki/Signal_(IPC)#Handling_signals). That is, [programmers](https://en.wikipedia.org/wiki/Programmer) can define the action they want to occur upon receiving a SIGHUP, such as calling a [function](https://en.wikipedia.org/wiki/Subroutine), ignoring it, or restoring the default action.
>
> The default action on [POSIX](https://en.wikipedia.org/wiki/POSIX)-compliant systems is an abnormal termination.

Vault Agent does not currently support SIGHUP. There is an existing [feature request](https://github.com/hashicorp/vault/issues/8216) for it, however, and will be something that we will look into in the future. With that said I'll close this as a duplicate.

Duplicate of https://github.com/hashicorp/vault/issues/8216

**Closed by ccapurso** 2022-11-11 18:33 UTC
Labels: agent
