### ISSUE TITLE
Provide ability for vault to clean / parse logs

### ISSUE THREAD

**Issue by queglay** [hashicorp/vault#10506] opened 2020-12-06 03:22 UTC
**Is your feature request related to a problem? Please describe.**
In CI workflows, text output can sometimes accidentally contain secrets. 

**Describe the solution you'd like**
It would be excellent if we could send any text through a vault function to get it to redact any sensitive data (even in past versions of all secrets optionally).  CI workflows could use this to redact their own log output through stdout or stderr.

**Describe alternatives you've considered**
None

**Explain any additional use-cases**
Gitlab, Github Circle CI could potentially benefit.

**Comment by swayne275** [comment] 2020-12-10 01:07
Could you provide steps to reproduce leaking secrets in the logs?

**Comment by queglay** [comment] 2020-12-12 00:38
Sorry if I wasn't clear there.  No vault isn't leaking secrets... I meant its just common for how people might automate anything for them to produce logs in their CI workflows that may show secrets being used.

Since vault is in the unique position of knowing them all, its ideal for it to be provide some service that cleans any output we send to it.  It would operate as a redaction service.

So thats the idea - Wouldn't it be cool if we could route any output or stdout / stderr through to vault and get it to redact output for us?

**Comment by ncabatoff** [comment] 2021-07-20 17:10
Hi @queglay,

Thanks for the feature suggestion.  There is a sort-of-related feature in Enterprise: https://www.vaultproject.io/docs/secrets/transform.  Transform, however, requires that you tell Vault how to identify the secrets in the input text.  As I understand it, you'd like this redaction API to just take raw text, pick out all the secrets within that we recognize as stored secrets, and replace them with placeholders like '***'. 

I understand why you would want something like this, I agree that it's a cool feature..  It's awesome that CircleCI already does this for secrets it manages.  The main impediment I see is that we'd want it to reliable and comprehensive: if I'm going to trust Vault to hide these secrets, it better not miss any.  To make it perform adequately, that would mean that every time a secret is written to Vault storage, we'd also have to update an index somewhere to record the secret value, such that Vault could lookup secrets by value to see whether any given input string is a stored secret.  Updating that index means another write, so now every write of a secret is twice as expensive.  Same goes for deleting a secret - now we have to delete the index value too.

Since write performance is a perennial concern, and independent of that, implementing this rarely-asked-for feature would probably be quite a bit of work, I think it is unlikely to happen.  I'm open to revisiting this if you have ideas to address my concerns, and please don't be shy to reach out if I'm missing something.  For now I will close the issue.

**Closed by ncabatoff** 2021-07-20 17:10 UTC
Labels: core/log, feature-request
