### ISSUE TITLE
identity propagation in ssh secrets engine

### ISSUE THREAD

**Issue by fredrikhgrelland** [hashicorp/vault#7547] opened 2019-10-02 13:57 UTC
**Is your feature request related to a problem? Please describe.**
At the moment it is not possible to enforce identity mapping from vault to ssh login using the ssh secrets engine for CA authentication. When creating a ssh signing role; setting allowed_users to '*' enables anyone attached to this role to impersonate any os user.

**Describe the solution you'd like**
Extending the allowed_users field with a new special character '?'
In path_sign.go we test the valid_principals filed against the authenticated users name.
The resulting signed public key will contain only the authenticated users name. 

**Describe alternatives you've considered**
In order to enforce vault user to os user mapping we must create one role pr user. This does not scale and requires puppet or the like to update the trusts in each and every server.

**Additional context**
Implementation in PR relies on parsing the request DisplayName, as I could not find any way of accessing Identity alias or the like from this context.

**Comment by fredrikhgrelland** [comment] 2019-10-02 14:07
#7548

**Comment by jefferai** [comment] 2019-10-02 14:34
More or less a duplicate of #6056.

**Comment by michelvocks** [comment] 2019-11-05 12:39
Closing this in favor of #6056

**Closed by michelvocks** 2019-11-05 12:39 UTC
