### ISSUE TITLE
Getting Permission Denied for Userpass Token lookup

### ISSUE THREAD

**Issue by sing011** [hashicorp/vault#14275] opened 2022-02-25 15:56 UTC
Hi,

Token lookup for the root token works perfectly fine. I want to write a script to renew a token related to a userpass user. Before I could run anything, I tried to lookup the user token. But I keep getting permission denied. The curl works fine if I put the root token instead.

curl --header "X-Vault-Token: <token>" --request POST https://vault-dev.smecloudops.com/v1/auth/token/lookup

>     --header "X-Vault-Token: <token>" \
>     --request POST \
>     --data @payload.json \
>     https://vault-dev.smecloudops.com/v1/auth/token/lookup
Warning: Couldn't read data from file "payload.json", this makes an empty
Warning: POST.
{"errors":["1 error occurred:\n\t* permission denied\n\n"]}

Am I missing anything here? Please help!

**Comment by sing011** [comment] 2022-02-25 15:57
And if possible, is there a script I can refer to which already has code for rotating a userpass token?

**Comment by hsimon-hashicorp** [comment] 2022-02-25 18:09
Hi! As this looks like a question and not a bug report, we ask that these sorts of posts be made in our [Discuss forum](https://discuss.hashicorp.com/c/vault/30). As a note, I think that there may be a problem with the pathing of your file or its permissions. I'm going to go ahead and close this issue now, but if you have a bug report or enhancement request, please do feel free to file that here. :)

**Closed by hsimon-hashicorp** 2022-02-25 18:09 UTC
