### ISSUE TITLE
list accounts in userpass

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/vault#911] opened 2016-01-07 16:34 UTC
It would be helpful for us to list the accounts in the `userpass` auth backend and their associated policies. This will enable our Sec Ops/Compliance team to audit who has access to what in Vault. While not as important, if would be nice if it also worked for the `app-id` auth backend as well.

**Comment by jefferai** [comment] 2016-01-07 16:59
Mostly a duplicate of #111 but I'll leave it as separate to track specific work.

**Comment by mtougeron** [comment] 2016-01-07 17:02
@jefferai I saw that issue but I'm not a fan of listing all secrets so I thought it deserved its own ticket. :)

**Comment by jefferai** [comment] 2016-01-07 18:05
@mtougeron Unfortunately that issue has become somewhat of a meta-issue where everyone has tacked on the various items they want to be able to list, so it's kind of a "list all the things" ticket at this point :-)  But that's why I left this open.

As a result, I'm not sure that issue will ever be closed, although some list support is going to start coming starting with 0.5.

**Comment by tomalok** [comment] 2016-04-06 23:31
+1 for being able to list what's in `auth/app-id/map/app-id` and `auth/app-id/map/user-id`
it'd also be useful to see some attached metadata to individual entries -- creation date, ttl, app-id -> policies, user-id -> app-id's

**Closed** 2016-04-19 23:31 UTC
Labels: auth/username-password, enhancement
