### ISSUE TITLE
v1/sys/health?standbyok=false acts as if set to true

### ISSUE THREAD

**Issue by thomasmitchell** [hashicorp/vault#7323] opened 2019-08-15 19:11 UTC
**Describe the bug**
/v1/sys/health endpoint does not check if the standbyok (and perfstandbyok) parameter is set to true - it merely checks if it is present. This can cause the unexpected case of `?standbyok=false` leading to the behavior as if it was set to true. The assumption that explicitly setting it to "false" would result in, effectively, a more API-change-safe no-op taken from the API docs saying the default is `bool: false` 

**To Reproduce**
1. Run `curl -kv $VAULT_ADDR/v1/sys/health?standbyok=false` against a standby node
2. See that it returns status code 200 (even though the JSON body payload returns that the node is a standby)
**Expected behavior**

I expected setting the boolean query parameter to false to result in the behavior reflecting it be false, not true.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.2
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: ubuntu/amd64

Vault server configuration file(s):

I don't have access to the configuration file

**Additional context**

https://github.com/hashicorp/vault/blob/233ca02dd967776d54af1c683298fa7ece746ee8/http/sys_health.go#L77

This is where the server is relying on the map-presence variable to determine whether standbyok is true. It should probably check for presence _and_ that the value is explicitly not "false"

**Comment by jefferai** [comment] 2019-08-19 17:36
I believe this is a duplicate of #7241, can you confirm?

**Comment by ncabatoff** [comment] 2019-08-19 17:45
> I believe this is a duplicate of #7241, can you confirm?

No, #7241 is about how we handle `standbyok` and `perfstandbyok` when they are set to `true`.  This issue is about how we parse them, i.e. they should be treated as bools instead of disregarding the value of the param and always treating them as `true` when present.

**Closed** 2019-10-28 23:55 UTC
