### ISSUE TITLE
Cleanly release lock on Vault shutdown

### ISSUE THREAD

**Issue by nbrownus** [hashicorp/vault#308] opened 2015-06-03 00:23 UTC
I am running a 5 node `consul` and `vault` cluster. If I `vault seal` on the current leader I notice an election happens immediately (with `v0.1.3-dev` only). If I kill the leader process all the standby nodes just sit around for about 30 seconds before they even realize the leader is gone. Takes another few seconds to elect a new leader after that.

I am doing a `vault read secret/test` in a tight loop during this time as well, hoping it would trigger an election. I get a lot of `connection refused` errors while the cluster thinks the dead leader is alive. After the cluster realizes the leader is dead I get a lot of `503` http response codes until a new leader is elected.

I am using version `Vault v0.1.3-dev (3ebde4b26820ffcb27cf797cb8424d737a5cab3f+CHANGES)`, the changes are to the build script.

This also happens in `v0.1.2`

**Comment by armon** [comment] 2015-06-03 08:51
@nbrownus This is largely by design. The locks Vault takes have a 15 second TTL, and a 15 second lock-delay period. This means in the worse case, it takes a full 30 seconds to fall over to the next instance. These are purposely conservatively set to strike a balance of failure recovery time versus overhead and potential safety concerns.

**Comment by nbrownus** [comment] 2015-06-03 16:52
In the happy case, `vault` exits cleanly, wouldn't it be better for the leader to release its lock at that time? I imagine this is what `seal` does on a leader since it forces an election to occur rather quickly.

**Comment by armon** [comment] 2015-06-03 21:39
@nbrownus Yeah totally, I think that is simple enough! Marking as enhancement!

**Closed** 2015-06-18 01:24 UTC
Labels: enhancement
