### ISSUE TITLE
Vault unseal takes long time

### ISSUE THREAD

**Issue by zivgabel** [hashicorp/vault#2182] opened 2016-12-14 15:04 UTC
Hi,
I have vault istalled with mysql backend
We are using app-id authentication 
It seems that we did not revoke any token since the beggining of the installation
Now I'm facing an issue where it takes a lot of time to load vault and for times it even hangs.
When trying to revoke the tokens using the following command:
vault token-revoke -mode=path auth/app-id

My log is now full of lines like the following
[ERROR] expire: failed to revoke lease: lease_id=auth/app-id/login/<token> 655 error=failed to revoke token: cannot revoke blank token

and while the above command was running the vault server crashed.

I did not find anywhere a manual way to remove tokens from a MySQL backend.

Please assists

**Comment by vishalnayak** [comment] 2016-12-14 15:34
@zivgabel Which version of Vault are you using? 

> It seems that we did not revoke any token since the beggining of the installation

It is possible that the token might have hit its TTL and got expired.

> Now I'm facing an issue where it takes a lot of time to load vault and for times it even hangs.

Can you provide logs for this?

Is this a recent setup of Vault and is this issue reproducible?

**Comment by zivgabel** [comment] 2016-12-14 16:02
The tokens did not hit the ttls as it has unlimited lifetime.
Which logs do you need ?
I'm running the token-revoke command again and the log has countless lines like the one above.
It's not a recent setup, I have this server running for almost one year.

I believe that the change in (our application's) setup that triggered it was that we started to use the pki mount to generate client side certificates.
For each request our application generates a new token, and there are lot's of requests.

I've used the mount-tune command to set a 10 minutes expiry for new app-id logins, but this will affect only new requests, not the old ones.

**Comment by vishalnayak** [comment] 2016-12-14 20:03
@zivgabel 

> Which logs do you need?

The server logs from the stdout.

Which version of Vault are you using? If it is the latest version, then what matters is that which version of Vault did you upgrade it from, and were the upgrade instructions followed during the process? It is fairly possible that this issue could be resolved in the latest version. It is also possible that the physical backend is corrupted in an irrecoverable manner.

It is hard to pin point the problem with the current details.

**Comment by jefferai** [comment] 2016-12-15 17:26
Hi @zivgabel,

I dug into this some more and I have good news and bad news. 

The good news is that I believe that this is actually the result of a quite old bug that caused tokens to sometimes be revoked but missed the lease entries. As a result when the lease entries then try to revoke the token again, it doesn't exist. So, updating to newer versions of Vault (probably 0.6+) would fix that. And generally speaking 0.6.3 is in a quite solid place and recommended.

The bad news is that fixing the problem on your end will require some log parsing. What you want to do is feed those lease IDs to https://www.vaultproject.io/docs/http/sys-revoke-force.html (which can operate on prefixes but a full lease ID is fine too). This should remove the leases which will cause them to not be loaded every time you start up, which is what is causing the slowdown.

I believe once you upgrade and then remove these, the problem shouldn't reoccur.

**Comment by jefferai** [comment] 2017-01-24 19:50
Closing due to lack of response.

**Closed by jefferai** 2017-01-24 19:50 UTC

**Comment by zivgabel** [comment] 2017-01-25 08:48
Sorry for the late response.
I just did the log parsing part, I will update as soon as I need to restart the server if it helped reducing the time it takes to load.

**Comment by nbrownus** [comment] 2017-02-21 20:56
Getting bit by this now in a test cluster but `vault` effectively DOS's the machine after unseal while trying to revoke all these leases. To get around the DOSing I built a custom version of `vault` that disables the actual revocation in [`ExpirationManager.Restore`](https://github.com/hashicorp/vault/blob/v0.6.5/vault/expiration.go#L160). But calling `/sys/revoke-force/<path>` didn't actually do anything.

Manually purging from `consul` worked.

```
curl -XDELETE "http://127.0.0.1:8500/v1/kv/vault/sys/expire/id/<PATH FROM LOGS>
```

I haven't really though about the edge cases but if a lease is invalid/malformed/etc it should just be deleted on startup.
