### ISSUE TITLE
thanks @cipherboy

### ISSUE THREAD

**Issue by vmhuy99** [hashicorp/vault#27383] opened 2024-06-06 15:47 UTC
thanks @cipherboy 

A workaround switching to ed25519 key algorithm is working:

```bash
$ ssh-keygen -t ed25519

$ vault write -field=signed_key ssh/sign/test public_key=@$HOME/.ssh/id_ed25519.pub valid_principals=jdoe | ssh-keygen -L -f -
(stdin):1:
Type: **ssh-ed25519-cert-v01@openssh.com** user certificate
Public key: ED25519-CERT SHA256:XhZL3wGE6JiWczuSsX5M2jwaYrlG8NEhuCPITuhUp5Y
Signing CA: RSA SHA256:sPKzOUJwvkR3aCFf2oCyHnc+JoMtFcow2UxcEz+cXo4 (using rsa-sha2-256)
Key ID: "group=test  pubkey_fp=5e164bdf0184e89896733b92b17e4cda3c1a62b946f0d121b823c84ee854a796
Serial: 11871586717846079993
Valid: from 2022-05-20T13:46:21 to 2022-05-21T01:46:51
Principals:
    jdoe
Critical Options: (none)
Extensions:
    permit-port-forwarding
    permit-pty
```

But with new OpenSSH changes, this issue is likely to affect many users.

_Originally posted by @prbinu in https://github.com/hashicorp/vault/issues/15488#issuecomment-1133382545_

**Comment by hsimon-hashicorp** [comment] 2024-06-11 21:43
Closing as a duplicate of #15488

**Closed by hsimon-hashicorp** 2024-06-11 21:43 UTC
Labels: cryptosec
