### ISSUE TITLE
LDAP: server selected unsupported protocol version 301

### ISSUE THREAD

**Issue by memotype** [hashicorp/vault#3199] opened 2017-08-17 16:24 UTC
**Environment:**

* Vault Version: Vault v0.7.3 ('0b20ae0b9b7a748d607082b1add3663a28e31b68')
* Operating System/Architecture:
```
ubuntu@svs-vault:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
ubuntu@svs-vault:~$ uname -a
Linux svs-vault 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Vault Config File:**

Running in -dev mode with no custom config file. Tried several LDAP auth configurations:

(actual hostnames and domains redacted)

```
vault write auth/ldap/config url=ldaps://<ldapserver>.com:636 userdn=ou=ccoentities,o=<ldapdomain>.com userattr=uid groupfilter='(|(memberOf=cn=svs-cloud-admins,ou=groups,o=<ldapdomain>.com)(memberOf=cn=svs-cloud-users,ou=groups,o=<ldapdomain>.com))' groupdn=ou=groups,o=<ldapdomain>.com groupattr=cn certificate=@/home/ubuntu/ad-ca.cer starttls=false

**Startup Log Output:**
<!-- Logs from vault's output on startup, if available. -->
```
ubuntu@svs-vault:~$ vault server -dev
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: inmem
                 Version: Vault v0.7.3
             Version Sha: 0b20ae0b9b7a748d607082b1add3663a28e31b68

==> WARNING: Dev mode is enabled!

In this mode, Vault is completely in-memory and unsealed.
Vault is configured to only have a single unseal key. The root
token has already been authenticated with the CLI, so you can
immediately begin using the Vault CLI.

The only step you need to take is to set the following
environment variables:

    export VAULT_ADDR='http://127.0.0.1:8200'

The unseal key and root token are reproduced below in case you
want to seal/unseal the Vault or play with authentication.

Unseal Key: epepOh3dodRHq68E0uFNeI16RU2fdVCSvEEWonE6xZ4=
Root Token: 4a4b0a43-9bee-ecbf-ca85-c5c7ac272490

==> Vault server started! Log data will stream in below:

2017/08/16 18:41:24.837417 [INFO ] core: security barrier not initialized
2017/08/16 18:41:24.837552 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/08/16 18:41:24.837708 [INFO ] core: post-unseal setup starting
2017/08/16 18:41:24.849696 [INFO ] core: loaded wrapping token key
2017/08/16 18:41:24.850628 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/08/16 18:41:24.850655 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/08/16 18:41:24.850785 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/08/16 18:41:24.852982 [INFO ] expiration: restoring leases
2017/08/16 18:41:24.853061 [INFO ] rollback: starting rollback manager
2017/08/16 18:41:24.854731 [INFO ] core: post-unseal setup complete
2017/08/16 18:41:24.854873 [INFO ] core: root token generated
2017/08/16 18:41:24.854877 [INFO ] core: pre-seal teardown starting
2017/08/16 18:41:24.854879 [INFO ] core: cluster listeners not running
2017/08/16 18:41:24.854888 [INFO ] rollback: stopping rollback manager
2017/08/16 18:41:24.854950 [INFO ] core: pre-seal teardown complete
2017/08/16 18:41:24.855020 [INFO ] core: vault is unsealed
2017/08/16 18:41:24.855035 [INFO ] core: post-unseal setup starting
2017/08/16 18:41:24.855091 [INFO ] core: loaded wrapping token key
2017/08/16 18:41:24.855207 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/08/16 18:41:24.855278 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/08/16 18:41:24.855286 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/08/16 18:41:24.855707 [INFO ] expiration: restoring leases
2017/08/16 18:41:24.855731 [INFO ] rollback: starting rollback manager
2017/08/16 18:41:24.855826 [INFO ] core: post-unseal setup complete
```

**Expected Behavior:**
<!-- What should have happened? -->
Successful authentication

**Actual Behavior:**
<!-- What actually happened? -->
(redacted actual hostnames)

```
ubuntu@svs-vault:~$ vault auth -method=ldap username=isfreema
Password (will be hidden):
Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/ldap/login/isfreema
Code: 400. Errors:

* 1 error occurred:

* error connecting to host "ldaps://<ldapserver>.com:636": LDAP Result Code 200 "Network Error": tls: server selected unsupported protocol version 301
```

**Steps to Reproduce:**
<!-- List the steps required to reproduce the issue. -->

* Start dev server
* enable ldap auth
* configure with above write command
* attempt to authenticate with "vault auth -method=ldap"

**Important Factoids:**
<!-- Describe any atypical environment setup, if any. -->

**References:**
<!-- Link to any references, such as GitHub issues or pull requests. -->

**Comment by joelthompson** [comment] 2017-08-17 16:32
Hey @memotype -- it looks like your LDAP server is trying to use TLS1.0, while by default, Vault requires TLS 1.2. TLS 1.0 is largely being deprecated in the security community, so you should contact whoever administers your LDAP server and strongly encourage them to support TLS 1.2.

If you can't do that, then the LDAP auth backend allows you to specify an allowed minimum TLS version. See the [`/auth/ldap/config` docs](https://www.vaultproject.io/api/auth/ldap/index.html); specifically, you'll want to set `tls_min_version` to `tls10`.

Again, I want to emphasize that this should be the option of last resort; you'll be much more secure if your LDAP server is upgraded to support TLS 1.2.

Hope this helps!

**Comment by jefferai** [comment] 2017-08-21 15:27
In agreement with Joel about the cause here; closing.

**Closed by jefferai** 2017-08-21 15:27 UTC
