### ISSUE TITLE
How to backup and restore Vault on single node 

### ISSUE THREAD

**Issue by talktosaswat** [hashicorp/vault#3073] opened 2017-07-27 18:35 UTC
I am using Vault as single node installation with Vault and Consul running on a single VM. How can I take real time Vault backup for avoiding any disaster. Looking for some inbuilt solution from opensource Vault product or other open source tool which takes Consult backup if there will be any change on credentials and will able to restore to Vault server in case disaster.

**Comment by viralpoetry** [comment] 2017-07-28 08:26
@talktosaswat this kind of questions are better suited for the mailing list.
You can use unofficial backup tools like:  
https://github.com/adamdecaf/vault-backend-migrator

which will crawl Vault paths and store it in the json file (plaintext!). Or simply use another backend.

**Comment by chrishoffman** [comment] 2017-07-28 15:20
The mailing list is probably the best place to answer this question [link](https://groups.google.com/forum/#!forum/vault-tool).  This questions ends up being highly dependent on your storage backend and recovery requirements.  

Duplicate of #2743

**Closed by chrishoffman** 2017-07-28 15:20 UTC
