### ISSUE TITLE
Vault inject on k8s env variables without source

### ISSUE THREAD

**Issue by sharmajee1** [hashicorp/vault#8267] opened 2020-01-30 19:56 UTC
Hi Gurus,

I am recently trying inject hashicrop vault in k8s. and its perfectly working using 
Secrets via Annotations. 
currently those entries stored in file system /vault/secrets/foo

What I am looking for:
Is it possible to inject vault in k8s env variables WITHOUT SOURCING the  /vault/secrets/foo file.

env:
   - name: USERNAME
     value: <something>:vault/secrets/foo#username

Thanks in advanced

**Comment by catsby** [comment] 2020-01-30 20:30
Hello there - 

Please post questions on the discussion forum (https://discuss.hashicorp.com/c/vault) rather than in GitHub issues.

The discussion forum gets a _lot_ more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the forum.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

I'm going to close this issue now.

Thanks!

**Closed by catsby** 2020-01-30 20:30 UTC
