### ISSUE TITLE
Missing telemetry core.unsealed metrics on standby nodes

### ISSUE THREAD

**Issue by exo-cedric** [hashicorp/vault#10015] opened 2020-09-22 15:13 UTC
**Describe the bug**

This is a follow-up on slightly different #9771 

**To Reproduce**
1. Setup a Raft cluster
2. Query metrics on a _stand-by_ (Follower) node
3. `vault.core.unsealed` metric is missing

**Expected behavior**
`vault.core.unsealed` metric should be present like on active (Leader) node:

```
# wget -qO- http://127.0.0.1:18200/v1/sys/metrics | jq '.Gauges[] | select(.Name=="vault.core.unsealed")'
{
  "Name": "vault.core.unsealed",
  "Value": 1,
}
```

The lack of `core.unsealed` metrics for a HA standing-by node is problematic since it prevents to monitor the health of all HA nodes (and make sure HA is actually still available).

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.0
* Vault CLI Version (retrieve with `vault version`): 1.5.0
* Server Operating System/Architecture: Linux x86_64

Vault server configuration file(s):

N/A

**Additional context**

Quickly going through `core.go`, `core_metrics.go` and `ha.go`, it _seems_ to me that `emitMetrics` (which spawns the `metrics
Loop` to refresh the `core.unsealed` metric) is only called via `postUnseal`, which is _not_ called for HA standing-by HA node (in `core.go`); only the Leader/Active node actually calls `postUnseal` (in `ha.go`).

**Comment by alwaysastudent** [comment] 2021-05-08 00:34
Facing the same issue on 1.6.x versions as well. Is this something that will be fixed?

**Comment by KawaiDesu** [comment] 2021-10-01 15:41
Hello! Any update on this? This is blocking us from abandoning vault_exporter.

**Comment by hsimon-hashicorp** [comment] 2021-12-15 20:25
Wanting to chime in that we're still working on a resolution for this. Thanks for your patience!

**Comment by Bowser1704** [comment] 2022-04-14 03:16
@hsimon-hashicorp Hi, have any updates on this？ It's important to emit metrics on the standby node in HA mode.

**Comment by geekofalltrades** [comment] 2022-09-26 16:29
We just upgraded to Vault 1.11.3. We saw all Vault replicas export `vault_core_unsealed` for `12h` (the value of our `prometheus_retention_time`), but without the `cluster` label. The leader also exported one with the `cluster` label. After 12 hours, the unlabeled ones disappeared.

I'm going to guess they just hadn't finished determining they were a cluster yet, and as soon as they went into HA standby mode, the standbys started hitting this bug and not reporting the metric.

**Comment by laugmanuel** [comment] 2022-12-09 13:12
I see the same behaviour with Vault 1.12.1 and missing vault_core_active metric after some time.
We've used the absence of that metric to determine missing leaders and got alerted by prometheus many times in the past.

**Comment by claviola** [comment] 2023-01-24 16:41
@hsimon-hashicorp any updates about this issue? the lack of reliable core metrics makes it very difficult to properly monitor vault using prometheus.

**Comment by none0nfg** [comment] 2023-02-08 01:02
also fased this problem, also needs resolution

**Comment by konstantin-921** [comment] 2023-02-09 11:51
+1

**Comment by cadmuxe** [comment] 2023-05-18 23:12
Hello, Any update? This really makes the unsealed metric useless.  Thanks.

**Comment by p-k-sharma** [comment] 2023-10-27 09:00
Any update on this? Its been more than 3 years... The issue is still open

**Comment by ameflorenti** [comment] 2023-12-05 16:30
Do I understand right? There is no way of knowing with prometheus if a VM on a HA cluster is sealed as long as some are unsealed. Does anyone find a solution to this? I really do not want to wait until (the whole cluster) vault is sealed before I get an alert. It defeats the purpose of HA setup where you can fix issues as they happen while keeping Vault unsealed. I just check and this seems the case for Enterprise Vault too

**Comment by LeoQuote** [comment] 2023-12-19 10:16
```
up{job="scrapeConfig/sa-common/vault"} > 0 unless on(instance) vault_core_unsealed
```
for warning alert (part of vault instance sealed)

```
sum(vault_core_unsealed) < 1 or absent(vault_core_unsealed)
```
for critical alert 

I think this is a problem needs to be solved, but currently I can only use this workaround

**Comment by cascadia-sati** [comment] 2024-01-09 13:41
Is this still an issue? I'm seeing `vault_core_unsealed` metrics even from standby nodes.

This is on an HA setup in K8s with the Vault Helm chart v0.25.0 and Vault v1.14.0.

When all are sealed:
```
$ for POD in {0..2}; do echo -n "vault-$POD: "; k get pod vault-$POD -oyaml | grep vault-active || echo; done
vault-0:     vault-active: "false"
vault-1:     vault-active: "false"
vault-2:     vault-active: "false"

$ for POD in {0..2}; do echo -n "vault-$POD: "; k exec -it vault-$POD -- /bin/sh -c "wget -O - localhost:8200/v1/sys/metrics?format=prometheus" | grep "^vault_core_unsealed" || echo; done
vault-0: vault_core_unsealed{cluster=""} 0
vault-1: vault_core_unsealed{cluster=""} 0
vault-2: vault_core_unsealed{cluster=""} 0
```

When all are unsealed:
```
$ for POD in {0..2}; do echo -n "vault-$POD: "; k get pod vault-$POD -oyaml | grep vault-active || echo; done
vault-0:     vault-active: "true"
vault-1:     vault-active: "false"
vault-2:     vault-active: "false"

$ for POD in {0..2}; do echo -n "vault-$POD: "; k exec -it vault-$POD -- /bin/sh -c "wget -O - localhost:8200/v1/sys/metrics?format=prometheus" | grep "^vault_core_unsealed" || echo; done
vault-0: vault_core_unsealed{cluster=""} 1
vault_core_unsealed{cluster="vault-cluster-7c97eef3"} 1
vault-1: vault_core_unsealed{cluster=""} 1
vault-2: vault_core_unsealed{cluster=""} 1
```

As you can see, there's another issue with duplicate metrics; one with a `cluster` tag and one without, so I have to use the `vault_core_unsealed{cluster=""}` query to filter that out.

I ran into another issue specific to the Vault Helm chart that caused metrics to disappear when all Vault pods are sealed, which we had to work around: https://github.com/hashicorp/vault-helm/issues/990

And I'm running into another problem that I'm about to file an issue for where specifically the `vault_core_unsealed` metric disappears after the `prometheus_retention_time` elapses, because apparently Vault doesn't periodically refresh the metric when it doesn't change.

**Comment by banks** [comment] 2024-07-24 14:23
Hi folks. Just checking thought older bugs. As @cascadia-sati mentioned, it would seem like this is not an issue any more, does anyone on this thread still see this problem?

As far as I can see this was actually fixed by https://github.com/hashicorp/vault/pull/12166 a couple of years ago - I've looked through the code and can confirm that now `runStandby` calls `metricsLoop` which is what outputs this.

Closing for now, please let us know if someone is still seeing this on a version of Vault after 1.13.0.

**Closed by banks** 2024-07-24 14:23 UTC
Labels: bug, core/metric, core/telemetry
