### ISSUE TITLE
max_ttl ignored on aws_ec2 roles?

### ISSUE THREAD

**Issue by maf23** [hashicorp/vault#1748] opened 2016-08-18 07:55 UTC
This is tested with 6.1rc3. I use aws_ec2 authentiation and have a role with a max_ttl of 1h:
```
# vault read /auth/aws-ec2/role/role_name
Key                      	Value
---                      	-----
allow_instance_migration 	false
bound_account_id         	REACTED
bound_ami_id             	
bound_iam_role_arn       	
disallow_reauthentication	false
max_ttl                  	3600
policies                 	[default xxx]
role_tag                 	vault_role
ttl                      	0
```

But when a machine authenticates with this role it gets a token like this:
```
# vault token-lookup
Key             	Value
---             	-----
accessor        	REDACTED
creation_time   	1471506447
creation_ttl    	2592000
display_name    	aws-ec2
explicit_max_ttl	0
id              	REDACTED
meta            	map[role_tag_max_ttl:0s ami_id:REDACTED instance_id:REDACTED region:us-east-1 role:role_name]
num_uses        	0
orphan          	true
path            	auth/aws-ec2/login
policies        	[default xxx]
renewable       	true
ttl             	2591996
```

I had expected the ttl to be 3600 since that is what the role specifies. The role tag does not specify any ttl.

Is this a bug or am I confused?

**Comment by maf23** [comment] 2016-08-18 08:32
This gets stranger, If I then do a token-renew the shown ttl jumps back to the expected value of 3600-elapsed time:
```
# vault token-renew
Key                        	Value
---                        	-----
token                      	REDACTED
token_accessor             	REDACTED
token_duration             	30m55s
token_renewable            	true
token_policies             	[default xxx]
token_meta_ami_id          	"REDACTED"
token_meta_instance_id     	"REDACTED"
token_meta_region          	"us-east-1"
token_meta_role            	"role_name"
token_meta_role_tag_max_ttl	"1h0m0s"
```

```
# vault token-lookup
Key              	Value
---              	-----
accessor         	REDACTED
creation_time    	1471507177
creation_ttl     	2592000
display_name     	aws-ec2
explicit_max_ttl 	0
id               	REDACTED
last_renewal_time	1471508922
meta             	map[region:us-east-1 role:role_name role_tag_max_ttl:1h0m0s ami_id:REACTED instance_id:REDACTED]
num_uses         	0
orphan           	true
path             	auth/aws-ec2/login
policies         	[default xxx]
renewable        	true
ttl              	1704
```

**Comment by jefferai** [comment] 2016-08-18 11:24
@maf23 The renewal behavior is actually correct; it's the initial behavior that's not right.

@vishalnayak I think the issue is that the role TTL is used blindly without checking whether it's zero. As a result core will assign it the default lease TTL, without the role max TTL being checked. Then at renewal time it works as expected because the role max TTL is being checked.

Although, I'd check whether the leaseextend call is doing the right thing using the Auth.TTL. It'll be capped by the role max, but shouldn't it be the role TTL instead?

**Closed** 2016-08-18 20:08 UTC
