### ISSUE TITLE
IAM authentication back-end?

### ISSUE THREAD

**Issue by sebastiang** [hashicorp/vault#406] opened 2015-07-07 15:00 UTC
If we launch an EC2 instance with an IAM role pre-baked, is there an authentication backend which would allow that IAM role to authenticate as a vault client?

**Comment by armon** [comment] 2015-07-07 16:15
@sebastiang I guess I'm not quite sure what this would look like. Clients would provide their AWS access key + secret to Vault and it would authenticate them using the AWS API somehow, but then how does that get mapped into authorization policies?

**Comment by sebastiang** [comment] 2015-07-07 16:22
Similar to the github backend, it would have to utilize information available from AWS/IAM to specify group names, etc. and be mapped to permissions. I don’t have a particular idea in mind, just seemed reasonable to rely on AWS for authentication as we do with github, since an EC2 instance can have an IAM role baked in, as opposed to generating a certificate, ferrying over a github key, making an app/password combo, etc.

**Comment by tellnes** [comment] 2015-07-15 16:32
This would be great.

**Comment by sethvargo** [comment] 2015-08-07 16:50
I think this is actually a duplicate of #307 upon further inspection. I'm going to close this as a dupe, but feel free to mention me if I misread something and I'll reopen it :smile:

**Comment by BRMatt** [comment] 2015-08-10 10:29
@sethvargo I think that this issue is asking for an IAM auth backend, whereas #307 is discussing a secret backend?

**Comment by st33v** [comment] 2015-09-09 19:06
This would really be helpful to me. huge +1

**Comment by nevir** [comment] 2015-09-15 22:05
This would remove much of the current pain when dealing with autoscaling groups +1

**Comment by igrayson** [comment] 2015-09-24 18:28
Is there a better place to vote for this feature? +1

**Comment by jefferai** [comment] 2015-09-25 00:38
There isn't. I'm tentatively scheduling this for the 0.4 milestone, but I want to make it clear that it may slip. It's a guess, not a promise. :-)

**Comment by johnrengelman** [comment] 2015-10-01 13:12
I was thinking you could do this using KMS by basically mapping the KMS key as the "appId" in Vault. Then the machine would need an IAM policy that allows access to the specified KMS key in order to perform the auth.

**Comment by fieldju** [comment] 2015-12-04 17:04
@johnrengelman, @igrayson, @nevir, @st33v, @BRMatt, @tellnes, @sebastiang 

There is a conversation about potentially design and implementation in https://github.com/hashicorp/vault/issues/805 your input would be great.

**Comment by wsh** [comment] 2016-03-31 20:38
Just another +1 for this. :smile:

**Comment by Gouthamve** [comment] 2016-05-28 07:02
Hi,

Whats the status of this after https://github.com/hashicorp/vault/pull/1300? Would you accept a PR if I do something similar to that but here we authenticate at an IAM level instead of at an instance level?

**Comment by jefferai** [comment] 2016-05-29 01:15
@Gouthamve How would this work exactly? EC2 provides characteristics that IAM does not and, if using IAM you could simply put values in KMS and map access to IAM roles. Then you can use any of several of the existing authentication backends.

**Comment by Gouthamve** [comment] 2016-05-29 08:32
So, while EC2 provides extra characteristics, a lot of people use only IAM roles successfully. We already use the IAM role baked while instance is launched to access relevant S3 buckets.

I think authenticating using only IAM roles and mapping IAM roles themselves to policies is a much cleaner way. Even users have IAM roles. This allows to have the same auth methodology for both users and instances. Finally, it will be an out of the box solutions for those using IAM already to restrict access to AWS resources.

**Comment by jefferai** [comment] 2016-05-29 11:50
@Gouthamve the issue isn't understanding the utility, it's the workflow. What is the workflow for using IAM roles for login? Every entity puts their IAM credentials on the wire and has enough privileges to introspect? Using which API endpoints? What's the workflow for renewals and reauth? Is there any scenario that doesn't just turn Vault into a giant repository of AWS credentials?

**Comment by ifuyivara** [comment] 2016-06-16 15:15
This feature was just merged into master here https://github.com/hashicorp/vault/pull/1522

**Comment by vishalnayak** [comment] 2016-06-16 17:46
Closing this as #1300 is now enhanced with #1522.
Please reopen if current features are not addressing the required workflows.

**Closed by vishalnayak** 2016-06-16 17:46 UTC
Labels: enhancement, secret/aws
