### ISSUE TITLE
Feature Request: Google Cloud Storage for storage backend

### ISSUE THREAD

**Issue by frodopwns** [hashicorp/vault#1305] opened 2016-04-06 17:26 UTC
This would be a nice alternative to the AWS offerings like S3 and dynamodb.

**Comment by jefferai** [comment] 2016-04-06 17:45
There are no plans to implement this by the Vault team, but like the S3 and Dynamo backends, we'll be happy to work with someone that wants to take on the task and submit a PR.

**Comment by frodopwns** [comment] 2016-04-06 20:26
Shouldn't this be left open so that a community member can know and see that this functionality is wanted and not yet underway?

**Comment by jefferai** [comment] 2016-04-06 20:56
@frodopwns I think a community member interested in such functionality will be able to either a) read this comment thread or b) look at the Vault docs and realize no such backend exists. :-)

**Comment by jefferai** [comment] 2016-11-03 16:19
Hi @tallpauley ,

I think it makes sense to follow Google's recommendations; requiring vars in Vault's config vs. env var is not any kind of dogma so long as it's documented. If it makes sense to you that the location could also be specified in the config file (user's choice) then great.

**Comment by rakyll** [comment] 2016-11-03 16:31
> I don't think there is an option in any of the go google storage libraries I've seen to just pass in a JSON string of the credentials

You can create a TokenSource from N and create a storage client with a custom TokenSource, see https://godoc.org/google.golang.org/api/option#WithTokenSource.


```
cfg, err := google.JWTConfigFromJSON(key) // key is the credentials JSON as []byte
if err != nil {
    log.Fatal(err)
}
client, err := storage.NewClient(ctx, option.WithTokenSource(cfg.TokenSource(ctx)))
```

**Comment by tallpauley** [comment] 2016-11-03 17:49
@jefferai thanks! Yeah, I suppose I could use Google's env variable for default application credentials, but I think it is probably good to abstract this in Vault config & env vars. @rakyll that's great, I was looking for just that option!

Ok, then I think it'd make sense if we had the following ways to pass in credentials:

1. env var: `GCP_SERVICE_ACCOUNT_FILE` (path to file)
2. config var: `conf['service_account_file']`
3. env var: `GCP_SERVICE_ACCOUNT_CREDENTIAL` (serialized JSON)

Precedence:
* 2 overrides 1 if specified (e.g. like with S3 backend, ENV overrides config option)
* 3 overrides both 1 & 2. Or, we could make it error when both are specified.

Any preference for mutual exclusion in the case of 3? override or error?

Also, any recommendations for the naming? I namespaced the other env variables like `GCP_STORAGE_BUCKET`, but `GCP_STORAGE_SERVICE_ACCOUNT_CREDENTIAL` seems a bit long. There is also the possibility that someone implements credential provisioning for GCP down the road and we may want to have the option of using separate credentials for storage & user provisioning. Thoughts?

Also, is "service account" even the best term to use?

**Comment by jefferai** [comment] 2016-11-07 18:48
Hi @tallpauley ,

In Vault, env vars always override values on disk. So the order should be 3, 1, 2, with 3 being preferred if both 3 and 1 are defined.

As for naming, `GOOGLE_APPLICATION_CREDENTIALS` is what Google uses and seems like the right thing for option 1. Maybe 3 would then be `GOOGLE_SERIALIZED_APPLICATION_CREDENTIALS`?

**Comment by tallpauley** [comment] 2016-11-08 01:52
Thanks @jefferai, I meant to say 1 overrides 2 if specified. That is also the order I had in mind.

I used the environment variables you suggested, sound good to me!

I ~~copied from s3.go~~ wrote a [GCP backend](https://github.com/tallpauley/vault/blob/gcp_storage/physical/gcp.go), and it passes the test... but not all the time -- maybe 90% of the time (that's not even consistent though). It *appears* that the methods of the google storage api or the wrapper library don't properly block to ensure the requested operation (put, delete) was completed.

If you run `make testacc TEST=./physical TESTARGS='-run GCPBackend'` several times, you might see the issue, you might not! To make failures happen more, I just run 10 test runs in sort-of parallel w/:
```
i=0; while [ $i -lt 10 ]; do make testacc TEST=./physical TESTARGS='-run GCPBackend' & i=$((i+1)); done
```

I also commented out the deferred teardown function in **gcp_test.go**, so I could examine the resulting state of the buckets, and I do **Printfs** in **gcp.go** to examine which of the 10 instances are failing when and why.


The last time I ran the "parallel" test I got these 5 test failures. In all the cases, the final state of the bucket matches exactly what it should have been when the assertion failed. Is there anything obvious I'm doing wrong [here](https://github.com/tallpauley/vault/blob/gcp_storage/physical/gcp.go)? If not I want to see if I can reproduce this problem with just the google storage library.

**Test**
```
export GOOGLE_PROJECT_ID=my_project_id
export export GOOGLE_APPLICATION_CREDENTIALS=service_account.json
i=0; while [ $i -lt 10 ]; do make testacc TEST=./physical TESTARGS='-run GCPBackend' & i=$((i+1)); done
```

**Test failures**
**1)**
- **console out:**
```
vault-gcp-testacc-4657920318338900191: listing results [foo]
--- FAIL: TestGCPBackend (5.46s)
	physical_test.go:201: bad: [foo]
```
- **final state of bucket (would have passed assertion):**
```
foo/
  zip
```

**2)**
- **console out:**
```
vault-gcp-testacc-4626358904153342684: listing results [bar nested1/]
--- FAIL: TestGCPBackend (3.93s)
	physical_test.go:173: there should be only one key left after deleting nested secret: [bar nested1/]
```
- **final state of bucket (would have passed assertion):**
```
foo/
  bar
```

**3)**
- **console out:**
```
vault-gcp-testacc-7108936922552470162: listing results [foo]
--- FAIL: TestGCPBackend (3.43s)
	physical_test.go:132: bad: [foo]
```
- **final state of bucket (would have passed assertion):**
```
foo
foo/
  bar
```

**4)**
- **console out:**
```
vault-gcp-testacc-3196730367424420466: listing results [foo]
--- FAIL: TestGCPBackend (2.34s)
	physical_test.go:96: bad: [foo]
```
- **final state of bucket (would have passed assertion):**
```
empty
```

**5)**
- **console out:**
```
vault-gcp-testacc-2242157198647564873: listing results [foo]
--- FAIL: TestGCPBackend (2.75s)
	physical_test.go:96: bad: [foo]
```
- **final state of bucket (would have passed assertion):**
```
empty
```

**Comment by jefferai** [comment] 2016-11-08 11:47
> It appears that the methods of the google storage api or the wrapper library don't properly block to ensure the requested operation (put, delete) was completed.

Have you checked carefully for consistency modes/options? This seems like a really odd behavior for the library to have but have no way to override.

**Comment by tallpauley** [comment] 2016-11-08 15:40
Consistency is exactly the word I was looking for but couldn't think of. Sure enough, list operations are only *eventually* consistent:
https://cloud.google.com/storage/docs/consistency

**Comment by jefferai** [comment] 2016-11-08 16:19
That's unfortunate...not sure what the right thing to do is, here. People might think Vault is having an issue when really it's GCP, but more importantly, I wonder if there are any parts of Vault that rely on the datastore being consistent. I wouldn't be surprised.

**Comment by tallpauley** [comment] 2016-11-08 17:44
Interestingly, [Google Storage's consistency model](https://cloud.google.com/storage/docs/consistency) is actually superior to [S3's](http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel):

#### S3 vs. Google Storage Consistency ####
| Operation | [S3](http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel) | [GCP](https://cloud.google.com/storage/docs/consistency)|
|-----------|----|-----|
|Read-after-write (new) |✓|✓|
|Read-after-write (update)  | | ✓ |
|Read-after-delete | |✓ |
|List-after-write | |  |
|List-after-delete | |  |

So, I'm surprised this issue hasn't come up for the S3 physical backend, at least during testing. Maybe 99.99% of time S3 list-after-write or list-after-delete is accurate? Or maybe the library used for the S3 physical backend can wait for consistency? I should take a closer look at the S3 library/api.

One thing I considered for Google storage backend is writing logic to:
- after write, continually check list until object shows up
- after delete, continually check list until object is gone

There is no guarantee for how long it will take to show up in the list, but since the test suite passes the vast majority of the time, it appears to be quick. A "wait for list consistency" option should probably ultimately be in the google storage library or API.

**Comment by tallpauley** [comment] 2016-11-09 19:17
So the weird thing about consistency for GCP is that even if you write and wait for the object to appear in the list, or delete and wait for the object to be removed from the list, subsequent lists may return different results. So I don't see any solution without Google providing a way to know when the list is consistent. Now, the GCP physical backend in vault could always store a cache of recently added or deleted objects, but this seems like a bad idea.

I'm assuming that list-after-write and list-after-delete are both valid sequences in Vault. If not, than I think the GCP backend will work fine.

This is maybe a bit old, but also helpful:
https://github.com/andrewgaul/are-we-consistent-yet

**Comment by jefferai** [comment] 2016-11-17 18:32
Closing in favor of #2099

**Closed by jefferai** 2016-11-17 18:32 UTC
