### ISSUE TITLE
/sys/audit/:path endpoint requires reading the parent endpoint for read operations

### ISSUE THREAD

**Issue by CVTJNII** [hashicorp/vault#3150] opened 2017-08-11 23:16 UTC
Please create a read operation for /sys/audit/:path. Currently to read the settings of an audit backend a library must read /sys/audit and select the :path/ key in the returned hash. Implementing a data model where all CRUD operations are on the same path will make client implementations more consistent and easier to maintain.  Thank you.

**Comment by catsby** [comment] 2019-11-05 21:45
Closing as a duplicate of https://github.com/hashicorp/vault/issues/3148

**Closed by catsby** 2019-11-05 21:45 UTC
