### ISSUE TITLE
core: failed to construct ACL: error="failed to get policy: failed to read policy: decryption failed: cipher: message authentication failed"

### ISSUE THREAD

**Issue by wneessen** [hashicorp/vault#8760] opened 2020-04-17 16:16 UTC
**Describe the bug**
This is a continuation of https://github.com/hashicorp/vault/issues/7214. While doing further testing I narrowed this down to being unrelated to the clustering (as I first assumed) but rather seems to be related to the policy name handling. It looks like, that if I name my policy "/roles/sys/superuser" the error occurs (reproducable). If I name my policy just "test", everything will work as expected.

**To Reproduce**
* Install a fresh vault instance (local storage is fine)
* Create an ACL policy called "/roles/sys/superuser" and enter the following: https://gist.github.com/wneessen/3e1d7fdb794dab9b5684c872d78eba91
* Create an "userpass" Auth method
* Create a new user and assign the "/roles/sys/superuser" and "default" policy
* Login with your new user and everything should be fine. You should basically have "superuser" access
* Restart your Vault instance
* Try to login with your user. The login will succeed, but you will not have no "superuser" access anymore. The debug log will show the following:
```
2020-04-17T14:34:51.418Z [ERROR] core: failed to construct ACL: error="failed to get policy: failed to read policy: decryption failed: cipher: message authentication failed"
2020-04-17T14:34:51.545Z [ERROR] core: failed to construct ACL: error="failed to get policy: failed to read policy: decryption failed: cipher: message authentication failed"
2020-04-17T14:34:51.545Z [ERROR] core: failed to construct ACL: error="failed to get policy: failed to read policy: decryption failed: cipher: message authentication failed"
2020-04-17T14:34:53.705Z [ERROR] core: failed to construct ACL: error="failed to get policy: failed to read policy: decryption failed: cipher: message authentication failed"
2020-04-17T14:34:53.705Z [ERROR] core: failed to construct ACL: error="failed to get policy: failed to read policy: decryption failed: cipher: message authentication failed"
2020-04-17T14:34:54.381Z [ERROR] core: failed to construct ACL: error="failed to get policy: failed to read policy: decryption failed: cipher: message authentication failed"
```
* Now do the same, but call your policy "test" instead of "/roles/sys/superuser" and everything will be working as expected.

**Expected behavior**
Using the "/roles/sys/superuser" should provide the expected access even after restarting Vault or Vault should present an error when creating the policy, that the name is not allowed.

**Environment:**
* Vault Server Version: v1.3.4
* Vault CLI Version: v1.3.4
* Server Operating System/Architecture: Tested on FBSD 11, 12 and latest Arch Linux (using 5.6.3.a-1-hardened Kernel)

Vault server configuration file(s):

```hcl
listener "tcp" {
  address          = "10.0.32.31:8200"
#  cluster_address = "10.0.32.31:8201"
  tls_cert_file = "/etc/vault.d/vault1.cgn.domain.com.crt"
  tls_key_file = "/etc/vault.d/vault1.cgn.domain.com.key"
  tls_ca_file = "/etc/vault.d/cleverCA_domainCA.cabundle"
}

listener "tcp" {
  address          = "127.0.0.1:8200"
  tls_cert_file = "/etc/vault.d/vault1.cgn.domain.com.crt"
  tls_key_file = "/etc/vault.d/vault1.cgn.domain.com.key"
  tls_ca_file = "/etc/vault.d/domainCA_ServerCA.cabundle"
}

storage "file" {
    path = "/var/lib/vault/vault_local"
}

api_addr = "https://vault1.cgn.domain.com:8200"
ui = 1

```

**Comment by briankassouf** [comment] 2020-04-17 18:29
Hi @wneessen Thanks for this report too! I believe the issue is that the policy you're assigning to the userpass backend starts with a `/`. We will investigate ways to improve this UX.

**Comment by wneessen** [comment] 2020-04-20 07:59
Hi @briankassouf,

I can confirm, that removing the leading ```/``` does indead work and fixes the problem for me. Thanks for the help!

**Closed** 2021-04-27 20:58 UTC
Labels: bug, core/policy
